### ISSUE TITLE
STAR-Fusion does not install resource utilities

### ISSUE THREAD

**Issue by yhoogstrate** [bioconda/bioconda-recipes#1005]
STAR-Fusion does not install additional tools required to generate custom databases, like `prep_genome_lib.pl` (https://github.com/STAR-Fusion/STAR-Fusion/wiki#data-resources-required).

This prevents the user from using custom reference builds and restricts the user to reference builds GRCh37/hg19 and hg38

**Comment by johanneskoester** [comment]
Good point, thanks for mentioning!
