### ISSUE TITLE
retire osx-whitelist?

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#1012]
Currently the default is to not build for OSX unless it is explicitly put on `osx-whitelist`. It seems like it would be cleaner to build everything for OSX by default, and failing recipes can then use 
```
build:
  skip: True  # [osx]
```
in the meta.yaml. This way all information about what platforms the recipe runs on is contained in the meta.yaml (rather than having to cross-reference with osx-whitelist). I'm certainly guilty of forgetting to add things to the whitelist. If this happens to other people too, building for OSX by default should increase the availability of OSX packages in bioconda. 

Setting up the build system to do this shouldn't be that tricky. The hard part will be in figuring out which recipes should be retrofitted to have `skip: True #[osx]`.

**Comment by bgruening** [comment]
:+1: for a osx-blacklist. But I suspect than many recipes are not building anymore because the tarball is missing. I have this problem in my add-zlib branch :(

**Comment by daler** [comment]
Do you mean tarballs for bioconductor packages? Or more generally?

**Comment by bgruening** [comment]
Mostly bioc packages. I'm working on a solution for this to fix it once and for all, just need time to write it down and open an own issue for it.

**Comment by daler** [comment]
For the most recent bioc release (month or two ago?) I did a round converting as many to bioaRchive as possible, but many didn't have a tarball there yet. I bet a lot of those have had an incremental release in the meantime, wiping the previous version on the bioc servers.

I feel your pain. To be continued on another issue perhaps . . . but like you say, it still needs to be resolved before removing osx-whitelist.

**Comment by johanneskoester** [comment]
Good idea. I totally support the removal of osx-whitelist. When I introduced it, I wasn't aware of the skip instruction.

**Comment by kyleabeauchamp** [comment]
+1

**Comment by bgruening** [comment]
@daler what do you think about this start? https://github.com/bioconda/bioconda-recipes/compare/kill_osx_whitelist?expand=1

I can work on this further. The idea is
1. add `skip:True` to every file that is currently not on the whitelist
2. add them to the whitelist
3. if all tools are on the whitelist, drop the whitelist

What do you think?

**Comment by daler** [comment]
I think this is a good plan. The disadvantage is that it does not find recipes that work on OSX but were never added to the whitelist by recipe authors. To address this I have an OSX development machine and was starting down the more painful route of deleting osx-whitelist first, and then only adding the `skip: True` to a recipe when it failed to build.

I can continue with this to decide which recipes can eventually have their `skip:True #[osx]` removed, but in the meantime your plan should work well to get rid of the whitelist moving forward.

**Comment by bgruening** [comment]
@daler yes, this would be the next step. As soon as we have removed the list we can go to all ucsc packages or R-packages and remove the osx-skip tag. We could even during our reviews ask to not use the os-x tag in new packages.

**Comment by bgruening** [comment]
@daler feel free to work on this branch as well. I'm just a little bit concerned about build times at some point and that travis will timeout. So maybe we merge this in chunks.

**Comment by daler** [comment]
Sure thing. I may not have time to chip away at this in the near future, so don't wait for me . . .

I agree, merging in chunks is the way to go.

**Comment by bgruening** [comment]
@daler given the tests are passing. Feel free to merge it :)

**Comment by daler** [comment]
Merged. Next step is to try removing `osx-whitelist` and adjusting [`travis-run.sh`](https://github.com/bioconda/bioconda-recipes/blob/master/scripts/travis-run.sh#L13), is that correct?

@bioconda/all, please see #1081 for notes on the intended changes with respect to OSX builds.

**Comment by bgruening** [comment]
@daler I have a few more chunks like this one. After this I would like to remove the osx-whitelist and adjust the travis-run.sh yes. If you want to do this feel free to do so :)

**Comment by kyleabeauchamp** [comment]
I noticed that samtools was previously on the whitelist, but now has a whitelist section in its yaml file.  I think this is either a bug, or we're temporarily in an "intermediate state".

**Comment by kyleabeauchamp** [comment]
Meant to say "skip", not whitelist.

**Comment by daler** [comment]
@kyleabeauchamp I think intermediate state, but certainly a bug as it stands.

@bgruening, I may have misunderstood. I thought the goal was to add `skip: True` to packages that were NOT on the original `osx-whitelist`. It looks like in some cases the opposite happened. The following uses a version of osx-whitelist that is before the first kill-osx-whitelist merge and checks against recipes that have `skip: True` defined in the current master (9a562a745).

```bash
# 989ba4 looks like it was just before the first kill-osx merge
wget -O - https://raw.githubusercontent.com/bioconda/bioconda-recipes/989ba45d8cd72a8f323530f5e3de553cfd10e147/osx-whitelist.txt \
  | sort | uniq > tmp.whitelist

# hopefully the regex is good enough to catch most variations
egrep -lR 'skip:\s*True\s*#\s*\[\s*osx'  recipes/ \
  | awk -F '/' '{print $2}' \
  | sort | uniq > skipped

# anything that is in osx-whitelist *and* is skipped for OSX is problematic
comm -12 tmp.whitelist skipped
```

This shows the 253 cases, including samtools, that used to be fine on OSX but are now skipped. These should not be skipped, right?

**Comment by johanneskoester** [comment]
Indeed, the logic should be inverted I guess.

**Comment by bgruening** [comment]
Kind of bug and intermediate state. I'm was side tracked with wanted to much at once and got stuck with broken links :(
I will have a final fix hopefully in a few hours, which reverts the wrong annotations.

**Comment by bgruening** [comment]
@daler @johanneskoester @kyleabeauchamp I would appreciate a review: https://github.com/bioconda/bioconda-recipes/pull/1105

Thanks a lot!
Bjoern
