### ISSUE TITLE
noarch

### ISSUE THREAD

**Issue by notestaff** [bioconda/bioconda-recipes#10146]
The current guidelines caution not to use noarch:
https://bioconda.github.io/guidelines.html
But not using it causes a lint error.
Are the guidelines outdated?  @bgruening @johanneskoester

**Comment by bgruening** [comment]
@notestaff use it, we need to update our docs :)

**Comment by unode** [comment]
This also came up in #10125 . Updating accordingly.

**Comment by epruesse** [comment]
Got a PR to fix docs here bioconda/bioconda.github.io#21

**Comment by epruesse** [comment]
Fixed
