### ISSUE TITLE
Making urls sustainable

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#1015]
To fix old recipes and to be prepared to rebuild recipes, for example to include zlib or extend builds for OS-X the `url` need to be sustainable.

The Galaxy community has developed several solutions to tackle this problem in several ways.
For example: 

[Bioarchive](https://bioarchive.galaxyproject.org/#/pkg/Biobase/): This one traverses the bioc svn repo and recreates all tarballs that are needed. Some scripts from @daler are using this service already.

[https://github.com/galaxyproject/cargo-port](Cargo-Port): Cargo-Port is a simple tsv file which everyone can extend. After checking the checksum and merging the PR the file will be downloaded, verified and stored.

Both services are storing data in one central place: https://depot.galaxyproject.org

I have talked to the Galaxy team, which is maintaining this storage server, and we agreed that it would be great if bioconda could directly use this storag-backend to make a backup of all needed files.

My idea would be to add a new travis-hook to:
* automatically download the specified URL
* verify it's integrity
* upload it to https://depot.galaxyproject.org
* add a new link to the recipe and commit it

The new recipe should look like this:

```
fn: limma_3.26.7.tar.gz
url:
  - http://bioconductor.org/packages/release/bioc/src/contrib/limma_3.26.7.tar.gz
  - https://depot.galaxyproject.org/bioc/src/limma_3.26.7.tar.gz
```

Problems that needs to be solved.
 * We currently do not have a nice way to fix old recipes that are hidden in git. Here the proposed solution of subdirectories would help a lot.
* It's not guaranteed that we will find every old tarball - bioarchive could help here at least for bioc

Any comments more then welcome!

xref: https://github.com/bioconda/bioconda-recipes/issues/1012

**Comment by daler** [comment]
cargo-port looks fantastic, please extend our thanks to the Galaxy team for storage.

Just to clarify your proposed solution -- I would write this example limma recipe using only the currently-working bioconductor url; upon committing (more specifically, upon merging into master) the travis hook 
would add the second URL as well? Does conda support multiple urls like that?

**Comment by bgruening** [comment]
@daler exactly. I thought that conda support multiple URL's I have seen this in wild. Not sure if it's working. If this is not the case we need to replace the given URL.

**Comment by johanneskoester** [comment]
That sounds great. The more urls there are in the recipe to download a tarball, the better. Apart from that, I wonder if we should extend our guidelines to encourage people to use git release tags or github release archives if available, because they should be equally sustainable as the galaxy resources, right? I think it is not even possible to delete accidentally.

**Comment by bgruening** [comment]
@johanneskoester you can change tags and releases in github as you want. I would discourage the use of git_url because we can not easily fetch this. Instead you could provide a `url:` to a github release. This has the advantage of both cases. We can have a github release and we can download the tarball and store if on the Galaxy server.

Just to give a little bit more motivation. This one is currently not working: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-dexseq/meta.yaml

This means I'm now not able to build this recipe for OS-X :( ... with older versions it is even more worse.

So my proposal is:
 * encourage users to use `checksums` and downloadable URLs
 * write a script that (during build-time) uploads the tarball from `url:` to the Galaxy store
 * changes the meta.yaml file and add the additional URL from Galaxy

What do you think?

**Comment by johanneskoester** [comment]
Sounds like a good plan! What I meant is that I don't think people will accidentally delete git tags or github releases. But I agree, since there is the possibility to delete them, we should not rely on it.

**Comment by bgruening** [comment]
We have now 211 packages mirrored on https://depot.galaxyproject.org/software.
We still need a mechanism to get these URLs back into the recipe and check that this service is working over time. But its a great step forward - closing this issue.
