### ISSUE TITLE
Circle CI Build timeouts

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#10207]
Hi Team Bioconda,

I'm experiencing a build timeout error on Circle Ci with PR #10177. This is a small, simple build (pure C lib with few dependencies). There are three builds happening in the PR (previous versions of the software) and two run/pass quickly and one hangs for >5hours, triggering the timeout. Any idea from @bioconda/core what might be happening here?

Thanks,
zach cp

**Comment by dpryan79** [comment]
This usually happens when a program sits there waiting for input. I've run into a few programs that act strangely in the dockerized environment, perhaps some versions of fasttree are like that.

**Comment by dpryan79** [comment]
BTW, you can usually trigger this locally

**Comment by zachcp** [comment]
thanks @dpryan79 .  

Your comments inspired me to find what I think is the problem. It seems that  one of the tests in the hanging version pipes to `cat` where the others use a `--help` flag.  So its probably just that that particular test does not return a return code. 

I've patched it and am rebuilding now.

**Comment by zachcp** [comment]
build passed! thanks again @dpryan79
