### ISSUE TITLE
got older version of GROMACS when installed via bioconda?

### ISSUE THREAD

**Issue by mrshirts** [bioconda/bioconda-recipes#10211]
I seem to be getting the gromacs 4.6.5 version when installing via conda, even though he recipe has been updated to 2018 (and now even 2018.2).  I can't seem to find how to pull down more recent versions using only conda (needed for a workflow).  

Specifically, `conda install gromacs` gives me version 4.6.5, `conda update gromacs` says ` All requested packages already installed`, and `conda install gromacs=2018` or 2018.2 says "PackagesNotFoundError: The following packages are not available from current channels"

I first added bioconda as a channel 2 days ago.

Is there an issue with the recipe, at https://github.com/bioconda/bioconda-recipes/tree/master/recipes/gromacs, or am I doing something wrong?

**Comment by kyleabeauchamp** [comment]
The newer packages are definitely online: https://anaconda.org/bioconda/gromacs/files

**Comment by mrshirts** [comment]
Conda config --show gives:

channels:
  - bioconda
  - conda-forge
  - http://conda.anaconda.org/omnia
  - defaults

So I think bioconda is highest.

**Comment by bgruening** [comment]
I get `gromacs:      2018.2-h470a237_0 bioconda`

with:
```
channels:
  - bioconda
  - conda-forge
  - defaults
```
Which conda version are you using?

Mine is:

```
(smithy) bag@bag:~/projects/code/r-base-feedstock$ conda --version
conda 4.5.8
```

**Comment by kyleabeauchamp** [comment]
Could it be that we have something in `omnia` that's overwriting a necessary upstream dependency from defaults?

**Comment by kyleabeauchamp** [comment]
And blocking the latest gromacs?

**Comment by mrshirts** [comment]
Conda version is conda 4.5.9 (updated today while trying to resolve this - it was 4.5.8 when I failed yesterday).

**Comment by mrshirts** [comment]
I removed omnia, created a new conda environment.  Has 
channels:
  - bioconda
  - conda-forge
  - defaults

Went into the new environment, tried to install gromacs, and got:

The following NEW packages will be INSTALLED:
    gromacs: 4.6.5-0 bioconda

Suggestions for what I need to start over on?

**Comment by bgruening** [comment]
Is this under Linux? I just tested it under Linux.

**Comment by mrshirts** [comment]
Good point, this is under Mac OS X, which is theory should also be supported by bioconda (and GROMACS itself compiles fine on OS X).

**Comment by bgruening** [comment]
@mrshirts yes this explains it. There is no newer OSX version in bioconda. For some reason OSX is skiped. If you like please help us to build it for OSX as well. I do not have a MAC and can not help here much.

**Comment by mrshirts** [comment]
Can you point to instructions on how to do that correctly?

**Comment by kyleabeauchamp** [comment]
I think you'll just need to open a PR that removes the `skip` line in the gromacs recipe: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gromacs/meta.yaml#L12

Then, you'll need to debug any compiler issues that you run into.  I imagine the previous author skipped OSX because they encountered some build issues on OSX, but maybe it will just work out of the box for you.  

There are more instructions here: https://bioconda.github.io/contributing.html
