### ISSUE TITLE
Issues with static htslib not finding libdeflate

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#10238]
Dear @bioconda/lib and fellow @bioconda/core members,
I am currently trying to update the htslib pinning in the bulk branch. However, for some recipes (e.g. gqt), libdeflate seemingly [cannot be found](https://circleci.com/gh/bioconda/bioconda-recipes/20700?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) when using htslib.a, although it is a correctly pinned dependency of htslib.

Does anybody have an idea?

Best,
Johannes

**Comment by johanneskoester** [comment]
The issue seems to come up here as well: https://github.com/samtools/htslib/issues/688

Lets see if there is a solution already...

**Comment by johanneskoester** [comment]
Not sure how to proceed to be honest. @kyleabeauchamp since you made it work with samtools, can you help us with gqt and the others that fail as well?

**Comment by dpryan79** [comment]
Try adding `-ldeflate` to the compiler flags.

**Comment by kyleabeauchamp** [comment]
Yeah, I suppose adding a -ldeflate to those other recipes would be one fix.   Is it possible to force them to use a shared link mode rather than static?  I wonder if that too could be a fix.

**Comment by epruesse** [comment]
The code has to come from somewhere. For dynamic libs, dynamic linker (ld.so) resolves requisite libs recursively at load time. For static libs, no such mechanism exists (well, libtool can with .la files, but that’s complicated for us bc of absolute paths in those files, see conda forge discussion on topic). So either create dynamic htslib and use that, or add deflate to dependent recipes,  either dynamic (-ldeflate) or static (libdeflate.a).

Technically, deflate code could be added to htslib.a, but then you get into trouble if someone downstream tries to add that code again. E.g. because accessing deflate directly as well.

**Comment by kyleabeauchamp** [comment]
AFAIK htslib is shipping both dynamic and static files:

```
ls *hts*

libhts.a  libhts.so  libhts.so.1.9  libhts.so.2
```

```
 ls *hts*
libhts.1.9.dylib libhts.2.dylib   libhts.a         libhts.dylib
```

**Comment by epruesse** [comment]
Then I don't see why we should use the static library at all. 

Does someone have a case where it is needed? IIRC conda-forge drops `.a` files usually, while the mainstream distros only include them in `-dev` packages. We could remove it from the htslib package to make sure it's all symmetric.

There are some minor performance benefits to using static libraries, but mostly it's about building binaries that are easier to distribute, which is an issue we don't have. For backwards compatibility purposes we can always just use pinning. 

Statically linked applications load a little faster as there is no dynamic linker involved, which can add up for larger applications needing a lot of libraries. Also, the compiler/linker can theoretically do some optimizations knowing where code will reside in memory relative to the calling code. People who are gentoo enough to care about that last percent of performance should compile everything for their CPU anyway, though.

**Comment by kyleabeauchamp** [comment]
It appears that we would need to edit our Makefile patch for gtq to force it to use SO files rather than .a files:

https://github.com/ryanlayer/gqt/blob/master/src/Makefile#L77

**Comment by johanneskoester** [comment]
Thanks guys! For now, I solved id with adding `-ldeflate`.

**Comment by bdferris642** [comment]
Hello. I am having similar issues. @johanneskoester (or others) would you mind being more specific about what adding -ldeflate to the compiler flags entails?
