### ISSUE TITLE
Having trouble getting started

### ISSUE THREAD

**Issue by cdunn2001** [bioconda/bioconda-recipes#10264]
I need to get just one build working ... of *anything*. I have a miniconda activated and docker installed on OSX. `docker info` works fine. I have modified a recipe in my local just to get something to build (not yet committed).
```
bioconda-utils build recipes config.yml --docker --mulled-test --git-range master

FILTER: not building recipe recipes/samtools/1.6 because the same number of builds are in channel(s) and it is not forced.
```

So I tried another, and then I tried modifying the version number, thinking that might "force" the build.
```
BUILD FAILED: the built package /tmp/miniconda/miniconda/conda-bld/osx-64/daligner-7.0p2-h470a237_2.tar.bz2 cannot be found
```
```diff
--- recipes/daligner/meta.yaml
+++ recipes/daligner/meta.yaml
@@ -1,9 +1,10 @@
+
 package:
   name: daligner
-  version: "1.0p2"
+  version: "7.0p2"

 build:
-  number: 1
+  number: 2
```
Any ideas what I'm doing wrong?

**Comment by cdunn2001** [comment]
Now I've tried `circleci build`, and I hit a very different error:
```
$ circleci build

====>> Spin up Environment
Build-agent version 0.0.5895-01cdb92 (2018-05-29T20:07:10+0000)
Starting container bioconda/bioconda-utils-build-env
  using image bioconda/bioconda-utils-build-env@sha256:15ee49e7dea59105b90a89660b385b0367eca5a533a2816ab9984d545d6c45dd

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1533496688
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=master
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=https://github.com/bio-nim/bioconda-recipes
  CIRCLE_SHA1=74b4e4fabb57ac401041fc3b0ee2455ef9560a53
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1533496688
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/sh
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
cp: cannot open `/tmp/_circleci_local_build_repo/./nohup.out' for reading: Permission denied
```

**Comment by cdunn2001** [comment]
> In general you need to either bump the build number or change the version (if you change the version, please change the build number back to 0).

But that doesn't explain the first crash, does it?

> Regarding the circleci error, you have to chmod a+rX everything in the path to the recipe (and the recipe directory).

Which directory? The `recipes/daligner/` directory is under **git** control and seems to have sufficient access. The `/tmp/_circleci_local_build_repo/` directory does not exist anymore. It's not created by the recipe. The `mkdir` command above is not part of the recipe. I don't have any idea what creates `nohup.out` or where I can `chmod` it.

Can you be more specific? And not that I am writing a new recipe. I'm only trying to *test* a recipe, any recipe. This one happens to be simple -- no dependencies.

**Comment by dpryan79** [comment]
The first one isn't a crash, only recipes that need to be built actually are. Whether a recipe needs to be built depends on the version and build number.

Regarding the circleci error, `/tmp/_circleci_local_build_repo` is the `bioconda-recipes` directory inside the docker container used for testing. So its entirety needs to be world readable. Further, you need to ensure that everything starting with `/` is readable up to it or the user inside the docker container may not have sufficient permissions to actually `cd` into it. 

If you do that then testing should work. I myself prefer to just directly use `bioconda-utils build`, which is what circleci ends up calling.

**Comment by cdunn2001** [comment]
> The first one isn't a crash, only recipes that need to be built actually are. Whether a recipe needs to be built depends on the version and build number.

Maybe I should have deleted the first few sentences. I got around *that* problem by modifying the `meta.yaml` file just as you later suggested, but then I hit the following crash:

    18:13:22 BIOCONDA ERROR BUILD FAILED: the built package /tmp/miniconda/miniconda/conda-bld/osx-64/daligner-7.0-h470a237_0.tar.bz2 cannot be found

So I switched to CircleCI.

> /tmp/_circleci_local_build_repo is the bioconda-recipes directory inside the docker container used for testing. So its entirety needs to be world readable. 

Do I need to learn more about Docker in order to change the permissions within the container? I was hoping to save a Docker deep-dive until later, but if that's the only problem, I can look into that next.

> I myself prefer to just directly use bioconda-utils build, which is what circleci ends up calling.

I don't understand. That's what I tried first, but it crashed, as shown above. Do you mean sans `--docker`? I thought Docker was *required* for testing. If I drop `--docker`, where will the built binaries end up? Somewhere in my current **conda** directory?

... Well, sans `--docker` seems to have built, but the "mulled-test" failed oddly.

https://gist.github.com/cdunn2001/9d9c1c5fed932445abc5780be38f0cc2
```
Passing program arguments as a string may be a security hazard if combined with untrusted input
failed MSpanList_Insert 0x878000 0xce7669b0ab44 0x0 0x0
fatal error: MSpanList_Insert
```
The "test" is exactly the part I need to test locally. This is not an error in the programs themselves, and they are static binaries. Can you at least tell me where the built binaries ended up? I'm afraid they went in the tmpdir, which was then deleted.

**Comment by cdunn2001** [comment]
When I re-run circleci and watch docker:
```
$ docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
```
The 2 stopped are separate. So circleci seems to create and run 2 new containers. How would I change the permissions on directories within them, when they are not currently running?

To be clear, this is the simplest non-trivial bioconda recipe I could fine. It's pure C code with zero dependencies. The "test" does nothing but run `--help` on each static binary. And the recipe already exists. I am only trying to test it locally so I know what I'm doing for future recipes. Any help would be appreciated.

**Comment by dpryan79** [comment]
You just change the permissions on your local directories, they're mapped into the docker containers.

**Comment by pb-cdunn** [comment]
> You just change the permissions on your local directories, they're mapped into the docker containers.

That directory does not exist and it's not created by my recipe. It's created by docker/circle/bioconda-utils, apparently. Are you saying the recipe itself should assume the directory has been created and change the permissions.? If so, wouldn't _all_ recipes need to do that?

**Comment by dpryan79** [comment]
That directory *is* the bioconda github repository on your computer. It's not created in the docker container, it is literally the directory on your computer with a different name.

**Comment by cdunn2001** [comment]
I still don't understand what you're suggesting. I tried this:
```
$ pwd
/Users/cdunn2001/repo/gh/bioconda-recipes

circleci build
```
With this change:
```diff
diff --git recipes/daligner/build.sh recipes/daligner/build.sh
index 1b7589dc3..1f07bfe11 100644
--- recipes/daligner/build.sh
+++ recipes/daligner/build.sh
@@ -1,5 +1,7 @@
 #!/bin/bash

+chmod -R a+xr /tmp/_circleci_local_build_repo
+
 mkdir -p $PREFIX/bin
 make
```

And I still got this:
```
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
cp: cannot open `/tmp/_circleci_local_build_repo/./nohup.out' for reading: Permission denied
```

What else can I try?

**Comment by dpryan79** [comment]
cd /Users/cdunn2001/repo/gh/bioconda-recipes
    chmod -R a+rX
    chmod a+rx /Users/cdunn2001/repo/gh
    chmod a+rx /Users/cdunn2001/repo
    chmod a+rx /Users/cdunn2001/

**Comment by cdunn2001** [comment]
I ran the following before your reply:
```
$ ls -ld .
drwxr-xr-x  25 cdunn2001  staff  800 Aug  6 10:44 .
bioconda-recipes:master$ ls -ld recipes/
drwxr-xr-x  3751 cdunn2001  staff  120032 Aug  4 23:40 recipes/
bioconda-recipes:master$ ls -ld recipes/daligner/
drwxr-xr-x  4 cdunn2001  staff  128 Aug  6 10:44 recipes/daligner/
$ umask
0022
```
I already have `a+rx` permissions everywhere!

**Comment by cdunn2001** [comment]
Ugh! I think I found the problem:
```
$ ls -l /Users/cdunn2001/repo/gh/bioconda-recipes/nohup.out
-rw-------  1 root  staff  54 Aug  5 00:10 nohup.out
```
I think docker created that when I started it.

You were *extremely* helpful though. I was not understanding where to look.

**Comment by cdunn2001** [comment]
Ok, now I'm back to the very first problem.

```
$ circleci build
...
.circleci/setup.sh
remote: Counting objects: 120, done.
remote: Total 120 (delta 58), reused 58 (delta 58), pack-reused 62
Receiving objects: 100% (120/120), 157.24 KiB | 2.76 MiB/s, done.
Resolving deltas: 100% (59/59), completed with 24 local objects.
From https://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__rsFJF6ejQe/master
fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository
...
17:37:27 BIOCONDA INFO No recipe modified according to git, exiting.
Success!
```

Does `circleci build` have a way to specify using my local repo? (`--skip-checkout` defaults to `true`)

**Comment by dpryan79** [comment]
That's annoying. Another reason to directly use `bioconda-utils build` (run `./bootstrap.py`).

**Comment by cdunn2001** [comment]
```
12:49:48 BIOCONDA ERROR COMMAND FAILED: mulled-build build-and-test daligner=7.0--h470a237_0 -n biocontainers --test daligner 2>&1 | grep Usage && LAsort 2>&1 | grep Usage && LAmerge 2>&1 | grep Usage && LAshow 2>&1 | grep Usage && LAcat 2>&1 | grep Usage && LAsplit 2>&1 | grep Usage && LAcheck 2>&1 | grep Usage && HPC.daligner 2>&1 | grep Usage --extra-channels file:///tmp/miniconda/miniconda/conda-bld,conda-forge,defaults --involucro-path /tmp/miniconda/miniconda/bin/involucro
12:49:48 BIOCONDA ERROR STDOUT+STDERR:
/tmp/miniconda/miniconda/bin/involucro -v=2 -f /tmp/miniconda/miniconda/lib/python3.6/site-packages/galaxy/tools/deps/mulled/invfile.lua -set CHANNELS='bioconda,file:///tmp/miniconda/miniconda/conda-bld,conda-forge,defaults' -set TEST='daligner 2>&1 | grep Usage && LAsort 2>&1 | grep Usage && LAmerge 2>&1 | grep Usage && LAshow 2>&1 | grep Usage && LAcat 2>&1 | grep Usage && LAsplit 2>&1 | grep Usage && LAcheck 2>&1 | grep Usage && HPC.daligner 2>&1 | grep Usage' -set TARGETS='daligner=7.0=h470a237_0' -set REPO='quay.io/biocontainers/daligner:7.0--h470a237_0' -set BINDS='build/dist:/usr/local/,/tmp/miniconda/miniconda/conda-bld:/tmp/miniconda/miniconda/conda-bld' -set CONDA_IMAGE='continuumio/miniconda3:4.3.27' build-and-test
.Passing program arguments as a string may be a security hazard if combined with untrusted input
failed MSpanList_Insert 0x878000 0xde61c5c62994 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x584810, 0x10)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbfed90 sp=0x7ffeefbfed78
runtime.(*mSpanList).insert(0x7bd888, 0x878000)
```
That seems to be a real bug in miniconda's `involucro`.

**Comment by dpryan79** [comment]
Could be, I can't help with that.

**Comment by cdunn2001** [comment]
> That's annoying. Another reason to directly use bioconda-utils build.

The following worked:
```
$ bioconda-utils build --packages daligner --testonly recipes/ config.yml
```
But only because the following *already* exists:

    /tmp/miniconda/miniconda/conda-bld/osx-64/daligner-7.0-h470a237_0.tar.bz2

So how do I *build and test* without using `--mulled-test`, which seems to have its own bug on OSX....

... Aha. I've finally found a combination which works!

    bioconda-utils build --packages=daligner recipes/ config.yml
```
13:09:40 BIOCONDA INFO BUILD SUCCESS daligner-7.0-h470a237_0.tar.bz2
13:09:42 BIOCONDA INFO BUILD SUMMARY: successfully built 1 of 1 recipes
```
Then I can run `--test-only`. I think `--mulled-test` is buggy, but this thread is already too long. Thanks for all your help, @dpryan79!

**Comment by cdunn2001** [comment]
If I bump the version, it builds, so I don't understand what `--force` is far.

At any rate, I am completely unable to make anything happen for `hts-nim-lib`:
```
$ bioconda-utils build --packages=hts-nim-lib recipes/ config.yml --force
...
13:25:25 BIOCONDA INFO Nothing to be done.
```
This is the real goal. I need to build `hts-nim-lib` locally. So now what I am doing wrong?

**Comment by dpryan79** [comment]
You might need `--force` before `--package daligner hts-nim-lib`, since that can take multiple options. Make sure the recipe isn't in the blacklist (just comment it out if it is).

**Comment by cdunn2001** [comment]
```
build-fail-blacklist:recipes/hts-nim-tools
```
But removing that line didn't help.
```
$ bioconda-utils build --force --packages=hts-nim-lib recipes/ config.yml
14:04:03 BIOCONDA INFO Nothing to be done.
```
Still no joy. Maybe the blacklist is still cached somewhere? Any ideas?

Could you try to force that package to build locally yourself? Errors are fine. I just need to get it *started*.

**Comment by cdunn2001** [comment]
```yaml
build:
  number: 0
  skip: True  # [osx] <<<<<<<<
```
Aha.
