### ISSUE TITLE
prokka: "Can't locate Bio/Root/Version.pm" error

### ISSUE THREAD

**Issue by nick-youngblut** [bioconda/bioconda-recipes#10277]
@Slugger70 I'm running `prokka    1.13     2    bioconda`, and am getting the following error:

```
Can't locate Bio/Root/Version.pm in @INC (you may need to install the Bio::Root::Version module) (@INC contains: /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/bin/../perl5 /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/site_perl/5.26.2/x86_64-linux-thread-multi /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/site_perl/5.26.2 /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/5.26.2/x86_64-linux-thread-multi /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/5.26.2 .) at /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/bin/prokka line 32.
```

Here's the full conda env:

```
aragorn                   1.2.38               h470a237_2    bioconda
barrnap                   0.9                           1    bioconda
bedtools                  2.27.1               he941832_2    bioconda
blast                     2.7.1                h96bfa4b_5    bioconda
boost                     1.66.0                   py36_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
expat                     2.2.5                hfc679d8_1    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gnutls                    3.5.19               h2a4e5f8_1    conda-forge
hmmer                     3.2                  hfc679d8_3    bioconda
icu                       58.2                 hfc679d8_0    conda-forge
infernal                  1.1.2                h470a237_1    bioconda
java-jdk                  8.0.92                        1    bioconda
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2
libgcc-ng                 7.2.0                hdf63c60_3
libgfortran-ng            7.2.0                hdf63c60_3
libidn11                  1.33                          0    conda-forge
libopenblas               0.2.20               h9ac9557_7
libstdcxx-ng              7.2.0                hdf63c60_3
minced                    0.2.0                         0    bioconda
ncurses                   6.1                  hfc679d8_1    conda-forge
nettle                    3.3                           0    conda-forge
numpy                     1.14.3           py36h28100ab_2
numpy-base                1.14.3           py36h0ea5e3f_1
openssl                   1.0.2o               h470a237_1    conda-forge
parallel                  20160622                      1    bioconda
pcre                      8.41                 h470a237_2    conda-forge
perl                      5.26.2               h470a237_0    conda-forge
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-archive-tar          2.18                    pl526_3    bioconda
perl-bioperl              1.6.924                       4    bioconda
perl-carp                 1.38                    pl526_1    bioconda
perl-compress-raw-bzip2   2.074           pl526hfc679d8_0    bioconda
perl-compress-raw-zlib    2.069           pl526ha92aebf_7    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.000000                pl526_0    bioconda
perl-extutils-makemaker   7.34                    pl526_0    bioconda
perl-file-path            2.15                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-io-compress          2.069           pl526hfc679d8_5    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.73                 h470a237_2    bioconda
perl-scalar-list-utils    1.45            pl526h470a237_3    bioconda
perl-test-more            1.001002                pl526_1    bioconda
perl-threaded             5.22.0                       13    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44            pl526h3a4f0e9_5    bioconda
perl-xml-sax              1.00                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_2    bioconda
perl-xml-simple           2.22                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
perl-yaml                 1.26                    pl526_0    bioconda
pip                       18.0                     py36_1    conda-forge
prodigal                  2.6.3                         1    bioconda
prokka                    1.13                          2    bioconda
python                    3.6.6                h5001a0f_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
setuptools                40.0.0                   py36_1    conda-forge
sqlite                    3.24.0               h2f33b56_0    conda-forge
tbl2asn                   25.6                          3    bioconda
tk                        8.6.8                         0    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
xz                        5.2.4                h470a237_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by nick-youngblut** [comment]
It appears that the bioperl package can't even be found in that environment:

```
$ perl -MBio::Root::Version -e 0
Can't locate Bio/Root/Version.pm in @INC (you may need to install the Bio::Root::Version module) (@INC contains: /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/site_perl/5.26.2/x86_64-linux-thread-multi /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/site_perl/5.26.2 /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/5.26.2/x86_64-linux-thread-multi /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/5.26.2 .).
BEGIN failed--compilation aborted.
(.snakemake/conda/126413bc) @ rick:/ebio/abt3_projects/methanogen_host_evo/bin/llga-lr

$ perl -MBio::Seq -e 0
Can't locate Bio.pm in @INC (you may need to install the Bio module) (@INC contains: /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/site_perl/5.26.2/x86_64-linux-thread-multi /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/site_perl/5.26.2 /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/5.26.2/x86_64-linux-thread-multi /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/5.26.2 .).
BEGIN failed--compilation aborted.
```

**Comment by nick-youngblut** [comment]
I tried simply updating bioperl:

```
perl-bioperl:                  1.6.924-4             bioconda    --> 1.6.924-6 bioconda
```

...but that didn't work:

```
$ prokka -h
Can't locate Bio/Root/Version.pm in @INC (you may need to install the Bio::Root::Version module) (@INC contains: /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/bin/../perl5 /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/site_perl/5.26.2/x86_64-linux-thread-multi /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/site_perl/5.26.2 /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/5.26.2/x86_64-linux-thread-multi /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/lib/5.26.2 .) at /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/126413bc/bin/prokka line 32.
```

**Comment by druvus** [comment]
Bio-perl is unfortunately not rebuilt for perl 5.26 yet. Hope it will be fix the coming week. Some dependencies are still in the queue to be fixed for cb3.

**Comment by nick-youngblut** [comment]
So `prokka` is broken until Bio-perl is rebuilt or can I use an older version? If yes for an older version do you know a version that will work?

**Comment by druvus** [comment]
@nick-youngblut you could probably still use older perl 5.22.  Please try if you could use it in a perl 5.22 environment: `conda create -n prokka522 perl=5.22 prokka`

**Comment by nick-youngblut** [comment]
Yeah, that worked! Thanks

**Comment by nick-youngblut** [comment]
Actually, I spoke too soon. I was checking the wrong thing. When I try running prokka (`prokka -h`) with perl=5.22, I get:

```
Can't locate XML/Simple.pm in @INC (you may need to install the XML::Simple module) (@INC contains: /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6/bin/../perl5 /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6/lib/perl5/site_perl/5.22.2 /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6/lib/perl5/5.22.2/x86_64-linux-thread-multi /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6/lib/perl5/5.22.2 .) at /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6/bin/prokka line 27.
```

perl-xml-simple is installed in the environment, but it's not found by prokka. If I try to update perl-xml-simple:

```
$ conda update -c bioconda perl-xml-simple
...
Solving package specifications: .

Package plan for installation in environment /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6:

The following packages will be UPDATED:

    perl:            5.22.2.1-0   conda-forge --> 5.26.2-h470a237_0 conda-forge
    perl-xml-simple: 2.22-0       bioconda    --> 2.22-pl526_1      bioconda
    perl-yaml:       1.24-pl522_1 bioconda    --> 1.26-pl526_0      bioconda

Proceed ([y]/n)?
```

... the update just changes the perl version from 5.22 to 5.26, which then results in `prokka -h` generating the error:

```
Can't locate Bio/Root/Version.pm in @INC (you may need to install the Bio::Root::Version module) (@INC contains: /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6/bin/../perl5 /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6/lib/site_perl/5.26.2/x86_64-linux-thread-multi /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6/lib/site_perl/5.26.2 /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6/lib/5.26.2/x86_64-linux-thread-multi /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6/lib/5.26.2 .) at /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6/bin/prokka line 32.
BEGIN failed--compilation aborted at /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2b4a8ed6/bin/prokka line 32.
```

...so it appears that I'm stuck with no working version of prokka.

**Comment by nick-youngblut** [comment]
@druvus do you know if there's been any progress on getting `prokka` fixed? I just tried creating a new conda env containing `prokka 1.13-2`, and `prokka -h` is still generating the `Can't locate Bio/Root/Version.pm in @INC` error.

**Comment by druvus** [comment]
@nick-youngblut bioperl is now fixed bit I don’t know it might be other  issues. I will take a look later tonight when I have access to a computer.

**Comment by druvus** [comment]
@nick-youngblut I have rebuilt prokka for linux to use the latest available biooerl and perl. Please try if it works for you.

It is still some issues with perl modules on osx so it is temporary skipped.

**Comment by nick-youngblut** [comment]
That seems of have worked. Thanks!

**Comment by nick-youngblut** [comment]
`prokka=1.13=3` appears to be broken at the CRISPR ID stage. I get the same error message at the same step for all of my genomes:

```
[10:27:08] Searching for CRISPR repeats

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: [[thread 23240125671168 also had an error]] does not look like GFF3 to me
STACK: Error::throw
STACK: Bio::Root::Root::throw /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2df28788/lib/site_perl/5.26.2/Bio/Root/Root.pm:447
STACK: Bio::Tools::GFF::_from_gff3_string /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2df28788/lib/site_perl/5.26.2/Bio/Tools/GFF.pm:616
STACK: Bio::Tools::GFF::from_gff_string /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2df28788/lib/site_perl/5.26.2/Bio/Tools/GFF.pm:437
STACK: Bio::Tools::GFF::next_feature /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2df28788/lib/site_perl/5.26.2/Bio/Tools/GFF.pm:395
STACK: /ebio/abt3_projects/methanogen_host_evo/bin/llga-lr/.snakemake/conda/2df28788/bin/prokka:676
-----------------------------------------------------------
```

This was probably missed by the test dataset because no CRISPRs are found in the `test/plasmid.fna` file used for running the prokka tests.

**Comment by nick-youngblut** [comment]
@druvus it seems that the developer of prokka is not sure what's causing the CRISPR repeat GFF error. Any ideas on if it's caused by some issue with the conda-installed version of `Bio::Tools::GFF`? For bioperl, my conda env includes:

```
perl-bio-asn1-entrezgene  1.72                    pl526_2    bioconda
perl-bio-coordinate       1.007001                pl526_0    bioconda
perl-bio-featureio        1.6.905                 pl526_1    bioconda
perl-bio-phylo            0.58                    pl526_1    bioconda
perl-bio-samtools         1.43            pl526h1341992_1    bioconda
perl-bio-tools-phylo-paml 1.7.3                   pl526_0    bioconda
perl-bio-tools-run-alignment-clustalw 1.7.4                   pl526_0    bioconda
perl-bio-tools-run-alignment-tcoffee 1.7.4                   pl526_0    bioconda
perl-bioperl              1.7.2                   pl526_8    bioconda
perl-bioperl-core         1.7.2                   pl526_3    bioconda
perl-bioperl-run          1.007002                pl526_3    bioconda
```

**Comment by druvus** [comment]
@nick-youngblut sorry I don't know really why it is not working. I hadn't time to look into it yet as I focused on rebuilding other blacklisted perl modules. I will try to look into bioperl next week.

**Comment by druvus** [comment]
@nick-youngblut I think the issue was an old version of parallel. Please see the PR #10642. 

If you want to try it before it is merged you could try this: 
```
conda create -n prokka-test prokka=1.13 minced=0.3.0 parallel=20180522
```

**Comment by nick-youngblut** [comment]
Sorry to pester you about this. `conda create -n prokka-test prokka=1.13 minced=0.3.0 parallel=20180522` worked for me, so I'll use that for now. Thanks!

**Comment by druvus** [comment]
Prokka is now rebuilt and should work for both linux and osx so I am closing.

**Comment by nixon444** [comment]
I am experiencing this very same issue! I installed prokka via conda, and tried all the above fixes but to no avail:

Can't locate Bio/Root/Version.pm in @INC (you may need to install the Bio::Root::Version module)

Any ideas? Do I need different versions of dependencies / Prokka? Install a different way?

**Comment by LakshmanTejaG** [comment]
Prokka doesn't work with perl5.26+ version and all you need to do just #run conda install perl=5.22.0 to downgrade the perl version and it will work for sure now

**Comment by carissableker** [comment]
Use the biobuilds channel to get the correct perl version:

    conda install -c biobuilds perl=5.22

I had to create a new conda environment to make sure down-grading perl didn't mess with other dependencies.

**Comment by uloeber** [comment]
> conda install -c biobuilds perl=5.22

I'm running into the same issue and unfortunately, it didn't fix the error. Does that still persist? Any other solutions?

**Comment by emmannaemeka** [comment]
Hello, I am running Mac OS monterey. I am facing similar issue

cpanm install the Bio::Root::Version
install is up to date. (0.01)
--> Working on the
Fetching http://www.cpan.org/authors/id/I/IN/INGY/the-0.15.tar.gz ... OK
Configuring the-0.15 ... OK
Building and testing the-0.15 ... OK
Successfully installed the-0.15
--> Working on Bio::Root::Version
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.7.8.tar.gz ... OK
Configuring BioPerl-1.7.8 ... OK
==> Found dependencies: Graph::Directed
--> Working on Graph::Directed
Fetching http://www.cpan.org/authors/id/E/ET/ETJ/Graph-0.9725.tar.gz ... OK
Configuring Graph-0.9725 ... OK
==> Found dependencies: Set::Object
--> Working on Set::Object
Fetching http://www.cpan.org/authors/id/R/RU/RURBAN/Set-Object-1.42.tar.gz ... OK
Configuring Set-Object-1.42 ... OK
Building and testing Set-Object-1.42 ... FAIL
! Installing Set::Object failed. See /Users/pamluka/.cpanm/work/1647519587.60768/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Set::Object' is not installed
! Bailing out the installation for Graph-0.9725.
! Installing the dependencies failed: Module 'Graph::Directed' is not installed
! Bailing out the installation for BioPerl-1.7.8.
1 distribution installed


I tried to install  Set::Object using cpanm install Set::Object It gave this error

cpanm (App::cpanminus) 1.7044 on perl 5.026002 built for darwin-thread-multi-2level
Work directory is /Users/pamluka/.cpanm/work/1647519889.61487
You have make /usr/bin/make
You have LWP 6.39
You have /usr/bin/tar: bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 
You have /usr/bin/unzip
Searching install () on cpanmetadb ...
--> Working on install
Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/install-0.01.tar.gz
-> OK
Unpacking install-0.01.tar.gz
Entering install-0.01
Checking configure dependencies from META.yml
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.36)
Configuring install-0.01
Running Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for install
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.36)
Building and testing install-0.01
cp lib/install.pm blib/lib/install.pm
Manifying 1 pod document
PERL_DL_NONLAZY=1 "/opt/miniconda3/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/install.t .. ok
All tests successful.
Files=1, Tests=1,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.08 cusr  0.02 csys =  0.12 CPU)
Result: PASS
Manifying 1 pod document
Appending installation info to /opt/miniconda3/lib/5.26.2/darwin-thread-multi-2level/perllocal.pod
-> OK
Successfully reinstalled install-0.01
Installing /opt/miniconda3/lib/site_perl/5.26.2/darwin-thread-multi-2level/.meta/install-0.01/install.json
Searching Set::Object () on cpanmetadb ...
--> Working on Set::Object
Fetching http://www.cpan.org/authors/id/R/RU/RURBAN/Set-Object-1.42.tar.gz
-> OK
Unpacking Set-Object-1.42.tar.gz
Entering Set-Object-1.42
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.36)
Configuring Set-Object-1.42
Running Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Set::Object
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Scalar::Util 0 ... Yes (1.46_02)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.36)
Checking if you have Test::More 0 ... Yes (1.302164)
Building and testing Set-Object-1.42
cp Changes.pod blib/lib/Set/Changes.pod
cp lib/Set/Object/Weak.pm blib/lib/Set/Object/Weak.pm
cp lib/Set/Object.pm blib/lib/Set/Object.pm
AutoSplitting blib/lib/Set/Object.pm (blib/lib/auto/Set/Object)
Running Mkbootstrap for Object ()
chmod 644 "Object.bs"
"/opt/miniconda3/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Object.bs blib/arch/auto/Set/Object/Object.bs 644
"/opt/miniconda3/bin/perl" "/opt/miniconda3/lib/5.26.2/ExtUtils/xsubpp"  -typemap '/opt/miniconda3/lib/5.26.2/ExtUtils/typemap' -typemap '/Users/pamluka/.cpanm/work/1647519889.61487/Set-Object-1.42/typemap'  Object.xs > Object.xsc
mv Object.xsc Object.c
x86_64-apple-darwin13.4.0-clang -c   -fno-common -DPERL_DARWIN -no-cpp-precomp -mmacosx-version-min=10.9 -fno-strict-aliasing -pipe -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -O3   -DVERSION=\"1.42\" -DXS_VERSION=\"1.42\" -fPIC --sysroot=/opt/MacOSX10.9.sdk "-I/opt/miniconda3/lib/5.26.2/darwin-thread-multi-2level/CORE"   Object.c
/bin/sh: x86_64-apple-darwin13.4.0-clang: command not found
make: *** [Object.o] Error 127
