### ISSUE TITLE
is conda-build 2 still used?

### ISSUE THREAD

**Issue by notestaff** [bioconda/bioconda-recipes#10311]
at https://bioconda.github.io/troubleshooting.html it says
Recipes built with conda-build 3
If you have conda-build 3 installed locally and use conda skeleton, the resulting meta.yaml will be incompatible with our conda-build 2 infrastructure.

We are moving towards supporting conda-build-3 which has many nice features we can take advantage of. In the meantime, however, we need to use conda-build 2.

Hasn't bioconda moved to conda-build 3?   @bgruening @johanneskoester

**Comment by kyleabeauchamp** [comment]
AFAIK it's conda-build3 now right?

**Comment by epruesse** [comment]
Yes, it's all CB3 now.

**Comment by epruesse** [comment]
@bgruening Remove that section from the docs?
