### ISSUE TITLE
HTSlib run_tests.sh incorrect commentary

### ISSUE THREAD

**Issue by jmarshall** [bioconda/bioconda-recipes#10321]
_recipes/htslib/run-test.sh_ says:

```sh
# None of the three commands have a simple --help or --version option that
# would allow to run them and get an exit code of 0.
```

This is incorrect. _htsfile_ has had such options since it was introduced in 1.2. _bgzip_ and _tabix_ have had a suitable `--version` option since 1.3.1.

**Comment by bgruening** [comment]
I think this was fixed. Thanks for the report!
