### ISSUE TITLE
Add extractSplitReads_BwaMem to somewhere in PATH

### ISSUE THREAD

**Issue by hepcat72** [bioconda/bioconda-recipes#10336]
I'm not versed in conda, or I'd have submitted a PR instead of an issue, but in order to be able to write a galaxy wrapper for extractSplitReads_BwaMem that could be submitted to the tool shed, which Imight like to do, I think `bioconda-recipes/recipes/lumpy-sv/build.sh` should either copy or link it in $PREFIX/bin.

**Comment by bgruening** [comment]
Lets see if https://github.com/bioconda/bioconda-recipes/pull/10337 fixes it.
