### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by tiagoantao** [bioconda/bioconda-recipes#1035]
Hi,

Eigensoft has this license:

_This software and its documentation are copyright (2010) by Harvard University 
and The Broad Institute. All rights are reserved. This software is supplied 
without any warranty or guaranteed support whatsoever. Neither Harvard 
University nor The Broad Institute can be responsible for its use, misuse, or 
functionality. The software may be freely copied for non-commercial purposes, 
provided this copyright notice is retained._

Is this acceptable?

Thanks

**Comment by johanneskoester** [comment]
Sure, you can specify this as custom license and provide a ``license_file`` in the recipe.

**Comment by tiagoantao** [comment]
Thanks!
