### ISSUE TITLE
RSEM version

### ISSUE THREAD

**Issue by acesnik** [bioconda/bioconda-recipes#10400]
Hi there,

I'm trying out bioconda for the first time, and I started with RSEM:

```
conda install rsem
conda update rsem
```

This gives me version 1.2.28, even though it [seems it should be installing the latest version, 1.3.0](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/rsem/meta.yaml#L2). I've tried `conda upgrade rsem`, too. Any idea why there is this discrepancy?

Thanks,

AC

**Comment by corburn** [comment]
@acesnik  when a new package is installed in an existing environment, a version will be selected that is compatible with existing packages. This includes direct dependencies and indirect dependencies of dependencies.

1.2.28 deps | 1.3.0 deps
-- | --
bioconductor-biobase | bioconductor-biobase
boost 1.60* | bioconductor-ebseq
htslib 1.3 | boost 1.64*
libgcc | libgcc
perl 5.22.0* | perl 5.22.0*
perl-module-build | perl-module-build
r 3.3.1* | r-base 3.4.1*
samtools 1.3 | samtools 1.3
zlib | zlib 1.2.8*
