### ISSUE TITLE
Remove mis-versioned `genomicconsensus` artifacts

### ISSUE THREAD

**Issue by pb-dseifert** [bioconda/bioconda-recipes#10426]
Hi @bgruening 
could you please do the same you did for BLASR for genomicconsensus too?
The problem comes from the fact that the initial addition (https://github.com/bioconda/bioconda-recipes/commit/cbc68dd545cb60ac4a157dafcc45e6347cc706df) used the version of the SMRTlink package (`3.0.2` at the time) and not the one in the `setup.py`. I cannot bump major version numbers, as this needs approval and has wide-ranging repercussions. Given that the `3.0.2` release is broken anyways due to bad versioning and changed dependencies (https://github.com/PacificBiosciences/GenomicConsensus/issues/124#issue-345310027), could you please remove and/or relabel as `broken` all the 4 `3.0.2` artifacts in the [Anaconda cloud](https://anaconda.org/bioconda/genomicconsensus/files)? Thanks!

**Comment by bgruening** [comment]
@pb-dseifert done! Let me know when you cross the boarder and we can get a ice-cream together :)
