### ISSUE TITLE
librsvg

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#1053]
librsvg contains the very useful rsvg-convert tool, and is therefore highly desirable for bioconda. @ostrokach I have seen that you already have a recipe in your private channel. Do you mind to push it to bioconda as well?

**Comment by ostrokach** [comment]
I think @pkgw would be in a better position to add librsvg.

conda-forge / bioconda is missing the `gdk-pixbuf`, `gtk3` and `libcroco` dependencies, and those are missing a set of dependencies themselves (a very large set if you try to create a conda package for every library in the xorg stack).

If `rsvg-convert` is the only thing that is required, I think a better approach would be to compile a static version using system libraries.

**Comment by johanneskoester** [comment]
Thanks. Personally, I don't need it anymore. I have added a cairosvg package to conda-forge, which does the same job with much lighter dependencies.

**Comment by pkgw** [comment]
OK, For what it's worth, I have a full stack of dependencies for `gtk3`, `librsvg`, `libcroco`, and `gdk-pixbuf` in a personal set of packages [here](https://github.com/pkgw/conda-recipes/) that layer on conda-forge. Now that X.org packages are in conda-forge, there actually aren't *that* many packages that need to be added to satisfy all of the dependencies.
