### ISSUE TITLE
What could be done community-wise to help keep bioconda recipes up to date? 

### ISSUE THREAD

**Issue by abalter** [bioconda/bioconda-recipes#10557]
What kind of system would help bioconda keep recipes up to date and in-sync with bioconductor?

I frequently run into conflicts setting up conda environments with bioconductor packages.

Perhaps an automated system could track which packages need to be updated and contributors could try to tick them off the list? Better than being in the middle of a project and suddenly needing to take time to do it.

Also, I don't know how to update builds. The [Contribute a Recipe](https://bioconda.github.io/contribute-a-recipe.html) docs are good. But perhaps the process is even simpler if just updating an existing recipe. 

Here is an example issue:
https://github.com/benjjneb/dada2/issues/545#issuecomment-414424455

**Comment by dpryan79** [comment]
The biggest delay is waiting for conda-forge to update its R package builds and pin them to the newest version of R.

See also #10288

**Comment by dpryan79** [comment]
At least for bioconductor packages we're now performing builds of all packages with each bioconductor release, so this should no longer be an issue. For more general packages we actually have a bot in development that checks for new package versions and creates PRs accordingly.

**Comment by abalter** [comment]
That is really awesome. Thanks folks!
