### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ewels** [bioconda/bioconda-recipes#1065]
Hi all,

I wanted to mention bioconda in a presentation and couldn't find an appropriate logo for it. So I made one, based on the [Conda logo](https://pypi.python.org/pypi/conda/4.0.0):

![bioconda](https://cloud.githubusercontent.com/assets/465550/13843079/ea10b5b8-ec31-11e5-9ae1-67a862a0606c.png)

Adobe Illustrator editable PDF: [bioconda.pdf](https://github.com/bioconda/bioconda-recipes/files/177652/bioconda.pdf) (the font is Brandon Grotesque, available to download [here](http://www.digitaldownloads.io/fonts/brandon-grotesque-bold-free/))

Thought I'd post it here in case it's of use to anyone else..

Phil

**Comment by ewels** [comment]
ps. I used the same colour as in the [Anaconda logo](https://en.wikipedia.org/wiki/File:Anaconda_Logo.png): `#3eb049`

**Comment by johanneskoester** [comment]
That's great, thank you! Do you think we could run into trouble because of using the conda logo? To avoid that, we could replace the white pattern in the O character with a white DNA helix.

Apart from that, I think we should get rid of the "registered trademark" symbol, because bioconda is not registered.

On the other hand, one could also see the right part of the logo just as the conda logo, in which case the R should be kept... To make that more clear, we could keep the conda part in a different color than the bio part.

You see, I like it, but I cannot decide what has to be changed in order to make this our official logo. Whatever decision we make, I think we should ask Continuum before be put it on our homepage. @bioconda/core, any thoughts?

**Comment by daler** [comment]
Agreed on all points: I like it, DNA for white pattern, and definitely need to check with Continuum.

For further separation from the Anaconda logo, maybe "BIO" in darker green and the helix on that first "O"? Something like:

![bioconda](https://cloud.githubusercontent.com/assets/115406/13849776/f6f33c5a-ec2d-11e5-8dc7-46697ec2f16b.png)

But of course depending on what the Continuum folks say.

**Comment by chapmanb** [comment]
This is awesome. Nice work Phil. I like Ryan's edits as well.

**Comment by ewels** [comment]
Nice! Like the variation @daler. Note that the _helix on that first "O"_ isn't a helix (yet) - it's a snake I think, taken from the original Conda logo. So it should probably stay in the `CONDA` part of the logo if we don't want to modify that.

**Comment by daler** [comment]
Good point; I just swapped the O's and changed color to try the idea . . . no helix yet.

**Comment by ewels** [comment]
Circular helices are difficult to draw! Here's my first attempt at it.. I tried to emulate the conda snake, I feel like it's not quite there though, needs something.

![bioconda](https://cloud.githubusercontent.com/assets/465550/13851920/423815f0-ec60-11e5-9115-b09608cd9701.png)

Maybe better without the original conda snake?

![bioconda2-01](https://cloud.githubusercontent.com/assets/465550/13852023/ad155702-ec60-11e5-89c4-c79875527441.png)

**Comment by johanneskoester** [comment]
That's beautiful! I like the second more, if Continuum does not mind.

**Comment by ewels** [comment]
I'll drop an e-mail to info@continuum.io and see what they say..

**Comment by tomkinsc** [comment]
@ewels nice work! I also like the second one.
It looks like the image on the [anaconda.org site](https://conda.anaconda.org/bioconda) is a gravitar. Perhaps there should be a smaller/two-line version of the logo for square images like that? Is that gravitar associated with your email address, @johanneskoester ?

**Comment by johanneskoester** [comment]
Yes, looks like. The email of the Bioconda account can be changed though.

**Comment by ewels** [comment]
No problem - I'll make a bunch of variants and post them here in a moment.

**Comment by ewels** [comment]
Ok, so here are some cleaned up versions which should be a bit better for general use:

![bioconda](https://cloud.githubusercontent.com/assets/465550/13853729/5a98dd0c-ec68-11e5-913d-5fc0fe6439a0.png)
![bioconda_monochrome](https://cloud.githubusercontent.com/assets/465550/13853730/5a98d5a0-ec68-11e5-8957-7b794de09f0d.png)
<img height="90" src="https://cloud.githubusercontent.com/assets/465550/13853728/5a985300-ec68-11e5-9aae-3ebaf3e84bfc.png"/>

Zip file also attached which contains PNG, SVG and AI files, along with the font used:
[bioconda_logo.zip](https://github.com/bioconda/bioconda-recipes/files/178308/bioconda_logo.zip)

**Comment by robinandeer** [comment]
Great work @ewels! I tried my luck with something awhile back not this is ten times better 😁

**Comment by ewels** [comment]
Ok, just got a reply from Michele at Contiuum - she says:

> Yes, you have permission to use the logo with a circled R to indicate it's a registered trademark. You'll also need to include the following copy:

> _Bioconda is a derivative mark of **Anaconda®**, a trademark of Continuum Analytics, Inc registered in the U.S. and other countries. Continuum Analytics, Inc. grants permission of the derivative use but is not associated with NGI Applications._

So I think we're good. I'll add the ® back in and post an updated version later today. She also got really excited about promoting Bioconda, so I've cc'ed @johanneskoester, @daler and @chapmanb to my reply to her - hope that's ok!

Phil

**Comment by ewels** [comment]
Hi all,

Michele from Continuum said that we're fine to use the logo, but requested that we keep the ® symbol to reflect that it's a registered trademark. Updated versions below:

![bioconda](https://cloud.githubusercontent.com/assets/465550/13878617/e71c8f6c-ed12-11e5-9c96-f68ce8497e14.png)
![bioconda_monochrome](https://cloud.githubusercontent.com/assets/465550/13878624/ebd2c22e-ed12-11e5-86eb-6ddd4920d146.png)
<img height="90" src="https://cloud.githubusercontent.com/assets/465550/13878626/efa093cc-ed12-11e5-8caf-4d771055a4f5.png"/>

Here's a zip file with contains PNG, SVG and AI files, along with the font used:
[bioconda_logo.zip](https://github.com/bioconda/bioconda-recipes/files/179674/bioconda_logo.zip)

It was requested that we add the following text somewhere when using the logo:
> Bioconda is a derivative mark of ***Anaconda®***, a trademark of Continuum Analytics, Inc registered in the U.S. and other countries. Continuum Analytics, Inc. grants permission of the derivative use but is not associated with Bioconda.

Great! Enjoy everyone :smile: :tada: 

Phil

**Comment by johanneskoester** [comment]
Thanks a lot Phil! I have added the logo to the homepage. I'll change the colors to match those you chose soon.

**Comment by ewels** [comment]
Great! Looks really nice :) I like the monochrome on the blue background actually - maybe the colour version could go at the top of the homepage or something?

**Comment by lecorguille** [comment]
Indeed, great logo.
So why not change the bioconda github-organization logo as well! Perhaps, just the O?

**Comment by bgruening** [comment]
This logo is great! Thanks for your work!
