### ISSUE TITLE
Salmon bioconda install segfaults when run through SLURM

### ISSUE THREAD

**Issue by scottx611x** [bioconda/bioconda-recipes#10662]
Hi all, [myself](https://github.com/COMBINE-lab/salmon/issues/271) and [others](https://github.com/COMBINE-lab/salmon/issues/268) have observed consistent segfaults when running `salmon` installed from the bioconda channel through SLURM.

It seems as though salmon's [pre-compiled linux binaries don't exhibit this issue](https://github.com/COMBINE-lab/salmon/issues/268#issuecomment-413045028).

Known versions exhibiting this behavior: [`0.9.1`, `0.11.1`, `0.11.2`]

My syslog reports the segfault as coming from `libtbb`:
`Aug 24 12:52:18 w13 kernel: [  431.254616] salmon[6645]: segfault at 2678e ip 00007f9b53298dca sp 00007fff00dc4740 error 4 in libtbb.so.2[7f9b53276000+37000]`

Just wondering if anyone has some intuition as to what could be going wrong? 
I'm quite happy to help debug, test, and provide more context/general info as needed!

Ref: https://github.com/COMBINE-lab/salmon/issues/268
Ref: https://github.com/COMBINE-lab/salmon/issues/271

**Comment by dpryan79** [comment]
Hmmm, one of our pipelines can optionally use salmon (0.9.1 from bioconda, though I should really update that to the newest version!) and we haven't noticed this. We also use slurm for submitting jobs, so we should have similarish enough setups for comparison. Can you make or suggest a minimal test case that reliably causes this behavior? I should note that our nodes use CentOS7 rather than Ubuntu, but it'd be a bit surprising if that were the cause of the problem.

BTW, I can also try to reproduce this in Galaxy, since our local instance uses the same slurm cluster and conda for dependency resolution.

**Comment by scottx611x** [comment]
Hi @dpryan79, thanks for offering your help. 

I'm wondering what you would need specifically to be able to reproduce this behavior? 

As a start, we are currently running Galaxy 17.05 with the aid of the latest Galaxy Cloudman.

**conda-specific Galaxy settings**:
```
galaxy@ip-172-31-24-127:/home/ubuntu/galaxy-app$ cat config/galaxy.ini | grep conda
conda_prefix = /mnt/galaxy/tool_dependencies/_conda
conda_auto_install = True
conda_auto_init = True
conda_ensure_channels = iuc,bioconda,conda-forge,defaults,r
conda_debug = True
```

[Recently tested `nativeSpecification` for salmon tool runs here](https://github.com/COMBINE-lab/salmon/issues/271#issuecomment-416364238)

**Input fastq**: `ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR103/002/SRR1039512/SRR1039512_1.fastq.gz`
**Reference Transcriptome** (from Galaxy History): `ftp://ftp.ensembl.org/pub/release-81/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz`

`salmon 0.11.2`( Galaxy revision `8:6b0ba6de1424`) has been installed from the main toolshed and had its dependencies resolved through conda. 

I've been running salmon with the default settings.

Some more specific information can be found [here as well](https://github.com/COMBINE-lab/salmon/issues/271)

I'd be happy to provide any additional context needed to help you attempt to reproduce this problem! Thanks again!

**Comment by dpryan79** [comment]
That should suffice, I expect I can run that on our own instance for testing.

**Comment by dpryan79** [comment]
Out of curiosity, is there a reason you're only using read 1 of the pair?

**Comment by scottx611x** [comment]
@dpryan79 For no particular reason other than my biological naivety :) 
If you think that using a pair could change any behavior for the better than I could try that out. I was initially just aiming for the simplest scenario that would yield a successful run.

**Comment by dpryan79** [comment]
Shouldn't really matter in the end, I was just curious if there was some underlying biological reason.

**Comment by dpryan79** [comment]
@scottx611x Are you still getting segfaults when run via slurm or has this issue gone away?

**Comment by scottx611x** [comment]
Hi @dpryan79, not 100% sure now I've since moved on to a new role. We ended up using Kallisto in the interim for our needs.

I think this can be closed, and reopened if the issue ever arises again, thanks for the follow-up!

**Comment by dpryan79** [comment]
Fair enough, thanks @scottx611x
