### ISSUE TITLE
misplaced recipe

### ISSUE THREAD

**Issue by Adamtaranto** [bioconda/bioconda-recipes#10688]
I accidentally created recipe 'teloclip' in top dir. I have just merged a pull request that should have deleted the old 'teloclip' dir and added a new one with some fixes into recipes.

The new one was created, but the old remains for some reason.

**Comment by dpryan79** [comment]
I'm putting together a PR to fix this real quick :)

**Comment by dpryan79** [comment]
Taken care of.
