### ISSUE TITLE
Remove `bats` package

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-recipes#10761]
The project [bats-core](/bats-core/bats-core) is continuing development of `bats`. `bats-core` is available via conda-forge.  No packages in `bioconda` depend directly on `bats`.

**Comment by epruesse** [comment]
ping @bioconda/core - need someone to move the old bats package to legacy

**Comment by epruesse** [comment]
I thought of it more as janitoring. 

Accidental use of an outdated unmaintained package and having a package in Bioconda channel for which no recipe is in master where my arguments for removing it.

**Comment by kyleabeauchamp** [comment]
Removal leads to inability to replicate saved environments and workflows, which hurts some folks.

**Comment by epruesse** [comment]
Agreed, been on that side often enough. 

Do I just close this issue and the PR then? `bats` is one of the many legacy packages that technically don't belong here, and probably won't be relevant to saved workflows, so I figured it could go. But I'm not going to press that - I just ended up at `bats` before finding `bats-core` as the most recent version of the testing framework.

**Comment by kyleabeauchamp** [comment]
I defer to @bgruening  as always :)

**Comment by epruesse** [comment]
😄 Me too

**Comment by bgruening** [comment]
I will close this for you, if you remove the recipe :)

Thanks @epruesse!

**Comment by epruesse** [comment]
done

Thanks @bgruening!
