### ISSUE TITLE
how long to run this command: conda install -c conda-forge -c bioconda deepvariant

### ISSUE THREAD

**Issue by sll513** [bioconda/bioconda-recipes#10773]
Hi:

I am new here. installed anaconda2, and then 
run conda install -c conda-forge -c bioconda deepvariant

It has been 6 hours for the install deepvariant on m4.large EC2. Is that normal?

Thanks,

**Comment by bgruening** [comment]
Not normal, but @mbargull and others are working on fixing this. Sorry, nothing we can do better atm, just try to keep your conda version to the newest available version and it will get better in the next weeks.

**Comment by mbargull** [comment]
That's very far from normal. Given the setup you describe, this should take more or less a minute:
```
$ time docker run --rm -it continuumio/anaconda2 conda install -c conda-forge -c bioconda deepvariant --dry-run                                                                                                                                                      
Solving environment: done
[...]
real 73.56
user 0.06
sys 0.03
$ time docker run --rm -it continuumio/anaconda2 conda create -nenv -c conda-forge -c bioconda deepvariant --dry-run                                                                                                                                                 
Solving environment: done
[...]
real 51.94
user 0.07
sys 0.01
```

So I think apart from `anaconda` and `python=2` there have to be other packages in the environment you install to that makes the solver struggle. Or some additional Conda channel configuration. Hard to tell without knowing more about the setup.
Can you provide the output of
`conda info`
`conda config --show-sources`
`conda list`
(for the environment you install `deepvariant` into)? Then I could elaborate what's wrong.

**Comment by mbargull** [comment]
But overall @bgruening is right in that we hope to improve very much on those long running cases. If everything goes well, the next feature release of `conda` will already improve the situation a lot. And I expect we'll be able to follow that up with some more tweaks over the next months, too.
