### ISSUE TITLE
Roary and Prokka dont work together

### ISSUE THREAD

**Issue by MichWeb75** [bioconda/bioconda-recipes#10783]
Hi, when I want to install bioconda roary and prokka in the same environment it does not work:

    roary:             3.7.0-0       bioconda

The following packages will be DOWNGRADED:

    perl-bioperl:      1.7.2-pl526_8 bioconda --> 1.6.924-6 bioconda
    perl-bioperl-core: 1.7.2-pl526_3 bioconda --> 1.6.924-1 bioconda
    prokka:            1.13-pl526_4  bioconda --> 1.13-2    bioconda

Afterwards prokka fails with:
Can't locate Bio/Root/Version.pm in @INC (you may need to install the Bio::Root::Version module)
Can't locate Bio/Roary/CommandLine/Roary.pm in @INC (you may need to install the Bio::Roary::CommandLine::Roary module)  

Apparently the roary recipe destroys something.

**Comment by druvus** [comment]
Roary is unfortunately still not rebuilt for perl 5.26. I fixed 4 perl dependencies so I PR #10791 will solve the issue by rebuild roary to use newer versions of perl, bioperl and parallel.

**Comment by MichWeb75** [comment]
This would be awesome. Thanks!

**Comment by druvus** [comment]
@MichWeb75 could you try if it works now? Roary was rebuilt in #11017

**Comment by bgruening** [comment]
@MichWeb75 please create a new issue if this is still a problem.
