### ISSUE TITLE
Nextflow NXF_HOME and multiuser install

### ISSUE THREAD

**Issue by abretaud** [bioconda/bioconda-recipes#10797]
ping @pditommaso 
We're trying to use the nextflow bioconda package in a multi-user cluster. It seems that you added a [redifinition of NXF_HOME](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/nextflow/build.sh#L2) in #7269
With this change users of our cluster get this error:
```
mkdir: cannot create directory ‘/conda/envs/nextflow-0.31.1/share/nextflow/tmp/ver’: Permission denied
Warning: Couldn't create cached classpath folder: /conda/envs/nextflow-0.31.1/share/nextflow/tmp/launcher/nextflow-one_0.31.1/nodename.example.org -- Maybe NXF_HOME is not writable? 
```
I'm tempted to just remove this line from build.sh, NFX_HOME would then be in the home of each user, and the problem fixed. Would you be ok with this change, or is there a good reason to keep this line?

(ping @cmonjeau too)

**Comment by pditommaso** [comment]
I think that's the proper folder to be used when installing via Conda. 

You can still provide [NXF_ASSETS](https://github.com/nextflow-io/nextflow/blob/3ee6c7856e4ae3786e598b5aa80b2382343dd7e8/nextflow#L253), [NXF_LAUNCHER](https://github.com/nextflow-io/nextflow/blob/3ee6c7856e4ae3786e598b5aa80b2382343dd7e8/nextflow#L277) and [CAPSULE_CACHE_DIR](https://github.com/nextflow-io/nextflow/blob/3ee6c7856e4ae3786e598b5aa80b2382343dd7e8/nextflow#L265) to user writable paths.

**Comment by abretaud** [comment]
I don't see why it's better to write in the conda env rather than in the home? Is it a bioconda guideline or a personal preference?

**Comment by pditommaso** [comment]
I'm not saying that it's better to write in the conda env but it's conda installing tool binaries in that in that directory and AFAIK it's not possible to change it.

**Comment by abretaud** [comment]
You're speaking about the jar file in `share/nextflow/framework/0.31.1/nextflow-0.31.1-one.jar`? I did not realise it was installed in NXF_FLOW, I see now why NXF_HOME to be changed indeed...

I wonder if the conda recipe could patch the nextflow bin to force NXF_ASSETS, NXF_LAUNCHER and CAPSULE_CACHE_DIR to use the default `$HOME/.nextflow/...` paths? It would make nextflow really usable in multi user setup. But maybe it's a bad idea and we'll just have to define these vars by hand on our cluster.

**Comment by pditommaso** [comment]
> I wonder if the conda recipe could patch the nextflow bin to force NXF_ASSETS, NXF_LAUNCHER and CAPSULE_CACHE_DIR to use the default $HOME/.nextflow/... paths?

Yes, that would actually make sense.

**Comment by jvolkening** [comment]
A note on this closed issue. I just spent quite a while trying to figure out why nextflow was ignoring my $HOME/.nextflow/scm configuration file. Finally saw that the bioconda recipe redefines `NXF_HOME`. 

For now, I will have to redefine `NXF_HOME` before all of my calls to nextflow or in `.bashrc`. I understand the rationale above about controlling where the jar files are installed, but the fact that this forces configuration files to live under the conda prefix seems...problematic. Or am I missing another option to configure those paths?

Thanks.

**Comment by pditommaso** [comment]
You are right. I'm realising that it would be better to keep NXF_HOME in the user HOME as it should be and and redefine instead the variables that controls the JARs location.

**Comment by jvolkening** [comment]
This is ideal, thanks @pditommaso!
