### ISSUE TITLE
arb-bio 6.0.6-2 broken - please remove in favor of build 3

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-recipes#10853]
Build 2 of `arb-bio 6.0.2` is broken. A configuration file needed by some of the tools separated in to the sub-package `arb-bio-tools` to avoid X11 dependencies for those ended up in the main package.

I'm preparing build 3 in PR #10833 

@bgruening Could you kindly delete or label as broken the build-2 packages for me?

Anaconda links:
https://anaconda.org/bioconda/arb-bio/files
https://anaconda.org/bioconda/arb-bio-tools/files
https://anaconda.org/bioconda/arb-bio-devel/files
https://anaconda.org/bioconda/libarbdb/files

**Comment by epruesse** [comment]
ping @bioconda/core

**Comment by bgruening** [comment]
Done!

**Comment by epruesse** [comment]
Thanks @bgruening!
