### ISSUE TITLE
conda not found in circleci build process

### ISSUE THREAD

**Issue by asmariyaz23** [bioconda/bioconda-recipes#10872]
circleci build fails with the following error:

`====>> Setup bioconda-utils
  #!/bin/bash -eo pipefail
.circleci/setup.sh
/opt/docker/bin/entrypoint_source: line 11: conda: command not found
/opt/docker/bin/entrypoint_source: line 11: conda: command not found
/opt/docker/bin/entrypoint_source: line 11: conda: command not found
Error: Exited with code 127
Step failed
Error: runner failed
Task failed`

I am using the latest bioconda-recipes repo and pulled down the latest bioconda-utils docker image with "docker pull bioconda/bioconda-utils-build-env". Any pointers as to how I can resolve this?

**Comment by epruesse** [comment]
I assume this is running `circleci build` locally.

@roryk also mentioned this on gitter and I ran into the same issue myself. 

ping @bioconda/core

**Comment by PertuyF** [comment]
I had similar issues in a different context. It appears that with conda>=4.3 `conda: command not found` happens when a script is executed under some conditions (non-interactive shell?) that does not source `conda.sh`.
If the script is executed from a conda-enabled shell, and the environment variables are kept, using `$CONDA_EXE` in the script could work as replacement for `conda` command.

**Comment by rhpvorderman** [comment]
I have exactly the same issue : 
```
Docker image digest: sha256:525c91e01875050fbf65cdb4bc83a45744c54f9027fa05f76f88713f3d37f4e3
====>> Spin up Environment
Build-agent version 0.0.7725-9681bc36 (2018-08-09T15:10:50+0000)
Starting container bioconda/bioconda-utils-build-env
  using image bioconda/bioconda-utils-build-env@sha256:ea59154ebeb07cbe1bb555148a67d4559bb11c6867592b7e3e5cd7e0a46cf298

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1536578709
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=bamstats
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=git@github.com:biopet/bioconda-recipes.git
  CIRCLE_SHA1=b22e92ae85f940edad6435aa0dd3a2ec5b74462f
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1536578709
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
====>> Setup ssh
  #!/bin/bash -eo pipefail
mkdir -p ~/.ssh
ssh-keyscan -H github.com >> ~/.ssh/known_hosts

# github.com SSH-2.0-libssh_0.7.0
====>> Setup base system
  #!/bin/bash -eo pipefail
cat >> $BASH_ENV <<EOF
if [[ \$- == *u* ]] ; then
    set +u ; . /tmp/repo/docker-entrypoint-source ; set -u
else
    . /tmp/repo/docker-entrypoint-source
fi
EOF

====>> Download common definitions
  #!/bin/bash -eo pipefail
curl -s https://raw.githubusercontent.com/bioconda/bioconda-common/master/common.sh > .circleci/common.sh

/opt/docker/bin/entrypoint_source: line 11: conda: command not found
====>> Setup bioconda-utils
  #!/bin/bash -eo pipefail
.circleci/setup.sh
/opt/docker/bin/entrypoint_source: line 11: conda: command not found
/opt/docker/bin/entrypoint_source: line 11: conda: command not found
/opt/docker/bin/entrypoint_source: line 11: conda: command not found
Error: Exited with code 127
Step failed
Error: runner failed
Task failed
```

**Comment by xileF1337** [comment]
I have the same issue on current Kubuntu as well as KDE Neon. The log looks like the one from @rhpvorderman .

**Comment by epruesse** [comment]
@micknudsen Yes, we did. It's probably worth retrying that, as that is the way to get a fix pulled.
