### ISSUE TITLE
Request of new recipe: consan

### ISSUE THREAD

**Issue by phil-gusev** [bioconda/bioconda-recipes#10904]
Dear Community,
This software [http://eddylab.org/software/consan/] is required for commonly used t_coffee to accurately align RNA.
I don't have the skill to write my own recipe yet, thus I'm requesting the help of a community of fulfilling this missing of a useful package.
Thank you in advance.
Best wishes,
Filipp

**Comment by druvus** [comment]
@phil-gusev I added conda in PR #11395
