### ISSUE TITLE
jellyfish 2.2.10-h2d50403_0 produces reasonable looking but incorrect results

### ISSUE THREAD

**Issue by bwlang** [bioconda/bioconda-recipes#10925]
I've filed this bug with upstream:
https://github.com/gmarcais/Jellyfish/issues/133

I think we should remove the 2.2.10 version for now, but I don't know how to do that...

**Comment by johanneskoester** [comment]
Our policy is to not remove versions in order to not break reproducibility. Hence, we cannot really remove it. What we could do is to add a post-link script that warns the user when installing that version into an environment.

**Comment by johanneskoester** [comment]
In case you would like to do that, simply follow [this guide](https://conda.io/docs/user-guide/tasks/build-packages/link-scripts.html).
