### ISSUE TITLE
Linter trying to lint recipes/perl-inline-c ATM

### ISSUE THREAD

**Issue by MathiasHaudgaard** [bioconda/bioconda-recipes#10938]
recipes/perl-inline-c is not my package but it's still trying to lint it right now when i'm building other packages.
Anyone experiencing the same problem?

**Comment by abretaud** [comment]
That's strange... Do you see this in a pull request, or locally?

**Comment by mbargull** [comment]
I assume you are seeing this locally or on a fork. When we determine which recipes to lint/build, we compare with the `master` branch. If you are on a fork and that fork's `master` is behind the upstream's `master` branch and you work on a branch based on that upstream `master`, then the branch contains changes newer than your fork's `master`.
So, just updating your fork's `master` to upstream `master` should fix it.

NB: We really should (at least on default) always try to compare with upstream `master`. It's just that no one fixed it yet :wink:.
