### ISSUE TITLE
searchgui glibc error

### ISSUE THREAD

**Issue by bernt-matthias** [bioconda/bioconda-recipes#11000]
One of the search engines (tide) seems to need glibc:

/gpfs1/work/songalax/galaxy-dev/database/jobs_directory/005/5277/working/bin/resources/Tide/linux/linux_64bit/crux: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /gpfs1/work/songalax/galaxy-dev/database/jobs_directory/005/5277/working/bin/resources/Tide/linux/linux_64bit/crux)

How can this be fixed?

**Comment by rvalieris** [comment]
unfortunately the binaries in the searchgui package are not compiled by bioconda, try to install/update you distro libstdc++ package.

you could also try reporting this problem upstream: https://github.com/compomics/searchgui

**Comment by bernt-matthias** [comment]
Just for curiosity: Wouldn't it be an option to install also the correct libstdc++ via conda?

**Comment by rvalieris** [comment]
the places were the program look up for these libs are sort of hardcoded at compile-time, so if you have these libs at a different place you will need to set a LD_LIBRARY_PATH env var to this directory.

see for example: http://wiredrevolution.com/system-administration/how-to-correctly-use-ld_library_path

**Comment by bernt-matthias** [comment]
Since the problem is the crux tool kit, I could imagine some solutions: 

1. make the crux-toolkit from bioconda a dependency and make searchgui use the crux-toolkit crux binary (by removing / replacing / linking). Potential Problems: 1) problem might still exist. I tested this and get now libgomp.so.1 not found (so the original problem might be solved and the omp problem could be solved with a new dependency), 2) searchgui might not be compatible (it currently uses 3.0.17109 and bioconda has 3.2). 
2. maybe the searchgui developers could use the 3.2 binary in their package (useful only if my test to solution 1 works).
3. crux-toolkit actually also provides the source code, but bioconda package takes the binaries. So it could be compiled by bioconda from source and then searchgui's crux could be replaced by this one.

further: 

- some more info on the glibc problem in crux: https://groups.google.com/forum/#!searchin/crux-users/glibc|sort:date/crux-users/I3VBe323xcU/RoSHn-qiJXIJ

**Comment by bgruening** [comment]
> the places were the program look up for these libs are sort of hardcoded at compile-time, so if you have these libs at a different place you will need to set a LD_LIBRARY_PATH env var to this directory.

Are you sure about this?

@bernt-matthias I think installing libgcc into your env by hand is worth a try.

**Comment by rvalieris** [comment]
he most likely already had libgcc installed by other packages.

conda does some tricks when its building the package to make the binaries relocatable, [see here](https://conda.io/docs/user-guide/tasks/build-packages/make-relocatable.html).

>Any binary file **containing the build prefix** can automatically be registered [...] The registered files will have their **build prefix replaced with the install prefix** at install time. This works by **padding the install prefix with null terminators** [...] On Linux and Mac, conda build **pads the build prefix** to 255 characters by appending _placehold’s to the end of the build directory name.

without these tricks the program will only search for libs on the system-wide paths set at `/etc/ld.so.conf*`

**Comment by rvalieris** [comment]
@bernt-matthias compiling with conda is definitely the better solution, however I don't think anybody tried to do that so far so we don't know if it will work with the other moving parts of searchgui, personally I never used these packages, I wouldn't know how to test these things.

my suggestion is try to compile it and see if it works, if it does you can submit a PR to bioconda to include these changes on the crux/tide and/or searchgui recipes.

**Comment by bernt-matthias** [comment]
Just tried to compile the 3.0 version of crux from their github page which failed due to some old link: 

https://teamcity.labkey.org/guestAuth/repository/download/bt81/.lastSuccessful/pwiz-src-3%200%2018264%20d4d63fb.tar.bz2

Anyway seeing all the licences at http://crux.ms/download.html I'm wondering if we should/can add this to bioconda anyway...

**Comment by bgruening** [comment]
Closing this. @bernt-matthias if this is still a problem let's talk the SG people to work with us closer together. We have some good connection to them.
