### ISSUE TITLE
Merged Antismash PR but the package is not built/available

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#11021]
HI @bioconda/core,

Yesterday I merged #9789 which is an update to Antismash. Although the PR build sand passes the tests, it is not built (see [the anaconda website](https://anaconda.org/bioconda/antismash)). Could someone from the core team check on the build logs for this package or point me where to look?

In the past, there was an issue with the large size of this package and I suspect that some maximum docker image build size was exceeded.

Thanks,
zach cp

**Comment by bgruening** [comment]
Its on the blacklist: https://github.com/bioconda/bioconda-recipes/blob/master/build-fail-blacklist#L1712

You need to remove it before it gets tested ... sorry.

**Comment by zachcp** [comment]
(facepalm)

thanks @bgruening
