### ISSUE TITLE
GATK4 and bundled conda env

### ISSUE THREAD

**Issue by marchoeppner** [bioconda/bioconda-recipes#11050]
Hi,
I hope I am not missing something essential - but the new GATK4 requires a custom conda environment to run (bundled with the distro as gatkcondaenv.yml). When installing GATK4 through bioconda, these dependencies are not installed. Perhaps it would make sense to include those dependencies? Some of the new GATK tools won't work without them.

Cheers,
Marc

**Comment by chapmanb** [comment]
Marc;
Thanks for looking into this. It appears as if the custom conda environment is mostly python libraries for the vqsr_cnn filter. We have this as a separate dependency in bioconda:

https://github.com/bioconda/bioconda-recipes/tree/master/recipes/vqsr_cnn

It adds quite a few dependencies and isn't yet widely used so we haven't made this as a strict requirement for gatk4, but can be installed separately if you're using it.

Would this work for you?

**Comment by marchoeppner** [comment]
Hi,
thanks for pointing this out; yes I believe this will work!
