### ISSUE TITLE
ddocent downgrades a few critical packages

### ISSUE THREAD

**Issue by tiagoantao** [bioconda/bioconda-recipes#1106]
ddocent requires the installation of old versions of a few packages:
bedtools
samtools
vcftools

I volunteer to upgrade this

**Comment by tiagoantao** [comment]
ping @bgruening @yvanlebras

**Comment by tiagoantao** [comment]
Is it OK to upgrade?

**Comment by bgruening** [comment]
I think it is. Please create a subfolder (version as name) under the main folder.

**Comment by tiagoantao** [comment]
But the version will be the same, I believe, than the standard one...

**Comment by bgruening** [comment]
Ah you mean the old bedtools version is already in bioconda, but the ddocent release installs a newer one?
Than a ddocent update is enough. You can use the `package match specification`: http://conda.pydata.org/docs/spec.html#build-version-spec

Please also increase the build number and maybe add a new test that makes sure a bedtools based feature is used.

**Comment by tiagoantao** [comment]
This seems to be a requirement of dDocent, unfortunately. Closing. Apologies for making you lose time.
