### ISSUE TITLE
Gateway time out at plass test-macos step

### ISSUE THREAD

**Issue by martin-steinegger** [bioconda/bioconda-recipes#11075]
The test-macos step of the Plass (https://github.com/bioconda/bioconda-recipes/pull/11074) bioconda recipe failed because of gateway timeout. I have attached the error. The error message recommends a restart but I can not restart the build. What can I do to resolve this error? 

```
conda.CondaMultiError: HTTP 504 GATEWAY_TIMEOUT for url <https://conda.anaconda.org/conda-forge/osx-64/xz-5.2.4-h470a237_1.tar.bz2>
Elapsed: 00:59.328563
CF-RAY: 45f688e179ad71e5-ORD

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

**Comment by dpryan79** [comment]
It happens, you just need to rerun the affected test (I've triggered a rerun).

**Comment by dpryan79** [comment]
Passes now.

**Comment by martin-steinegger** [comment]
Thank you! How can I rerun the test? I could not trigger it.

**Comment by dpryan79** [comment]
It's not terribly intuitive :( First you need to login to circleci with your github account. If you then click on a failed step you'll see near the top right of the page a button that says "Rerun workflow". Note that this will rerun the entire thing (linting, then the Linux test and then finally the OSX test). If one instead clicks on the link under "workflow" in the top center (this will be something like "bioconda-test") then you get to a different page with additional options. The most useful option there is the "Rerun" button on the left that allows you to select "Rerun from failed".

I won't tell you how many months it took me to realize that one could do all of that...
