### ISSUE TITLE
Recipes that need to be fixed because they violate FHS or flood the environment with unnecessary files.

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#1113]
This is a (growing) list of recipes that need to be fixed because they either won't work this way or could cause conflicts or just flood PATH.
- [rnastructure](https://github.com/bioconda/bioconda-recipes/blob/cedfd52d1790d397405419a82493f6d62b238244/recipes/rnastructure/5.7/build.sh) need a more reasonable executable name than `exe`
- [collectl](https://github.com/bioconda/bioconda-recipes/blob/48f9f361446ba90fcdd22b24617d546869a57774/recipes/collectl/build.sh) executable needs to be copied to $PREFIX/bin

**Comment by dmaticzka** [comment]
this has been fixed by rnastructure 6.0

**Comment by epruesse** [comment]
and collectl has been fixed in 38b2a3088ec16b73a030e42633a74397cd9273fc
