### ISSUE TITLE
Update DESeq2 package to depend on bioconductor-rhdf5

### ISSUE THREAD

**Issue by jennaj** [bioconda/bioconda-recipes#11141]
**Reference**: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-deseq2/meta.yaml

**Issue**: missing dependency error when Kallisto data are input to DESeq2

**Error**: ``` reading kallisto results from hdf5 files requires Bioconductor package `rhdf5` ```

**Comment by bgruening** [comment]
This should be fixed now.
