### ISSUE TITLE
maker package not found

### ISSUE THREAD

**Issue by lstevens17** [bioconda/bioconda-recipes#11163]
Hello, 

I'm currently trying to install maker using bioconda, but I'm getting a package not found error. 

```
$ conda install maker
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - maker
  - repeatmasker
  - perl-text-soundex

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch
```

I get the same result using conda install -c bioconda maker.

Any ideas why this is happening? The package appears to be available on both the anaconda (https://anaconda.org/bioconda/maker) and bioconda (https://bioconda.github.io/recipes/maker/README.html) websites. 

Thanks any help you can offer, 

Lewis

**Comment by acaprez** [comment]
Hmm, I think `conda-forge` is missing from your channel list.  Did you do the channel setup (item 2 under "Using Bioconda") on [this page](https://bioconda.github.io/)?  Running the command `conda info` and pasting the output would also help with troubleshooting.

**Comment by lstevens17** [comment]
Seems that was indeed the issue - not sure how I've made it this far without conda-forge. 

Thanks for your help, I appreciate it!
