### ISSUE TITLE
raxml version: 7.3.0

### ISSUE THREAD

**Issue by sghignone** [bioconda/bioconda-recipes#1118]
Qiime 1.9.1, as evidenced by qiime-deploy configuration file (https://github.com/qiime/qiime-deploy-conf/blob/master/qiime-1.9.1/qiime.conf), still requires the  version: 7.3.0 of RAXML.
Raxml is already in bio-conda, as version 8.2.4.
Is it possible to add also the older version?

Thanks

**Comment by colinbrislawn** [comment]
Oh that's a great question. Can a bioconda dev tell us more about how to support older versions? I know legacy packages are needed for `biom-format`, `fasttree`, and others.

**Comment by daler** [comment]
Sure, see the last section of the [guidelines](https://github.com/bioconda/bioconda-recipes/blob/master/GUIDELINES.md#versions).

**Comment by sghignone** [comment]
For example, also INFERNAL (https://anaconda.org/bioconda/infernal/files) and MUSCLE (https://anaconda.org/bioconda/muscle/files) have different versions available, and the older ones are required by qiime 1.9.1

**Comment by tiagoantao** [comment]
I actually did 8.2.4 for raxml. I can do 7.3.0 if no one is working on this. Please drop me an email in the next 48 hours if you are working on this, if not I will start on Monday

**Comment by colinbrislawn** [comment]
Oh thanks @tiagoantao. I don't think anyone has taken it, and we would really appreciate this package.

**Comment by tiagoantao** [comment]
This is now committed. I am closing this issue. If there are any problems please open a new issue **and ping me**
