### ISSUE TITLE
bowtie2 wrong installation directory

### ISSUE THREAD

**Issue by jma1991** [bioconda/bioconda-recipes#1121]
The latest version of bowtie2 in the bioconda repository gets installed into the root folder of my anaconda installation. When I try with other packages, such as bowtie and bedtools they get placed into my bin folder.

**Comment by johanneskoester** [comment]
Indeed, there have been a few recipes containing this error. This will be fixed with PR #1111.

**Comment by crawforc3** [comment]
This is still happening

**Comment by johanneskoester** [comment]
Which version of bowtie?

**Comment by crawforc3** [comment]
Here's the output of boetie2 --verison, note that I moved it to bin/ already

crawforc3@ubuntu-desktop:~/anaconda3$ bowtie2 --version
/home/crawforc3/anaconda3/bin/bowtie2-align-s version 2.2.5
64-bit
Built on 487386fc9b54
Thu Jan  7 17:00:15 UTC 2016
Compiler: gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC) 
Options: -O3 -m64 -msse2  -funroll-loops -g3 -DPOPCNT_CAPABILITY
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}

**Comment by johanneskoester** [comment]
That is a very old version. But even that has been fixed since then. Simply do a `conda update bowtie2` in your environment. If you want to keep 2.2.5, then do `conda update bowtie2=2.2.5`

**Comment by johanneskoester** [comment]
Feel free to reopen if you disagree.
