### ISSUE TITLE
CI failing for mysterious reasons

### ISSUE THREAD

**Issue by pinin4fjords** [bioconda/bioconda-recipes#11298]
Hi all,

I've been having trouble recently making trivial tweaks to recipes, for example see https://github.com/bioconda/bioconda-recipes/pull/11292. 

Basically the CI fails. When I check the outputs in Circle CI the package downloads and installs, and the tests all pass, but there's a copy error like in this PR:

"cp: cannot stat `/opt/conda/conda-bld/noarch/r-seurat-scripts-0.0.2-0.tar.bz2': No such file or directory"

This seems to be somewhat intermittent, seemed to go away but now it's recurred.

I'm afraid I'm not yet familiar with the nuts and bolts here to provide diagnosis or cure- could anyone else suggest a solution?

Many thanks,

Jon

**Comment by dpryan79** [comment]
You may need to `chmod a+ws something/conda-bld/noarch` and `linux-64` as well. When things are run in the docker container they're done as a different user and then written to that directory (and a `chown` run on them). If the user that runs things in the docker container doesn't have write permissions to the aforementioned directories then you'll get an error like that.

**Comment by pinin4fjords** [comment]
Thanks @dpryan79. Where should that chmod'ing be done?

I couldn't get the container-based testing up and running on my local machine (I just use the containerless tests), so I'm only talking about the testing associated with the above PR to this repo.

**Comment by dpryan79** [comment]
You'd need to `chmod` where ever you've installed conda.

**Comment by pcm32** [comment]
Thanks @dpryan79 we are a bit lost still though. The explanation makes sense (privileges issue), but from the two files that we commit in the bioconda recipe (build.sh and meta.yml), we fail to see where we would enact such changes. Does the build.sh should include such logic, so that after inferring where things will be built, it makes a chmod on those folders?

**Comment by pcm32** [comment]
The error we are getting is on the CI itself, not locally: https://circleci.com/gh/bioconda/bioconda-recipes/29369#tests/containers/0

**Comment by dpryan79** [comment]
Try getting rid of `noarch`.

**Comment by pinin4fjords** [comment]
Okay, tried that, same issue. Very puzzling.

**Comment by pinin4fjords** [comment]
@bgruening  - you were kind enough to help with these recipes to begin with. Can you by any chance identify the that's causing the CI to fail in https://github.com/bioconda/bioconda-recipes/pull/11292?

**Comment by chapmanb** [comment]
Jonathan;
I ran into the same issue with an update and did some experiments. I don't understand why but it turns out adding `r-base` to host fixes the issue:
```
requirements:
  host:
     - r-base
```
in addition to having it in `run`. #11394 is the PR I debugged on if you want to follow along with all my attempts. Hope adding that to your `meta.yaml` will get your recipe built.

**Comment by pinin4fjords** [comment]
Thanks @chapmanb - I tried it, but no joy.

**Comment by pinin4fjords** [comment]
Happening again in https://github.com/bioconda/bioconda-recipes/pull/11510 :-(

**Comment by pinin4fjords** [comment]
@chapmanb I just reset the git on https://github.com/bioconda/bioconda-recipes/pull/11292. But for completeness I've made the change to https://github.com/bioconda/bioconda-recipes/pull/11510- doesn't solve the problem.

**Comment by chapmanb** [comment]
Thanks for confirming. Sorry, that is all the magic I have and resolved my issue but glad you're pursuing R pinning with Bjorn as that has solved other issues with me in the past. Fingers crossed this combo will get you through this and thanks for all the work trying to debug this.

**Comment by pinin4fjords** [comment]
Thanks @chapmanb. It seems to be that in my case pinning the R version to match the pinned Seurat version (with host entry as you suggested) is what sorted things out.
