### ISSUE TITLE
umi_tools: Pinned depenency versions

### ISSUE THREAD

**Issue by IanSudbery** [bioconda/bioconda-recipes#11303]
Hi,

I am one of the authors of `umi_tools`, however, I didn't build the biconda recipe (and we are super greatful to those maintaining this for us). The bioconda recipe includes a dependency for `certifi` that was not in the `meta.yml` from our own channel (. The version in the bioconda recipe is pinned at `certifi=2016.9.26`. However one of the pacakges that `umi_tools` is often used with is pinned at `certifi=2018.8.24`. 

Can someone explain to me:
1) Why this dependency is present
2) Why it is pinned at this version?

Cheers.

**Comment by IanSudbery** [comment]
I notice that this requirement was added with the recipe was updated by @davebx  for `v0.5.0` (PR #5875), and that it was queried at the time by @croth1 .

**Comment by croth1** [comment]
continued in: https://github.com/bioconda/bioconda-recipes/pull/11376
