### ISSUE TITLE
Should bioconductor packages depend on a bioconductor "version-only" package?

### ISSUE THREAD

**Issue by ebolyen** [bioconda/bioconda-recipes#11315]
I was diagnosing a strange namespace error in our QIIME 2 integration tests, where OS X runs of DADA2 were failing because Biostrings moved `narrow` out of its namespace. This correction was accounted for the in the latest bioconductor train release (which isn't up on bioconda yet), however for some reason a [OS X builds](https://anaconda.org/bioconda/bioconductor-biostrings/files) for the latest Biostrings version were uploaded (linux wasn't and the recipe doesn't seem to have changed, is this an accidental recursive upload from a different package?)

This got me thinking, what if the bioconda packages for bioconductor all depended on an artificial package which was used to track the bioconductor train release? Then in this situation, conda would have identified that the bioconductor-dada2 being installed required `bioconductor==<some version>` and could have ignored the bioconductor-biostrings OS X build as it would have required `bioconductor==<some version+1>`.

I believe this would be similar to how the `blas` metapackage is used to negotiate whether or not OpenBlas is available for linking elsewhere in the conda ecosystem.

That being said, I'm not sure if it is possible to do this after the fact, since older builds would still exist without the constraint and so conda might "solve" those by downgrading other things which is probably an even worse a problem.

Thoughts?

**Comment by bgruening** [comment]
@ebolyen; @dpryan79 is currently rebuilding the Bioconductor stack on the `bulk` branch. OSX is just faster to build as we build containers on Linux as well. The updated recipe is one the bulk branch. 

Sorry for any inconvenience.

**Comment by dpryan79** [comment]
Bulk is currently rebuilding again, so perhaps the missing package will be there in a few hours :)

**Comment by ebolyen** [comment]
@bgruening @dpryan79, great to hear, I hope that all is going well! 

However my question was more about how we might be able to get conda to respect the bioconductor train release rather than any particular package being present or absent.

**Comment by dpryan79** [comment]
For the new bioconductor builds we're making them require other bioconductor packages from the same release. So a bioc 3.7 package should only pull in other bioc 3.7 packages as dependencies. That's currently not part of the bioconductor skeleton, but it's planned.

**Comment by ebolyen** [comment]
That's even more robust! Thanks for the info, looking forward to the new release :+1:
