### ISSUE TITLE
Update went fine for noarch only, linux and osx still on the previous version

### ISSUE THREAD

**Issue by julie-sullivan** [bioconda/bioconda-recipes#11368]
I made a pull request for my new updates that was subsequently merged:

https://github.com/bioconda/bioconda-recipes/pull/11182

This correctly updated to `1.11.0` for noarch but it's still on 1.10.0 for linux and osx:

https://anaconda.org/bioconda/intermine

What do I need to do to update all? Thanks!

Tell @nupurgunwant

**Comment by druvus** [comment]
For new installation or updates It should pull in 1.11.0 from noarch for linux and osx so everything is in order.
