### ISSUE TITLE
bioconda FASTA3 version out of date

### ISSUE THREAD

**Issue by wrpearson** [bioconda/bioconda-recipes#11383]
The version of fasta36 (the bioconda fasta3 package) is fasta-36.3.8g dated December, 2017.  This version has some bugs that have been corrected in fasta3-36.3.8g dated August, 2018.  How can I help get the version updated?

```
$ /seqprg/bin/fasta36 -h
USAGE
 fasta36 [-options] query_file library_file [ktup]
 fasta36 -help for a complete option list

DESCRIPTION
 FASTA searches a protein or DNA sequence data bank
 version: 36.3.8g Aug, 2018

COMMON OPTIONS (options must preceed query_file library_file)
 -s:  [BL50] scoring matrix;
 -f:  [-10] gap-open penalty;
 -g:  [-2] gap-extension penalty;
 -S   filter lowercase (seg) residues;
 -b:  high scores reported (limited by -E by default);
 -d:  number of alignments shown (limited by -E by default);
 -I   interactive mode;
```

**Comment by druvus** [comment]
@wrpearson thanks for pointing this out. The way to update the tool is by submitting a PR updating the `recipies/fasta3/meta.yaml`file. I can help with it if you could point me to the correct location of the latest release. I was not able to find the newer version at `http://faculty.virginia.edu/wrpearson/fasta/`

**Comment by wrpearson** [comment]
You are quite correct that the version that was there was old.

I have updated it.

The current fasta-36.3.8g.tar.gz is dated Oct. 23, and is the current version.

Thanks for your help.

Bill Pearson


Begin forwarded message:

**Comment by micknudsen** [comment]
Fixed in PR https://github.com/bioconda/bioconda-recipes/pull/7215
