### ISSUE TITLE
racon 1.3.1 racon_wrapper doesn't work

### ISSUE THREAD

**Issue by imneuro** [bioconda/bioconda-recipes#11405]
Hi team,

I used racon1.3.1 and had error in racon_wrapper. My errror message is "error: unable to run rampler!". It is as same as others reported in [https://github.com/isovic/racon/issues/81](https://github.com/isovic/racon/issues/81) . 

Could someone rebuild this version? Thank you.

Best,
Xin

**Comment by acaprez** [comment]
@imneuro - I'd give it an hour or so for the updated package to be in the bioconda channel, then do `conda update racon` and try running `racon_wrapper` again.
