### ISSUE TITLE
Sambamba 0.6.8 is broken (for us)

### ISSUE THREAD

**Issue by messersc** [bioconda/bioconda-recipes#11422]
Hi,

we are running into `sambamba: error while loading shared libraries: libphobos2-ldc-shared.so.81: cannot open shared object file: No such file or directory` since updating to sambamba 0.6.8 on CentOS.

https://github.com/bioconda/bioconda-recipes/pull/11212

https://github.com/bioconda/bioconda-recipes/commit/db7bc603d54525a27df3d4ed847e0a16734aec20#comments

@dpryan79 @pjotrp Hope it's ok if I add you as you seem to be knowledgeable about the change. Any ideas?

Thanks,
Clemens

**Comment by dpryan79** [comment]
Yeah, I had the same issue. I have on my to do list to pin sambamba to ldc. That will fix this. At the moment you'll need to `conda install -c conda-forge ldc=1.11.0` to get around this.

**Comment by pjotrp** [comment]
Since ldc in conda is at 1.11.0 why do you have to pin it? And why does it work in CI but not in individual cases?

**Comment by dpryan79** [comment]
It looks like the newest ldc clashes with some other packages currently due to conflicting dependencies. I had this issue in an env with htslib.

**Comment by dpryan79** [comment]
This should now be fixed.

**Comment by pjotrp** [comment]
Great. Note we are having issues with ldc 1.12.0 if it comes up https://github.com/biod/BioD/issues/44

**Comment by dpryan79** [comment]
Glad I pinned it to 1.11.0 then :)

**Comment by pjotrp** [comment]
@dpryan79 sambamba now compiles with later ldc versions incl. 1.18, see https://travis-ci.org/biod/sambamba
