### ISSUE TITLE
Using other channels

### ISSUE THREAD

**Issue by tiagoantao** [bioconda/bioconda-recipes#1145]
I am afraid of the answer to this, but I have to ask:

Due to the way anaconda works, we can only use packages from bioconda and r channels right? I would like to add some dependencies related to geo-localization that are on the osgeo channel. I suppose I have to copy package definitions across?

**Comment by johanneskoester** [comment]
This is a very important question. Sure including them into bioconda would be one possibility. For a single package, this might be ok, but with many non-bio package, we might add too much of a maintenance burden for us. 

Regarding depending on another external channel:
The osgeo description does not sound very compatible with bioconda, e.g.

> These packages use development versions of software and have dependencies which may conflict with packages from the official anaconda channels.

Another possibility would be to depend on the rios channel: https://anaconda.org/rios, which is said to have the corresponding stable releases.

I would suggest to depend of rios if possible. Since it is maybe a bit too specific to add it to the list of required channels on the homepage, you could use the ``extra -> notes`` section in the meta.yaml to specify the channel. Even better would be to add a section ``extra -> channels`` to the meta.yaml, which we could display at a prominent location in the package description on the homepage.

**Comment by tiagoantao** [comment]
Thanks. Unfortunately the package that I am interested in is not on rios, (gdal). But I will make sure I will not be introducing conflicts with the official channels (last resort I will do a non-conflicting package).
I will add extra -> channels to meta.yaml.
Do you think it would be worth putting a note about this on the development docs?

**Comment by tiagoantao** [comment]
@johanneskoester Just a question: putting the channels on extra will fail travis, right?

**Comment by johanneskoester** [comment]
Yes, this should be in the docs. Why should it fail travis? Conda itself is ignoring the extra section.

**Comment by johanneskoester** [comment]
Oh yes, now I understand. Of course your package cannot build. We would need to add osgeo to the channels... But we can't since it might overwrite packages from the default channel.

**Comment by johanneskoester** [comment]
In that case, I would really say that you should move the necessary packages over to bioconda.

**Comment by johanneskoester** [comment]
If we would already use the anaconda build system, you could specify the channels in ``.binstar.yaml`` I think.

**Comment by tiagoantao** [comment]
Would there be a way to configure travis to do a channel configuration _per package test_ (thus avoiding bringing unwanted clutter for packages that do not need it)? Say by importing a local binstar.yaml.
The same to docker?

I would avoid importing packages, or we will end up with a lot of clutter. But I would do that if there are no alternatives...

Pinging @bgruening as he might have a opinion on the docker front...

**Comment by johanneskoester** [comment]
I we want to go that direction, I guess it would be a good idea if we can get the anaconda build service to work as a replacement of our travis setup. Apart from per-package channel specs, it allows us to get rid of quite some custom code on our side.

**Comment by johanneskoester** [comment]
Apart from that, I still like the idea of Bioconda being as self-contained as possible, because it allows us to ensure consistency and policies.

**Comment by tiagoantao** [comment]
OK. In the short term I will import all packages needed for flightr to work.

But it might be interesting, in the long term, to have that bioconda build service

**Comment by bgruening** [comment]
@tiagoantao very interesting question that also popped up here: https://github.com/bioconda/bioconda-recipes/pull/1101

I tried to combine both channels during the last days and found many problems if you activate multiple channels by default for all packages. I'm more and more in favour of joining all repos to one giant, continuum supported channel and have a procedure to move packages into the main channel after some time.

**Comment by tiagoantao** [comment]
I am going to close this issue to avoid "polluting" the open issues list. I will import the relevant gdal packages that I need for now.

Something to keep in mind, though...
