### ISSUE TITLE
R 3.5 pinning

### ISSUE THREAD

**Issue by dpryan79** [bioconda/bioconda-recipes#11456]
At the moment, we're adding `conda_build_config.yaml` files to the various bioconductor packages that can only exist for R 3.5. This is less than ideal and is leading to a lot of extra files. For the next bioconductor release we should clean this up and come up with a better way of handling things.

Xref: #11452

**Comment by dpryan79** [comment]
I'll use this as an issue tracker for updates we should make before the next bioconductor release hits bioconda:

 - [ ] Update the bioconductor skeleton to pin to other bioconductor dependencies within the same release. In effect, this means `>=X.Y.0,<X.Y+2.0`.
 - [ ] Ensure that th skeleton properly wraps package summary blocks. `bulk` is breaking on occasion because the YAML can't read long lines.
 - [ ] Make sure only one R release is built for new bioconductor packages.

**Comment by nsoranzo** [comment]
From @msarahan's comment in #11452:
> The problem here is basically the same as people see with python.  Specifying any kind of constraint for python or R breaks conda-build's handling of it.  The core languages are very special cases.  It is best to use
>
>```
>build:
>  skip: True  # [some r version limit]
>```
>
> instead.  PRs to improve this part of conda-build would be most welcome.

**Comment by bgruening** [comment]
@dpryan79 any change you can push your skeleton changes somewhere? Our bioconductor friends would like to build on top of this and improve it.

**Comment by dpryan79** [comment]
I don't have any changes to push at the moment, I just made ad hoc scripts to change things. When is the next release due? It's pretty soon as I recall. My goal was to finish with the last one and then work on the skeleton (assuming no one else updated it first).
