### ISSUE TITLE
Building old version of SPAdes after merging new recipe

### ISSUE THREAD

**Issue by nickp60** [bioconda/bioconda-recipes#11473]
Hi all,
I added a recipe for SPAdes 3.9.1 (a minor version that includes a bugfix for use on OSX).  The recipe was[ merged last week](https://github.com/bioconda/bioconda-recipes/pull/11397), but it seems that the build is not available to be installed yet.  Is there a step I am missing when it comes to triggering a build for legacy versions?

Any help would be appreciated!

**Comment by bgruening** [comment]
Those version are now online. Will close this issue. Thanks @nickp60 for all your PRs!
