### ISSUE TITLE
Cannot find scaffold_builder

### ISSUE THREAD

**Issue by metageni** [bioconda/bioconda-recipes#11480]
A few months ago I have created this receipt (https://github.com/bioconda/bioconda-recipes/tree/master/recipes/scaffold_builder). However, I cannot install it using 

`conda install scaffold_builder`
or
`conda create -n scaffold_builder -c bioconda scaffold_builder`
`source activate scaffold_builder`

Also, I cannot find it here (https://bioconda.github.io/recipes.html)

**Comment by metageni** [comment]
@bgruening: Any idea what is up here?

**Comment by bgruening** [comment]
Hi @metageni I only have a guess, please see here: https://github.com/bioconda/bioconda-recipes/pull/12818

**Comment by metageni** [comment]
@bgruening: Thanks
