### ISSUE TITLE
Binaries copies from singularity container to $HOME fail to load shared libs

### ISSUE THREAD

**Issue by pvanheus** [bioconda/bioconda-recipes#11579]
I noticed this problem while debugging a `searchgui` problem. The `searchgui` package essentially creates a copy of its environment in a path controlled by the user (something under $HOME) when the `eu.isas.searchgui.cmd.PathSettingsCLI` function in run. This means that binaries such as `tandem` (from the [X!Tandem](https://omictools.com/x-tandem-tool)) are copied from the container to the path under $HOME.

When trying to run these binaries in a Singularity container built from the *quay.io* Docker image for `searchgui` an error is reported: `error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory` - I *suspect* this has something to do with how mounts work in Singularity.

I reproduced the error with a simpler example. Starting with this C++ program:

```
#include <iostream>

int main(int argc, char *argv[]) {
  std::cout << "hello world" << std::endl;
}
```

I compiled a binary `hello` (with `g++ -o hello hello.cc`) and then created a Docker image using this Dockerfile:

```
FROM quay.io/biocontainers/diamond:0.9.21--1

COPY hello /usr/local/bin

ENTRYPOINT /bin/bash
```

and uploaded the resulting image to Docker Hub as `pvanheus/singularity-test:latest`. I then created a Singularity image with `singularity build singularity-test.simg docker://pvanheus/test-singularity:latest` and tried to run `hello`:

```
$ singularity exec test-singularity.simg hello
hello: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```
(singularity version 2.5.2)

This appears to be a Singularity bug triggered by the way that `searchgui` operates. A fix could be to either fix Singularity or avoid `searchgui`'s practice of copying binaries outside the container.

**Comment by bgruening** [comment]
We once discussed to not ship the binaries with SG and compile them on our own, but upstream did not recommend this :(

**Comment by pvanheus** [comment]
I don't believe that that would fix this problem. Somehow SG needs to not rely on binaries running in $HOME.

**Comment by bgruening** [comment]
@pvanheus can you please try the new Singularity container from https://depot.galaxyproject.org/singularity/ they are all newly build against Singularity 3.
