### ISSUE TITLE
epa-ng: Error building on Mac os X

### ISSUE THREAD

**Issue by gavinmdouglas** [bioconda/bioconda-recipes#11617]
I've been working on a conda recipe for EPA-NG (https://github.com/Pbdas/epa-ng) and thanks to @ebolyen's gracious help I managed to get the recipe working in the Linux docker container, see PR here: https://github.com/bioconda/bioconda-recipes/pull/10902. I'm running into a different issue when building the tool in the Mac OS X container (see below). I should mention that the authors haven't tested the tool on Mac OS X and they don't guarantee that it's installable on Macs. Is this a requirement for bioconda recipes?

```
/Users/distiller/project/miniconda/conda-bld/epa-ng_1540400737097/work/build/genesis_unity_sources/lib/all.cpp:17912:56: error: allocating an object of abstract class type 'const utils::ColorNormalization'
        tree, params, std::vector<utils::Color>{}, {}, {}, svg_filename
                                                       ^
/Users/distiller/project/miniconda/conda-bld/epa-ng_1540400737097/work/libs/genesis/lib/genesis/utils/tools/color/normalization.hpp:168:20: note: unimplemented pure virtual method 'normalize_' in 'ColorNormalization'
    virtual double normalize_( double value ) const = 0;
                   ^
/Users/distiller/project/miniconda/conda-bld/epa-ng_1540400737097/work/libs/genesis/lib/genesis/utils/tools/color/normalization.hpp:173:18: note: unimplemented pure virtual method 'is_valid_' in 'ColorNormalization'
    virtual bool is_valid_() const = 0;
                 ^
/Users/distiller/project/miniconda/conda-bld/epa-ng_1540400737097/work/build/genesis_unity_sources/lib/all.cpp:17923:45: error: allocating an object of abstract class type 'const utils::ColorNormalization'
        tree, params, color_per_branch, {}, {}, svg_filename
```

I specified these compiler versions for the compilation: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/delly/conda_build_config.yaml

Has anyone run into similar errors when building C++ tools on Mac OS X? Alternatively are there other clang settings that anyone could recommend?

Thanks!

Gavin

**Comment by epruesse** [comment]
>  Is [macos] a requirement for bioconda recipes?

@gavinmdouglas We strongly prefer to have both linux and osx binaries, but it's not mandatory. You can use `build: skip: True # [osx]` to skip the build on macos. 

W.r.t to your error message: That's simply a bug in the code. GCC doesn't catch it, but CLANG does, and it thinks it's grave enough to abort compilation.

Background: In C++, abstract classes are classes which contain "pure virtual methods", methods lacking an implementation. GCC will allow you instantiate such classes, but if you call the method, the program will crash. 

So in this case, epa-ng is using something out of the genesis library that's not meant to be used that way. Sounds like something for upstream to deal with though...

**Comment by gavinmdouglas** [comment]
Thanks for getting back to me @epruesse. I'll let the developers know about this error.

**Comment by lczech** [comment]
Hi @gavinmdouglas,

I am the developer of the genesis library that EPA-ng is using. Thanks for catching that bug! It is a bit weird though, because genesis is also tested with clang, and this issue is something that should have popped up earlier... Can you please tell me which clang version you used exactly?

Anyway, the problem was in a small helper function that was totally unrelated to EPA-ng, so nothing to worry about. It is fixed now in genesis, so now EPA-ng needs to update to the latest genesis version, and then everything should work fine!

Lucas

**Comment by epruesse** [comment]
@lczech Have a look at `clang-tidy`. Pretty nifty.

**Comment by gavinmdouglas** [comment]
Thanks for getting back to me so quickly @lczech! I'll keep an eye out for the updated genesis version to be linked to EPA-NG.

Gavin

**Comment by gavinmdouglas** [comment]
Also, you can see the full report [here](https://circleci.com/gh/bioconda/bioconda-recipes/30845?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) @lczech: 

The clang version tested was 4.0.1, here are the exact versions:
```
clang:           4.0.1-h662ec87_0                 
clang_osx-64:    4.0.1-h1ce6c1d_11                
clangxx:         4.0.1-hc9b4283_0                 
clangxx_osx-64:  4.0.1-h22b1bf0_11
```

**Comment by lczech** [comment]
Thanks for posting the full report, which also revealed some other issues that @Pbdas and I need to work on. It seems, OpenMP is not found with this version of Clang (a common issue with Clang...), which will make EPA-ng single threaded... We will look into this and let you [on the EPA-ng issue page](https://github.com/Pbdas/epa-ng/issues/18) once we found solutions to all the issues.

**Comment by gavinmdouglas** [comment]
Hi again, @epruesse - with the developers' help the package has built successfully! See PR https://github.com/bioconda/bioconda-recipes/pull/10902


Best,

Gavin
