### ISSUE TITLE
StageR anaconda package

### ISSUE THREAD

**Issue by AngryMaciek** [bioconda/bioconda-recipes#11692]
Dear All,

Would anyone please be so kind to create an anaconda package out of Bioconductor's StageR?
I am following this [TUTORIAL](https://f1000research.com/articles/7-952/v1) to analyse transcripts usage
I don't know anything about creating anaconda packages, never done that and it would require too much of my time to focus on it right now...

Regards!
Maciek

**Comment by bgruening** [comment]
Hi @AngryMaciek,

we have written some documentation about this, have a look here: https://bioconda.github.io/contributing.html.

Especially interesting for you is this section about bioconductor: https://bioconda.github.io/guidelines.html#r-bioconductor

Hope that helps!
Bjoern
