### ISSUE TITLE
gnuplot error: libwebp.so.6

### ISSUE THREAD

**Issue by HTaekOppa** [bioconda/bioconda-recipes#11719]
Hi all,

I am trying to test this script https://github.com/josephryan/estimate_genome_size.pl.
After installing all necessary programs and dependencies via BioConda, I have used these two command first. 

# JellyPlot
jellyplot.pl spec1_25mer.histo

# Find Valleys
find_valleys.pl spec1_25mer.histo

And I got this error message.
gnuplot: error while loading shared libraries: libwebp.so.6: cannot open shared object file: No such file or directory system call to gnuplot failed.  Is gnuplot in path?

After searching for an answer, I tried to include "libwebp" onto preexisting "Genome_Estimate" package. 

conda install libwebp
Solving environment: done

# All requested packages already installed.

It was already installed. 

Any idea or suggestion to make this work?

Many thanks in advance!

Cheers,

Taek

**Comment by croth1** [comment]
I stopped maintaining bioconda's gnuplot version after migrating it to conda-forge. By now all bioconda versions of gnuplot are probably broken. The latest versions from conda-forge should however work fine:  https://github.com/conda-forge/gnuplot-feedstock
