### ISSUE TITLE
Error: Creating a dedicated VM with default image

### ISSUE THREAD

**Issue by PauAndrio** [bioconda/bioconda-recipes#11723]
Hello,

Since yesterday, every time we create a pull request for the biobb_model branch, CircleCI produces this error: 
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Build-agent version 0.1.900-892a9f73 (2018-10-25T15:49:42+0000)
Creating a dedicated VM with default image
We had an unexpected error preparing a VM for this build, potentially due to our infrastructure or cloud provider.  Please retry the build in a few minutes

Unexpected environment preparation error: failed to create host: An internal error occurred when provisioning resources for this job.  Provisioning Service returned status code: 503
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

Is it an error of the infrastructure or an error in recipe? Has anyone encoutered the same issue?

Regards,
Pau Andrio

**Comment by dpryan79** [comment]
Try rebasing your commits. I reran things on circleci and it's currently getting hung up on a package that was just added to conda-forge but already existed here (if you rebased then it would ignore that package).

**Comment by PauAndrio** [comment]
Thank you Davon,

That solved the problem!

Regards,
Pau
