### ISSUE TITLE
mzR build fails with undefined symbol "H5::LinkCreatPropList::DEFAULT"

### ISSUE THREAD

**Issue by sneumann** [bioconda/bioconda-recipes#11772]
The mzR build fails with 
```
Error: package or namespace load failed for ‘mzR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/conda/conda-bld/bioconductor-mzr_1540935780023/.../lib/R/library/mzR/libs/mzR.so':
  /opt/conda/conda-bld/bioconductor-mzr_1540935780023/.../lib/R/library/mzR/libs/mzR.so: undefined symbol: _ZN2H517LinkCreatPropList7DEFAULTE
```
where the unresolved symbol is `c++filt _ZN2H517LinkCreatPropList7DEFAULTE`
becomes de-mangled: `H5::LinkCreatPropList::DEFAULT`

https://circleci.com/gh/bioconda/bioconda-recipes/31750?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by sneumann** [comment]
Hi, picking up again. I would like to bump some versions 
to see if that fixes the SEGV. I am unsure which changes I can do, 
I tried to bump rhdf5 to Bioc release-3.8 rhdf5-1.4.1
but 1) I don't know if I have the freedom to do that here, 
and 2) I get errors `conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: set(["bioconductor-rhdf5lib[version='>=1.4.1,<1.6.0']"])` 
because I don't know my way around. 

=> Any suggestions ?

**Comment by bgruening** [comment]
1.4.1 is not yet build in bioconda. There is some ongoing work to build __all__ bioc packages at once. But this will take a week or two until we start.

**Comment by sneumann** [comment]
Ok, waiting until then. My current state is in https://github.com/phnmnl/bioconda-recipes/tree/fix11722
with manual update to rdhf5lib-1.4.1 and mzR-2.16.0, but some nasty dependencies 
still on BioC-3.6 versions. And still SEGV. Sigh.

**Comment by bgruening** [comment]
@sneumann can you check the state of this and maybe open a new issue if this is still valid. Thanks.

**Comment by sneumann** [comment]
Hi, unfortunately I am lost and have no idea how to check among the myriad 
of jobs on https://circleci.com/gh/bioconda/bioconda-recipes Yours, Steffen
