### ISSUE TITLE
CircleCI not running

### ISSUE THREAD

**Issue by holmrenser** [bioconda/bioconda-recipes#11781]
#11712 is not being tested for a while now. Also, there is only one expected check listed: test-macos, whereas this normally are three checks: lint, test-linux, and test-macos.
In addition, test-linux failed earlier this week because of a missing docker container:
https://circleci.com/gh/bioconda/bioconda-recipes/32184

I am not really sure what is going on, but currently my package is not building, so I would love some tips to get this fixed.

**Comment by holmrenser** [comment]
That indeed seems to have triggered tests to run again. However, only linting and test-macos are listed. Why not test-linux?

Additionally, the linting test fails on ```recipes/r-maldiquant``` which is not related to my recipe, nor anything I have ever worked on.

The error is 
```
recipes/r-maldiquant	in_other_channels	{'exists_in_channels': {'conda-forge'}, 'fix': 'consider deprecating'}	{'conda-forge'}	consider deprecating
```

https://circleci.com/gh/bioconda/bioconda-recipes/32269

**Comment by druvus** [comment]
Please merge in master into branch. It got outdated wheel the large bulk run got merged some days ago.

**Comment by holmrenser** [comment]
Thanks! Problem solved!

**Comment by SilasK** [comment]
It seems I have the same problem:

```
	recipe	check	info	exists_in_channels	fix
0	recipes/r-maldiquant	in_other_channels	{'exists_in_channels': {'conda-forge'}, 'fix': 'consider deprecating'}	{'conda-forge'}	consider deprecating
Exited with code 1

```

#12278

https://circleci.com/gh/bioconda/bioconda-recipes/34590?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by SilasK** [comment]
I managed to make a simple conda profile.

**Comment by Chris-Lowe-Integrity** [comment]
I am having the exact same issue.  Does anyone have a solution/explanation?

https://circleci.com/gh/bioconda/bioconda-recipes/34681?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Chris-Lowe-Integrity** [comment]
I attempted to merge and my branch is up date

**Comment by Chris-Lowe-Integrity** [comment]
Update: The test passed this time.  I would still like to know what was behind the issue if anyone knows.
