### ISSUE TITLE
Genomepy 0.5.2 is not available

### ISSUE THREAD

**Issue by simonvh** [bioconda/bioconda-recipes#12079]
@bioconda/core (Sorry for pinging all of you, I don't who to ask specifically)

Some time ago I have added a new version of genomepy (0.5.2, PR #11267). It seems to be merged correctly, however the package is not available. Genomepy used to be present in the blacklist, but I removed it and as far as I can see it is not in there anymore. 

Any thoughts?

**Comment by epruesse** [comment]
Try bumping the build number. That should trigger a rebuild. Could be that something failed in the build pipeline (docker offline, CircleCI didn't catch the merge, ...)

**Comment by simonvh** [comment]
Too simple. Thanks! :)
