### ISSUE TITLE
Manta 1.4.0 failing to build/install

### ISSUE THREAD

**Issue by marchoeppner** [bioconda/bioconda-recipes#12086]
Hi,

just tried to install Manta (1.4.0) through Bioconda and am getting the following error using miniconda2, 4.5.1:

The following NEW packages will be INSTALLED:

    manta: 1.4.0-py27_1 bioconda

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for manta located at /home/sukmb352/.conda/pkgs/manta-1.4.0-py27_1
appears to be corrupted. The path 'share/manta-1.4.0-1/libexec/DumpSVLoci'
specified in the package manifest cannot be found.

CondaVerificationError: The package for manta located at /home/sukmb352/.conda/pkgs/manta-1.4.0-py27_1
appears to be corrupted. The path 'share/manta-1.4.0-1/libexec/EstimateSVLoci'
specified in the package manifest cannot be found.

CondaVerificationError: The package for manta located at /home/sukmb352/.conda/pkgs/manta-1.4.0-py27_1
appears to be corrupted. The path 'share/manta-1.4.0-1/libexec/GenerateSVCandidates'
specified in the package manifest cannot be found.

CondaVerificationError: The package for manta located at /home/sukmb352/.conda/pkgs/manta-1.4.0-py27_1
appears to be corrupted. The path 'share/manta-1.4.0-1/libexec/GetAlignmentStats'
specified in the package manifest cannot be found.

CondaVerificationError: The package for manta located at /home/sukmb352/.conda/pkgs/manta-1.4.0-py27_1
appears to be corrupted. The path 'share/manta-1.4.0-1/libexec/GetChromDepth'
specified in the package manifest cannot be found.

CondaVerificationError: The package for manta located at /home/sukmb352/.conda/pkgs/manta-1.4.0-py27_1
appears to be corrupted. The path 'share/manta-1.4.0-1/libexec/TestAssembler'
specified in the package manifest cannot be found.

SafetyError: The package for manta located at /home/sukmb352/.conda/pkgs/manta-1.4.0-py27_1
appears to be corrupted. The path 'share/manta-1.4.0-1/libexec/samtools'
has a sha256 mismatch.
  reported sha256: 1c1f9e148c0f1c77eb2311c92521091d0f81fbc7f93cba25f80434ab07849efe
  actual sha256: 991d27b2fb8a9d6eac737b30c2825b025132ecf0969f5bbbb6f46fa9e0f54bb0

**Comment by epruesse** [comment]
@marchoeppner This looks like you may have run out of disk space on the way. Move the unpacked package aside (`mv /home/sukmb352/.conda/pkgs/manta-1.4.0-py27_1 manta_bkup`) and try again after making sure you've got enough disk space. If that works, delete the backup (`rm -rf manta_bkup`).

I'm closing this for now. Reopen if this didn't help.
