### ISSUE TITLE
Cleanninng swap files 

### ISSUE THREAD

**Issue by ypriverol** [bioconda/bioconda-recipes#12087]
Hi all: 
Can some one add to travis an step to check for files that are not needed in the building process like this https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-complexheatmap/.meta.yaml.swp looks like a file a a swap file system file.

**Comment by ypriverol** [comment]
ping @bgruening

**Comment by epruesse** [comment]
Should go into lint?

**Comment by ypriverol** [comment]
I don't know what is the best way to clean all the temp files this that has been edited probably manually. I can try to do a PR cleanning all of them if you want @epruesse

**Comment by epruesse** [comment]
@ypriverol Yes, that would be very welcome. Ping me for review&merge.

**Comment by ypriverol** [comment]
@epruesse PR https://github.com/bioconda/bioconda-recipes/pull/12137 At the end was only one file

**Comment by epruesse** [comment]
@ypriverol thanks anyway!
