### ISSUE TITLE
Biocontainers image not available for new recipe

### ISSUE THREAD

**Issue by philres** [bioconda/bioconda-recipes#12097]
Hi,

don't know if this is the right place to post this, but I added recipe for a new tool to bioconda a bit more then two days ago.

I can install it through conda and it showed up on the available packages on the bioconda webpage: https://bioconda.github.io/recipes/qcat/README.html

However, there is no image in biocontainers.

I was wondering how to find out what went wrong there. For the other recipes I uploaded (a while back though) it always worked.

Thanks,
Philipp

**Comment by bgruening** [comment]
There is a slight delay in making them public. It should be there now. Enjoy!

**Comment by philres** [comment]
Yes it is there now. Thanks a lot!

**Comment by bgruening** [comment]
You are welcome!
