### ISSUE TITLE
R packages not on CRAN

### ISSUE THREAD

**Issue by hvaret** [bioconda/bioconda-recipes#12091]
Dear all,

I just realized that the SARTools R package I try to maintain now appears in the build-fail-blacklist file as it is not on the CRAN (nor on Bioconductor).

Maybe I missed an important information, but is there a new policy about these packages? Would it be possible to remove it from the list in order to allow users to install the last version?

Thanks for your help,

Best regards,

Hugo

**Comment by druvus** [comment]
It was probably placed there during migration to cb3 or R version update due failed build caused by missing dependencies. You are welcome to remove it from blacklist and bump version in a new PR to get it rebuilt.

**Comment by hvaret** [comment]
Thanks @druvus for your help, it seems to be OK.
Best,
Hugo
