### ISSUE TITLE
gffcompare newest version not available

### ISSUE THREAD

**Issue by bernt-matthias** [bioconda/bioconda-recipes#12353]
Despite two more recent pull requests (https://github.com/bioconda/bioconda-recipes/pull/12308, https://github.com/bioconda/bioconda-recipes/pull/11517) which upgraded gffcompare to 0.10.6 the latest installable version is still 0.10.1. 

Wondering if there is something wrong with the recipes?

**Comment by epruesse** [comment]
It's blacklisted. Open a PR removing gffcompare from the file build-fail-blacklist and work from there.
