### ISSUE TITLE
cannot compile xhmm

### ISSUE THREAD

**Issue by drramki-chop** [bioconda/bioconda-recipes#1243]
Cannot compile xhmm (https://bitbucket.org/statgen/xhmm/overview) as it fails with not finding libblas. I have tried openblas and atlas recipes but it doesn't help (and tried with a modified makefile as well).

**Comment by johanneskoester** [comment]
Are you referring to a particular recipe?

**Comment by drramki-chop** [comment]
I am trying to create a recipe for the CNV tool xhmm and one of the failing requirements is libblas.

**Comment by johanneskoester** [comment]
Can you create a PR? This makes it easier for us to find the problem, because we see your code.

**Comment by bgruening** [comment]
@drramki-chop please create a PR and ask for help. We will see if we can fix it!

Thanks!

**Comment by holtgrewe** [comment]
@drramki-chop It's been a while but this has been resolved in #10183, I think.
