### ISSUE TITLE
Nominating @epruesse to become a core team member

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#12475]
Hi all and especially @bioconda/core!
I would like to nominate @epruesse to become a member of the Bioconda core team. In the past months and years, he has made numerous contributions to our framework, packages, and the paper. This has culminated in the current efforts on developing the much awaited autobump functionality which will bring us automated updates for many packages, thereby greatly reducing everybodies workload.

Please let us know whether you support this.

**Comment by bgruening** [comment]
Oh yes! Of course! @epruesse rocks! :+1:

**Comment by chapmanb** [comment]
That would be awesome. Elmar +1

**Comment by tomkinsc** [comment]
+1 !

**Comment by druvus** [comment]
totally agree! +1

**Comment by daler** [comment]
Absolutely!

**Comment by epruesse** [comment]
Thank you guys!

I remember when @mdehollander was asking about binaries for SINA for Bioconda. The ones I had been offering didn't work on the CF/anvil docker image.  When I started looking into the project I was like **"The world has needed *THIS* for a long time!"**. So thank you all even more for creating Bioconda and for the countless hours I know you have each invested into making this work. I don't believe there is any other project as relevant to an entire field of science as what you have created here. It literally changes the game.

And so I'm proud to have been given the opportunity to become part of the team. It's been a great experience working with you all!

**Comment by mdehollander** [comment]
+1 Elmar has done great work creating a package for SINA and in general for bioconda. I will have a look at this autobump, that would be a fantastic feature.

**Comment by johanneskoester** [comment]
Ok, I think we have an agreement here. Welcome to bioconda/core, @epruesse!

**Comment by epruesse** [comment]
Thanks again guys! Looking forward to working more on Bioconda's infrastructure :)
