### ISSUE TITLE
Packaging GATK-protected

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#1247]
I just had a look at this repository:
https://github.com/broadgsa/gatk-protected/

These seem to be the official sources of GATK including the non-commercial licensed parts (e.g. the callers I think). We have other non-commercial license software in bioconda. Hence, my question is, can't we package this as well? Both the anaconda page and the bioconda homepage will clearly state that this is non-commercial use only.

@bioconda/core any thoughts?

**Comment by johanneskoester** [comment]
Looking into the license, this passage might be problematic:

> 2.2 No Sublicensing or Additional Rights. LICENSEE shall not sublicense or distribute the PROGRAM, in whole or in part, without prior written permission from BROAD. LICENSEE shall ensure that all of its users agree to the terms of this Agreement. LICENSEE further agrees that it shall not put the PROGRAM on a network, server, or other similar technology that may be accessed by anyone other than the LICENSEE and its employees and users who have agreed to the terms of this agreement.

**Comment by kyleabeauchamp** [comment]
That is pretty clearly a no-go IMHO.  Furthermore, even in the absence of such a clause, I don't think it's safe to assume that you have "redistribution" rights for binaries.

**Comment by kyleabeauchamp** [comment]
For example, all of the latest UCSC tools.

**Comment by kyleabeauchamp** [comment]
Also regarding ucsc, we should stop using varies in license field.

**Comment by chapmanb** [comment]
You aren't allowed to re-distribute GATK, unfortunately. This has been the source of a lot of effort on building workarounds in bcbio. I'm having a conversation with the Broad team about allowing it in docker, but it's not yet clear if it will be possible. I'll ask their thoughts on bioconda as part of this conversation.

**Comment by johanneskoester** [comment]
Great, thanks Brad!
@kyleabeauchamp we are building ucsc packages from source, right? Does that also have these problems?

**Comment by kyleabeauchamp** [comment]
AFAIK yes.  Here is the license info:

http://genome.ucsc.edu/license/

It's noncommerical, so we at the very least need each yaml file to say that this component has a non-commericial license.  It's not clear to me that you are allowed to redistribute without their permission, even for academics.

**Comment by johanneskoester** [comment]
Well, the source code and binaries are freely available for academic use. Question is if redistribution via bioconda and installation by academic users can be seen as academic use. At least they don't disallow redistribution.

**Comment by kyleabeauchamp** [comment]
At the very least, we need to fix the license section in the yaml files.

**Comment by johanneskoester** [comment]
Yes indeed. We should provide a license file and specify the license as "Custom". @yhoogstrate, you are currently working on ucsc recipes. Are you interested in changing the script accordingly? We could help with the details.

**Comment by jxtx** [comment]
I do not think this is entirely accurate. Most of the code is under a
permissive license, "free for all use public private or commercial"

  https://github.com/ENCODE-DCC/kentUtils/blob/master/src/lib/README

The Genome Browser itself and Blat are under a different license which does
not allow commercial use without permission.

**Comment by xguse** [comment]
So I am gearing up to use GATK a lot and would REALLY like it to be as easy as including it in a requirements.txt file in my snakemake pipeline folder so it can be as portable as possible (at least across systems that I have user privileges on).

So I began writing a recipe that would source a local copy of `GenomeAnalysisTK-3.5.tar.bz2` and build a conda pkg that I could install easily. I was basing the recipe on the picard recipe, but it occurred to me that this discussion was also going on here at the moment.

What if we just supplied a standardized recipe that uses an environment var like `$GATK_v35_TARBALL` that at least let everyone build their own standard pkg after they obtained the code, however, is appropriate for them to obtain the code?  Perhaps this could use the `build.skip` yaml tag to prevent its inclusion in the travis build tests.

Anyway, I am not sure how annoying people would find such a manual-ish build-install operation for this but I can tell you that I for one would welcome a similar method.

**Comment by johanneskoester** [comment]
@xguse I have also thought about some in this direction. What about the following: we add a recipe that installs

* a wrapper script ``gatk`` that basically invokes java with the GATK jar file and forwards all additional arguments.
* a script ``gatk-register`` that takes a GATK tarball and installs it into ``$PREFIX/usr/share/gatk``.

The workflow for the user would be
```
conda install gatk
gatk-register path/to/GenomeAnalysisTK-3.5.tar.bz2
```

If ``gatk`` is called without first calling gatk-register, the wrapper will exit with an error message describing what to do.

What do you think?

**Comment by xguse** [comment]
I actually like that MUCH better. It is cleaner and doesn't make folks have to download the bioconda repo, change a recipe meta.yaml tag from True to False, build the bloody recipe and THEN install it.

One problem I see though, is that without tying the GATK version number to the build itself, I don't know how we enforce which GATK jar version they supply to the register script.  I suppose the register script could be tasked with that job though... Just have the script check for a hardcoded version number that is established by the original build recipe.

Yeah, actually that is certainly better than what I did for myself.

**Comment by johanneskoester** [comment]
Yes, the register script should do the check, and we build the script dynamically with the version of the recipe.

**Comment by tomkinsc** [comment]
@johanneskoester The gatk-register solution is a good workaround to the gatk licensing problem. Is anyone working on it? @bioconda/core

**Comment by tomkinsc** [comment]
Closing this for now due to #1683, at least until the GATK license terms change.

**Comment by tomkinsc** [comment]
GATK3 can now be redistributed! See PR #7138
