### ISSUE TITLE
mummerplot does not work out of the box

### ISSUE THREAD

**Issue by tiagoantao** [bioconda/bioconda-recipes#1254]
The subject is mostly self-explanatory, mummerplot does not seem to work out of the box. My user is getting:

```
Can't use 'defined(%hash)' (Maybe you should just omit the defined()?) at .../conda/bin/mummerplot line 884.
```

**Comment by tiagoantao** [comment]
ping @tomkinsc

**Comment by tomkinsc** [comment]
What OS are you running this under, and what version of perl (`perl -v`)?

**Comment by tiagoantao** [comment]
Linux, perl 5.22 (The one made available on bioconda)

```
This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi
```

**Comment by tomkinsc** [comment]
This probably a matter of patching to remove "defined" from the conditionals on the following lines, and pinning Perl to v5.22.

```
884
894
981
991
1034
1044
```

Can someone with more Perl experience weigh in?

**Comment by rvalieris** [comment]
as described in [defined](http://perldoc.perl.org/functions/defined.html), simply removing the defined in these cases should solve the problem, but I don't think pinning perl is necessary, a simple if(%hash) should also work in older versions, quoting from [release notes](http://perldoc.perl.org/perl5220delta.html#defined(%40array)-and-defined(%25hash)-are-now-fatal-errors):
>  These have been deprecated since v5.6.1 

to patch these out, put this in the build.sh:
```perl
perl -i -pe 's/defined \(%/\(%/' mummerplot
```
