### ISSUE TITLE
can not conda install bcool/bwise

### ISSUE THREAD

**Issue by Malfoy** [bioconda/bioconda-recipes#12559]
I added two recipes to bioconda recently: bwise and bcool.
They were successfully merged but I can not install them using the conda install command : 

 conda install bwise
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - bwise

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/r/linux-64
  - https://conda.anaconda.org/r/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Is there a problem ?

**Comment by bgruening** [comment]
Your PR was never merged until now: https://github.com/bioconda/bioconda-recipes/pull/12456 :)
