### ISSUE TITLE
migrate cwltool to conda-forge

### ISSUE THREAD

**Issue by croth1** [bioconda/bioconda-recipes#12550]
As cwl is not bio specific, I suggest we migrate cwltool to conda-forge:

https://github.com/conda-forge/staged-recipes/pull/7214

On a side effect, we get a windows build and it will be easier to maintain 👍

**Comment by bgruening** [comment]
ping @chapmanb

**Comment by chapmanb** [comment]
Christian;
Moving to conda-forge is great, thanks so much for doing all the work. If you want to add me as a recipe maintainer I can also help with keeping it up to date there. Thanks again.

**Comment by croth1** [comment]
Merged in CF. Anything else we have to do here?

**Comment by chapmanb** [comment]
Christian;
Thanks again for all this work. I tried to re-start some of the workflows like schema-salad as they initially failed because dependencies weren't yet built in conda-forge. Beyond that, we should remove all the recipes you migrated from bioconda and then be good to go. Thank you again.
