### ISSUE TITLE
Deepvariant --regions should be optional

### ISSUE THREAD

**Issue by GhisF** [bioconda/bioconda-recipes#12560]
deepvariant 0.7.1

The --regions argument of the dv_make_examples.py script should be optional.
DeepVariant can run without intervals for wgs calling.

**Comment by bgruening** [comment]
ping @chapmanb

**Comment by chapmanb** [comment]
Thanks much for the suggestion. The latest deepvariant build makes `--regions` optionally and will hopefully work for your needs. Please let us know if you run into any issues.
