### ISSUE TITLE
Version 0.43.0 instead of 0.45.0

### ISSUE THREAD

**Issue by chrarnold** [bioconda/bioconda-recipes#12589]
Hi, I installed kallisto via conda:

`kallisto                  0.45.0               hdcc98e5_0    bioconda`

I explicitly asked for 0.45.0, and conda list shows me also that 0.45.0 is installed. However, 

```
$ kallisto version
kallisto, version 0.43.0
```

What is going on here?

**Comment by bgruening** [comment]
All I can say is that we are fetching the correct tarball: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/kallisto/meta.yaml

And according to this commit: https://github.com/pachterlab/kallisto/commit/0c950a3579b2691eada652f6a106d14473e4e467 I think kallisto is reporting a wrong version.

ping @pmelsted to be sure.
