### ISSUE TITLE
Use the holy build box as a basis for our linux builds

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#126]
Brant Faircloth has suggested to use the https://github.com/phusion/holy-build-box for building. If we base our docker image on that, we might be able to get rid of some complexity in the dockerfile.

**Comment by daler** [comment]
I haven't played around with it yet, but [this page of the docs](https://github.com/phusion/holy-build-box/blob/master/TUTORIAL-2-COMPILATION-SCRIPT.md) says the environment has to be activated before use.

If every conda recipe has to be modified to activate the environment, then I don't think trading recipe complexity for dockerfile complexity would be worth it. But if this can be done in the high-level build script, then no prob.

**Comment by johanneskoester** [comment]
I actually thought we would only use their docker container instead of CentOS 5 as base image. My impression was that this way we just won't need the lines installing libs and compilers.
The rest (like our conda build script and so on), I would not change at all.

**Comment by daler** [comment]
Ah, in that case it seems like a good way to simplify.

**Comment by ostrokach** [comment]
I am in favour of this. 

I remember having issues compiling packages on CentOS 5 because gcc and autotools are very old. I was even adding gcc and autotools (m4, autoconf, automake, libtool, pkg-config) to the conda recipe in order to compile with the newer versions. Using the `holy-build-box` should fix this because it already comes with [a newer version of gcc and autotools](https://github.com/phusion/holy-build-box#isolated-build-environment-based-on-docker-and-centos-5).

**Comment by kyleabeauchamp** [comment]
FWIW, Centos5 is no longer supported by NVIDIA CUDA, which is currently only available for Centos 6 and Centos7 (https://developer.nvidia.com/cuda-downloads).  I don't think that matters for any of you, but it was a limiting factor for my work on another recipe repo (https://github.com/omnia-md/conda-recipes).

**Comment by kyleabeauchamp** [comment]
We were able to get reasonably portable linux binaries on a Centos6 build.

**Comment by kyleabeauchamp** [comment]
FWIW I just closed pull #787 because the upstream binaries were built on centos 6.  AFAIK, if we were using the holy build box, the upstream binaries would have been totally OK.

**Comment by kyleabeauchamp** [comment]
I'm not saying we need to upgrade now, but I think we might as well compile a list of pros / cons for an upgrade.

**Comment by johanneskoester** [comment]
That makes sense. We should consider it!

**Comment by kyleabeauchamp** [comment]
FWIW, I noticed that my previous collaborators use a version of the holy build box that has been extended to include CUDA, OPENCL, and TexLive:

https://github.com/omnia-md/omnia-build-box/blob/master/Dockerfile

Could be useful if we do decided to go the holy build box route.  In particular I'm pretty sure CUDA cannot be installed in userspace, so this would be the only way to support it.

**Comment by bgruening** [comment]
For now we are using whatever conda-forge is using. Let's propose this to conda-forge if we think it is the correct approach. Will close this issue now.
