### ISSUE TITLE
Rscript requirement to install and run program

### ISSUE THREAD

**Issue by dariober** [bioconda/bioconda-recipes#12622]
Hi- I'm trying to submit a recipe under branch [cnv_facets](https://github.com/bioconda/bioconda-recipes/tree/cnv_facets/recipes/cnv_facets). This is a program that uses Rscript to install some R dependencies and to run the program itself on the command line (more [here](https://github.com/wwcrc/cnv_facets), if relevant). 

The problem is that Rscript doesn't seem to be available during the build. When the installation script [setup.sh](https://github.com/wwcrc/cnv_facets/blob/master/setup.sh) is executed I get 

```
setup.sh: line 116: Rscript: command not found
```

See: https://circleci.com/gh/bioconda/bioconda-recipes/37250?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

My [meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/cnv_facets/recipes/cnv_facets/meta.yaml) already includes:

```
requirements:
  run:
    - r-base
```

How do I make Rscript available? Thanks!

**Comment by bgruening** [comment]
You should define the packages that this tool needs as a requirement. It's not intended that the packages are installed during runtime.

To answer your question, you could but r-base as a `host` dependency in.
