### ISSUE TITLE
poretools not installing

### ISSUE THREAD

**Issue by burkesquires** [bioconda/bioconda-recipes#1266]
When I try to install poretools I get the following error:

[ squiresrb L01891689  ~ ]$ conda install poretools
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: .
Error:  Package missing in current osx-64 channels: 
  - poretools

Did you mean one of these?

    r-devtools, pybedtools, dreamtools

You can search for this package on anaconda.org with

    anaconda search -t conda poretools

**Comment by johanneskoester** [comment]
Same story, not build for osx so far. @emilhaegglund did we try to build on osx?

To clarify @burkesquires: bioconda switched building policies recently. Previously, we build linux-64 only per default. Now, we also build on osx per default, and the developer has to explicitly disable this if it does not work. However, most of the recipes are from before the change. Hence an osx build often has not been tried.

**Comment by daler** [comment]
Hi Burke - 
poretools is currently not built for OSX, likely due to the problems with HDF5 libraries (see #476) that still need to be resolved. It may be that recent versions of conda have fixed the problem, so I'll give #476 another shot.

**Comment by burkesquires** [comment]
Thanks Johannes and Ryan! I am just excited to see something like bioconda exist! Keep up the great work!
