### ISSUE TITLE
pomegranate not installing

### ISSUE THREAD

**Issue by burkesquires** [bioconda/bioconda-recipes#1267]
When I try to run the pomegranate install I get the following error:

[ squiresrb L01891689  ~ ]$ conda install pomegranate
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: .
Error:  Package missing in current osx-64 channels: 
  - pomegranate

You can search for this package on anaconda.org with

    anaconda search -t conda pomegranate
[ squiresrb L01891689  ~ ]$

**Comment by johanneskoester** [comment]
Hi, pomegranate is currently only build for linux-64, sorry. @druvus are the specific reasons for not building on osx did we just not try it so far?

Best,  
Johannes

**Comment by burkesquires** [comment]
Thanks Johannes

**Comment by druvus** [comment]
No specific reason but it should work. I will try to fix it now by #1270

**Comment by burkesquires** [comment]
That fixed it! Thanks!
