### ISSUE TITLE
ggbio Rsamtools dependency

### ISSUE THREAD

**Issue by ntraut** [bioconda/bioconda-recipes#12683]
I have a problem with ggbio 1.26.0 which depends on rsamtools 1.32.3
When I do: `conda install bioconductor-ggbio`
It installs:
```
bioconductor-ggbio:             1.26.0-r3.4.1_0       bioconda
bioconductor-rsamtools:         1.32.3-r341hfc679d8_0 bioconda
```
But when in R I do `library(ggbio)`, I get this error:
```
object path is not exported by namespace:Rsamtools
```
It seems related to the fact that Rsamtools does not export `path` in its newer version:
https://support.bioconductor.org/p/104313/

**Comment by ntraut** [comment]
I solved the problem for me by doing `conda install bioconductor-rsamtools=1.30`, but I do not understand why I had to do this manually, since this the dependency number which I found in `pkgs/bioconductor-ggbio-1.26.0-r3.4.1_0/info/recipe/meta.yaml`.

**Comment by bgruening** [comment]
We did not include an upper bound to bioc packages, which means as soon as we released a new version of rsamtools, ggbio would pick it up. All the new bioc packages which @dpryan79 is building since a month will have this upper bound and such error will not occur again. Sorry for the trouble.
