### ISSUE TITLE
Can not install bwise or bcool

### ISSUE THREAD

**Issue by Malfoy** [bioconda/bioconda-recipes#12717]
I added the bwise recipes to bioconda recently:
They were successfully merged but I can not install them using the conda install command :
conda install bwise
Solving environment: failedPackagesNotFoundError:
 The following packages are not available from current channels:
bwise

**Comment by epruesse** [comment]
Wasn't built for some reason. Merge says:
```
17:23:50 BIOCONDA INFO Nothing to be done for recipe recipes/bwise
```

**Comment by epruesse** [comment]
Ok. Your recipe now successfully fails. Have a look at #12753 - you should be able to push to that branch to continue working on this. Same changes are probably necessary for bcool as well.

**Comment by Malfoy** [comment]
Thank you for the bwise problem. But the bcool recipe do not fail

**Comment by epruesse** [comment]
The recipe did not fail because it was never built.

**Comment by bgruening** [comment]
I see a new PR, so closing this off.
