### ISSUE TITLE
Specifications were found to be in conflic

### ISSUE THREAD

**Issue by dariober** [bioconda/bioconda-recipes#12740]
Hi- I (successfully) submitted the package [cnv_facets](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/cnv_facets). However, when I try to install it on a fresh Ubuntu system I get:

```
conda install -c bioconda cnv_facets
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - cnv_facets
Use "conda info <package>" to see the dependencies for each package.
```

The suggested `conda info cnv_facets` returns no error and no output. Any help understanding what's going on much appreciated!

Dario

**Comment by epruesse** [comment]
You need to configure your channels to include bioconda and conda-forge. See https://bioconda.github.io/#set-up-channels

If you do, `conda create -n demo_env cnv_facets` will work as expected.

Your `conda info` line is missing the `-c bioconda` to show anything (you won't need that once you have persistently added the bioconda and conda-forge channels).
