### ISSUE TITLE
Log of download requests for bioconda package

### ISSUE THREAD

**Issue by Adamtaranto** [bioconda/bioconda-recipes#12750]
Is there data available for the number of times a bioconda package has been installed by users? 

If this is logged somewhere could we get API access to build a download tracker? Would also be good to know which packages are never downloaded so that they can be removed or relocated.

**Comment by Adamtaranto** [comment]
There was some talk a while back about creating a bioconda-beta repo for pre-release packages. I can't find the thread, did that ever happen?

**Comment by epruesse** [comment]
> Is there data available for the number of times a bioconda package has been installed by users?

Yes. A count is maintained by anaconda cloud. At the top of each recipe "vignette", you'll find a badge that shows it. See e.g. https://bioconda.github.io/recipes/sina/README.html

If you click on the badge, and then select the files tab, you'll see the exact number of downloads for each package binary file (https://anaconda.org/bioconda/sina/files).

Please be aware that those numbers can be significantly inflated by automated installs, in particular for commonly used tools. Those installs happen e.g. when a package is built here on Bioconda. Each time you trigger a build of a recipe, all of its dependencies will be installed. Similarly, if a tool is used for the unit tests of other tools, a download will be counted every time the unit tests for that tool are run. I'm pretty certain e.g. that SINA didn't get 5000 legitimate downloads by individual users.

> If this is logged somewhere could we get API access to build a download tracker? 

Anaconda has an API to query these numbers.

> Would also be good to know which packages are never downloaded so that they can be removed or relocated.

That would violate the reproducible science concept. Unless there is significant need (severely broken packages), they remain where they are.

> There was some talk a while back about creating a bioconda-beta repo for pre-release packages. I can't find the thread, did that ever happen?

No. So far, no-one has had the time for something like that. There may be more threads, but here is one: https://github.com/bioconda/bioconda-utils/issues/356
