### ISSUE TITLE
Nominating @dpryan79 to become a core team member 

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#12774]
Hi all!

I would like to nominate @dpryan79 to become a member of the Bioconda core team. In the past months and years, he has made numerous contributions to our framework and a lot of packages. 
Recently he was indispensable for the Bioconductor rebuilds and the overhaul of the Bioconductor skeleton generator. There is always a rebuild going on and Devon is always there to help - it would be nice to have him in the core team.

Please let us know whether you support this.

ping @bioconda/core

**Comment by kyleabeauchamp** [comment]
Agree

**Comment by chapmanb** [comment]
+1 Devon rocks. Thanks for nominating him Björn, I love these threads recognizing all the hard work the community puts into bioconda.

**Comment by daler** [comment]
Absolutely, Devon has been consistently a great help, whether it's solving tricky library issues, monitoring updates and rebuilds, or building infrastructure.

**Comment by druvus** [comment]
+1

**Comment by johanneskoester** [comment]
Yes, very good idea! Devon is an outstanding contributor!

**Comment by bgruening** [comment]
Awesome! @dpryan79 welcome to the Bioconda Core team!

**Comment by epruesse** [comment]
Welcome @dpryan79!
