### ISSUE TITLE
update phylowgs

### ISSUE THREAD

**Issue by vodkatad** [bioconda/bioconda-recipes#12841]
Hello fellow bioconders, I noticed that the phylowgs package since the last build package here has been changed in many aspects (mainly now it has multiple MCMC chains and there is a new, recommended, tool to perform this step).

Updating the recipe should be simple enough and I could work on it (bioconda-utils update and then a new ln in the recipe, it seems), I was just wondering if there is some sort of policy about updates or not, from the docs it seems to be perfectly ok to proceed but since the package changed a lot I preferred asking :)

**Comment by bgruening** [comment]
It's perfectly valid to update the package and then ping the owners/contributors and ask for help/comments. Thanks for asking and happy new year.

**Comment by vodkatad** [comment]
Working on it, locally it tested ok via docker (had to fix docker on my debian with the vsyscall=emulate kernel param though, I did not use docker for a bit...) but on circleci I'm getting "Too long with no output (exceeded 10m0s)" for macos, any ideas? https://circleci.com/gh/bioconda/bioconda-recipes/tree/updated_phylowgs (sorry for the first checks on a copy of master :/)

**Comment by dpryan79** [comment]
@vodkatad Were you able to get this built and merged in or is this still an open issue?

**Comment by vodkatad** [comment]
@dpryan79 honestly I did not find any explainable cause for the "Too long with no output" so not knowing what to change I stopped investigating - is it reasonable to trigger another build without changing anything? I can give another look this weekend, if the same error happen twice there should be something off in how I updated the recipe...

**Comment by dpryan79** [comment]
@vodkatad Rerunning things should suffice, though `master` will need to get merged in first. I'll merge the updated master branch in and then we can see if this is still an issue.

**Comment by dpryan79** [comment]
I don't know if you had a PR made already, so if not: https://github.com/bioconda/bioconda-recipes/pull/14128

**Comment by dpryan79** [comment]
I've merged in the update. Please feel free to reopen this if there are additional issues.
