### ISSUE TITLE
protein viwer in Jupyter notebook

### ISSUE THREAD

**Issue by hainm** [bioconda/bioconda-recipes#1305]
What do all of you think if I make a PR for a protein viewer in Jupyter notebook?

https://github.com/arose/nglview

Since bioconda focus on bioinformatics tool, I am not sure if this is suitable. I am use it (nglview) for viewing trajectory from MD simulation.

**Comment by johanneskoester** [comment]
Sure, go ahead, that's fine!

**Comment by hainm** [comment]
cool. thanks.
