### ISSUE TITLE
star fusion not found

### ISSUE THREAD

**Issue by arahuja** [bioconda/bioconda-recipes#1309]
Just started using `bioconda`, so perhaps there issues with my environment.

I am able to `conda install bwa`, `conda install star`, but `conda install star-fusion` says

```
$ conda install star-fusion
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .
Error:  Package missing in current osx-64 channels:
  - star-fusion

You can search for this package on anaconda.org with

    anaconda search -t conda star-fusion
```

**Comment by yhoogstrate** [comment]
It looks like this was done on purpose (https://github.com/bioconda/bioconda-recipes/commit/72f83c9ca571560cc1ab318e8dbe6b03d08c49f5#diff-c3003e41a4de2456cc63ab98ab2932d0R7). @bgruening any thoughts?

@arahuja Could you clone the repo, remove the line, and try to build the package and see if this works out for you? It's explained over here [ https://github.com/bioconda/bioconda-recipes#step-2-test-the-recipe ] how to do this.

**Comment by bgruening** [comment]
Not on purpose this was just during migration from a white list to a blacklist. So feel free to try to build it on OSX.
