### ISSUE TITLE
conda-forge no longer supports Python 3.5 while Bioconda still builds against it

### ISSUE THREAD

**Issue by EricR86** [bioconda/bioconda-recipes#13097]
Hello,

It appears that around October of last year, the conda-forge channel dropped support for Python 3.5. Specifically no new conda builds in that channel will be built for Python 3.5.

Can Bioconda follow suit? As-in can builds submitted no longer build loop through Python 3.5 (and use 3.6 and 3.7 instead)? I've recently run into issues why my Python 3.5 build was failing and I couldn't track down why but I'm fairly certain this is the case and at best it will only cause issues with older potentially buggy dependencies. I believe conda-forge now supports Python versions 3.6 and 3.7.

[Here was the announcement on Twitter](https://twitter.com/condaforge/status/1045699331171528707) regarding the change in October.

Thanks!

**Comment by EricR86** [comment]
Additionally at the very least it would be great at the very least to add Python 3.7 builds. Currently if you want to explictly not use 3.5 (due to known bugged dependencies in conda-forge) a bioconda recipe will only be available to environments with Python 3.6 *only*.

**Comment by EricR86** [comment]
@bgruening thank you for looking into this!

**Comment by bgruening** [comment]
See https://github.com/bioconda/bioconda-recipes/issues/13155

**Comment by dpryan79** [comment]
Closing, since we've also dropped python 3.5 support.
