### ISSUE TITLE
OS X stdlib future direction and conda-recipes compatibility for C++ packages

### ISSUE THREAD

**Issue by yesimon** [bioconda/bioconda-recipes#1314]
**Warning: Only relevant to C++ packages**

I talked about this briefly in #393, and have a fuller picture of OS X build environment in conda/conda-recipes#505.

They are linking against libstdc++ and setting a minimum OS X version of 10.7. Meanwhile, the homebrew package manager is linking against libc++ and requiring minimum OS X 10.9. I think that keeping in sync with conda-recipes might be problematic for OS X, since libstdc++ is now unsupported and now starting to lack many recent features in C++11/14 and beyond, which developers are now starting to utilize in their applications. 

I don't think having a 10.9 version minimum is unreasonable since OS X updates are now free. For a scientific software perspective, we should target more compatibility on the developer coding side than old operating system side of things.

Concretely, for the most part the conda-recipes packages should present no problems as long as they are binary packages, although you might be able to gain a bit from compiling with `MACOSX_DEPLOYMENT_TARGET=10.9`. For library packages, I propose rebuilding all with `libc++` to standardize our base.

**Comment by johanneskoester** [comment]
I would like to delay changes to the minimum dependencies as long as possible. I have seen many old osx installations on peoples desktops. Especially if bioconda shall be used by non-experts, requiring an os update for installing a package is a big hurdle. Maybe we should use this thread to collect a list of packages that won't build on the old setup. If that list contains enough important packages, we switch?

**Comment by yesimon** [comment]
Let's maintain max compatibility with and closely follow `conda-recipes`.

Similarly to #1332, I would strongly support a separate channel for newer OS X supporting 10.9 (what's available on travis)., `libc`, and newer C++ features because there are already some cases where `libstdc++` is not new enough.

**Comment by johanneskoester** [comment]
Having a separate channel is problematic. I believe our funding from Continuum is only for the primary bioconda channel. I wonder if there is a way to have such packages in the main channel, and have them automatically selected if a newer osx is available... We could use the "feature" functionality for that, similar to the mkl builds of numpy in the main channel.

**Comment by epruesse** [comment]
Closing - outdated.
