### ISSUE TITLE
plan for the GCC7 migration

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#13155]
* [x] label all main packages with an additional label (as conda-forge)
* [x] merge bulk into master
* [x] add `main` label to all packages with a `gcc7` label
* [x] communicate clearly to our community that now everything gets (re)build against gcc7
* [x] communicate that we need to bump the build-number to all packages (and its dependents) if you want to have a rebuild (https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change)
* [ ] create a bot to assist users to bump builds, potentially in a single-issue
* [ ] make the bot smart enough to (re)build packages it pinning are bumped globally

**Comment by bgruening** [comment]
Thanks to @dpryan79 we have now https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change  ... the bot in progress by @epruesse afaik. That leaves us to the point of how we communicate this.

Creating a new issue and ping /all/?

**Comment by bgruening** [comment]
I added an issue  (https://github.com/bioconda/bioconda-recipes/issues/13578) and update the PR template (https://github.com/bioconda/bioconda-recipes/pull/13579) to reach more people.

**Comment by kyleabeauchamp** [comment]
Is the plan for us to wait for the old compilers to be removed and then
start bumping the build number on our favorite recipes?

**Comment by epruesse** [comment]
You can already start bumping. That's actually what the new `bioconda-utils update-pinning` command does - you hand it packages of interest and it'll bump the dependency chain as necessary.

**Comment by epruesse** [comment]
@bgruening - Does this mean I can restart `autobump` now?

**Comment by bgruening** [comment]
@epruesse if `autobump` also considers `update-pinning` then yes.

Let's wait for @dpryan79 to confirm and feel free to merge https://github.com/bioconda/bioconda-recipes/pull/13579 so we update our users.

@kyleabeauchamp: unrelated but could you add `run_exports` to htslib. I think this would help a lot. Would be great if we could use `run_exports` more in our stack.

**Comment by kyleabeauchamp** [comment]
Will take a look tonight

**Comment by dpryan79** [comment]
Go for it, no need to wait for me!

**Comment by kyleabeauchamp** [comment]
I ran the update-pinning script and I get a lot of errors:

```
bioconda-utils update-pinning --bump-only-python recipes/ config.yml --packages deeptools
[...]

Attempting to finalize metadata for pysam
Solving environment: ...working... done
Solving environment: ...working... failed
Unsatisfiable dependencies for platform linux-64: {'bcftools==1.3.1', 'samtools==1.3.1', 'htslib==1.3.1'}

Packages requiring the following:
  No build number change needed: 12
  A rebuild for a new python version: 0
  A build number increment: 0
6 packages produced an error in conda-build: ['recipes/pysam/0.9.1', 'recipes/bcftools', 'recipes/samtools', 'recipes/pysam', 'recipes/htslib', 'recipes/pysam/0.10.0']

```

I also tried with `--bump-only-python` and got similar results.  Not sure what to make of it, but I thought I'd post because I imagine others will see similar.

**Comment by kyleabeauchamp** [comment]
Regarding run_exports, I've made a WIP PR (https://github.com/bioconda/bioconda-recipes/pull/13586/, not sure what else needs to be done.

**Comment by epruesse** [comment]
@kyleabeauchamp It works for me. Could be something with your conda setup...

**Comment by epruesse** [comment]
(It says nothing needs to be bumped, so you're ok)

**Comment by dpryan79** [comment]
@kyleabeauchamp I already rebuilt deepTools, pysam (the most recent version), and everything related to samtools/htslib. What you're seeing is due to old pysam versions depending on samtools/htslib versions that are no longer maintained in bioconda (1.3 in particular). We should really go through and see which pysam versions are still required by packages and blacklist/remove those that aren't being actively used. We can add samtools 1.3 back in if it's actually needed of course.

**Comment by epruesse** [comment]
@dpryan79 packages or recipes? I assume we only need to maintain recipes building old versions to satisfy pinnings by extant recipe versions, right?

**Comment by dpryan79** [comment]
@epruesse If there's no linking going on then we only care about packages. Pysam happens to link to htslib, though. However it's in C and not C++, so you're a better judge of whether that's an actual issue than me.
