### ISSUE TITLE
Help to prepare a recipe

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#13159]
Hi,
Has anyone tried to create a recipe for [polar_star](https://github.com/phasegenomics/polar_star) which seems to be an alternative to PBjelly.

It appears that the installations are embedded into the Snakemake 
[file](https://github.com/phasegenomics/polar_star/blob/master/Snakefile#L110) and will install the following packages:

- samtools, 
- htslib, 
- vcflib, 
- gdrive, 
- minimap2, 
- bedtools2

Would it be the best way to delete everything from line 110 and add the dependencies into `meta.yaml` file?

Thank you in advance.

Michal

**Comment by dpryan79** [comment]
Yes, it looks like that would be the best way to proceed. Even easier would be to have the authors simply provide an environment.yaml file and change their Snakefile to use it. Then you wouldn't have to deal with any of this.
