### ISSUE TITLE
New linting issues

### ISSUE THREAD

**Issue by pinin4fjords** [bioconda/bioconda-recipes#13187]
Hi all,

We're now seeing new issues with a couple of recipes at the linting stage, one in a recipe we wrote:

https://github.com/bioconda/bioconda-recipes/pull/13153

... and another in an unrelated SOP in which I just requested a dependency tweak: 

https://github.com/bioconda/bioconda-recipes/pull/13153

Identical issue, error like this at the bottom of the CircleCI readout:

```
...
10:31:35 BIOCONDA DEBUG lint recipes/r-seurat/1.4.0.16
10:31:56 BIOCONDA DEBUG lint recipes/r-sleuth
10:32:17 BIOCONDA DEBUG lint recipes/r-speaq/1.2.1
	recipe	check	info	fix	missing_hash	output
0	recipes/bioconductor-cummerbund/2.12.1	missing_hash	"{'missing_hash': True, 'fix': 'add md5, sha1, or sha256 hash to ""source"" section', 'output': 'bioconductor-cummerbund'}"	"add md5, sha1, or sha256 hash to ""source"" section"	True	bioconductor-cummerbund
1	recipes/bioconductor-cummerbund/2.8.2	missing_hash	"{'missing_hash': True, 'fix': 'add md5, sha1, or sha256 hash to ""source"" section', 'output': 'bioconductor-cummerbund'}"	"add md5, sha1, or sha256 hash to ""source"" section"	True	bioconductor-cummerbund
2	recipes/bioconductor-rgraphviz/2.13.0	missing_hash	"{'missing_hash': True, 'fix': 'add md5, sha1, or sha256 hash to ""source"" section', 'output': 'bioconductor-rgraphviz'}"	"add md5, sha1, or sha256 hash to ""source"" section"	True	bioconductor-rgraphviz
Exited with code 1
```

Does anyone know what the problem is?

**Comment by pcm32** [comment]
I have tried re-starting the testing on one of the affected PRs, but it keeps failing on the linting of other tools that are not part of the PR. It never actually reaches the linting of the tool in the PR :-(.

**Comment by pcm32** [comment]
For some reason, it is unblacklisting a number of recipes at the beginning of the linting....

```
16:25:18 BIOCONDA INFO Recipes newly unblacklisted:
r-dartr
bioconductor-onassis
bioconductor-rchyoptimyx
bioconductor-mirlab
bioconductor-envisionquery
r-speaq/1.2.1
pizzly
bioconductor-fci
bioconductor-camthc
r-data.table
....
```

and then one of this fails.

**Comment by pcm32** [comment]
After reading https://github.com/bioconda/bioconda-utils/issues/387 I updated our fork's master to be up-to-date with bioconda's and then rebased my PR's branch and the linting passed.

**Comment by pinin4fjords** [comment]
Confirmed @pcm32 's solution works, closing issue.
