### ISSUE TITLE
Using llvm in OSX builds

### ISSUE THREAD

**Issue by acaprez** [bioconda/bioconda-recipes#1332]
I'm trying to understand the motivation for specifying `llvm` as opposed to `gcc` for OS X builds.  Best I can tell, the conda `llvm` package doesn't include the clang compiler.  It's just the Core part of llvm with the library and utilities.  So when you specify `llvm`, what will really get used is the Xcode-provided clang (and llvm) that is symlinked to `/usr/bin/gcc`.  I'm just curious if that was the intention or not.

**Comment by yesimon** [comment]
It does look like a mistake, and should be removed.

I think it's yet to be decided whether we are using clang or gcc for OS X builds in the future. One thing to note is that conda-recipes uses clang which would be my vote.

**Comment by johanneskoester** [comment]
Thanks for pointing this out. Indeed, the intention was to follow anaconda.org and conda-recipes and build using clang on osx. However, I am personally also fine with using the real gcc on osx, if that does not introduce incompatibilities with anaconda.org or conda-recipes.

**Comment by johanneskoester** [comment]
@bioconda/core we should collect some opinions and decide how to proceed.

**Comment by croth1** [comment]
I think it may make sense to check the policies of the conda-forge community project and see if their recipe format fits for us as well.

**Comment by yesimon** [comment]
I think we should use built-in clang and default travis OS X setup for max compatibility with `conda-recipes` and `conda-forge`. 

I was thinking it could be a good idea to provide an alternative channel such as `bioconda-gcc-osx` for gcc builds on OS X.

**Comment by molpopgen** [comment]
The OS X/GCC thing came up for me while prepping PR #2682, which is a C++11 package.  In short, the issues are:

1. The built-in clang on OS X was not feature-complete for C++11 until 10.9  or so.
2. The built-in clang on the Travis install is simply too old, resulting in "unrealistic" failures (there just can't be that many 10.5/10.6 machines still in use).
3. Ignoring the Travis issue, clang on OS X Yosemite removed built-in support for OpenMP, which is a problem for a lot of scientific computing.  Some uses of OpenMP further don't easily support conditional compilation to get around this--I'm thinking Cython here. For HomeBrew users, one can install clang-omp to band-aid the problem.

Using GCC for OS X builds addresses all of these issues: old and new OS X targets are supported, as is -fopenmp.

I'm not sure there's a completely perfect answer here, but GCC does check of a lot of boxes.

**Comment by bgruening** [comment]
Here a little bit more background from conda-forge. https://github.com/conda-forge/staged-recipes/issues/1193 I think the agreement is to move to GCC on OSX as well at some point.

Also please note that travis upgraded there OSX images and XCode a week ago.

**Comment by martin-mann** [comment]
I just ran into the OSX problem that (as far as I can see) the currently pinned boost 1.60 was built with clang. This is no problem (when using the header-only libs) unless you use boost-sublibs that come with a shared lib like `-lboost_regex -lboost_program_options`. Here I get linker errors that are (given my short web search) connected to mixed compilation/linking setups. In my build I use the `llvm` on oxs, which uses `g++` in the backend as stated above...

My main point: when finally settling the OSX build system, **ensure all libs (at least the pinned ones) are built conform to your decision**. Currently, it seems they are not. :/

**Comment by yhoogstrate** [comment]
@martin-mann how did you solve it and which package did you work on? I'm stuck with a similar problem

**Comment by martin-mann** [comment]
Hi @yhoogstrate , I finally gave up and disabled osx build for the time being. It seems both available boost versions (1.60 and 1.61) are not built for c++11 support (which I need).

If you do not need c++11, you might build with the static boost=1.61.* (not the pinned one) and disable the runtime boost dependency from the yaml file. This might get it running.. ensure you use similar compiler/linker flags as the ones used for the [boost package](https://github.com/conda/conda-recipes/tree/master/boost).

I am crossing fingers.. :)

**Comment by yhoogstrate** [comment]
@martin-mann I think I have found a way to do this. In the meta.yml I have:

```
requirements:
  build: 
    - llvmdev ==3.9.1 # [osx]
    - libcxx # [osx]
    - gcc ==4.8.5 # [linux]
    - boost ==1.63.0
    - etc. etc.
  run: 
    - libgcc # [linux]
    - libcxx # [osx]
    - boost ==1.63.0
    - etc. etc.
```

Then in the build you need to make sure you have the  `-std=c++0x`/`-std=c++11` flag enabled. Then for the OS X build specifically, you also need to have `-stdlib=libc++`. Especially the latter is important as it links to the `libcxx` dependency that seems to be c++11 compatible. You can link them via export commands. Be aware that `-stdlib=...` is specific for CLANG and will break with GCC, so for the OS-X build you need a separate compile command in some kind of if statement.

example:
https://github.com/yhoogstrate/bioconda-recipes/blob/953893f3144bf6d9bd24cbbc350c654ac6829648/recipes/segmentation-fold/build.sh (I know it's a mess, I'll work on that later).

**Comment by epruesse** [comment]
outdated
