### ISSUE TITLE
entrez-direct installation links the wrong perl version on a MacOS

### ISSUE THREAD

**Issue by ialbert** [bioconda/bioconda-recipes#13415]
entrez-direct installation links the wrong perl version on a MacOS

    conda create -y -n foo python=3.6
    conda activate foo
    conda install entrez-direct

All packages listed for installation are for Perl `5.26` except a library that looks like Perl `5.22`

    ...
    perl-threaded      bioconda/osx-64::perl-threaded-5.22.0-10
    ...

Running `efetch` fails:

    efetch

produces:

    Can't locate HTML/Entities.pm in @INC (you may need to install the HTML::Entities module) (@INC contains: 
    /Users/ialbert/miniconda3/envs/foo/bin/aux/lib/perl5 
    /Users/ialbert/miniconda3/envs/foo/lib/perl5/site_perl/5.22.0/darwin-thread-multi-2level 
    /Users/ialbert/miniconda3/envs/foo/lib/perl5/site_perl/5.22.0 
    /Users/ialbert/miniconda3/envs/foo/lib/perl5/5.22.0/darwin-thread-multi-2level
    /Users/ialbert/miniconda3/envs/foo/lib/perl5/5.22.0 .) at 
    /Users/ialbert/miniconda3/envs/foo/bin/edirect.pl line 71.
    BEGIN failed--compilation aborted at /Users/ialbert/miniconda3/envs/foo/bin/edirect.pl line 71

Note how the import is trying to access directories for perl `5.22`. The perl versions are:

    ls -l ~/miniconda3/envs/foo/bin/perl*

it shows two versions for perl `5.22` an `5.26` and the `5.22` is linked under the default `perl`:

    -rwxr-xr-x  5 ialbert  staff   1.9M Apr  1  2016 /Users/ialbert/miniconda3/envs/foo/bin/perl
    -rwxr-xr-x  5 ialbert  staff   1.9M Apr  1  2016 /Users/ialbert/miniconda3/envs/foo/bin/perl5.22.0
    -rwxrwxr-x  1 ialbert  staff   2.0M Jan 30 10:27 /Users/ialbert/miniconda3/envs/foo/bin/perl5.26.2
    -rwxr-xr-x  1 ialbert  staff    44K Jan 30 10:27 /Users/ialbert/miniconda3/envs/foo/bin/perlbug
    -rwxr-xr-x  1 ialbert  staff   284B Jan 30 10:27 /Users/ialbert/miniconda3/envs/foo/bin/perldoc
    -rwxr-xr-x  1 ialbert  staff    11K Jan 30 10:27 /Users/ialbert/miniconda3/envs/foo/bin/perlivp
    -rwxr-xr-x  1 ialbert  staff    44K Jan 30 10:27 /Users/ialbert/miniconda3/envs/foo/bin/perlthanks

But the Perl `5.22`  does not have any of the required packages installed hence it fails. Moreover, conda thinks all libraries are correct so one cannot fix this error by installing the correct Perl library.  conda believes that Perl `5.26` is active.

The "fix" is to uninstall `perl` then reinstall `entrez-direct`:

    conda remove perl
    conda install entrez-direct

now `efetch` works as the correct version of perl is linked in.

    ls -l ~/miniconda3/envs/foo/bin/perl*

produces:

```
-rwxrwxr-x  1 ialbert  staff   2.0M Jan 30 10:32 /Users/ialbert/miniconda3/envs/foo/bin/perl
-rwxr-xr-x  5 ialbert  staff   1.9M Apr  1  2016 /Users/ialbert/miniconda3/envs/foo/bin/perl5.22.0
-rwxrwxr-x  1 ialbert  staff   2.0M Jan 30 10:32 /Users/ialbert/miniconda3/envs/foo/bin/perl5.26.2
-rwxrwxr-x  1 ialbert  staff    45K Jan 30 10:32 /Users/ialbert/miniconda3/envs/foo/bin/perlbug
-rwxrwxr-x  1 ialbert  staff   322B Jan 30 10:32 /Users/ialbert/miniconda3/envs/foo/bin/perldoc
-rwxrwxr-x  1 ialbert  staff    11K Jan 30 10:32 /Users/ialbert/miniconda3/envs/foo/bin/perlivp
-rwxrwxr-x  1 ialbert  staff    45K Jan 30 10:32 /Users/ialbert/miniconda3/envs/foo/bin/perlthanks
```

I do think that this error is not directly caused by the entrez-direct recipe, rather than some interplay of some other components. It is where most bioinformaticians will run into though, so it is useful if it labeled as such.

I am also hoping that this gets tagged in a way that gets to whoever can fix it.

**Comment by ialbert** [comment]
A different order in listing the requirements also appears to help the problem. Installing `entrez-direct` like  will make it work:
```
perl
perl-net-ssleay
entrez-direct
```

this now points to some sort of inconsistency in the dependency graph.

**Comment by dpryan79** [comment]
This is probably a nice example of why `conda install` should be avoided and `conda create` used instead, since the latter will nicely pull in perl 5.26 100% of the time and be faster. If there are still issues regarding this then please feel free to reopen this.

**Comment by ialbert** [comment]
I honestly don't understand what this means - I am even more puzzled of why the issue was closed. 

Are you saying that the chain of commands I have listed on the top:

```
conda create -y -n foo python=3.6
conda activate foo
conda install entrez-direct
```

are not the way to install `entrez-direct` with conda?

If that is so what are the commands?

**Comment by dpryan79** [comment]
I can't reproduce the issue with the exact commands you gave. In general it's best to create environments with everything you want in them from the beginning. Obviously this isn't always possible, in which case you can run into issue like you observed. In this particular case what likely happened is that there was a dependency that needed to be rebuilt (and since has been).

**Comment by ialbert** [comment]
this problem has been plaguing my students for a very long time (several years)! There is a separate section in my book titled: "How to fix a Chronic Case of Entrez Direct" which discuss various recovery scenarios. 

Every single year I have numerous people reporting it, I have seen it happen to me as well, though it is still not clear under what circumstance. The order in which tools are installed seems to matter. 

  I do agree that the problem might not be caused by entrez direct, it is rather some unfortunate interdependency when it comes to SSH libraries, perl and HTML libraries for perl. That being said simply closing the issue and stating the problem has "probably" been fixed does not quite seem like the right solution. The right course of actions should be to as for confirmation that the problem still persists at the reporting side at this time.

**Comment by bgruening** [comment]
Hi @ialbert!

I think what you are seeing here is a variety of different issues with conda in general. (Also I'm not sure if these are issues or we should just be more clear about how to use conda.)

1. `conda create` vs. `conda install`

`conda create` takes the specified pkgs, and only those, to find a feasible env solution. `conda install` in contrast takes the specified packages but also the packages that are currently installed in your active environment. This makes the solving of the environment really hard and implicit. You should avaoid that as much as you can.

2. openssl

OpenSSL is special in Conda (and many other similar projects). The community struggles here to answer the Q security > or < reproducibility. Conda has a (configurable) setting that openssl is treated very differently as other packages and that is, that openssl gets updated no matter what - it gets priority. Which again can cause trouble, but we (mainly @dpryan79) has rebuild the bioconda stack against latest openssl recently.

3. Perl

Our perl (bioconda-)community is not that huge :( We have a huge list of things that needs to be done to bring the quality of our perl packages on-par with python/R/C++/C/rust/... packages. I would love to get people together that have Perl experience to solve that, but until then perl is, unfortunately, a second-class citizen (in bioconda) imho.

Sorry that you had so much trouble, following @dpryan79 advice should at least get it working. Please let us know if this workaround does not work for you.

**Comment by ialbert** [comment]
> following @dpryan79 advice should at least get it working.

as I mentioned before I  am not quite sure what this advice consists. As I mentioned before I installed my tools with:

```
conda create -y -n foo python=3.6
conda activate foo
conda install entrez-direct
```

neither @dpryan79 nor yourself are sufficiently specific as to what alternative code are you suggesting for the above installation. What is the replacement code for the above that you claim to work?

And most importantly if one wanted to install more than one package beyond entrez direct. Will it work?

Do you want to know what the actual most ridiculous issue is here? Entrez Direct would already work on a Mac even without conda. Everything is properly installed: perl, SSL, HTML libraries are already installed properly.

The conda recipes are the ones that are overwriting a properly set up and otherwise working environment, by adding all kinds of junk and ends up messing up the perl PATH by linking two different versions of perl in the environment. That's the most ludicrous thing I have ever seen, where conda is the means to corrupt a working system. 

The conda Entrez recipe should not install ANY dependency at all!

Read what the original issue states, there are two version of perl installed, an old Perl 22 that is older than what the Mac already packages.

**Comment by dpryan79** [comment]
Looks like indeed that perl-threaded requires a rebuild, I must have misread that originally. I'll reopen this then and see if I can update it to 5.26.

**Comment by dpryan79** [comment]
Actually, that package has no contents. It appears as though the OSX perl-5.26 package from conda-forge actually contains perl-5.22. That will obviously break a great many things, of which this appears to be one. We'll have to track this down with the conda-forge folks (I wonder how this wasn't caught during CI testing).

**Comment by dpryan79** [comment]
I've tracked down the cause of this and also why it isn't always reproducible. While perl-threaded is an empty package, it has a run-time dependency on perl-5.22. So if perl-threaded happens to get installed after the other perl packages then the perl executable will point to perl-5.22 rather than perl-5.26 and many things will break. `perl-threaded` predates the perl pinnings and I wonder why it's even being pulled in.

**Comment by dpryan79** [comment]
@ialbert Please try this again, it should be fixed after #14147

**Comment by druvus** [comment]
I was digging into this problem last summer when we rebuilt all perl packages. I think the issue is coming from "ancient" bioconda packages (<=2016) built with conda build v1. Those early perl packages seems not have any perl version pinned so sometimes they are dragged in and pulling in other 5.22. It was an real issue during the rebuild process on osx and as some packages got rebuilt and labelled as 5.26 packages even if they depended on 5.22 versions. 

The problem was seen earlier in #10365 but never got fixed.

**Comment by dpryan79** [comment]
Hopefully we can start fixing some of these long-standing pinning issues once bioconda has been migrated to the anaconda CDN and we can patch metadata.

**Comment by bgruening** [comment]
@ialbert what we meant is something along those lines:

```bash
conda create -y -n foo python=3.6 entrez-direct
```

@druvus maybe we can create a list of those packages, rebuild them and mark the old once as deprecated?

**Comment by ialbert** [comment]
Hello all. Thanks for the fix. 

It does look like the fundamental issue was corrected: having the wrong version of perl linked as executable. Thanks for the effort @dpryan79 . 

I will run a few more tests but I am optimistic that the "Chronic Case of Entrez Direct" might be cured for good. Thus I'll close the issue.

**Comment by ialbert** [comment]
I spoke too soon a different error occurs, foolishly enough I only tested that the command starts efetch, not that it returns the proper content. Perl 5.22 still gets installed and some libraries are installed for 5.22 instead of 5.26:

    efetch -db nuccore -id 2

```
501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)
No do_post output returned from 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=2&rettype=native&retmode=text&edirect_os=linux&edirect=10.2&tool=edirect&email=ialbert@beep.localdomain'
Result of do_post http request is
$VAR1 = bless( {
                 '_content' => 'LWP will support https URLs if the LWP::Protocol::https module
is installed.
...
```

even though the required module seems to be installed:

```
conda list | grep https
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
```

the following command fails like so:

`perl -e 'require LWP::Protocol::https;'`

```
Can't locate Net/SSLeay.pm in @INC (you may need to install the Net::SSLeay module)) at /home/ialbert/miniconda3/envs/foo/lib/site_perl/5.26.2/IO/Socket/SSL.pm line 19.
BEGIN failed--compilation aborted at /home/ialbert/miniconda3/envs/foo/lib/site_perl/5.26.2/IO/Socket/SSL.pm line 19.
Compilation failed in require at /home/ialbert/miniconda3/envs/foo/lib/site_perl/5.26.2/Net/HTTPS.pm line 25.
Can't locate Net/SSL.pm in @INC (you may need to install the Net::SSL module) (@INC contains: /home/ialbert/miniconda3/envs/foo/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/ialbert/miniconda3/envs/foo/lib/site_perl/5.26.2 /home/ialbert/miniconda3/envs/foo/lib/5.26.2/x86_64-linux-thread-multi /home/ialbert/miniconda3/envs/foo/lib/5.26.2 .) at /home/ialbert/miniconda3/envs/foo/lib/site_perl/5.26.2/Net/HTTPS.pm line 29.
Compilation failed in require at /home/ialbert/miniconda3/envs/foo/lib/site_perl/5.26.2/LWP/Protocol/https.pm line 8.
Compilation failed in require at -e line 1.
```

it appears that the `SSLeay` module is still installed for perl version `5.22`:

    find /home/ialbert/miniconda3/envs/foo/ -name '*SSLeay*'

prints:

    /home/ialbert/miniconda3/envs/foo/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/Net/SSLeay

**Comment by dpryan79** [comment]
This is probably the same as #14037

**Comment by dpryan79** [comment]
@ialbert Thanks for noting the perl 5.22 path issue with perl-net-ssleay, that's hopefully enough for us to track down the root cause.

**Comment by dpryan79** [comment]
@ialbert Can you try making a new environment? I can't reproduce this with the default `perl-net-ssleay` (1.85-pl526h9dad42d_0) that I'm getting with a fresh env. If you get the same result, can you post the output of `conda list` in that env?

**Comment by ialbert** [comment]
on my system it installs 

```
conda list | grep ssleay
perl-net-ssleay           1.74                          0    bioconda
```

both on Ubuntu for Windows and on MacOSX

**Comment by dpryan79** [comment]
What's the output of `conda config --show channels`?

**Comment by ialbert** [comment]
```
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
```

**Comment by dpryan79** [comment]
What happens if you create an env without `python=3.6`? That is, just `conda create -n bar entrez-direct`? There seems to be a conflict between python and more recent versions of the perl packages (we should track that down).

**Comment by ialbert** [comment]
that way it works and it installs 

    perl-net-ssleay           1.85            pl526h9dad42d_0    bioconda

python 3.6 is required by many bioinformatics tools, thus we can't quite do without that. In addition I want to note that previously once can upgrade with `conda install perl-net-ssleay==1.84` and that seems to work as well. 

Finally installing two different versions of perl seems to be a  more fundamental problem than a python dependency. Whatever tools requests that version of the library (looks like (`x86_64-linux-thread-multi` can't be possibly be working correctly as there is no perl 5.22 binary installed anymore)

**Comment by dpryan79** [comment]
I found the root problem. The most recent `perl-net-ssleay` has openssl properly pinned, but it hasn't been updated to be pinned to openssl-1.1.1. perl-net-ssleay-1.74 has no pinning to openssl, so it's incorrectly getting installed and therefore pulling in `perl-threaded`. A lot of the perl packages are currently blacklisted, which is why they didn't get updated for the new pinnings (among the many reasons we want to move them to conda-forge). I'll see if I can get perl-net-ssleay rebuilt. At least we have a nice test now to check if it's working properly :)

**Comment by dpryan79** [comment]
Xref: #14172

**Comment by dpryan79** [comment]
@ialbert Can you confirm that this issue is now resolved on OSX? The new perl-net-ssleay seems to fix things on this end.

**Comment by ialbert** [comment]
I can confirm that it works on both MacOSX and Windows Ubuntu Bash. Thanks for the assistance.
