### ISSUE TITLE
How do I modify environment variables from a recipe? Activate script?

### ISSUE THREAD

**Issue by pinin4fjords** [bioconda/bioconda-recipes#13423]
I think I'm missing something obvious here, hopefully someone can point me in the right direction.

Basically: what's the Conda way of setting environment variables from a recipe such that they're available for both testing and running? 

I'm trying to make a Conda package for an old tool (not mine)which has various expectations on environment variables. It also has executables in various sub-directories which I'd rather not flatten into $PREFIX/bin if I can avoid it. I thought I had the solution in the form of an activate script, which works fine and passes local tests without containers. But the containers used by the CircleCI tests on here don't seem to run the activate scripts so my test command is failing.

Thanks in advance for any help.

The PR in question is here: https://github.com/bioconda/bioconda-recipes/pull/13399.

**Comment by pinin4fjords** [comment]
Thanks @PertuyF , and don't worry, I had no intention of trying to use the install script to install dependencies (see comment in the build.sh). The point of bringing iRAP into Bioconda is to do as you suggest as regards dependencies (eventually), but right now I just want to get some of the basic stuff working without lots of patching. 

I would just like to use PATH so that I don't have to flatten everything into $PREFIX/bin (which I suspect will break some thing), and set another environment variable (IRAP_DIR).

**Comment by dpryan79** [comment]
In case this is still an issue, you can theoretically use `post-link.sh` for this to create an `etc/activate.d` in the environment in which the package is installed. That should REALLY be avoided though, as @PertuyF said.

I'll close this, but feel free to reopen if there are further questions.
