### ISSUE TITLE
Incorrect links on recipe pages

### ISSUE THREAD

**Issue by apeltzer** [bioconda/bioconda-recipes#13426]
Might be a duplicate (didn't find one, but still I could be missing something):

Note the `/home/circleci/....` stuff creeping in.... probably not intentional? Clicking on the link also proceeds to a non-existing landing page...

@bioconda/core 

<img width="727" alt="bildschirmfoto 2019-01-31 um 15 41 05" src="https://user-images.githubusercontent.com/2359510/52061486-b4b67f00-256e-11e9-93c4-876abb622741.png">

**Comment by dpryan79** [comment]
Nice catch! I bet expect this is coming from bioconda-utils, can you open an issue there?

**Comment by apeltzer** [comment]
CLosing here, opened another one 👍

**Comment by dpryan79** [comment]
:+1: Thanks @apeltzer!
