### ISSUE TITLE
libreadline.so.6 not found while using biocodna on Linux Ubuntu 18.04

### ISSUE THREAD

**Issue by davidechicco** [bioconda/bioconda-recipes#13439]
Hi all

I am the developed of the [behst](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/behst) package in bioconda. 

This package has always been working well on my computers (Linux CentOS 7 or Ubuntu 18), until today. When I call an R script from my main bash script, now I get this error:

`/home/davide/miniconda3/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory`

It looks like the libreadonline.so.6 library is absent or not working. **How can I fix this problem?**

I already tried the following actions (that did not solve the problem):
- updating conda (`conda update --all`)
- updating libreadonline (`sudo apt -y install libreadonline7`)

Can someone help me? Thanks!

**Comment by davidechicco** [comment]
I was able to fix the issue by installing an old version of readline:

`conda install -c conda-forge readline=6.2`

But I think this cannot be the solution on the long term. I officially ask the bioconda curators ( @bgruening @daler @johanneskoester ) to look into this readline problem and try to fix it. Thanks!

**Comment by dpryan79** [comment]
It sounds like you installed something else in that environment and that caused readline to get updated (likely to 8.0). As a rule of thumb, it's best to specify `--no-update-deps` when installing new packages into an existing environment, as otherwise conda will try to update things.

**Comment by suhrig** [comment]
I'm having the same issue and it has nothing to do with omitting `--no-update-deps`. Version 6 of libreadline was never installed. Recent releases of Miniconda are shipped with version 7 of libreadline. Packages that were built with older releases are linked against version 6. That's the problem.

Here are the steps to reproduce (in an ubuntu:bionic Docker):

```
wget 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh'
bash Miniconda3-latest-Linux-x86_64.sh
source /root/miniconda3/bin/activate
conda install r=3.3.1
# states in the output that it installs readline-7.0-h7b6447c_5
R
# throws error about missing libreadline version 6
```

I am not sure what is the best way to deal with this in general. I ran into this problem, when writing a new recipe that accepts R versions 3.3.0 and later. Conda chooses to install 3.3.1, even though newer versions are available. Should I instead configure my recipe to use whatever the most recent version of R is at the time of building it? I wanted to give users some flexibility and specified the oldest version that I found compatible, because I have run into dependency hell with Conda myself due to packages requiring specific versions. Then again, using the latest version does not solve the underlying issue. What if a new release of Miniconda comes out which is based on libreadline 8? Won't this invalidate all R packages built before that? I'm interested hearing an opinion from the bioconda experts, since it seems like a fundamental issue to me.

**Comment by dpryan79** [comment]
Old versions of R are not supported and all bioconda packages are built with R 3.5.1 currently.

**Comment by suhrig** [comment]
> Old versions of R are not supported 

Okay, makes sense.

> all bioconda packages are built with R 3.5.1 currently

It turns out an R package (bioconductor-genomicalignments) used by my Conda package (arriba) causes a conflict with R 3.5.1, such that version 3.3.1 is installed instead. I will try to get to the root of this and report back.

Thanks for the speedy reply.

**Comment by dpryan79** [comment]
I suspect you have the `r` channel in your channel list. If so, remove it and see if that causes the problem.

**Comment by suhrig** [comment]
> I suspect you have the r channel in your channel list.

If `conda config --show channels` does not list it, this means I haven't, right?

`conda search bioconductor-genomicalignments` gives me this:

```
# Name                  Version           Build  Channel             
bioconductor-genomicalignments           1.6.0               0  bioconda            
bioconductor-genomicalignments           1.6.1               0  bioconda            
bioconductor-genomicalignments           1.6.3               0  bioconda            
bioconductor-genomicalignments           1.6.3               1  bioconda            
bioconductor-genomicalignments           1.8.4        r3.3.1_0  bioconda            
bioconductor-genomicalignments          1.10.0        r3.3.1_0  bioconda            
bioconductor-genomicalignments          1.10.0        r3.3.2_0  bioconda            
bioconductor-genomicalignments          1.10.0        r3.4.1_0  bioconda            
bioconductor-genomicalignments          1.12.2        r3.4.1_0  bioconda            
bioconductor-genomicalignments          1.14.0        r3.4.1_0  bioconda            
bioconductor-genomicalignments          1.14.1        r3.4.1_0  bioconda            
bioconductor-genomicalignments          1.16.0  r341h470a237_0  bioconda            
bioconductor-genomicalignments          1.16.0  r351h470a237_0  bioconda            
bioconductor-genomicalignments          1.18.0  r351h14c3975_0  bioconda            
bioconductor-genomicalignments          1.18.1  r351h14c3975_0  bioconda  
```

Does this mean R 3.3.1 is chosen, because `bioconductor-genomicalignments` is not available for R 3.5.1 and someone needs to build a package? If yes, who is responsible?

**Comment by dpryan79** [comment]
The last three lines are for R 3.5.1 (the `r351` prefix is meant to indicate that).

**Comment by suhrig** [comment]
Then why does `conda install -c bioconda bioconductor-genomicalignments r=3.5.1` result in a conflict and `conda install -c bioconda bioconductor-genomicalignments r` wants to install R 3.3.1 or 3.3.2? I am clueless.

**Comment by dpryan79** [comment]
You'll want `r-base=3.5.1` instead of `r`.

**Comment by suhrig** [comment]
Sorry to bombard you with questions, but this does not help. Heck, even installing `bioconductor-genomicalignments` alone results in a conflict:

```
conda install bioconductor-genomicalignments=1.18.1
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - bioconductor-genomicalignments=1.18.1
```
I don't understand this. Am I the only person with this problem? What could I be doing wrong? This a fresh Ubuntu Docker with nothing but Miniconda installed.

**Comment by dpryan79** [comment]
> Am I the only person with this problem?

I can't reproduce it, so possibly yes. `conda create -n foo bioconductor-genomicalignments r-base=3.5.1` installs bioconductor-genomicalignments-1.18.1 for me. Never use `conda install` unless you absolutely have to, it's an excellent way to break packages you're already using.

**Comment by bgruening** [comment]
> Sorry to bombard you with questions, but this does not help. Heck, even installing bioconductor-genomicalignments alone results in a conflict:

This is probably because in your current environment contains `r-base` in a version that is not compatible with `bioconductor-genomicalignments=1.18.1`. So please follow @dpryan79 advice and use `conda activate` to create a new environment.

**Comment by suhrig** [comment]
I am starting to question my own sanity. :-D I tried using the exact command @dpryan79 suggested. It results in a conflict on two systems (Ubuntu bionic, CentOS 7). I am not using the `r` channel. There is no `r-base` installed according to `conda list`. Here are my exact commands to reproduce the error:

```
$ docker pull ubuntu:bionic
bionic: Pulling from library/ubuntu
898c46f3b1a1: Pull complete
63366dfa0a50: Pull complete
041d4cd74a92: Pull complete
6e1bee0f8701: Pull complete
Digest: sha256:017eef0b616011647b269b5c65826e2e2ebddbe5d1f8c1e56b3599fb14fabec8
Status: Downloaded newer image for ubuntu:bionic

$ docker run -i -t --rm ubuntu:bionic bash

$ apt-get update && apt-get install wget -y

$ wget 'https://repo.anaconda.com/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh'

$ bash Miniconda3-4.5.12-Linux-x86_64.sh
Do you accept the license terms? [yes|no]
[no] >>> yes
Miniconda3 will now be installed into this location:
[/root/miniconda3] >>> /root/miniconda3
Do you wish the installer to initialize Miniconda3 in your /root/.bashrc ? [yes|no]
[no] >>> no

$ source /root/miniconda3/bin/activate

$ conda config --add channels bioconda

$ conda config --show channels
channels:
  - bioconda
  - defaults

$ conda list
# packages in environment at /root/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0  
ca-certificates           2018.03.07                    0  
certifi                   2018.11.29               py37_0  
cffi                      1.11.5           py37he75722e_1  
chardet                   3.0.4                    py37_1  
conda                     4.5.12                   py37_0  
conda-env                 2.6.0                         1  
cryptography              2.4.2            py37h1ba5d50_0  
idna                      2.8                      py37_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libstdcxx-ng              8.2.0                hdf63c60_1  
ncurses                   6.1                  he6710b0_1  
openssl                   1.1.1a               h7b6447c_0  
pip                       18.1                     py37_0  
pycosat                   0.6.3            py37h14c3975_0  
pycparser                 2.19                     py37_0  
pyopenssl                 18.0.0                   py37_0  
pysocks                   1.6.8                    py37_0  
python                    3.7.1                h0371630_7  
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                   py37_0  
ruamel_yaml               0.15.46          py37h14c3975_0  
setuptools                40.6.3                   py37_0  
six                       1.12.0                   py37_0  
sqlite                    3.26.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
urllib3                   1.24.1                   py37_0  
wheel                     0.32.3                   py37_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3  

$ conda create -n foo bioconductor-genomicalignments r-base=3.5.1
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - bioconductor-genomicalignments
  - r-base=3.5.1
```

I you confirm that these commands do not throw an error on your system, then we will just have to accept that our systems are inexplicably different and leave it at that.

**Comment by dpryan79** [comment]
You're missing the conda-forge channel, which should have the highest priority.

**Comment by suhrig** [comment]
THANK YOU! Solved.
