### ISSUE TITLE
bioconductor-chromvar is broken

### ISSUE THREAD

**Issue by huidongchen** [bioconda/bioconda-recipes#13432]
Hi,

The recently updated 'bioconda-chromvar' bioconda package doesn't work any more. (Its R package works well so I suppose it has something to do with bioconda)

I'm attaching the R script and datasets here to reproduce the errors.
https://www.dropbox.com/sh/ts3a6bjrija6qw7/AAD0ryO5qzXvcyO6NKMJQMera?dl=0

`$ conda create -n chromvar_test python=3.6`
`$ conda activate chromvar_test`
`$ conda install bioconductor-chromvar`
`$ conda install bioconductor-bsgenome.hsapiens.ucsc.hg19`
`$ Rscript chromVAR.R`

Several errors will be reported:

Error1 : **libssl.so.1.0.0: cannot open shared object file: No such file or directory**  
It is caused by library mismatches between r-openssl and openssl
**Fixed by** `conda install openssl==1.0.2p`

Error2: **libgsl.so.19: cannot open shared object file: No such file or directory**
**Fixed by** `conda install gsl=2.2.1`

Error3: **Error in library(BSgenome.Hsapiens.UCSC.hg19) : there is no package called ‘BSgenome.Hsapiens.UCSC.hg19’** 
It looks like `conda install bioconductor-bsgenome.hsapiens.ucsc.hg19` doesn't really work
**Fixed by** installing 'BSgenome.Hsapiens.UCSC.hg19' within R
`$ R`
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg19", version = "3.8")
```

Error4: **Segmentation fault**
This error happens at the step of 'kmerdev <- computeDeviations(SE, KmerMatch)' in R script
We tracked down the dependency package 'r-nabor '. 
**Fixed by** installing 'nabor' within R
`$ R`
`> install.packages("nabor")`

I did my best but it seems beyond my capabilities to fix all the issues. I would be really grateful if you could help fix them. Many thanks!

**Comment by dpryan79** [comment]
Please try adding `bioconda/label/gcc7` to your channels (give it a higher priority than bioconda). The packages there will get moved into the main bioconda channel soon (within the next couple days I hope).

**Comment by huidongchen** [comment]
@dpryan79 Unfortunately it doesn't solve the issues. I added it to my channel and re-did everything from scratch. Also I make sure the package is installed in the channel `bioconda/label/gcc7`. 

But the issues still persist..

**Comment by dpryan79** [comment]
Your script and data work for me without issue:

```
> kmerdevTable[1:10,1:2]
    singles-BM0828-HSC-fresh-151027-1 singles-BM0828-HSC-fresh-151027-2
AAA                      -0.002570623                      0.0004508171
AAC                      -0.004618456                     -0.0011869930
AAG                      -0.003669833                     -0.0006971799
AAT                      -0.006666843                      0.0021049899
ACA                      -0.003854727                     -0.0012820565
ACC                      -0.003746648                     -0.0007921739
ACG                       0.000717893                      0.0015343434
ACT                      -0.003882573                     -0.0004182199
AGA                      -0.003644585                     -0.0008849635
AGC                      -0.003746533                     -0.0007811362
```

I suspect R is picking up libraries from outside of conda. Please add `.libPaths(R.home("library"))` to the very first line of your script (before you import any libraries). This will prevent R from looking at non-conda dependencies. When I created a clean env just now with `conda create -n bioc_debug python=3.6 bioconductor-chromvar bioconductor-bsgenome.hsapiens.ucsc.hg19` everything worked.

BTW, you can remove `bioconda/label/gcc7` from your list of channels as I copied everything from it to `bioconda` last night.

**Comment by huidongchen** [comment]
Hi 
Thanks a lot for helping test the script. 

I tried it from scratch (I removed the channel `bioconda/label/gcc7` and created new env ) with `.libPaths(R.home("library"))` and without `.libPaths(R.home("library"))` in both MacOS and Linux, but they still failed with similar errors as before:

For macos:
```
Loading required package: GenomeInfoDb
Error: package or namespace load failed for ‘GenomeInfoDb’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/hardy/anaconda3/envs/test1/lib/R/library/RCurl/libs/RCurl.so':
  dlopen(/Users/hardy/anaconda3/envs/test1/lib/R/library/RCurl/libs/RCurl.so, 6): Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /Users/hardy/anaconda3/envs/test1/lib/libssh2.1.dylib
  Reason: image not found
Error: package ‘GenomeInfoDb’ could not be loaded
Execution halted

```

For linux:
```
Loading required package: GenomeInfoDb
Error: package or namespace load failed for ‘GenomeInfoDb’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/data/pinello/SHARED_SOFTWARE/anaconda3/envs/bioc_debug/lib/R/library/RCurl/libs/RCurl.so':
  libssl.so.1.0.0: cannot open shared object file: No such file or directory
Error: package ‘GenomeInfoDb’ could not be loaded
Execution halted
```

**Comment by dpryan79** [comment]
On my system, installing those packages resulted in openssl-1.0.2p-h14c3975_1002 being installed, which provides that dependency. What version of openssl was installed in your environment?

**Comment by huidongchen** [comment]
For MacOS, it's `openssl 1.1.1a h1de35cc_1000 conda-forge`
For Linux, it's `openssl 1.1.1a h14c3975_1000 conda-forge`

I guess this is still related to my very first post. There seem to be several library mismatches here. Somehow the appropriate versions can't be installed by default.

**Comment by dpryan79** [comment]
My guess is that that's a byproduct of you not listing everything you needed in one command. Try `conda create -n bioc_debug python=3.6 bioconductor-chromvar bioconductor-bsgenome.hsapiens.ucsc.hg19` to avoid dependencies from getting upgraded incorrectly. I've just run exactly that again and once again got an appropriate openssl.

**Comment by huidongchen** [comment]
It's a great solution to put all the dependency packages in one command.

But it seems I can't install other packages any more within the created env. Each time i try to install new package, it will upgrade the `openssl` or other dependencies, which can easily break the installed bioconductor packages. 

Do you have any suggestions for installing new packages?

**Comment by dpryan79** [comment]
Use the `--no-update-dependencies` option.

**Comment by huidongchen** [comment]
Thanks again, can you explain to me why installing a new package will break other packages? Is the dependency graph for the bioconda channel not consistent or something else?

Having more details on this will be really helpful.

Thanks a lot.

**Comment by huidongchen** [comment]
More specifically, we built a bioconda package **stream_atac**, which depends on **bioconductor-chromvar**.

First of all, if I run:
`conda install stream_atac`
```
The following packages will be UPDATED:

  openssl                              1.0.2p-h1de35cc_1002 --> 1.1.1a-h1de35cc_1000
```
 `openssl` will be updated , which further will break bioconductor-chromvar. 

So I have to add `--freeze-installed`

But the following commands will only install the old version 'stream_atac' (0.1.0), which is depreciated.
```
conda create -n stream_atac_test python=3.6
conda activate stream_atac_test
conda install --freeze-installed stream_atac
```

So I tried to specify the latest version(0.2.0), 
```
conda create -n stream_atac_test2 python=3.6
conda activate stream_atac_test2
conda install --freeze-installed stream_atac=0.2.0
```
But it will report errors:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda-forge/osx-64::libcxx==7.0.0=h2d50403_2
  - stream_atac=0.2.0
Use "conda search <package> --info" to see the dependencies for each package.
```

I looks like although bioconda package **'stream_atac'** is successfully built, there is no way to really make it work.

**Comment by dpryan79** [comment]
If you just `conda create -n stream_atac_test stream_atac=0.2.0 python=3.6` you'll get an environment with the appropriate openssl. None of your problems have anything to do with bioconda, they are all simply because `conda install` ignores pinnings. So try to avoid using `conda install`.

**Comment by lucapinello** [comment]
@dpryan79 thanks for the suggestions and for the explanation, we really appreciate your input. 

Is there any simpler solution to this problem? I think many users will assume that conda install will automatically take care of the right dependencies during the "solving env" phase. I think this is not intuitive and not well document and could create several side effects.  We spent more than 2 weeks wrangling between dependencies problems and I think this could discourage bioconda users and developers.

@johanneskoester what do you think?

**Comment by dpryan79** [comment]
Closing, since this is a conda, rather than bioconda issue.

**Comment by huidongchen** [comment]
`bioconductor-chromvar` seems broken again. Errors happened even when using `conda create`

```
>conda create -n test_env python=3.6 bioconductor-chromvar

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0'.
LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /data/pinello/SHARED_SOFTWARE/anaconda3/envs/stream_atac/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /data/pinello/SHARED_SOFTWARE/anaconda3/envs/stream_atac/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>

```

**Comment by dpryan79** [comment]
Please refrain from reopening this. The actual issue is being addressed [here](https://github.com/bioconda/bioconda-recipes/issues/13846).

**Comment by pinellolab-service** [comment]
Hi @dpryan79 @johanneskoester . I just want to say thank you for the great support you have provided to Huidong and to the bioconda community.

**Comment by johanneskoester** [comment]
You're welcome, Luca! All of this would not work at all if there weren't users who take the effort of reporting bugs and issues, so thanks go back to you guys!
