### ISSUE TITLE
variant-effect-predictor recipe renames scripts

### ISSUE THREAD

**Issue by dakl** [bioconda/bioconda-recipes#1349]
`variant-effect-predictor` renames `INSTALL.pl` --> `vep_install.pl` which is reasonable. It also renames `convert_cache.pl` to `vep_convert_cache.pl` which causes `vep_install.pl` to fail when the `--CONVERT` flag is added to is since it looks for `convert_cache.pl`. 

```
vep_install.pl --SPECIES homo_sapiens_vep --AUTO c --ASSEMBLY GRCh37 --NO_HTSLIB --CONVERT --CACHEDIR ~/tmp/vep
Getting list of available cache files
 - downloading ftp://ftp.ensembl.org/pub/release-83/variation/VEP/homo_sapiens_vep_83_GRCh37.tar.gz
 - unpacking homo_sapiens_vep_83_GRCh37.tar.gz
 - converting cache
Can't open perl script "/nfs/ALASCCA/miniconda2/bin/convert_cache.pl": No such file or directory
WARNING: Failed to run convert script

All done
```

Does `convert_cache.pl` really have to be renamed?

**Comment by johanneskoester** [comment]
@chapmanb, I guess this is yours. In fact, I like the renaming. Can we easily fix the error, maybe by patching? Also, it would be nice mention the changed script names in `extra -> notes`.

**Comment by chapmanb** [comment]
Daniel -- thanks for the report and Johannes thanks for pinging me. I pushed a fix so `vep_install.pl` will call the renamed `vep_convert_cache.pl` correctly and added details on this to the notes as well as the post-link message scripts. Thanks again.

**Comment by dakl** [comment]
😃👍
