### ISSUE TITLE
repeatmasker issue

### ISSUE THREAD

**Issue by juancrescente** [bioconda/bioconda-recipes#13562]
Seems like I cannot run repeatmasker

<pre>RepeatMasker version development-$Id: RepeatMasker,v 1.332 2017/04/17 19:01:11 rhubley Exp $
Search Engine: NCBI/RMBLAST [ 2.6.0+ ]
Taxononmy::new() Could not locate the taxonomy data file!
 at /home/juan/miniconda3/envs/bio/share/RepeatMasker/RepeatMasker line 638.
</pre>

**Comment by pvanheus** [comment]
@juancrescente you need to set the REPEATMASKER_LIB_DIR to the location where the RepeatMasker/Libraries are and REPEATMASKER_MATRICES_DIR to the matrices directory. This is necessary because RepeatMasker uses a non-free library.

**Comment by druvus** [comment]
I confirmed that the suggested solution worked on a fresh installation. Please reopen if the error still is there for you.

**Comment by billahcse** [comment]
How can I set REPEATMASKER_LIB_DIR & REPEATMASKER_MATRICES_DIR ?

**Comment by tuguangxian** [comment]
> Seems like I cannot run repeatmasker
> 
> RepeatMasker version development-$Id: RepeatMasker,v 1.332 2017/04/17 19:01:11 rhubley Exp $
> Search Engine: NCBI/RMBLAST [ 2.6.0+ ]
> Taxononmy::new() Could not locate the taxonomy data file!
>  at /home/juan/miniconda3/envs/bio/share/RepeatMasker/RepeatMasker line 638.

I met the same problem, do you have a solution?thank you！

**Comment by pdroslva84** [comment]
I had the same issue, the problem for me turned out to be that the `taxonomy.dat.gz` file in the `Libraries/` folder was not uncompressed. The configure script is supposed to do that but apparently it didn't...

What worked for me was going into the `Libraries/` folder and manually uncompress the file: `gunzip -f taxonomy.dat.gz`
