### ISSUE TITLE
GCC7 migration is done

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#13578]
Thanks to @dpryan79, @epruesse and the conda-forge community we finished the GCC7/py37 migration. Thanks everyone.

### What does this mean?

* New Python packages, or updates, will get a new build against Python 3.7. Please note that it is still preferred to use [`noarch: python`](https://conda-forge.org/docs/meta.html#building-noarch-packages) for all pure Python packages (run-time dependencies do not count).

* If you rebuild or build a (C/C++) package you will now use the new compilers that are coming from the conda default channel. The compilers in the container are not used anymore and will be removed from the container in the next days.

* It can be that some dependencies in Bioconda are not yet compiled against GCC7, so that your program fails unexpectedly. To fix this please also re-build all the dependencies that you need. Bioconda utils gained an [`update-pinning`](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) command which you could use to figure out what needs to be rebuilt.

* We already rebuilt all Bioconductor packages against GCC7 and the latest BioConductor release. Enjoy a clean and up-to-date R stack!

* Watch out for the [skip-list](https://github.com/bioconda/bioconda-recipes/blob/master/build-fail-blacklist). If packages are failing during a rebuild or produce major problems we put them on this list. Please feel free to help us "fixing" those recipes to bring them back.

Enjoy the new compilers, we hope that the Conda stack gets more stable with it.

**Comment by SilasK** [comment]
I cannot install the bioconda-utils

`pip install https://github.com/bioconda/bioconda-utils`

gives me the following error:

```
Collecting https://github.com/bioconda/bioconda-utils
  Downloading https://github.com/bioconda/bioconda-utils
     \ 184kB 901kB/s
  Cannot unpack file /private/var/folders/bt/97hqkwdn0nv0lwjfmtmsk20c0000gn/T/pip-unpack-522j387s/bioconda-utils (downloaded from /private/var/folders/bt/97hqkwdn0nv0lwjfmtmsk20c0000gn/T/pip-req-build-_c9mgh3g, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /private/var/folders/bt/97hqkwdn0nv0lwjfmtmsk20c0000gn/T/pip-req-build-_c9mgh3g
```

**Comment by dpryan79** [comment]
`pip install git+https://github.com/bioconda/bioconda-utils`

**Comment by unode** [comment]
Hi @bgruening 

#13885 passed all tests prior to merge but failed to do the final build and upload.
There's nothing conclusive in the logs so, would this still fall under this issue or general CI related ones?

**Comment by bgruening** [comment]
@unode it seems that the upload to anaconda actually worked isn't it?

https://circleci.com/gh/bioconda/bioconda-recipes/46302

The problem seems to be on the quay.io site that your Docker container is not uploaded because it takes longer than 10min. This is because the Docker container contains the 1GB file of the post-link script. The solution could be to fix our CCI setup to not time-out after 10min without output.

**Comment by unode** [comment]
> @unode it seems that the upload to anaconda actually worked isn't it?

The second try made a little more progress. The first didn't get to upload anything.

> The solution could be to fix our CCI setup to not time-out after 10min without output.

Would printing some kind of progress mark also help?
Dots (`.`) printed during testing, maybe the same could be done with upload?
