### ISSUE TITLE
conda install cyvcf installs cyvcf2

### ISSUE THREAD

**Issue by mfoos** [bioconda/bioconda-recipes#13609]
Hi there, I was recommended a python package called cyvcf, and when I created an environment with it, everything installed without error. When I tried to `import cyvcf` it said module not found. After digging into paths in every way I knew how, a coworker tried `help('modules')` and we discovered that cyvcf installs cyvcf2, which is a different piece of software. You can see in the "home" link on the Anaconda package page that it does not go to cyvcf: https://anaconda.org/bioconda/cyvcf

Can you please fix either the name of the package, or the source link? (the former may be more appropriate, since cyvcf seems to be more regularly updated) Thank you!

**Comment by wdecoster** [comment]
cyvcf seems quite old and unmaintained. I think cyvcf2 would be better (I use it a lot), but I don't know your application...

**Comment by mfoos** [comment]
I've actually already gone ahead and completed my project with cyvcf2, I just wasted a lot of time troubleshooting the installation issue and I'd like to save someone else that frustration. I've alerted the authors of both, so presumably if they want to fight for one configuration or another, they will do so. Thanks.

**Comment by wdecoster** [comment]
Good point.

The authors are also from the same group (Quinlan and Pedersen). Probably no need for a fight as cyvcf2 is the successor of cyvcf ;-)
