### ISSUE TITLE
Docker image not on quay.io

### ISSUE THREAD

**Issue by johnlees** [bioconda/bioconda-recipes#13628]
I had a merged recipe #13468 which is available on anaconda, but I can't find the docker image on quay.io
I assumed that the docker image is created automatically after upload to anaconda, but I can't find any documentation about this though. Any ideas why it's not available?
Is this due to a failure of the BusyBox build? If so, how can I find information on the error?

Thanks!

**Comment by bgruening** [comment]
@johnlees it's here: https://quay.io/repository/biocontainers/spydrpick

(was hidden by default and is now visible)

**Comment by johnlees** [comment]
Brilliant, thank you!
