### ISSUE TITLE
Defiant: Differential methylation: Easy, Fast, Identification and ANnoTation

### ISSUE THREAD

**Issue by grehl** [bioconda/bioconda-recipes#13624]
Hi together,

it would be great if you could please add the tool "Defiant" to bioconda. It is a caller for differential methylation and outperformed every other DMR caller in our benchmark studies. 

https://github.com/hhg7/defiant

All the best,
Claudius

**Comment by epruesse** [comment]
Hi @grehl - it's unlikely someone with the time to spare to package something they don't know or use is going to come along here. Perhaps you can try? Or you could write an issue over at hhg7's repo and perhaps convince the upstream author to help you.

**Comment by npavlovikj** [comment]
@grehl , we have a conda package for "defiant" on our local HPC conda channel. I haven't used the package myself, but I can port the recipe here and you can give it a try.
