### ISSUE TITLE
Testing build script commands in docker image?

### ISSUE THREAD

**Issue by mbhall88** [bioconda/bioconda-recipes#13641]
Is there a way that I can get a docker image that has the same environment as the one when build is running my `build.sh`?  

I am trying to debug my build script but the process is super slow as I change something in my script and then rerun build and it takes 5 minutes each time.

**Comment by acaprez** [comment]
Yep, I do the same thing quite often.  The name of the Docker image used is [here](https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/docker_utils.py#L280).  Assuming you're in the top level of the repo, run `docker run -it -v $PWD:/repo bioconda/bioconda-utils-build-env:2019-02-01 bash` to start a shell in the container.  The repo will be mounted at `/repo` inside the container.  To build the recipe, `cd` to your package's directory (`/repo/recipes/<my_package>`) and run `conda build -e /opt/conda/conda_build_config.yaml -m /opt/conda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml .`

**Comment by mbhall88** [comment]
Fantastic. Thanks @acaprez , this worked a treat.
