### ISSUE TITLE
mothur 1.36.1 boost library incompatibility

### ISSUE THREAD

**Issue by pvanheus** [bioconda/bioconda-recipes#1365]
The default version of mothur installed from the bioconda channel is 1.36.1. This installs boost 1.60.0 as a dependency but when run you get:

mothur: error while loading shared libraries: libboost_iostreams.so.1.57.0: cannot open shared object file: No such file or directory

**Comment by shiltemann** [comment]
hmm, which build number are you pulling? I encountered the same problem, but this should have been fixed in build 1 (see #1203) by pinning the boost dependency version to the one used at build-time (in the way of #1207)

**Comment by shiltemann** [comment]
hmm, seems build 1 is not yet available in the bioconda channel?

@bgruening @johanneskoester ..did something go wrong here?

**Comment by yhoogstrate** [comment]
How it worked for me: `conda install mothur boost=1.57.0` or `conda create -n mothur mothur boost=1.57.0`

**Comment by johanneskoester** [comment]
Sure, manually specifying the version will always work. I will investigate the issue ASAP. It looks like the building works, but the package is not uploaded properly...

**Comment by johanneskoester** [comment]
Should be fixed now. The pinned version has been uploaded.
