### ISSUE TITLE
why new recipe not available in channel

### ISSUE THREAD

**Issue by gmat** [bioconda/bioconda-recipes#13661]
Hi,
do you know why I still don't find the package isocor in the channel ?
The recipe was accepted in the master one day ago, before for example an update of snakemake.
Did I do something wrong ?
Thanks for your help

**Comment by mbhall88** [comment]
Is it not this one? https://anaconda.org/bioconda/isocor

**Comment by gmat** [comment]
Yes ! this is it.
But I have done some mistake because it's only build on macos... 
Maybe that's why it was so long to be online.
I should correct the recipe to be a noarch one.
