### ISSUE TITLE
2to3 step not being run on mongoengine installation

### ISSUE THREAD

**Issue by mbhall88** [bioconda/bioconda-recipes#13699]
When executing `mykrobe` from [this recipe](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/mykrobe) I am getting an [error coming from `mongoengine` relating to code that is not compatible with python3](https://github.com/Mykrobe-tools/mykrobe/issues/44). After [raising this issue on the `mongoengine` repository](https://github.com/MongoEngine/mongoengine/issues/2003) it looks like what is actually happening is that a [line within the `mongoengine` `setup.py` that should make the package python3 compatible](https://github.com/MongoEngine/mongoengine/blob/db4760486558f42d4a36540159c41844f20a7b53/setup.py#L60) is not happening/working for some reason.  

There must be something I am missing or doing incorrectly in the building of the `mykrobe` recipe for this to not work as when I run mykrobe in a container with only python3 it runs fine and I dont get this python compatibility problem.  

Is anyone able to take a look at [the recipe](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/mykrobe) and see if there is something I can change to fix this? As it currently stands the mykrobe bioconda recipe is not useable as a result of this problem.

**Comment by bgruening** [comment]
@mbhall88 you could skip the python2 build for your package for the time being I think.

**Comment by mbhall88** [comment]
@bgruening I believe I already am? https://github.com/bioconda/bioconda-recipes/blob/4697c00b0c0cfd965666aef9ce7d3cd60d244116/recipes/mykrobe/meta.yaml#L14

**Comment by mbhall88** [comment]
It appears that there may have been an issue with the mongoengine recipe on conda https://github.com/conda-forge/mongoengine-feedstock/commit/4c31a9896078a8df74b1222d393d30861aba2556  
I will try bumping the build number and see if that fixes it using the new mongoengine recipe.
