### ISSUE TITLE
usearch and license issues

### ISSUE THREAD

**Issue by dkoppstein** [bioconda/bioconda-recipes#137]
I use usearch and wanted to add a recipe for it, but noticed that the terms of use do not allow redistribution (although the author apparently is willing to give out redistribution licenses for free). I think I will contact Robert Edgar to ask if we can have a redistribution license. 

More generally, we should probably check whether redistribution is allowed for each package that we add (licensing issues I think don't apply to this repository, but maybe to the binstar channel).

**Comment by johanneskoester** [comment]
Absolutely.

**Comment by dkoppstein** [comment]
It looks like we can't obtain a redistribution license (@johanneskoester cc'd). I've heard of [vsearch](https://github.com/torognes/vsearch) as an alternative, but haven't used it. It looks like the latter would be under GPL which would require licenses to be redistributed with the bzipped tarball.

**Comment by johanneskoester** [comment]
Do you really think that the license has to be in the tarball? It will be mentioned in the meta.yaml and linked on the anaconda page.

**Comment by dkoppstein** [comment]
Good point, I had just [glanced over it](https://github.com/torognes/vsearch/blob/master/LICENSE.txt) and noticed 

    1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.

Whereas what I think applies to us is

    2. Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.

So I think you're right, it should be fine.

**Comment by johanneskoester** [comment]
vsearch looks promising at first sight. I would always prefer the free alternative if it is not worse.

**Comment by kyleabeauchamp** [comment]
One idea is to create two separate repositories (or maybe two channels).  One for things that are open source and fully redistributable, and another for things that have a non-OSS license. 

For example, I believe linux package managers generally maintain separate channels for "free" and "non-free" software (https://www.debian.org/legal/licenses/).

**Comment by johanneskoester** [comment]
For debian, one of the reasons is that the first is activated by default and the second is optional, in order to be able to call debian FOSS. I don't think that we need something like that for Bioconda. If the license allows redistribution, we can include the package. If the license does not allow it, we can't, even in a "nonfree" channel.

**Comment by kyleabeauchamp** [comment]
I bet that some of the non-FOSS licenses are legally unclear about redistribution.  Also, the dependency solver will automatically install (and potentially even run) software regardless of license legality.  

I imagine that people in industry would be happy to contribute to this project if there were stronger separation between the FOSS software and the "academic" licensed software.

**Comment by johanneskoester** [comment]
Ok, that's a point. Maybe we can make a list of packages that would have to be in such a channel to evaluate if it is worth the effort.

**Comment by marcelm** [comment]
I’ve used VSEARCH a bit and it is really nice. It aims to be a drop-in replacement for USEARCH (same command-line options etc.), but the last time I checked, it did not have all the functionality, so people will still want to use USEARCH.

**Comment by colinbrislawn** [comment]
VSEARCH is now dual-licensed under GPL and BSD, so this is a non issue. Also, the vsearch devs are comfortable with us building recipes for it: https://github.com/torognes/vsearch/issues/134 

While we could ask robert@drive5.com for permission to distribute USEARCH, I'm not sure he would say yes and I'm not sure folks are interested in supporting proprietary software. My vote is to support vsearch.

**Comment by dkoppstein** [comment]
I already asked Robert and he said no, so we can go ahead with vsearch.

**Comment by bgruening** [comment]
vsearch was added! Thanks! Closing this now.

**Comment by happykhan** [comment]
Usearch is now open source
