### ISSUE TITLE
Replacing/updating hall-lab-svtools

### ISSUE THREAD

**Issue by ernfrid** [bioconda/bioconda-recipes#1372]
I've been significantly updating the hall-lab svtools suite and am narrowing in on a release. I was thrilled to see that there is already a bioconda recipe for an earlier version and would like to make a conda recipe for the new version. 

I had a question though, the bioconda recipe is for hall-lab-svtools. The package itself is called svtools and I've uploaded it to pip under that name. Is it possible to remove or rename the old package? What would be your recommendation?

**Comment by bgruening** [comment]
I would keep the old version and add a comment to the yaml that this one is deprecated and replaced by the new one.

**Comment by johanneskoester** [comment]
For me, it would be fine to remove the old recipe from the repository, and just keep the packages in the bioconda channel. This would further decrease the chance that people install the old one. @brainstorm this is your recipe, what do you think?

**Comment by chapmanb** [comment]
Dave;
Thanks for the work on svtools and updating the bioconda package. I'm the originator of the hall-lab-svtools name and was probably being over specific. Happy to call it whatever you prefer and agree with Johannes that we can rename the current one to svtools and then update. Thanks again.

**Comment by brainstorm** [comment]
@johanneskoester, IIRC the reason for the naming was to differentiate from the different forks and name collisions the tool was having at the time. It's totally ok with me to remove (rename) the old tool and upload the new one with `svtools` name, much better, IMHO. Thanks all!

**Comment by johanneskoester** [comment]
@ernfrid, looks like we have a decision here. Feel free to take over the existing recipe, rename it to svtools and update the version. Do you want me to add you as a bioconda member?

**Comment by ernfrid** [comment]
Got it! Thanks very much everybody. I really appreciate the guidance.

@johanneskoester - Definitely add me. That sounds great.

Just so you're all aware. I'm still waiting on some documentation before releasing so there may be a delay before you see a new recipe.

**Comment by bgruening** [comment]
@ernfrid thanks for your contribution. I will close this issue now.
