### ISSUE TITLE
Multiqc biocontainer does not include `ps` tool

### ISSUE THREAD

**Issue by pditommaso** [bioconda/bioconda-recipes#13751]
The Multiqc container created by the Bioconda recipe does not include the `ps`. 

```
docker run   quay.io/biocontainers/multiqc:1.6--py35h24bf2e0_0 sh -c 'ps'
sh: 1: ps: not found
```

The `ps` command is used by NF to collect execution stats when the metrics feature is enabled and therefore the execution fail. 

This seems related to the extended base image used by the Multiqc recipe. See more here https://github.com/BioContainers/containers/issues/308#issuecomment-465709990. 

As rule of thumb the extended base image should be a superset of the stock biocontainer image, therefore including at least the same minimal toolset.  

cc @bgruening @ewels

**Comment by bgruening** [comment]
@johanneskoester can we choose another extended base image? What were your criteria for the last one?

**Comment by dpryan79** [comment]
@bgruening Should we add "Adding ps to the extended image" to our list of things to discuss (not that I expect there'd be much objection)?

**Comment by bgruening** [comment]
Yes, please let's add this and let's discuss this.

**Comment by dpryan79** [comment]
I'll put it on the list (we should schedule this meeting at some point...)

**Comment by rspreafico** [comment]
Upvoting this issue. There was previous discussion on ensuring compatibility between Biocontainers and Nextflow with a number of Github issues addressed last year. The lack of `ps` only in a single container breaks the expectation that a minimal toolset is available in any biocontainer. So far, `multiqc` was the only biocontainer lacking `ps` that I could find. Also, the other option `ewels/multiqc` either lacks `ps` in older versions or lacks `bash` in newer versions. So currently one would need to set up its own Dockerfile for `multiqc` to work with Nextflow, which seems unnecessary. Given how widespread multiqc is, the impact of lacking `ps` is substantial.

See:
https://github.com/BioContainers/mulled/issues/148
https://github.com/nextflow-io/nextflow/issues/321
https://github.com/ewels/MultiQC/issues/935

**Comment by rspreafico** [comment]
While this is being fixed, interested parties may use the official MultiQC container from @ewels, who has just released a `bash` and `ps`-able container with tag `1.7` (NOT `v1.7`). Future containers will all be using the same `bash` and `ps`-able base. 

https://github.com/ewels/MultiQC/issues/935

**Comment by dpryan79** [comment]
A small update on this since we had a meeting a few hours ago, we'll try to add `ps` to conda-forge first and if that proves a nightmare only then add it to the container. I'll attempt that tomorrow, so we should know pretty quickly how easy it will prove to be.

**Comment by dpryan79** [comment]
procps-ng (this provides, `ps`, `top`, etc.) is now in conda-forge, so we can add it to the multiqc package (for linux only) so it ends up in the biocontainer.

**Comment by bgruening** [comment]
I think we should add this to https://github.com/bioconda/bioconda-extended-base-image/blob/master/Dockerfile#L6. This way all extended-base images can be run with nextflow. MQC is just a very well known tool, but this problem exists for all those containers.

Moreover, this is not a requirement of MQC isn't it? It's a nextflow requirement.

**Comment by ewels** [comment]
Exactly my thoughts @bgruening - this dependency doesn't really have anything to do with MultiQC, it's purely so that the container (for any tool) can be used with nextflow.

**Comment by dpryan79** [comment]
Yeah, that was a misunderstanding on my part. Xref: https://github.com/bioconda/bioconda-extended-base-image/pull/8

**Comment by ewels** [comment]
Still super nice to have `ps` conda-installable though, will make solving similar issues for other containers in the future a little easier.. 😉 Thanks!

**Comment by bgruening** [comment]
I hope https://github.com/bioconda/bioconda-recipes/pull/14473 will fix this. All new containers will have ps installed.

Please reopen if this is not the case.

**Comment by rspreafico** [comment]
Thanks guys!
