### ISSUE TITLE
samtools should depend on ncurses-5.9-4

### ISSUE THREAD

**Issue by simonvh** [bioconda/bioconda-recipes#1377]
samtools-1.3-2 doesn't work with ncurses-5.9-0 from the defaults channel:

```
$ samtools
samtools: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar
```

Installing ncurses-5.9-4 from the r channel will fix this issue.
Is it possible to have samtools depend on ncurses from the r channel?

**Comment by johanneskoester** [comment]
The r channel is specified as a dependency of bioconda on our homepage. We cannot guarantee that bioconda works without the r channel. Unfortunately, as far as I know there is no way to enforce a particular channel as a dependency, sorry.

**Comment by johanneskoester** [comment]
Feel free to reopen if you disagree or have a suggestion how to improve this.

**Comment by simonvh** [comment]
Sorry, reopening :). If the r channel is required anyway, could samtools then just not depend on ncurses-5.9-4? It's only present in the r channel, but that wouldn't hurt then, would it?

**Comment by johanneskoester** [comment]
You are actually right, the ncurses version used for building samtools should be pinned. Thanks for reopening.

**Comment by marcelm** [comment]
I believe this issue can be closed.

**Comment by bgruening** [comment]
@marcelm thanks the pointer.
