### ISSUE TITLE
Depending on a glibc package

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#1378]
Hi @bioconda/core, there are a couple of glibc packages on different channels. My question to you: do you think depending on a glibc package would help to avoid the need to build on an old CentOS image?
This might also make us more flexible in case we run into a package that requires a newer version of glibc.

Do you think doing this would make the conda distribution fully self-contained?

**Comment by kyleabeauchamp** [comment]
I recall a horror story where I set my bashrc PATH and LD_LIBRARY_PATH to ignore the system glibc and use my user-space one.  I basically bricked my cluster login and had to have the sysadmin sudo rm the bashrc file from my home directory :)  Obviously conda is a bit smarter because it uses RPATH instead of setting LD_LIBRARY_PATHS.

My silly story aside, though, I think we should see what the continuum folks recommend on that one.  AFAIK if they start packaging GLIBC, then it's probably feasible.  IMHO we should "go with the flow".

**Comment by johanneskoester** [comment]
There is also an intermediate way I think. We can use an old glibc as a build dependency. This way, we get compatible builds even if the package is build on a newer system.

**Comment by kyleabeauchamp** [comment]
On a somewhat related note, my old colleague wrote a PEP (https://www.python.org/dev/peps/pep-0513/) that suggests that recommends using restricted subsets of GLIBC and building on older boxes.    Probably worth a read because it points the way that pip / wheel is headed.

**Comment by chapmanb** [comment]
I'm also nervous about this change as I don't have enough experience with glibc to know about the consequences. I liked the old approach as it was battle tested, and I'm on the side of if ain't broke don't fix it. If we had someone who was able to test packages on older CentOS 5 machines that would be helpful.

**Comment by bgruening** [comment]
:+1: for "go with the flow". This idea seams very appealing to me but I also fear some unexpected consequences.

**Comment by yesimon** [comment]
I wasn't able to get linuxbrew standalone to work with a built from source glibc after much effort on an older RHEL system, so I would strongly advise against it.

**Comment by johanneskoester** [comment]
I see. Can you give us some details about the problems that occured?

**Comment by yesimon** [comment]
Here's one example Linuxbrew/linuxbrew#867, experienced through linuxbrew standalone, which builds a standalone glibc. Building glibc works, but things started breaking left and right - for example this mysterious segfault on tmux.

**Comment by bgruening** [comment]
We are now depening on conda-forge and I think we agreed all on following there advice on these kind of questions. Currently, they don't build there own glibc but using CentOS-6 to compile against glibc.

I will close this for now, but feel free to reopen if necessary.
