### ISSUE TITLE
C compiler error for at the hhsuite conda package

### ISSUE THREAD

**Issue by martin-steinegger** [bioconda/bioconda-recipes#13798]
My conda package for hhsuite (https://github.com/soedinglab/hh-suite/) is failing at the ci/circleci: test-linux step. https://circleci.com/gh/bioconda/bioconda-recipes/45644?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link 

The error that seems to occur is that the C compiler "/opt/rh/devtoolset-2/root/usr/bin/gcc"  can not compile a simple test program. Is this any issue in my recipe or is it occurring because of the gcc update?

**Comment by dpryan79** [comment]
If this is still an issue then please reopen. You'll need to pass `$CC` in as the compiler, since `gcc` will not work.
