### ISSUE TITLE
rename to bioconda-recipes?

### ISSUE THREAD

**Issue by dkoppstein** [bioconda/bioconda-recipes#138]
I generally organize my repos like `src/github.com/bioconda/recipes`, so my fork of this is called `src/github.com/dkoppstein/recipes`, which makes it look like my personal repo of favorite dinners. Maybe we should make like [conda/conda-recipes](https://github.com/conda/conda-recipes) and call it `bioconda/bioconda-recipes`.

**Comment by kyleabeauchamp** [comment]
I like bioconda-recipes because I currently have forks of 2 different repositories called `conda-recipes`:

https://github.com/omnia-md/conda-recipes

https://github.com/conda/conda-recipes

**Comment by daler** [comment]
I typically specify a path to clone into, like
```
git clone git@github.com:bioconda/recipes.git bioconda-recipes
```
That way my local filesystem is uncoupled from github and I can call things by whatever makes sense to me.

You can always run

```bash
cd bioconda-recipes
git remote -v
# origin	git@github.com:bioconda/recipes.git (fetch)
# origin	git@github.com:bioconda/recipes.git (push)
```

to see where the origin is for any arbitrarily-named clone.

**Comment by kyleabeauchamp** [comment]
I guess my point is that if everyone is already doing the `recipes` -> `bioconda-recipes` locally, we might was well do it globally.

**Comment by johanneskoester** [comment]
For me, renaming to bioconda-recipes would be fine. Your arguments are reasonable.
Any objections?

**Comment by daler** [comment]
I was just providing counter-argument rather than objecting -- rename away!

**Comment by johanneskoester** [comment]
Ok, I have done the renaming. Please update your local clones and forks! Sorry for the inconvenience.
