### ISSUE TITLE
PLEK still missing PLEK.range

### ISSUE THREAD

**Issue by khourhin** [bioconda/bioconda-recipes#13807]
I am trying to use plek:

Install:
```
conda create -n plek
conda install -n plek -c bioconda plek
```
But apparently I still get the PLEK.range file missing from `bin` even after this fix: #13389 

Run:
```
PLEK.py -fasta test.fas -out test
```

> [2019-02-26 12:00:17] Beginning PLEK run (Version 1.2) 
[2019-02-26 12:00:17] PLEK is running
[2019-02-26 12:00:17] Calculating k-mer usage
        52 sequences.
[2019-02-26 12:00:18] Scaling data
can't open file /home/khourhin/programs/miniconda3/envs/plek/bin/PLEK.range
can't open file /home/khourhin/programs/miniconda3/envs/plek/bin/PLEK.range
can't open file /home/khourhin/programs/miniconda3/envs/plek/bin/PLEK.range
can't open file /home/khourhin/programs/miniconda3/envs/plek/bin/PLEK.range
can't open file /home/khourhin/programs/miniconda3/envs/plek/bin/PLEK.range
[2019-02-26 12:00:18] Predicting
[2019-02-26 12:00:23] Run complete
        Result file: test
Traceback (most recent call last):
  File "/home/khourhin/programs/miniconda3/envs/plek/bin/PLEK.py", line 403, in <module>
    Total_count-Noncoding_count, Total_count, 1.0*(Total_count-Noncoding_count)/Total_count*100, 
ZeroDivisionError: float division by zero

Am I missing something ?

Thanks !

@sschmeier

**Comment by bgruening** [comment]
Thanks for the report, can you please try the latest version?
