### ISSUE TITLE
Question about contributing a recipie

### ISSUE THREAD

**Issue by SilasK** [bioconda/bioconda-recipes#13826]
Hello, I's like to optimize how I build conda recipies. 

I read the [Guide](https://bioconda.github.io/contribute-a-recipe.html) but several things are not clear to me.

1. Can I run the mulled test on a osx

2.  It is not clear how to install the `bioconda-utils`. On https://github.com/bioconda/bioconda-utils states it can be instlaled with conda but it's better to see on https://bioconda.github.io/contribute-a-recipe.html to match the architecture. 

3. `bioconda-utils update` is not a valid command
```
bioconda-utils update recipes/ config.yml --packages gdsctools
usage: bioconda-utils [-h]
                      {build,dag,dependent,lint,duplicates,update-pinning,bioconductor-skeleton,clean-cran-skeleton,autobump}
                      ...
bioconda-utils: error: invalid choice: 'update' (choose from 'build', 'dag', 'dependent', 'lint', 'duplicates', 'update-pinning', 'bioconductor-skeleton', 'clean-cran-skeleton', 'autobump')
```

**Comment by frytime32** [comment]
I am having the same issue with updating recipes, 'update' is an invalid choice.

**Comment by ljq12697** [comment]
Same issue when building recipies using `bioconda-utils` following the [Guide](https://bioconda.github.io/contribute-a-recipe.html).

**Comment by dpryan79** [comment]
It rarely matters whether you install with pip from github or `conda install`, you'll usually get the same thing. As others have noticed, `autobump` is the current name of the `update` subcommand.

**Comment by dpryan79** [comment]
BTW, feel free to reopen if there are other questions.
