### ISSUE TITLE
Moving Bioconda to anaconda.org CDN

### ISSUE THREAD

**Issue by msarahan** [bioconda/bioconda-recipes#13832]
Greetings from the Anaconda team.  In an effort to reduce the load on our anaconda.org servers, we'd like to shift your channel over to our CDN.  Here are the implications:

1. Only the "main" label would be on the CDN.
2. Packages on the CDN will have a delay in availability from when they are uploaded, and when the next mirroring/indexing operation happens.  We would try for scheduling those every 20 minutes, but we can't make any sort of service level promise.
3. Packages on the CDN should have much faster download speeds, especially for people who are further from the US East Coast.
4. CDN-enabled channels will benefit from the new package format, while other anaconda.org channels will not, because anaconda.org does not support the new format yet.  This is more of a near-future benefit, rather than a current benefit.
5. You would gain the ability to hotfix your repodata to fix old packages with bad metadata.

Conda-forge has been on the CDN for several months now.  Things seem to be mostly OK for them.

Is this OK with your community?  If so, is there a convenient time for making the switch?  There were a few small hiccups with conda-forge, but it should be smoother now.  Nevertheless, planning for some small potential disruption would be wise.

**Comment by bgruening** [comment]
:+1: from me. This is very exciting, thanks a lot Mike! Let's ask others from @bioconda/core!

**Comment by tomkinsc** [comment]
Thanks, Mike! This is wonderful news. We've been seeing a fair number of intermittent network failures when installing packages from anaconda.org; being on the CDN should certainly help.

**Comment by dpryan79** [comment]
This is excellent news, faster downloads for everyone (and earlier support of the new format) will benefit everyone! Thumbs up from me!

**Comment by johanneskoester** [comment]
Excellent news, thanks @msarahan!

**Comment by johanneskoester** [comment]
Regarding time, @bioconda/core I have no preference, but let us do that when there are no major migrations underway. So, as I understood there will be the openssl migration soon. Maybe afterwards?

**Comment by dpryan79** [comment]
Yes, after the OpenSSL migration makes sense. I don’t think that will take so terribly long, but time will tell.

**Comment by johanneskoester** [comment]
Ok, let's do it like that. @msarahan we will contact you here once openSSL migration is done. As I understood @dpryan79 before, this will be in a couple of weeks, once conda-forge is finished with it.

**Comment by dpryan79** [comment]
I'm hoping to get the OpenSSL migration going tonight. We don't have a huge number of packages directly using is (a couple hundred, almost exclusively ucsc-* stuff and samtools/htslib/etc.), so I'm hoping that that will be "finished enough" by Monday morning. I'll give an update around that time.

**Comment by dpryan79** [comment]
@johanneskoester @msarahan I'm now finished updating packages for the OpenSSL migration, so you have the all-clear from me to begin moving things to the CDN.

**Comment by dpryan79** [comment]
@msarahan Are things being migrated over to the CDN now? We're noticing a LOT of failed builds at the moment and I'm hoping that that's the reason.

**Comment by msarahan** [comment]
Nope, something else is wrong.  We're looking into it.

**Comment by dpryan79** [comment]
OK, thanks for the update!

**Comment by johanneskoester** [comment]
@msarahan any update in the CDN migration?

**Comment by msarahan** [comment]
It's on our sprint for this week, but unfortunately it looks like it probably won't happen this week.  We'll keep trying to get to it.

**Comment by dpryan79** [comment]
Let us know if there's anything we can do on our end to facilitate things.

**Comment by msarahan** [comment]
Will do.  Sadly, it's mostly just a case of being pulled in too many directions at once.  This is a priority, though, because it will definitely help anaconda.org have less errors.

**Comment by epruesse** [comment]
Thanks @ContinuumIO! :)

The CDN is working nicely.
