### ISSUE TITLE
rMATS bioconda version

### ISSUE THREAD

**Issue by shihaoshen** [bioconda/bioconda-recipes#13853]
https://anaconda.org/bioconda/rmats/4.0.2/download/linux-64/rmats-4.0.2-py27h24bf2e0_0.tar.bz2

For rMATS 4.0.2 on bioconda, its two binary files are different from the rMATS 4.0.2 Sourceforge version:
https://sourceforge.net/projects/rnaseq-mats/files/MATS/rMATS.4.0.2.tgz/download

Could someone check what causes the difference in these two pre-complied binary files? Thanks.

diff -r rmats-4.0.2-py27h24bf2e0_0/rMATS/ rMATS.4.0.2/rMATS-turbo-Linux-UCS4/
Binary files rmats-4.0.2-py27h24bf2e0_0/rMATS/rMATS_C/rMATSexe and tmp/rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rMATS_C/rMATSexe differ
Only in rmats-4.0.2-py27h24bf2e0_0/rMATS/rMATS_P: FDR.pyc
Only in rmats-4.0.2-py27h24bf2e0_0/rMATS/rMATS_P: inclusion_level.pyc
Only in rmats-4.0.2-py27h24bf2e0_0/rMATS/rMATS_P: joinFiles.pyc
Only in rmats-4.0.2-py27h24bf2e0_0/rMATS/rMATS_P: paste.pyc
Binary files rmats-4.0.2-py27h24bf2e0_0/rMATS/rmatspipeline.so and tmp/rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rmatspipeline.so differ

**Comment by dpryan79** [comment]
Conda uses an rpath for libraries, which is the cause of the differences:

    $ objdump -x foo/rMATS/rMATS_C/rMATSexe | grep RPATH
      RPATH                $ORIGIN/../../lib
    $ objdump -x rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rMATS_C/rMATSexe | grep RPATH
    $ 

The former is the conda binary. The same can be seen in the shared library.

**Comment by shihaoshen** [comment]
Thanks for the reply. I can verify that the 4.0.2 version on bioconda generates the same results as the rMATS 4.0.2 Sourceforge version.
