### ISSUE TITLE
1000 packages

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#1389]
Dear @bioconda/all,
I just noticed that we recently reached 1000 packages! I want to thank all of you for the amazing work you have done to make this happen!

Please help me spreading the word by liking or retweeting (or however people call this) this tweet:
https://twitter.com/johanneskoester/status/724585414309326851

Thanks!  
Johannes

**Comment by bgruening** [comment]
What a great community!

**Comment by zachcp** [comment]
thanks for spearheading this, Johannes.

**Comment by daler** [comment]
The new `scripts/utils.py` makes it easy to do things like this:

```python
from scripts.utils import get_dag, get_recipes, nx
nx.write_gml(get_dag(get_recipes('.'))[0], 'dag.gml')
```

After loading `dag.gml` into Gephi, scaling node labels by out-degree and running YifanHu layout followed by Label Adjust layout we get something like this. I was a little surprised by how depended-upon `pysam` is. `R` is in the `r` conda channel, otherwise I bet that would be the most-depended-on package.

![dag](https://cloud.githubusercontent.com/assets/115406/14944137/a722bb52-0fb8-11e6-9c39-3e3439281397.png)

**Comment by johanneskoester** [comment]
Very nice Ryan! Looking at utils.py lets me think we should move away from scripts and have a proper bioconda-utils package that offers build, test and e.g. the DAG drawing as subcommands. This would avoid code duplication as we have it now.

**Comment by daler** [comment]
Thanks, and I definitely agree on a bioconda-utils package. My next step was going to be refactoring build-packages.py to use utils.py to cut down on duplication (more on this over on #1463).

**Comment by wilzbach** [comment]
> I just noticed that we recently reached 1000 packages!

Congrats! Sorry that I hijack this discussion a bit, but are there any plan to deal with the growing `recipes` folder? Within the last two months the number of packages went up to 1400 packages.

**Comment by bgruening** [comment]
@johanneskoester we have briefly discussed this topic here: https://github.com/bioconda/bioconda-recipes/issues/1734
My proposal was to split it according to the main language or the conda skeleton generator, e.g. perl, r, node ...

**Comment by johanneskoester** [comment]
What about having alphabetical subfolders a, b, c, d, ...?

**Comment by bgruening** [comment]
@johanneskoester which name would you take from "bioconductor-deseq"? `d` or `b`.
It seems conda-recpies has done this: https://github.com/conda/conda-recipes/tree/master/python but also only for python not for `r`. It seems everything is in a flux.

With the new package naming that was proposed we need to ensure that packages with the same name do not end up in the same directory, my feeling is that this will happen with alphabetical subfolders.

**Comment by wilzbach** [comment]
> What about having alphabetical subfolders a, b, c, d, ...?

As @bgruening already pointed out that will be very misleading and user unfriendly. Apart from the obvious fact that it will be hard to find the according folders also smaller stuff like tab-completion won't work well. I really liked the idea to group them  into their according namespaces :)

**Comment by johanneskoester** [comment]
@bgruening, that is a good point. @wilzbach, I actually thought that it would make finding the package easier. However, Björns argument holds. We just need to decide how to proceed for packages with a mixture of languages.

**Comment by bgruening** [comment]
We now passed the 1500 packages! :)
Nevertheless, I will close this issue and waiting for the 2000 package to create a new one!

**Comment by jerowe** [comment]
Awesome! Looking forward to 2000!
