### ISSUE TITLE
GATK4 conda environment isn't activated by the bioconda recipe

### ISSUE THREAD

**Issue by cmnbroad** [bioconda/bioconda-recipes#13904]
Most GATK4 tools depend only on Java, but some (the CNN and CNV tools) also depend on Python, and use a conda environment to establish a set of Python dependencies. The .yml file defining the conda environment is [shipped with GATK4](https://github.com/broadinstitute/gatk#python).

It looks like the current GATK4 bioconda recipe doesn't activate/include the GATK conda environment, which is creating confusion for bioconda users. Is there a way to integrate the existing GATK4 conda .yml into the bioconda recipe in some automated way that doesn't require manually reproducing it ?

**Comment by dpryan79** [comment]
@cmnbroad The closest to an automated solution would be to make a package using that yaml file and add it as a dependency to the current GATK4 recipe. However that just shifts the burden of updating of updating dependencies to another recipe. So I don't currently foresee anything more automatic aside from writing an updater script (like we do for bioconductor packages).

**Comment by cmnbroad** [comment]
Ok, will look into those - thanks for the response @dpryan79.
