### ISSUE TITLE
sha256 codes do not match

### ISSUE THREAD

**Issue by carolzhou** [bioconda/bioconda-recipes#13919]
I compute the sha256 for my .tar.gz (tarball) file, then upload it to my GitHub repository. In running conda-build with the meta.yaml, in the step where the build script downloads the tarball from the GitHub address, there is a mismatch between the stated sha256 (in meta.yaml) and the sha256 that conda-build computes on the tarball upon downloading. Why do they not match, and how can this be fixed?

**Comment by PertuyF** [comment]
Download from the same url indicated in your `meta.yaml`, then compute the sha256sum and use this in the recipe. That's the only thing to do.

**Comment by carolzhou** [comment]
I did that. The behavior I am seeing implies that the sha256 changes. If it works once, then with the next download I get the mismatch error again. It makes no sense to me. I am not changing the file that is being downloaded.

**Comment by dpryan79** [comment]
@carolzhou Can you link to the github repository/tarball producing this issue? Usually you only have this problem if you use a tarball of an entire branch, since that will change with every commit.

**Comment by carolzhou** [comment]
The bigger problem I am trying to solve is:  I need to upload a tarball of my code into a location from which it will be downloadable when conda-build is run. I need to know the sha256 (to put in meta.yaml), and it must match the sha256 that is computed by conda-build upon download.  Right now the tarball is on git lfs. Is this an appropriate location? I don't see how to get the URL of the tarball on git lfs, or how to get the sha256 of the uploaded tarball file.  repo:  carolzhou/MultiPhATEb, tarball: multiphate.tar.gz. Thank you.

**Comment by dpryan79** [comment]
@carolzhou Can't you just tag a release on github? Then you have a static tarball you can point to.

**Comment by carolzhou** [comment]
Ok, I tagged a release on GitHub and got the URL, which ends in /releases/latest.  I manually downloaded either the .tar.gz or the .zip, and in either case the file downloads as a .tar.  I can locally compute the sha256 for that file, and put that in the meta.yaml, but what would the correct url: (or git_url) be? Do I add the name of the .tar.gz or .zip file? I've tried every combination of URL with filename.tar.gz, .zip, and .tar, and prefixed it with url: or git_url: in the meta.yaml, but conda-build always returns a 404 error. What is the correct way to construct the meta.yaml so that conda-build can download the code from the GitHub release?

**Comment by dpryan79** [comment]
Great, you can use `url: https://github.com/carolzhou/multiPhATEb/archive/v0.1.1.tar.gz`.

**Comment by carolzhou** [comment]
Thank you, that worked. Now my local conda-build can download the code and build the package. I'm now troubleshooting the test of my package, but will start a new thread on that issue, assuming the problem has not already been answered on this forum.
