### ISSUE TITLE
OpenSSL migration

### ISSUE THREAD

**Issue by dpryan79** [bioconda/bioconda-recipes#13958]
@bioconda/all Thanks to conda-forge [largely finishing their migration to OpenSSL 1.1.1](https://conda-forge.org/status/), we've now upgraded the bioconda-wide pinnings to match.

# Why was this done?

There has been a recent spate of people running into cryptic error messages due to using `conda install` and it upgrading OpenSSL on them. Recently a new minor release of OpenSSL (1.1.1) was made available in the conda-forge and defaults channels and this version is not compatible with our previous project-wide pinnings (to 1.0.2). Since OpenSSL is typically among the packages in `conda config --show aggressive_update_packages` and therefore automatically updated upon using `conda install`, this version change resulted in tools such as `samtools` no longer having a compatible OpenSSL **if** they were installed into an environment already before `conda install` was used to install a package not itself pinned to a compatible OpenSSL version.

# What do we need to do now?

We (the core team) have already taken care of updating the most commonly used packages that make use of OpenSSL (samtools, htslib, pysam, etc.), but if you have other packages you're using that you'd like to ensure are compatible with our updated pinnings then use `bioconda-utils update-pinning` [as layed out in the documentation](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change). If you have not already updated your applicable recipes for the recent compiler change change to GCC7 and clang, then not that that will be done at the same time (for more on that, see #13578 ).

We hope this will alleviate the pain many have experienced when faced with cryptic `libcrypto`-related errors upon using `conda install`.

As always, please feel free to open an issue and/or ping @bioconda/core if you run into problems.

**Comment by jbelyeu** [comment]
I'm still having a related issue. Installing with conda works fine, but the samtools package is still pointing to libcrypto.so.1.0.0. Similar to https://github.com/PacificBiosciences/pbbioconda/issues/85

Example:
`
$ samtools 

samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory 

$ openssl version 

OpenSSL 1.1.1b  26 Feb 2019 

$ conda --version

conda 4.6.7
`

**Comment by dpryan79** [comment]
What does `conda list | grep samtools` show?

**Comment by jbelyeu** [comment]
```
conda list | grep samtools
samtools                  1.9                  hb029021_5    bioconda
```

**Comment by dpryan79** [comment]
You'll need to `conda install samtools`, there are more recent builds against the updated OpenSSL.

**Comment by jbelyeu** [comment]
Ok, great, working now.

**Comment by RStadhouders** [comment]
Hi Devon,

Despite trying to follow your advice mine is still not working.

I get the following error message:

(base) ralphs-imac:~ ralphstadhouders$ samtools
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/ralphstadhouders/bioinformatics/anaconda2/bin/samtools
  Reason: image not found
Abort trap: 6

This is what conda list | grep samtools shows:

(base) ralphs-imac:~ ralphstadhouders$ conda list | grep samtools
samtools                  1.9                  hb029021_5    bioconda

Running conda install samtools just ends in telling me that everything is up to date.

Thanks in advance,
Ralph

**Comment by bgruening** [comment]
@RStadhouders the version you need to install is `samtools-1.9-h7c4ea83_11` to the 11 build number. Also try to not install into your root/base environment, always use `conda create -n samtools samtools` for example.

Hope that helps!

**Comment by RStadhouders** [comment]
Thanks Björn!

It’s strange (although I have the feeling I’m forgetting something silly):
if I run conda install samtools=1.9=h7c4ea83_11 f I get an error that it
can’t find the package. If I do conda search for it I do see it in the
bioconda channel (which already exists in my channels list, as conda
config —add channels bioconda tells me it’s already there - see below).

What am I missing here? I’m using MacOSX btw.

PackagesNotFoundError: The following packages are not available from
current channels:


  - samtools==1.9=h7c4ea83_11 -> curl[version='>=7.64.0,<8.0a0']


Current channels:


  - https://conda.anaconda.org/bioconda/osx-64

  - https://conda.anaconda.org/bioconda/noarch

  - https://conda.anaconda.org/r/osx-64

  - https://conda.anaconda.org/r/noarch

  - https://repo.anaconda.com/pkgs/main/osx-64

  - https://repo.anaconda.com/pkgs/main/noarch

  - https://repo.anaconda.com/pkgs/free/osx-64

  - https://repo.anaconda.com/pkgs/free/noarch

  - https://repo.anaconda.com/pkgs/r/osx-64

  - https://repo.anaconda.com/pkgs/r/noarch


To search for alternate channels that may provide the conda package you're

looking for, navigate to


    https://anaconda.org


and use the search bar at the top of the page.



(base) ralphs-imac:~ ralphstadhouders$ conda search samtools=1.9=h7c4ea83_11

Loading channels: done

# Name                       Version           Build  Channel

samtools                         1.9     h7c4ea83_11  bioconda

(base) ralphs-imac:~ ralphstadhouders$ conda config --append channels
bioconda

Warning: 'bioconda' already in 'channels' list, moving to the bottom


Op ma 11 mrt. 2019 om 14:20 schreef Björn Grüning <notifications@github.com

**Comment by dpryan79** [comment]
`conda install samtools=1.9` by itself should suffice, you can't give `conda install` the full hash and build number as far as I know.

**Comment by RStadhouders** [comment]
Thanks, although there are a lot of samtools=1.9 builds around:

samtools                         1.9      h28b8610_6  bioconda

samtools                         1.9      h28b8610_7  bioconda

samtools                         1.9      h46bd0b3_0  bioconda

samtools                         1.9     h7c4ea83_10  bioconda

samtools                         1.9     h7c4ea83_11  bioconda

samtools                         1.9      h8ee4bcc_1  bioconda

samtools                         1.9      hb029021_2  bioconda

samtools                         1.9      hb029021_3  bioconda

samtools                         1.9      hb029021_4  bioconda

samtools                         1.9      hb029021_5  bioconda

samtools                         1.9      hb029021_8  bioconda

samtools                         1.9      he6825b8_9  bioconda


And simply trying to install with =1.9 simply results in this:


conda install samtools=1.9

Collecting package metadata: done

Solving environment: done


# All requested packages already installed.

Op ma 11 mrt. 2019 om 15:02 schreef Devon Ryan <notifications@github.com>:

**Comment by dpryan79** [comment]
Then use `conda update samtools`
--
Devon Ryan, Ph.D.
Email: dpryan@dpryan.com
Data Manager/Bioinformatician
Max Planck Institute of Immunobiology and Epigenetics
Stübeweg 51
79108 Freiburg
Germany
<devon.ryan@dzne.de>

**Comment by RStadhouders** [comment]
Same results unfortunately… Version installed/updated is still:

samtools                  1.9                  hb029021_5    bioconda

Perhaps removing samtools and a clean install will force conda to use the
latest build?

Op ma 11 mrt. 2019 om 15:27 schreef Devon Ryan <notifications@github.com>:

**Comment by dpryan79** [comment]
Yes, give that a whirl.

**Comment by mikecormier** [comment]
Hey @dpryan79, I am having the same problem. That is, I can only install/update samtools to build 5, and am unable to access build 11. However, this seems to be isolated to an anaconda distribution. It seems that there is no problem when using a miniconda distribution. I am not sure why there would be a difference. Any suggestions?

**Comment by dpryan79** [comment]
What version of conda do you have and what else is in the environment?

**Comment by mikecormier** [comment]
Conda version: `conda 4.6.8` 
This installation of anaconda is new and the environment should be clean

**Comment by PertuyF** [comment]
You should be able to provide part of the build number with `conda install samtools=1.9=*_11`.

Otherwise, `conda install samtools=1.9 --force-reinstall` will try to install samtools even if it is already in your environment.

**Comment by unode** [comment]
How should package versions that are no longer in the git repository be handled?
For instance `blast==2.6.0` is pinned by `rgi==4.4.2` and exists in anaconda but is no longer in git-master nor does it pin openSSL. Due to this it breaks if openssl 1.1 is installed in the conda environment.

**Comment by dpryan79** [comment]
@unode The general strategy is to ignore them unless absolutely needed. These packages will still install and work fine in new environments, they just won't be able to be mixed with newer versions of other programs.

**Comment by dpryan79** [comment]
This should be done now, closing.

**Comment by YantingHuang** [comment]
this would work:
`conda install -c bioconda samtools=1.9`
