### ISSUE TITLE
Undocumented Nanopolish dependency on libcrypto.so

### ISSUE THREAD

**Issue by PertuyF** [bioconda/bioconda-recipes#14015]
Hi @bioconda/core ,

One of my users ran in a libcrypto.so error as described in #13958 using `nanopolish`, and I think it is due to the new pinning to `openssl 1.1`.
It seems that the dependency of nanopolish on libcrypto should be clearly stated somewhere in the recipe, don't you think so?

Any help will be appreciated!

#### Further info:

Creating an environment with just `nanopolish` ends up referencing libcrypto `1.0.0` (not found) and `1.1`

```shell
$ conda create -n test-nanopolish nanopolish -y
$ conda activate test-nanopolish
$ ldd $( which nanopolish ) | grep libcrypto
libcrypto.so.1.0.0 => not found
libcrypto.so.1.1 => /opt/conda/envs/test-nanopolish/bin/../lib/./libcrypto.so.1.1 (0x00007f23166be000)
```

Which results in an error while trying to run nanopolish:
```shell
$ nanopolish
nanopolish: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

I triggered rebuild of nanopolish (see #14014 ), but will this solve the issue?

**Comment by dpryan79** [comment]
I expect this is related to using `gcc` rather than `{{ compiler('cxx') }}`. I think you're getting a mixture of old and new compiler packages.

**Comment by dpryan79** [comment]
Anyway, libcrypto is getting pulled in by htslib and libcurl.

**Comment by PertuyF** [comment]
@dpryan79 you're right, I updated the recipe accordingly and it build for Linux. But it appears `gcc` was used specifically because `nanopolish` does not support building with `clang` on OSX.

I see several possible solutions:

1. Force `gcc` as compiler for OSX using selectors in the recipe
2. Force `gcc` as compiler for OSX using some recipe-level extension of `conda_build_config.yaml` (does it even exist for Bioconda?)
3. Use `{{ pin_compatible('openssl') }}` in the recipe (is it possible?)

Trying solution °1 right now, but not sure if forcing `gcc` as build dependency for OSX will not keep this libcrypto version issue.
Any thoughts?

**Comment by dpryan79** [comment]
Pinning is already performed (we reuse conda-forge-pinning), so I don't think 3 will do much. You can try 1 and 2 (you can create `recipes/nanopolish/conda_build_config.yaml` and the global versions will get updated with its contents). I also noticed that nanopolish makes use of STLs not distributed by clang, which seems to make things difficult.

**Comment by PertuyF** [comment]
Just saw you tried a few things in #14016 , but that `gcc` is not available for OSX using the new compilers.

Looks like using selectors in the recipe does the trick, build succeeded for OSX (although calling `nanopolish --help` in testing should have failed with missing `libcrypto.so.1.0.0`).

Merging #14014 and closing issue.

**Comment by dpryan79** [comment]
The `{{ compiler('c') }}` syntax just doesn't work when you change things, which I had forgotten. Glad you got it working though!
