### ISSUE TITLE
unit-tests fetches a GPU version of pytorch 

### ISSUE THREAD

**Issue by romain-lopez** [bioconda/bioconda-recipes#14020]
Hi, 

I am trying to update scVI to 0.3.0. 

It looks like when enforcing pytorch >= 0.4.1, the unit tests try to fetch version 1.0.1 of pytorch, which seems only available as a GPU version on anaconda (https://anaconda.org/anaconda/pytorch/files?version=1.0.1). This makes my PR to fail when I want to update my recipe. https://github.com/bioconda/bioconda-recipes/runs/76968620

When I enforce pytorch == 0.4.1 on one particular test, this fetches a CPU version of pytorch and I pass this particular test (https://github.com/bioconda/bioconda-recipes/runs/77616305). 

However, this seems like a suboptimal hack. Is there another workaround ? I'll revert the pytorch == 0.4.1 back to pytorch >= 0.4.1.

**Comment by dpryan79** [comment]
Specify `pytorch-cpu` as the dependency instead.

**Comment by romain-lopez** [comment]
Hi, 
that is not going to solve the problem as I would like the requirement to be independent of either the gpu version or the cpu version. However, for the unit tests, it seems that I need to force a cpu version. Is there a way to do that ? It would be inefficient to force users to use a cpu version of pytorch just because of the unit tests of bioconda-recipes.

**Comment by dpryan79** [comment]
The only way to force the CPU version is to specify that rather than the GPU version. There's unfortunately not a more flexible way at the moment. It might be easier to make a weird test that doesn't actually load pytorch.

**Comment by romain-lopez** [comment]
Thanks for your answer, I forced pytorch 0.4.1 which did not have this
problem and will wait for another version.

Best,
Romain
