### ISSUE TITLE
most updated version of BUSCO

### ISSUE THREAD

**Issue by dcopetti** [bioconda/bioconda-recipes#14032]
Hello,

I am not sure if this is the right place for this question, but my issue is that I don't have the most updated (3.0.2) version of BUSCO (https://bioconda.github.io/recipes/busco/README.html) when installing it from Bioconda.
This is what I did:
```
$ conda install busco
$ busco -v
BUSCO 2.0
$ conda update busco
Solving environment: done

# All requested packages already installed.
```
I would like to have version 3: how can I do it?
Thanks,

Dario

**Comment by dpryan79** [comment]
This seems to no longer be an issue, closing.
