### ISSUE TITLE
Problems with ShortStack installation

### ISSUE THREAD

**Issue by mgalland** [bioconda/bioconda-recipes#14033]
Dear bioconda team, 

When trying to install [ShortStack](https://github.com/MikeAxtell/ShortStack) version ShortStack version 3.8.5 with `conda create --name shortstack -c bioconda ShortStack` into its own dedicated environment, I get a bug upon execution: 

```
dyld: Symbol not found: _stdscr
  Referenced from: /Users/MG/miniconda3/envs/shortstack/bin/samtools
  Expected in: /Users/MG/miniconda3/envs/shortstack/bin/../lib//libncursesw.6.dylib
````

It comes from the samtools dependency as I also have the same error message when installing samtools `conda create --name samtools -c bioconda samtools`.

Thank your for your help,
Marc

**Comment by dpryan79** [comment]
I just tried this on a mac and can't reproduce the issue. Please use `-c conda-forge -c bioconda` and try creating new environments. My guess is that you're picking up some very old version of ncurses from bioconda rather than conda-forge.

**Comment by mgalland** [comment]
Works like a charm thanks! The `-c conda-forge` was missing indeed. 
Thanks a lot.
