### ISSUE TITLE
eggnog-mapper container does not include wget

### ISSUE THREAD

**Issue by lukasjelonek** [bioconda/bioconda-recipes#14039]
Hey,

I'd like to use the eggnog-mapper container and tried the latest release `quay.io/biocontainers/eggnog-mapper:1.0.3--py27_2`. Apparently it is missing `wget` for their database download script, although the last commit in this recipe (f935cd6a46281fb45048a98be4b77f1ce3dea117) states "Use the extended-base container because of wget issues when downloading databases". Is there a way to include the required non-busybox-wget into the container?

**Comment by bgruening** [comment]
@lukasjelonek you could add wget as a runtime dependency to the recipe.

**Comment by lukasjelonek** [comment]
I'll check it out and test it locally

**Comment by lukasjelonek** [comment]
Can you give me a hint how to build the docker container locally? I don't want to submit untested code.

**Comment by npavlovikj** [comment]
@lukasjelonek , I added "wget" to the "eggnog-mapper" recipe. The updated biocontainer is `quay.io/biocontainers/eggnog-mapper:1.0.3--py_3`.
For future reference, you can check https://bioconda.github.io/contributing.html to see how to set and test the recipe itself (usually using the bootstrap method).
Please let me know if you are still encountering issues with "eggnog-mapper".

**Comment by lukasjelonek** [comment]
@npavlovikj Thanks for the changes. Now it works for me.
