### ISSUE TITLE
womtool does not find jar file

### ISSUE THREAD

**Issue by rspreafico-vir** [bioconda/bioconda-recipes#14041]
Execute:

```
womtool
```

Get this error:

```
Error: Unable to access jarfile /Users/rspreafico/miniconda3/envs/bio/share/womtool/womtool.jar
```

Way around issue:

```
java -jar /Users/rspreafico/miniconda3/envs/bio/share/womtool-36-0/womtool.jar
```

Notice the issue is that `womtool` looks for `jar` in `.../share/womtool` whereas in fact it is in `.../share/womtool-36-0`.

**Comment by npavlovikj** [comment]
@rspreafico , I updated "womtool" to 38 (https://anaconda.org/bioconda/womtool), and this update should include the correct path to the "jar" file. Can you please give it a try, and let me know if you encounter any further issues?

**Comment by rspreafico-vir** [comment]
Thanks @npavlovikj , I confirm this works indeed. Thank you for the quick resolution!
