### ISSUE TITLE
Graphlan installing error on Windows

### ISSUE THREAD

**Issue by Mahmoudbassuoni** [bioconda/bioconda-recipes#14052]
guys I encountered an issue while installing the "Graphlan" package from bioconda so can you please help me ? 
 
this is the error that I always encounter..  

I am using windows 10 and python 2.7.16
![Capture](https://user-images.githubusercontent.com/16631169/54441756-0e04f700-4746-11e9-8476-2c0978f39e01.PNG)

**Comment by npavlovikj** [comment]
@Mahmoudbassuoni , Bioconda only supports 64-bit Linux and Max OSX systems, and not Windows.
In the "_Installers_" section of https://anaconda.org/bioconda/graphlan, you will also see that "_graphlan_" is only available for Linux and OSX.

**Comment by druvus** [comment]
It is a work around to activate Linux bash shell in W10. I have tried it and it seems to work with Bioconda even if real OS X/Linux is preferable.

See more details here: https://github.com/kapsakcj/win10-linux-conda-how-to/blob/master/README.md

**Comment by Mahmoudbassuoni** [comment]
thanks guys I tried it on Ubuntu and it haven't show any errors yet,  it still taking too much time in the "solving environment" part, is it normal ? I canceled the operation after around 30 min and now I am trying it again.

**Comment by bgruening** [comment]
@Mahmoudbassuoni please also see https://github.com/bioconda/bioconda-recipes/issues/13774
