### ISSUE TITLE
Linting recipe stuck in the queue

### ISSUE THREAD

**Issue by dariober** [bioconda/bioconda-recipes#14082]
I have pushed the branch [gat-py2](https://github.com/bioconda/bioconda-recipes/tree/gat-py2) 4 days ago and since then it is in the queue waiting for [liniting](https://github.com/bioconda/bioconda-recipes/runs/78855609). Is it normal that it takes so long or something went wrong?

**Comment by dpryan79** [comment]
@dariober That happens on occasion, Elmar is still working on the bot and ironing out the bugs. You needn't wait for it to be green to merge.
