### ISSUE TITLE
Missing (bio)container on quay.io for biopet-fastqsplitter

### ISSUE THREAD

**Issue by DavyCats** [bioconda/bioconda-recipes#14090]
As I understand it there should be a container auto-generated on quay.io for every bioconda package. However, for the [biopet-fastqsplitter](https://anaconda.org/bioconda/biopet-fastqsplitter) package there does not seem to be a container available. Did something go wrong during the creation of the container or is there some other reason it's missing?

**Comment by dpryan79** [comment]
There was probably a transient network error. If you really need it you can just make a PR increasing the build number by 1. Merging that in should create a new container :)

**Comment by unode** [comment]
@dpryan79 Writing it here as this seems to be a more prevalent issue. In #14097 we are seeing the same issue. Everything is green but nothing appeared online (bioconda, quay).

On circleCI it seems there's a build job but no upload.

**Comment by dpryan79** [comment]
@unode You'll have to remove motus from `build-fail-blacklist`. It was giving me issues in `bulk` so I had to disable building it.

**Comment by rhpvorderman** [comment]
@dpryan79 I have looked trough all of the documentation, but could not find the answer. How long does it take for containers to be built? Is there anywhere the process can be monitored? (Other than rabidly F5-ing quay.io/biocontainers/biopet-fastqsplitter)

**Comment by bgruening** [comment]
Can you all check again. There was probably an API change in quay.io so all repos are private by default. Need to fix this at some point.

**Comment by dpryan79** [comment]
The containers are uploaded right after packages once the CI job is run on the master branch, so if you see the linux/noarch package uploaded to anaconda.org then the biocontainer should within a couple minutes.

**Comment by rhpvorderman** [comment]
@dpryan79 Thank you for the answer. It was indeed uploaded in a few minutes.

> Can you all check again. There was probably an API change in quay.io so all repos are private by default. Need to fix this at some point.

And this is why I did not have access. Thanks @bgruening for enabling the repo!
