### ISSUE TITLE
Are packages rebuilt when the recipe changes?

### ISSUE THREAD

**Issue by duboism** [bioconda/bioconda-recipes#14170]
It might be a silly question but I'm not familiar with bioconda so I prefer to ask it.

I merged a recipe for a simple tool we developed based on a Github release ([plaScope](https://github.com/GuilhemRoyer/PlaScope)). After that I realized I made a mistake in the release (I forgot to bump the version number in the code) so I deleted it and recreated it (with the same version number). Therefore I had to modify the hash in meta.yml and remerge the recipe (I didn't change anything else - build number, etc.). See [this branch](https://github.com/bioconda/bioconda-recipes/tree/plascope-1.3.1) for a detailed history. I realize it's not great for building a stable and reproducible environment but I didn't want to "pollute" plaScope or bionconda with fake releases.

AFAIK, `conda install plascope` installs the first version merged (the one with the wrong version number). My question is: is a bioconda package rebuilt when the recipe changes ?

**Comment by dpryan79** [comment]
The package will only be rebuilt if you increment the build number. As is, it sees a package with the same version and build number already exists and therefore skips it.

**Comment by duboism** [comment]
Thank you. I will increment the build number.
