### ISSUE TITLE
Missing biocontainer for Lumpy

### ISSUE THREAD

**Issue by cagaser** [bioconda/bioconda-recipes#14262]
Hello. I am having the same issue as #5986 .  #14215 was merged but missing updated biocontainer for lumpy on quoy.io.

**Comment by dpryan79** [comment]
lumpy-sv is listed in `build-fail-blacklist`. Please make a PR removing it, which will then cause the new biocontainer to get built.

**Comment by dpryan79** [comment]
I just removed lumpy-sv from the blacklist, the biocontainer should be available in ~30 minutes.

**Comment by cagaser** [comment]
@dpryan79 Thank you very much!
