### ISSUE TITLE
ISMapper merged but conda package not found

### ISSUE THREAD

**Issue by rpetit3** [bioconda/bioconda-recipes#14264]
Hello BioConda Team,

I submitted and merged (after passing CI) a recipe for ISMapper (https://github.com/bioconda/bioconda-recipes/pull/14180) 7 days ago. The conda package is still not available for install [ISMapper Readme](https://bioconda.github.io/recipes/ismapper/README.html).

```
conda create -n ismapper-bioconda -c conda-forge -c bioconda ismapper
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - ismapper

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

The recipe did have samtools, so I'm wondering if it is related to https://github.com/bioconda/bioconda-recipes/issues/14162

Thank you very much for any help!
Robert

**Comment by npavlovikj** [comment]
Can you maybe try to re-trigger another build with increasing the build number to 1?

**Comment by rpetit3** [comment]
That did the trick! Thank you very much for your help @npavlovikj!
