### ISSUE TITLE
Updated package does not appear in channel

### ISSUE THREAD

**Issue by micknudsen** [bioconda/bioconda-recipes#14341]
Hi,

I bumped the version of `expansionhunter` several days ago. The PR (https://github.com/bioconda/bioconda-recipes/pull/14265) passed tests and was merged into master. However, the updated package (v3.0.0) is still not available in the bioconda channel:

```
$ conda search expansion*
Loading channels: done
# Name                       Version           Build  Channel
expansionhunter                2.0.6               0  bioconda
expansionhunter                2.0.8               0  bioconda
expansionhunter                2.0.8      hf66f9d2_1  bioconda
```

Is there a standard procedure for investigating this kind of issues? After merging of a PR into master, the rest of the update process is (as far as I know) out of my hands.

**Comment by armintoepfer** [comment]
Same here for `isoseq3` version `3.1.2`

**Comment by armintoepfer** [comment]
Pinging @bioconda/core

**Comment by dpryan79** [comment]
I'll take a look.

**Comment by dpryan79** [comment]
@micknudsen expansionhunter is in `build-fail-blacklist`. Make a new PR removing it from there and if that passes and you merge it then the package will get built and uploaded. We're working on notifying people better when they update a recipe on the blacklist, but that's not all rolled out yet.

**Comment by dpryan79** [comment]
@armintoepfer Isoseq3 was also blacklisted due to build failures last I looked, so follow the same procedure.

**Comment by parlar** [comment]
Any news on expansionhunter?

**Comment by dpryan79** [comment]
@parlar I'm not aware of anyone trying to removing it from the blacklist, so no.

**Comment by micknudsen** [comment]
@parlar I tried removing it, but it then failed for other reasons I didn't fully understand, so I gave up on my PR.

**Comment by parlar** [comment]
Okay. I've never made a conda package but I could at least try to figure out whats wrong. Am I allowed to modify the existing package? Or do I need to release a new one under my own user?

**Comment by micknudsen** [comment]
@parlar You cannot modify the existing package directly. What you'll have to do is make a fork of `bioconda-recipes`, create a new branch, make your suggested changes, and then submit a pull request.

See also https://bioconda.github.io/contribute-a-recipe.html

**Comment by parlar** [comment]
Okay, I'll give it a go. There is a first time for everything. It's about time I do something useful, for a change.

**Comment by epruesse** [comment]
> You cannot modify the existing package directly. 

Well, none of us do that. We modify the recipe that says how the recipe should be built. Since that usually doesn't work out the first time, we all do that in PRs. The build system sees the PR and tries to build the recipe for which you are proposing a change. If it succeeds, PR can get merged and the package is uploaded.
