### ISSUE TITLE
Quasitools 0.6.0 build failing in Master

### ISSUE THREAD

**Issue by ericenns** [bioconda/bioconda-recipes#14406]
quasitools uses click and #14401 passed for testing but after merging into master it failed to build for linux.

**Comment by ericenns** [comment]
@bioconda-bot hello

**Comment by ericenns** [comment]
@bioconda-bot rebuild 6772c3a

**Comment by ericenns** [comment]
@BiocondaBot rebuild 6772c3a

**Comment by ericenns** [comment]
@BiocondaBot hello

**Comment by ericenns** [comment]
@BiocondaBot rebuild

**Comment by ericenns** [comment]
@bgruening would you be able to trigger a rebuild for 6772c3a

**Comment by bgruening** [comment]
I have done so already :)

**Comment by ericenns** [comment]
Thanks @bgruening

**Comment by ericenns** [comment]
Hmm, it is still failing due to locales and click which I thought was fixed by specified `extended-base: true` in the meta.yml of the recipe.

**Comment by dpryan79** [comment]
@bgruening See the PR I just merged, hopefully that will fix things.

**Comment by bgruening** [comment]
https://github.com/bioconda/bioconda-recipes/pull/14409 ;)

**Comment by bgruening** [comment]
Let's see :)

**Comment by dpryan79** [comment]
Great minds think alike :)

**Comment by dpryan79** [comment]
Looks like that worked.
