### ISSUE TITLE
Recipe fails with: package ‘GenomeInfoDb’ could not be loaded

### ISSUE THREAD

**Issue by dariober** [bioconda/bioconda-recipes#14421]
Hi- I updated the recipe of [cnv_facets](https://github.com/bioconda/bioconda-recipes/blob/cnv_facets/recipes/cnv_facets/meta.yaml) to use the latest release. 

The build fails with `Error: package ‘GenomeInfoDb’ could not be loaded` (see https://circleci.com/gh/bioconda/bioconda-recipes/50637) even if GenomeInfoDb is listed among the packages to be installed and previous versions of this recipe worked.

Any idea what could be wrong? It seems related to issue #13846

**Comment by dpryan79** [comment]
We can probably merge this issue in with #13846.

**Comment by dpryan79** [comment]
@dariober What OS are you using? If Linux, which distribution and version?

**Comment by dariober** [comment]
Hi @dpryan79 - I'm working on a Ubuntu 18.04 workstation but I don't see why it should matter since the issue I report here fails on circleci while building the recipe (as per log https://circleci.com/gh/bioconda/bioconda-recipes/50637). 

P.S. I may open a separate issue for this. For now, worked around the problem with GenomeInfoDB by installing it in the `build.sh` script via bioconductor. However, now I get a problem with `snp-pileup` (https://circleci.com/gh/bioconda/bioconda-recipes/51133): `snp-pileup: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`

**Comment by dpryan79** [comment]
In the other thread this was mentioned to be a bit OS dependent. Just bump the build number in `snp-pileup`, it needs the new pinnings.

BTW, please don't merge you `cnv_facets` branch in without stripping the changes to genomeinfodb. We're trying to keep data packages out of the tarballs to not blow up our space usage.

**Comment by dariober** [comment]
Apologies this is off-topic for this issue... I bumped the build version of `snp-pileup` as suggested by @dpryan79 . But now the recipe for `snp-pileup fails` with 

```
/opt/conda/conda-bld/snp-pileup_1555406160180/work/conda_build.sh: line 28: g++: command not found
``` 
(see https://circleci.com/gh/bioconda/bioconda-recipes/51166) even if the [meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/371146765a9c7f38b1fce765721ae300f79b0cf3/recipes/snp-pileup/meta.yaml) for `snp-pileup` specifies

```
requirements:
  build:
      - {{ compiler('cxx') }}
      - {{ compiler('c') }}
```

**Comment by dpryan79** [comment]
See https://github.com/bioconda/bioconda-recipes/pull/14487
