### ISSUE TITLE
dendropy fails installation on OSX

### ISSUE THREAD

**Issue by dpryan79** [bioconda/bioconda-recipes#14433]
This is related to https://github.com/bioconda/bioconda-recipes/pull/14233 and I haven't been able to figure out what the problem is. At least versions 4.4.0 and 4.2.0 produce the following errors on OSX (they're fine on Linux):

```
ERROR:conda.core.link:An error occurred while installing package 'bioconda::dendropy-4.2.0-py_2'.
FileNotFoundError(2, "No such file or directory: '/Users/distiller/project/miniconda/conda-bld/sepp_1554974722683/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python3.6'")
Attempting to roll back.
```

For some reason it tries to install dendropy before installing python, which doesn't work. I've built a new dendropy which works fine in CI testing, but still fails locally (and later on pull requests for other packages that use it).

**Comment by cjw85** [comment]
Looks like something similar is happening on this [medaka](https://circleci.com/gh/bioconda/bioconda-recipes/50813?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) MacOS build.

**Comment by dpryan79** [comment]
@cjw85 Indeed, I'm not sure whether I'm happy that it's more than one package doing this now or not. I find it odd that this stuff works in a PR if I update a recipe, but then the uploaded package fails (in the case of `dendropy` I even removed the tarball that was uploaded by circleci and replaced it with the seemingly working one from my initial PR, to no effect).

**Comment by cjw85** [comment]
It's always comforting to know others are in the same boat I guess. I presume something has changed in CI recently to have caused this?

**Comment by druvus** [comment]
Seems to have been resolved in recent versions so closing.
