### ISSUE TITLE
bioconda-builder command line from the Dev Guide doesn't work as shown

### ISSUE THREAD

**Issue by simonvh** [bioconda/bioconda-recipes#1449]
I'm not sure if it's me, but the following command from the Developer Guide doesn't work for me:

```
docker run -v `pwd`:/bioconda-recipes bioconda/bioconda-builder --packages your_package --env-matrix scripts/env_matrix.yml
```

However, it does work like this:

```
docker run -v `pwd`:/bioconda-recipes bioconda/bioconda-builder --packages your_package --env-matrix /bioconda-recipes/scripts/env_matrix.yml
```

Anything I miss here?

**Comment by acaprez** [comment]
Nope, I had the same issue.  It's because the docker instance starts with `/` as the current working directory, and the repo is mounted at `/bioconda-recipes` inside of it.  So you have to prepend `/bioconda-recipes` for the path to be correct.

**Comment by daler** [comment]
Thanks, I updated the README to fix this.
