### ISSUE TITLE
Blastn can't find libpcre.so.1

### ISSUE THREAD

**Issue by minglwu427** [bioconda/bioconda-recipes#14521]
I am running a script that uses the bioconda blast package.  However, when I was running it, it gave me an error

/home/user/anaconda3/pkgs/blast-2.7.1-h4422958_6/bin/blastn: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory

However, libpcre.so.1 is in my anaconda3 library.  (But not in the blast pkgs library)  Does anyone know how to fix this issue?

**Comment by epruesse** [comment]
Can you check your channel order? 
Try `conda create env -n blast -c bioconda -c conda-forge blast` and check if it works in that environment. You probably got packages from defaults somehow.

Posting the output of `conda list` helps. Having an env like above makes that list shorter.

**Comment by druvus** [comment]
Blast got updated to 2.9.0. Please reopen if you still experience issues.
