### ISSUE TITLE
linux build didn't show up after version bump

### ISSUE THREAD

**Issue by molpopgen** [bioconda/bioconda-recipes#14528]
I bumped a recipe recently via [this PR](https://github.com/bioconda/bioconda-recipes/pull/14496)

All checks passed.  The OS build is available, but the linux build is not, meaning that `conda search -c bioconda fwdpy11` doesn't show it.

Any ideas on how to debug this?

**Comment by epruesse** [comment]
What's the difference between fwdpy and fwdpy11?

**Comment by epruesse** [comment]
Files are here: https://anaconda.org/bioconda/fwdpy11/files

**Comment by molpopgen** [comment]
> What's the difference between fwdpy and fwdpy11?

Two different projects.  The first was based on using Cython, but that quickly fell apart as the project grew (and modern C++ support in Cython remained absent).  fwdpy11 uses pybind11 and replaces fwdpy.

**Comment by molpopgen** [comment]
> Files are here: https://anaconda.org/bioconda/fwdpy11/files

Yes, and it shows the problem.  Note that 0.3.2 is missing for Linux, yet the build update passed.

```
conda search -c bioconda fwdpy11
fwdpy11                        0.1.4   py36_gsl2.2_1  bioconda            
fwdpy11                        0.2.1  py36h4f780e3_0  bioconda            
fwdpy11                        0.3.1  py36h4f780e3_0  bioconda          <---where is 0.3.2??
fwdpy11                        0.4.0  py36h4f780e3_0  bioconda            
fwdpy11                        0.4.1  py36h4f780e3_0  bioconda 
```

**Comment by epruesse** [comment]
Yes - that's a known problem. It would have gotten picked up if you had given it a few more days. Check the commits for the master branch - that's where you can see if the merge commit failed. If it does fail - no immediate package but a week or so until the nightly picks it up. 

Long story short - the Bioconda Core members have only so much time next to teaching, mentoring students, writing grants and the like. Infrastructure is not as important as community and packages, so we dedicate what time we can spare to things like getting the most recent BLAST in here and help people with their PRs. We need more volunteers to fix packages besides the ones they published themselves or need right now, though. People to help triage issues, guide new members, debug problems with installations or upstream tools, etc. Contributions at any skill level are what make this work here.

I'd be happy to get you up to speed on the infrastructure if you want to help! Code is over in the bioconda-utils repo. :)

**Comment by molpopgen** [comment]
> Yes - that's a known problem. It would have gotten picked up if you had given it a few more days. Check the commits for the master branch - that's where you can see if the merge commit failed. If it does fail - no immediate package but a week or so until the nightly picks it up.
> 
Thanks--I hadn't seen it take this long before.  I was ~1 week.

> Long story short - the Bioconda Core members have only so much time next to teaching, mentoring students, writing grants and the like. Infrastructure is not as important as community and packages, so we dedicate what time we can spare to things like getting the most recent BLAST in here and help people with their PRs. We need more volunteers to fix packages besides the ones they published themselves or need right now, though. People to help triage issues, guide new members, debug problems with installations or upstream tools, etc. Contributions at any skill level are what make this work here.
>
I hear you--I'm in the same boat.  I find the infrastructure quite confusing, especially when things fail.  I'm mostly focusing on getting other genetics colleagues to start contributing here, but it is slow going.
 
> I'd be happy to get you up to speed on the infrastructure if you want to help! Code is over in the bioconda-utils repo. :)
