### ISSUE TITLE
Phyml: Core dumped shortly after starting a job - Ubuntu 16.04

### ISSUE THREAD

**Issue by servalli** [bioconda/bioconda-recipes#14613]
I installed Phyml and its dependencies from bioconda (on Ubuntu 16.04.4)
A help message is succesfully printed. However, when I start a job, phyml crashes shortly after printing the information about the alignment. I was able to build a tree from a same alignment using <s>also a bioconda installation</s> an installation built from source downloaded here https://github.com/stephaneguindon/phyml/releases/tag/v3.3.20190321 on another machine with Ubuntu 18.04, so the input file cannot be a reason of the problem.

Here is the output:

```

. Command line: phyml -i phylip_formatted/muscle_it2_MK706.phylip -d aa -m JTT -c 4 -o tlr -b 100 






  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////

        . Sequence filename:				 muscle_it2_MK706.phylip
        . Data type:					 aa
        . Alphabet size:				 20
        . Sequence format:				 interleaved
        . Number of data sets:				 1
        . Nb of bootstrapped data sets:			 100
        . Compute approximate likelihood ratio test:	 no
        . Model name:					 JTT
        . Proportion of invariable sites:		 0.000000
        . Number of subst. rate catgs:			 4
        . Gamma distribution parameter:			 estimated
        . 'Middle' of each rate class:			 mean
        . Amino acid equilibrium frequencies:		 model
        . Optimise tree topology:			 yes
        . Tree topology search:				 NNIs
        . Starting tree:				 BioNJ
        . Add random input tree:			 no
        . Optimise branch lengths:			 yes
        . Optimise substitution model parameters:	 yes
        . Run ID:					 none
        . Random seed:					 1556010147
        . Subtree patterns aliasing:			 no
        . Version:					 3.3.20180621
        . Byte alignment:				 32
        . AVX enabled:					 yes
        . SSE enabled:					 yes

  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////

Illegal instruction (core dumped)
```

Error message from dmesg:
`[8775514.038286] traps: phyml[11420] trap invalid opcode ip:41b6c9 sp:7ffd168bfc60 error:0 in phyml[400000+163000]`

Packages installed in the same enviroment:
```
# packages in environment at /home/servalli/miniconda3/envs/phylo:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
mpi                       1.0                     openmpi    conda-forge
ncurses                   6.1                  he6710b0_1  
openmpi                   3.1.3             h1c2f66e_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
phyml                     3.3.20180621         h470a237_0    bioconda/label/cf201901
pip                       19.0.3                   py37_0  
python                    3.7.3                h0371630_0  
readline                  7.0                  h7b6447c_5  
setuptools                41.0.0                   py37_0  
sqlite                    3.27.2               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
wheel                     0.33.1                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3
```

**Comment by PertuyF** [comment]
Can you setup your conda channels [as recommended](https://bioconda.github.io/#set-up-channels), then recreate your environment and try again?

**Comment by epruesse** [comment]
Can you try running this in `gdb`, to get a little closer to the instruction?

```console
$ gdb --args phyml ...
gdb> run
[....]
gdb> thread apply all bt
```

How old is the CPU you are running on? (look at `/proc/cpuinfo`)

**Comment by epruesse** [comment]
@stephaneguindon - do you prefer looking into this here or on the issue in your repo?

It's probably not the version of Ubuntu. It might be that the older box has a CPU that is older than we support though. The issue is that each generation has gotten a little bit better at SSE (think of it as the CPU version of a  multi-channel pipette), with more instructions that can do more things, making it possible to apply it to other algorithms. This is important to a lot of the computational kernels (e.g. dada2), and very likely used by PhyML as well.

The cause can be in many places. The recent `dada2` issue was due to the way `r-rcppparallel` was built over on conda-forge, a combination of Intel TBB and gcc7 idiosyncrasies. So I'm careful about what I claim might be the reason. It could be PhyML code, it could be one of the Bioconda or Conda-Forge packages, or something else.

The `ip` and `sp` values (I think `instruction pointer` and `stack pointer`) don't help much. I would hope that running in `gdb` might get us closer to the location of the invalid instruction.

If you can recompile PhyML locally that might help too in tracking this. We will need your help, though, @servalli, as we need the machine you are experiencing the error on to trace what's causing it.

**Comment by servalli** [comment]
I set the channel order again and then created a fresh environment with
`conda create -n phylo2 -c bioconda phyml`
PhyML keeps crushing.
The resulting package list is
```
# packages in environment at /home/servalli/miniconda3/envs/phylo2:
#
# Name                    Version                   Build  Channel
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
mpi                       1.0                     openmpi    conda-forge
openmpi                   3.1.4                hc99cbb1_0    conda-forge
phyml                     3.3.20190321         h14c3975_0    bioconda

```

gdb output:

```
Program received signal SIGILL, Illegal instruction.
0x00005555555755c0 in Are_Compatible ()
```


my /proc/cpuinfo:
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
stepping        : 4
microcode       : 0x42c
cpu MHz         : 1200.117
cache size      : 15360 KB
physical id     : 0
siblings        : 12
core id         : 0
cpu cores       : 6
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 cl$
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 4200.42
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
stepping        : 4
microcode       : 0x42c
cpu MHz         : 1200.281
cache size      : 15360 KB
physical id     : 0
siblings        : 12
core id         : 1
```

**Comment by servalli** [comment]
PhyML cloned from Github repo proceeds to computation but exits with "Eigenvalues/vectors computation does not converge"
```

. 200 patterns found (out of a total of 200 sites). 

. 0 sites without polymorphism (0.00%).


. Computing pairwise distances...
. Eigenvalues/vectors computation does not converge : computation cancelled

. Type enter to exit.
```

**Comment by epruesse** [comment]
Could be some GCC optimization flags. Wish I had an ivy bridge Xeon at hand to test.

Do you have access to docker on the Ubuntu 16.04 machine?

**Comment by servalli** [comment]
I have erroneously reported that installation from bioconda worked on Ubuntu 18.04 machine, however, it turns out that I ran into the same problem before and was actually using a build from latest stable release (downloaded from @stephaneguindon repo).
Sorry for misconception

I have sudo rights on both machines, so I can install docker if necessary

**Comment by epruesse** [comment]
So it's not just the Bioconda binary, but the official binaries as well?

**Comment by servalli** [comment]
No, I meant the official binary is working correctly on 18.04

**Comment by epruesse** [comment]
Ok, so both Bioconda packages are not working, but the local build from git and the official binaries are working. Given the location, it sounds like the compiler flags don't like your Ivy Bridge CPU. Curious.

**Comment by stephaneguindon** [comment]
This last issue most probably has a different cause from the one you mentioned earlier. It generally has to do with very extreme data sets, e.g., conveying no phylogenetic signal whatsoever. I'm happy to look more into it if you send me the data.

**Comment by stephaneguindon** [comment]
Any chance a faulty Bioconda binary could be built with -g option and run through valgrind? That would give me a precise idea of where the problem come from.

**Comment by servalli** [comment]
I suppose that Bioconda binaries were not built in debug mode; if I run phyml from this installation with valgrind it no longer crashes but proceeds to BioNJ tree normally, so the bug might be pretty difficult to catch.

**Comment by stephaneguindon** [comment]
It is possible that the execution does not crash but generates warning messages through valgrind. If you have them handy, I'd like to look at them (not having the line numbers that generate the warnings is not such a big deal).

**Comment by servalli** [comment]
@stephaneguindon, for some reason I cannot view your previous answer here. This is definitely not the same issue, however, I cannot blame it entirely on my data quality as a tree is successfully produced by a locally built installation from the latest stable version on Ubuntu 18.04 machine while an installation built from github clone on 16.04 gives this error, the input alignment is the same. It is a small (~400 sequences, ~200 sites) alignment of some pretty distant proteins with gappy regions trimmed out. It does not look extreme to me:
[muscle_it2_COG0344_MK706.zip](https://github.com/bioconda/bioconda-recipes/files/3112271/muscle_it2_COG0344_MK706.zip)

**Comment by servalli** [comment]
All that is printed on the step when it normally crash if executed without valgrind are these two REDIR messages:
```

. 200 patterns found (out of a total of 200 sites). 

. 0 sites without polymorphism (0.00%).
--29836-- REDIR: 0x5295870 (libc.so.6:__memset_sse2_unaligned) redirected to 0x4c365d0 (memset)


. Computing pairwise distances...--29836-- REDIR: 0x535f510 (libc.so.6:__strncmp_sse42) redirected to 0x4c33570 (__strncmp_sse42)


. Building BioNJ tree...

. WARNING: this analysis will use at least 228 MB of memory space...

. Score of initial tree: -135168.98
```

**Comment by stephaneguindon** [comment]
@servalli I've just pushed a fix to the "Eigen value computation" issue. The analysis now should run fine on 16.04 and 18.04 (I suspect that the github clone version would not complete on 18.04 either...). 
Still investigating the other issue...

**Comment by stephaneguindon** [comment]
I've tried the latest stable release and the cloned version on 16.04, with and without valgrind. Both of them seem to work fine (didn't get any message from valgrind...). I'm not sure whether the Ivy Bridge CPU should be incriminated since a local build from git gives a binary that runs well on this CPU. Is Bioconda  doing something unconventional compilation-wise?

**Comment by epruesse** [comment]
Yes and no. Bioconda and Conda-Forge use the compilers and flags that Anaconda provides. Pragmatically, installing `gcc_linux-64` or `gxx_linux-64` gives you the same compiler like so:

```shell
$ conda create -n phyml_build gcc_linux-64 gxx_linux-64
[...]
$ conda activate phyml_build
$ echo $CC
...build/bin/x86_64-conda_cos6-linux-gnu-cc
$ echo $CFLAGS
-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
$ echo $LD
...build/bin/x86_64-conda_cos6-linux-gnu-ld
$ echo $LDFLAGS
-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags
```

That's a bunch of options, but nothing really unusual as distros go. It looks very similar to what Debian/Redhat like to use. Bit of safety, bit of trying to keep binaries smaller, a compromise in target CPU. 

One thing is unusual -  Conda brings it's own "sysroot", containing ld.so, libc, libm, etc:
```
(phyml_build) $ ls $CONDA_PREFIX/x86*/sysroot/lib
```

Those aren't used at runtime, but are used at compile time AFAIK. Probably so that you don't build stuff that suddenly needs a brand new libc and won't work elsewhere, but don't have to keep an ancient Linux around.

**Comment by epruesse** [comment]
Ouch. I think I'm not building with `--disable-native`.

**Comment by epruesse** [comment]
Reading your `configure.ac`, I probably need to override CFLAGS completely. Most `autotools` built things just add to `CFLAGS` and friends, so the things that are set in the environment are picked up automatically. Guess I should have read it rather than assume stuff...

**Comment by epruesse** [comment]
See https://github.com/bioconda/bioconda-recipes/pull/14675

**Comment by epruesse** [comment]
@servalli We have a new build that hopefully fixes the problem.

**Comment by servalli** [comment]
The new build no longer crashes. Thank you for the quick response!

**Comment by epruesse** [comment]
Thank you for your help @servalli! This bug had been in Bioconda for quite a while. We need people like you to create tickets when stuff like this happens and stick around helping to debug and eventually confirm that it's working!
