### ISSUE TITLE
Can't push to branch to request pr

### ISSUE THREAD

**Issue by astrovsky01** [bioconda/bioconda-recipes#14653]
I'm trying to add in a tool file via a fork I made, but I'm getting the error:

remote: Permission to bioconda/bioconda-recipes.git denied to astrovsky01.
fatal: unable to access 'https://github.com/bioconda/bioconda-recipes.git/': The requested URL returned error: 403

**Comment by epruesse** [comment]
This looks like you are trying to  `push` directly to `bioconda/bioconda-recipes`, not your fork, and probably to the master branch. You need to push to your own fork. Perhaps just doing `git push origin` works. It depends how you named your remotes.

Look around for tutorials on the whole fork/PR process on Github. Once you are set up, it's trivial. But the first bit is tough. Here is one of the many tutorials:

https://gist.github.com/Chaser324/ce0505fbed06b947d962

If you run across something better, please post here.

Also - for this type of problem it's easier to ask on our gitter channel https://gitter.im/bioconda/Lobby

I'll close the issue now so I don't forget later. You can still comment and I will still get notified.
