### ISSUE TITLE
More recent NEST package on conda-forge

### ISSUE THREAD

**Issue by steffengraber** [bioconda/bioconda-recipes#14709]
For the bioconda package NEST https://github.com/bioconda/bioconda-recipes/tree/master/recipes/nest there is a more recent package on conda-forge https://github.com/conda-forge/nest-simulator-feedstock/.
The NEST developers have decided to focus on the development of the conda-forge package (https://github.com/nest/nest-simulator/issues/1077). 
Is there the possibility to delete the bioconda package or to register it accordingly? If so, which conditions must be met?

**Comment by bgruening** [comment]
Hi @steffengraber! Please just create a PR to remove the recipe.

Thanks!

**Comment by bgruening** [comment]
Fixed with https://github.com/bioconda/bioconda-recipes/pull/14750
