### ISSUE TITLE
Tensorflow reference error

### ISSUE THREAD

**Issue by astrovsky01** [bioconda/bioconda-recipes#14721]
When trying to import and use tensorflow for a package I'm working on, I'm getting the error

"ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /opt/conda/conda-bld/scvis_1556216719029/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)" 

I don't get this error on my machine, likely because, from what I can tell, glibc is a linux-specific package. Should I be adding it into my requirements? If not, what should I be doing?

**Comment by kyleabeauchamp** [comment]
This is a known issue, the tensorflow conda-forge package is built directly from the pip wheels, which do not support old versions of linux.  See the discussion in https://github.com/bioconda/bioconda-recipes/pull/14499; I believe the workaround might be use tensorflow installed from the "defaults" channel temporarily.

**Comment by astrovsky01** [comment]
I changed from tensorflow >=1.1 to just tensorflow, but it made no difference...

**Comment by astrovsky01** [comment]
That didn't seem to work either. How do I change to force the default tensorflow if not

requirements:
    run:
        - tensorflow
?

**Comment by dpryan79** [comment]
You'll have to add a skip-lint (https://github.com/bioconda/bioconda-recipes/pull/14499/files#diff-44fc88eb24d85efd0c798a9a40dd5300R53 ) and remove testing (just add the last 4 lines).

**Comment by astrovsky01** [comment]
@dpryan79 I tried added it and upped the tensorflow version to at least 1.12, but it still won't work for me... Thanks though.

**Comment by astrovsky01** [comment]
@dpryan79 the removal of the tests worked. Thank you! Now on to the next error!
