### ISSUE TITLE
Request to move RGT to different channel

### ISSUE THREAD

**Issue by npavlovikj** [bioconda/bioconda-recipes#14980]
@bioconda/core , I don't feel competent to decide on the request here, https://github.com/CostaLab/reg-gen/issues/92, so I would really appreciate if you can comment on it. I tried tagging you there, but it looks like I can not do that.

Many thanks in advance!

**Comment by dpryan79** [comment]
I've left a reply there, thanks. They're obviously welcome to copy anything from here they want, but we don't have a reason to remove the package from bioconda.

**Comment by npavlovikj** [comment]
Thanks for chipping in Devon! The license is GPL, so I thought that might be the case.
