### ISSUE TITLE
Packages needing update for new bamtools pinnings

### ISSUE THREAD

**Issue by dpryan79** [bioconda/bioconda-recipes#15013]
- [x] recipes/scalpel
- [x] recipes/ngs-disambiguate
- [x] recipes/transrate-tools
- [x] recipes/vphaser2
- [x] recipes/dropest
- [x] recipes/telseq
- [x] recipes/squid
- [x] recipes/augustus
- [x] recipes/bioconvert
- [x] recipes/sniffles
- [x] recipes/cage
- [x] recipes/piranha
- [x] recipes/comparative-annotation-toolkit
- [x] recipes/sga

**Comment by dpryan79** [comment]
Xref https://github.com/bioconda/bioconda-recipes/pull/15014

**Comment by dpryan79** [comment]
Xref: https://github.com/bioconda/bioconda-recipes/pull/15030

**Comment by npavlovikj** [comment]
SGA in #15053

**Comment by dpryan79** [comment]
Xref: https://github.com/bioconda/bioconda-recipes/pull/15054

**Comment by dpryan79** [comment]
Only sga is left. @npavlovikj hopefully you have better luck with that package than me :)

**Comment by npavlovikj** [comment]
With @epruesse 's assistance, SGA is updated as well \o/

**Comment by dpryan79** [comment]
Great job!
