### ISSUE TITLE
GATK4 Spark?

### ISSUE THREAD

**Issue by apeltzer** [bioconda/bioconda-recipes#15059]
The recipe currently states:

```
# Does not yet install spark jar to save space.
# cp gatk-*-spark.jar $PACKAGE_HOME
```

According to the [docs](https://gatkforums.broadinstitute.org/gatk/discussion/11245/spark) it should be fairly straightforward and in general possible to use the SPARK capabilities for GATK4. 

Before I update the recipe, I just wanted to ask whether this is against some guidelines or similar. @bioconda/core

**Comment by dpryan79** [comment]
How big is the spark .jar file? There's really nothing speaking against that unless it's quite large.

**Comment by apeltzer** [comment]
```
 19 KB  Tue Apr 23 13:31:14 2019  gatk
828.5 KB  Tue Apr 23 13:31:14 2019  gatk-completion.sh
269.7 MB  Tue Apr 23 13:31:12 2019  gatk-package-4.1.2.0-local.jar
130.9 MB  Tue Apr 23 13:31:14 2019  gatk-package-4.1.2.0-spark.jar
964 B   Tue Apr 23 13:31:14 2019  gatkcondaenv.yml
3.5 KB  Tue Apr 23 13:31:14 2019  GATKConfig.EXAMPLE.properties
-   Tue Apr 23 13:31:14 2019  gatkdoc
112 KB  Tue Apr 23 13:31:14 2019  gatkPythonPackageArchive.zip
36.9 KB  Tue Apr 23 13:31:14 2019  README.md
-   Tue Apr 23 13:31:16 2019  scripts
```

So we're talking about 267MB for the local and another 130MB for the SPARK version. I thought about also making another recipe gatk4-spark, but since some tools are only available in SPARK and some tools only in the local version, that most likely doesn't make sense. 

I can add it then ...?

**Comment by dpryan79** [comment]
I would say yes, but let's wait and see if others have an opinion on that.

**Comment by epruesse** [comment]
Use `outputs` to create a second package?

**Comment by epruesse** [comment]
Oh, the jars overlap? Meeeh.

**Comment by apeltzer** [comment]
Unfortunately, yes. Some tools are SPARK, some are not but if you want to build a pipeline connecting these, you might require tools from both jars :-/

**Comment by epruesse** [comment]
I don't quite understand the details on GATK, but you could have 

```
outputs:
   - name: gatk
   ...
   - name: gatk-spark
```
with gatk-spark depending on gatk. Have a look at the `arb-bio` package for one example. There are more at conda-forge.

Most distros separate the "source package" from the "binary packages". The `outputs` thing allows the same for conda. So you have one upstream release you download, and then multiple packages that each contain part of the files.

I'm using it for `arb` to have a X11 and a non-X11 part.

**Comment by epruesse** [comment]
I.e., one recipe building multiple packages.

**Comment by epruesse** [comment]
Useful to limit the number of dependencies, or to keep install size down. Typical is to separate the `runtime library` part from the `developer` part, from the documentation, from the tools. So a classic for redhat or debian would be `XYZ-tools`, `XYZ-doc`, `libXYZ`, `libXYZ-dev` (redhat uses `-devel`).

**Comment by apeltzer** [comment]
I mean I'm good if that approach works - didn't have to add that to any package so far but if that is in general possible/feasible, why not 👍

**Comment by epruesse** [comment]
Ping me on the PR if you need help. There may be issues. Don't know. We don't have that many `outputs` packages yet. It sounds like the best fix though. And easier in the long run than two recipes.

**Comment by epruesse** [comment]
You can pin the sparks package to have to be exactly the same version as the non-parks package. Look at the arb-bio recipe. I think I'm doing that there.

The docs on this aren't very good. It might be a bit tedious to get to work.

You'll get a recipe page like this: https://bioconda.github.io/recipes/arb-bio/README.html So the two packages will both be listed under the recipe name.

**Comment by apeltzer** [comment]
See PR #15112
