### ISSUE TITLE
ucsc utility bundling

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#151]
Starting a new issue to follow up on #139:

All UCSC utilities together take up about 600MB. So we're building an individual recipe for each tool to keep the footprint small.  It would be nice to bundle them into metapackages for easier installation. How should they be bundled?

Here are some options. They aren't mutually exclusive.
### by file type

For example, `ls recipes | grep -i "bed"` to bundle anything that works with a BED file -- as long as that fact is indicated in the program name. Looking at the program names, we can have bundles for:
- axt
- fa
- bed
- wig
- hgLoad
- genePred
- axt
- chain
- lav
- maf
- psl
- twoBit
- gff3
### by general functional role
- utils for working with big* files, plus `fetchChromSizes`, and maybe hubCheck
- utils for liftover: liftOver, liftUp, chain*

Any other groupings?

**Comment by percyfal** [comment]
Ryan Dale <notifications@github.com> writes:

>
> Here are some options. They aren't mutually exclusive.

I'm not that familiar with conda metapackages, but is it possible to
assign a package to several metapackages, and is that what you're
suggesting?

>
> by file type
>
> For example, ls recipes | grep -i "bed" to bundle anything that works
> with a BED file -- as long as that fact is indicated in the program
> name. Looking at the program names, we can have bundles for:
>
>   * axt * fa * bed * wig * hgLoad * genePred * axt * chain * lav * maf
> * psl * twoBit * gff3
>
> by general functional role
>
>   * utils for working with big* files, plus fetchChromSizes, and maybe
> hubCheck * utils for liftover: liftOver, liftUp, chain*

These are the ones that come to mind and I think both are reasonable. 
I'll see if I can think of any other possibility.

/P

**Comment by daler** [comment]
Yep, as far as I can tell, metapackages are just dependency-only packages. Metapackages still have to be named uniquely though.

What sort of scheme? `ucsc-bundle-bed`?  `ucsc-bed-bundle`? `ucsc-meta-bed`?

**Comment by tomkinsc** [comment]
I like the idea of having metapackages in general, including various subsets of all bioconda recipes. It makes installation more simple (and we can recipes for all tools that deal with the same file type, *and* those functionally related, etc., as you suggest, @daler). It would be great to be able to tell someone "just install the metagenomics package from the bioconda channel", or "the bam-tools package has everything you need to get started, just install that."

**Comment by bgruening** [comment]
ping @daler

**Comment by daler** [comment]
Thanks for the reminder Bjoern :) 

In the intervening years, I'm not sure this is a good idea anymore. It seems like extra overhead to save a few lines in an env.yaml file.
