### ISSUE TITLE
cxx compiler issue when circleci test on macosx

### ISSUE THREAD

**Issue by samuelecancellieri** [bioconda/bioconda-recipes#15103]
Hi,

the recipe I try to merge, passes successfully the circle CI tests for lint and Linux, but fails when tests for macOS X.
As I can understand, the problem is that using the call, compiler('cxx') in the recipe, select two different compilers, depending on the system, so g++ on Linux and clang on mac, but my software need a specific g++ version to compile (g++ 5.4). It's possible to set a specific compiler and version, that will work also on macOS X?? 

Thank you.

Samuele

**Comment by PertuyF** [comment]
Please link to your PR, it will be more efficient.
You can have a look to the [recipe for `nanopolish`](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/nanopolish/meta.yaml) that has to force `gcc` for osx using selectors. However I am not sure if you can force any version.

**Comment by samuelecancellieri** [comment]
Hi,

thanks for the fast reply, my PR is #15060 
I need to use g++ 5.4 to compile all the correct libraries, I will try using the same call as in the recipe you link.
Thanks.

**Comment by samuelecancellieri** [comment]
Now fails also the linting phase, the bot is telling that i can't use the -gcc instructions anymore, recipe #15060

**Comment by dpryan79** [comment]
We don't build with gcc on OSX, only clang.

**Comment by samuelecancellieri** [comment]
> We don't build with gcc on OSX, only clang.

ok, so it's not possible to compile with gcc on OSX, there's a way to overcome this problem? 

thanks.

Samuele

**Comment by dpryan79** [comment]
No, we don't allow that as the resulting packages wouldn't always be compatible with each other.

**Comment by samuelecancellieri** [comment]
> No, we don't allow that as the resulting packages wouldn't always be compatible with each other.

Ok, so is not possible to label a package as incompatible with some compiler or OS.
I will try to fix this in my software so.

Thanks for the help.

Samuele
