### ISSUE TITLE
r-biom r351

### ISSUE THREAD

**Issue by alienzj** [bioconda/bioconda-recipes#15187]
@zachcp 
https://anaconda.org/bioconda/r-biom/files
Could you provide an r-biom r351 version?

**Comment by zachcp** [comment]
Hi @alienzj ,

I just took a look at the r-biom [repo](https://github.com/joey711/biom/) and it looks like it hasn't been updated in 4 years. Furthermore, it appears that it has been [removed from CRAN for inactivity](https://cran.r-project.org/web/packages/biom/).  Are you sure you want to use this package?  Can you get it to build locally in your workflow?

zach cp

**Comment by alienzj** [comment]
Hi @zachcp 
I try it.
Thanks very much!
