### ISSUE TITLE
conda skeleton List::Util

### ISSUE THREAD

**Issue by matthdsm** [bioconda/bioconda-recipes#1518]
Conda skeleton fails to create a recipe for CPAN package List::Util
Traceback:

<pre>
vagrant@vagrant-ubuntu-trusty-64:~/bioconda-recipes/recipes$ conda skeleton cpan List::Util --recursive 
WARNING: List::Util was part of the Scalar-List-Utils distribution, so we are making a recipe for Scalar-List-Utils instead.
Using url https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.45.tar.gz (86481) for Scalar-List-Utils.
Processing dependencies for Scalar-List-Utils.......An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/vagrant/miniconda2/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 298, in main
    args_func(args, p)
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda_build/main_build.py", line 493, in args_func
    args.func(args, p)
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 315, in execute
    cpan.main(args, parser)
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda_build/cpan.py", line 249, in main
    processed_packages)
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda_build/cpan.py", line 407, in deps_for_package
    dep_version, perl_version, dependency=True)
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda_build/cpan.py", line 508, in get_release_info
    rel_dict['version'] = rel_dict['version'].lstrip('v')
AttributeError: 'int' object has no attribute 'lstrip'
</pre>

Conda info:
<pre>
Current conda install:

             platform : linux-64
        conda version : 4.0.5
  conda-build version : 1.20.1
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/vagrant/miniconda2  (writable)
  default environment : /home/vagrant/miniconda2
     envs directories : /home/vagrant/miniconda2/envs
        package cache : /home/vagrant/miniconda2/pkgs
         channel URLs : https://conda.anaconda.org/bioconda/linux-64/
                        https://conda.anaconda.org/bioconda/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/vagrant/.condarc
    is foreign system : False

</pre>

**Comment by rvalieris** [comment]
> An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
> https://github.com/conda/conda-build/issues

I think this should be reported at the [conda repo](https://github.com/conda/conda-build/issues) not here.

Nonetheless, I just tested the command on my install, and did not reproduce the error.


```
WARNING: List::Util was part of the Scalar-List-Utils distribution, so we are making a recipe for Scalar-List-Utils instead.
Using url https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.45.tar.gz (86481) for Scalar-List-Utils.
Processing dependencies for Scalar-List-Utils.......done
Writing recipe for perl-scalar-list-utils-1.45
WARNING: Version 0.98 of Test-Simple is not available on MetaCPAN, but it's a core module, so we do not actually need the source file, and are omitting the URL and MD5 from the recipe entirely.
Writing recipe for perl-test-simple-0.98
Using url http://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-6.66.tar.gz (421570) for ExtUtils-MakeMaker.
Writing recipe for perl-extutils-makemaker-6.66
Done
```

               platform : linux-64
          conda version : 4.0.6
    conda-build version : 1.20.2
         python version : 3.5.1.final.0
       requests version : 2.9.1
