### ISSUE TITLE
Monocle 3 Recipe Please

### ISSUE THREAD

**Issue by MediciPrime** [bioconda/bioconda-recipes#15212]
Bioconda is awesome! However I have one tiny request.

I am currently using this [recipe](https://bioconda.github.io/recipes/bioconductor-monocle/README.html) for monocle v2.10.0 perform scRNA-seq trajectory analysis.  Its great however Monocle has come out with [version 3](http://cole-trapnell-lab.github.io/monocle-release/monocle3/).  I have tried so hard to install it on my University's cluster however I have been unsuccessful.  

Could someone in this wonderful community please create a conda recipe for Monocle 3?  I would be very grateful to you.

Thank you! :)

**Comment by PertuyF** [comment]
Good news is that [work is in progress](https://github.com/bioconda/bioconda-recipes/pull/15160) to get Bioconductor 3.9 packages to Bioconda, as Monocle 3.0 is part of this *very new* release of Bioconductor.

Bad news is that you'll have to be patient, due to how Bioconductor works, it is quite complicated to update Bioconda for such release (there's a lot of interdependent packages requiring rebuild at once).
@dpryan79 may be able to give more details on this.

**Comment by dpryan79** [comment]
The most recent released version of monocle is 2.12.0, which is from the most recent Bioconductor release and in the queue to be built (it depends on BiocGenerics, which allegedly requires R 3.6, for which nothing in conda has been built yet...). I expect monocle3 will actually be released in about 6 months, at which point it will be included in bioconda. In the interim you'll have to install the development/alpha versions as described on the monocle3 page.

**Comment by epruesse** [comment]
@MediciPrime - Thanks for the very kindly written issue! 

Please re-open if this is still an issue. Since monocle is part of the Bioconductor process, I assume we need no additional reminder. Wish the 3.6 requirement wasn't there...

**Comment by MediciPrime** [comment]
I think Monocle 3 is out!!  [LINK](https://cole-trapnell-lab.github.io/monocle3/)
I am really looking forward to it in the new version on Conda, please and thank you. :)

**Comment by dpryan79** [comment]
Guess you noticed it's still in beta :)

--
Devon Ryan, Ph.D.
Email: dpryan@dpryan.com
Data Manager/Bioinformatician
Max Planck Institute of Immunobiology and Epigenetics
Stübeweg 51
79108 Freiburg
Germany
<devon.ryan@dzne.de>

**Comment by MediciPrime** [comment]
Hahaha yup, they went from Alpha to Beta.  :)

**Comment by mjsteinbaugh** [comment]
To follow up, `r-monocle3` is now up on bioconda

**Comment by MediciPrime** [comment]
Wow!  In beta and you guys still managed it!  Nice job!  Thank you!
