### ISSUE TITLE
building from git that requires `git clone --recursive` flag 

### ISSUE THREAD

**Issue by snewhouse** [bioconda/bioconda-recipes#1524]
Hi All & @bioconda/all 

New to conda/bioconda and really glad to be part of the community. 

Quick question when putting together the `build.sh`, anyone know how to or has anyone specified/used the  `git clone --recursive` flag when wanting to build from a `git` repo?

Cheers

Steve

**Comment by bgruening** [comment]
Afaik the `git_url` approach clones the repo with `--recursice`.

http://conda.pydata.org/docs/building/meta-yaml.html#source-from-git

**Comment by johanneskoester** [comment]
Yes, that is also what I have experienced so far.

**Comment by snewhouse** [comment]
thanks all. not too clear in the docs...unless I missed  it. cheers again
