### ISSUE TITLE
autobump?

### ISSUE THREAD

**Issue by pmjklemm** [bioconda/bioconda-recipes#15317]
So i did  ` bioconda-utils autobump recipes/ config.yml --packages proteinortho`
but i dont know where to inspect the results as mentioned in https://bioconda.github.io/updating.html:
> will update the package’s recipe which you can then inspect.

And here is the output:

> 
> 16:45:45 BIOCONDA INFO Hosters loaded: ['FTPHoster', 'GithubRelease', 'GithubTag', 'GithubReleaseAttachment', 'GithubRepoStore', 'Bioconductor', 'CargoPort', 'SourceForge', 'PyPi', 'Bioarchive', 'CPAN', 'CRAN', 'BitBucketTag', 'BitBucketDownload', 'GitlabTag']
> 16:45:45 BIOCONDA WARNING Selected 1 packages
> 16:45:45 BIOCONDA INFO Building Recipe DAG
> 16:45:50 BIOCONDA INFO svtools has duplicate key                                 
> 16:45:55 BIOCONDA INFO amptk has duplicate key                                   
> 16:45:57 BIOCONDA INFO r-smartsva has duplicate key                              
> 16:45:57 BIOCONDA INFO nullarbor has duplicate key                               
> 16:46:02 BIOCONDA INFO spades/3.11.1 has duplicate key                           
> 16:46:05 BIOCONDA INFO sierrapy has duplicate key                                
> 16:46:06 BIOCONDA INFO homer has duplicate key                                   
> 16:46:08 BIOCONDA INFO s3gof3r has duplicate key                                 
> 16:46:16 BIOCONDA INFO igblast/1.4.0 has duplicate key                           
> 16:46:20 BIOCONDA INFO r-isva has duplicate key                                  
> 16:46:20 BIOCONDA ERROR Could not load recipe while parsing a block mapping      
>   in "<unicode string>", line 23, column 3:
>       build:
>       ^ (line: 23)
> expected <block end>, but found '-'
>   in "<unicode string>", line 44, column 3:
>       -     - gcc-libs         # [win]
>       ^ (line: 44)
> 16:46:22 BIOCONDA INFO sourcetracker has duplicate key                           
> 16:46:24 BIOCONDA INFO cufflinks has duplicate key                               
> 16:46:30 BIOCONDA INFO msms has duplicate key                                    
> 16:46:35 BIOCONDA INFO segemehl has duplicate key                                
> 16:46:35 BIOCONDA INFO segemehl/0.3.1 has duplicate key                          
> 16:46:35 BIOCONDA INFO segemehl/0.2.0 has duplicate key                          
> 16:46:39 BIOCONDA INFO scoary has duplicate key                                  
> 16:46:46 BIOCONDA INFO nim-falcon has duplicate key                              
> 16:46:47 BIOCONDA INFO platypus-conquistador has duplicate key                   
> 16:46:47 BIOCONDA INFO fcsparser has duplicate key                               
> 16:46:54 BIOCONDA INFO pubchempy has duplicate key                               
> Loading Recipes...: 100%|████████████████████| 6571/6571 [01:13<00:00, 89.60it/s]
> 16:46:59 BIOCONDA INFO Building Recipe DAG: done (4637 nodes, 16678 edges)
> 16:46:59 BIOCONDA WARNING Graph contains 14 packages (blacklist excluded)
> 16:46:59 BIOCONDA WARNING Excluding 450 blacklisted recipes
> 16:46:59 BIOCONDA INFO Loading package lists for ['conda-forge']
> Downloading: 100%|██████████████████████████████| 9/9 [00:05<00:00,  1.09files/s]
> 16:47:06 BIOCONDA INFO Running pipeline with these steps:
> 16:47:06 BIOCONDA INFO  1. Exclude blacklisted recipes: build-fail-blacklist / 450 recipesnoarch: 2.81MB [00:00, 6.31MB/s]
> 16:47:06 BIOCONDA INFO  2. Exclude sub-recipes
> 16:47:06 BIOCONDA INFO  3. Exclude recipes depending on packages in need of updateioconda/linux: 5.39MB [00:00, 28.8MB/s]
> 16:47:06 BIOCONDA INFO  4. Load the recipe from the filesystem
> 16:47:06 BIOCONDA INFO  5. Exclude recipes in conda-forge
> 16:47:06 BIOCONDA INFO  6. Bump recipes in need of rebuild after pinning changes
> 16:47:06 BIOCONDA INFO  7. Scan upstream for new releases and update recipe
> 16:47:06 BIOCONDA INFO  8. Fetch additional upstream dependencies (PyPi)
> 16:47:06 BIOCONDA INFO  9. Update source checksums
> 16:47:06 BIOCONDA INFO  10. Write recipe to filesystem
> 16:48:02 BIOCONDA INFO Package diamond=0.9.24=hbde9309_1 missing!                
> 16:48:38 BIOCONDA INFO diamond needs rebuild. Bumping buildnumber to 2           
> 16:48:39 BIOCONDA INFO proteinortho deferred pending rebuild of dependencies: diamond
> 100%|████████████████████████████████████████████| 14/14 [01:32<00:00,  6.64s/it]
> 16:48:39 BIOCONDA INFO Unrecognized URL stats:
> 16:48:39 BIOCONDA INFO 
> 16:48:39 BIOCONDA INFO Recipe status statistics:
> 16:48:39 BIOCONDA INFO IsSubRecipe: 12
> 16:48:39 BIOCONDA INFO Updated: 1
> 16:48:39 BIOCONDA INFO DependencyPending: 1
> 16:48:39 BIOCONDA INFO SUM: 14

And nothing seems to happen afterwards ? (I thought a merge request will be created)
Or what should i do now to update my recipe

**Comment by epruesse** [comment]
Hi @pmjklemm - it should have modified the recipe locally in your branch. `autobump` works like a pipeline and has a bunch of things you can turn off and on. To have it create a PR for you, you need to activate that module using `--create-pr`. You will need to have a GITHUB_TOKEN set, so that it can authenticate with github. Or you can just use the modified recipe as normal.

**Comment by epruesse** [comment]
Sorry about the lack of current docs. PRs very very appreciated!

**Comment by epruesse** [comment]
```
16:48:02 BIOCONDA INFO Package diamond=0.9.24=hbde9309_1 missing!
16:48:38 BIOCONDA INFO diamond needs rebuild. Bumping buildnumber to 2
```
That was from the pinning check. If you disable that with `--no-check-pinnings`, the whole thing runs much faster. Conda API is horribly slow. 99% time goes down here.

```
16:48:39 BIOCONDA INFO proteinortho deferred pending rebuild of dependencies: diamond
```
That's the part that waits until all dependencies are up to date before checking a specific package. Diamons needs a rebuild, so proteinortho doesn't get checked at the moment.

You can override that with `--no-check-pending-deps`. 

So:

```
bioconda-utils autobump recipes/ config.yml --max-updates 50  --create-pr  --packages proteinortho --no-check-pending-deps --no-check-pinnings
22:56:46 BIOCONDA INFO Hosters loaded: ['FTPHoster', 'GithubRelease', 'GithubTag', 'GithubReleaseAttachment', 'GithubRepoStore', 'Bioconductor', 'CargoPort', 'SourceForge', 'PyPi', 'Bioarchive', 'CPAN', 'CRAN', 'BitBucketTag', 'BitBucketDownload', 'GitlabTag']
22:56:46 BIOCONDA WARNING Selected 1 packages
22:56:46 BIOCONDA INFO Building Recipe DAG
22:56:47 BIOCONDA INFO msms has duplicate key                                                          
22:56:48 BIOCONDA INFO r-isva has duplicate key                                                        
22:56:48 BIOCONDA INFO preseq has duplicate key                                                        
22:56:48 BIOCONDA INFO s3gof3r has duplicate key                                                       
22:56:49 BIOCONDA INFO amptk has duplicate key                                                         
22:56:49 BIOCONDA INFO homer has duplicate key                                                         
22:56:51 BIOCONDA INFO fcsparser has duplicate key                                                     
22:56:52 BIOCONDA INFO platypus-conquistador has duplicate key                                         
22:56:53 BIOCONDA INFO pubchempy has duplicate key                                                     
22:56:55 BIOCONDA INFO sierrapy has duplicate key                                                      
22:56:58 BIOCONDA INFO segemehl has duplicate key                                                      
22:56:58 BIOCONDA INFO segemehl/0.3.1 has duplicate key                                                
22:56:58 BIOCONDA INFO segemehl/0.2.0 has duplicate key                                                
22:57:00 BIOCONDA INFO svtools has duplicate key                                                       
22:57:02 BIOCONDA INFO igblast/1.4.0 has duplicate key                                                 
22:57:03 BIOCONDA INFO nim-falcon has duplicate key                                                    
22:57:04 BIOCONDA INFO scoary has duplicate key                                                        
22:57:04 BIOCONDA INFO sourcetracker has duplicate key                                                 
22:57:05 BIOCONDA INFO r-smartsva has duplicate key                                                    
22:57:05 BIOCONDA INFO bioconductor-rrdpdata has duplicate key                                         
22:57:05 BIOCONDA INFO spades/3.11.1 has duplicate key                                                 
22:57:06 BIOCONDA INFO cufflinks has duplicate key                                                     
Loading Recipes...: 100%|█████████████████████████████████████████| 6571/6571 [00:21<00:00, 305.68it/s]
22:57:08 BIOCONDA INFO Building Recipe DAG: done (4643 nodes, 16727 edges)
22:57:08 BIOCONDA WARNING Graph contains 14 packages (blacklist excluded)
22:57:08 BIOCONDA WARNING Excluding 450 blacklisted recipes
22:57:08 BIOCONDA WARNING Checking out master
22:57:09 BIOCONDA INFO Updating master to latest project master
22:57:09 BIOCONDA INFO Updating and pruning remotes
22:57:10 BIOCONDA INFO Loading package lists for ['conda-forge']
Downloading: 100%|████████████████████████████████████████████████████| 9/9 [00:05<00:00,  1.13files/s]
22:57:16 BIOCONDA WARNING Will exit after 50 updated recipes
22:57:16 BIOCONDA INFO Running pipeline with these steps:
22:57:16 BIOCONDA INFO  1. Exclude recipes disabled via config
22:57:16 BIOCONDA INFO  2. Exclude blacklisted recipes: build-fail-blacklist / 450 recipes
22:57:16 BIOCONDA INFO  3. Exclude sub-recipes
22:57:16 BIOCONDA INFO  4. Load recipe from git (honoring active branches)
22:57:16 BIOCONDA INFO  5. Exclude recipes in conda-forge
22:57:16 BIOCONDA INFO  6. Scan upstream for new releases and update recipe
22:57:16 BIOCONDA INFO  7. Update source checksums
22:57:16 BIOCONDA INFO  8. Write recipe to per-recipe git branch
22:57:16 BIOCONDA INFO  9. Create or Update PR on GitHub
22:57:16 BIOCONDA INFO  10. Terminate pipeline after 50 recipes have been updated.
22:57:18 BIOCONDA INFO diamond had no changes                                                          
22:57:19 BIOCONDA INFO Updating checksum for proteinortho 6.0.1                                        
22:57:21 BIOCONDA INFO Creating new branch bump/proteinortho                                           
22:57:22 BIOCONDA INFO Checking out branch bump/proteinortho                                           
22:57:23 BIOCONDA INFO Pushing branch bump/proteinortho                                                
22:57:36 BIOCONDA INFO Creating PR 'Update proteinortho to 6.0.1'                                      
22:57:37 BIOCONDA INFO Modifying PR 15323                                                              
22:57:38 BIOCONDA INFO Created PR 15323: Update proteinortho to 6.0.1                                  
100%|██████████████████████████████████████████████████████████████████| 14/14 [00:20<00:00,  5.87s/it]
22:57:38 BIOCONDA INFO Unrecognized URL stats:
22:57:38 BIOCONDA INFO 
22:57:38 BIOCONDA INFO Recipe status statistics:
22:57:38 BIOCONDA INFO IsSubRecipe: 12
22:57:38 BIOCONDA INFO NoChanges: 1
22:57:38 BIOCONDA INFO Updated: 1
22:57:38 BIOCONDA INFO SUM: 14
22:57:38 BIOCONDA WARNING Switching back to master
```

There you go. #15323

**Comment by pmjklemm** [comment]
Ahh ok i think i get it now. Thank you so much, now i will do the rest.

**Comment by tlkaufmann** [comment]
If anyone like me stumbles on this page, the documentation has moved to https://bioconda.github.io/contributor/updating.html
