### ISSUE TITLE
bioconductor-monocle 

### ISSUE THREAD

**Issue by hmkim** [bioconda/bioconda-recipes#15416]
$ conda install -c bioconda bioconductor-monocle

Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - bioconductor-monocle -> r-ddrtree[version='>=0.1.4']
  - bioconductor-monocle -> r-densityclust[version='>=0.3']
  - bioconductor-monocle -> r-vgam[version='>=1.0-6']

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by npavlovikj** [comment]
Looks like you are missing `conda-forge`, please try the following: `conda install -c conda-forge -c bioconda -c defaults bioconductor-monocle`

**Comment by hmkim** [comment]
Thanks @npavlovikj 
I'll solved it via your comment.
