### ISSUE TITLE
PASA no executable files

### ISSUE THREAD

**Issue by HTaekOppa** [bioconda/bioconda-recipes#15439]
Hi @johanneskoester and @nathanweeks,

We installed PASA with `conda create -n pasa pasa` and activated it with `conda activate pasa` but we could not find any executable files. Could you please provide any examples/scripts how to run PASA?

Cheers,

Taek

**Comment by nathanweeks** [comment]
`conda activate pasa` sets the PASAHOME environment variable, which is used in the official PASA documentation: https://github.com/PASApipeline/PASApipeline/wiki/PASA_alignment_assembly

The conda package doesn't include the sample_data (and the run_sample_pipeline.pl script in the sample_data hard-codes some paths and can't be used directly), but you can test pasa thus:

```
$ curl -L https://github.com/PASApipeline/PASApipeline/releases/download/pasa-v2.3.3/PASApipeline-v2.3.3.tar.gz | tar -xzf -
$ cd PASApipeline-v2.3.3/sample_data/
$ gunzip genome_sample.fasta.gz
$ sed -e "s#<__DATABASE__>#$PWD/database.sqlite#" -e 's/^validate/#validate/' $PASAHOME/pasa_conf/pasa.alignAssembly.Template.txt > alignAssembly.config
$ $PASAHOME/Launch_PASA_pipeline.pl \
           -c alignAssembly.config -C -R -g genome_sample.fasta \
           -t all_transcripts.fasta.clean -T -u all_transcripts.fasta \
           -f FL_accs.txt --ALIGNERS blat,gmap --CPU 2
```
