### ISSUE TITLE
blast+ version is getting old

### ISSUE THREAD

**Issue by nick-youngblut** [bioconda/bioconda-recipes#15564]
It appears that the most recent version of blast+ on bioconda is v2.7.1, which was released back in Oct of 2017. The newest version is 2.9.0 (released in April 2019). Is there a particular reason why blast+ hasn't been updated in a long time (eg., dependency issues)? I could try creating a new blast+ recipe with the newest version, but I don't want to waste time if there's some reason why it shouldn't be updated (yet).

**Comment by npavlovikj** [comment]
Please see https://github.com/bioconda/bioconda-recipes/pull/15550. The team has been working on it, but unfortunately, it is not an easy package to build from source...

**Comment by dpryan79** [comment]
I just merged in version 2.9.0
