### ISSUE TITLE
braker: Input file not in genbank format.

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#15574]
Hi @npavlovikj ,
Have you ever got this error:

```
/work/waterhouse_team/miniconda2/envs/braker2/bin//etraining: ERROR
        Input file not in genbank format.
```

Thank you in advance,

Michal

**Comment by npavlovikj** [comment]
Hi @mictadlo ,

This sounds like specific issue with the input data used with `braker` and `etraining` which is not related with the conda recipe itself.
I saw you have asked the same quesion in the BRAKER repo, https://github.com/Gaius-Augustus/BRAKER/issues/34, which is the proper place for this type of question, so I would suggest you to try the given suggestions there.

**Comment by mictadlo** [comment]
Ok, thank you.
