### ISSUE TITLE
Container for fastqsplitter not accessible: Not authorized

### ISSUE THREAD

**Issue by rhpvorderman** [bioconda/bioconda-recipes#15602]
http://bioconda.github.io/recipes/fastqsplitter/README.html

The biocontainer is not authorized.

@bioconda/core . Can this be authorized? Any progress on this issue of containers being created in a private repo by default? It seems to happen a lot lately.

**Comment by dpryan79** [comment]
@bgruening Can you have a look at this?

**Comment by bgruening** [comment]
Done!

**Comment by rhpvorderman** [comment]
Thanks @bgruening and @dpryan79 !
