### ISSUE TITLE
r-probmetab getting stuck on "Solving environment:"

### ISSUE THREAD

**Issue by Tomnl** [bioconda/bioconda-recipes#15639]
Hi all,

When trying to install r-probmetab via linux using the following command

```
conda install -c bioconda r-probmetab
```

The install gets stuck on  "Solving environment:"

However if I specify the build it seems to install with no problem

```
conda install -c bioconda r-probmetab=1.1=r341hf484d3e_3
```

Does anybody have any ideas on how to fix this?

FYI:
@RJMW

**Comment by PertuyF** [comment]
There is currently a performance issue with conda solving an environment. This is due to the large number of packages, versions and builds available in channels `defaults`, `bioconda` and `conda-forge`, which offer a huge number of combinations to solve dependencies constraints.

You can have a look to Bioconda's recommendations regarding solving slowdown in issue https://github.com/bioconda/bioconda-recipes/issues/13774.

For instance, in your case using metachannels lowers solving significantly with the following command:
```shell
conda create -n test --override-channels --no-pin -c https://metachannel.conda-forge.org/defaults,bioconda,conda-forge/r-probmetab,--max-build-no r-probmetab
```

**But** when looking closer, it appears that `r-probmetab` is built against `r-base` version `3.4.1` which is pretty old and most certainly makes things harder...
Looking to rebuild without pinnings is this PR https://github.com/bioconda/bioconda-recipes/pull/15647

**Comment by Tomnl** [comment]
thanks @PertuyF,

I think using the `https://metachannel.conda-forge.org/defaults,bioconda,conda-forge/r-probmetab` option might be problematic when using Galaxy. @RJMW  what do you think?

**Comment by RJMW** [comment]
@Tomnl Yes, this might be problematic for galaxy.

@bgruening any idea how to address this in Galaxy?
@Gildas did you experience any issues with r-probmetab as part of W4M?

**Comment by Tomnl** [comment]
After doing some testing locally with conda using Planemo and the Galaxy wrapper https://github.com/workflow4metabolomics/probmetab

Everything seems to pass (at least locally on my system) if we update the requirements to specify a compatible build for r-probmetab

        <requirements>
            <requirement type="package" version="0.4_1">r-snow</requirement>
            <requirement type="package" version="1.0=r3.3.2_0">r-probmetab</requirement>
            <requirement type="package" version="1.1_4">r-batch</requirement>
        </requirements>


I noticed @lecorguille was updating the dependencies a few weeks ago in a separate branch and it was failing on [travis ](https://travis-ci.org/workflow4metabolomics/probmetab/builds/533938891?utm_source=github_status&utm_medium=notification). So would be good to get his thoughts on this.

**Comment by bgruening** [comment]
It seems RCytoscape was dropped from BioConductor? This is why we do not have recent builds of r-probmetab as it seems.

Try adding an explicit dependency to r-base=3.4.1

**Comment by Tomnl** [comment]
Thanks @bgruening,

Seems OK now if I run the following 

`conda create -n test3052019  -c bioconda r-base=3.4.1 r-probmetab=1.1`

Also, I did try to update the recipe to explicitly only use [ r-base=3.4.1 ](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/r-probmetab/meta.yaml#L22).  

And for the Galaxy wrapper - added r-base 3.3.2 due to other dependencies versions requiring an older R version.

```
   <requirements>
        <requirement type="package" version="3.3.2">r-base</requirement>
        <requirement type="package" version="0.4_1">r-snow</requirement>
        <requirement type="package" version="1.0">r-probmetab</requirement>
        <requirement type="package" version="1.1_4">r-batch</requirement>
    </requirements>
```


Regarding the Galaxy wrapper - is there any problem with specifying the builds? To me it seems it is more reproducible to do so, but I am probably missing some important consideration.

**Comment by bgruening** [comment]
@Tomnl this is ok. Looks good to me. 
For more information see here: https://github.com/bioconda/bioconda-recipes/issues/13774
