### ISSUE TITLE
Building Trinity on OSX

### ISSUE THREAD

**Issue by dpryan79** [bioconda/bioconda-recipes#15631]
Xref: https://github.com/bioconda/bioconda-recipes/pull/15577

I've tried to get this to work but it's always failed when running `install_name_tool`. Disabling that just causes the binaries to crash, so it's failing for a very good reason. If someone ever figures out the cause of the following error, please let me know:

    16:09:06 BIOCONDA INFO (ERR) /Applications/Xcode-8.3.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: the __LINKEDIT segment does not cover the end of the file (can't be processed) in: /Users/distiller/project/miniconda/conda-bld/trinity_1558911838992/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/opt/trinity-2.8.5/Chrysalis/build/CreateIwormFastaBundle

ping @epruesse

**Comment by dpryan79** [comment]
Closing in the hope that https://github.com/bioconda/bioconda-recipes/pull/18695 will eventually work.

**Comment by mencian** [comment]
Closing in favor of #57053, `Trinity` is now available on `osx64` and `arm64`.
