### ISSUE TITLE
License description consistency

### ISSUE THREAD

**Issue by hardingnj** [bioconda/bioconda-recipes#1581]
Currently the licence descriptions are a bit all over the place. Is it work spending some effort bringing them into line? I'm not sure whether down the line we may want to filter by license type etc?

Happy to do the work if people think it's worthwhile

`grep -r "license:" . | perl -lne '$_ =~ m/license: (.+)$/; print $1;' | sort | uniq -c`

> ```
>  10 ''
>   4 academic
>   1 Academic and Research License
>   1 Academic Free License 3.0
>   2 Academic Free License (AFL)
>   1 Academic Free License version 3.0
>   1 Academic use, commerically restricted (http://www.stats.ox.ac.uk/~marchini/software/gwas/gwas.html#licence)
>   3 Affero GPL
>   2 AGPL
>   2 AGPL-3
>   1 AGPL + file LICENSE
>   1 AGPLv3
>   1 "Apache 2"
>   2 apache_2_0
>  11 Apache 2.0
>  12 Apache License 2.0
>   1 Apache License V2.0
>   4 Apache License, Version 2.0
>   9 Apache Software License
>   3 Apache v2
>   1 "Apache v2.0"
>   2 Apache v2.0
>   1 Artistic
>   1 "Artistic"
>   1 artistic_2
>  64 Artistic-2.0
>   1 'Artistic-2.0 | file LICENSE'
>   2 'Artistic-2.0 + file LICENSE'
>   1 'Artistic-2.0 | GPL-2 + file LICENSE'
>   3 Artistic License
>  10 Artistic License 2.0
>   1 Biopython License Agreement
>   2 Boost Software License
>  36 BSD
>   1 BSD_2_clause + file LICENSE
>   1 BSD 3-clause
>   1 BSD-3-clause
>   1 BSD-3-Clause
>   1 BSD_3_clause + file LICENCE
>   4 BSD_3_clause + file LICENSE
>  52 BSD License
>   1 BSD New
>   1 CC BY-NC 2.0
>   1 CC BY-SA 3.0
>   1 CCPL (Creative Commons Public License)
>   2 CeCILL
>   1 CeCILL FSLA
>   1 Commercial (requires license for multithreaded use)
>   1 Copyright © 2009-2014,2015 by Thomas E. Dickey
>   1 'Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported'
>   7 Custom
>   2 Custom OSS
>   1 "dual-licensed under GPLv3+ or BSD 2-clause"
>   1 ECL 2.0
>   1 Eclipse Public License v1.0
>   2 EPL
>   1 'file LICENSE'
>   1 FreeBSD 2-clause license
>   1 Free for academic, nonprofit and personal use
>   1 Free for academic use.
>   1 Free software license (https://github.com/lh3/bioawk/blob/master/README.awk#L1)
>   3 GNU
>   1 GNU General Public License
>   3  GNU General Public License (GPL)
>   6 GNU General Public License (GPL)
>   2 GNU General Public License v2 (GPLv2)
>   3 GNU General Public License v2 or later (GPLv2+)
>   1 GNU General Public License v3
>  12 GNU General Public License v3 (GPLv3)
>   3 GNU General Public License v3 or later (GPLv3+)
>   1 GNU General Public License version 2.0
>   1 GNU General Public License version 2.0 (GPLv2)
>   1 GNU General Public License version 3.0
>   1 GNU Lesser General Public License v2 or later (LGPLv2+) or GNU General Public License v2 or later (GPLv2+)
>   1 GNU Lesser General Public License v3 (LGPLv3)
>   1 GNU Lesser General Public License v3 or later (LGPLv3+)
>   7 GNU Library or Lesser General Public License (LGPL)
>   2 Gnuplot License + others
>  47 GPL
>   1 "GPL"
>   3 GPL2
>   8 'GPL (>= 2)'
>   4 'GPL (>=2)'
>  34 GPL (>= 2)
>  33 GPL-2
>   2 'GPL (>=2.0)'
>   1 'GPL 2.0+'
>   2 GPL (>= 2.0)
>   2 'GPL (>= 2) + file LICENSE'
>   1 'GPL-2 | GPL-3'
>   2 GPL-2|GPL-3
>   7 GPL-2 | GPL-3
>  19 GPL3
>   3 'GPL (>= 3)'
>   1 GPL 3
>  10 GPL (>= 3)
>   7 GPL-3
>   1 'GPL (>=3.0)'
>   1 GPL-3 | file LICENSE
>  14 GPLv2
>   1 'GPL v2'
>   1 "GPL v2"
>   1 "GPLv2"
>   1 "GPLv2+"
>   3 GPL v2
>   1 GPLv2 and others
>  62 GPLv3
>   3 "GPLv3"
>   1 "GPLv3+"
>   2 GPL v3
>   1 GPLv3+
>   1 GPLv3 | BIOPYTHON
>   1 https://github.com/mikessh/migmap/blob/master/LICENSE
>   2 "https://raw.githubusercontent.com/atgreen/libffi/master/LICENSE"
>   1 https://raw.githubusercontent.com/dropbox/dropbox-sdk-python/master/LICENSE
>   1 "https://raw.githubusercontent.com/file/file/master/COPYING"
>   1 "https://raw.githubusercontent.com/marbl/Mash/master/LICENSE.txt"
>   1 https://raw.githubusercontent.com/seqan/seqan/develop/apps/yara/LICENSE
>   2 "https://raw.githubusercontent.com/trinityrnaseq/trinityrnaseq/master/LICENSE.txt"
>   1 'https://www.broadinstitute.org/node/4238'
>   1 'https://www.broadinstitute.org/node/4962'
>   1 "http://www.drive5.com/muscle/manual/license.html"
>   1 http://www.gnu.org/licenses/gpl-2.0.html
>  14 LGPL
>   1 LGPL2
>   5 'LGPL (>= 2)'
>   1 LGPL (>= 2)
>   1 LGPL-2
>   2 'LGPL (>= 2.0)'
>   7 LGPL (>= 2.1)
>   1 LGPL-2.1
>   3 'LGPL (>= 3)'
>   4 LGPL-3
>   1 LGPLv2
>   3 LGPLv3
>   1 "LGPLv3"
>   2 LICENSE.txt
>   1 mit
> 110 MIT
>   1 MIT (code), CC-BY-3.0 (docs)
>   1 MIT/Expat
>  11 MIT + file LICENSE
>   1 MIT license
>   1  MIT License
>  47 MIT License
>   1 MIT License or Academic Free License (AFL)
>   6 MIT-like
>   1 Modified MIT (no inclusion in commercial tools)
>   2 MPL2
>   1 Non-commercial
>   1 Open Software License v2.1
>   1 open_source
>   1 OSL-2.1
>  26 Perl
>  42 perl_5
>   1 PSF license
>   2 Public domain
>  11 Public Domain
>   1 PUBLIC DOMAIN
>   2 Python Software Foundation License
>   1 Several OSS
>   2 Simplified BSD Licence 
>   1 Simplified BSD License
>   1 "The Artistic License"
>   1 The Broad Institute (own license thingy)
>   2 "The license for this meta-package is MIT; individual tools vary"
>   1 "The MIT License (MIT)"
>   1 The Non-Profit Open Software License version 3.0 (NPOSL-3.0)
>   1 "UC-LBL license (see package)"
>   1 uncopyrighted
>   5 unknown
>   7 Unknown
>   1 Unknown 
>   2 UNKNOWN
>   1 Unlimited
>  67 "varies; see http://genome.ucsc.edu/license"
>   1 W3C License
>   1 WTFPL
>   1 ZPL 2.1
> ```

**Comment by bgruening** [comment]
Great idea! I would merge a PR :-)
I think it would make sense to add a Travis check to this field with a huge list of allowed licenses. 
I was thinking about this since a while we could also check if tests are defined. In rare cases we need a way to explicitly deactivate those checks.

**Comment by hardingnj** [comment]
Cool, as a first pass I can slim down the list of allowed licenses and fix some of the license/license_file mix ups. 

Some licenses require that copies of themselves are included in any distribution, so that's something else to look into.

**Comment by bgruening** [comment]
You might also look how github handels license and to get an initial list.
Thanks for looking at it!

**Comment by daler** [comment]
I agree, and it will be nice to have a linter to warn about this kind of thing. Can you keep track of the set of allowed licenses so we can check against that list in future PRs? Thanks for brining this up and working on it.

**Comment by hardingnj** [comment]
Right, just an update on this. For the many packages that use GPL/Apache/Academic this should be straightforward. However there are a number that use custom or institutional licenses (eg https://github.com/TGenNorth/NASP/blob/master/LICENSE.rst). For these I was planning to use a custom tag, then we can enforce a `license file` in the meta.yaml.

Also, several software packages use the >= notation, so unsure how to handle that. 

Will aim to submit a PR with a license list in the next week or so.

**Comment by bgruening** [comment]
This would be a nice project for the upcoming hackathon.

**Comment by peterjc** [comment]
This ought to include addressing multiple licensing (eg dual licensing), there is a mix of comma separated, or separated, and pipe (``|``) separated. e.g.

```
recipes/angsd/meta.yaml:  license: GPLv3, MIT
recipes/tqdm/meta.yaml:  license: Mozilla Public License 2.0 (MPL 2.0) or MIT License
recipes/vsearch/meta.yaml:  license: "dual-licensed under GPLv3+ or BSD 2-clause"
recipes/r-bigmemory/meta.yaml:  license: LGPL-3 | Apache License 2.0
```

**Comment by epruesse** [comment]
closing in favor of https://github.com/bioconda/bioconda-utils/issues/438
