### ISSUE TITLE
gnu-wget fails to run due to OpenSSL version

### ISSUE THREAD

**Issue by pcm32** [bioconda/bioconda-recipes#16128]
Running wget inside environemnt created for gnu-wget fails with this error:

```
wget: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

for some reason the binary is requesting a particular version of libssl, but a slightly newer version gets installed. Going into the environment and changing the OpeSSL package version installed to 1.0.0 fixes the problem. Should OpenSSL 1.0.0 be pinned in gnu-wget package?

The same error doesn't happen inside the mulled container.

**Comment by bgruening** [comment]
We moved gnu-wget to conda-forge. We could try to fix the old package, but is it worth it? Can you depend on the conda-forge on, its called just wget I think.

**Comment by pcm32** [comment]
Thanks! Do those get a container created as the ones in bioconda?

**Comment by pcm32** [comment]
This is for a galaxy tool wrapper that does some wget calls, so we only depend on gnu-wget.

**Comment by bgruening** [comment]
@pcm32, not all of them but you can always use the multitool-container repo to create one if it is missing.

**Comment by bgruening** [comment]
I released a new build of this old version with better pinning. Please note that we still need to migrate to the new conda-forge packages. This was just a out-of-order release :)
