### ISSUE TITLE
Bioconductor Easy-qpcr

### ISSUE THREAD

**Issue by PertuyF** [bioconda/bioconda-recipes#16158]
Hi @dpryan79 !

I noticed you prepared a recipe for [`bioconductor-easyqpcr` version `1.26.0`](https://github.com/bioconda/bioconda-recipes/blob/bulk/recipes/bioconductor-easyqpcr/meta.yaml) in bulk, likely as part of next Bioconductor release on bioconda (version 3.9 of the repo). I believe this is on hold waiting for release of R `3.6.1`?

Looks like there used to be a recipe for [version `1.24.0` of this package](https://github.com/bioconda/bioconda-recipes/blob/3761102478f21107957c166e85ca843f9c3410b1/recipes/bioconductor-easyqpcr/meta.yaml), matching bioconductor 3.8, hence R `3.5.1`, but no package can be found on Bioconda.
Would it be OK with you to compile the package for version `1.24.0` now?

**Comment by dpryan79** [comment]
I could never get that to pass testing, it always seemed to need a fully functional X server. I can presumably add it, but I can't guarantee that it'll actually work then.

**Comment by bgruening** [comment]
@PertuyF does this work for you https://anaconda.org/bioconda/bioconductor-easyqpcr/files

Please reopen if not. :)
