### ISSUE TITLE
Error running rMATS

### ISSUE THREAD

**Issue by pd1305** [bioconda/bioconda-recipes#16169]
Hello, I am a biologist trying to analyse my RNAseq data for alternative splicing. I am trying to run rMATS and encountering many errors. Any pointers in this direction will be very useful. Thank you very much in advance.

Command line used:  rmats.py --b1 /home/RNAseq_BAM/b1.txt --b2 /home/RNAseq_BAM/b2.txt --gtf /home/Homo_sapiens.GRCh37.75.gtf --od /home/rmats_op -t paired --readLength 130 --cstat 0.0001 --libType fr-unstranded  

There are 63677 distinct gene ID in the gtf file
There are 215170 distinct transcript ID in the gtf file
There are 39333 one-transcript genes in the gtf file
There are 1306656 exons in the gtf file
There are 27125 one-exon transcripts in the gtf file
There are 23895 one-transcript genes with only one exon in the transcript

Average number of transcripts per gene is 3.379085
Average number of exons per transcript is 6.072668
Average number of exons per transcript excluding one-exon tx is 6.804387
Average number of gene per geneGroup is 7.854952

Fail to open ﻿home/RNAseq_BAM/C12_S1.bam
Fail to open  home/RNAseq_BAM/C12_S2.bam
Fail to open  home/RNAseq_BAM/C12_S3.bam
Fail to open ﻿home/RNAseq_BAM/UT_S1.bam
Fail to open  home/RNAseq_BAM/UT_S2.bam
Fail to open  home/RNAseq_BAM/UT_S3.bam

Done processing each gene from dictionary to compile AS events
Found 41132 exon skipping events
Found 2567 exon MX events
Found 14232 alt SS events
There are 8814 alt 3 SS events and 5418 alt 5 SS events.
Found 6651 RI events

Running the statistical part.
/home/anaconda3/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/odenthal/anaconda3/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpZW150k/JC_SE/rMATS_result_P-V.txt'
paste: /tmp/tmpZW150k/JC_SE/rMATS_result_FDR.txt: File or directory not found

/home/anaconda3/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/odenthal/anaconda3/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpZW150k/JCEC_SE/rMATS_result_P-V.txt'
paste: /tmp/tmpZW150k/JCEC_SE/rMATS_result_FDR.txt: File or directory not found

..........
The statistical part is done.
Done

**Comment by bgruening** [comment]
Could you please retest the latest version and open a new issue if this still exists?

Thanks!

**Comment by jianguozhouzunyimedicaluniversity** [comment]
I also have this error...
