### ISSUE TITLE
maker

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#16277]
Hi @abretaud, @nathanweeks, @johanneskoester, @kastman and @ArneKr,
I am running maker in the following way for 140 hours on 100 compute nodes. Is it normal that no output files have been generated until now?

```
#!/bin/bash -l
#PBS -N maker
#PBS -l walltime=150:00:00
#PBS -j oe
#PBS -l select=100:ncpus=1:mpiprocs=1:mem=4G

cd $PBS_O_WORKDIR

conda activate maker

mpirun maker -fix_nucleotides
```

Thank you in advance,

Michal

**Comment by abretaud** [comment]
Hi,
Is there any output produced in $PBS_O_WORKDIR? If it's working correctly, Maker should create a temp dir there with a lot of temporary files.
I tested it with slurm,no idea if there's anything to do when using pbs
Do you have a way to check what Maker is doing? (eating cpu or not ? strace?)

**Comment by mictadlo** [comment]
Hi,
Maybe the problem could be caused by:
```
> qpeek 4702790.pbs
Possible precedence issue with control flow operator at /lustre/work-lustre/waterhouse_team/miniconda2/envs/maker/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
STATUS: Parsing control files...
ERROR: Could not determine if RepBase is installed
--> rank=NA, hostname=cl4n008
```
Where do I install RepBase with this package?

Thank you in advance,

Michal

**Comment by mictadlo** [comment]
Hi, 
I fixed the problem by using `mpirun maker -mpi -RM_off -fix_nucleotides`. However, I got a new problem:

```
DBD::SQLite::db do failed: near ".": syntax error at /lustre/work-lustre/waterhouse_team/miniconda2/envs/maker/bin/../lib/GFFDB.pm line 498, <$IN> line 170017.
```
What did I miss?

Thank you in advance,

Michal

**Comment by abretaud** [comment]
For the repbase error, see my answer in https://github.com/bioconda/bioconda-recipes/issues/16501
For the `DBD::SQLite::db` I've never seen it... Do you give some GFF as evidences in your CTL file?

**Comment by bgruening** [comment]
@mictadlo please open a new issue if this is not resolved :)

Thanks!
