### ISSUE TITLE
Proprietary software (ibm aspera connect/ascp)

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [bioconda/bioconda-recipes#16306]
I couldn't find the license of [aspera connect](https://downloads.asperasoft.com/connect2/), and I couldn't find the policy of bioconda/anaconda neither.

Where can I find the anaconda/bioconda policies about this?

**Comment by bgruening** [comment]
@Maarten-vd-Sande we are only allowed to distribute software that will allow distributing software.

**Comment by Maarten-vd-Sande** [comment]
@bgruening, thanks for the reply.
