### ISSUE TITLE
travis not starting tests

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#1633]
ping @bioconda/all, does anyone know what's going on with travis? There are a few PRs waiting 10+ hrs to start building. travis-ci.com is not reporting any issues.

**Comment by bgruening** [comment]
@daler travis granted us yesterday a increased max build-time. Maybe they screwed something up during the configuration. Let me call the service again ... sorry. If this is working we should have 75min.

**Comment by daler** [comment]
@bgruening I just saw your other messages -- thanks for getting increased build times, that's great!

**Comment by chapmanb** [comment]
Björn -- thanks for doing this and investigating what is going wrong with our builds. Did you have any luck getting us unstuck so we can start pushing packages through again?

**Comment by daler** [comment]
Looks like we're back in business -- thanks @bgruening (xref #1629).

**Comment by bgruening** [comment]
Great, sorry for the inconvenience. Travis is looking at this bug and we will get an increased build-time.
