### ISSUE TITLE
Assistance in building GPU Racon

### ISSUE THREAD

**Issue by rvaser** [bioconda/bioconda-recipes#16358]
Hi,
I was wondering if it is possible to build the new version of racon (1.4.0) with CUDA on your servers? The `build.sh` file needs to be modified by adding `-Dracon_enable_cuda=ON` to the `cmake` list of flags. The minimum CUDA version is 10. I guess the `meta.yaml` file needs an update too?

Thank you and best regards,
Robert

**Comment by bgruening** [comment]
There are legal issues to resolve at first. The brave folks at conda-forge are trying to find a solution. You can read more about it here: https://github.com/conda-forge/conda-forge.github.io/issues/63

Or from Linus: https://www.youtube.com/watch?v=_36yNWw_07g
