### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by jeffhsu3** [bioconda/bioconda-recipes#1639]
I'm getting an conflict error for bx-python when trying to install from bioconda using python3.  Don't see anywhere in the recipe where it specifies the python version.  Not sure how conda handles it.

**Comment by daler** [comment]
By using conda's [preprocessing selectors](http://conda.pydata.org/docs/building/meta-yaml.html#preprocessing-selectors) on the `skip: True` line, we can control which packages get skipped. In this case, the recipe is skipped for anything that's not py27 (see [this line](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bx-python/meta.yaml#L13)). bx-python does not currently support python3 as far as I know.

**Comment by lzamparo** [comment]
From their [setup.py](https://github.com/bxlab/bx-python/blob/master/setup.py):

```python
if sys.version_info < (2, 6):
    sys.exit("ERROR: bx-python requires Python 2.6 or greater")
elif sys.version_info > (3, ) and sys.version_info < (3, 3):
    sys.exit("ERROR: bx-python requires Python 3.3 or greater")
```
They now support contemporary versions of python3. Can we just omit the `skip: True` line to install for python3, or is it more involved?

**Comment by jxtx** [comment]
You can but it is unlikely to work. You can see this on the Travis tests
for bx-python.

The lines in setup.py are new in the dev branch, not in the last release.

**Comment by lzamparo** [comment]
So do you think my best chances are to check out the dev branch and build from setup.py?
