### ISSUE TITLE
vcflib - needs python 2 

### ISSUE THREAD

**Issue by tseemann** [bioconda/bioconda-recipes#16448]
RE: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/vcflib

vcflib is mostly binaries `vcf*` but some of them are python scripts, namely python 2.x, and run using `#!/usr/bin/env python`. 

Unfortunately `python` seems to be 3.x and tools like `vcffirstheader` fail.

How can we make vcflib depend on python 2.x instead?

CC: @Koen-vdl

**Comment by bgruening** [comment]
Hi @tseemann,

you can pin the python version in the recipe to `python <3`. But please note that python2 is EOL next year, so these scripts should really be ported over.

**Comment by tseemann** [comment]
Thanks @bgruening - I don't know how to do that, and am posting this on behalf of someone.  I will file with upstream @ekg

**Comment by bgruening** [comment]
@tseemann you could do it this way: https://github.com/bioconda/bioconda-recipes/pull/16450

However, this adds big python to its dependencies and in theory vcflib also container R ... should we also add R?
Currently, this package does not depend on either of both, so package size is small and the user can easily install python or R on their own.

You could do this via `conda create -n vcflib python=2 vcflib r-base=3.6`.

I'm not sure we should add python and R to the package. @ekg do you consider these scripts as part of the vcflib package and python/R as a dependency?

**Comment by tseemann** [comment]
The `python` scripts are definetly essential (and should be moved to py 3.x or perl)
The `R` scripts are rarely/ever used.

**Comment by tseemann** [comment]
Ok, i've worked with upstream and removed py2 !
https://github.com/vcflib/vcflib/releases/tag/v1.0.0-rc3

**Comment by bgruening** [comment]
Cool, thanks! I think we can close this.
