### ISSUE TITLE
Snakemake and others not building for Python 3.4?

### ISSUE THREAD

**Issue by tomkinsc** [bioconda/bioconda-recipes#1647]
Looking at the builds of Snakemake [available on anaconda.org](https://anaconda.org/bioconda/snakemake/files) (and other packages), it seems Snakemake 3.7.1 is only available in a build for Python 3.5. Is this expected with the new build system? Was 3.4 eliminated from the build matrix for any particular reason (storage constraints?)?

**Comment by johanneskoester** [comment]
You are right. I added it again in PR #1667. Thanks for pointing this out!
