### ISSUE TITLE
scrm: segfault on all tested input

### ISSUE THREAD

**Issue by kdmurray91** [bioconda/bioconda-recipes#16550]
Hello,

It would appear that the scrm package (v 1.7.3) is broken. I get a segmentation fault on any usage of the tool (e.g. the `scrm 2 1 -T` used to test the recipe). I'm on debian sid, x86_64. GDB reports the segfault to happen thusly:

```
(gdb) r 2 1 -T
Starting program: ~/opt/conda3/envs/popsim/bin/scrm 2 1 -T

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff7f29fd8 in std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream (this=0x7fffffffab70, __in_chrg=2,              
    __vtt_parm=0x0)
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/build/build-cc-gcc-final/x86_64-conda_cos6-linux-gnu/libstdc++-v3/include/sstream:783
#2  0x0000000000437053 in double Param::convert<double>(std::string const&) [clone .local.3009] ()                                                                          
#3  0x0000000000439211 in Param::parse() ()
#4  0x0000000000405952 in main ()
```

I've taken a look at the recipe, and it looks like it builds the same way I have in the past (& the same way the debian package does, IIRC).

I've manually checked out version [1.7.3](https://github.com/scrm/scrm/archive/v1.7.3.tar.gz) from github, build the same way as build.sh does, and it works fine. 

I''ve no idea would cause this. CC upstream author @paulstaab in case he has any ideas?

Cheers,
K

**Comment by bgruening** [comment]
Can you please try the latest version and make sure you get the build number 1.
