### ISSUE TITLE
Need to specify linux-64 only but forced noarch

### ISSUE THREAD

**Issue by aaronmussig** [bioconda/bioconda-recipes#16557]
Hello,

I'm updating the `gtdbtk` package to specify that it cannot be run on OSX (given that the pplacer dependency is linux-64 only). However, I cannot do this using `skip: True  # [osx or py3k]` as linting specifies:
`ERROR: recipes/gtdbtk/meta.yaml:15: should_be_noarch_generic: The recipe should be build as noarch`.

The current master version is `noarch` as I couldn't figure it out and figured it was best to get the most up-to-date version released ASAP. However, the issue has been arising where OSX users are installing the package and unsure why it fails.

Link to [meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/gtdbtk/recipes/gtdbtk/meta.yaml)
PR: #16556 
Thanks for your input,
Aaron.

**Comment by dpryan79** [comment]
The issue is that the previous build will always be there so they'll always run into this. Maybe have a look at pplacer and see if you can get it built for OSX. Alternatively, document in your readme that only Linux is supported.

**Comment by aaronmussig** [comment]
Thanks for clearing that up, it's much appreciated. I'll see what I can do with pplacer.
