### ISSUE TITLE
Need a configure file for a heterogeneous plant genome genome size is 600mb.

### ISSUE THREAD

**Issue by nagendranipgr** [bioconda/bioconda-recipes#16741]
Actually i want to assemble heterogeneous plant genome genome size is 600mb. but how to configure the file for that. Can you plz provide me a falcon assembler configure file with all best parameters. i go though all the tutorials but i didn't understands how to configure file. i run the with examples data its running fine but with my data I am getting error. i am using pb-assembly installed with conda install -c bioconda pb-assembly we have local server 2tb Ram with 108 core and 4 CPU plz configure the all need computational need also.

Thanking you in advances

**Comment by PertuyF** [comment]
Hi,
This is the repository for Bioconda *recipes*, it is not the appropriate place for such question. If you need help regarding usage of a specific package, please see the [dedicated repo](https://github.com/PacificBiosciences/pb-assembly), or any users discussion space.
