### ISSUE TITLE
STAR-Fusion is missing Carp::Assert (perl-carp-assert) dependency

### ISSUE THREAD

**Issue by acesnik** [bioconda/bioconda-recipes#16759]
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/star-fusion/meta.yaml#L20

needs to have `- perl-carp-assert`, too

Error from STAR-Fusion:
```
Can't locate Carp/Assert.pm in @INC (you may need to install the Carp::Assert module) (@INC contains: /home/acesnik/miniconda3/envs/spritz/lib/STAR-Fusion/FusionAnnotator/util/../PerlLib /home/acesnik/miniconda3/envs/spritz/lib/STAR-Fusion/FusionAnnotator/util /home/acesnik/miniconda3/envs/spritz/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/acesnik/miniconda3/envs/spritz/lib/site_perl/5.26.2 /home/acesnik/miniconda3/envs/spritz/lib/5.26.2/x86_64-linux-thread-multi /home/acesnik/miniconda3/envs/spritz/lib/5.26.2 .) at /home/acesnik/miniconda3/envs/spritz/lib/STAR-Fusion/FusionAnnotator/util/FusionCodingEffect.pm line 6.
```

**Comment by bgruening** [comment]
A fix is here https://github.com/bioconda/bioconda-recipes/pull/16760 and waiting for review and merge.

Thanks for reporting!

**Comment by micknudsen** [comment]
@acesnik Does that error occur if you just run the `STAR-Fusion` command with no options? I run STAR-Fusion almost on a daily basis, and I have never encountered that error.

**Comment by acesnik** [comment]
I'm using something like `--examine_coding_effect --CPU {threads} --tmpdir {input.tmpdir} --genome_lib_dir {input.genomelibdir} --output_dir output --left_fq {input.fq1} --right_fq {input.fq2}`

**Comment by micknudsen** [comment]
Oops. Now I see that I have actually added `perl-carp-assert` to my environment. I must have had the same error and just forgot about it. I think I considered it "not strictly necessary" as requirement, because it isn't needed for the very basic functionality. For example like certain R-stuff in GATK.
