### ISSUE TITLE
scanpy - remove constraint on scipy version

### ISSUE THREAD

**Issue by 0xaf1f** [bioconda/bioconda-recipes#16793]
With the [last scanpy update](https://github.com/bioconda/bioconda-recipes/commit/8d239cb62987d1769d81f6ba72759448cd019b05), the scipy dependency was appropriately pinned to version <1.3 because of https://github.com/theislab/scanpy/issues/643 (helpfully linked from the commit message!), which traces back to an issue in anndata that [looks to have been fixed in the latest version](https://anndata.readthedocs.io/en/stable/#post-v0-6-june-6-2019). Could the scipy version constraint now be dropped from scanpy?

**Comment by bgruening** [comment]
Have a look at https://github.com/bioconda/bioconda-recipes/pull/16804.

You are welcome to contribute and fix recipes if you like!
