### ISSUE TITLE
Next Bioconda Collaboration Fest 30.09.2019 and 01.10.2019

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#16858]
Hi all,

we would like to organize a new collaboration fest and work together with you on Bioconda and it's ecosystem.

There is a lot to do! Here are a few ideas:

* Linting of the entire repo
* adding more jinja templates to make auto-updates and review easier
* adding DOI / bio.tools
* Reviewing package license, add missing ones
* Moving packages to conda-forge
* Documenting missing parts of Bioconda
* Missing tools - get started and contribute to Bioconda
* Go over all our issues
* Go over all the PRs
* adjust linting skips to new names e.g. uses_git_url --> uses_vcs_url**

We would like to encourage you to organize local events and join us as teams. A globally, decentralised Bioconda Collaboration Fest.

Joins us at __30.09.2019__ and __01.10.2019__ and improve the conda ecosystem!

Google Hangout: https://hangouts.google.com/call/rpXeNTj0gJAdIqxZTIfoAEEI
GitterChat: https://gitter.im/bioconda/Lobby

**Comment by bgruening** [comment]
The University of Freiburg will host one of these events. Read more in our [announcement](https://galaxyproject.eu/event/2019-08-19-bioconda-cofest/) and join us if you are closeby.

**Comment by pinin4fjords** [comment]
We'd love to help out on this, though it may end up being just one of us. Is there more info somewhere on how these things should be structured, how we should coordinate? Happy to do some grunt-work if there are things you can leave to people with less in-depth know-how.

**Comment by bgruening** [comment]
Hi @pinin4fjords!

What I will do is: 
- get a bigger room,
- some beverages,
- and cookies :) 

The rest we will organize on the day on gitter and I'm pretty sure there is a lot to do for everyone!

Would be great if a few EBI people could join you. If you confirm I will try to send a few EBI friends to you :)

**Comment by pinin4fjords** [comment]
I'm sending out feelers- but yep, you can point people at me. I'm happy to coordinate rooms etc once I have an idea what numbers we have.

**Comment by dpryan79** [comment]
@bgruening Do you have a room in mind or are you thinking about just using the meeting room near your office? I was planning to come over and at least one other person from here will also be joining.

**Comment by FleurGaBru** [comment]
Hi! The bioinformatics unit of the NIOO-KNAW in the Netherlands (@mdehollander and me) would also like to contribute. Do you already have of program or a plan, how divide tasks?

**Comment by bgruening** [comment]
@bgruening we will use the big meeting room next to our offices. It can fit 20 people - so I think this will be fine. There are rumors that an EBI organized hackathon will also happen :)

I will post a hangout link here during the weekend. In addition I assume that we all will be on [gitter](https://gitter.im/bioconda/Lobby) to help and coordinate us :)

**Comment by bgruening** [comment]
@FleurGaBru awesome! Thanks for joining. I have a list of things that we all can work on in the issue above. If you want to pick on that would be a start. Otherwise, we organize and group us (depending on how many people we are) on Monday morning. If we are lucky we have contributors from all over the work and can keep the CI system busy 24h :)

**Comment by druvus** [comment]
We are also hosting a local event at Umeå University during the first day (10-16 CET) to do outreach and contribute at the same time.

**Comment by bgruening** [comment]
@druvus great news!

**Comment by bgruening** [comment]
Let's use Hangouts and Gitter to coordinate our work:

Google Hangout: https://hangouts.google.com/call/rpXeNTj0gJAdIqxZTIfoAEEI
GitterChat: https://gitter.im/bioconda/Lobby

And please write here if you plan to work on some items.

Thanks see you all in 2 days.

**Comment by bgruening** [comment]
I will start with some old issue :)

**Comment by bgruening** [comment]
There are of course also all issue with the `hackathon` label: https://github.com/bioconda/bioconda-recipes/labels/hackathon

**Comment by bgruening** [comment]
Thanks a lot everyone! 

In the last two days we have merged over 50 PR on Bioconda (no counting our work on conda-forge), closed nearly 100 issues, added DOI and license information to packages and migrated 35 packages to conda-forge. There has also been work to start linting the entire repo and add noarch information to hundreds of packages.

Do you have any feedback for us? Should we do this more often?
