### ISSUE TITLE
STAR-Fusion is missing IGV Reports (igv-reports) dependency

### ISSUE THREAD

**Issue by acesnik** [bioconda/bioconda-recipes#16877]
Just encountered another dependency error in STAR-Fusion  when running with FusionInspector options. (https://github.com/bioconda/bioconda-recipes/issues/16759 was just fixed)

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/star-fusion/meta.yaml#L20

needs to have - igv-reports, too

Error from STAR-Fusion:

```
Traceback (most recent call last):
  File "/home/acesnik/miniconda3/envs/spritz/lib/STAR-Fusion/FusionInspector/fusion-reports/create_fusion_report.py", line 7, in <module>
    from igv_reports import datauri
ModuleNotFoundError: No module named 'igv_reports'
```

**Comment by acesnik** [comment]
Just to confirm, STAR-Fusion finished with FusionInspector after adding `igv-reports` to my conda environment.

**Comment by acesnik** [comment]
It looks like you may also want to add `- requests`, too, based on the FusionInspector software requirements. I'm not sure if that's part of the base distribution.

**Comment by acesnik** [comment]
It looks like there's also an option to use `Trinity` to do reconstruction, so maybe including `- trinity` is also in order.

https://github.com/FusionInspector/FusionInspector/wiki/De-novo-reconstruction-of-fusion-transcripts

https://github.com/STAR-Fusion/STAR-Fusion/blob/5e26eee39fc59dd45e4a13403726790b14e9a6fc/STAR-Fusion#L215

**Comment by micknudsen** [comment]
I have had to pin `igv-reports==0.2.1`. Other versions on bioconda are `>=0.9.0`, and they seem to be incompatible with `STAR-Fusion`.

**Comment by acesnik** [comment]
I had success yesterday with `igv-report=0.9.4`, so maybe the issue was fixed. :)

**Comment by acesnik** [comment]
By the way, the latest version of trinity failed for me, so I'd recommend using `- trinity=2.9.4-0`

**Comment by micknudsen** [comment]
Maybe you ran into this bug which existed for a rather short time?

https://github.com/bioconda/bioconda-recipes/pull/16873#issuecomment-521166797

**Comment by micknudsen** [comment]
@acesnik You are right. Now STAR-Fusion also works for me with `igv-reports=0.9.4`.

**Comment by bgruening** [comment]
Cool thanks for catching up!
