### ISSUE TITLE
No way to test recipes locally

### ISSUE THREAD

**Issue by RomainFeron** [bioconda/bioconda-recipes#16881]
Hi,

I am writing a few recipes for bioconda and I would like to be able to test them locally. At the moment, for me, neither the CircleCLI client nor the bootstrap method works.

**CircleCLI client**

It seems that git is missing from the docker archive (I think this has been reported before).

`circleci build 
`
> Docker image digest: sha256:65b2102646d5658f892e0ad8253b7912c676126c857c87c8c12460f0aa4f5aa1
> ====>> Spin up Environment
> Build-agent version 1.0.8563-43047892 (2019-03-06T15:11:54+0000)
> Starting container bioconda/bioconda-utils-build-env
>   using image bioconda/bioconda-utils-build-env@sha256:1686e738903f322e5cc2d83ab8b89b9d233fe92e59cb8597c3910146b00b51ed
> 
> Using build environment variables
>   BASH_ENV=/tmp/.bash_env-localbuild-1565772004
>   CI=true
>   CIRCLECI=true
>   CIRCLE_BRANCH=PhyloCSF
>   CIRCLE_BUILD_NUM=
>   CIRCLE_JOB=build
>   CIRCLE_NODE_INDEX=0
>   CIRCLE_NODE_TOTAL=1
>   CIRCLE_REPOSITORY_URL=git@github.com:bioconda/bioconda-recipes.git
>   CIRCLE_SHA1=d8500521b997954e310dc0d7a522be6491904786
>   CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1565772004
>   CIRCLE_WORKING_DIRECTORY=~/project
> 
> ====>> Checkout code
>   #!/bin/bash -eo pipefail
> mkdir -p /root/project && cd /tmp/_circleci_local_build_repo && git ls-files -z | xargs -0 tar -c | tar -x -C /root/project && cp -a /tmp/_circleci_local_build_repo/.git /root/project
> /bin/bash: git: command not found
> tar: Cowardly refusing to create an empty archive
> Try `tar --help' or `tar --usage' for more information.
> tar: This does not look like a tar archive
> tar: Exiting with failure status due to previous errors
> Error: Exited with code 2
> Step failed
> Error: runner failed
> {"Runner":true,"level":"error","msg":"runner failed","task-id":"localbuild-1565772004","time":"2019-08-14T08:40:08Z"}
> Task failed
> Error: task failed

**Bootstrap method**

Somehow numpy seems to be missing from the conda environment :

`bioconda-utils build --docker --mulled-test --git-range master`

> 
> Traceback (most recent call last):
>   File "/tmp/miniconda/miniconda/bin/bioconda-utils", line 6, in <module>
>     from bioconda_utils.cli import main
>   File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 25, in <module>
>     import pandas
>   File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/pandas/__init__.py", line 19, in <module>
>     "Missing required dependencies {0}".format(missing_dependencies))
> ImportError: Missing required dependencies ['numpy']

Listing packages in the current conda environment, numpy is there :

`conda list`

> \# packages in environment at /tmp/miniconda/miniconda:
> \#
> \# Name                    Version                   Build  Channel
> numpy                       1.16.4                     py36h99e49ec_0  
> numpy-base              1.16.4                     py36h2f8d375_0 

I know this is a bit two issues in one, but I thought to group them since the result is that I cannot test my recipes locally.
Any idea how to solve either problem ?

Thanks !

**Comment by dpryan79** [comment]
I've never gotten the circleci client to work. For bioconda-utils, try making a new env (` conda create -n bioconda bioconda-utils`) and see if using that env fixes the issue.

**Comment by RomainFeron** [comment]
Thanks for your reply. I followed the tutorial on https://bioconda.github.io/contributor/building-locally.html, so I had to load the environment created by boostrap.py I think.
However, I fixed my problem with another approach, I will post it in case somebody has the same problem: I uninstalled numpy (
