### ISSUE TITLE
Installing trimmomatic without installl Java-11

### ISSUE THREAD

**Issue by abhi18av** [bioconda/bioconda-recipes#16935]
Hello BioConda team,

I am trying to install `trimmomatic` from this channel and I already have `Java 8` setup on my `Ubuntu` machine. However, when I try to install the package it prints out 

```sh
(biodragon) (miniconda3-latest) root@biodragon:~# conda install trimmomatic
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /root/.pyenv/versions/miniconda3-latest/envs/biodragon

  added / updated specs:
    - trimmomatic


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openjdk-11.0.1             |    h516909a_1016       175.5 MB  conda-forge
    trimmomatic-0.39           |                1         142 KB  bioconda
    ------------------------------------------------------------
                                           Total:       175.7 MB

The following NEW packages will be INSTALLED:

  openjdk            conda-forge/linux-64::openjdk-11.0.1-h516909a_1016
  trimmomatic        bioconda/noarch::trimmomatic-0.39-1


Proceed ([y]/n)? 

```

I have installed `java` via the `asdf` package manager and this is the location of `java` 

```
/root/.asdf/installs/graalvm/19.1.1
```

Another piece of information is about `java -version`

```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-20190711120915.buildslave.jdk8u-src-tar--b08)
OpenJDK 64-Bit GraalVM CE 19.1.1 (build 25.222-b08-jvmci-19.1-b01, mixed mode)
(biodragon) (miniconda3-latest) root@biodragon:~/.asdf/installs/graalvm/19.1.1# 
```
My guess is that `conda` isn't able to sense that `Java` is already installed. Could you please help me out?

**Comment by PertuyF** [comment]
Conda does not rely on system dependencies, which would completely cancel the purpose of virtual environments.
So it is completely normal openjdk is installed in your case, you can't (and don't want to) avoid that.

**Comment by abhi18av** [comment]
Ohh, I see. Well I found a solution to this problem in a different way, I just specified the `openjdk=x.y.z` to conda while trying to install the packages and it managed the rest. 

I think the it'll take care of it the same way when I try to reproduce it later on again.

Thanks for the clarification @percyfal 👍
