### ISSUE TITLE
[request] bbmap suite adapters is missing

### ISSUE THREAD

**Issue by sunta3iouxos** [bioconda/bioconda-recipes#16972]
Hi all,

This is a request based on file omission for the BBmap suite.

So, I was looking to use the  bbmap suite (specifically the trimming
subroutine), downloaded it with bioconda but the extra folder that contains all adapters
(in bbmap resources folder, that exists in the original .tar.gz from sourceforge) is
not there. While for the trimmomatic the folder is properly created.
Could you please fix this?

Best
Theo

**Comment by pvanheus** [comment]
Hi @sunta3iouxos 

The resources folder is copied as part of the recipe, and is available at `$CONDA_PREFIX/opt/bbmap*/resources` (presuming you have installed `bbmap` in a conda environment).

Is this sufficient to answer your question?
