### ISSUE TITLE
Adding new members

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#1701]
Dear @bioconda/core,
when adding new members to the team, please make sure to put them into the "all" team so that we can properly mention them in issues that concern everybody. Further, they should also be added to the list of devs in the file `docs/index.rst`.

**Comment by bgruening** [comment]
Can we push to master directly to add members. Creating a PR for every new member seem like a little bit of overhead. Maybe we should generate the `docs/index.rst` automatically, or just link to https://github.com/bioconda/bioconda-recipes/graphs/contributors ?

**Comment by johanneskoester** [comment]
I think it would anyway be a clean solution would to move the docs out of the recipes repository. For such a separated repository, there is no need to protect the master branch.

**Comment by bgruening** [comment]
@johanneskoester can we simply link to this page everywhere? https://github.com/bioconda/bioconda-recipes/graphs/contributors

**Comment by johanneskoester** [comment]
Done, see PR #2628.
