### ISSUE TITLE
Symbol lookup error with samtools 1.3.1_1

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#1728]
With the latest samtools build, I get a lookup error that apparently comes from the system libncurses:
```
samtools: symbol lookup error: /lib64/libncurses.so.5: undefined symbol: _nc_putchar
```

@chapmanb any idea how that can happen? I thought that we pin the version and explicitly use the packaged ncurses.

**Comment by chapmanb** [comment]
Johannes;
I think one is the annoying incompatibility between ncurses in the `r` channel and standard ncurses. Both are `5.9` but the packages in bioconda get built against the `r` version (5.9-4) and this is apparently different than the standard version (5.9-0). I can reproduce your problem if I force install the standard system r and can fix with:

https://github.com/bioconda/bioconda-recipes/issues/637#issuecomment-173021376

I don't know how to avoid this in our builds without dropping the `r` package when pulling things in so it gets built against the system ncurses package.

**Comment by johanneskoester** [comment]
Right, I forgot about this. Sorry for the noise! We could think about adding a pre-link script that issues a warning to activate the r channel. Another nice thing would be channel dependencies (i.e., activating bioconda implies activating the r channel).
