### ISSUE TITLE
GCC dependency and common build platform

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#1734]
Hi @bioconda/core ,
Last week, I have attended a meeting with Continuum and Conda-Forge about what strategy to follow in terms of depending on gcc or using the built-in compiler. The bottom line was that both strategies have their downsides and limitations, and no consensus has been reached so far. A side question was what would be the minimum CentOS version to support. Conda-forge is using CentOS 6, we and Continuum are using CentOS 5.

Here comes my question:
Is it feasible for us to switch to CentOS 6? Does anybody know about clusters that still use CentOS 5?

**Comment by bgruening** [comment]
Adding a few more items for the conda-forge meeting last week:

1. conda-forge wants to add more prefixes to the packages, like bioconda is doing with `perl-`, `r-` and `bioconda-`, but also for `python-`, `node-` and what ever we will package. Any objections against this?

2. I would also like to split our repo into subdirectories, `perl`, `python`, `r` and so on. We currently have more packages than github can display and this would solve it for the foreseeable future.

> Is it feasible for us to switch to CentOS 6? Does anybody know about clusters that still use CentOS 5?

I don't know anyone running a cluster on CentOS 5.

**Comment by johanneskoester** [comment]
1. For the python prefix, I would only do this if Continuum does it as well in the default channel. For the rest, we do this anyway, right?
2. That would be fine for me. Any such changes should wait until we have switched to the new bioconda-utils, because the current scripts/build-packages.py should not be changed anymore (in order to avoid the need to port things over to bioconda-utils).

**Comment by bgruening** [comment]
> 1. For the python prefix, I would only do this if Continuum does it as well in the default channel. For the rest, we do this anyway, right?

The  Continuum people in conda-forge are fine with this move. I think changing the default channel will not happen in the near future, it's not high priority.
If you ask me, conda-forge will define standards (with us) and the default channel will be synced with conda-forge.

**Comment by johanneskoester** [comment]
For the user, this is quite inconvenient. If this move is not made in an orchestrated way, you can end up with two installations of the same package in the same environment, and you don't know which one overwrites the other.

Further, did they mention if this is planned only for libs or also for tools? It does not make sense to call a command line utility python-xy, only because it has been written in Python. This does not matter for the end user, and he probably does not even know. Also, how should we deal with packages that represent a mix of languages?

**Comment by chapmanb** [comment]
Johannes and Björn;
We support systems with bcbio that run CentOS 5, so would vote for keeping with that to maintain compatibility. Why do the conda-forge team prefer CentOS 6? With the devtoolset you can get up to date compilers for 5 and everything builds cleanly. It seems like we should error on the side of being more compatible if there are no build downsides.

I'd also be careful about renaming, as that seems like a potential compatibility nightmare for little gain. If we want to suggest a naming scheme for new packages, I'm for that. For perl, I've been naming libraries with perl- and tools without. It's arbitrary in some cases, but as long as we maintain a consistent name we should be okay.

**Comment by bgruening** [comment]
>For the user, this is quite inconvenient. If this move is not made in an orchestrated way, you can end up with two installations of the same package in the same environment, and you don't know which one overwrites the other.

Channel priorities will fix this and it was discussed to enhance conda to give smarter hints to find the correct package.

> Further, did they mention if this is planned only for libs or also for tools? It does not make sense to call a command line utility python-xy, only because it has been written in Python. 

My understanding was that this holds true for all python packages (e.g. coming from pypi). Debian, Fedora is doing the same, so I don't see a problem here. We already have prefixes all over the place just for python packages we don't.

>  This does not matter for the end user, and he probably does not even know.

? I think prefixing with `python-` is the same as prefixing with `perl-`. The user needs to know that `bioperl` is called `perl-bioperl`

> Also, how should we deal with packages that represent a mix of languages?

No prefix I guess.

If conda-forge will be using this schema and we should probably follow.

Brad;
>We support systems with bcbio that run CentOS 5, so would vote for keeping with that to maintain compatibility. Why do the conda-forge team prefer CentOS 6? With the devtoolset you can get up to date compilers for 5 and everything builds cleanly. It seems like we should error on the side of being more compatible if there are no build downsides.

My understanding was that it is hard to get newer devtoolsets to work on old CentOS and that features like OpenCL will not work. Please participate on this poll: https://t.co/q0l2mkS5Na
Brad do you know how many bcbio users are running CentOS 5?

> I'd also be careful about renaming, as that seems like a potential compatibility nightmare for little gain. If we want to suggest a naming scheme for new packages, I'm for that. For perl, I've been naming libraries with perl- and tools without. It's arbitrary in some cases, but as long as we maintain a consistent name we should be okay.

Oh sorry for the confusion I'm not talking about renaming old recipes but we should have consistent naming schemes over all languages for new packages.

**Comment by bgruening** [comment]
@jxtx nothing decided yet, please participate here: https://t.co/q0l2mkS5Na

**Comment by chapmanb** [comment]
Björn -- I don't keep stats like that but I'd guess a handful of places (~5?) are running older CentOS versions. It would be useful to know. I assume Galaxy is going to have the same problem as these are primarily infrequently updated academic clusters.

**Comment by bgruening** [comment]
Yes Galaxy will have the same problem.
The problem is really that we want to support newer toolchains but can not do this with such old systems. My personal opinion is that the merge with conda-forge is worth to break the compatibility with CentOS-5, if needed. But it's not yet clear if conda-forge will switch to CentOS-6. We wanted to ask the community first - that's the reason for the questionnaire.

Thanks for the feedback! Exactly what we need!

**Comment by johanneskoester** [comment]
I thought that conda-forge is already building on CentOS-6. They might move to CentOS 5 depending on the questionnaire.
To clarify, there won't be a merge with conda-forge, we just want to unify our build-platform and to be able to depend on packages in conda-forge.

**Comment by johanneskoester** [comment]
@bgruening, I don't think that the prefix-policy convinces me. For R packages, the prefix makes sense, because they are always imported from R. The same for Perl and node in general. However, for any tool that just offers a command line interface (regardless of the language), I think a package name without prefix makes more sense. Think about it: package names like "c-bwa", "java-gatk", "c++-bowtie" just don't make sense for the user. Further, they might be even misleading, in the sense that people might assume that this is a corresponding API instead of the command line utility.

**Comment by bgruening** [comment]
@johanneskoester I'm not talking about compiled languages. At least this is what I remember from the last meeting - sorry to not being concrete enough. I think bioconda is pretty much on the save side here as we do prefixing a lot, just not python afaik.
Perl packages also offer a lot command-line utilities and we do prefix them. I think this makes logically sense and is in consensus to other packagers like dpkg.

**Comment by johanneskoester** [comment]
Making a distinction between scripting and compiled languages sounds rather arbitrary to me. Regarding perl, STAR-Fusion is written in Perl, and we don't prefix it. There is no reason to call it perl-star-fusion. It can't be used from within perl, it adds no value to the perl ecosystem, there won't ever be a package called python-star-fusion, unless the author decides to port the package entirely. In that case, it would rather be a new version number.

Without really thinking about it we made a rather natural choice in bioconda. Published tools, where the author has chosen a reasonable name and where no value is added by prefixing are called as they have been named by upstream. Libraries that are of general use in a language ecosystem are prefixed with the language name.

Even if we start only prefixing new incoming Python libraries (and not command line utilities), I am a bit worried about the results. This would mean we have a lot of python packages without prefix, and some new ones with a prefix. If a new user starts using conda/bioconda, he would think that this is a mess.

Finally, let me quote the Debian guidelines:

>  Public Python 3 modules used by other packages must have their binary package name prefixed with python3-. Public Python 2 modules used by other packages must have their binary package name prefixed with python-. It is recommended to use this prefix for all packages with public modules as they may be used by other packages in the future.

They as well only encourage the prefixing for library type packages. An example for this policy is the package of the version control system Mercurial. In Debian based distros, this is called "mercurial", not "python-mercurial" although it is written in Python, because it is mainly a tool, not a library.

**Comment by bgruening** [comment]
> Making a distinction between scripting and compiled languages sounds rather arbitrary to me. 

It's not so arbitrary if you look at how most of the packages are created, compiled ones are written from scratch, scripting ones are created by skeletons - and these are usually prefixed.

> Regarding perl, STAR-Fusion is written in Perl, and we don't prefix it. There is no reason to call it perl-star-fusion. It can't be used from within perl, it adds no value to the perl ecosystem, there won't ever be a package called python-star-fusion, unless the author decides to port the package entirely. In that case, it would rather be a new version number.

The only reason star-fusion has no prefix is that it is not in cpan ;)

> Without really thinking about it we made a rather natural choice in bioconda. Published tools, where the author has chosen a reasonable name and where no value is added by prefixing are called as they have been named by upstream. Libraries that are of general use in a language ecosystem are prefixed with the language name.

`reasonable name`, `general use` sounds like some loose definition. If we can make this more concrete and share this view with other conda-projects I'm all for it.

> Even if we start only prefixing new incoming Python libraries (and not command line utilities), I am a bit worried about the results. This would mean we have a lot of python packages without prefix, and some new ones with a prefix. If a new user starts using conda/bioconda, he would think that this is a mess.

Yes, but this is true for every big change we do. Rather now than in 2 years, isn't it. And please keep in mind that this is what was discussed in the conda-forge meeting. I don't care so much about this, I just think it makes sense and we should go with the flow. Otherwise we are better of to discuss this now with the conda-forge team, or we end up with many prefixed python packages in conda-forge and non-prefixed in bioconda. 
(Just mentioning that plans exists to grep the pypy RSS feed and creating packages on-the-fly which makes many bioconda packages obsolete at this point.)

> Finally, let me quote the Debian guidelines:

>>  Public Python 3 modules used by other packages must have their binary package name prefixed with python3-. Public Python 2 modules used by other packages must have their binary package name prefixed with python-. It is recommended to use this prefix for all packages with public modules as they may be used by other packages in the future.

I'm fine with this! We just need to define `public modules` - Imho it is easier to assume everything from pypi is a public-module and go with this.
I'm curious if the conda-forge guys changing the skeleton wrapper as well to prefix packages :)

> They as well only encourage the prefixing for library type packages. An example for this policy is the package of the version control system Mercurial. In Debian based distros, this is called "mercurial", not "python-mercurial" although it is written in Python, because it is mainly a tool, not a library.

And yet this is a public-module isn't it? So you can import it and use it as library :).

**Comment by johanneskoester** [comment]
> It's not so arbitrary if you look at how most of the packages are created, compiled ones are written from scratch, scripting ones are created by skeletons - and these are usually prefixed.

I meant that the distinction is arbitrary from a user perspective.

> And yet this is a public-module isn't it? So you can import it and use it as library :).

Well, technically, every python package exposes public modules, because private modules are impossible in Python. However, I think the distinction that is meant in the Debian docs (cli vs lib) is very clear and valid. Plus, it feels very natural when installing something. And mercurial is not the only example. This is consistent for all I have checked packages. If it is primarily used inside a language, you prefix it. If it is used standalone, you don't. Why reinvent the wheel if an established system has successfully followed this policy for years?

Indeed, this should be discussed with the conda-forge guys as soon as possible. I agree with you that we should try to be consistent with them. However, I think that Bioconda as a project should have a vote in this decision as well.

**Comment by johanneskoester** [comment]
Actually, apparently because of similar concerns as raised here, there won't be such a prefixing strategy. Instead, conda will support implicit namespaces, as outlined in [this comment](https://github.com/conda-forge/staged-recipes/pull/568#issuecomment-225315370).

**Comment by hainm** [comment]
> there won't be such a prefixing strategy. 

I just feel relieved when reading  this.

I mostly use Python and it's common to `conda install xyz` then `import xyz`

**Comment by jerowe** [comment]
I only just saw this, but my HPC cluster is still on Centos5 for the next few months. We should have a new cluster up and running by September, but I am sure other clusters are still using Centos5. This distinction is especially important for command line packages and packages that must import glibc.

I want to go and read the rest of the thread now and the conversation seems to have evolved.

**Comment by bgruening** [comment]
@johanneskoester @hainm there is a need for treating python packages in the same way as any other package from other programming languages. And it is not so clear how-to proceed. We had lengthy discussions about this in the last conda-forge meetings and I think we have an emerging consensus (imho a very good) one that will serve all our users equally.

What do you think about:
https://gist.github.com/mcg1969/da5aec380d2ed083b79ddcf151ca16f1

**Comment by johanneskoester** [comment]
The proposal is perfect in my opinion. I hope it gets implemented as soon as possible.

**Comment by bgruening** [comment]
@johanneskoester let them know! :)
I also think that gets everything together in a coherent and correct way.

**Comment by johanneskoester** [comment]
I did :-).

**Comment by yesimon** [comment]
At the very least CentOS 5 will be EOL on April 1, 2017 which I think will be safe to switch no matter what. 

I'm excited that conda-forge will have more consistent support for OS X packages due to building with `libc++`. As long as we don't have to deal with system packages then using conda's GCC should be fine, and is probably better because we get updates and better optimizations. System packages don't really belong in bioconda anyways.

**Comment by epruesse** [comment]
outdated
