### ISSUE TITLE
GLIBC error for running dag

### ISSUE THREAD

**Issue by zjhzxjm** [bioconda/bioconda-recipes#1735]
Hi,

when I run the command "snakemake -s Split_QC.snake --dag | dot | display", I got the error as follows:
dot: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/xujm/soft/Anaconda/anaconda3/envs/snakemake/bin/../lib/libgvc.so.6)
dot: /lib64/libm.so.6: version `GLIBC_2.15' not found (required by /home/xujm/soft/Anaconda/anaconda3/envs/snakemake/bin/../lib/libgvc.so.6)
dot: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/xujm/soft/Anaconda/anaconda3/envs/snakemake/bin/../lib/libcgraph.so.6)
dot: /lib64/libm.so.6: version `GLIBC_2.15' not found (required by /home/xujm/soft/Anaconda/anaconda3/envs/snakemake/bin/../lib/./libpathplan.so.4)

On my system ldd --version output is ldd (GNU libc) 2.12, When I try to export higher version, snakemake will crash.

# The author of snakemake reply as follow:

This is a problem with your graphviz installation, that has apparently 
been built on a libc version newer than the one that is available on 
your system. It is not Snakemake related. 

If your graphviz installation comes from bioconda, can you please file 
an issue on the bioconda page? 

Best, 
Johannes

**Comment by johanneskoester** [comment]
Thanks, its me again :-). Which Linux (distro and version) do you use?

**Comment by zjhzxjm** [comment]
Centos 6.5

**Comment by johanneskoester** [comment]
Can you please also provide the output of `conda info graphviz`?

**Comment by bgruening** [comment]
@jeromekelleher I think I have fixed this in: https://github.com/bioconda/bioconda-recipes/compare/bioperl
At least I have seen a similar error.

**Comment by bgruening** [comment]
I have updated graphviz, can you try the new build?

**Comment by zjhzxjm** [comment]
Thanks. It works, but gets another error: Error: Could not find/open font
