### ISSUE TITLE
virsorter: perl libraries/modules not found after conda installation but are located in different path

### ISSUE THREAD

**Issue by papanikos** [bioconda/bioconda-recipes#17503]
Installing VirSorter through conda didn't work initially for me, so I am working on a PR [here](https://github.com/papanikos/bioconda-recipes/tree/update_virsorter). I have reached a point where I don't know how to proceed and goes beyond my basic understanding of how the packaging details work.

Building the package with my changes above and installing locally, addresses the issues I encountered. Now it has become a matter of pointing `perl` to the locations where some required libraries are located.

The related error I get is
```
Can't locate Bio/Seq.pm in @INC \
(you may need to install the Bio::Seq module) (@INC contains:\
 /home/nikos/miniconda3/envs/vs_local/lib/site_perl/5.26.2/x86_64-linux-thread-multi \
 /home/nikos/miniconda3/envs/vs_local/lib/site_perl/5.26.2 \
/home/nikos/miniconda3/envs/vs_local/lib/5.26.2/x86_64-linux-thread-multi \
/home/nikos/miniconda3/envs/vs_local/lib/5.26.2 \
.)
```
after creating a new environment with virsorter and its dependencies only:
```
conda create -n vs_local -c ${CONDA_PREFIX}/conda-bld virsorter
```
The `Bio::Seq` module along with some other dependencies is located at 
```
/home/nikos/miniconda3/envs/vs_local/lib/perl5/site_perl/5.22.0
```
which is not by default in the `@INC` variable -and is a different version for that matter.

To fix this, it can be manually included after installation e.g. with the `$PERL5LIB` environmental variable and it works, but this beats the purpose of installing through conda.

I guess the question is how to handle this? Any input appreciated.

**Comment by wclose** [comment]
Hi @papanikos, I've been working on getting the package working properly and I think I've sorted out all the problems so go ahead and try the latest build. You'll want to make sure it's build virsorter-1.0.5-pl526h516909a_3 if on linux or virsorter-1.0.5-pl526h01d97ff_3 if on osx when doing `conda install`. During the installation, you may receive some ClobberError messages but it should be ok. Let me know how it goes for you. Thanks!

**Comment by bgruening** [comment]
Thanks @papanikos for reporting and @wclose for the fix.
