### ISSUE TITLE
Bpipe for recipe is the wrong version?

### ISSUE THREAD

**Issue by dbampalikis** [bioconda/bioconda-recipes#17545]
The version of bpipe https://bioconda.github.io/recipes/bpipe/README.html is supposed to be 0.9.9.2-0 but the yaml file https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bpipe/meta.yaml defines it as 0.9.9.6. My guess is that there is typo on the README file.

And one relevant question, are you planning to release the bpipe 0.9.9.7 version too?

Thanks!

**Comment by druvus** [comment]
An updated PR is found at #17765

**Comment by druvus** [comment]
bpipe 0.9.9.7 is now available so closing.  Please reopen if you think it is still an issue.
