### ISSUE TITLE
Java execution in CircleCI docker image misses a dependancy

### ISSUE THREAD

**Issue by blinard-BIOINFO** [bioconda/bioconda-recipes#17566]
The minimal docker image used by conda-utils to run tests is based on a minimal CentOS image.
In this image, any application based on java openjdk >=8 and requiring basal graphical libraries will work fine ONLY after explicitely installing this package in the docker image:
`sudo yum install dejavu-sans-fonts
`
Putting java >8 as a dependancy in the recipe does not solve the problem because it is the headless version of java that is installed in the conda envirnement, and it misses some dependancies.

Possible solutions:
a) set dejavu-sans-fonts as a dependency in openjdk recipes.
b) add this font library in your docker image used for tests in your contiinuous integration engine.

If a), I'm happy to do the modification but I would say that b) would save lots of time to anyone building a recipe for recent java versions.

**What bioconda maintainers would suggest ?**

This was really hard to understand and I raise the issue here hopping this will save the 2 days I used to understand the process of integration of bioconda and making my java program pass the linus tests ... so below, I details how did I found the issue in case it could be useful to someone else.

What helped me a lot:
https://wiki.jenkins.io/display/JENKINS/Jenkins+got+java.awt.headless+problem

Finding this required that I understand:

1) how to run interactively the docker image launched by conda-utils , e.g.
```
docker run --entrypoint "/bin/sh" -it --net host -v /tmp/tmpluo5v4hi/build_script.bash:/opt/build_script.bash -v /tmp/miniconda/miniconda/conda-bld/:/opt/host-conda-bld -v /home/ben/bioconda-recipes/recipes/rappas:/opt/recipe -e LC_MEASUREMENT=fr_FR.UTF-8 -e LC_PAPER=fr_FR.UTF-8 -e LC_MONETARY=fr_FR.UTF-8 -e LANG=en_GB.UTF-8 -e LC_NAME=fr_FR.UTF-8 -e LC_ADDRESS=fr_FR.UTF-8 -e LC_NUMERIC=fr_FR.UTF-8 -e LC_TELEPHONE=fr_FR.UTF-8 -e LC_IDENTIFICATION=fr_FR.UTF-8 -e LC_TIME=fr_FR.UTF-8 -e HOST_USER_ID=1000 bioconda/bioconda-utils-build-env:latest
```

2) that running interactively this minimal linux image REQUIRES to change the prefix :
```
#run docker to generate the bug, but do not stop it
docker run --entrypoint "/bin/sh" -it [...etc..]
#enter this docker to access the exact environement in which the bug occured
docker exec -it [container_id] bash
```
3) which conda environment is setup by bash /opt/build_script.bash, e.g.
```
conda activate /opt/conda/conda-bld/rappas_1568911290112/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
```

4) on which system is based this docker generated by conda-utils:
```
cat /etc/system-release
```

I may be wrong, but none of this is documented in conda tutorials for helping to debug packages.
Adding this example in the tutorial may be very helpful !

**Comment by bgruening** [comment]
> The minimal docker image used by conda-utils to run tests is based on a minimal CentOS image.

That is not true. Is is busybox. Can you please check which version of openjdk you get.
Please have a look at https://github.com/bioconda/bioconda-recipes/issues/5026 and related issue. I hope you just got the wrong openjdk. The correct solution is to add the font to openjdk, the conda-forge recipe. If this is still missing please open an issue against openjdk.

Something like this is pretty much what is happening after the build finishes successfully:

https://galaxy-lib.readthedocs.io/en/latest/topics/mulled.html#build-test-and-push-a-conda-forge-package-to-biocontainers

Thanks!
