### ISSUE TITLE
Missing monocle3.dylib for `r-monocle3` recipe

### ISSUE THREAD

**Issue by mjsteinbaugh** [bioconda/bioconda-recipes#17605]
Users are reporting an issue with `monocle3.dylib` for `r-monocle3`:
https://github.com/cole-trapnell-lab/monocle3/issues/218

I'm taking a look to see if we can fix this today.

**Comment by mjsteinbaugh** [comment]
See recent pull for v0.2 #17561

**Comment by mjsteinbaugh** [comment]
Can confirm that I'm now seeing this on macOS with the v0.2 release:

```
Error: package or namespace load failed for ‘monocle3’ in library.dynam(lib, package, package.lib):
 shared object ‘monocle3.dylib’ not found
```

**Comment by bgruening** [comment]
@mjsteinbaugh that is interesting. monocle3 is a noarch package in bioconda, means that we assume it is a R only package.

Since it is not compiled this seems correct. What does a dylib do in this package?
You can try to remove this line https://github.com/bioconda/bioconda-recipes/blob/master/recipes/r-monocle3/meta.yaml#L14 but really this seems wired.

Do you know if this package as some architecture-specific dependencies?

**Comment by mjsteinbaugh** [comment]
@bgruening I didn't change anything with the recipe but it seems to be working for me now. I installed the recipe clean on a virtual machine this morning and the package loads as expected. I think this issue is safe to close for the time being, but I'll keep an eye out to see if this dylib issue pops up again.

**Comment by nh3** [comment]
Sorry to re-open the issue. monocle3 doesn't seem to be an R only package: https://github.com/cole-trapnell-lab/monocle3/tree/master/src. Currently installing the conda recipe creates a `monocle.so` under `R/library/monocle3/libs/` for both linux and macosx, which causes problem in the latter environment:
`Error: package or namespace load failed for ‘monocle3’ in library.dynam(lib, package, package.lib):
 shared object ‘monocle3.dylib’ not found`

**Comment by nh3** [comment]
#74987 doesn't seem to have actually built and tested the recipe on macos: https://circleci.com/gh/bioconda/bioconda-recipes/74987?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

```
09:49:53 BIOCONDA INFO Nothing to be done for recipe recipes/r-monocle3
09:49:53 BIOCONDA INFO BUILD SUMMARY: successfully built 0 of 1 recipes
```

**Comment by mjsteinbaugh** [comment]
Somewhat unrelated, but the current version of monocle3 also won't build because of a dependency on Matrix.utils, which has been removed from CRAN. I'll take a look, but this might not be an easy fix on macOS for the time being. The recipe does currently work on Linux though.

**Comment by nh3** [comment]
Yes it's due to r-matrix somehow requires openblas v3.7 where conda currently install v3.8 by default. @dpryan79 fixed it immediately after your report: https://github.com/conda-forge/r-matrix-feedstock/pull/14. What speed!

**Comment by nh3** [comment]
Still, recipe for `r-monocle3` needs fix (possibly by removing the `noarch: generic` line).

**Comment by dpryan79** [comment]
Now that #20604 has been merged in can this be closed?

**Comment by mjsteinbaugh** [comment]
I think this is safe to close.
