### ISSUE TITLE
SHAPEIT license

### ISSUE THREAD

**Issue by marcelm** [bioconda/bioconda-recipes#1763]
I would like to add a recipe for SHAPEIT, which is free for academic use. The web site states, however:
> A specific license must be obtained for any commercial or for-profit organization or for any web-diffusion purpose.

I do not know what a "web-diffusion purpose" is, but to be on the safe side, I assume it includes making a bioconda package available.

I have therefore asked the license holders Prof. Zagury and Prof. Marchini whether they would agree to include SHAPEIT into bioconda. I will record their decision in this issue, in order to prevent that others bother them with the same request.

**Comment by bgruening** [comment]
Hi @marcelm,

please have a look at this section: https://github.com/bioconda/bioconda-recipes/blob/master/GUIDELINES.md#other-examples
You could do something similar for the gatk package.

Thanks to @tomkinsc for updating this document!

**Comment by marcelm** [comment]
Thanks, that is a possibility if the answer is negative - but it’s worth asking.

**Comment by bgruening** [comment]
Definitely! Thanks for doing so, hopefully it will be positive!

**Comment by marcelm** [comment]
Jonathan Marchini has thanked for the offer, but has declined it. 

I will myself not create a GATK-like recipe.

**Comment by bgruening** [comment]
This is so sad :(
