### ISSUE TITLE
InvalidArchiveError - FastQC

### ISSUE THREAD

**Issue by windysky** [bioconda/bioconda-recipes#17659]
Hi, 
I am trying to install FastQC using conda but just getting the following error. I am using the latest version of Anaconda with all updated on a Windows machine.

InvalidArchiveError("Error with archive C:\\Users\\________\\AppData\\Local\\Con
tinuum\\anaconda3\\pkgs\\fastqc-0.11.2-1.tar.bz2.  You probably need to delete a
nd re-download or re-create this file.  Message from libarchive was:\n\nCan't cr
eate '\\\\?\\C:\\Users\\________\\AppData\\Local\\Continuum\\anaconda3\\pkgs\\fa
stqc-0.11.2-1\\bin\\fastqc' (errno=22, retcode=-25, archive_p=73133120)")

Thanks

**Comment by druvus** [comment]
@windysky bioconda only builds for linux and osx. A possible solution for you could be to[ run linux within W10](https://github.com/kapsakcj/win10-linux-conda-how-to).
