### ISSUE TITLE
Metaphlan2

### ISSUE THREAD

**Issue by MichWeb75** [bioconda/bioconda-recipes#17693]
There is a version issue for samtools 0.1.19 vs 1.19 is the same
```
UnsatisfiableError: The following specifications were found to be in conflict:

  - bioconda/linux-64::samtools==1.9=h10a08f8_12
  - metaphlan2=2.9.21 -> samtools[version='>=0.1.19,<1.0']
```

**Comment by micknudsen** [comment]
I am not able to reproduce this. Just tested it on a Mac, and these two packages are installed without any problems:

```
samtools           bioconda/osx-64::samtools-0.1.19-ha6d3ead_6
metaphlan2         bioconda/noarch::metaphlan2-2.9.21-py_0
```

**Comment by MichWeb75** [comment]
I solved the issue by removing all channels from .condarc. Apparently, the channel priority causes this problem, when conda tries to update existing packages.
