### ISSUE TITLE
certifi and openssl

### ISSUE THREAD

**Issue by MichWeb75** [bioconda/bioconda-recipes#17752]
Every time I install a new package with conda, it downloads packages **certifi** and **openssl** in various versions. How can I prevent conda from doing this , is this necessary for the update process ?

**Comment by bgruening** [comment]
Have you updated your conda? Maybe reinstalling Miniconda?
You might also try to ask in this channel for help as it is more conda in general: https://gitter.im/conda-forge/conda-forge.github.io
