### ISSUE TITLE
Install DFAST with no internet connection

### ISSUE THREAD

**Issue by standage** [bioconda/bioconda-recipes#17982]
I am trying to install DFAST on a system with no internet connection. The system has a local mirror of anaconda, conda-forge, and bioconda that is updated frequently. The initial DFAST install/build succeeds, but the post-link fails since this step attempts to connect to the Internet to download large databases required by DFAST.

Is there a way to disable the post-link script? I've downloaded the databases before, and I can manually copy them to the `dfast_core/db/` for each new DFAST install. In any case, the [conda docs](https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html) suggests that this is not what the post link script was intended for:

> Post-link and pre-unlink scripts should:
>
> - Be avoided whenever possible.
> - Not touch anything other than the files being installed.
> - Not write anything to stdout or stderr, unless an error occurs.
> - Not depend on any installed or to-be-installed conda packages.
> - Depend only on simple system tools such as `rm`, `cp`, `mv` and `ln`.

cc @nigyta

**Comment by nigyta** [comment]
@standage 
Thank you for letting me know. I didn't know the document for pre- and post link scripts.
So I should delete the post-link script and move the procedure described in the script to build.sh

Could you wait a few more days until I fix this issue?

Thanks.

**Comment by standage** [comment]
Thanks for your response @nigyta, and of course, take the time you need.

Moving the `file_downloader.py` command to the `build.sh` script is one option. This would bundle the databases in the DFAST conda tarball, resulting in a very large install payload. Prokka uses a similar approach—Torsten has the DB files in the Prokka repo itself, and the resulting payload is about 200 Mb. If we were to bundle the DFAST DBs in the conda tarball, I guess it will be 2 Gb - 3Gb in size.

An alternative is to require the user to run the `file_downloader.py` command after installation. The downside is that DFAST would not be ready to run right away after `conda install dfast`. Perhaps a compromise would be to give the user the ability to disable `file_downloader.py` during `conda install` and manage the databases manually. I don't know the mechanics of the bioconda build system to know if this is possible though.

**Comment by dpryan79** [comment]
To my knowledge the only good way to do this would be to make a second DFAST package (presumably in a subdirectory of the current recipe) with a "track_feature" set. If the post-link script were removed from that then that package could be installed correctly if requested, but anyone just requesting DFAST would get the normal post-install actions.

Regarding packaging the databases in, we really don't want to do that. Our 6000+ packages create just as many docker containers and we don't want to push our luck too much with all the free hosting people are providing us.

**Comment by nigyta** [comment]
Dear @standage and @dpryan79 
Thank you for the comments and I'm sorry for the late response.

I'm going to update the package to remove reference database.

**Comment by nigyta** [comment]
@standage
I have updated the DFAST recipe.
Downloading of the reference database is done during build process, and post-link script was removed. To reduce the file size, index files of the database are not included  in the package, but they are automatically generated at the first running time. 
I think it can now run on a machine without internet connection.

**Comment by standage** [comment]
Hi @nigyta! I'm at a conference at the moment, but I will give this a try as soon as I have a chance. Thanks for the response, and I'll comment again early next week!

**Comment by standage** [comment]
Hello again @nigyta! I've added DFAST v1.2.4 to our local bioconda mirror, and installation seems to work well. Thanks for this update!
