### ISSUE TITLE
Errors of popularity (anaconda.org over capacity)

### ISSUE THREAD

**Issue by tomkinsc** [bioconda/bioconda-recipes#1808]
We had an automated test on Travis fail today while installing a conda package, because the anaconda.org server was at capacity:

`Fetching package metadata .......Error: HTTPError: 503 Server Error: Service Unavailable: Back-end server is at capacity for url: https://conda.anaconda.org/bioconda/linux-64/repodata.json.bz2: https://conda.anaconda.org/bioconda/linux-64/`

This has happened a few times now. Do we have any indication of whether anaconda.org is rate-limited by account/channel, or whether their limits are global? It's a bit surprising they don't have a CDN in front of the servers hosting packages, especially for channels on their commercial plans.

**Comment by daler** [comment]
I've been getting similar errors, but sometimes for the R channel as well. Most recently about 5 mins ago. So presumably it's not just our channel . . .

**Comment by johanneskoester** [comment]
I think the conda-forge people have the same problem, see [here](https://conda-forge.hackpad.com/conda-forge-meetings-2YkV96cvxPG).
They are discussing caching of packages, but I would say this problem should be solved on continuum site. There is a meeting tomorrow(see the link above). Can anybody join that and ask about the problem? @bgruening are you already planning to join the meeting?

**Comment by bgruening** [comment]
@johanneskoester I will join. If you have anything else to discuss, vote fore let me know.

**Comment by tomkinsc** [comment]
[According to](https://github.com/conda/conda/issues/2816#issuecomment-227879776) @kalefranz, Continuum is aware of the problem and working to resolve the issue. Closing this.
