### ISSUE TITLE
Needed!?! auto test failure if tool is blacklisted..

### ISSUE THREAD

**Issue by martin-raden** [bioconda/bioconda-recipes#18270]
I again ran into the problem that I found a bioconda package (namely `dialign-tx`) not working on my machine when taken from bioconda and tried to fix the conda recipe...

All tests reported green, so I thought the package built fine.. 

**BUT** it was blacklisted, so eventually **not built nor tested at all**

### Would it be possible to add to the test pipeline another check (like linting), which fails if the tool is blacklisted?

This would very much ease identifying such cases...

just a suggestion, hope it helps.

Best,
Martin

**Comment by martin-raden** [comment]
ping @bioconda/build-system @bioconda/core

**Comment by dpryan79** [comment]
Yes, this is much needed. Can you make a feature request on bioconda-utils? This should really be a lint.
