### ISSUE TITLE
package never uploaded to channel after PR merge

### ISSUE THREAD

**Issue by pbasting** [bioconda/bioconda-recipes#18299]
Hi bioconda members,

I made a PR (https://github.com/bioconda/bioconda-recipes/pull/18219) for a new recipe (isescan) which was merged a few days ago, but I still haven't been able to find the package on https://anaconda.org/ or download it using `conda install`. I'm guessing it usually doesn't take this long to upload to the channel, so is it possible that the upload failed? If so, what is the best course of action to try again?

Thanks for the help,

-Preston

**Comment by druvus** [comment]
@pbasting according the log the package was never build before merging even if showed it passed. I opened a new PR #18304 to see if I could solve the issue.

**Comment by druvus** [comment]
@pbasting building of the package is failing. Maybe you could take another look as you originally added it. Did it build locally for you?

**Comment by pbasting** [comment]
@druvus yes it was building locally prior to the initial PR but the recipe has been modified during review. I'll try building locally with the current recipe to see if I can figure out what is going wrong.

**Comment by druvus** [comment]
Package is now available for download, so I am closing.
