### ISSUE TITLE
New build without increasing build number

### ISSUE THREAD

**Issue by micknudsen** [bioconda/bioconda-recipes#18318]
Hi,

I just noticed a new `gatk4` in the bioconda channel,

`gatk4                        4.1.4.0               1  bioconda`

and I was curious to figure out what had changed. However, when I check the corresponding `meta.yaml` file, it is still at build `0`.

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gatk4/meta.yaml

How is that possible?

**Comment by micknudsen** [comment]
The build number has new been updated in the `meta.yaml` file. I am still wondering, though, how the build `1` could be a available in the `bioconda` channel before `meta.yaml` was updated.

**Comment by dpryan79** [comment]
Likely it got updated in the bulk branch, which also uploads to the conda cloud.
