### ISSUE TITLE
UMI-tools python version

### ISSUE THREAD

**Issue by IanSudbery** [bioconda/bioconda-recipes#18324]
Dear Maintainers,

The latest version of UMI-tools is python>=3.5 only, but bioconda is still building versions (that won't work) for python 2.7. Is it possible to change this? Is this something we should change on our end.

Thanks for all your hard work!

Ian

**Comment by npavlovikj** [comment]
Hi @IanSudbery ,

Looks like the current recipe is not using pinned version of Python, and thus both Python 2 and Python 3 are used, https://github.com/bioconda/bioconda-recipes/blob/ba22416e4dda1f4bc87e31fb8579b36191460b00/recipes/umi_tools/meta.yaml.

If you feel comfortable with it, you can modify the bioconda recipe by setting `python >=3.5` in both `run` and `host` sub-sections under `requirements` and open PR with the change.

**Comment by npavlovikj** [comment]
I think you can also specify `python >=3.5` in the setup.py script (something like `python_requires='>=3.5',`) to avoid future inconsistencies, but since the recipe is already in bioconda, that would not affect/update the current recipe unless the recipe itself is modified as I mentioned earlier.

**Comment by IanSudbery** [comment]
I have opened a PR (#18420) and am waiting for tests to complete.
