### ISSUE TITLE
fusioncatcher dependencies do not match the git origin

### ISSUE THREAD

**Issue by gilfreund** [bioconda/bioconda-recipes#18338]
In fusioncatcher 1.10 there seems to be some missing dependencies and an incorrect reference
* star should be star=2.7.0f
* bbmap should bbmap=38.44
(see: https://github.com/ndaniel/fusioncatcher/blob/2b7753c99e41afcafd856e7497f25e303829cf7f/doc/manual.md)

Also, in the `download-human-db.sh` the current DB version is v95 (see https://sourceforge.net/projects/fusioncatcher/files/data/)

**Comment by PertuyF** [comment]
Looks like [the recipe](https://github.com/bioconda/bioconda-recipes/blame/master/recipes/fusioncatcher/) was not fully updated during last version bump. Please feel free to submit a new PR.
Versions should be changes in `meta.yaml`, but db version should be changed in a separate script.
