### ISSUE TITLE
DREME tool from MEME suite uses Python 2 print statement in Python 3 environment

### ISSUE THREAD

**Issue by jma1991** [bioconda/bioconda-recipes#1840]
The DREME tool from the MEME suite uses Python 2 print statements. This means when you try and run it in a Python 3 environment with Anaconda you get an error.

```
> conda install meme
> dreme
File "/home/jashmore/anaconda3/bin/dreme", line 759
    print "Finding secondary RE in left flank..."
```

**Comment by rvalieris** [comment]
meme doesn't support python3, the new update now only builds on python2.
to make sure you are using python2 use conda environment: `conda create -n py2 python=2 meme`

**Comment by rfarouni** [comment]
@rvalieris  But on the website, it says that Python3 is supported. 

http://meme-suite.org/doc/install.html?man_type=web#prereq_python

Are there any other Python 2 dependencies that prevent building the recipe for Python 3?

**Comment by qicaibiology** [comment]
> hi @rfarouni, yeah looks like they added support recently, it wasn't there on the version I updated.
> 
> I can't look into this right now but feel free to work on it.

Hi @rvalieris I still have the same problem in MEME 5.0.5. my MEME works but when I type dreme it shows:
```
File "/home/caiqi/anaconda3/bin/dreme", line 765
    print "Finding secondary RE in left flank..."
                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Finding secondary RE in left flank...")?
```

I work on anaconda3
