### ISSUE TITLE
Guidelines for which recipes should be included

### ISSUE THREAD

**Issue by ostrokach** [bioconda/bioconda-recipes#185]
Are there any guidelines for which programs should be included here?

For example, one of our pipelines uses `knot` and `msms`, but I'm wondering whether anyone else will ever be interested in those tools, or if adding them will just clutter things. 

Similarly with `tmux` and `byobu`. I always have those running on HPC cluster nodes that I use, and I think they would be relevant to other bioinformatics people, but they're not *really* bioinformatics tools.

And there are also some packages with many many dependencies, including some of the packages from [conda/conda-recipes](https://github.com/conda/conda-recipes) (`graph-tool` is a [particular nutcase](https://github.com/ostrokach/conda-recipes-extra/tree/master/graph-tool) in this respect). Adding them could eventually get us close to the  3 GB storage limit for free accounts on anaconda.org.

**Comment by johanneskoester** [comment]
So, tmux and byobu are fine for me, they are really useful to have on clusters that are not that well maintained. I think for now we can package also tools that are rarely used. We should have some minimum quality requirements maybe. So a tool that crashes all the time is maybe not a good candidate for bioconda. I think all the graph-tool dependencies are available in the default anaconda channel, so it won't add a lot.

In general, we should of course think twice if a package needs a lot of space. We should maybe discuss from case to case.

**Comment by bgruening** [comment]
Since a few weeks we are depending on conda-forge, which offers many system level packages. So I think a loosely defined guideline is to store scientific packages in bioconda and system level packages in conda-forge.

Please feel free to reopen if you feel we should make this more clear in the readme file.
