### ISSUE TITLE
Problem when running rMATS; shared libraries missing; propably the libgsl.so.0 issue

### ISSUE THREAD

**Issue by DrDentJulius** [bioconda/bioconda-recipes#18648]
Hello,
I'm trying to set up rMATS using conda/bioconda and test it with the data provided by the developer.
While the first part seems to run smoothly, I get an error when entering the statistical part.

I'm running Ubuntu 18.04 LTS with miniconda3
Everything is freshly updated and upgraded to it's latest versions.

I found several issues dealing with this problem on [biostar](https://www.biostars.org/p/336864/) and the dedicated [google group](https://groups.google.com/forum/#!topic/rmats-user-group/FOrCUW8IvtY).

Unfortunately I'm not able to adapt the solution to my needs.
I already tried to copy/rename the latest version of libgsl (libgsl.so.23) as libgsl.so.0 in all paths that seemed reasonable for me ( /usr/lib/x86_64-linux-gnu/ ; ~/miniconda3/envs/splice/x86_64-linux-gnu/ ;  ~/miniconda3/envs/splice/x86_64-linux-gnu/lib/ )
 

Here is my code + the ouput:

`python ~/miniconda3/envs/splice/rMATS/rmats.py --b1 /media/julius/HD-PZFU3/TestData/b1.txt --b2 /media/julius/HD-PZFU3/TestData/b2.txt --gtf /media/julius/HD-PZFU3/backup/Homo_sapiens.GRCh38.83.gtf --od /media/julius/HD-PZFU3/TestData/rMATS_test/ -t paired --readLength 50 --cstat 0.0001 --libType fr-unstranded --nthread 3`

There are 60675 distinct gene ID in the gtf file
There are 199184 distinct transcript ID in the gtf file
There are 38917 one-transcript genes in the gtf file
There are 1176808 exons in the gtf file
There are 27376 one-exon transcripts in the gtf file
There are 25218 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 3.282802
Average number of exons per transcript is 5.908145
Average number of exons per transcript excluding one-exon tx is 6.690212
Average number of gene per geneGroup is 7.629187

==========
Done processing each gene from dictionary to compile AS events
Found 38772 exon skipping events
Found 2465 exon MX events
Found 12850 alt SS events
There are 7883 alt 3 SS events and 4967 alt 5 SS events.
Found 5834 RI events
==========

Running the statistical part.
/home/julius/miniconda3/envs/splice/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/julius/miniconda3/envs/splice/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpLaYjCl/JC_SE/rMATS_result_P-V.txt'
paste: /tmp/tmpLaYjCl/JC_SE/rMATS_result_FDR.txt: Datei oder Verzeichnis nicht gefunden
/home/julius/miniconda3/envs/splice/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/julius/miniconda3/envs/splice/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpLaYjCl/JCEC_SE/rMATS_result_P-V.txt'
paste: /tmp/tmpLaYjCl/JCEC_SE/rMATS_result_FDR.txt: Datei oder Verzeichnis nicht gefunden
/home/julius/miniconda3/envs/splice/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/julius/miniconda3/envs/splice/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpLaYjCl/JC_MXE/rMATS_result_P-V.txt'
paste: /tmp/tmpLaYjCl/JC_MXE/rMATS_result_FDR.txt: Datei oder Verzeichnis nicht gefunden
/home/julius/miniconda3/envs/splice/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/julius/miniconda3/envs/splice/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpLaYjCl/JCEC_MXE/rMATS_result_P-V.txt'
paste: /tmp/tmpLaYjCl/JCEC_MXE/rMATS_result_FDR.txt: Datei oder Verzeichnis nicht gefunden
/home/julius/miniconda3/envs/splice/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/julius/miniconda3/envs/splice/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpLaYjCl/JC_A3SS/rMATS_result_P-V.txt'
paste: /tmp/tmpLaYjCl/JC_A3SS/rMATS_result_FDR.txt: Datei oder Verzeichnis nicht gefunden
/home/julius/miniconda3/envs/splice/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/julius/miniconda3/envs/splice/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpLaYjCl/JCEC_A3SS/rMATS_result_P-V.txt'
paste: /tmp/tmpLaYjCl/JCEC_A3SS/rMATS_result_FDR.txt: Datei oder Verzeichnis nicht gefunden
/home/julius/miniconda3/envs/splice/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/julius/miniconda3/envs/splice/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpLaYjCl/JC_A5SS/rMATS_result_P-V.txt'
paste: /tmp/tmpLaYjCl/JC_A5SS/rMATS_result_FDR.txt: Datei oder Verzeichnis nicht gefunden
/home/julius/miniconda3/envs/splice/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/julius/miniconda3/envs/splice/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpLaYjCl/JCEC_A5SS/rMATS_result_P-V.txt'
paste: /tmp/tmpLaYjCl/JCEC_A5SS/rMATS_result_FDR.txt: Datei oder Verzeichnis nicht gefunden
/home/julius/miniconda3/envs/splice/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/julius/miniconda3/envs/splice/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpLaYjCl/JC_RI/rMATS_result_P-V.txt'
paste: /tmp/tmpLaYjCl/JC_RI/rMATS_result_FDR.txt: Datei oder Verzeichnis nicht gefunden
/home/julius/miniconda3/envs/splice/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/julius/miniconda3/envs/splice/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpLaYjCl/JCEC_RI/rMATS_result_P-V.txt'
paste: /tmp/tmpLaYjCl/JCEC_RI/rMATS_result_FDR.txt: Datei oder Verzeichnis nicht gefunden
The statistical part is done.
Done.

If I've missed a detail you might need for better understanding my problem please let me know!

Thanks in advance!
Julius

**Comment by dpryan79** [comment]
Can you post the output of `conda list`? Unfortunately rMATs isn't open source, so it's rather difficult to continue supporting it. In this particular case, it needs an old version of GSL. In the recipe we have this pinned to 1.16, but perhaps conda installed a different version. If that's the case, try manually installing `gsl==1.16` in that environment and see if that fixes things.

**Comment by DrDentJulius** [comment]
Thanks for the quick response!

Here is the output:
`conda list`
> # packages in environment at /home/julius/miniconda3/envs/splice:
> #
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                        main  
> binutils_impl_linux-64    2.31.1               h6176602_1    anaconda
> binutils_linux-64         2.31.1               h6176602_8    anaconda
> blas                      2.14                   openblas    conda-forge
> bwa                       0.7.17               hed695b0_6    bioconda
> ca-certificates           2019.9.11            hecc5488_0    conda-forge
> certifi                   2019.9.11                py27_0    conda-forge
> gcc_impl_linux-64         7.3.0                habb00fd_1    anaconda
> gcc_linux-64              7.3.0                h553295d_8    anaconda
> gfortran_impl_linux-64    7.3.0                hdf63c60_1    anaconda
> gfortran_linux-64         7.3.0                h553295d_8    anaconda
> gsl                       2.6                  h294904e_0    conda-forge
> libblas                   3.8.0               14_openblas    conda-forge
> libcblas                  3.8.0               14_openblas    conda-forge
> libffi                    3.2.1             he1b5a44_1006    conda-forge
> libgcc-ng                 9.1.0                hdf63c60_0  
> libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
> liblapack                 3.8.0               14_openblas    conda-forge
> liblapacke                3.8.0               14_openblas    conda-forge
> libopenblas               0.3.7                h6e990d7_3    conda-forge
> libstdcxx-ng              9.1.0                hdf63c60_0  
> ncurses                   6.1               hf484d3e_1002    conda-forge
> numpy                     1.16.5           py27h95a1406_0    conda-forge
> openssl                   1.1.1d               h516909a_0    conda-forge
> perl                      5.26.2            h516909a_1006    conda-forge
> pip                       19.3.1                   py27_0    conda-forge
> python                    2.7.15            h5a48372_1009    conda-forge
> readline                  8.0                  hf8c457e_0    conda-forge
> rmats                     4.0.2            py27h24bf2e0_2    bioconda
> scipy                     1.2.1            py27h921218d_2    conda-forge
> setuptools                41.6.0                   py27_1    conda-forge
> sqlite                    3.30.1               hcee41ef_0    conda-forge
> star                      2.7.3a                        0    bioconda
> tk                        8.6.9             hed695b0_1003    conda-forge
> wheel                     0.33.6                   py27_0    conda-forge
> zlib                      1.2.11            h516909a_1006    conda-forge

I also manually installed gsl 1.16 as you suggested, but unfortunately it didn't solve the issue.

**Comment by dpryan79** [comment]
When I create a new environment this works correctly, perhaps you have something already installed in that env that conflicts.

**Comment by DrDentJulius** [comment]
Well I've played around the whole thing and now managed to solve it.
It was a different problem which could easily be solved by running:
`apt-get install libgfortran3 `

Thanks for your help!
I guess I'd have faced that gsl issue sooner or later, but now I'm prepared.
