### ISSUE TITLE
Recommendations for dealing with a pre release?

### ISSUE THREAD

**Issue by luizirber** [bioconda/bioconda-recipes#18659]
Hi,

sourmash is in the process of merging a PR replacing C++ with Rust. We will signal this to user by releasing version 3.0, but we want to do release candidates first.

For PyPI that doesn't break users installations, since you need to use `--pre` to get pre releases.

With conda it's more complicated: since we recommend installing using `conda install -c conda-forge -c bioconda sourmash` it will pick up whatever is the newest version (in this case, `3.0.0-rc1` or something similar). At the same time, we would like to update the bioconda recipe to be able to build the new extension code, but don't want to subject users to a (possibly) broken installation while we figure out quirks in the process.

My question: is it OK to create a temporary `sourmash3` recipe, and later remove it? This way we can test release candidates before commiting to the final `sourmash==3.0.0` release. Or is there any other option that will (by default) keep installing the stable `2.x` version instead of a release candidate?

/cc @ctb

**Comment by dpryan79** [comment]
In theory we could manually change the label on the package to "prerelease" after uploading, but for this usage I'd suggest just creating your own conda channel and uploading release candidates there. That's free and all you need to do is create an account on anaconda.org. The simplest way to get packages built is to simply run `bioconda-utils build` locally. If you do that from within a branch of bioconda-recipes you can modify the conda recipe as you go and directly make a PR from it once you're ready to tag a release.

**Comment by luizirber** [comment]
thanks @dpryan79, I'll try that and report back =]
