### ISSUE TITLE
osx builds on travis

### ISSUE THREAD

**Issue by jerowe** [bioconda/bioconda-recipes#1876]
Are stopping. Anyone know why? I got an email about it this morning. I just restarted my builds to see if it was a temporary problem.

Why do things need to build with osx? I always specify skipping those...

**Comment by bgruening** [comment]
@jerowe we want to have as many packages as possible build on OS-X as we want to support both OS-X. Maybe in the future even Windows.

OS-X builds are a little bit flaky at the moment.

**Comment by jerowe** [comment]
@bgruening, I restarted a few builds last night and they completed, so I'm restarting the others that failed.

Is there a limit to the number of pull requests I should submit at a time? 

That's fine, but I have no experience with OSX. Whats the best way to go about making sure my packages build? Just build them and see? Are there any particular tricks I need to know for OSX?

Windows? Whyyyyyyyyyy?
