### ISSUE TITLE
r-nabor is broken

### ISSUE THREAD

**Issue by lucapinello** [bioconda/bioconda-recipes#18900]
It seems Bulk #18362 broke this package on OSX. @huidongchen  can you please report the log here?

**Comment by dpryan79** [comment]
Yup, the recipe specifies a generic package, but it's compiled so we need platform-specific builds.

**Comment by dpryan79** [comment]
Actually, that should be migrated to conda-forge.

**Comment by lucapinello** [comment]
Thanks @dpryan79. Is there a simple script to create recipes for R packages for conda-forge? Or are you creating this recipe on conda-forge?

**Comment by dpryan79** [comment]
If you can clone this repo that's the easiest way to generate the recipe for conda-forge: https://github.com/bgruening/conda_r_skeleton_helper

**Comment by mfansler** [comment]
This was successfully transferred.

PR: https://github.com/conda-forge/staged-recipes/pull/12203
Feedstock: https://github.com/conda-forge/r-nabor-feedstock
