### ISSUE TITLE
HiSAT2 with Python 3k

### ISSUE THREAD

**Issue by ewels** [bioconda/bioconda-recipes#18911]
Hi all,

https://bioconda.github.io/contributor/guidelines.html states that "packaging is hard" - I agree! 😆 But one of the examples is:

> hisat2 runs 2to3 to make it Python 3 compatible, and copies over individual scripts to the bin dir

Sure enough, the build recipe does run `2to3`: https://github.com/bioconda/bioconda-recipes/blob/90620569f00fa786b85d272507445a229748272d/recipes/hisat2/build.sh#L5-L20

However, the meta.yml file then skips python 3k builds: https://github.com/bioconda/bioconda-recipes/blob/90620569f00fa786b85d272507445a229748272d/recipes/hisat2/meta.yaml#L13

So despite making the code python 3 compatible, HiSAT2 ends up being available for Python 2 only.

This skipped build was added by @pvanheus and  @bgruening last year in https://github.com/bioconda/bioconda-recipes/pull/9973 - can you guys remember why? Do you think it's possible to add python 3 support back again?

Phil

**Comment by bgruening** [comment]
@pvanheus can you please comment here?

**Comment by ewels** [comment]
What’s the best course of action here? Shall I prep a PR enabling Py3k builds again?

**Comment by ewels** [comment]
I updated the `build.sh` file to run `2to3` conversion on all HiSAT2 python scripts (several were missing) and allowed it to build for all python versions.

The CI tests seemed to pass. Testing functionality now, but I _think_ that this may be fixed now..? 🤞

**Comment by ewels** [comment]
It's a slightly obscure test, but the [nf-core/methylseq](https://github.com/nf-core/methylseq) pipeline now runs with bismark using HiSAT2 on a python 3k environment inside a docker container! 😆 

https://travis-ci.com/nf-core/methylseq/jobs/263630208

I'm happy with this, so will close this issue now.
