### ISSUE TITLE
trnascan-se update request

### ISSUE THREAD

**Issue by tnn111** [bioconda/bioconda-recipes#19063]
trnascan-se is at version 2.0.3 here but the current version of the software is 2.0.5. There are significant bugs that were fixed and it would good to get it updated.

**Comment by bgruening** [comment]
@tnn111 everyone can update recipes here. Feel free to create a PR.

Thanks!

**Comment by oschwengers** [comment]
@bgruening @tnn111 I jus tcreated a PR: https://github.com/bioconda/bioconda-recipes/pull/19298

**Comment by oschwengers** [comment]
https://github.com/bioconda/bioconda-recipes/pull/19298 is merged, so I close this issue.
