### ISSUE TITLE
pyopenms/openms restructuring

### ISSUE THREAD

**Issue by jpfeuffer** [bioconda/bioconda-recipes#19200]
Hi everyone!

I followed the recent integration of pyOpenMS and the changes to OpenMS a little.
I started to clean up the recipes locally a bit and I was wondering if it wouldn't be
possible to just split a general OpenMS recipe into multiple subpackages
via the "output" section. Since all the parts should have the same versions of dependencies
and sources anyway I think that would make sense (if it is supported in bioconda). Also it
is much less trouble to build them together. Or was it very important to reduce the build times
here?

We could have multiple subpackages:
- libopenms
- openms-tools
- (openms-gui) # if we can make it work
- pyopenms

One question that I would have then is how to specify the "outputs" for pyopenms.
We build it with distutils based on our CMake output but what kind of files should go where
for a python package. In the current recipe it seems like it just "pip install"s the wheel.

**Comment by bgruening** [comment]
All I can say is that one recipe with multiple outputs is the preferred way. I raised this in the initial reivew and people agreed that this is the long-term strategy.

**Comment by jpfeuffer** [comment]
Ok great. Then I am going to follow this path. My first attempts were promising.
pyOpenMS is a bit tricky since the wheel of course comes with all libs etc. bundled. 
I assume the conda way would be to reference libs installed by the future libopenms package right?
Does anyone know if the activate scripts act transitively, i.e. if I set the OPENMS_DATA_PATH in the libopenms package and pyOpenMS requires it, will it be loaded as well during activation?

**Comment by bernt-matthias** [comment]
This seems to be done now, or?
