### ISSUE TITLE
Dependency platform requirement ignored?

### ISSUE THREAD

**Issue by aaronmussig** [bioconda/bioconda-recipes#19229]
Hi, I've noticed - or it appears - that there are no checks in place to ensure that the platform of a dependency is satisfied.

At a minimum, shouldn't packages only be able to run on the least common subset of platforms in the dependencies of a package?

e.g. [checkm-genome](https://bioconda.github.io/recipes/checkm-genome/README.html) has dependencies such as [pplacer](https://bioconda.github.io/recipes/pplacer/README.html), which only supports Linux-64. Therefore, shouldn't checkm-genome only support Linux-64 and not be noarch?

**Comment by dpryan79** [comment]
checkm-genome itself has no dependency restrictions, so why should we artificially restrict in just because one dependency currently lacks an OSX build? If someone bothers getting pplacer to build for OSX we'd then need to rebuild everything that needs it so they can be used on OSX.
