### ISSUE TITLE
Remove arch specific builds for staramr

### ISSUE THREAD

**Issue by Takadonet** [bioconda/bioconda-recipes#19511]
Trying to address [issue](https://github.com/phac-nml/staramr/issues/109) from some of our users where if they do not specific a version of staramr, it will install _latest_ arch build for osx and linux version v0.5.1 instead of the latest noarch version of [v0.7.1](https://anaconda.org/bioconda/staramr) . 

We modified our recipe to create only noarch build after v 0.5.1 and probably when the issue started to occur. We normally always specify a version when we install tools with conda but others users may let conda decide the latest version for them when installing. 

 Wonder if possible to deprecated arch build or default to noarch when users install with command **conda install staramr**?

**Comment by apetkau** [comment]
Running `conda install staramr` on Linux right now will install version `0.7.2` for me. So I'm going to assume this issue has been fixed.
