### ISSUE TITLE
Add recipes for Genomedata and Segway

### ISSUE THREAD

**Issue by michaelmhoffman** [bioconda/bioconda-recipes#1953]
Could you please add recipes for the Genomedata dense genomic data storage system and the Segway semi-automated genome annotation software?

http://genomedata.hoffmanlab.org/
http://segway.hoffmanlab.org/

Genomedata is a prerequisite for Segway.

Thank you!

**Comment by michaelmhoffman** [comment]
PyTables appears to be in the anaconda channel too (https://anaconda.org/anaconda/pytables). forked-path and textinput are pure Python packages in PyPI. The latest GMTK tarball is available from http://melodi.ee.washington.edu/downloads/gmtk/gmtk-1.4.4.tar.gz. Do you need a way to figure out the newest GMTK automatically? That would take more doing but I could liaise with the GMTK authors.

**Comment by dpryan79** [comment]
No, this would use a single version of gmtk. I've added textinput and forked-path as new packages in the branch with genomedata already and those appear to work. I'm just trying to get genomedata happy now.

**Comment by bgruening** [comment]
Community :heart:!

**Comment by dpryan79** [comment]
`genomedata` seems to work now (at the very least TravisCI is happy). Note that this isn't compatible with python3. I'll try to add in segway now.

**Comment by dpryan79** [comment]
TravisCI is showing green for segway now too. The PR is waiting for approval.

@michaelmhoffman: If you have a chance sometime, you might update some of the dependency packages you wrote to support python3.

**Comment by bgruening** [comment]
@michaelmhoffman Docker containers also needed for segway?

**Comment by bgruening** [comment]
@michaelmhoffman here is your Docker container: https://github.com/mulled/mulled/pull/129
