### ISSUE TITLE
biocontainer for biotdg not accessible

### ISSUE THREAD

**Issue by rhpvorderman** [bioconda/bioconda-recipes#19749]
https://quay.io/repository/biocontainers/biotdg?tab=tags

Is marked as private. Biotdg was accepted in bioconda yesterday. @bioconda/build-system shouldn't new repositories be set to public automatically? Is this a bug in the build system or a limitation of quay.io?

**Comment by rhpvorderman** [comment]
Hi 12 days later, the repo is still private. Is there anything I can do to help?

**Comment by bgruening** [comment]
You haven't used the bot to merge, isn't it?

Eitherway, its now open ...

**Comment by rhpvorderman** [comment]
@bgruening  Ah is that the trick. My apologies then, I wasn't aware. I should have read the latest documentation. Thanks for opening the repo!
