### ISSUE TITLE
Updating R packages

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#1977]
R 3.3.1 is out. Between the last R update and now, we started using the `env_matrix.yml` to determine which R version to use for all builds. If we just make a single change -- simply add `CONDA_R: 3.3.1` to env_matrix.yml -- it triggers a re-build of every R package in bioconda. As you would expect, we get lots of errors. I would expect we would go over the 75 min limit even it we could build them all without errors.

Options that I currently see to solve this:

Option 1: add `skip: True` to all R packages to disable their building on R 3.3.1, and then incrementally change them to `skip: False` to test them in small batches

Option 2: Don't use the CONDA_R env var, and instead manually pin the R version in the dependencies

Option 3: modify `build-packages.py` to check the git log and only consider building recipes that have changed relative to master

Anyone have a better idea @bioconda/core?

**Comment by johanneskoester** [comment]
Option 1: sounds like an ok solution to me. Maybe an even more clear solution that does not include modifying the recipes: introduce a blacklist of packages, that will be ignored by our build scripts. This way, we can temporarily omit packages based on the needs of our build system without messing with the git history of a package.

Option 2: I would not make the recipes unnecessary complicated just to solve a build system issue.

Option 3: This can cause other problems with the way the env matrix works. E.g. we won't be able to trigger updates by just changing the env matrix any more.

**Comment by daler** [comment]
I like that idea, an R blacklist should do the trick and be minimally disruptive.

**Comment by johanneskoester** [comment]
Since this needs changes in the build scripts, it would be ideally implemented in bioconda-utils. I haven't yet merged that PR, because it needs some modifications in the dockerfile. I will try to do that as soon as possible. If you want, you could already include the blacklist code into bioconda-utils.

**Comment by daler** [comment]
OK, I'll add the blacklist code to bioconda-utils.

**Comment by bgruening** [comment]
Option one with blacklist sounds good! Thanks for working on it!

**Comment by daler** [comment]
closing in favor of #2404
