### ISSUE TITLE
Trinity: Error Unable to access ExitTester.jar 

### ISSUE THREAD

**Issue by PietJones** [bioconda/bioconda-recipes#1981]
Hi,

I am trying to run trinity (after installing it from the bioconda recipe), on a cluster environment. But, I get the following error:

```
Thursday, July 14, 2016: 12:22:46       CMD: java -Xmx64m -XX:ParallelGCThreads=2 -jar      ExitTester.jar 0
Error: Unable to access jarfile ExitTester.jar
Error, cmd: java -Xmx64m -XX:ParallelGCThreads=2 -jar ExitTester.jar 0 died with ret 256 at   /lustre/atlas1/bif102/proj-shared/piet/miniconda/bin/Trinity line 2209.
```

I know the ExitTester.jar file is located in the miniconda share subfolder, but for some reason it is not being detected. Any advice?

P

**Comment by jerowe** [comment]
@PietJones, I built the most recent trinity recipe. I'll look into it today.

**Comment by rvalieris** [comment]
I just tested the trinity-2.3.2 package with the sample data run, and I didn't get any errors. 

report back here if you are still experiencing issues.
