### ISSUE TITLE
Replace matplotlib dependency with matplotlib-base in most recipes

### ISSUE THREAD

**Issue by marcelm** [bioconda/bioconda-recipes#19996]
The `matplotlib` package has been split into a `matplotlib` and `matplotlib-base` package a while ago, see https://github.com/conda-forge/matplotlib-feedstock/pull/178 . The only difference is that `matplotlib-base` does not depend on `pyqt`, reducing installation size significantly. Unless Matplotlib’s PyQt backend is explicitly needed by a package, depending on `matplotlib-base` is sufficient.

To be clear: Interactive plotting is still possible even with only `matplotlib-base` because the TkAgg backend is still available. It actually looks very similar to the PyQt backend.

Also, Matplotlib 3+ has a backend fallback mechanism. For interactive plotting, it prefers PyQt, but falls back to TkAgg. Nothing needs to be configured. If the user wants to use PyQt (or PySide or similar), they simply need to install that package, and they’ll get PyQt instead of TkAgg automatically.

Around 230 packages are affected.

```bash
$ egrep -l " *- matplotlib(\s|$)" recipes/*/meta.yaml | wc -l
230
```

cf #19985

**Comment by bgruening** [comment]
@marcelm Thanks a lot for pushing this! Maybe a good first step is to enhance our linter to warn about the matplotlib usage and recommend the -base version?

**Comment by marcelm** [comment]
We’re currently at around 100 packages that still depend on `matplotlib`. I’m closing this now because the linter check is in place and because I don’t think anyone wants to manually go through the remaining recipes and update them. They have obviously not been updated in the last 1.5 years, so most of these will be for software that is not used so much anyway.
