### ISSUE TITLE
Problems with Cactus and Ragout

### ISSUE THREAD

**Issue by amizeranschi** [bioconda/bioconda-recipes#20075]
Hi @dpryan79,

I'm having some trouble with the Ragout recipe, which I believe you've created: https://github.com/fenderglass/Ragout/issues/57#issue-558342181. Could you please have a look?

On a related note, would you also be able to update the recipe for Cactus, as this is a dependency for Ragout? https://github.com/ComparativeGenomicsToolkit/cactus/issues/135#issue-558257037

**Comment by dpryan79** [comment]
I didn't create the recipe, I just created a new build as part of a mass migration of hundreds of packages.

**Comment by amizeranschi** [comment]
Hmm, then, who created that Ragout recipe?

Also, do you have a link for where I could read more about how Bioconda recipes are created and maintained, in general?

**Comment by dpryan79** [comment]
It was originally made by @nickp60 in 2017.

Your best best is to look at the general [conda recipe tutorials](https://docs.conda.io/projects/conda-build/en/latest/user-guide/getting-started.html), since Bioconda is no different in this regard than any other conda-based project.

**Comment by amizeranschi** [comment]
OK, thanks a lot for the info.

**Comment by fenderglass** [comment]
The discussion was moved to the Ragout repo and the original problem was solved - closing the issue.
