### ISSUE TITLE
Tandem Repeats Finder and Licensing

### ISSUE THREAD

**Issue by jerowe** [bioconda/bioconda-recipes#2010]
```
Tandem Repeats Finder License Terms

The author of this software grants to any individual or organization **the right to use and to make an unlimited number of copies of this software.** You may not de-compile, disassemble, reverse engineer, or modify the software. **This software cannot be sold, incorporated into commercial software or redistributed**. The author of this software accepts no responsibility for damages resulting from the use of this software and makes no warranty or representation, either express or implied, including but not limited to, any implied warranty of merchantability or fitness for a particular purpose. This software is provided as is, and the user assumes all risks when using it. 
```

The source code is not available, only precompiled binaries. I'm kind of unclear on whether or not the binaries could be bundled into a conda package because of the 'redistribute' clause.

?

**Comment by rvalieris** [comment]
license page: https://tandem.bu.edu/trf/trf.license.html

> This software cannot be sold, incorporated into commercial software or redistributed.

I think its pretty clear the author doesn't want his software to be available anywhere but his site.

We can distribute instructions on how to acquire the software, such as a conda recipe, but not distribute the software itself, as a conda package.

We could either use a register system similar to the gatk package, or try to contact the author and ask for a clarification and/or exception for bioconda.

**Comment by jerowe** [comment]
I figured that with the redistribute clause, but then I was thrown by the 'unlimited number of copies'. I think its completely reasonable for an author to want that. I will just move onto other things. Thanks for the opinion. ;-)
