### ISSUE TITLE
EdgeR should depend on r-locfit

### ISSUE THREAD

**Issue by yhoogstrate** [bioconda/bioconda-recipes#2011]
To estimate dispersion EdgeR needs to make use of the conda package `r-locfit`. I tried to update the edgeR package but the bioconductor package is already gone and conda gives the following error:
```
Error: HTTPError: 404 Client Error: Not Found: 
http://bioconductor.org/packages/release/bioc/src/contrib/edgeR_3.12.1.tar.gz
```
I don't know the bioconda policy on how to solve this. I could go for 3.12.0 instead which has maintained urls by  the galaxy team, or upgrade to 3.14.

**Comment by daler** [comment]
We're working on moving to R 3.3.1 which should help resolve this by allowing the latest updates for all bioconductor packages. You can also try using the `scripts/bioconductor/bioconductor_skeleton.py` script which should build a recipe for the latest version, but the dependency chain might require R 3.3.1. @bgruening, is there a way for you to get a previous bioconductor package into bioaRchive?

**Comment by bgruening** [comment]
@daler in principle yes. We can get all packages that where taged as a release from the bioarchive svn. But it seems that 3.12.1 is missing, so never was tagged. https://bioarchive.galaxyproject.org/#/pkg/edgeR/3.12.0 is the only one available :(

**Comment by bgruening** [comment]
@yhoogstrate we build yesterday a edgr version. Can you retest please?
