### ISSUE TITLE
Cheetah-templated YAML files are not portable

### ISSUE THREAD

**Issue by VJalili** [bioconda/bioconda-recipes#20262]
Cheetah is a python-specific template engine; while its produced YAML files are deserializable in python, they are not readable in other programming languages. For instance, [this online YAML linting service](http://www.yamllint.com) fails parsing [this YAML file](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/a5-miseq/meta.yaml).  Therefore, in order to make the YAML files portable, I suggest converting the Cheetah-templated YAML files to a "standard" syntax.

**Comment by bgruening** [comment]
@VJalili the yaml files are enriched with jinja2 templates. If you wanna read them, please use the conda tools for this, in particular the bioconda-utils can parse those files.

Another option is to download the packages from anaconda.org, in each tarball you will find a deserialized version.
