### ISSUE TITLE
Bowtie2 for Python 3.8

### ISSUE THREAD

**Issue by mivade** [bioconda/bioconda-recipes#20280]
The most recent builds of `bowtie2` (2+ days ago at the time of writing) do not have packages built for Python 3.8 (which was released mid-October 2019). As far as I can tell `bowtie2` only uses Python for CLIs with the standard library `argparse` module so there should be little difficulty in toggling that switch. Can the recipe please be updated to produce builds for Python 3.8?

**Comment by alienzj** [comment]
Hi, now I can install bowtie2 on python 3.8 conda environment.
Maybe you can try.

**Comment by mivade** [comment]
It looks like there now are Python 3.8 packages as of about a month and a half ago, so thanks to whoever addressed this.
