### ISSUE TITLE
bioconductor-rhdf5 does not support R 3.3

### ISSUE THREAD

**Issue by Horta** [bioconda/bioconda-recipes#2030]
R 3.3 has been recently introduced into the R channel but the above mentioned package doesn't support it:  https://anaconda.org/bioconda/bioconductor-rhdf5/files

And maybe other packages as well.

**Comment by daler** [comment]
Actually just about all R packages currently in bioconda are not supported on R 3.3. We're working on it; see https://github.com/bioconda/bioconda-recipes/issues/1977.
