### ISSUE TITLE
how to delete a package from Bioconda?

### ISSUE THREAD

**Issue by Xiangyang1984** [bioconda/bioconda-recipes#20445]
I want to delete a package from Bioconda, how to do it?

**Comment by mbargull** [comment]
Which package? Why? This is generally discouraged.
We usually delete packages only when there are legal reasons that prevent us from their distribution.
We move packages off of the `main` label on anaconda.org (which makes them unavailable to users of the `bioconda` channel), if there are important technical reasons.

**Comment by Xiangyang1984** [comment]
The package is Gcluster. We found some mistakes in this package, so we want to remove there two version for Gcluster. @mbargull

**Comment by mbargull** [comment]
Why do you need to remove those? Can't you just package a new fixed version?

**Comment by Xiangyang1984** [comment]
Yes, we are going to build a new version, but I wonder whether the mistaken version may be installed by some users using "conda install package_name"?

**Comment by dpryan79** [comment]
It can be, but once your fixed version is released it'll take priority.

Basically every package ever released has notable bugs found at some point, just patch them in the next release and don't worry too much about it.

**Comment by Xiangyang1984** [comment]
Ok, thanks for your reply.

**Comment by raivivek** [comment]
@Xiangyang1984 Looks like this is resolved, but if not, please re-open.

**Comment by suvrajitm** [comment]
Hello, 
I uploaded a package called "mcross" on my anaconda channel to test if it installs properly through conda install. There is another version of the package on bioconda and when I do conda install -c "mychannel" mcross,  it is installing from the bionconda channel and not "mychannel". If -c "mychannel" is specified , why is it selecting bioconda ? Can anyone provide any suggestions how to fix this issue. Also, is it possible to remove the package from bioconda? We would prefer to maintain the package on our anaconda channel only. Thanks

**Comment by bgruening** [comment]
Because you default channels have bioconda activated and you just add yours ontop. You can overwrite channel settings. Please consult the general conda documentation here.
