### ISSUE TITLE
Danpos recipe uses wrong samtools version

### ISSUE THREAD

**Issue by mae92** [bioconda/bioconda-recipes#20637]
This issue pertains to the bioconda danpos recipe.

DANPOS2 has not been updated in a long time and is only able to use samtools 0.1.19 or below. Because of this, the current recipe does not allow for DANPOS2 to to take BAM and SAM files as input without the user having to uninstall samtools  1.9 and reinstall samtools 0.1.19.

**Comment by guillaumecharbonnier** [comment]
Should be solved now.
