### ISSUE TITLE
bowtie2 not available from current channels?

### ISSUE THREAD

**Issue by pavel-shliaha** [bioconda/bioconda-recipes#20948]
I am very new to conda, but I follow the suggestions shown below:

https://bioconda.github.io/user/install.html#install-conda

I installed the miniconda, added the system path C:\ProgramData\Miniconda3; C:\ProgramData\Miniconda3\Scripts; C:\ProgramData\Miniconda3\Library\bin and ran the suggested code. The results are shown below

(base) C:\WINDOWS\system32>conda config --add channels defaults
Warning: 'defaults' already in 'channels' list, moving to the top

(base) C:\WINDOWS\system32>conda config --add channels bioconda
Warning: 'bioconda' already in 'channels' list, moving to the top

(base) C:\WINDOWS\system32>conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top

(base) C:\WINDOWS\system32>conda install bowtie2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - bowtie2

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Any suggestions as to why this package is not available? It is specified as available here: https://bioconda.github.io/recipes/bowtie2/README.html

**Comment by Slugger70** [comment]
Hi there. Unfortunately, Bowtie2 is not available for Windows. It is only available for Linux and OSX.
See: https://anaconda.org/bioconda/bowtie2

**Comment by pavel-shliaha** [comment]
thanks. Installing LINUX.
