### ISSUE TITLE
Autobump malva recipe

### ISSUE THREAD

**Issue by ldenti** [bioconda/bioconda-recipes#21073]
Hi all,
last time we released a new version of our tool (malva, from v1.1.0 to v1.1.1), the bioconda recipe got updated automatically. However, one month ago we created a new release (version 1.2.0 from 1.1.1) and the recipe didn't get automatically updated.

Do I have to trigger an autobump scan by explicitly invoking the BiocondaBot? We didn't change any dependency.

Thanks,
Luca

**Comment by ldenti** [comment]
@BiocondaBot autobump malva

**Comment by blinard-BIOINFO** [comment]
Hi, 
I got the same issue with the "rappas" recipe.
Last time, it autobumped when I released tag 1.20.
But my last tag 1.21 did not autobump.
There was no changes in dependancies.

Why would it autobump on some occasions but not others ?
Is there some rules for autobumps ?

**Comment by blinard-BIOINFO** [comment]
@BiocondaBot autobump rappas

**Comment by ldenti** [comment]
I don't think it worked as expected. For sure we are doing something wrong. But from https://github.com/bioconda/bioconda-recipes/issues/14400 it's not totally clear to me what is the correct way for autobumping a recipe

**Comment by blinard-BIOINFO** [comment]
I added the "help wanted" label, after reading  #14400 I understand the autobump should have been launched on our recipes, but no new pull request with autobump label appeared.
@bioconda/core  , maybe we missed something in how the process works ?

**Comment by dpryan79** [comment]
There's no autobump command on github, just on the command line with `bioconda-utils`.

**Comment by dpryan79** [comment]
There is a cron job that runs every hour. It's unclear why malva is getting skipped, just manually make a PR updating it.

**Comment by ldenti** [comment]
Oh, I see: then the issue https://github.com/bioconda/bioconda-recipes/issues/14400 is an old issue that is not valid anymore. I'll make a PR, thank you.

**Comment by ldenti** [comment]
Just for future reference, it was an error on our end.

I just noticed that we changed the tag format from v1.* to 1.*. I think this is the reason why malva recipe was skipped. Now I tagged the release in the correct way (ie v1.2.0) and the recipe has been autobumped.

**Comment by blinard-BIOINFO** [comment]
Hi,
@dpryan79 . Sorry to come back to this but I'm stuck with autobumping via bioconda-utils.

First, when following tutorials, I realized that they are not updated anymore.
For instance, https://bioconda.github.io/contributor/updating.html say to use a `bioconda-utils update` command, but the `update` option does not appear anymore in current version of bioconda-utils (install via `conda install bioconda-utils`). 

Then I see via the help of bioconda-utils that there is an `autobump` option. I try to use it but only get some pyton errors:
```
$ bioconda-utils autobump recipes/ config.yml --package rappas
12:02:55 BIOCONDA INFO Hosters loaded: ['FTPHoster', 'GithubRelease', 'GithubTag', 'GithubReleaseAttachment', 'GithubRepoStore', 'Bioconductor', 'CargoPort', 'SourceForge', 'PyPi', 'Bioarchive', 'CPAN', 'CRAN', 'BitBucketTag', 'BitBucketDownload', 'GitlabTag']
12:02:55 BIOCONDA WARNING Selected 1 packages
12:02:55 BIOCONDA INFO Building Recipe DAG
Loading Recipes...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 7222/7222 [00:20<00:00, 346.49it/s]
12:03:17 BIOCONDA INFO Building Recipe DAG: done (4753 nodes, 18345 edges)
12:03:17 BIOCONDA ERROR Dropping into debugger
Traceback (most recent call last):
  File "/media/ben/STOCK/VIRTUAL_ENV/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 71, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-17>", line 5, in autobump
  File "/media/ben/STOCK/VIRTUAL_ENV/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 90, in wrapper
    func(*args, **kwargs)
  File "/media/ben/STOCK/VIRTUAL_ENV/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 823, in autobump
    config_dict, cache_fn=cache and cache + "_dag.pkl")
  File "/media/ben/STOCK/VIRTUAL_ENV/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/autobump.py", line 133, in __init__
    self.dag = graph.filter_recipe_dag(self.dag, packages, exclude)
  File "/media/ben/STOCK/VIRTUAL_ENV/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/graph.py", line 127, in filter_recipe_dag
    and not any(fnmatch(recipe.reldir, p) for p in exclude)):
TypeError: 'NoneType' object is not iterable

```
So my simple question is: what is the command to autobump via bioconda-utils ?
