### ISSUE TITLE
Python test failures due to "python: no such file or directory"

### ISSUE THREAD

**Issue by marcelm** [bioconda/bioconda-recipes#21121]
At least three PRs for Python packages that contain command-line scripts fail at the moment when Conda tries to run the scripts during the test phase. The errors always look like this (reformatted to make it readable):
```
+ phylophlan --version
/opt/conda/conda-bld/phylophlan_1585178088625/_test_env_placehold_...\
_placeho/bin/phylophlan: \
line 2: /opt/conda/conda-bld/phylophlan_1585178088625/_h_env_placehold_...\
_placehold_pl/bin/python: No such file or directory

/opt/conda/conda-bld/phylophlan_1585178088625/_test_env_placehold_...\
_placehold_placeho/bin/phylophlan: \
line 2: exec: /opt/conda/conda-bld/phylophlan_1585178088625/_h_env_placehold_...\
_placehold_pl/bin/python: cannot execute: No such file or directory
```

Affected PRs: #21097, #21102, #21113 (possibly also #21104, but the error message is different).

At least for #21102, I know for certain that the previous version worked and that package and recipe have changed minimally since then.

**Comment by fbeghini** [comment]
Also #21032 is affected, the PR is now closed, I've run CircleCI locally and the test phase fails with the same error. The receipe has not change since the last PR and previously, the test were all OK.

**Comment by marcelm** [comment]
I was now able to reproduce this even by just running `conda build .` in the recipe folder without any bioconda-specific setup. Perhaps this is a conda-build issue?

**Comment by fbeghini** [comment]
Tests are OK for PR #21097 with conda-build 3.18.11 and 3.17.8

**Comment by fasnicar** [comment]
Thanks marcelm!
I have the same error locally and the conda-build version I have is `3.19.1`.
Haven't tried yet with older versions of conda-build.

**Comment by marcelm** [comment]
PyPI is down for me so further tests will have to wait. I got the local failure with 3.19.1 as well.

**Comment by mbargull** [comment]
Thanks for the PR references. This is most likely due to a `conda-build=3.19.1` issue we've been made aware of in https://github.com/bioconda/bioconda-recipes/pull/21112. This is fixed by https://github.com/conda-forge/conda-build-feedstock/pull/131 and our subsequent update of our build system. I'll restart the CI for the linked PRs.

**Comment by marcelm** [comment]
Thanks! All the affected PRs are now passing their respective tests. I’m closing this now and will follow upstream conda/conda-build#3893.
