### ISSUE TITLE
The local docker/build tests worked and the travis CI tests worked, but I broke the build

### ISSUE THREAD

**Issue by endrebak** [bioconda/bioconda-recipes#2118]
Since I am not allowed to merge a pull request without Travis CI passing, I do not know how this could have happened. 

Can someone please help me interpret the error below, found on the following page: https://travis-ci.org/bioconda/bioconda-recipes/jobs/151169104 

It seems like a `user.email` was not set when it tried to add some stuff to git to update the `bioconda.github.io` page.

```
...
build succeeded, 5885 warnings.
# Add generated files to the bioconda.github.io repository
touch .nojekyll
git add .nojekyll
echo '.*' >> .gitignore
git add .
git config user.name "Travis CI"
git commit --all -m "Updated docs to commit ${TRAVIS_COMMIT}."
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'travis@testing-gce-bb4e34e4-a2b5-4f28-9aa2-032e7559f0d7.(none)')
/home/travis/build.sh: line 112:  3018 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait 75 scripts/travis-run.sh" exited with 128.
Done. Your build exited with 1.
```

The previous build errored as you can see here in the list of builds, but that is probably unrelated: https://travis-ci.org/bioconda/bioconda-recipes/builds

**Comment by endrebak** [comment]
I tried restarting the build, the only possible fix I can think of.

**Comment by endrebak** [comment]
I guess this will remain a mystery.

**Comment by daler** [comment]
see #2121
