### ISSUE TITLE
HMMER - Package missing in current linux-64 channels

### ISSUE THREAD

**Issue by ciemanek** [bioconda/bioconda-recipes#21192]
Hi,

While trying to install HMMER via conda environment.ymlfile, I come across a following error:

```
Fetching package metadata .............


NoPackagesFoundError: Package missing in current linux-64 channels: 
  - bioconda:hmmer
```

What is a possible reason for that?

**Comment by acaprez** [comment]
Can you share your `environment.yml` file and the output from `conda info`?

**Comment by ciemanek** [comment]
I managed to fix the issue by modyfying my `environment.yml` from:
```
  - bioconda:hmmer
```
to:
```
  - bioconda::hmmer
```

following conda release notes: https://docs.conda.io/projects/conda/en/latest/release-notes.html#id203
