### ISSUE TITLE
recipe in master branch not found with conda search

### ISSUE THREAD

**Issue by matthdsm** [bioconda/bioconda-recipes#2122]
Hi,

Recently I've submitted a recipe for umi_tools to bioconda. This was accepted and merged, but I'm not able to find the tool using conda. Is it possible the recipe wasn't pushed to anaconda yet?

Thanks
M

**Comment by bgruening** [comment]
@matthdsm this can be. We had some build environment issues. Can you change the recipe, some whitespace changes and try it again, please?

**Comment by matthdsm** [comment]
done in #2123

**Comment by matthdsm** [comment]
wrong extension on meta.yaml seems to be the cause, fixed in #2126

**Comment by matthdsm** [comment]
Issue seems to be resolved, I'll close this now.

Thanks for the help!
M
