### ISSUE TITLE
igblast 1.15.0 can't find the internal_data directory

### ISSUE THREAD

**Issue by ressy** [bioconda/bioconda-recipes#21378]
I upgraded my igblast install today from 1.10.0 to 1.15.0 and found that it no longer is able to automatically find its internal_data directory.

**More Detail**

A dummy igblastn call that worked under 1.10.0 now gives:

    $ igblastn -germline_db_V stub_HV.fasta -germline_db_D stub_HD.fasta -germline_db_J stub_HJ.fasta -query works.fasta -outfmt 19
    BLAST query/options error: Germline annotation database human/human_V could not be found in [internal_data] directory
    Please refer to the BLAST+ user manual.

Supposedly I should be able to set `IGDATA=/path/to/internal_data` but it doesn't have any effect.  For what it's worth, the same is true for the copy of 1.15.0 I downloaded straight from NCBI, so this may really be their bug to solve.  Having internal_data in the current working directory, for example by symlinking it from the installed location, *does* work:

    $ ln -s $CONDA_PREFIX/share/igblast/internal_data .
    $ igblastn -germline_db_V stub_HV.fasta -germline_db_D stub_HD.fasta -germline_db_J stub_HJ.fasta -query works.fasta -outfmt 19
    Warning: Auxilary data file could not be found
    sequence_id     sequence        locus  ...etc...

**Even More Detail**

 * Previous build that worked: `igblast-1.10.0-h6ac72b6_1`
 * Current build that doesn't: `igblast-1.15.0-h18cd00f_0`
 * This is following the upgrade in #15994.

**Comment by marcelm** [comment]
Hi, I was the one who upgraded the recipe. I saw this issue only now. Were you able to solve it?

The first command that you pasted above works for me (after I created indices for the three database FASTA files with `makeblastdb`). However, when I set the `$IGDATA` environment variable to something invalid, I do get the exact same problem.

Is it possible that you had the `$IGDATA` variable set even for the first command?

Possibly relevant: Note that the Bioconda package installs a wrapper. When you run `igblastn`, that is actually a shell script that will set `$IGDATA` for you before running the actual IgBLAST binary. If `$IGDATA` is already set, the script will however not set `$IGDATA` and just use the already set value. The behavior of this wrapper may have changed slightly.

**Comment by ressy** [comment]
Looking closer I think this is on me.  I must have gotten mixed up between the wrapper's behavior and the binary itself I also tried from NCBI but nothing actually changes between versions of the igblastn binary.  (I'd interpreted the docs to mean that IGDATA should point to the internal_data directory itself, but your wrapper script helped me realize it's supposed to point to the *parent* of internal_data.)  Testing from scratch with a clean environment and the bioconda package for 1.15.0 all works as it should so I'll close this one now.  Thanks for your help as always!

**Comment by marcelm** [comment]
Great, thanks for letting me (us) know! I’m glad to hear I probably didn’t mess up the recipe after all ;-).
