### ISSUE TITLE
Setting memory in java apps: high or low?

### ISSUE THREAD

**Issue by endrebak** [bioconda/bioconda-recipes#2140]
Do I err on the side of too much or too little?

I added ASCIIGenome to bioconda and set the default memory size to 8 gigs. This is because I had experienced a problem with the standard settings (1.5gb) where it could not even parse a gencode gtf.

Like you see below, the author thinks this is too much and I want to respect his wishes, but I also want to know what the community thinks.

https://github.com/dariober/ASCIIGenome/issues/22

I imagine most computers used for bioinformatics work have metric boatloads of RAM.

Thought: is this possible to let the user set in an install script? Or when running the software? What would be the desired bioconda solution?

**Comment by daler** [comment]
Can you add a wrapper script as described in the [guidelines](https://github.com/bioconda/bioconda-recipes/blob/master/GUIDELINES.md#java)? Then the user can specify whatever memory they need.

**Comment by endrebak** [comment]
I'll try copying this script the next time I update asciigenome: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/peptide-shaker/peptide-shaker.py

Thanks for your help.

**Comment by bgruening** [comment]
thank @endrebak!
