### ISSUE TITLE
sra-tools version bump

### ISSUE THREAD

**Issue by gokceneraslan** [bioconda/bioconda-recipes#21526]
Current version of sra-tools has some issues related to the NGC file usage, see

https://github.com/ncbi/sra-tools/issues/307#issuecomment-613457054

It'd be great to upgrade the package to 2.10.5 @mvdbeek

**Comment by gernophil** [comment]
It's the same again. Would be great to update to 3.0.5 (released yesterday).

**Comment by mvdbeek** [comment]
I don't know why I am getting pinged here, you'll have to fix the build in https://github.com/bioconda/bioconda-recipes/pull/40871, I don't have time for that.

**Comment by cbrueffer** [comment]
Updated in https://github.com/bioconda/bioconda-recipes/pull/41006
