### ISSUE TITLE
Update salmon version

### ISSUE THREAD

**Issue by rob-p** [bioconda/bioconda-recipes#2152]
There's a new release of salmon (v0.7.0), and it would be great to update the version in bioconda. There are a few details about how the build is specified that I don't completely grok yet.  Also, some of the RPATH issues that were in v0.6.0 [have been fixed in v0.7.0](https://github.com/Homebrew/homebrew-science/pull/4058), so hopefully fixes some of the shared library problems in the current build.

cc: @roryk

**Comment by roryk** [comment]
Thanks Rob, I messed around with this a little bit yesterday and couldn't get it to build properly right off the bat. This wasn't the problem, but do you know if including gperftools is still necessary for getting it to run on older CentOS systems? I had to grab libunwind and build that to get past the gperftools step.

**Comment by roryk** [comment]
If I drop that stuff I can get it to build.

**Comment by roryk** [comment]
It fails building in the docker container though-- there are lots of clashes with multiple definitions of stuff inside of jemalloc:

```
src/arena.pic.o: In function `__signbitf':
/usr/include/bits/mathinline.h:37: multiple definition of `__signbitf'
src/jemalloc.pic.o:/usr/include/bits/mathinline.h:37: first defined here
src/arena.pic.o: In function `__signbit':
```

**Comment by rob-p** [comment]
What are the specs of the docker container?  I have a successful docker image [here](https://hub.docker.com/r/combinelab/salmon/).  I wonder what the differences might be (my dockerfile is [here](https://github.com/COMBINE-lab/salmon/blob/master/docker/Dockerfile)).

**Comment by roryk** [comment]
Hi Rob, thanks for looking into it. The dockerfile for the bioconda builder image is here, if that helps at all: https://hub.docker.com/r/bioconda/bioconda-builder/~/dockerfile/

**Comment by roryk** [comment]
I ended up getting this to go a couple days ago, seems to be fine. Thanks!
