### ISSUE TITLE
RepeatMasker misses buildRMLibFromEMBL.pl

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#21684]
Hi,
I installed RepeatMasker but I can't find `buildRMLibFromEMBL.pl`.

What did I miss?

Thank you in advance,

Michal

**Comment by Juke34** [comment]
It is not among the exe copied in /bin 
`DateRepeats DupMasker ProcessRepeats RepeatProteinMask util/queryRepeatDatabase.pl util/queryTaxonomyDatabase.pl util/rmOutToGFF3.pl util/calcDivergenceFromAlign.pl util/createRepeatLandscape.pl util/dupliconToSVG.pl util/getRepeatMaskerBatch.pl util/rmOut2Fasta.pl util/trfMask util/rmToUCSCTables.pl util/buildSummary.pl`

I will check if the script is in the distribution, if yes we should modify the recipe to include it
