### ISSUE TITLE
$R command unknown

### ISSUE THREAD

**Issue by osallou** [bioconda/bioconda-recipes#2168]
meta.yml sometimes specifies test commands.
For R related packages, those commands specifies for example:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/r-snowfall/meta.yaml

    $R -e "library('snowfall')"

but $R is unknown, R should be used instead.

This error prevent auto-testing of packages install from meta.yml. test commands should specify commands that can be run in the system.

**Comment by bgruening** [comment]
$R is replaces by the conda test infrastructure afaik. On Windows you need to call an other executable as under Linux afaik.

We could discuss if this makes sense in bioconda as we do not support Win intentionally, but it does not seem to be a bug to me.
Feel free to reopen if this is an issue in your setup.
