### ISSUE TITLE
jalview can not be installed on windows 10

### ISSUE THREAD

**Issue by abecerra** [bioconda/bioconda-recipes#21888]
On windows 10, when doing:

conda install jalview 

All the dependencies install correctly, but I get this error:

InvalidArchiveError("Error with archive C:\\Users\\abecerra\\miniconda3\\pkgs\\jalview-2.11.0-1.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCan't create '\\\\?\\C:\\Users\\abecerra\\miniconda3\\pkgs\\jalview-2.11.0-1\\bin\\jalview'")

**Comment by foreveremain** [comment]
Hi Abecerra - as far as I am aware, currently Bioconda only supports Linux and OSX. If you just want to run Jalview as an interactive GUI application then I suggest you download the Windows installation package from www.jalview.org/download

**Comment by abecerra** [comment]
Thank you @foreveremain, closing the issue.
