### ISSUE TITLE
Add previous versions of a package

### ISSUE THREAD

**Issue by bow** [bioconda/bioconda-recipes#2208]
Hi Bioconda developers,

I saw that the VarScan (version 2.4.2) is available in the recipes. I am wondering, however, what the policy is for adding previously released versions of a package.

My concrete use case is that I may need to use a previous version of VarScan (version 2.3.7 to be exact). I've tested this locally, following the guidelines set in the README up to the docker test, and everything seems to work fine.

Now, are there specific policies for supporting older versions of a package? Are they even allowed? If so, what should be done so that, in this case, VarScan 2.3.7 is added to the recipes? There are only two strings that need to be changed: the version string and the URL for downloading the package (this particular version is only hosted in SourceForge it seems). Everything else is the same as the existing 2.4.2 setup, so it seems quite trivial for a pull request (though I am absolutely fine with doing so :) ).

**Comment by bgruening** [comment]
@bow they are allowed and a few of us really want to have them visible at any time.
For the moment, please create a subdirectory called 2.3.7 in the varscan folder, this should do the trick.

**Comment by bow** [comment]
Hi @bgruening,

Great :). Would you prefer I open a merge request for this?

**Comment by bgruening** [comment]
@bow that would be awesome! Btw. it's called Pull request. You are asking us if we can pull your changes :) Strange words I know :)

**Comment by bow** [comment]
@bgruening Aha, indeed ~ I often get lost in the terminology :P. But anyway, it's open now here: https://github.com/bioconda/bioconda-recipes/pull/2211 :).
