### ISSUE TITLE
cannot install bowtie2 v2.4.1

### ISSUE THREAD

**Issue by brainfo** [bioconda/bioconda-recipes#22171]
Hi, I've reinstalled anaconda today to get the newest anaconda release 2020.02.
Now I have conda v4.8.3
But when I try conda install bowtie2 and conda update bowtie2, I can only get bowtie2 v2.3.5.1
I've removed tsinghua channel images so I thought the channels are from authorized original ones. But I'm sure which steps' wrong.
I want to install and execute the latest bowtie2 (I noticed from bioconda channel it's already available). Anyone can help?

**Comment by dpryan79** [comment]
Specify the version of what you want, otherwise you're just asking conda for any random version it wants to give to you.
