### ISSUE TITLE
conda recipe builds locally, but does not build remotely in one of four Travis CI tests

### ISSUE THREAD

**Issue by alexpreynolds** [bioconda/bioconda-recipes#2222]
I tried to issue a PR for the following commit:

https://github.com/bioconda/bioconda-recipes/pull/2220/files

I was able to build the conda recipe locally (OS X) without errors.

On the remote side, the first of the four Travis CI tests failed (Ubuntu 14). The other three passed. 

Is there something I can do to troubleshoot the failed test? I don't know how to replicate the setup related to the failed remote Travis CI test host. Thanks for any advice.

**Comment by notestaff** [comment]
You can look at the build logs here: https://travis-ci.org/bioconda/bioconda-recipes/pull_requests

**Comment by daler** [comment]
The [README](https://github.com/bioconda/bioconda-recipes/blob/master/README.md) describes how to set up the Docker container used for travis-ci tests. You can give this a shot on your local machine for troubleshooting.

**Comment by alexpreynolds** [comment]
From following the README, I am not able to get the Docker container running:

```
Papillion:bioconda-recipes alexpreynolds$ export DOCKER_TLS_VERIFY=1
Papillion:bioconda-recipes alexpreynolds$ export DOCKER_HOST=tcp://192.168.59.103:2376
Papillion:bioconda-recipes alexpreynolds$ export DOCKER_CERT_PATH=/Users/alexpreynolds/.boot2docker/certs/boot2docker-vm
Papillion:bioconda-recipes alexpreynolds$ docker run -v `pwd`:/bioconda-recipes bioconda/bioconda-builder --packages bedops --env-matrix /bioconda-recipes/scripts/env_matrix.yml
Unable to find image 'bioconda/bioconda-builder:latest' locally
Pulling repository bioconda/bioconda-builder
FATA[0014] Could not reach any registry endpoint   
```

Am I perhaps missing some configuration file or settings not described in the README?

**Comment by daler** [comment]
Haven't seen this before. Could be that dockerhub is down (though the [status](http://status.docker.com/) page seems fine). Docker version could also be an issue as described ([here](https://github.com/docker/docker/issues/15442) and [here](https://github.com/docker/hub-feedback/issues/398)).

**Comment by alexpreynolds** [comment]
Maybe I can fix this without trying to locally replicate the one remote Docker setup that is not working.

Is there documentation for what the variable `SUBDAG=0` changes for compilation by Bioconda?

There are two Linux-based Travis CI tests, and the one Linux test which passes uses `export SUBDAG=1`. The Linux host that fails uses `export SUBDAG=0`. 

Since this is the only difference, there's probably something about this particular variable that is causing compilation to fail.

I don't know what this variable changes about compilation. Google did not yield any results other than links to compile logs for other jobs. Anyone know what this variable does?

**Comment by daler** [comment]
Subdags are actually unrelated to the problem:

The subdags are a trick we use to get travis-ci to build recipes in parallel when possible. Recipes to be built are bundled into topologically-sorted sub-DAGs that can be built together. The job running with SUBDAGS=0 is building different recipes than the job running with SUBDAGS=1.  For a single recipe, there will only be one subdag (containing just that recipe) so it will run on the SUBDAGS=0 job. The reason SUBDAG=1 passed here is because it actually didn't build anything (as you can see from [this line](https://travis-ci.org/bioconda/bioconda-recipes/jobs/155256330#L285) in its build log).

I'll find a good spot to add this in the README or maybe the GUIDELINES.

I'm afraid I'm not much help when it comes to compiler issues, but there's a lot of gcc- and CentOS5-related stuff in the github issues which might help your troubleshooting.

**Comment by alexpreynolds** [comment]
I get the following error when trying to build an updated recipe via the `bioconda-builder` container (the recipe references code that is known to compile correctly on other hosts):

```/tmp/cc09LpmV.s: Assembler messages:
/tmp/cc09LpmV.s:8995: Error: symbol `stat64' is already defined
/tmp/cc09LpmV.s:9006: Error: symbol `fstat64' is already defined```

There are no Github issues for `bioconda-recipes` that seem to report problems with calls to `stat64` or `fstat64`. 

My code/recipe does not call either of these functions directly, though it does specify LFS (Large File Support) and calls `stat` and `fstat`.

Google searches suggest a problem with older versions of GCC. 

Is there a way to specify a reasonably recent version of GCC when building my recipe? 

When I add the following to the `meta.yaml` file, the build test ends with a different (and also fatal) error:

```requirements:
  build:
    - gcc >=5.3.0
  run:
    - libgcc >=5.3.0```

The error suggests that newer compilers are unavailable:

```Error:  Package missing in current linux-64 channels: 
  - gcc >=5.3.0```

I'm in the dark about how to troubleshoot this, since the `stat64/fstat64` compile error messages do not seem to have a direct connection with the code being compiled, and I'm not familiar enough with how bioconda recipes work to specify different build requirements that may resolve this. Any advice is appreciated.
