### ISSUE TITLE
depending on only the executables in a package

### ISSUE THREAD

**Issue by notestaff** [bioconda/bioconda-recipes#2228]
Bioconda recipes often have a particular type of package dependency: package A depends on package B, but only in that A runs some executables that B puts in bin/ .  In such a case, when installing A into an environment (say env_main), it is not necessary to install B and its dependencies into env_main, where they may create conflicts.   Instead, a separate environment (say env_B) can be created automatically, where B and its dependencies are installed.  Then, for each binary (say B_prog) that package B puts into env_B/bin, create correspondingly named script env_main/bin/B_prog which activates env_B, runs env_B/bin/B_prog within it, then deactivates env_B, returning to env_A.

Then e.g. a package written in Python 3 could depend on a package written in Python 2, as long as only executables from the Python 2 package were used.

This could be implemented e.g. by automatically creating, for a recipe  X, a recipe X_exec which contains a pre-link script that calls conda to install X and its dependencies in a separate environment.  The built recipe X_exec would then just contain the shadow scripts in bin/ corresponding to the executables that X puts in bin/ .   X_exec would have no dependencies except on conda, so other packages could list X_exec as a dependency without causing installation conflicts.  Then previously incompatible combinations of packages could co-exist in one environment.

Would this cause problems?

**Comment by daler** [comment]
Give it a try -- that'll be the best way to figure out what if any problems it would cause. I can't think of any show-stoppers off the top of my head.

**Comment by epruesse** [comment]
Not sure I understand OP

closing because stale
