### ISSUE TITLE
Unsync macos and linux release for pygtfk

### ISSUE THREAD

**Issue by guillaumecharbonnier** [bioconda/bioconda-recipes#22330]
The current releases for this package
https://anaconda.org/bioconda/pygtftk
 are unsync:
* linux-64  v1.1.2
* osx-64  v1.1.0

v1.1.2 update done by BiocondaBot is passing macOS tests so I do not know why it is not available?
https://github.com/bioconda/bioconda-recipes/runs/604937302

v1.1.0 was the last manual update. Coincidence?

**Comment by dpryan79** [comment]
The recipe has OSX skipped, likely due to build failures there. Maybe those were due to random CI issues and are now resolved, but if not please just remove the skip for OSX in a PR.
