### ISSUE TITLE
samtools 1.10 can't be installed

### ISSUE THREAD

**Issue by nahanoo** [bioconda/bioconda-recipes#22351]
Hi

The latest version of samtools 1.10 can't be installed not even in freshly setup conda environements.

Tried with python 3.6.8 and python 3.7.1.

Both installations fail caused by conflicts:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package _libgcc_mutex conflicts for:
python=3.7.1 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
samtools=1.10 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]

Package libgcc-ng conflicts for:
samtools=1.10 -> libgcc-ng[version='>=7.3.0']
samtools=1.10 -> ncurses[version='>=6.1,<6.2.0a0'] -> libgcc-ng[version='>=7.2.0']
```

**Comment by dpryan79** [comment]
`conda create -n samtools_foo samtools=1.10` works just fine.

**Comment by lculibrk** [comment]
I would like to mention that I am also unable to install samtools 1.10.

1. Make an empty conda env
```conda create -p env/```
2. try to install samtools >= 1.10
```conda install -c bioconda "samtools>=1.10"```
3. Receive this error:
```Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:
```

I did attempt this with the above command ```conda create -n samtools_foo samtools=1.10``` and also run into the same error. I'm running on centOS7 and conda 4.9.2.

**Comment by zhemingfan** [comment]
Debugging it with @lculibrk, it seems that running  `conda create -n samtools_foo samtools=1.10 -c bioconda -c conda-forge -c defaults` will work. Explicit channel ordering is important in this case.

**Comment by bounlu** [comment]
I have the same issue to install samtools=1.11 to the existing environment:

```
$ conda install samtools=1.11
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for mkl_fft dask pywavelets mkl_random numexpr optitype numba crossmap macs2 bottleneck scikit-image scikit-learn odo statsmodels bx-py/ o
```

It just takes forever.

**Comment by kp1203** [comment]
@lculibrk @bounlu I have the same error popping up. Could you solve the issue? Any help appreciated.

**Comment by bounlu** [comment]
@kp1203 I use 2 environments, so just installed the `samtools v1.11` to `py3` environment, which worked fine. My `py2` environment is more messy with tons of packages which probably cause the conflicts.

**Comment by lculibrk** [comment]
what fixed it for me as mentioned above:

`conda install -c bioconda -c conda-forge -c defaults samtools=1.11`
