### ISSUE TITLE
Issues with installing bioconductor-go.db with r-base=4.0

### ISSUE THREAD

**Issue by npavlovikj** [bioconda/bioconda-recipes#22389]
Hi,

I am trying to install `bioconductor-go.db` with `r-base=4.0`, e.g. `conda create -c conda-forge -c bioconda -c defaults -n bio_go r-base=4.0 bioconductor-go.db`.
However, during the "_Downloading and Extracting Packages_" step I am getting the following error:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: | ERROR conda.core.link:_execute_post_link_actions(658): An error occurred while installing package 'bioconda::bioconductor-go.db-3.11.1-r40_0'.
LinkError: post-link script failed for package bioconda::bioconductor-go.db-3.11.1-r40_0
running your command again with `-v` will provide additional information
location of failed script: /home/fedora/npavlovikj/.conda/envs/bio_go/bin/.bioconductor-go.db-post-link.sh
==> script messages <==
<None>
```

Looks like none of the links in post-link.sh script are valid:
```
URLS=(
  "https://bioconductor.org/packages/3.11/data/annotation/src/contrib/GO.db_3.11.1.tar.gz"
  "https://bioarchive.galaxyproject.org/GO.db_3.11.1.tar.gz"
  "https://depot.galaxyproject.org/software/bioconductor-go.db/bioconductor-go.db_3.11.1_src_all.tar.gz"
)
```

I don't know if this is an intermittent server issue or not, so I am just opening the issue in case someone can take a look at it.

Thank you,
Natasha

**Comment by dpryan79** [comment]
Ugh, Bioconductor removed the tarball. I'll update the version we have in bioconda and hope the Galaxy depot clones it before it gets deleted yet again. Yay reproducibility...

**Comment by dpryan79** [comment]
A fixed version should be available shortly

**Comment by npavlovikj** [comment]
Thank you so much Devon!
