### ISSUE TITLE
The `tag` package tries to import `microhapdb` instead

### ISSUE THREAD

**Issue by standage** [bioconda/bioconda-recipes#22485]
The bioconda bot detected the recent release of tag v0.5 and created an update PR (#22477), which I merged not too long ago (without checking: forgive me for I have sinned). It is showing up now in the bioconda channel, and installs without any errors, but when I attempt to run it I get the following error.

```
$ tag --help
Traceback (most recent call last):
  File "/home/standage/anaconda3/envs/tagtest/bin/tag", line 6, in <module>
    from microhapdb.__main__ import main
ModuleNotFoundError: No module named 'microhapdb'
```

That's strange, but indeed these are the contents of the CLI entry point.

```
$ cat /home/standage/anaconda3/envs/tagtest/bin/tag
#!/home/standage/anaconda3/envs/tagtest/bin/tag
# -*- coding: utf-8 -*-
import re
import sys

from microhapdb.__main__ import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

No idea why the tag library is trying to import the microhapdb library. The only connection I can think of is that I am a maintainer of both libraries.

**Comment by standage** [comment]
Manually replacing `microhapdb` with `tag` in `/home/standage/anaconda3/envs/tagtest/bin/tag` fixes the issue. But I don't have the foggiest idea how `microhapdb` ended up there in the first place.

**Comment by dpryan79** [comment]
Could the last PR updating the package have used the wrong source URL or something like that?

**Comment by mbargull** [comment]
@standage, please open a PR that changes the following line: https://github.com/bioconda/bioconda-recipes/pull/21425/files#diff-ecc4456b3846910b777dac0e3ce03267R15
(Also increment `build/number` by 1 ;)

**Comment by mbargull** [comment]
Also, highly recommended: If you add
```yaml
  commands:
    - tag --version
```
to the recipe's `test` section, the CI can check if it works.

**Comment by standage** [comment]
Thanks @mbargull, that's an embarrassingly easy fix. I have been using the tag conda package for over a month now without any issues, so I didn't look in the MOST OBVIOUS PLACE for the issue. I guess it turns out I have only been using the Python API (which is fine) and not the CLI, so I never saw this problem manifested.

Thanks again for the extra set of eyes!

**Comment by mbargull** [comment]
> embarrassingly easy fix.

I do like those ;). Happy to help.
