### ISSUE TITLE
perl travis builds on osx:

### ISSUE THREAD

**Issue by jerowe** [bioconda/bioconda-recipes#2248]
```
The following packages will be downloaded:

    package                    |            build

    ---------------------------|-----------------

    perl-log-log4perl-1.47     |                0         190 KB  local

The following NEW packages will be INSTALLED:

    libgcc:                 4.8.5-1   r       

    perl:                   5.22.0-9  bioconda

    perl-dbi:               1.634-2   bioconda

    perl-log-log4perl:      1.47-0    local   

    perl-pathtools:         3.40-0    bioconda

    perl-scalar-list-utils: 1.42-3    bioconda

    perl-threaded:          5.22.0-10 bioconda

Traceback (most recent call last):

  File "/anaconda/bin/conda-build", line 5, in <module>

    sys.exit(main())

  File "/anaconda/lib/python3.5/site-packages/conda_build/main_build.py", line 144, in main

    args_func(args, p)

  File "/anaconda/lib/python3.5/site-packages/conda_build/main_build.py", line 401, in args_func

    args.func(args, p)

  File "/anaconda/lib/python3.5/site-packages/conda_build/main_build.py", line 388, in execute

    build.test(m, activate=args.activate)

  File "/anaconda/lib/python3.5/site-packages/conda_build/build.py", line 776, in test

    test_file=join(tmp_dir, 'run_test.pl')))

KeyError: 'perl'

/Users/travis/build.sh: line 112:   570 Terminated: 15          travis_jigger $! $timeout $cmd
```

Anyone know what is happening here? I think it should be lvm or something for OSX instead of libgcc, but I'm not sure why that would be pulled in as a

**Comment by jerowe** [comment]
I'm seeing this problem again and again with perl builds on OSX. It keeps bringing in vanilla perl as a dependency, and then I get that the 'run_test.pl' fails.

Here is a travis build of perl-test-simple. It doesn't require any non core modules, just perl-threaded, and perl is still being pulled in as a dependency. Its making me kind of crazy, and I would like some insight. ;-)

**Comment by jerowe** [comment]
pinging @daler  and @bgruening . Whyyyyyyyy?

**Comment by daler** [comment]
My initial guess would be that there's something hard-coded in conda; I'll need to look closer at this.

**Comment by bgruening** [comment]
@jerowe does this still happen with the new conda build system?

**Comment by jerowe** [comment]
I'm not sure.

I've bit off more than I can chew with current projects, but I'll be getting back to conda builds SOON. I need to add some perl projects shortly, and I will keep an eye out.

**Comment by bgruening** [comment]
Will close this now. Please reopen if you still have problems.
