### ISSUE TITLE
error in installing meme

### ISSUE THREAD

**Issue by onkarnath89** [bioconda/bioconda-recipes#2272]
PASS: ama1
PASS: ama2
PASS: ame1
PASS: centrimo1
PASS: create-priors1
PASS: create-priors2
**FAIL:** dreme1 (CRASH!)
**FAIL:** dreme2 (CRASH!)
PASS: fasta-center1
**FAIL:** fasta-dinucleotide-shuffle1 (CRASH!)
PASS: fimo1
PASS: fimo2
PASS: fimo3
PASS: fimo4
**FAIL:** glam2_1 (CRASH!)
FAIL: glam2scan1 (CRASH!)
PASS: gomo1
PASS: gomo2
PASS: mast1
PASS: mast2
PASS: mast3
PASS: mast4
PASS: mast5
PASS: mast6
PASS: mast7
PASS: mast8
PASS: mast9
PASS: mast10
PASS: mast11
PASS: mast12
PASS: mast13
PASS: mast14
PASS: mast15
PASS: mast16
PASS: mast17
PASS: mast18
PASS: mcast1
PASS: meme1
PASS: meme2
PASS: meme3
PASS: meme4
PASS: meme5
PASS: meme6
PASS: meme_psp
PASS: motif-in.meme.crp0.text
PASS: motif-in.meme.crp0.xml
PASS: motif-in.meme.crp0.html
PASS: motif-in.meme.lipocalin.text
PASS: motif-in.meme.lipocalin.xml
PASS: motif-in.meme.lipocalin.html
PASS: motif-in.meme.puf3p.text
PASS: motif-in.meme.puf3p.xml
PASS: motif-in.meme.puf3p.html
PASS: motif-in.meme.crp0.extdna.text
PASS: motif-in.meme.crp0.extdna.xml
PASS: motif-in.meme.crp0.extdna.html
SKIP: motif-in.dreme.klf1.text (dreme.txt missing)
SKIP: motif-in.dreme.klf1.xml (dreme.xml missing)
SKIP: motif-in.dreme.klf1.html (dreme.html missing)
SKIP: motif-in.dreme.klf1.extdna.text (dreme.txt missing)
SKIP: motif-in.dreme.klf1.extdna.xml (dreme.xml missing)
SKIP: motif-in.dreme.klf1.extdna.html (dreme.html missing)
SKIP: motif-in.dreme.puf3p.text (dreme.txt missing)
SKIP: motif-in.dreme.puf3p.xml (dreme.xml missing)
SKIP: motif-in.dreme.puf3p.html (dreme.html missing)
PASS: motiph1
PASS: motiph2
PASS: psp-gen1
PASS: psp-gen2
PASS: psp-gen3
PASS: qvalue1
PASS: spamo1
PASS: spamo2
PASS: tomtom_allr
PASS: tomtom_ed
PASS: tomtom_kullback
PASS: tomtom_pearson
PASS: tomtom_sandelin
PASS: tomtom_blic1
PASS: tomtom_blic5
PASS: tomtom_allr_cs
PASS: tomtom_ed_cs
PASS: tomtom_kullback_cs
PASS: tomtom_pearson_cs
PASS: tomtom_sandelin_cs
PASS: tomtom_blic1_cs
# PASS: tomtom_blic5_cs
# Testsuite summary for meme 4.11.2
# TOTAL: 87
# PASS:  73
# SKIP:  9
# XFAIL: 0
# FAIL:  5
# XPASS: 0
# ERROR: 0

The above five failed installing. I searched for the error and found that there are issues in installing with python3, So I tried installing it with python 2.7.12 instead of python 3.5.2 and this time I got error in "glam2_1" only, all 86 others passed.
**### error with version 2.7.12 is:**
# RUN: glam2

---

Test glam2_1 ...
glam2 -M -r 3 -n 100 -O results/glam2_1 p common/At.s &> log
Writing results to output directory 'results/glam2_1'.
Run 1... 406 iterations
Run 2... 445 iterations
Run 3... 400 iterations

  File "/CPCFG_NAS_P1/ONKAR/Softwares/meme_4.11.2/scripts/glam2psfm", line 18
    print 'ALPHABET= ' + string.upper(''.join(letters))
                     ^
SyntaxError: invalid syntax
Program glam2psfm exited with value 1
## Warning: failed to convert output to MEME format motif!

glam2 exited with value 1 indicating failure.
FAILED!

**### The corresponding errors with version 3.5.2 are:**
# RUN: dreme

---

Test dreme1 ...
dreme -oc results/dreme1 -v 1 -p common/Klf1-200-100.s &> log
  File "/CPCFG_NAS_P1/ONKAR/Softwares/meme_4.11.2/scripts/dreme", line 760
    print "Finding secondary RE in left flank..."
                                                ^
## SyntaxError: Missing parentheses in call to 'print'

dreme exited with value 1 indicating failure.
FAILED!

---

Test dreme2 ...
dreme -norc -oc results/dreme2 -v 1 -p common/Klf1-200-100.s &> log
  File "/CPCFG_NAS_P1/ONKAR/Softwares/meme_4.11.2/scripts/dreme", line 760
    print "Finding secondary RE in left flank..."
                                                ^
## SyntaxError: Missing parentheses in call to 'print'

dreme exited with value 1 indicating failure.
FAILED!
# RUN: fasta-dinucleotide-shuffle

---

Test fasta-dinucleotide-shuffle1 ...
fasta-dinucleotide-shuffle -f common/Klf1-200-100.s -t -dinuc 1> results/fasta-dinucleotide-shuffle1/fasta-dinucleotide-shuffle_Bf5HW_stdout 2> log
Traceback (most recent call last):
  File "/CPCFG_NAS_P1/ONKAR/Softwares/meme_4.11.2/scripts/fasta-dinucleotide-shuffle", line 6, in <module>
    import alphabet
  File "/CPCFG_NAS_P1/ONKAR/Softwares/meme_4.11.2/scripts/alphabet.py", line 1096, in <module>
    predef = (dna(), rna(), protein())
  File "/CPCFG_NAS_P1/ONKAR/Softwares/meme_4.11.2/scripts/alphabet.py", line 1017, in dna
    factory.parseSymbol('A', "Adenine", 0xCC0000, complement='T')
  File "/CPCFG_NAS_P1/ONKAR/Softwares/meme_4.11.2/scripts/alphabet.py", line 451, in parseSymbol
    if not(isinstance(symbol, basestring) and len(symbol) == 1):
## NameError: name 'basestring' is not defined

fasta-dinucleotide-shuffle exited with value 1 indicating failure.
FAILED!
# RUN: glam2

---

Test glam2_1 ...
glam2 -M -r 3 -n 100 -O results/glam2_1 p common/At.s &> log
Writing results to output directory 'results/glam2_1'.
Run 1... 406 iterations
Run 2... 445 iterations
Run 3... 400 iterations

  File "/CPCFG_NAS_P1/ONKAR/Softwares/meme_4.11.2/scripts/glam2html", line 43
    alen = 4
           ^
TabError: inconsistent use of tabs and spaces in indentation
Program glam2html exited with value 1
Warning: failed to convert output to HTML!
  File "/CPCFG_NAS_P1/ONKAR/Softwares/meme_4.11.2/scripts/glam2psfm", line 18
    print 'ALPHABET= ' + string.upper(''.join(letters))
                     ^
SyntaxError: invalid syntax
Program glam2psfm exited with value 1
## Warning: failed to convert output to MEME format motif!

glam2 exited with value 1 indicating failure.
FAILED!
# RUN: glam2scan

---

Test glam2scan1 ...
glam2scan -O results/glam2scan1 p glam2/glam2.txt common/At.s &> log
Writing results to output directory 'results/glam2scan1'.
  File "/CPCFG_NAS_P1/ONKAR/Softwares/meme_4.11.2/scripts/glam2scan2html", line 24
    print '<html>'
                 ^
SyntaxError: Missing parentheses in call to 'print'
Program glam2scan2html exited with value 1
## Warning: failed to convert output to HTML!

glam2scan exited with value 1 indicating failure.
FAILED!

Kindly suggest me a solution to this issue.

**Comment by bgruening** [comment]
Are you running this under python3? Can you try it with python2?
@gregvonkuster is meme python3 ready?

**Comment by onkarnath89** [comment]
I also tried it with python 2
the details are included in the above message. I had one error of "glam2_1" with version 2.7.12. see detail at the starting of the error detail section above

**Comment by rvalieris** [comment]
meme install docs says python3 is not supported: http://meme-suite.org/doc/install.html

these errors:
```
print 'ALPHABET= ' + string.upper(''.join(letters))
^
SyntaxError: invalid syntax
```
shouldn't happen if you are running on python2, python3 requires parentheses around print(), my guess is that something in your setup is making the scripts run with python3 by mistake.

installing meme inside a env like: `conda create -n py2 python=2 meme`, should solve the problem.

**Comment by bgruening** [comment]
python3 is one problem that needs to be fixed by simply skipping it, an other is the failing test of `glam2_1`.
Who wants to work on this?

**Comment by rvalieris** [comment]
yea but what I am saying is that when I run the tests with python2 I don't get any errors, and the errors described in the post are the types you would get by using python3 by mistake.

```
============================================================================
Testsuite summary for meme 4.11.2
============================================================================
# TOTAL: 87
# PASS:  87
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

I will do a PR to skip python3 build, and I could also include these tests in the build.

**Comment by bgruening** [comment]
Thanks to @rvalieris this should be fixed.
