### ISSUE TITLE
Packages without a test-case

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#2276]
Here is a list of packages without tests defined.

No tests defined for: recipes/extract_fullseq/meta.yaml
No tests defined for: recipes/setuptools_cython/meta.yaml
No tests defined for: recipes/libgd/meta.yaml
No tests defined for: recipes/libgtextutils/meta.yaml
No tests defined for: recipes/perl-test-xml/meta.yaml
No tests defined for: recipes/perl-bioperl/meta.yaml
No tests defined for: recipes/backports.csv/meta.yaml
No tests defined for: recipes/perl-text-nsp/meta.yaml
No tests defined for: recipes/perl-html-entities-numbered/meta.yaml
No tests defined for: recipes/metavelvet-sl-feature-extraction/meta.yaml
No tests defined for: recipes/gettext/meta.yaml
No tests defined for: recipes/hubward-all/meta.yaml
No tests defined for: recipes/perl-pathtools/meta.yaml
No tests defined for: recipes/sparsehash/2.0.2/meta.yaml
No tests defined for: recipes/sparsehash/2.0.3/meta.yaml
No tests defined for: recipes/tidyp/meta.yaml
No tests defined for: recipes/jemalloc/meta.yaml
No tests defined for: recipes/trinity/meta.yaml
No tests defined for: recipes/migmap/meta.yaml
No tests defined for: recipes/bedtools/2.22/meta.yaml
No tests defined for: recipes/bedtools/2.20.1/meta.yaml
No tests defined for: recipes/bedtools/2.19.1/meta.yaml
No tests defined for: recipes/perl-timedate/meta.yaml
No tests defined for: recipes/perl-filesys-df/meta.yaml
No tests defined for: recipes/dwgsim/meta.yaml
No tests defined for: recipes/ocrad/0.21/meta.yaml
No tests defined for: recipes/perl-soap-lite/meta.yaml
No tests defined for: recipes/gmap/meta.yaml
No tests defined for: recipes/mugsy/meta.yaml
No tests defined for: recipes/perl-bioperl-core/meta.yaml
No tests defined for: recipes/perl-cpan-meta/meta.yaml
No tests defined for: recipes/schema/meta.yaml
No tests defined for: recipes/samtools/0.1.17/meta.yaml
No tests defined for: recipes/perl-math-base-convert/meta.yaml
No tests defined for: recipes/perl-bioperl-run/meta.yaml
No tests defined for: recipes/discovar/meta.yaml
No tests defined for: recipes/discovar-denovo/meta.yaml
No tests defined for: recipes/perl-uri/1.71/meta.yaml
No tests defined for: recipes/perl-io-string/meta.yaml
No tests defined for: recipes/fftw/meta.yaml
No tests defined for: recipes/lapack/meta.yaml
No tests defined for: recipes/cuneiform/1.1.0/meta.yaml
No tests defined for: recipes/sqlitebrowser/meta.yaml
No tests defined for: recipes/tbb/meta.yaml
No tests defined for: recipes/perl-template-toolkit/meta.yaml
No tests defined for: recipes/genepop/meta.yaml
No tests defined for: recipes/perl-bloom-faster/meta.yaml
No tests defined for: recipes/perl-yaml/meta.yaml
No tests defined for: recipes/pbgzip/meta.yaml
No tests defined for: recipes/tclap/1.2.1/meta.yaml
No tests defined for: recipes/kraken-all/meta.yaml
No tests defined for: recipes/kraken-all/0.10.5beta/meta.yaml
No tests defined for: recipes/python-magic/meta.yaml
No tests defined for: recipes/python-magic/0.4.6/meta.yaml
No tests defined for: recipes/networkxgmml/meta.yaml
No tests defined for: recipes/perl-moosex-fileattribute/meta.yaml
No tests defined for: recipes/fastx_toolkit/meta.yaml
No tests defined for: recipes/phylowgs/meta.yaml
No tests defined for: recipes/bitstring/meta.yaml
No tests defined for: recipes/fastdtw/meta.yaml
No tests defined for: recipes/blat/meta.yaml
No tests defined for: recipes/pytest-mock/meta.yaml
No tests defined for: recipes/popt/meta.yaml
No tests defined for: recipes/spectacle/meta.yaml
No tests defined for: recipes/perl-archive-zip/meta.yaml
No tests defined for: recipes/perl-math-vecstat/meta.yaml
No tests defined for: recipes/grabix/0.1.3/meta.yaml
No tests defined for: recipes/perl-math-bezier/meta.yaml
No tests defined for: recipes/sprinkles/meta.yaml
No tests defined for: recipes/requests-mock/meta.yaml
No tests defined for: recipes/tbl2asn/meta.yaml
No tests defined for: recipes/wham/meta.yaml
No tests defined for: recipes/glpk/meta.yaml
No tests defined for: recipes/perl-extutils-makemaker/meta.yaml
No tests defined for: recipes/pyopt/meta.yaml
No tests defined for: recipes/socksipy-branch/meta.yaml
No tests defined for: recipes/cd-hit/meta.yaml
No tests defined for: recipes/sentieon/meta.yaml
No tests defined for: recipes/perl-image-info/meta.yaml
No tests defined for: recipes/soapdenovo2-errorcorrection/meta.yaml
No tests defined for: recipes/gatk/meta.yaml
No tests defined for: recipes/gatk/3.5/meta.yaml
No tests defined for: recipes/perl-html-parser/meta.yaml
No tests defined for: recipes/metavelvet-sl/meta.yaml
No tests defined for: recipes/perl-dbi/meta.yaml
No tests defined for: recipes/htslib/meta.yaml
No tests defined for: recipes/perl-xml-twig/meta.yaml
No tests defined for: recipes/python-wget/meta.yaml
No tests defined for: recipes/gdal/meta.yaml
No tests defined for: recipes/viennarna/2.1.9/meta.yaml
No tests defined for: recipes/libdb/meta.yaml
No tests defined for: recipes/seqprep/meta.yaml
No tests defined for: recipes/libffi/meta.yaml
No tests defined for: recipes/libffi/3.0.13/meta.yaml
No tests defined for: recipes/perl-config-general/meta.yaml
No tests defined for: recipes/pytest-timeout/meta.yaml
No tests defined for: recipes/perl-mixin-linewise/meta.yaml
No tests defined for: recipes/wkhtmltopdf/meta.yaml
No tests defined for: recipes/graphicsmagick/1.3.20/meta.yaml
No tests defined for: recipes/metaseq-all/meta.yaml
No tests defined for: recipes/mirdeep2/meta.yaml
No tests defined for: recipes/perl-readonly/meta.yaml
No tests defined for: recipes/xmltodict/meta.yaml
No tests defined for: recipes/sga/meta.yaml

The perl onces are probably false-positives because many of them are using the run_tests.pl scripts. But we should check those and improve our test coverage.

**Comment by yesimon** [comment]
I know that kraken-all is a metapackage which probably shouldn't have tests. If there are any other metapackages they should probably also be filtered out.

**Comment by jerowe** [comment]
On a possibly related note, my boss, who is a real live scientist, is interested in having actual data to test against. He already has trimmed down data sets for many kinds of analysis, and we test all tools against our local data sets. 

For instance, we recently discovered that htseq needs a specific version of pysam to actually run its analysis. This is not something you would pick up on by simply importing the library. We are planning on using a CI service to test all pipelines on the test data, but I'm not sure if bioconda would be interested in having 'real' data as a part of its tests. I'm not sure how this would look from a technical point of view. Builds may get unmanageably long if running too many real data tests.

I contributed metavelvet-sl, so I'll take a look at that. I can also take a look at the perl packages during the contribution fest.

**Comment by bgruening** [comment]
@jerowe yes please fix a few packages!
Regarding your question of testing with real data you might want to contact the IUC. They do already have data and testing tools for Galaxy. E.g. here: https://github.com/galaxyproject/tools-iuc/tree/master/tools/htseq_count/test-data

**Comment by bgruening** [comment]
Anyone up to update this list and tackle a few recipes? It should be much less nowadays with linting in place.

**Comment by dpryan79** [comment]
I imagine these got blacklisted in the great migration to CB3, should this be closed then?

**Comment by epruesse** [comment]
yes. closing. we can re-open a new one if we need to.
