### ISSUE TITLE
bioconductor-org.hs.eg.db  download fail

### ISSUE THREAD

**Issue by Lix1993** [bioconda/bioconda-recipes#22806]
cannot download 3.11.1 by all 3 url,

3.11.4 can be downloaded by
https://bioconductor.org/packages/3.11/data/annotation/src/contrib/org.Hs.eg.db_3.11.4.tar.gz

**Comment by tinavisnovska** [comment]
Hi there, 

same goes for mouse, with the active download links being 

https://bioconductor.org/packages/3.11/data/annotation/src/contrib/org.Mm.eg.db_3.11.4.tar.gz
https://www.bioconductor.org/packages/release/data/annotation/src/contrib/org.Mm.eg.db_3.11.4.tar.gz

by the way, is there some sort of regular automated check to catch broken links like these?

**Comment by Lix1993** [comment]
thx
