### ISSUE TITLE
Conda does not install the latest version of samtools

### ISSUE THREAD

**Issue by rhpvorderman** [bioconda/bioconda-recipes#22824]
For some reason `conda create -n samtools samtools` suggests an environment with samtools 1.9.
1.10 is the newest version.

I have checked conda's version solver:
```
>>> from conda.models.version import VersionOrder
>>> VersionOrder("1.10") > VersionOrder("1.9")
True
>>> VersionOrder("1.10-2") > VersionOrder("1.9-8")
True
```

So that should work correctly. Is this something on bioconda's end?

**Comment by rhpvorderman** [comment]
#22820 Unearthed this issue.

**Comment by aichachikh1202** [comment]
conda install -c bioconda samtools=1.9 --force-reinstall
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed
