### ISSUE TITLE
Latest Bowtie2 build doesn't include version

### ISSUE THREAD

**Issue by rpetit3** [bioconda/bioconda-recipes#22836]
The current build of Bowtie2 does not output version number.
```
bowtie2 --version
/home/rpetit/miniconda3/envs/bactopia-1.3.1/bin/bowtie2-align-s version
...truncated...
```

The expected output is:
```
bowtie2 --version
/home/rpetit/miniconda3/envs/bactopia-1.3.1/bin/bowtie2-align-s version 2.4.1
...truncated...
```

After digging it looks like this is related to the change in: https://github.com/bioconda/bioconda-recipes/pull/22545 (specifically https://github.com/bioconda/bioconda-recipes/pull/22545/commits/5dd7114e3c358c36fa3defb2f9377c8bdf371adb).

Bowtie2 uses the `VERSION` file to specifiy the version (See: https://github.com/BenLangmead/bowtie2/blob/b4911f20a7a701df57dd1889d6eee0134d1ec895/Makefile#L328)

Related issue on Bowtie Repo: https://github.com/BenLangmead/bowtie2/issues/301

I can see about submitting a PR to bowtie2 that would allow VERSION to be set at command line instead of only being available from the file.

**Comment by cblume** [comment]
I was about to open this issue as well. A result of this bug is SAM headers missing the value to the `VN:` key, which renders the header--and in turn, the whole file--invalid.

**Comment by bernt-matthias** [comment]
Seems to be fixed in the latest version
