### ISSUE TITLE
bx-python intervaltrees work for python3. Can we allow bx-python for python3?

### ISSUE THREAD

**Issue by endrebak** [bioconda/bioconda-recipes#2288]
Can we allow bx-python to be installed on Python3? Many modules there do not work, but intervaltrees do and I desperately need them :) 

If so, how should I/we fix it?

https://github.com/bioconda/bioconda-recipes/issues/1639

**Comment by bgruening** [comment]
ping @jxtx

**Comment by endrebak** [comment]
We would need to change the yaml to:

```
test:
  imports:
    - bx.intervals
    # - the other modules that potentially work 
```

Perhaps we could have a `bx-python3` where we reduce the tests to only those modules that work? Seems suboptimal to not include anything from `bx-python` just because not all of it works in `python3`. I never use all bx-python modules at the same time, only 1 or at most 2 (interval and clustertrees both work in py3).

**Comment by endrebak** [comment]
Come to think of it, a much more hackish (but less intrusive) way to use bx-python in conda with python3 is just to do this in the `build.sh`:

```
pip install bx-python; $PYTHON setup.py install
```

If you would mind this for some reason, please tell me. I see it than better than not adding something to python3 in bioconda just because it uses intervaltrees.
