### ISSUE TITLE
URL to download miniconda script is incorrect format

### ISSUE THREAD

**Issue by mbhall88** [bioconda/bioconda-recipes#22889]
https://github.com/bioconda/bioconda-recipes/blob/3a4cba3197c24f1602a0efd398eab43c9f7b5456/.circleci/setup.sh#L69

It seems thats the [structure of the URLs has changed](https://repo.anaconda.com/miniconda/) in version 4.8.3 and now requires the python version too - or you can use latest.

Whereas before, the url would be `Miniconda3-4.7.12.1-Linux-x86_64.sh` it's now `Miniconda3-py38_4.8.3-Linux-x86_64.sh`

The result of this is the downloaded script is not as expected (it's a 404 HTML file) and running `./bootstrap.py /tmp/miniconda` fails

**Comment by mbargull** [comment]
Oops, should be fixed by https://github.com/bioconda/bioconda-recipes/commit/d39f158192c6f06e9fe978e89f9b56512497dc31.
Thanks for the report!
