### ISSUE TITLE
CellProfiler -- some images require Java Advanced Imaging library

### ISSUE THREAD

**Issue by raivivek** [bioconda/bioconda-recipes#22947]
```
Java Advanced Imaging (JAI) is required to read some TIFF files.
Please install JAI from https://jai.dev.java.net/
```

Perhaps there might be some way to package these into the recipe / provide install instructions.

**Comment by sunyi000** [comment]
can you please explain a bit more, what are you trying to do and are you getting exceptions with the cellprofiler recipe? 

thanks

**Comment by raivivek** [comment]
I think the issue is that CellProfile is unable to read TIFF files without the "Advanced Java Imaging" library. This is not really a bug with CellProfiler but would be nice to specify/install with the package recipe. Also, should `JAVA_HOME` be exported in the recipe?

In my case, I was trying to run CellProfiler in the container downloaded from quay.io

**Comment by bgruening** [comment]
@raivivek do you know if there is already a conda package for "Advanced Java Imaging"? If we would have one, we could easily add it as run-time dependency.

**Comment by raivivek** [comment]
I looked but couldn't find anything. Oracle's website was a mess. In the end, was able to download relevant packages from this blog post -- https://docs.geoserver.org/latest/en/user/production/java.html#installing-native-jai-on-linux. So I am not sure what is the best solution here.

**Comment by bgruening** [comment]
You can create a package if you like.
