### ISSUE TITLE
Announcement: Linux containers (Docker, rkt) for all conda packages

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#2297]
Dear @bioconda/all,

this is a small announcement to let you know that we succeeded in creating an very efficient Linux container for every\* Bioconda package. Yes, there are now 1338 [Docker](https://www.docker.com/) and [rkt](https://coreos.com/rkt/docs/latest/) containers build from your contributions to Bioconda, freely available for everyone!
## How does it work?

We have created a tool called [involucro](https://github.com/involucro/involucro) that can create containers based on a technology which we called `layer donning`. We have a build environment, here the `continuum/miniconda:latest` Docker image, and a run-time environment, `busybox`! We trigger a simple `conda install` inside the build-environment and copy the resulting layer over into the run-time environment. We end up with a `busybox` container and the parts that are specified in run time environment of your meta.yaml file. This is the smallest container that you can get for your tool.

A small presentation about layer donning (I know it’s now great, sorry) can be found here:

https://galaxy.slides.com/bgruening/docker-layer-donning/live#/

The new container is then pushed to [quay.io](https://quay.io/organization/biocontainers) and is available for everyone with a predictable container name. Quay.io offers not only `Docker` containers, but you can also get `rkt` containers if you prefer this technology.
## What does it mean?

Thanks to Travis we are able to build every 24h all new packages from Bioconda for you, completely automatically. As soon as your PR is merged we are mirroring all tarballs for you (see https://github.com/bioconda/bioconda-recipes/issues/2194) and from now on we are building a container for every single package you submit, plus every new version.

The users of your tool can decide if they prefer to use Docker or Conda and they will get exactly the same package (same compilation settings, etc.) either way. This is especially useful for systems like snakemake or Galaxy where a global configuration can decide which dependency mechanism a user prefers.

Hope you like it!
We would be very happy about any feeback!
Jonas and Bjoern

**Comment by kyleabeauchamp** [comment]
Once again great work by @bgruening, looking forward to test it out.

**Comment by hainm** [comment]
Fantastic. Thanks.

**Comment by daler** [comment]
@bgruening, this is awesome. Amazing work.

**Comment by gregvonkuster** [comment]
@bgruening You rock!!  Thanks!

**Comment by roryk** [comment]
sick!

**Comment by thriqon** [comment]
It's nice to hear that you folks like it :) If you want to know more about the usage of different base images that @bgruening mentioned just tell me.

And we're looking for help... If anybody knows a slick way to get the list of recently (i.e. since yesterday) updated packages directly from the Conda repository, you'll be our hero!

**Comment by dmaticzka** [comment]
nice!

**Comment by mwolfien** [comment]
That's "a thing"! =)

**Comment by jerowe** [comment]
This is so cool!

@thriqon , this could be accomplished using the binstar api. I do something similar for our conda packages. I can't work on it today, but I should be able to get it written for you by the end of tomorrow.

**Comment by snewhouse** [comment]
@bgruening this is amazing!

**Comment by jerowe** [comment]
@thriqon 

```python
from binstar_client.commands.authorizations import utcnow
from dateutil.parser import parse as parse_date
from binstar_client.utils import get_server_api

aserver_api = get_server_api()
now = utcnow()
days_since_upload = 2

##Get a list of bioconda packages
packages = aserver_api.user_packages('bioconda')

##Get a particular package
package = aserver_api.package('bioconda', 'htseq')

for package in packages:
    versions = package['versions']

def get_distros(package, versions):

    for version in versions:
        release = aserver_api.release('bioconda', package, version)
        distros = release['distributions']
        get_time_diff(distros)

def get_time_diff(distros):

    for distro in distros:
        upload_time = distro['upload_time']
        upload_time_obj = parse_date(upload_time)
        time_diff = now - upload_time_obj
        if time_diff.days > days_since_upload:
            do_docker_things(distro)

def do_docker_things(distro):
    """ Docker things! """
    full_name = distro['full_name']
    l = full_name.split("/")

    #Get the package name back from the full name - or save it in a class?
    name = l[1]
    version = l[2]
    pass
```

**Comment by bgruening** [comment]
Thanks for all your positive comments! I'm also really excited and see so many potential in it.
@jerowe thanks for this snippet, this will help us to improve at least the bioconda integration. Unfortunately, `default` does not store the `meta.yaml` in its packages and we need this file to extract the test cases. So I think at least for `default` and `r` we still need to clone the github repos.

Anyhow, from here on we can improve things and get more conda repositories build automatically. Let's see if the conda-forge guys are interested in this technology.

Thanks again to you all for this encouraging feedback.

**Comment by jerowe** [comment]
@bgreuning, what do you mean? The original source url?

```bash
➜  ~ anaconda show anaconda/scipy/0.18.0                                          
Using Anaconda API: https://api.anaconda.org
version 0.18.0
   + linux-32/scipy-0.18.0-np111py27_0.tar.bz2
   + linux-32/scipy-0.18.0-np111py27_nomkl_0.tar.bz2
   + linux-32/scipy-0.18.0-np111py34_0.tar.bz2
   + linux-32/scipy-0.18.0-np111py34_nomkl_0.tar.bz2
   + linux-32/scipy-0.18.0-np111py35_0.tar.bz2
   + linux-32/scipy-0.18.0-np111py35_nomkl_0.tar.bz2
   + linux-64/scipy-0.18.0-np111py27_0.tar.bz2
   + linux-64/scipy-0.18.0-np111py27_nomkl_0.tar.bz2
   + linux-64/scipy-0.18.0-np111py34_0.tar.bz2
   + linux-64/scipy-0.18.0-np111py34_nomkl_0.tar.bz2
   + linux-64/scipy-0.18.0-np111py35_0.tar.bz2
   + linux-64/scipy-0.18.0-np111py35_nomkl_0.tar.bz2
   + osx-64/scipy-0.18.0-np111py27_0.tar.bz2
   + osx-64/scipy-0.18.0-np111py27_nomkl_0.tar.bz2
   + osx-64/scipy-0.18.0-np111py34_0.tar.bz2
   + osx-64/scipy-0.18.0-np111py34_nomkl_0.tar.bz2
   + osx-64/scipy-0.18.0-np111py35_0.tar.bz2
   + osx-64/scipy-0.18.0-np111py35_nomkl_0.tar.bz2
   + win-32/scipy-0.18.0-np111py27_0.tar.bz2
   + win-32/scipy-0.18.0-np111py34_0.tar.bz2
   + win-32/scipy-0.18.0-np111py35_0.tar.bz2
   + win-64/scipy-0.18.0-np111py27_0.tar.bz2
   + win-64/scipy-0.18.0-np111py34_0.tar.bz2
   + win-64/scipy-0.18.0-np111py35_0.tar.bz2
None
➜  ~ anaconda show anaconda/scipy/0.18.0/linux-64/scipy-0.18.0-np111py35_0.tar.bz2
Using Anaconda API: https://api.anaconda.org
linux-64/scipy-0.18.0-np111py35_0.tar.bz2
no description

owner                    : 'anaconda'
size                     : 31976434
upload_time              : '2016-07-27 09:22:45.758000+00:00'
type                     : 'conda'
full_name                : 'anaconda/scipy/0.18.0/linux-64/scipy-0.18.0-np111py35_0.tar.bz2'
download_url             : '//api.anaconda.org/download/anaconda/scipy/0.18.0/linux-64/scipy-0.18.0-np111py35_0.tar.bz2'
version                  : '0.18.0'
md5                      : '91a36c34aa4882de0ba4e67ccea8c730'
distribution_type        : 'conda'
dependencies             : []
labels                   : ['main']
ndownloads               : 176
Metadata:
    + depends                  : ['libgfortran 3.0.0', 'mkl 11.3.3', 'numpy 1.11*', 'python 3.5*']
    + license                  : 'BSD'
    + date                     : '2016-07-25'
    + build                    : 'np111py35_0'
    + platform                 : 'linux'
    + version                  : '0.18.0'
    + build_number             : 0
    + requires                 : []
    + arch                     : 'x86_64'
    + name                     : 'scipy'
```

'api.anaconda.org/download/anaconda/scipy/0.18.0/linux-64/scipy-0.18.0-np111py35_0.tar.bz2', is an actual url.

I am very interested in how this works. ;-)

**Comment by kyleabeauchamp** [comment]
cc @etal  did you see this?  https://quay.io/repository/mulled/cnvkit claims you can do `docker pull quay.io/mulled/cnvkit`.

**Comment by bgruening** [comment]
More precisely `docker pull quay.io/mulled/cnvkit:0.8.0--py35_0`. I do not currently create a `default` image. So you need to specify the version.
Maybe this small script is useful. https://github.com/mulled/auto-mulled/blob/master/mulled.py

You can do something like: `mulled.py -s cnvkit` to see all versions.

**Comment by etal** [comment]
This looks great. I'd like to point CNVkit users to this instead of the hand-rolled one on [Docker Hub](https://hub.docker.com/r/etal/cnvkit/), which I've been building less efficiently from the Dockerfile in CNVkit's repo. How would you recommend I do that? Is there a command I can put in README that includes the string "biodocker", or should I use the line above?

**Comment by bgruening** [comment]
@etal please test before :)
Currently, the URL is all what I have and this URL will stay. I'm in contact with the biodocker guys and mulled will at some point be renamed either to biodocker or biocontainers. But this will take a while.

**Comment by bgruening** [comment]
A small update we have now `1690` containers and we are using now the `biocontainers` name space. I have updated the description above accordingly.

**Comment by bgruening** [comment]
Short update we do have 1800 containers now available via biocontainers. @daler has incorporated the mulled in the new build-system which is explained in https://github.com/bioconda/bioconda-recipes/issues/2695.

This means we are now testing all packages in a busybox, which should ensure high-quality packages.

**Comment by bgruening** [comment]
Short update before I close this issue, we just passed the 2500 containers on https://quay.io/organization/biocontainers

**Comment by lucapinello** [comment]
Amazing!
