### ISSUE TITLE
Falling back to numpy 1.11 even though numpy is pinned to later version?

### ISSUE THREAD

**Issue by dpellow** [bioconda/bioconda-recipes#22974]
Under the test-linux building and testing section I see the following message:
`CONDA_BUILD WARNING No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11`
Why is it ignoring the pinned value of numpy in my requirements section?

**Comment by nfahlgren** [comment]
I think it always reports that in the log when it's setting up the conda build environment. For my recipe, it reports the same but when it goes on to install package dependencies it installs a newer version of NumPy.

**Comment by dpellow** [comment]
Thanks, that seems to be correct.
