### ISSUE TITLE
https with cmake

### ISSUE THREAD

**Issue by jerowe** [bioconda/bioconda-recipes#2319]
Hello,

I'm not 100% sure this is an error with the bioconda curl, so bear with me here.

I have a conda env that I use just for building - with cmake, autoconf, automake, gcc, zlib, and ssl installed.

```
Scanning dependencies of target jemalloc
make[3]: Leaving directory `/scratch/gencore/.local/source/neovim-0.1.5/.deps'
make[3]: Entering directory `/scratch/gencore/.local/source/neovim-0.1.5/.deps'
[  1%] Creating directories for 'jemalloc'
[  2%] Performing download step for 'jemalloc'
-- file: /scratch/gencore/.local/source/neovim-0.1.5/.deps/build/downloads/jemalloc/jemalloc-4.2.1.tar.bz2
-- downloading...
     src='https://github.com/jemalloc/jemalloc/releases/download/4.2.1/jemalloc-4.2.1.tar.bz2'
     dst='/scratch/gencore/.local/source/neovim-0.1.5/.deps/build/downloads/jemalloc/jemalloc-4.2.1.tar.bz2'
     timeout='none'
CMake Error at /scratch/gencore/.local/source/neovim-0.1.5/third-party/cmake/DownloadAndExtractFile.cmake:74 (message):
  error: downloading
  'https://github.com/jemalloc/jemalloc/releases/download/4.2.1/jemalloc-4.2.1.tar.bz2'
  failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1
```

`which curl` gives me the correct curl.

```
[gencore@login-0-2 neovim-0.1.5]$ :ldd `which curl`
        linux-vdso.so.1 =>  (0x00007ffcf7aa8000)
        libcurl.so.4 => /scratch/gencore/.local/easybuild/software/gencore_build/1.0/bin/../lib/libcurl.so.4 (0x00007f1b050db000)
        libssl.so.1.0.0 => /scratch/gencore/.local/easybuild/software/gencore_build/1.0/bin/../lib/libssl.so.1.0.0 (0x00007f1b04e64000)
        libcrypto.so.1.0.0 => /scratch/gencore/.local/easybuild/software/gencore_build/1.0/bin/../lib/libcrypto.so.1.0.0 (0x00007f1b04a2d000)
        libz.so.1 => /scratch/gencore/.local/easybuild/software/gencore_build/1.0/bin/../lib/libz.so.1 (0x00007f1b04817000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f1b04601000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f1b04240000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f1b0403c000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1b03e1f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1b0533e000)
```

Looks right too.

I can run 

```
 curl -sSL https://bootstrap.pypa.io/get-pip.py 
```

Just fine.

Ideas?

**Comment by jerowe** [comment]
Ah.

Its actually that cmake is compiled without ssl support.

Any votes against me adding a cmake with ssl support to the bioconda channel? This would be very handy for me to have, but I don't now if its useful for anyone else.

**Comment by jerowe** [comment]
Doesn't conda forge build against centos6? That would make many recipes unusable for anyone still relying on the centos5 architecture.

**Comment by bgruening** [comment]
Yes they do. But CentOS5 is running out of supported soon and joining the conda-forge has so many advantages.

**Comment by jerowe** [comment]
I think a lot of HPC centers are still on centos 5. We only just switched. I suppose if centos5 support is going away at least some of these will upgrade.

I don't know a whole lot about conda forge. I see they have their own perl - 5.20 I think. It looks like there are lots of cool things happening over there, and they have all my desired build tools!

I'm still working on testing it out. I was getting an error about missing libiconv when using switching to conda forge for this particular build process. When using the precompiled cmake binary from the cmake website I didn't have it. This may be fixed by installing libiconv from conda forge. ;-)

**Comment by jerowe** [comment]
For anyone else who was wondering I was able to get around the issue of conda-forge having its own perl by simply not subscribing to conda-forge, but creating a separate environment with conda-forge build tools.
