### ISSUE TITLE
PlantCV -- autobump to 3.9.0 fails with libGL ImportError

### ISSUE THREAD

**Issue by nfahlgren** [bioconda/bioconda-recipes#23434]
Hi all,

The updated recipe for PlantCV (autobump from 3.8.0 to 3.9.0) in PR #23305 is failing with the error:

```
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

I tweaked the recipe a little based on https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl in case something was updated, but now I'm stuck.

We have been using `extended-base: true` and looking back at the previous build that worked I could find in the logs that it was using this container, but I don't see that now in the current CircleCI logs (not 100% sure though). 

Appreciate the help!

**Comment by yamrzou** [comment]
Got that error in one of my projects, it was due to opencv-python being upgraded to 4.3.0.38 .
Downgrading to 4.3.0.36 seems to fix it.

**Comment by nfahlgren** [comment]
Thanks @yamrzou! This recipe uses OpenCV 3.4.9 currently. Our previous release that was built successfully used the same opencv package version.
