### ISSUE TITLE
Make sure that all Python packages are rebuilt with Python 3.5

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#235]
This should in fact happen automatically, but we should check whether that is really the case.

**Comment by kyleabeauchamp** [comment]
@johanneskoester it appears that some packages have old versions for py34 but new versions for py35.  

For example, if someone tries to install `snakemake` in a py34 environment, they are directed to version 3.4.2.  https://anaconda.org/bioconda/snakemake/files

I'm not sure what the best decision here is, as it seems like we want to either "force py35 and delete the old" or ensure that py34 is still being updated.

**Comment by johanneskoester** [comment]
Good point. I think we could keep the last two Python versions for convenience, see pull request #396.

**Comment by johanneskoester** [comment]
Pull request has been merged.
