### ISSUE TITLE
Env issue

### ISSUE THREAD

**Issue by kyleabeauchamp** [bioconda/bioconda-recipes#2359]
Hey, wanted to cross-post this env issue I've observed over the past couple of months in case someone else observed it:

https://github.com/conda/conda/issues/3478

**Comment by kyleabeauchamp** [comment]
cc @johanneskoester  According to commends on the external thread, the `conda env update` command is allegedly semi-busted.  I don't think you used that in your Snakemake env work (or herein), but I figured I'd ping you just in case for an FYI.

**Comment by johanneskoester** [comment]
Thanks for the hint! I hope they'll fix it soon!
