### ISSUE TITLE
ln adds lots of placehold

### ISSUE THREAD

**Issue by iquasere** [bioconda/bioconda-recipes#23771]
The meta.yaml in pull request #23759 has a symbolic link created with ```ln -s "${dir}/scripts/mosca.py" "${PREFIX}/bin/"```.  Running the local build I get
```
BIOCONDA INFO (OUT) ln: creating symbolic link `/opt/conda/conda-bld/mosca_1596617450339/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/mosca.py': No such file or directory
```
Where do all those placehold come from??

**Comment by simonbray** [comment]
answered here: https://github.com/bioconda/bioconda-recipes/pull/23759#issuecomment-669237184
