### ISSUE TITLE
Unintended release?

### ISSUE THREAD

**Issue by iprada** [bioconda/bioconda-recipes#23780]
Dear bioconda developers,

I am the maintainer of Circle-Map. https://anaconda.org/bioconda/circle-map

I see that a new file was uploaded 10 days ago. However, I didn't do anything to release it. Is this an intended behaviour?

Best 

Inigo

**Comment by bgruening** [comment]
@iprada welcome!

Yes, kindof. We do have a bot that creates automaticly PRs and if they are reviewed, those PRs can be merged. We have implemented this to make your life easier.

**Comment by iprada** [comment]
I see. That is great. Thanks!
