### ISSUE TITLE
Merged package not available

### ISSUE THREAD

**Issue by joachimwolff** [bioconda/bioconda-recipes#23797]
Hi,

yesterday I merged `schicexplorer` version 5 to bioconda, however, a search for `conda search -c bioconda schicexplorer` shows me it is not available and the newest version is version 4. 

On the anaconda cloud, version 5 is listed available since around 20 h: https://anaconda.org/bioconda/schicexplorer/files

Any ideas?

Best,

Joachim

**Comment by bgruening** [comment]
The CDN mirroring is not working at the moment. See also https://gitter.im/bioconda/Lobby
