### ISSUE TITLE
R 3.3 migration

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#2404]
Opening this as a catch-call for all R 3.3-related issues.
### What's happening and why

We really want to have R and Bioconductor packages built for R 3.3. But it gets tricky.

Conda looks for a `$CONDA_R` environmental variable when building packages dependent on R. In bioconda, this is configured in [scripts/env_matrix.yml](https://github.com/bioconda/bioconda-recipes/blob/master/scripts/env_matrix.yml). When bioconda started we built everything for R 3.2 and did not anticipate the large number of R recipes that would be contributed. If we were to simply change `$CONDA_R` to "3.3" then our build system on travis-ci would time out because it would see that every single R recipe in bioconda would need to be updated.

To get around this we wrote and started using [bioconda-utils](https://github.com/bioconda/bioconda-utils) for our build system, which supports blacklists to force-disable the building of listed packages. Now we can put all R recipes on that blacklist (the aptly-named [`r-blacklist`](https://github.com/bioconda/bioconda-recipes/blob/master/r-blacklist)), change `$CONDA_R` to "3.3", and travis-ci will not timeout trying to build everything.

Now all we have to do is incrementally un-comment recipes in `r-blacklist` in topologically-sorted order, right?  But we run into more problems. CRAN and Bioconductor store only the most recent version of a package on their servers. So if we uncomment an R recipe from the blacklist, say, `bioconductor-ropls`, it is likely to fail because `bioconductor-ropls 1.4.2` [source url](http://bioconductor.org/packages/release/bioc/src/contrib/ropls_1.4.2.tar.gz)  no longer exists but [1.4.4](https://bioconductor.org/packages/release/bioc/src/contrib/ropls_1.4.4.tar.gz) does, at least at the time of this writing. So the `bioconductor-ropls` recipe needs to be fixed and updated accordingly. This process needs to be done for each of the 350+ R packages we have. 

Furthermore, much has changed in bioconda since the first R packages were added. For example we now require that any packages using gcc must depend on the conda package; we are now building on CentOS6; and we are now templating dependencies like Boost. This requires manually updating older packages.

While some of this migration can be automated, much can not (see our [bioconductor recipe docs](https://github.com/bioconda/bioconda-recipes/tree/master/scripts/bioconductor) for some autmation helpers). As a result, this migration will be an iterative process of uncommenting some recipes and then reading through the travis-ci logs to see what failed, fixing them and trying again.

So: please bear with us and report any issues you find here.
## Issues identified so far

Here's a running list of things that need to be fixed. 

For now I'm keeping them (as well as any packages that depend on them) on the blacklist just to be able to keep moving and identify all problems. Once the bulk of packages have been migrated to R3.3 we can start working through these issues.

If anyone's looking for a small slice to help out on, these would be good targets:
- `r-ash` needs `lsb_release`; source probably needs patching
  - dependency of `r-ggalt`, `r-hdrcde`, `r-rainbow`, `bioconductor-bubbletree`
- `rsem` is giving zlib errors (even after adding `zlib` as dependency). Likely needs patching
- `r-phonr` loops indefinitely when trying to build. Not sure why.
- `r-blockmodeling` has gfortran errors
  - dependency of `bioconductor-ebseq`
- `bioconductor-dnacopy` has gfortran errors
  - dependency of `bioconductor-cghcall`, `bioconductor-qdnaseq`, `cnvkit`, `r-pscbs`
- missing URLs for older versions of `bioconductor-limma`, `bioconductor-s4vectors`

**Comment by bgruening** [comment]
Just to add, this will hopefully get easier as we are mirroring tarballs from now on. So at least this will be a non-issue in the future.

**Comment by jerowe** [comment]
Thanks for the all the work! It will be awesome to have multiple versions of R. ;-)

I'm wondering, will all packages still exist for R 3.2?

Also, I would like to get working on updating at least my contributions, and obviously there dependency trees. I'm not sure how to go about doing this. Could you please advise?

In terms of building, I'm still doing my local building against the bioconda-builder docker image before commiting and moving to travis. Should I now be building against the conda-forge/linux-anvil?

**Comment by bgruening** [comment]
All old packages will stay. Only your packages will not really help, or it would make more work to find out the dependencies of your packages. But you could help to comment out the blacklist step-by-step and rebuild packages. The bioconductor packages are the most problematic once as the tarballs are often missing for a rebuild.

Yes you would need to test your build against conda-forge/linux-anvil, but I think all test that pass against the bioconda container will also pass against the new one. We will update the documentation soon.

**Comment by jerowe** [comment]
Is the blacklist already sorted? I don't mind just starting from whichever direction I should work from and going up until I hit mine.

**Comment by bgruening** [comment]
Yes, look at this PR: https://github.com/bioconda/bioconda-recipes/pull/2414
Similar to this. Thanks for your help.

**Comment by jerowe** [comment]
Got it. I will try to get some work done on it in the next few days.

**Comment by bgruening** [comment]
I hope we are done in a few days ;)

**Comment by daler** [comment]
@bgruening just noticed that recipes that specify an R version are not being picked up as needing a rebuild. First noticed this in `bioconductor-dupradar` in #2456.

```bash
grep -ER "\- .r\s" recipes | grep meta.yaml  | sort | uniq
```

```
Binary file recipes/bioconductor-complexheatmap/.meta.yaml.swp matches
recipes/bioconductor-affyio/meta.yaml:    - 'r >=2.6.0'
recipes/bioconductor-affy/meta.yaml:    - 'r >=2.8.0'
recipes/bioconductor-annotate/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-annotationdbi/meta.yaml:    - 'r >=2.7.0'
recipes/bioconductor-annotationforge/meta.yaml:    - 'r >=2.7.0'
recipes/bioconductor-ballgown/meta.yaml:    - 'r >=2.7.0'
recipes/bioconductor-biobase/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-biocinstaller/meta.yaml:    - 'r >=3.2.0'
recipes/bioconductor-biomformat/meta.yaml:    - 'r >=3.2.0'
recipes/bioconductor-biostrings/meta.yaml:    - 'r >=2.8.0'
recipes/bioconductor-biovizbase/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-bsgenome/meta.yaml:    - 'r >=2.8.0'
recipes/bioconductor-bubbletree/meta.yaml:    - 'r >=3.2.1'
recipes/bioconductor-bumphunter/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-camera/1.22.0/meta.yaml:    - 'r >=2.1.0'
recipes/bioconductor-camera/1.26.0/meta.yaml:    - 'r >=2.1.0'
recipes/bioconductor-cexor/meta.yaml:    - 'r >=2.10.0'
recipes/bioconductor-cghbase/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-cghcall/meta.yaml:    - 'r >=2.0.0'
recipes/bioconductor-chipseeker/meta.yaml:    - 'r >=3.1.0'
recipes/bioconductor-clusterprofiler/meta.yaml:    - 'r >=3.1.0'
recipes/bioconductor-cn.mops/meta.yaml:    - 'r >=2.12'
recipes/bioconductor-complexheatmap/meta.yaml:    - 'r >=3.1.2'
recipes/bioconductor-csaw/meta.yaml:    - 'r >=3.2.0'
recipes/bioconductor-cummerbund/meta.yaml:    - 'r >=2.7.0'
recipes/bioconductor-dada2/meta.yaml:    - 'r >=3.2.0'
recipes/bioconductor-degreport/meta.yaml:    - 'r >=3.2.0'
recipes/bioconductor-diffbind/meta.yaml:    - 'r >=3.2.2'
recipes/bioconductor-do.db/meta.yaml:    - 'r >=2.7.0'
recipes/bioconductor-dose/meta.yaml:    - 'r >=3.1.0'
recipes/bioconductor-dupradar/meta.yaml:    - 'r >=3.2.0'
recipes/bioconductor-ebseq/meta.yaml:    - 'r >=3.0.0'
recipes/bioconductor-edger/3.12.1/meta.yaml:    - 'r >=2.15.0'
recipes/bioconductor-edger/meta.yaml:    - 'r >=2.15.0'
recipes/bioconductor-flowai/meta.yaml:    - 'r >=3.2'
recipes/bioconductor-flowcl/meta.yaml:    - 'r >=3.0.2'
recipes/bioconductor-flowcore/meta.yaml:    - 'r >=2.10.0'
recipes/bioconductor-flowdensity/meta.yaml:    - 'r >=2.10.0'
recipes/bioconductor-fourcseq/meta.yaml:    - 'r >=3.0'
recipes/bioconductor-gagedata/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-gage/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-genelendatabase/1.6.0/meta.yaml:    - 'r >=3.1.0'
recipes/bioconductor-geneplotter/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-genomeinfodb/meta.yaml:    - 'r >=3.1'
recipes/bioconductor-genomicalignments/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-genomicranges/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-ggtree/meta.yaml:    - 'r >=3.2.0'
recipes/bioconductor-go.db/meta.yaml:    - 'r >=2.7.0'
recipes/bioconductor-gosemsim/meta.yaml:    - 'r >=3.1.0'
recipes/bioconductor-goseq/1.22.0/meta.yaml:    - 'r >=2.11.0'
recipes/bioconductor-gostats/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-graphite/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-graph/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-gseabase/meta.yaml:    - 'r >=2.6.0'
recipes/bioconductor-gviz/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-hpar/meta.yaml:    - 'r >=2.15'
recipes/bioconductor-illuminamousev2.db/meta.yaml:    - 'r >=2.7.0'
recipes/bioconductor-impute/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-iranges/2.4.6/meta.yaml:    - 'r >=3.1.0'
recipes/bioconductor-isomirs/meta.yaml:    - 'r >=3.2'
recipes/bioconductor-jmosaics/meta.yaml:    - 'r >=2.15.2'
recipes/bioconductor-kegg.db/meta.yaml:    - 'r >=2.7.0'
recipes/bioconductor-limma/3.26.7/meta.yaml:    - 'r >=2.3.0'
recipes/bioconductor-limma/3.28.2/meta.yaml:    - 'r >=2.3.0'
recipes/bioconductor-limma/3.28.6/meta.yaml:    - 'r >=2.3.0'
recipes/bioconductor-limma/meta.yaml:    - 'r >=2.3.0'
recipes/bioconductor-marray/meta.yaml:    - 'r >=2.10.0'
recipes/bioconductor-metams/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-mgug4122a.db/meta.yaml:    - 'r >=2.7.0'
recipes/bioconductor-mmdiff/meta.yaml:    - 'r >=2.14.0'
recipes/bioconductor-mosaics/meta.yaml:    - 'r >=3.0.0'
recipes/bioconductor-multtest/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-organismdbi/meta.yaml:    - 'r >=2.14.0'
recipes/bioconductor-org.dm.eg.db/meta.yaml:    - 'r >=2.7.0'
recipes/bioconductor-org.hs.eg.db/meta.yaml:    - 'r >=2.7.0'
recipes/bioconductor-org.mm.eg.db/meta.yaml:    - 'r >=2.7.0'
recipes/bioconductor-pathview/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-phyloseq/meta.yaml:    - 'r >=3.2.0'
recipes/bioconductor-qdnaseq/meta.yaml:    - 'r >=3.1.0'
recipes/bioconductor-qvalue/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-rcytoscape/meta.yaml:    - 'r >=2.14.0'
recipes/bioconductor-rgraphviz/2.13.0/meta.yaml:    - 'r >=2.6.0'
recipes/bioconductor-rgraphviz/meta.yaml:    - 'r >=2.6.0'
recipes/bioconductor-rtracklayer/meta.yaml:    - 'r >=2.10'
recipes/bioconductor-s4vectors/0.8.7/meta.yaml:    - 'r >=3.1.0'
recipes/bioconductor-summarizedexperiment/1.0.2/meta.yaml:    - 'r >=3.2'
recipes/bioconductor-sva/meta.yaml:    - 'r >=2.8'
recipes/bioconductor-topgo/meta.yaml:    - 'r >=2.10.0'
recipes/bioconductor-variantannotation/meta.yaml:    - 'r >=2.8.0'
recipes/bioconductor-vsn/meta.yaml:    - 'r >=2.1'
recipes/bioconductor-xcms/1.44.0/meta.yaml:    - 'r >=2.14.0'
recipes/bioconductor-xcms/1.46.0/meta.yaml:    - 'r >=2.14.0'
recipes/bioconductor-xvector/meta.yaml:    - 'r >=2.8.0'
```

Looks like these are all bioconductor packages, so the bioconductor skeleton script probably needs to be fixed to not pay attention to R version restrictions. For this R3.3 migration I think we should just change these all to plain old `r`.

**Comment by bgruening** [comment]
Sounds good to me. I will be busy today, sorry. I think we can change this in on PR without rebuilding in the same PR?

**Comment by daler** [comment]
@bgruening the default [limma](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-limma/meta.yaml#L6) specifies https://depot.galaxyproject.org/software/limma/limma_3.28.10_src_all.tar.gz which I'm getting a 404 on. Other tarballs seem available in https://depot.galaxyproject.org/software/limma. I'll switch limma to the bioaRchive tarball for now, but wanted to give you a heads up in case it indicates a problem with cargo port.

**Comment by daler** [comment]
@bgruening also, the [older limma package directories](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/bioconductor-limma) won't work since they specify versions that don't exist in bioaRchive. I will keep them blacklisted for now.

**Comment by bgruening** [comment]
I'm not sure if we should close this. I feel the R3.3.1 migration is done, but we should find a solution to pin for R3.3*.

**Comment by johanneskoester** [comment]
To give you an update, I have r-base 3.3.2 in conda-forge. I am still working on getting all other packages from the R channel into conda-forge. It turns out that they need to change their build system in order to properly support this. They are really trying their best, but progress is quite slow. Unfortunately, the feedstock approach makes the whole process even more complicated.

**Comment by johanneskoester** [comment]
Apart from that, I just noticed that the bioconductor packages depend on the `r` package. Shouldn't they depend on `r-base`?

**Comment by bgruening** [comment]
@johanneskoester I think this issue here is separated from the conda-forge migration.
Some users have the need to use R3.3.2 and we are pinning against R3.3.1. So we need to change this and I think we should pin against `R3.3` which will be resolved  to `R3.3*`.

I'm not sure about your bioconductor question, we have a rule to depend on `r` and not on `r-base`. I guess this is because conda is pinning only when `r` is a dependency. This is hard-coded last time I cheked.

**Comment by bgruening** [comment]
@daler the current rebuild went more or less smoothly and I expect the next to be a breeze if we don't need to migrate everything :)
Can we close this issue?

**Comment by daler** [comment]
It will be so nice to not worry about mass migrations!
