### ISSUE TITLE
Edlib recipe: does not compile successfully if Python >= 3.8

### ISSUE THREAD

**Issue by Martinsos** [bioconda/bioconda-recipes#24071]
Author of Edlib here! @ayaanhossain reported this issue at edlib repo (https://github.com/Martinsos/edlib/issues/151), but it seems the problem is coming from the bioconda recipe for Edlib, so I am forwarding this here, hoping that you could help since I don't know much about conda/bioconda. Thanks!

**Comment by mbargull** [comment]
Fixed with gh-24215.
