### ISSUE TITLE
CNVkit installs outdated version by default

### ISSUE THREAD

**Issue by etal** [bioconda/bioconda-recipes#2412]
If I run `conda install cnvkit -c bioconda`, version 0.7.4 is fetched instead of the latest 0.8.

Looking at the dependencies, and the error message printed for `conda install cnvkit==0.8 -c bioconda`, it appears that the bundled R packages `cghFLasso` and `pscbs` might be asking for the wrong version of R base.

For example:

    $ conda create -n demo pandas
    $ source activate demo
    $ conda install cnvkit==0.8 -c bioconda
    $ conda install cnvkit==0.8 -c bioconda
    Fetching package metadata .........
    Solving package specifications: .
    Error: Dependencies missing in current linux-64 channels: 
    - cnvkit ==0.8 -> r-cghflasso -> r 3.2.2*
    - cnvkit ==0.8 -> r-pscbs -> r-future >=0.8.2 -> r-globals >=0.5.0 -> r-codetools

    Close matches found; did you mean one of these?

        r-codetools: r-catools, cdbtools, sra-tools
    ...
    $ R --version
    R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
    ...

I first noticed this issue while trying to build a docker image on the continuumio/miniconda3 base image, but it happens on a workstation where I installed CNVkit from source too. This might explain some recent user questions, too.

**Comment by kyleabeauchamp** [comment]
You need to do `-c bioconda -c r`

**Comment by kyleabeauchamp** [comment]
R packages live in another channel.

Starting soonish (after next build), you may also need to do `-c bioconda -c r -c conda-forge`, as bioconda now depends on both the R and conda-forge channels for basic infrastructure tools.

**Comment by etal** [comment]
Ah, sorry. It's been a long week.
