### ISSUE TITLE
blast installation defaults to version 2.5.0 ?

### ISSUE THREAD

**Issue by jvollme** [bioconda/bioconda-recipes#24182]
When installing blast via the bioconda channel (```conda install blast```  with "bioconda" already in my channel list), the "newest" version seems to default to v.2.5.0, even though the most current available version there seems to be 2.10.1? 
Also after manually installing version 2.9.0 some time ago, i can now not update to v.2.10.1 with ```conda update blast``` as this version is not seen as "newer".

manually trying to install blast version 2.10 with ```conda install blast=2.10``` yields a "Solving environment: failed with initial frozen solve" error and the installation just hangs.

Is this a problem just for me, or is something wrong with the recipe?

here is my output of '''conda info''':
```
     active environment : analysis_env2
    active env location : /opt/conda/miniconda/envs/analysis_env2
            shell level : 2
       user config file : /home/conda_admin/.condarc
 populated config files : /home/conda_admin/.condarc
          conda version : 4.8.4
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __glibc=2.27
       base environment : /opt/conda/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/miniconda/pkgs
                          /home/conda_admin/.conda/pkgs
       envs directories : /opt/conda/miniconda/envs
                          /home/conda_admin/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.7.4 Linux/4.15.0-70-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

**Comment by ar0ch** [comment]
It *should* work with `blast==2.10.1` not `blast==2.10`

**Comment by jvollme** [comment]
thanks I'll try it out. But since there is no 2.10.0 available (only 2.10.1), it should actually default to that anyway, shouldn't it?
Also since that is the newest version, simply running ```conda install blast``` (without version info) should automatically default to the newest version. So why does it seem to default to 2.5 (or is it just me)?

**Comment by jvollme** [comment]
thanks I'll try it out. But since there is no 2.10.0 available (only 2.10.1), it should actually default to that anyway, shouldn't it?
Also since that is the newest version, simply running ```conda install blast``` (without version info) should automatically default to the newest version. So why does it seem to default to 2.5 (or is it just me)?

**Comment by jvollme** [comment]
thanks I'll try it out. But since there is no 2.10.0 available (only 2.10.1), it should actually default to that anyway, shouldn't it?
Also since that is the newest version, simply running ```conda install blast``` (without version info) should automatically default to the newest version. So why does it seem to default to 2.5 (or is it just me)?

**Comment by jvollme** [comment]
thanks I'll try it out. But since there is no 2.10.0 available (only 2.10.1), it should actually default to that anyway, shouldn't it?
Also since that is the newest version, simply running ```conda install blast``` (without version info) should automatically default to the newest version. So why does it seem to default to 2.5 (or is it just me)?

**Comment by jvollme** [comment]
thanks I'll try it out. But since there is no 2.10.0 available (only 2.10.1), it should actually default to that anyway, shouldn't it?
Also since that is the newest version, simply running ```conda install blast``` (without version info) should automatically default to the newest version. So why does it seem to default to 2.5 (or is it just me)?

**Comment by jvollme** [comment]
thanks I'll try it out. But since there is no 2.10.0 available (only 2.10.1), it should actually default to that anyway, shouldn't it?
Also since that is the newest version, simply running ```conda install blast``` (without version info) should automatically default to the newest version. So why does it seem to default to 2.5 (or is it just me)?

**Comment by dpellow** [comment]
@jvollme - did this work? For me it seems to be installing 2.9 by default and I need 2.10.1 (there's a bug fix for multithreading according to the release notes).

**Comment by jvollme** [comment]
@dpellow: although it seems you already found the answer in the meantime, I post it here anyway: Yes it works when specifying the complete version down to the last digit. But as mentioned in issue #24199 thet jmarshal linked, this is not the normal behavior for conda and probably a bioconda bug.

**Comment by zeynepkurtw** [comment]
I've tried all the blast versions with conda and mamba. I set the order of the channels in .condarc BUT nothing worked. Does anyone know why the following doesn't work on MAC as it is the least version down to the last digit?

command:
`conda install -c bioconda blast=2.12.0`

error:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - blast=2.12.0

Current channels:

  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by didillysquat** [comment]
> I've tried all the blast versions with conda and mamba. I set the order of the channels in .condarc BUT nothing worked. Does anyone know why the following doesn't work on MAC as it is the least version down to the last digit?
> 
> command: `conda install -c bioconda blast=2.12.0`
> 
> error:
> 
> ```
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - blast=2.12.0
> 
> Current channels:
> 
>   - https://conda.anaconda.org/bioconda/osx-arm64
>   - https://conda.anaconda.org/bioconda/noarch
>   - https://conda.anaconda.org/conda-forge/osx-arm64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://repo.anaconda.com/pkgs/main/osx-arm64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/osx-arm64
>   - https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.
> ```

Make sure to use `blast==2.12.0` and not `blast=2.12.0`

**Comment by mhoban** [comment]
This is still very much an issue for me. I'm using the latest version of Miniconda, with channels configured as suggested [here](https://bioconda.github.io/#set-up-channels).  If I just do `conda install blast`, I get version 2.5.0. If I try any newer version, the following happens:

```bash
$ conda install blast==2.14.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: done
Collecting package metadata (repodata.json): -
```

It sits there forever spinning away at "Collecting package metadata" and occasionally goes back into "Solving" mode, which always seems to fail.

**Comment by FunmiB** [comment]
I have encountered the same issue. Any way to navigate this?

**Comment by boratyng** [comment]
Creating a new environment worked for me:
```
conda create -n blastenv -c bioconda -c conda-forge blast==2.15.0
```
Also, make sure to include `conda-forge`.

**Comment by FunmiB** [comment]
Thank you.

I had tried to install blast as you recommended earlier. I was getting an error saying no channel contained the package; and when I ran 'conda search blast', blast itself was nonexistent. Meanwhile I have all the required channels. Ended up installing it manually.

**Comment by peterjc** [comment]
@FunmiB I would guess you are trying to install BLAST on an Apple ARM CPU, but BioConda does not yet have it packaged for ``osx-arm64``. This is currently waiting on some of the Perl dependencies.

Otherwise I think/hope we can close this as stale. I personally have installed blast recently and got the current release.
