### ISSUE TITLE
Python 3.8 package builds finally landed in Bioconda

### ISSUE THREAD

**Issue by mbargull** [bioconda/bioconda-recipes#24215]
@bioconda/all 

After numerous delays, Python 3.8 packages are now available through Bioconda!

In preparation for this we rebuild about 1/3 of our non-Bioconductor packages with newer compilers and libraries over the course of the last 2 months. (Bioconductor packages are usually handled separately in batches for each Bioconductor release.)
Through this preparation work we also laid the ground for the upcoming Python 3.9 release and similar ecosystem-wide update processes. There has also been much work on conda-forge's side regarding [managing and speeding up such migrations](http://conda-forge.org/blog/posts/2020-07-11-R-4/) this year.
All in all, updating to the next Python release is likely to happen much faster in the future!

Note: If you encounter packages that are not yet installable with `python=3.8`, please check whether their recipes have a `skip: True  # [py>=38]` entry or if they are on the [`build-fail-blacklist`](https://github.com/bioconda/bioconda-recipes/blob/master/build-fail-blacklist). In case of `noarch: python` packages, it could also just be dependencies that are not yet rebuilt or compatible with `python=3.8`. (Tip to check which dependency might need a rebuild: You can use [`mamba`](https://github.com/thesnakepit/mamba) as an alternative to `conda`. The former usually gives more meaningful output on conflicting packages.)

**Comment by cbrueffer** [comment]
Thanks everyone involved, much appreciated!

**Comment by nextgenusfs** [comment]
So what is the recommended way to deal with python packages that do not work with v3.8? Should `skip: True # [py>=38]` be added to the `meta.yaml`?  For example if in the setup.py this is specified `REQUIRES_PYTHON = '>=2.7.0, !=3.0.*, !=3.1.*, !=3.2.*, <3.8'` then the build fails because build using python 3.8, just happened to me here https://github.com/bioconda/bioconda-recipes/pull/24566

**Comment by bgruening** [comment]
Thanks everyone!

**Comment by LiterallyUniqueLogin** [comment]
@mbargull There's [this page](https://bioconda.github.io/user/versions.html) of the docs which lists currently supported versions, and is now out of date. I don't know who's working on the upgrade to 3.9, but they should modify this page when they make that change.
