### ISSUE TITLE
`pyrodigal` recipe is not auto-bumped

### ISSUE THREAD

**Issue by althonos** [bioconda/bioconda-recipes#24245]
Hi !

I noticed that the recipe for my Pyrodigal package is not auto-bumped for some reason, so the package in the Bioconda channel is now quite outdated (plus it's a version prone to Segmentation Fault, so it'd be great to update :smiley: ).

Should I manually update the recipe in the meantime?

Cheers!

**Comment by raivivek** [comment]
Hi @althonos — Yes, I think that sounds great. Please go ahead and update your recipe manually for now! :)
