### ISSUE TITLE
channel precedence, ncurses, and package linking woes

### ISSUE THREAD

**Issue by tomkinsc** [bioconda/bioconda-recipes#2446]
@bioconda/core: This is related to the issues I was having with samtools that prompted [my rebuild PR](https://github.com/bioconda/bioconda-recipes/pull/2431). The cause is partially my fault, but it may warrant greater attention and a conversation. 

If my `~/.condarc` gives precedence to `conda-forge` over the `r` channel (not unreasonable given recent changes?), I see the following error when I try to run `samtools` (on macOS 10.11.6):

```
dyld: Symbol not found: _stdscr
  Referenced from: /Users/tomkinsc/miniconda3/bin/samtools
  Expected in: /Users/tomkinsc/miniconda3/bin/../lib//libncursesw.5.dylib
 in /Users/tomkinsc/miniconda3/bin/samtools
Trace/BPT trap: 5
```

This is with my `~/.condarc` set as follows:

```
channels:
  - bioconda
  - conda-forge
  - r
  - defaults
```

The packages are sourced as follows:

```
    ca-certificates: 2016.8.31-0 conda-forge
    curl:            7.45.0-1    bioconda
    ncurses:         5.9-9       conda-forge
    openssl:         1.0.2h-2    conda-forge
    samtools:        1.3.1-4     bioconda
    zlib:            1.2.8-3     conda-forge
```

If I re-order the channels in my `~/.condarc` to put `r` before `conda-forge`:

```
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
```

Then the packages are sourced like this (and samtools functions):

```
    ca-certificates: 2016.8.31-0 conda-forge
    curl:            7.45.0-1    bioconda
    libgcc:          4.8.5-1     r
    ncurses:         5.9-8       r
    openssl:         1.0.2h-2    conda-forge
    samtools:        1.3.1-4     bioconda
    zlib:            1.2.8-1     r
```

Spot the difference? In both cases, ncurses 5.9 was used, but in the working case, samtools links against the `r`-sourced `ncurses` package (and the `r`-channel version of ncurses depends on libgcc). 

Putting `conda-forge` before `r` is my fault, but perhaps it should have precedence. In the docs, are we intentionally giving precedence to the `r` channel over `conda-forge`? Is this samtools issue isolated to me? If not, it since it seems we currently have an inconsistency between the channel ordering [present in the docs](https://github.com/bioconda/bioconda-recipes/blob/master/docs/index.rst#step-2-setup-bioconda)(`r` listed before `conda-forge`), and the channel ordering of our [build config](https://github.com/bioconda/bioconda-recipes/blob/master/config.yml#L6-L10) (`conda-forge` is listed before `r)`. It's somewhat curious my samtools [rebuild passed on OSX](https://travis-ci.org/bioconda/bioconda-recipes/builds/163147652), given that it  relied on `conda-forge` ncurses over the `r`-channel build of ncurses. It's also possible the conda-forge build of ncurses is broken under OSX (notably lacking `libgcc` as a dependency), but that seems unlikely. 

Here's a comparison of the two ncurses packages (one from `r`, one from `conda-forge`):

```
ncurses 5.9 8
-------------
file name   : r::ncurses-5.9-8.tar.bz2
name        : ncurses
version     : 5.9
build number: 8
build string: 8
channel     : r/osx-64
size        : 757 KB
arch        : x86_64
binstar     : {'package_id': '54f621fd5e76833a5ee29663', 'channel': 'main', 'owner_id': '52c5dc11f53f2a0b1a9de428'}
fn          : ncurses-5.9-8.tar.bz2
license     : Free software - X11 License
license_family: Other
machine     : x86_64
md5         : 5576417989f3bab7ab50dfd6a0da61a7
operatingsystem: darwin
platform    : osx
priority    : 2
schannel    : r
subdir      : osx-64
target-triplet: x86_64-any-darwin
url         : https://conda.anaconda.org/t/to-9f3dac7a-ccc2-4833-bd0e-1ee4b237b3b1/r/osx-64/ncurses-5.9-8.tar.bz2
dependencies:
    libgcc

ncurses 5.9 9
-------------
file name   : conda-forge::ncurses-5.9-9.tar.bz2
name        : ncurses
version     : 5.9
build number: 9
build string: 9
channel     : conda-forge/osx-64
size        : 1000 KB
arch        : x86_64
binstar     : {'package_id': '56ec8ad47751384ef085ed39', 'channel': 'main', 'owner_id': '5528f42ce1dad12974506e8d'}
fn          : ncurses-5.9-9.tar.bz2
has_prefix  : True
license     : Free software (MIT-like License)
machine     : x86_64
md5         : 0774faecfc51c44f8b20cb46a4abfa7e
operatingsystem: darwin
platform    : osx
priority    : 3
schannel    : conda-forge
subdir      : osx-64
target-triplet: x86_64-any-darwin
url         : https://conda.anaconda.org/t/to-9f3dac7a-ccc2-4833-bd0e-1ee4b237b3b1/conda-forge/osx-64/ncurses-5.9-9.tar.bz2
dependencies:
```

Any thoughts on actions to take to avoid this in the future? It doesn't seem ideal to give the `r` channel precedence over `conda-forge`.

At a minimum, we should amend the docs to mention that conda source channel ordering really matters, and that users should preserve the order we use to build packages if they want to install bioconda packages.

**Comment by kyleabeauchamp** [comment]
Thanks for figuring all this out.  My only thoughts are:

1.  perhaps we can ping the R and conda-forge people to encourage them to build ncurses consistently?
2.  Can we get the R channel to use the conda-forge version and remove the overlaps?

**Comment by tomkinsc** [comment]
The second option sounds like the better option to me, especially if Continuum is moving to source packages from conda-forge.

**Comment by kyleabeauchamp** [comment]
I don't think so, I think it is maintained by Continuum.

Actually, could this be a DAG-related bug?   IMHO shouldn't `conda` always pick the higher version number (5.9.9), regardless of the order of the channels in your RCfile?

**Comment by johanneskoester** [comment]
As long as the r channel relies only on anaconda, we should not put conda forge in between. Other dependencies could break as well. So there are two reasonable orders: conda forge before or after bioconda but both after anaconda and r.

The real solution to the problems is having channel dependencies in conda.

**Comment by tomkinsc** [comment]
Channel dependencies in conda would be amazing (for this, and [working support](https://github.com/conda/conda/issues/2800) for `conda env create`). 

I suppose I'll list `r` first in my config, and close this...

**Comment by johanneskoester** [comment]
Let's keep this open until I have fixed the docs tomorrow.
