### ISSUE TITLE
Runtime error: HTTPError: 404 Client Error: NOT FOUND for url

### ISSUE THREAD

**Issue by sebastian-luna-valero** [bioconda/bioconda-recipes#2448]
Hello,

Is there anybody else having this errors?
https://github.com/Anaconda-Platform/support/issues/56#issuecomment-250119179

Best regards,
Sebastian.

**Comment by tomkinsc** [comment]
Someone in our group was seeing 404 errors earlier today while trying to install `R` packages from anaconda.org.

**Comment by pjr314** [comment]
I think this is an intermittent network connection problem.  It seems to have crept up other places before.  after numerous retries, eventually had successful instal. 
https://github.com/Anaconda-Platform/docs.anaconda.org/issues/116
