### ISSUE TITLE
tmux error on ubuntu

### ISSUE THREAD

**Issue by dkoppstein** [bioconda/bioconda-recipes#246]
Hi @ostrokach, I installed tmux using the bioconda recipe on an Ubuntu 14.04 machine, but got the following error when I tried running it: 

```
tmux: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar```
```

Do we need to add an updated libncurses to the repo?

**Comment by ostrokach** [comment]
Hmmm, it seems that tmux got built using `ncurses-5.9-4` from the R channel. 

Can you install that version of ncurses and see it that makes it work (`conda update ncurses -c r`)?

**Comment by dkoppstein** [comment]
Indeed, that makes it work!

**Comment by dkoppstein** [comment]
Ah, I just realized something -- the problem is actually not that the build version isn't explicitly stated, it's that in order to fetch the "correct" ncurses from the r channel instead of the default ncurses, you need to have previously done `conda config --add channels r` for your local conda (which I haven't done). It seems like the channel should be something specified in the meta.yaml file though, but [unfortunately isn't](https://groups.google.com/a/continuum.io/forum/#!msg/anaconda/8wFAUiwVUog/3DdBGpYDCQAJ). Until conda offers specified channels in meta.yaml, we should at least state in the README you should run `conda config --add channels r; conda config --add channels bioconda` to get bioconda to install packages properly.

**Comment by ostrokach** [comment]
Yeah, I agree that `conda config --add channels r; conda config --add channels bioconda` should be stated somewhere in the README. 

I also think it's a bug that the `r `channel and the `defaults` channel have the same package with different versions. If a packages build using the `r `version of `ncurses` doesn't work with the `defaults` version of ncurses, another package built using the `defaults` version may not  the `r` version...

**Comment by dkoppstein** [comment]
I believe the the `config --add` commands are in the user manual, but are currently just recommendations; they might actually be required to build some packages (like tmux). 

It seems like a fundamental problem with conda that you can't specify channels in the recipes. For some of the more popular packages, there are like 20 different versions of them on anaconda.org so depending on the user's .condarc you could be fetching any one of them. It looks like there's an issue here: conda/conda/#988 that has been open for a while.

**Comment by johanneskoester** [comment]
Isn't this very similar to packages built against a particular Python or numpy version. Conda somehow adds the versions to the build string and properly reports conflicts. This mechanism must be accessible somehow. Maybe there is a simple annotation in the meta yaml for this. I would imagine something like

```
requirements:
  build:
    - ncurses
  run:
    - ncurses # [lock]
```

would be useful...

**Comment by bgruening** [comment]
We are pinning versions for ncurses now. I hope this is fixed. Please feel free to reopen.
