### ISSUE TITLE
Conda-installed Perl cannot find "sys/types.h" when compiling C extension

### ISSUE THREAD

**Issue by standage** [bioconda/bioconda-recipes#24709]
I am looking into making a bioconda recipe for [vadr](https://github.com/nawrockie/vadr). The author provides [an install script](https://github.com/nawrockie/vadr/blob/master/vadr-install.sh) that downloads several packages and Perl modules and installs them. Using my system's Perl distribution (CentOS 7) as well as the `Inline::C` module that I installed in my home directory using `cpanm`, I was able to run the install script successfully.

Now in terms of a bioconda recipe, several of the packages the vadr install script downloads—HMMER, Infernal, BLAST+—are available as bioconda packages. Even easel is available, but Bio-Easel (Perl bindings for easel?) is not. So I figured Bio-Easel installation could be handled in the `build.sh` script. I attempted the installation process in a fresh conda environment with the following commands.

```
conda create --name bio-easel-test -y perl=5.26 perl-inline-c=0.78
conda activate bio-easel-test
curl -L -o Bio-Easel-vadr-1.1.1.tar.gz https://github.com/nawrockie/Bio-Easel/archive/vadr-1.1.1.tar.gz
tar -xzf Bio-Easel-vadr-1.1.1.tar.gz 
cd Bio-Easel-vadr-1.1.1/
mkdir src
cd src/
curl -L -o easel-Bio-Easel-0.12.tar.gz https://github.com/EddyRivasLab/easel/archive/Bio-Easel-0.12.tar.gz
tar -xzf easel-Bio-Easel-0.12.zip 
mv easel-Bio-Easel-0.12 easel
cd easel/
autoconf
cd ../../
perl Makefile.PL 
make
```

For sake of clarity, I won't include the output from most of these commands. Everything went as expected until the final command, which emitted this compiler error.

```
/home/centos/anaconda3/envs/bio-easel-test/bin/..//bin/..//bin/x86_64-conda_cos6-linux-gnu-gcc -c  -iquote"/home/centos/test/Bio-Easel-vadr-1.1.1" -I/home/centos/test/Bio-Easel-vadr-1.1.1/src/easel -D_REENTRANT -D_GNU_SOURCE --sysroot=/home/centos/anaconda3/envs/bio-easel-test/bin/..//bin/..//x86_64-conda_cos6-linux-gnu/sysroot -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2   -DVERSION=\"0.01\" -DXS_VERSION=\"0.01\" -fPIC --sysroot=/home/centos/anaconda3/envs/bio-easel-test/bin/..//bin/..//x86_64-conda_cos6-linux-gnu/sysroot "-I/home/centos/anaconda3/envs/bio-easel-test/lib/5.26.2/x86_64-linux-thread-multi/CORE"   MSA.c
In file included from MSA.xs:2:0:
/home/centos/anaconda3/envs/bio-easel-test/lib/5.26.2/x86_64-linux-thread-multi/CORE/perl.h:694:10: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:336: MSA.o] Error 1
make[1]: Leaving directory '/home/centos/test/Bio-Easel-vadr-1.1.1/_Inline/build/Bio/Easel/MSA'

A problem was encountered while attempting to compile and install your Inline
C code. The command that failed was:
  "make" with error code 2

The build directory was:
/home/centos/test/Bio-Easel-vadr-1.1.1/_Inline/build/Bio/Easel/MSA

To debug the problem, cd to the build directory, and inspect the output files.

 at /home/centos/test/Bio-Easel-vadr-1.1.1/blib/lib/Bio/Easel/MSA.pm line 69.
        ...propagated at /home/centos/perl5/lib/perl5/Inline/C.pm line 888.
BEGIN failed--compilation aborted at /home/centos/test/Bio-Easel-vadr-1.1.1/blib/lib/Bio/Easel/MSA.pm line 75.
Compilation failed in require.
BEGIN failed--compilation aborted.
make: *** [Makefile:961: MSA.inl] Error 25
```

The system `sys/types.h` header is at the expected location in `/usr/include/`, but it looks like the conda-installed Perl can't find the header in its distribution. Several Google searches didn't uncover any helpful information. Am I missing any Conda Perl packages, or any other important details?

**Comment by nextgenusfs** [comment]
This is the same error (`fatal error: sys/types.h: No such file or directory`) I get when trying to build `DB_File`manually with `cpanm`in Conda environment.... https://github.com/bioconda/bioconda-recipes/issues/24688

**Comment by mbargull** [comment]
There is a new build of the `conda-forge::perl=5.26.2` package up. Can you check if it works with that one now?

**Comment by standage** [comment]
That indeed fixed the issue. Thanks!

I'm still running into challenges with making a VADR recipe, but that has everything to do with VADR and little or nothing to do with conda/bioconda.

**Comment by mbargull** [comment]
@standage, perfect! Thanks for reporting back!

**Comment by max1c** [comment]
Sorry to post in the old issue but I am encountering the exact same problem with perl 5.26.2=h516909a_1006. I'm trying to configure maker with MPI and this is the only compatible perl version. Any advice?

```
Configuring MAKER with MPI support
Running Mkbootstrap for MPI ()
chmod 644 "MPI.bs"
"/apps/maker/3.01.03/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- MPI.bs blib/arch/auto/Parallel/Application/MPI/MPI.bs 644
"/apps/maker/3.01.03/bin/perl" "/apps/maker/3.01.03/lib/site_perl/5.26.2/ExtUtils/xsubpp"  -typemap "/apps/maker/3.01.03/lib/5.26.2/ExtUtils/typemap"   MPI.xs > MPI.xsc
mv MPI.xsc MPI.c
/apps/maker/3.01.03/bin/mpicc -c  -I"/apps/maker/3.01.03/maker/src" -I/apps/maker/3.01.03/include -D_REENTRANT -D_GNU_SOURCE --sysroot=/apps/maker/3.01.03/bin/..//x86_64-conda_cos6-linux-gnu/sysroot -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2  -O2   -DVERSION=\"0.00\" -DXS_VERSION=\"0.00\" -fPIC --sysroot=/apps/maker/3.01.03/bin/..//x86_64-conda_cos6-linux-gnu/sysroot "-I/apps/maker/3.01.03/lib/5.26.2/x86_64-linux-thread-multi/CORE"   MPI.c
In file included from MPI.xs:2:0:
/apps/maker/3.01.03/lib/5.26.2/x86_64-linux-thread-multi/CORE/perl.h:694:10: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:333: MPI.o] Error 1

A problem was encountered while attempting to compile and install your Inline
C code. The command that failed was:
  "make > out.make 2>&1" with error code 2
```

**Comment by Weihankk** [comment]
> Sorry to post in the old issue but I am encountering the exact same problem with perl 5.26.2=h516909a_1006. I'm trying to configure maker with MPI and this is the only compatible perl version. Any advice?
> 
> ```
> Configuring MAKER with MPI support
> Running Mkbootstrap for MPI ()
> chmod 644 "MPI.bs"
> "/apps/maker/3.01.03/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- MPI.bs blib/arch/auto/Parallel/Application/MPI/MPI.bs 644
> "/apps/maker/3.01.03/bin/perl" "/apps/maker/3.01.03/lib/site_perl/5.26.2/ExtUtils/xsubpp"  -typemap "/apps/maker/3.01.03/lib/5.26.2/ExtUtils/typemap"   MPI.xs > MPI.xsc
> mv MPI.xsc MPI.c
> /apps/maker/3.01.03/bin/mpicc -c  -I"/apps/maker/3.01.03/maker/src" -I/apps/maker/3.01.03/include -D_REENTRANT -D_GNU_SOURCE --sysroot=/apps/maker/3.01.03/bin/..//x86_64-conda_cos6-linux-gnu/sysroot -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2  -O2   -DVERSION=\"0.00\" -DXS_VERSION=\"0.00\" -fPIC --sysroot=/apps/maker/3.01.03/bin/..//x86_64-conda_cos6-linux-gnu/sysroot "-I/apps/maker/3.01.03/lib/5.26.2/x86_64-linux-thread-multi/CORE"   MPI.c
> In file included from MPI.xs:2:0:
> /apps/maker/3.01.03/lib/5.26.2/x86_64-linux-thread-multi/CORE/perl.h:694:10: fatal error: sys/types.h: No such file or directory
>  #include <sys/types.h>
>           ^~~~~~~~~~~~~
> compilation terminated.
> make: *** [Makefile:333: MPI.o] Error 1
> 
> A problem was encountered while attempting to compile and install your Inline
> C code. The command that failed was:
>   "make > out.make 2>&1" with error code 2
> ```

Hi max1c， I meet the same problem， did you solve it ？

**Comment by imhuangshihui** [comment]
> 
> 
> > Sorry to post in the old issue but I am encountering the exact same problem with perl 5.26.2=h516909a_1006. I'm trying to configure maker with MPI and this is the only compatible perl version. Any advice?
> > ```
> > Configuring MAKER with MPI support
> > Running Mkbootstrap for MPI ()
> > chmod 644 "MPI.bs"
> > "/apps/maker/3.01.03/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- MPI.bs blib/arch/auto/Parallel/Application/MPI/MPI.bs 644
> > "/apps/maker/3.01.03/bin/perl" "/apps/maker/3.01.03/lib/site_perl/5.26.2/ExtUtils/xsubpp"  -typemap "/apps/maker/3.01.03/lib/5.26.2/ExtUtils/typemap"   MPI.xs > MPI.xsc
> > mv MPI.xsc MPI.c
> > /apps/maker/3.01.03/bin/mpicc -c  -I"/apps/maker/3.01.03/maker/src" -I/apps/maker/3.01.03/include -D_REENTRANT -D_GNU_SOURCE --sysroot=/apps/maker/3.01.03/bin/..//x86_64-conda_cos6-linux-gnu/sysroot -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2  -O2   -DVERSION=\"0.00\" -DXS_VERSION=\"0.00\" -fPIC --sysroot=/apps/maker/3.01.03/bin/..//x86_64-conda_cos6-linux-gnu/sysroot "-I/apps/maker/3.01.03/lib/5.26.2/x86_64-linux-thread-multi/CORE"   MPI.c
> > In file included from MPI.xs:2:0:
> > /apps/maker/3.01.03/lib/5.26.2/x86_64-linux-thread-multi/CORE/perl.h:694:10: fatal error: sys/types.h: No such file or directory
> >  #include <sys/types.h>
> >           ^~~~~~~~~~~~~
> > compilation terminated.
> > make: *** [Makefile:333: MPI.o] Error 1
> > 
> > A problem was encountered while attempting to compile and install your Inline
> > C code. The command that failed was:
> >   "make > out.make 2>&1" with error code 2
> > ```
> 
> Hi max1c， I meet the same problem， did you solve it ？

Hi， max1c and Weihankk, same error with you, did you solve it?

**Comment by orangeSi** [comment]
@imhuangshihui @Weihankk I fix this by ```conda install -n myenv gcc_linux-64 ``
