### ISSUE TITLE
maxbin2.2.7 has missing package

### ISSUE THREAD

**Issue by SilasK** [bioconda/bioconda-recipes#24707]
```
Can't locate LWP/Simple.pm in @INC (you may need to install the LWP::Simple module) (@INC contains: /Workindir/databases/conda_envs/40f36dfb/lib/site_perl/5.30.3/x86_64-linux-thread-multi /Workindir/databases/conda_envs/40f36dfb/lib/site_perl/5.30.3 /Workindir/databases/conda_envs/40f36dfb/lib/5.30.3/x86_64-linux-thread-multi /Workindir/databases/conda_envs/40f36dfb/lib/5.30.3 .) at /Workindir/databases/conda_envs/40f36dfb/bin/run_MaxBin.pl line 4.
```

related to #18267

@bgruening Can this pearl package be added? 

I use python 3.6 in a miniconda docker container

**Comment by SilasK** [comment]
I checked conda has already installed ` perl-lwp-simple` but maxbin doean't find it.

**Comment by SilasK** [comment]
Does @colinbrislawn or @keuv-grvl  have an idea.

Maxbin doean't find the perl package simple also on Linux CentOS

**Comment by nick-youngblut** [comment]
@SilasK I'm getting `Can't locate HTTP/Date.pm in @INC (you may need to install the HTTP::Date module)` with `bioconda::maxbin2=2.2.7`. Any ideas on how to fix that issue, which seems similar to your `Can't locate LWP/Simple.pm in @INC` issue?
