### ISSUE TITLE
Adjust memory of Java tool (pilon) 

### ISSUE THREAD

**Issue by apeltzer** [bioconda/bioconda-recipes#24749]
Hi!

we're trying to use pilon in a pipeline but the proposed fix to run pilon from bioconda requires modifying the recipe / runner:

https://github.com/rrwick/Unicycler/issues/147

Is there any way to change this on a per-user basis, e.g. supplying a parameter to the recipe call? Or is this out of scope?

**Comment by daler** [comment]
@apeltzer the default arguments are just defaults; at runtime you should be able to use, e.g., 

```bash
pilon -Xmx64g
```
 The [wrapper](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pilon/pilon.py) has the details, but they are basically being parsed from the original command and passed along to java.

Does that work?

**Comment by apeltzer** [comment]
I will definitely check this out - this looks like exactly what we need - thanks @daler !

**Comment by bgruening** [comment]
@apeltzer all Java tools have this wrapper implemented. If you like have a look how Galaxy is using this.
