### ISSUE TITLE
errors with gcc and gfortran from defaults channel

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#2475]
I've been hitting some issues with building R packages that I think is related to the gcc package from defaults channel.

How to reproduce:

``` bash
docker run -it --net="host" -v `pwd`:/bioconda-recipes condaforge/linux-anvil /bin/bash -c \
"cd bioconda-recipes; conda build -c r -c bioconda recipes/r-ash"
```

fails with the following message:

```
gfortran   -fpic  -I/opt/conda/conda-bld/r-ash_1475351407071/_b_env_placehold_placehold_placehold_pl/include -L/opt/conda/conda-bld/r-ash_1475351407071/_b_env_placehold_placehold_placehold_pl/lib  -c ash.f -o ash.o
f951: internal compiler error: Illegal instruction
```

The information I've found makes me think it's an issue with how it was compiled, e.g.,
- https://trac.macports.org/ticket/41364
- https://bugzilla.redhat.com/show_bug.cgi?id=222371
- https://github.com/Homebrew/legacy-homebrew/issues/18761

Before I open an issue with conda and/or conda-forge, anyone else know another way of fixing this? ping @bioconda/core

**Comment by bgruening** [comment]
I was also seeing it and have no clue how to fix it. A few ideas ... Does the GCC from r work? Is this a regression in the latest build and maybe a previous build works?

**Comment by daler** [comment]
No luck. I don't see a gcc in r channel, and gcc 4.8.2 (the earliest available in defaults channel) has the same error.

**Comment by bgruening** [comment]
You are right, libgcc is in `r`:

`libgcc                       4.8.4                         0  r ` 

I guess the we should raise this issue upstream. Something is broken here :(

**Comment by daler** [comment]
xref: https://github.com/conda/conda-build/issues/1424

**Comment by mingwandroid** [comment]
libgcc in `r` is at version 4.8.5:

`libgcc:     4.8.5-1   r`

.. but IMHO it shouldn't be there at all.

**Comment by daler** [comment]
@bgruening this seems to be CPU architecture related. Locally on my machine it still fails, but on travis-ci it's working (https://travis-ci.org/bioconda/bioconda-recipes/builds/171435307). I have a Xeon X5482, so if you're running on something around the same age it might be why you have issues too.

Being able to build these fortran-compiled packages opens up a lot of the R package DAG that can be built!

**Comment by epruesse** [comment]
outdated
