### ISSUE TITLE
Canu recipe fine - container not fine

### ISSUE THREAD

**Issue by apeltzer** [bioconda/bioconda-recipes#24854]
Hi canu users,

I've been using the canu recipe just fine in my own conda environment(s) but whenever I try using the biocontainer / container built from conda, I'm running into weird errors, see: https://github.com/marbl/canu/issues/1816 

@skoren gave me the hint to check this a bit more in detail but I'm not sure how to fix this in the canu container (if this is possible?). Maybe making bash a requirement in the canu recipe too?

**Comment by bgruening** [comment]
> Maybe making bash a requirement in the canu recipe too?

Bash is installed in the container, maybe not the latest version (5?) but pure bash is installed.

**Comment by bgruening** [comment]
The problem was not bash, but a missing dependency called `getconf`, in addition libGL dependency was missing. Fixed in the latest container.

**Comment by apeltzer** [comment]
Glad that this is fixed now :-)
