### ISSUE TITLE
stacks version

### ISSUE THREAD

**Issue by tiagoantao** [bioconda/bioconda-recipes#2501]
Hi,

The current stacks version is 1.40. (though the log says 1.42).
Stacks 1.40 clone_filter has a problem with fastq non-gzipped files. This is quite serious on galaxy.
I can put a 1.42 version in ASAP as long as @abretaud is fine with that.

**Comment by bgruening** [comment]
:+1:

**Comment by abretaud** [comment]
Hi,
That's strange, I uploaded the [1.42 version](https://github.com/bioconda/bioconda-recipes/blob/f6d2c07011f8b5fd9dece5a50c4ee3d2425cf03f/recipes/stacks/meta.yaml#L10) a few days ago, and the tests for galaxy wrappers used that version...
Did I miss something?

**Comment by bgruening** [comment]
True, there is a stacks version 1.42 and a container: https://quay.io/repository/biocontainers/stacks?tab=tags

Will close this. @tiagoantao please let me know if you do not see this package and make sure you have enabled conda-forge as channel as well.

**Comment by tiagoantao** [comment]
argh! I did not notice the top version. just the subdirectories...
Sorry for wasting everybody's time
