### ISSUE TITLE
Augustus 3.3.3 missing Samtools depenency

### ISSUE THREAD

**Issue by marchoeppner** [bioconda/bioconda-recipes#25029]
Hi,
the recipie for augustus-3.3.3 is missing samtools ~= 1.9 as dependency. The authors rewrote several tools for this release, including bamToWig.py - which relies on Samtools. This is mainly an issue for biocontainers. 

/M

**Comment by bgruening** [comment]
Is bamtols not enough? @marchoeppner if you like you can add samtools here https://github.com/bioconda/bioconda-recipes/blob/master/recipes/augustus/meta.yaml#L63. Do not forget to increase the build-number.
