### ISSUE TITLE
Adding omero-py to conda-forge

### ISSUE THREAD

**Issue by manics** [bioconda/bioconda-recipes#25079]
It's taken a while, but we (@ome) are adding omero-py to conda-forge as originally suggested in https://github.com/bioconda/bioconda-recipes/pull/15831#issuecomment-501633453

- A conda-forge PR to add omero-py is in progress here: https://github.com/conda-forge/staged-recipes/pull/13028

Please let us know if there are any steps we need to take in bioconda.

**Comment by bgruening** [comment]
No steps needed from our side. As soon as you package is in conda-forge we can remove the recipe here.

Thanks @manics
