### ISSUE TITLE
Bioconductor hackathon!

### ISSUE THREAD

**Issue by dpryan79** [bioconda/bioconda-recipes#25225]
## Background

From 29.10-5.11 we published packages for well over 3000 Bioconductor 3.12 packages. While this is quite the achievement, from 9.11-13.11 we'd like to have a hackathon to try and whittle down the list of remaining packages further. Below are a list of Bioconductor packages that remain to be built. These have been broken into sections of related issues for convenience. 

## How it will work

If you would like to work on one or more packages, please edit this post and put your github username in parentheses beside said package. Once you have a PR in progress, please feel encouraged to put a link to it in the same place. Finally, once you have the package building and the PR has been merged please put a check.

If you have questions, please join us in the bioconda gitter channel and ask questions there: https://gitter.im/bioconda/Lobby

Important! Please remember that you will have to remove these packages from the `build-fail-blacklist` as part of your pull request.

### can't resolve environment (missing unknown dependencies in conda-forge/bioconda)

 - [x] recipes/bioconductor-adimpute  https://github.com/bioconda/bioconda-recipes/pull/25261
 - [x] recipes/bioconductor-anvilbilling  https://github.com/bioconda/bioconda-recipes/pull/25261
 - [x] recipes/bioconductor-chimera  https://github.com/bioconda/bioconda-recipes/pull/25261
 - [x] recipes/bioconductor-chipcomp  https://github.com/bioconda/bioconda-recipes/pull/25261
 - [x] recipes/bioconductor-ctrap  https://github.com/bioconda/bioconda-recipes/pull/25261
 - [x] recipes/bioconductor-cytomapper  https://github.com/bioconda/bioconda-recipes/pull/25285
 - [x] recipes/bioconductor-famat  https://github.com/bioconda/bioconda-recipes/pull/25261
 - [x] recipes/bioconductor-getdee2  https://github.com/bioconda/bioconda-recipes/pull/25261
 - [x] recipes/bioconductor-ggnewscale  https://github.com/bioconda/bioconda-recipes/pull/25263
 - [x] recipes/bioconductor-gpart  https://github.com/bioconda/bioconda-recipes/pull/25263
 - [x] recipes/bioconductor-gsreg  https://github.com/bioconda/bioconda-recipes/pull/25263
 - [x] recipes/bioconductor-hilda  https://github.com/bioconda/bioconda-recipes/pull/25263
 - [x] recipes/bioconductor-iloreg  https://github.com/bioconda/bioconda-recipes/pull/25263
 - [x] recipes/bioconductor-italics  https://github.com/bioconda/bioconda-recipes/pull/25263
 - [x] recipes/bioconductor-mirsm  https://github.com/bioconda/bioconda-recipes/pull/25274
 - [x] recipes/bioconductor-msimpute  https://github.com/bioconda/bioconda-recipes/pull/25274
 - [x] recipes/bioconductor-nearbynding  https://github.com/bioconda/bioconda-recipes/pull/25274
 - [x] recipes/bioconductor-sangeranalyser  https://github.com/bioconda/bioconda-recipes/pull/25282
 - [x] recipes/bioconductor-spatialdecon  https://github.com/bioconda/bioconda-recipes/pull/25282
 - [x] recipes/bioconductor-spatialheatmap  https://github.com/bioconda/bioconda-recipes/pull/25282
 - [x] recipes/bioconductor-systempipeshiny  https://github.com/bioconda/bioconda-recipes/pull/25282
 - [x] recipes/bioconductor-vanillaice  https://github.com/bioconda/bioconda-recipes/pull/25285
 - [x] recipes/bioconductor-tcgabiolinksgui  https://github.com/bioconda/bioconda-recipes/pull/25373
 - [x] recipes/bioconductor-transite gh-25374 @dpryan79 
 - [x] recipes/bioconductor-wpm gh-25375 @dpryan79 
 - [x] recipes/bioconductor-xps

### Needs bioconductor-scatedata data package to be available from bioconductor
- [x] recipes/bioconductor-scate  https://github.com/bioconda/bioconda-recipes/pull/25314

### Needs r-dagitty
 - [x] recipes/r-pcalg  https://github.com/bioconda/bioconda-recipes/issues/25336
 - [x] recipes/bioconductor-epinem  https://github.com/bioconda/bioconda-recipes/pull/25336

### Needs r-rcppdist
 - [x] recipes/bioconductor-bayesspace  https://github.com/bioconda/bioconda-recipes/pull/25245

### Needs r-philentropy
 - [x] recipes/r-biomartr  https://github.com/bioconda/bioconda-recipes/pull/25245

### Needs r-biomartr and (on OSX) r-fst>0.9.2
 - [x] recipes/bioconductor-orfik  (@dpryan79) gh-25366

### Needs r-matchingr and r-nsga2r  
 - [x] recipes/bioconductor-gsgalgor  https://github.com/bioconda/bioconda-recipes/pull/25245
 - [x] recipes/bioconductor-mogamun  https://github.com/bioconda/bioconda-recipes/pull/25245

### Needs r-tfprobability
 - [x] recipes/bioconductor-netreg  https://github.com/bioconda/bioconda-recipes/pull/25274

### Needs r-imager
 - [x] recipes/bioconductor-biomm  https://github.com/bioconda/bioconda-recipes/pull/25254

### Needs r-ggnewscale
 - [x] recipes/bioconductor-ggtreeextra  https://github.com/bioconda/bioconda-recipes/pull/25254

### Needs a fix to r-mixsqp
 - [x] recipes/bioconductor-diffbind  https://github.com/bioconda/bioconda-recipes/pull/25280
 - [x] recipes/bioconductor-chipqc  https://github.com/bioconda/bioconda-recipes/pull/25280

### Needs r-netrep >=1.2.1
 - [x] recipes/bioconductor-gwena  https://github.com/bioconda/bioconda-recipes/pull/25274

### Needs r-crmn
 - [x] recipes/bioconductor-msprep  https://github.com/bioconda/bioconda-recipes/pull/25254

### Needs r-intrinsicdimension
 - [x] recipes/bioconductor-pipecomp  https://github.com/bioconda/bioconda-recipes/pull/25254

### Needs r-condformat
 - [x] recipes/bioconductor-uncoverapplib  https://github.com/bioconda/bioconda-recipes/pull/25254

### Can't compile
 - [x] recipes/bioconductor-bgmix (@mbargull) gh-25311
 - [x] recipes/bioconductor-bgx (@mbargull) gh-25310
 - [x] recipes/bioconductor-biggr (@mbargull) gh-25312 + gh-25317 + gh-25336
 - [x] recipes/bioconductor-cetf (@mbargull) gh-25313 + gh-25318
 - [x] recipes/bioconductor-chicago (@mbargull) gh-25307
 - [x] recipes/bioconductor-iclusterplus (@mbargull) gh-25308
 - [x] recipes/bioconductor-interactivedisplay (@dpryan79) gh-25366
 - [x] recipes/bioconductor-netboost (@mbargull) gh-25309
 - [x] recipes/bioconductor-networkbma (@mbargull) gh-25306
 - [x] recipes/bioconductor-pchicdata (@mbargull) gh-25307
 - [x] recipes/bioconductor-rariant (@mbargull) gh-25305
 - [x] recipes/bioconductor-rsbml (@mbargull) gh-25312 + gh-25317
 - [x] recipes/bioconductor-sictools (@mbargull) gh-25304

### Fails on OSX
 - [x] recipes/bioconductor-cardinal  https://github.com/bioconda/bioconda-recipes/pull/25275 @jmarshall 
 - [x] recipes/bioconductor-cydar  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-cytofast  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-cytoml  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-cytotree  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-flowclust  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-flowcore  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-flowfp  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-flowmatch  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-flowsom  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-flowspy  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-flowworkspace  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-gmapr  https://github.com/bioconda/bioconda-recipes/pull/25365 @jmarshall 
 - [x] recipes/bioconductor-immunoclust  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-macpet
 - [x] recipes/bioconductor-ncdfflow  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-opencyto  https://github.com/bioconda/bioconda-recipes/pull/25299  @jmarshall 
 - [x] recipes/bioconductor-qckitfastq  https://github.com/bioconda/bioconda-recipes/pull/25372 @jmarshall 
 - [x] recipes/bioconductor-quasr
 - [x] recipes/bioconductor-rbowtie

**Comment by dpryan79** [comment]
Here is a list of CRAN packages currently known to be missing from conda-forge and bioconda:

 - [ ] r-rcppdist
 - [ ] r-splines2
 - [ ] r-crmn
 - [ ] r-binr
 - [ ] r-intrinsicdimension
 - [ ] r-ggnewscale
 - [ ] r-svgpanzoom
 - [ ] r-drimpute
 - [ ] r-aricode
 - [ ] r-mpinet
 - [ ] r-matchingr
 - [ ] r-shinytoastr
 - [ ] r-htm2txt
 - [ ] r-rdetools
 - [ ] r-biomartr
 - [ ] r-imager
 - [ ] r-pcalg
 - [ ] r-nsga2r
 - [ ] r-excelr
 - [ ] r-av
 - [ ] r-lognormreg
 - [ ] r-shinycustomloader
 - [ ] r-condformat

**Comment by mbargull** [comment]
I'm taking a stab on the "Can't compile" bunch (the non-OSX ones at least for now).

**Comment by dpryan79** [comment]
@mbargull Thanks! A bunch of these have issues with FlowCore or something like that, so I foresee it being theme and variation. My guess is that it's something to do with the .so vs. .dylib name difference.

**Comment by jmarshall** [comment]
Fails on OSX:
* recipes/bioconductor-cardinal #25275

**Comment by jmarshall** [comment]
Fails on OSX:

* recipes/bioconductor-cydar, -cyto*, -flow*, -immunoclust, -ncdfflow, -opencyto #25292

**Comment by mbargull** [comment]
@jmarshall, thanks a bunch for for working on the macOS builds! Those are usually a pain to debug for the ones without Macs.

----

The non-macOS compile failures all have PRs now -- part from `bioconductor-interactivedisplay`; that one has some R-specific failure I don't know how to handle properly:
```
* installing to library ‘/opt/conda/conda-bld/bioconductor-interactivedisplay_1605094556601/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/R/library’
* installing *source* package ‘interactiveDisplay’ ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Installing package into ‘$PREFIX/lib/R/library/00LOCK-work/00new’
(as ‘lib’ is unspecified)
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
Error: unable to load R code in package ‘interactiveDisplay’
Execution halted
ERROR: lazy loading failed for package ‘interactiveDisplay’
* removing ‘/opt/conda/conda-bld/bioconductor-interactivedisplay_1605094556601/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/R/library/interactiveDisplay’
```
Web search for `trying to use CRAN without setting a mirror` says something about repos from `/etc/R/Rprofile.site` or similar.=
If someone versed in R knows how to do that, please go ahead and take that one :).

**Comment by jmarshall** [comment]
The remaining “Fails on OSX” packages fail as follows:

####  recipes/bioconductor-gmapr

This builds `gmapR.so` (via hard-coded rules in _src/Makefile_) but later looks for `gmapR.dylib`. Probably the way to fix this is to convert it to build via a _src/Makevars_ instead? Is this something that is worth doing by patching in bioconda's recipe, or would it be better to assist upstream convert to _Makevars_ and fix this in bioconda via an eventual new upstream version?

####  recipes/bioconductor-qckitfastq

Fails due to using `std::shared_timed_mutex` which is apparently only provided by Apple's libc++.dylib starting from macOS 10.12:

```
20:34:16 BIOCONDA INFO (ERR) …/lib/R/library/RSeqAn/include/seqan/parallel/enumerable_thread_local.h:66:10: error: 'shared_timed_mutex' is unavailable: introduced in macOS 10.12
20:34:16 BIOCONDA INFO (ERR)     std::shared_timed_mutex  _mutex{};        // TODO(rrahn): Replace by shared_mutex when c++17 is available.
```

Is there precedent for altering the version of macOS being targeted by a bioconda recipe? (And how do you do it?)

####  recipes/bioconductor-macpet, recipes/bioconductor-quasr, recipes/bioconductor-rbowtie

I have a fix in progress for these three.

**Comment by dpryan79** [comment]
@jmarshall 

 - For bioconductor-gmapr let's just patch it here. Patches to bioconductor packages will probably take 6 months to work their way through otherwise.
 - For bioconductor-qckitfastq I don't think we have a mechanism for changing the OSX build platform (they can do this on conda-forge already I think, but we have yet to implement it). So let's just leave it blacklisted until we switch over in January or so to a newer OSX build target.

**Comment by mbargull** [comment]
@jmarshall, for `bioconductor-qckitfastq` you should be able to add a `conda_build_config.yaml` file in the recipe folder with:
```yaml
MACOSX_DEPLOYMENT_TARGET:
  - 10.12
```

**Comment by dpryan79** [comment]
I'm curious to hear if that actually works :)

**Comment by mbargull** [comment]
The thing that we don't support on Bioconda is changing the version of the actual SDK. On conda-forge you can also choose a different SDK version because of the per-recipe build configuration. Since we have only on central one on Bioconda, all recipes share the same SDK. But since we updated to 10.13 earlier this year, this should cause any issue in the foreseeable future (I hope ;)).

**Comment by mbargull** [comment]
Oh, but I just remembered that this didn't work in https://github.com/bioconda/bioconda-recipes/pull/22744 !
So, it is supposed to work, but IIRC `conda-build` gives precedence to the `MACOSX_DEPLOYMENT_TARGET` from the environment variable.
We can fix that by removing the environment variable from the CI setup -- but then we should add it to the cbc.yaml of `bioconda-utils` to have a proper default value. I'll open an issue to not forget that.

@jmarshall, with the above said, instead of adding the `conda_build_config.yaml` you can also add
```sh
case "${target_platform}" in osx-*) export MACOSX_DEPLOYMENT_TARGET=10.12 ; esac
```
to the top of `build.sh`.

**Comment by mbstadler** [comment]
@jmarshall, I am the maintainer of `Rbowtie` and `QuasR` and am excited to hear that you are looking into these.

I am not very familiar with conda/bioconda and did not manage to get detailed logfiles when locally testing these builds (I only see the call to `build.sh`, but none of the STDOUT from that call). My guess was that the `Makefile` in `Rbowtie` ignores the setting of `CC` and `CXX`, and `QuasR` probably fails because it misses `Rbowtie`.

I am happy to help on the R side if needed.

**Comment by mbargull** [comment]
@mbstadler, while you're here, maybe you could help me out (because I'm not very knowledgeable wrt Bioconductor):
Is there a "canonical" way to report build issues and submit patches for certain packages on Bioconductor?
Say, e.g., if I go to https://www.bioconductor.org/packages/release/bioc/html/Rbowtie.html it doesn't tell me I could go to https://github.com/fmicompbio/Rbowtie/pulls to submit a patch but just shows Bioconductor's Git repository URL.

I've got a couple of patches and C++17 or Makefile issue reports for other packages I'd like to upstream -- but of course, if possible, I don't want to invest an unreasonable amount of time to dig up upstream repos and/or register for multiple services to contribute tiny patches ;).

**Comment by mbstadler** [comment]
@mbargull, there are optional `URL` and `BugReports` fields in the package DESCRIPTION file (https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file), for example from `Rbowtie` (devel version):
```
URL: https://github.com/fmicompbio/Rbowtie
BugReports: https://github.com/fmicompbio/Rbowtie/issues
```
While these fields are optional and may not be set, the `Maintainer` field with a valid email address is mandatory. This might be the quickest relyable route of contact for you.

**Comment by mbargull** [comment]
Nice, then I can just `curl ... | tar -xzOf- \*/DESCRIPTION | grep ...` whenever I encounter a tarball URL in the wild ^_^.

> If these fields are set, they are reported on the package landing page, under **Details** e.g. https://www.bioconductor.org/packages/devel/bioc/html/Rbowtie.html

Ah, it's interesting that they are readily consumable under `.../devel/bioc/...` but not `.../release/bioc/...` -- that's also good to know :).

Thank you, @mbstadler, that's quite helpful!

**Comment by mitraak** [comment]
Taking a stab at the few remaining bioconductor recipes (xps, transite, wpm, tcgabiolinksgui)

**Comment by dpryan79** [comment]
@mitraak Good luck, I think the ones you mentioned have issues due to having dependencies with differing pinnings. I suspect they're just not going to be buildable for a few months until we next update our own pinnings.

**Comment by jmarshall** [comment]
recipes/bioconductor-gmapr is now fixed by PR #25365.

**Comment by dpryan79** [comment]
@mbargull I figured out bioconductor-interactivedisplay, it has an unlisted dependency on r-biocmanager. If that's not present then it tries to install it the normal R way. Adding that in fixes it. Of course 99% of the time one would use biocmanager::install to install Bioconductor packages, but since we're the 1% not doing that... Anyway: https://github.com/bioconda/bioconda-recipes/pull/25366

**Comment by jmarshall** [comment]
recipes/bioconductor-qckitfastq is now fixed by PR #25372, which avoids the problem and builds on any macOS version.

**Comment by dpryan79** [comment]
Here are the causes of the conflicts for the last 3 packages:

 - bioconductor-xps: root5 needs to be rebuilt (none of the packages built in the past 2 years have been uploaded)
 - bioconductor-wpm: missing `r-shinycustomloader` from conda-forge
 - bioconductor-transite: r-rcpp for R 4.0 on linux never got pushed on conda-forge due to a CI failure

**Comment by dpryan79** [comment]
@mbargull Can you try and trigger a build on the conda-forge root5-feedstock? That should solve last package.

**Comment by bgruening** [comment]
Thanks @dpryan79 for organizing and everyone that participated!
