### ISSUE TITLE
could not install any software

### ISSUE THREAD

**Issue by bioramg** [bioconda/bioconda-recipes#25469]
Hi,
I had some issue with samtools, so I reinstalled Anaconda v4.9.2 and trying to install some bioinformatics tools like bowtie2, trim-galore etc. But its failed to install

conda install -c bioconda trim-galore
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for secretstorage typed-ast mistune gst-plugins-base matplotlib filelock olefile xlsxwriter python harfbuzz py sqlalchemy pandas joblib jupyter_core sip pillow pytest click entrypoints ruamel_yaml flake8 prompt_toolkit zict sphinxcontrib-jsmath co/ e

How to solve this issue?

**Comment by bgruening** [comment]
Please see our user documentation at https://bioconda.github.io/user/index.html 

You always need to add the conda-forge channel as well.
