### ISSUE TITLE
Delete Old Docker Image or Update Docs to flag as outdated

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#2557]
Team Bioconda,

As the build system has changed it is probably a good idea to take down the CentOS5 image from DockerHub or at least to add a prominent disclaimer at the top of the page that this is no longer the correct route for building bioconda packages.

https://hub.docker.com/r/bioconda/bioconda-builder/

zcp

**Comment by daler** [comment]
Fixed in #2557, and addressed more generally in #2593.
