### ISSUE TITLE
gnuplot is missing libjpeg

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#2568]
gnuplot: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory

**Comment by croth1** [comment]
I contributed libgd and gnuplot to conda-forge. We could remove the recipes and revoke the bioconda builds from anaconda.org to fix this problem.

**Comment by bgruening** [comment]
@croth1 for completeness, can you link to the PRs on conda-forge.
@bioconda/core is it ok, if I remove the exact same version that is now on conda-forge from our channel? The older ones we can keep.

**Comment by croth1** [comment]
https://github.com/conda-forge/gnuplot-feedstock
https://github.com/conda-forge/libgd-feedstock

These are the two feedstocks.

Before removing the builds we better compare the dependencies carefully to make sure we don't break compatibility.

**Comment by johanneskoester** [comment]
Yes that's fine @bgruening! Merry Christmas guys!
