### ISSUE TITLE
Can't build package bioconductor-cn.mops

### ISSUE THREAD

**Issue by sndrtj** [bioconda/bioconda-recipes#2592]
I'm not able to build the `bioconductor-cn.mops` package. 
Running `conda build recipes/bioconductor-cn.mops` finally results in:

```
..INFO:stderrlog:...
Can't build /home/sndrtj/bioconda-recipes/recipes/bioconductor-cn.mops due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - bioconductor-biobase
  - r 3.3.1*
```

**Comment by daler** [comment]
It's not biobase that's the problem, it's likely other dependencies (see https://github.com/conda/conda-build/issues/1454).

We are rebuilding all the R packages and we'll get to this one. They have to be done in order so we don't hit dependency issues -- [here](https://github.com/bioconda/bioconda-recipes/blob/master/sorted-r-blacklist#L386) is where it is in the list.

**Comment by sndrtj** [comment]
Thanks for that explanation. I guess I'll just have to sit tight and wait for this to resolve, in that case.

**Comment by druvus** [comment]
Packages are now rebuilt so this should be working now. Please reopen if you still have the same issue.
