### ISSUE TITLE
Recent Crossmap version is not available via bioconda

### ISSUE THREAD

**Issue by ManavalanG** [bioconda/bioconda-recipes#25991]
Crossmap is currently at version `0.5.2`, but the version in bioconda is stuck at `0.4.2`. This may have to do with recent versions not being available in [sourceforge](https://sourceforge.net/projects/crossmap/files/).

**Comment by bgruening** [comment]
Lets try to build a new version here https://github.com/bioconda/bioconda-recipes/pull/26007 :)

**Comment by bgruening** [comment]
Ok, this should be fixed now. Thanks for noticing!
