### ISSUE TITLE
Issues with the simulate_travis script

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#2609]
Team Bioconda,

Thanks for the updated instructions for local builds.  This is great. However, I've encountered a few errors when running the `simulate_travis.py script`.

1.  PATH variables aren't passed. I'm on OSX and when I run simulate_travis i get an error about conda. It seems that the script calls out to scripts/travis-run.py and that this gets its PATH from the following line:

    ```export PATH=/anaconda/bin:$PATH```

    In my case the anaconda bin PATH is in my home directory. Can we autodect the anaconda locations?

2.  Can we specify the OS to build on the CLI? It would be nice to specify `linux` builds as well.

Thanks.
zach cp

**Comment by daler** [comment]
@zachcp Sorry about that, I wasn't updating the environment passed to `travis-run.sh` with the shell environment. As of #2610 PATH should make it through now, and you can set TRAVIS_OS_NAME to linux (check the help for `simulate-travis.py`) to build for linux while running on a mac.

**Comment by zachcp** [comment]
@daler  - you are the man.
