### ISSUE TITLE
Label gunc 0.1.2 as broken

### ISSUE THREAD

**Issue by fullama** [bioconda/bioconda-recipes#26105]
Can gunc 0.1.2 be labelled as broken?

The initial version of gunc I realeased was accidentally broken.. it will never work (a required file was not included). I know the policy is never to remove packages but as far as I can tell the alternative is to have it labelled as broken? I am having users complaining the tool doesn’t work because this is the version that got installed instead of the latest version (this I guess is not unexpected as I had looser requirements for the first version.

**Comment by dpryan79** [comment]
Sure, done.
