### ISSUE TITLE
Optimizing a conda recipe?

### ISSUE THREAD

**Issue by gtrichard** [bioconda/bioconda-recipes#26285]
Hello,

I have an issue with deepstats recipe. Using the following command-line it works, but it takes a long time to solve the environment (so long that CircleCI is timed out, so it's even the case on a clean and freshly installed miniconda).

`conda create -c bioconda -c conda-forge -n deepStats python=3.7 deepStats`

The repo: https://github.com/gtrichard/deepStats
The recipe: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/deepstats

Is there any way to speed up the process (by declaring more dependencies explicitly, i.e. what the above command-line is returning?).

Thanks

EDIT: added downloaded packages as a text file.
[deepstats_reqs.txt](https://github.com/bioconda/bioconda-recipes/files/5836687/deepstats_reqs.txt)

**Comment by druvus** [comment]
you should swap the order of bioconda and conda-forge. I would also recommend using mamba on top of conda to speed up solving dependencies. I just confirmed that the following command works. 

`mamba create -c conda-forge -c bioconda -n deepStats python=3.7 deepStats`
