### ISSUE TITLE
Travis: the download failed but Travis is happy

### ISSUE THREAD

**Issue by lecorguille** [bioconda/bioconda-recipes#2649]
One of the download url is broken so,

Travis failed for OSX
https://travis-ci.org/bioconda/bioconda-recipes/jobs/169154254#L559

But succeed for Linux
https://travis-ci.org/bioconda/bioconda-recipes/jobs/169154252#L630

**Comment by rvalieris** [comment]
looks like the PR was merged, so I am closing this.
