### ISSUE TITLE
Bioconductor links are broken by new bioconductor releases

### ISSUE THREAD

**Issue by jrderuiter** [bioconda/bioconda-recipes#2650]
Bioconductor source links for many packages are now broken after the update of bioconductor from 3.3 to 3.4. This is because many links refer to the current release, rather than a specific bioconductor version. An example is the below link, which is now broken because this version of BSgenome is specific to bioconductor 3.3:

http://bioconductor.org/packages/release/bioc/src/contrib/BSgenome_1.40.1.tar.gz

The correct link would be:

http://bioconductor.org/packages/3.3/bioc/src/contrib/BSgenome_1.40.1.tar.gz

Similarly, we should refer to current versions of bioconductor by including the bioconductor version from the start:

http://bioconductor.org/packages/3.4/bioc/src/contrib/BSgenome_1.42.0.tar.gz

This would prevent source links being broken by new releases (e.g. bioconductor 3.5).

**Comment by jrderuiter** [comment]
Maybe slightly off-topic, but are there plans to migrate to bioconductor 3.4?

**Comment by jrderuiter** [comment]
And is there any reason that the bioconductor packages are not linked to specific R version(s)? As I understand, releases of bioconductor are linked to specific R version(s). This does not seem to be the case in the bioconda recipes.

**Comment by daler** [comment]
@jrderuiter see https://github.com/bioconda/bioconda-recipes/issues/2404. We are working on it but it is very time consuming. 

Many existing bioconductor packages were built before conda-build added the R version to the build string. So those still on the `sorted-r-blacklist` will not have the R version.

**Comment by jrderuiter** [comment]
Thanks, it wasn't clear for me if this also was included in that issue.

**Comment by bgruening** [comment]
We are now also mirroring all tarballs to cargo-port. So we should be able to replace all links in one go the next time we rebuild them.
@jrderuiter can you try to rebase #2647
