### ISSUE TITLE
ERROR: Could not determine if DFam is installed

### ISSUE THREAD

**Issue by yvanpapa** [bioconda/bioconda-recipes#26529]
Hi @abretaud, @nathanweeks, @johanneskoester, @kastman, @pvanheus, @jerowe, @bgruening and @ArneKr,

When running Maker 2.31.11-0 I get the following error:

```
Possible precedence issue with control flow operator at /nfs/scratch/papayv/bin/miniconda3/envs/genome_annotation/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
STATUS: Parsing control files...
ERROR: Could not determine if DFam is installed
--> rank=NA, hostname=c03n01
```

I know this is a very similar issue to this: https://github.com/bioconda/bioconda-recipes/issues/16501
I tried to set the RepeatMasker environment variables in my shell script as 

```
export REPEATMASKER_LIB_DIR=/nfs/scratch/papayv/bin/miniconda3/envs/genome_annotation/share/RepeatMasker/Libraries
export REPEATMASKER_MATRICES_DIR=/nfs/scratch/papayv/bin/miniconda3/envs/genome_annotation/share/RepeatMasker/Matrices
mpiexec -n 12 maker -base TARdn_V2P_rnd1 $dir/round1_maker_opts.ctl $dir/maker_bopts.ctl $dir/maker_exe.ctl
```
but the error is still exactly the same. I even tried to set REPEATMASKER_LIB_DIR to my own custom RepeatMasker library folder (which worked fine with RepeatMasker only), still no luck. Do you please have any insight on that issue?

Many thanks

**Comment by nathanweeks** [comment]
Hi @yvanpapa , the RepeatMasker 4.1.0 bioconda package removed support for the (bioconda-RepeatMasker-rspecific) REPEATMASKER_LIB_DIR environment variable, as the upstream RepeatMasker [added support for an equivalent LIBDIR environment variable](https://github.com/bioconda/bioconda-recipes/pull/21155#issuecomment-605297886).  maker 2.31.11-0 now checks for the [LIBDIR environment variable](https://github.com/bioconda/bioconda-recipes/pull/25586#issuecomment-737501951) as well.

**Comment by yvanpapa** [comment]
Thanks for the quick reply, that worked indeed by using `export LIBDIR` instead!

**Comment by gla1997** [comment]
> Thanks for the quick reply, that worked indeed by using `export LIBDIR` instead!

HI @yvanpapa ...I'm new to this and could you indicate how you solved the problem?
STATUS: Parsing control files...
ERROR: Could not determine if DFam is installed

**Comment by yvanpapa** [comment]
Hi @gla1997, 

The following worked for me:

**Comment by yvanpapa** [comment]
Hi @gla1997,
The following worked for me:
source activate maker [maker=the name of your conda environment with maker] 
export LIBDIR=*path to your conda environment*/miniconda3/envs/genome_annotation/share/RepeatMasker/Libraries
maker -base name opts.ctl exe.ctl etc... 

Works for me with the conda package recipe for maker 2.31.11-0.
This also works fine if you specify the path for LIBDIR to a custom repeat library that you set up yourself, e.g. as detailed here "Install RepeatMasker Libraries": http://www.repeatmasker.org/RepeatMasker/ 

Hope that helps

**Comment by gla1997** [comment]
Thank you. Now when I run maker it generates this error.
STATUS: Parsing control files ...
STATUS: Processing and indexing input FASTA files ...
mv: target 'genome / dpp_contig.maker.output / mpi_blastdb / dpp_est% 2Efasta.mpi.1.0 /' is not a directory
mv: target 'genome / dpp_contig.maker.output / mpi_blastdb / dpp_est% 2Efasta.mpi.1 /' is not a directory
ERROR: SplitDB not created correctly

 at /home/gilmar/anaconda3/envs/Anotaciones/bin/../lib/GI.pm line 1178.
GI :: split_db ("/ home / gilmar / Annotate genome / dpp_est.fasta", "nucleotide", 10, "/ home / gilmar / Annotate genome / dpp_contig.maker.output / mpi_blastdb", "C") called at / home / gilmar / anaconda3 / envs / Annotations / bin / maker line 534
-> rank = NA,
Do you have any idea what it could be?
