### ISSUE TITLE
biobb_vs: No Quai docker biocontainer created.

### ISSUE THREAD

**Issue by PauAndrio** [bioconda/bioconda-recipes#26533]
Hello,

After merging [PR 26446](https://github.com/bioconda/bioconda-recipes/pull/26446) the bioconda package has been updated correctly but the Quai docker biocontainer has not been created.

Where we can find any log or information about this process? So we can know if there is an error or just what's happening in the container creation process.

Kind regards,
Pau Andrio

**Comment by gbayarri** [comment]
Hi, it happens the same with [PR 26515](https://github.com/bioconda/bioconda-recipes/pull/26515).

Both of them are new bioconda packages. When updating the existing ones, it works.

Best.

**Comment by stain** [comment]
Any updates on this? We are not sure what is the process that generates the Biocontainers packages, or how it can be triggered?

**Comment by bgruening** [comment]
Repo is here: https://quay.io/repository/biocontainers/biobb_vs?tab=settings

**Comment by stain** [comment]
`docker pull quay.io/biocontainers/biobb_vs:3.5.0--py_0` seems to work for me. Thanks for checking @bgruening

**Comment by gbayarri** [comment]
Hi, @bgruening , thanks for your answer.

What about these two (new ones as well)?

https://quay.io/repository/biocontainers/biobb_amber?tab=tags
https://quay.io/repository/biocontainers/curves?tab=tags

Best.

**Comment by bgruening** [comment]
Same problem. Please use the bot to merge your PRs, this avoid this problem.

**Comment by bgruening** [comment]
Both are now available.

**Comment by gbayarri** [comment]
Ok, thanks a lot.
