### ISSUE TITLE
bioconductor-genomeinfodbdata | Link for database files are broken

### ISSUE THREAD

**Issue by caspargross** [bioconda/bioconda-recipes#26657]
The following links are broken:
`
https://bioconductor.org/packages/3.12/data/annotation/src/contrib/GenomeInfoDbData_1.2.4.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.4.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.4_src_all.tar.gz

`
![image](https://user-images.githubusercontent.com/10211013/107226344-4983cb00-6a1a-11eb-93bf-8da2ec4d8539.png)

**Comment by dlaehnemann** [comment]
I think, only the `bioarchive` link is still unavailable. I tried filing it upstream, but am unsure whether that is the right spot:
https://github.com/bioarchive/aRchive_source_code/issues/38

**Comment by dlaehnemann** [comment]
I guess this explains, why the bioarchive package isn't there:
https://github.com/bioconda/bioconda-recipes/pull/23728#issuecomment-668663952
