### ISSUE TITLE
Pangolin 2.3 fails with missing dependency

### ISSUE THREAD

**Issue by marchoeppner** [bioconda/bioconda-recipes#26849]
Hi,

I just tried the new Pangolin 2.3.0 via Biocontainers. 

Seems the recipie is missing a dependency:

```
  /bin/bash: gofasta: command not found

```
Cheers,
Marc

**Comment by olelund** [comment]
I ran into the same problem when I updated Pangolin today
Ole

**Comment by bgruening** [comment]
@druvus any idea about this one?

**Comment by olelund** [comment]
I managed to get it to work. I found it as a solved issue
https://github.com/cov-lineages/pangolin/issues/146


Basically after running the
pangolin --update

I also reran the pangolin installation scripts:
cd /path_to_pangolin/pangolin-master
conda env create -f environment.yml
conda activate pangolin
python setup.py install

Which I think should in principle not be needed, but it did the job

**Comment by druvus** [comment]
pangolin 2.3 changed dependencies to use gofasta instead of datafunk. The bioconda-bot update was merged without changes but I tried to fix it in #26887 so the pangolin 2.3.0 build 1 should be ok. You can also solve the issue manually by installing gofasta in the same environment. 

I tried it on Friday in a fresh environment and it was working. I will double check tonight.

**Comment by druvus** [comment]
I went back to check the dumped environment for pangolin that I output as a log for all analysis done by snakemake. 

Relevant software and version are shown in the snippets below:
```
dependencies:
  - gofasta=0.0.3=0
  - pangolearn=2021.02.18=pyh3252c3a_0
  - pangolin=2.3.0=py_1
  - ...
```

**Comment by druvus** [comment]
@olelund @marchoeppner could you please check your environment thar you are using build 1 of  pangolin v2.3.0 (pangolin=2.3.0=py_1)

**Comment by marchoeppner** [comment]
Hi and thanks for the quick fix - yes, the updated py_1 is working for me! Happy to close this.

**Comment by lbiernot** [comment]
Is there any real reason to use `pangolin --update`?
