### ISSUE TITLE
the new bioconda build system

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#2695]
@bioconda/all:

As of #2694, bioconda will be using [`bioconda-utils`](https://github.com/bioconda/bioconda-utils) for building all packages.

**The workflow will remain unchanged**. Contributors will still submit PRs with recipes and watch for them to be tested on travis-ci. The most noticeable difference is probably the improved logs to help debug recipes both locally and within travis-ci.

If you are interested in the changes, here is a high-level overview of what is different:
- better logs
- better tests for the build system
- better tests for built packages
- faster builds: if a package fails to build, any subsequent packages will be quickly skipped and noted in the log
- more comprehensive checks for which recipes should be built
- more uniform environment between osx and linux
- easier testing for developers (see `simulate-travis.py`)
- ability to blacklist recipes
- tested with the latest version of conda
- uses the latest conda-build API

During the [contribution fest](https://github.com/bioconda/bioconda-recipes/issues/2277) on Nov 2-3, I'll be adding detailed documentation on these changes and how everything works. For now, here's a little more detail:
## Build system tests

We finally have a test suite for the build infrastructure. It's difficult to predict all scenarios, so as new corner cases pop up during "production" in bioconda-recipes, we can add tests for them and ensure those problems don't happen again.
## Built package tests

Packages have always been tested by conda-build immediately after building, inside the container that does the building. But now, thanks to @bgruening, @thriqon ([`involucro`](https://github.com/involucro/involucro)) and [`galaxy-lib`](https://github.com/galaxyproject/galaxy-lib), each built package is tested in its own isolated, minimal docker container (busybox for those keeping track . . .). While not implemented yet, the pieces are in place to then push these containers to a repository as in [mulled](https://github.com/mulled/mulled).

That is, every successful recipe that makes it into bioconda will automatically get its own docker image on quay.io.
## Configuration

Configuration occurs via these files:
- `.travis.yml`
- `config.yml`
- `scripts/env_matrix.yaml`
- `scripts/travis-setup.sh`
- `scripts/travis-run.sh`

More details on how things work together will be added to the docs Nov 2-3.
## Side effects
- running `bioconda-utils build --docker` will build a recipe in a CentOS6 docker container, test it in a minimal busybox container, and place the resulting built recipe in the host's conda-bld directory for local installation. Since this is basically the same command used on travis-ci, it makes it easier to confirm locally that a new recipe is working before submitting a PR.
- The `bioconda-utils dependent` tool can be used to identify the entire dependency chain or reverse-dependency chain of a recipe to figure out what other recipes will be affected or might need to be rebuilt.
- The `bioconda-utils dag` can be used for inspecting the DAG of all recipes
- If you're on OSX and have docker installed, you can build and test recipes for linux and osx:

``` bash
# test on host osx
./simulate-travis.py

# test using docker
./simulate-travis.py --docker

```

**Comment by chapmanb** [comment]
Ryan;
This is amazing work, thank you. I've gotten way behind on understanding how the build infrastructure works and would definitely appreciate documentation on the best way to setup for local testing. I've got something cobbled together `condaforge/linux-anvil` and `bioconda-utils build` but am guessing it's suboptimal with all these fixes. Looking forward to understanding this better once you've had time to document all the details. Thanks again.

**Comment by daler** [comment]
Hi Brad - once you have bioconda-utils installed, the short answer is to use `simulate-travis.py`. This [FAQ section](https://github.com/bioconda/bioconda-recipes/blob/master/FAQs.md#how-do-i-get-set-up-to-test-recipes-locally) might give some extra details but you're probably aware of them already.

The biggest hurdle at the moment for the docs is figuring out how to describe everything coherently without sounding like it's just recapitulating the source code.

Please let me know if anything's unclear or if you have suggestions about how to make it clearer.

**Comment by bgruening** [comment]
bioconda-utils is awesome and powers the entire bioconda community. Thanks a lot @daler for all your work you have put into it.
