### ISSUE TITLE
Remove cgat-core from the channel

### ISSUE THREAD

**Issue by Acribbs** [bioconda/bioconda-recipes#27017]
@bioconda/core 

In cgatcore recipe I once accidentally renamed the name to cgat-core(https://github.com/bioconda/bioconda-recipes/pull/16094).

I was wondering if it is possible to remove the cgat-core from the channel?

**Comment by dpryan79** [comment]
We could, but doing so could break someone's environment if they happen to have it installed and go to either update everything or install another package. Unless its existence is causing a problem it's usually best to leave it there.

**Comment by Acribbs** [comment]
Thanks Devon,

The potential problem would be that if there is a dual installation of cgatcore and cgat-core, I have no idea what this would do to the persons environment.

**Comment by sebastian-luna-valero** [comment]
Hi,

I agree with @Acribbs  the release of `cgat-core` was unintended, and therefore it should be removed from the channel. No one should depend on it, and there is an equivalent `cgatcore` version released. Going forward we want to avoid further confusion by just having `cgatcore` available. If users have problems, they should open an issue in https://github.com/cgat-developers/cgat-core/issues and we can explain and help them.

Just as a reference, here is a comparison on the number of downloads on both packages:
https://anaconda.org/bioconda/cgatcore
https://anaconda.org/bioconda/cgat-core

Best regards,
Sebastian

**Comment by dpryan79** [comment]
Fair enough, I'll remove the package.

**Comment by Acribbs** [comment]
Thanks very much for this @dpryan79

**Comment by sebastian-luna-valero** [comment]
Many thanks @dpryan79
