### ISSUE TITLE
FastANI incompatible with R in macOS

### ISSUE THREAD

**Issue by lmrodriguezr** [bioconda/bioconda-recipes#27120]
Hello bioconda community,

First off, thanks for you great work!

I'd like to deploy a package using conda, but I'm finding a conflict in libraries between *FastANI* and recent versions of *R* in macOS.

For example, this simple command runs forever trying to resolve the environment (without success):
```
conda create -n fastani-r -c conda-forge -c bioconda r fastani
```

On the other hand, attempting to install `fastani` with `r-base` (instead of `r`) does work, but it gets resolved to R 3.3.1 (the current version in conda-forge is 4.0.3). I'm not sure what's the FastANI library at fault here.

Thanks!
Miguel.

**Comment by bgruening** [comment]
Please try  `conda create -n fastani-r -c conda-forge -c bioconda r-base=4 fastani`

**Comment by lmrodriguezr** [comment]
With `conda create -n fastani-r -c conda-forge -c bioconda r-base=4 fastani` I get the following error:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                            

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package llvm-openmp conflicts for:
r-base=4 -> llvm-openmp[version='>=10.0.0|>=11.0.0|>=11.0.1']
r-base=4 -> libgfortran5[version='>=9.3.0'] -> llvm-openmp[version='10.0.0.*|>=10.0.1|>=8.0.0|>=8.0.1']
fastani -> openmp[version='>=4.0'] -> llvm-openmp[version='8.0.0|8.0.0|8.0.1',build='h770b8ee_0|h770b8ee_1|h770b8ee_0']

Package libcxx conflicts for:
fastani -> boost[version='>=1.70.0,<1.70.1.0a0'] -> libcxx[version='>=9.0.0']
fastani -> libcxx[version='>=4.0.1|>=4.0|>=9.0.1']
```

**Comment by bgruening** [comment]
> conda create -n fastani-r -c conda-forge -c bioconda r-base=3.6 fastani

works for me :)

**Comment by lmrodriguezr** [comment]
Thanks a lot for your hellp @bgruening !
