### ISSUE TITLE
Software requests

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#2719]
Hi, 
Seqping (https://sourceforge.net/projects/seqping/) has the following: 
- BLAST 2.2.25 (ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/)
- CD-HIT 4.5.4 (http://www.bioinformatics.org/downloads/index.php/cd-hit/)
- Exonerate 2.2 (http://www.ebi.ac.uk/~guy/exonerate/)
- GlimmerHMM 3.0 (ftp://ccb.jhu.edu/pub/software/glimmerhmm/)
- AUGUSTUS 2.6.1 (http://bioinf.uni-greifswald.de/augustus/binaries/)
- SNAP-2012-05-17 (http://korflab.ucdavis.edu/Software/)
- MAKER 2.28 (http://www.yandell-lab.org/software/maker.html)
- EMBOSS 6.4.0 (http://emboss.sourceforge.net/download/)
- HMMER 3 (http://hmmer.janelia.org/software)
- RepeatMasker-3-3-0 (http://www.repeatmasker.org/RMDownload.html)
- NCBI C++ Toolkit (ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools++/)

Would you be able to provide it?

Thank you in advance.

Mic

**Comment by bgruening** [comment]
We accepting Pull Requests :-)

**Comment by bgruening** [comment]
@mictadlo if you like join us during your Contribution fest: https://github.com/bioconda/bioconda-recipes/issues/2277

... and we will get you kickstarted!

**Comment by druvus** [comment]
I quickly checked what already exist in bioconda and repos it depends on.

- [x] BLAST (2.5.0)
- [x] CD-HIT (4.6.0)
- [x] Exonerate (2.2.0) (missing osx)
- [ ] GlimmerHmm
- [x] Augustus (3.2.2) (missing osx)
- [x] SNAP (2013_11_29)
- [ ] Maker
- [x] Emboss (6.5.7)
- [x] HMMER (3.1b2)
- [x] Repeatmasker (4.0.6) (missing osx)
- [ ] NCBI C++ toolkit

For linux three additional packages are needed. An issue is Maker that requires registering on their home page before downloading source code. The people behind Maker needs to be contacted to be able  to fix dependencies for Seqping

**Comment by druvus** [comment]
Seems only NCBI C++ toolkit is missing now.

**Comment by bgruening** [comment]
@druvus thanks for checking this!!!

**Comment by bgruening** [comment]
migrated the last missing one to https://github.com/bioconda/bioconda-recipes/issues/17729
