### ISSUE TITLE
Investigate other CI systems

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#2764]
Given the vast amount of PR every day I think it makes sense to split our testing into 2 different CI systems. Similar to what conda-forge is doing. Travis can do the OSX jobs and some other service could take over the Linux builds.

**Comment by hainm** [comment]
I've been using [circleci](https://circleci.com) and seems to be a good additional ci.

- ssh for debugging
- easy to retrieve artifacts

**Comment by colinbrislawn** [comment]
There are tons of CI services, and it's a little tricky to differentiate them. I'll add [wercker](http://www.wercker.com/) to the list.

- 2 concurrent jobs
- Strong Docker support
- [Example package](https://github.com/jakirkham/splauncher) using both travis and wercker (for different parts of the build)

I'm not sure which parts of the build are worth splitting out, but wercker could be a good fit for making Docker containers.

**Comment by bgruening** [comment]
Since the issue we tried a few others but at the moment we are quite happy with travis and the `bulk` branch. Closing for now.
