### ISSUE TITLE
Expand functionality of bioconda-utils: validation, hash population, secure urls, and automated package updates

### ISSUE THREAD

**Issue by tomkinsc** [bioconda/bioconda-recipes#2777]
For processes that can be automated, I would advocate adding functions to [`bioconda-utils`](https://github.com/bioconda/bioconda-utils/tree/master/bioconda_utils) so we can easily repeat parts of this effort in the future.

#### A few potential functions to automate:
- `source_url_https <package_name>` — changes urls `http://` -> `https://` for hostnames known to support TLS (github, etc.)
- `list_sources_without_hash <package_name> [--update_recipe]` — lists packages that include `url:` but no `md5:`/`sha1:`/`sha257:`/etc, perhaps with an optional argument to automatically populate hash values: download each source for a package, calculate hashes, and add to the recipe) 
- `validate_recipe <package_name>` — a validation function, including https://github.com/bioconda/bioconda-utils/issues/19 and checks of our own: that the license field is populated, that https is used for known TLS hostnames, etc.
- `attempt_version_update <package_name> [--leave_on_build_failture]` — A function to update a recipe and try to build it, where possible. For packages sourced from GitHub, this is a matter of comparing the current version with the most recent release/tag, with an optional function to convert the GitHub tag to the version used by conda (i.e. strip the preceding `v` from `v1.x`). Not sure how feasible this would be for sourceforge packages. This is in response to #2282. If the build fails after the automated update attempt, the recipe could be rolled back, or left as-is for manual fixes. We could also imagine having an optional script, `update-version.py` in each recipe directory, with a function, `determine_latest_url()`, that would return the package-appropriate url for latest version of a given package.

For each of these, a package name could be provided, or if omitted all bioconda packages would be used.

**Comment by epruesse** [comment]
Got most of this by now.
