### ISSUE TITLE
(t)csh needed as alternative shell for builds

### ISSUE THREAD

**Issue by martin-raden** [bioconda/bioconda-recipes#2792]
@bioconda/core  We (me and @druvus) do encounter the problem that some tools (e.g. NCBI toolkit) come with `csh` make scripts, see #2587, that cannot be bypassed when building from source (available binaries not working due to glibc problems).

I just discussed with @bgruening that it should be no problem to add the `tcsh` package to the general docker container unless you set `bash` to be the standard shell. This way, one can run the `csh` script within the bash build scripts using `csh -f FILE` and there is no change for any other stuff needed.

Please discuss with the other dependent communities. Would be great to have!

Thanks,
Martin

**Comment by johanneskoester** [comment]
Sounds good to me!

**Comment by martin-mann** [comment]
Any status/plan update?

**Comment by johanneskoester** [comment]
@jakirkham we need an optional tcsh for building certain packages. Since we use the same docker image, what is your opinion on adding tcsh to condaforge/linux-anvil?

**Comment by epruesse** [comment]
I assume this was fixed.
