### ISSUE TITLE
Download binaries of old Blast+ instead of compiling

### ISSUE THREAD

**Issue by jlanga** [bioconda/bioconda-recipes#2795]
Hi.

I want to contribute and learn to make recipes in Bioconda by adding the recipes of the older Blast+ versions (from 2.2.18 to 2.4.0).

I've been able to run `simulate-travis.py` on my machine and it exits successfully. My problem comes when using the real Travis: it runs out of time. 

I've read blast-legacy's [meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/blast-legacy/2.2.22/meta.yaml) and it is written to download binaries instead of compiling from source.

Is it OK to just download NCBI's blast+ binaries, as in OSX, at least for the older versions, for Linux?

Thanks,

Jorge

**Comment by daler** [comment]
Binaries sound fine to me for older versions if there's no clear way to speed up builds and if we're already doing it for OSX. I suppose the mulled-build test will tell us if the binaries are truly portable. @bioconda/core thoughts?

**Comment by martin-mann** [comment]
Hi,

it seems there are some problems with the precompiled blast-legacy binaries (see #2587), so we are working on a build from source, which is currently hindered due to the missing (t)csh shell in the base system (see #2792).

Just to let you know...

**Comment by jlanga** [comment]
Hi @martin-mann. I was successfully compiling those blast+ versions in my laptop with `conda build` and `simulate-travis.py`. I think it's only an issue in `blast-legacy`.

The major issue I found was with `conda build` because I have installed `g++-5`.

@bioconda/core: I've [tested](https://travis-ci.org/jlanga/bioconda-recipes/builds) all 15 blast+ recipes on Travis. I made a pull request for the first one. Remember that they are downloading binaries for both Linux and OSX versions because it takes more than 50 minutes. Also, I made one branch per version because Travis runs out of space when downloading and decompressing all at once.

Do I have your blessing before adding 14 more pull requests?

Thanks,

Jorge

**Comment by daler** [comment]
@jlanga looking great! Would you mind submitting 1 PR at a time?  That is, submit one PR, wait for it to pass, merge into master and wait that to pass, before opening another PR. The reason is that travis-ci is pretty slow recently and 14 long-running PRs would pretty much block any other PRs from running for something like a day or two.

**Comment by jlanga** [comment]
Hi @daler. I have already one branch per version in my fork, all of them tested in Travis. So as you say, I'll be doing one or two merges to master per day to allow other people's work.

**Comment by bgruening** [comment]
@jlanga @daler do we agreed here to create 14 binary packages or compiled ones?
I think @martin-mann was able to compile them as soon as we can fix: https://github.com/bioconda/bioconda-recipes/issues/2792

**Comment by peterjc** [comment]
Personally I am comfortable with using the NCBI provided binaries - from a reproducibility perspective this is preferable to a fresh compilation which may use different versions of the compiler chain or library dependencies, and the NCBI have done a good job with making portable binaries.

(For the Galaxy BLAST packages https://github.com/peterjc/galaxy_blast/tree/master/packages it was also far more practical to use the binaries compared to trying to create a working build environment on an arbitrary user's machine)

**Comment by bgruening** [comment]
Peter do you know if these binaries are centos6 compatible and will stay so?

**Comment by peterjc** [comment]
We're still running CentOS6 on our cluster, and I have not had compatibility problems with the NCBI provided BLAST+ binaries. Do you want me to check any in particular?

**Comment by bgruening** [comment]
@peterjc no need to. Just wanted to check if the binaries are compatible, as this is requirement.
Imho, I have no strict opinion on self-compiling or pre-compiled binaries as long as they work on CentOS. Question is still if we want to split the package into multiple ones.

**Comment by bgruening** [comment]
There is now a blast-legacy package and people seem to be happy with it. Please reopen if you need older version of this package or if there is still an issue.

Thanks!
