### ISSUE TITLE
r-ahocorasicktrie requires Rcpp >= 0.12.5

### ISSUE THREAD

**Issue by claresloggett** [bioconda/bioconda-recipes#2797]
On my system recipe r-ahocorasicktrie fails. `conda_build.sh` attempts to install the R package, and fails with `namespace ‘Rcpp’ 0.12.1 is being loaded, but >= 0.12.5 is required`

Presumably needs a version number on the Rcpp requirement in meta.yaml?

**Comment by bgruening** [comment]
@claresloggett do you still encounter this problem? There should be a version `0.12.8` for Rcpp now.

**Comment by bgruening** [comment]
Closing for now. This should work now, please re-open otherwise!
