### ISSUE TITLE
R/bioconductor hackathon small-ish tasks

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#2799]
If anyone is looking for a small-ish chunk to work on for the hackathon, here are some ideas that could help. In most cases, check `sorted-r-blacklist` for comments.

-  there are a few package that have rgl issues that we've skipped for now, and it would be nice to get them fixed (e.g., `r-ks`).

- `r-spp` 1.14 appears to be having boost issues.

- there are several packages with older versions that don't have stable URLs. This is probably a matter of poking around the bioconductor site.

- `rsem` is giving zlib errors. It probably needs a patch

- `cap-mirseq` has an error that needs looking into

- if `autoconf` is worked out (ping @druvus), `bioconductor-rhtslib` and `bioconductor-csaw` can be added

**Comment by druvus** [comment]
@daler autoconf is building correctly on the image but I not sure it actually got tested by travis. I am currently away from the computer so I am happy if someone could check the autoconf build.

**Comment by daler** [comment]
@druvus I figured out what the issue is, see #2793. I'll be updating bioconda-utils to only filter out a recipe if a package is in bioconda (and don't care if it's in conda-forge, r, or defaults).

**Comment by druvus** [comment]
Thanks I missed that this filter was already implemented.

**Comment by bgruening** [comment]
@daler we should update or create a new issue with this and assemble a small task force to clean up the black list(s).

**Comment by daler** [comment]
@bgruening sounds good, let's close this one.
