### ISSUE TITLE
fastANI dependencies

### ISSUE THREAD

**Issue by alienzj** [bioconda/bioconda-recipes#28032]
![image](https://user-images.githubusercontent.com/8847420/114801813-0d306a80-9dcf-11eb-8c92-7c004feff3a0.png)

Hi, how to update the version dependency of fastANI on boost? 

Many software relies on higher versions of boost, which makes fastANI unable to be installed in the same environment as many software.

**Comment by bernt-matthias** [comment]
Hi @alienzj can you post your question at https://github.com/bioconda/bioconda-recipes/ or https://gitter.im/bioconda/Lobby?

**Comment by bernt-matthias** [comment]
Sorry my bad :)

**Comment by alienzj** [comment]
> Hi @alienzj can you post your question at https://github.com/bioconda/bioconda-recipes/ or https://gitter.im/bioconda/Lobby?
Hi, thanks thanks for your reminder.
