### ISSUE TITLE
`mummer` build 12 introduces error (bad Perl interpreter)

### ISSUE THREAD

**Issue by widdowquinn** [bioconda/bioconda-recipes#28209]
Build 12 of mummer errors for me (on macOS Mojave); build 11 does not.

With build 12:

```bash
$ nucmer --version
-bash: /Users/lpritc/opt/anaconda3/envs/pyani_py38/bin/nucmer: /usr/local/bin/perl: bad interpreter: No such file or directory
```

With build 11:

```bash
$ conda install mummer=3.23=h6de7cb9_11
$ nucmer --version
nucmer 
NUCmer (NUCleotide MUMmer) version 3.1
```

**Comment by rpetit3** [comment]
Seeing that alot now as well.

I wonder if patching the nucmer scripts to replace `/usr/local/bin/perl` with `/usr/bin/env perl` would work.

**Comment by peterjc** [comment]
I just ran into this problem too, and my hunch was the same - the hash-bang lines need changing from ``/usr/local/bin/perl``

**Comment by peterjc** [comment]
Confirming that downgrading to build 11 fixes it on macOS Monterey 12.0.1

```
$ mamba install mummer=3.23=h6de7cb9_11
...
$ head -n 1 `which nucmer`
#!/usr/bin/perl
```

Still would have thought it should use the Conda provided Perl, not the system one.

**Comment by widdowquinn** [comment]
Bumping, as this problem persists in build `h770b8ee_9`, which is the default build at the current date.

```bash
% nucmer
<PATH_TO>/bin/nucmer: bad interpreter: /usr/local/bin/perl: no such file or directory
% conda search mummer
Loading channels: done
# Name                       Version           Build  Channel
mummer                          3.23               1  bioconda
mummer                          3.23               2  bioconda
mummer                          3.23               3  bioconda
mummer                          3.23               4  bioconda
mummer                          3.23               5  bioconda
mummer                          3.23               6  bioconda
mummer                          3.23               7  bioconda
mummer                          3.23               8  bioconda
mummer                          3.23     h589c0e0_12  bioconda
mummer                          3.23     h6de7cb9_10  bioconda
mummer                          3.23     h6de7cb9_11  bioconda
mummer                          3.23      h770b8ee_9  bioconda
```

The fix is still to downgrade to `h6de7cb9_11`

**Comment by Adamtaranto** [comment]
Still an issue in:
`mummer    v3.23            h589c0e0_12          bioconda`

Fixed by replacing the shebang line in nucmer with the correct location of perl in my env.

Looks like there are other variables in there that are specific to my env. Can the perl path not be set at build?
