### ISSUE TITLE
Updating Bioconda recipe on Windows

### ISSUE THREAD

**Issue by llegregam** [bioconda/bioconda-recipes#28206]
Hello,

I have recently uploaded a package onto bioconda. I now need to update the package, but the documentation only refers to a way of doing it using bioconda-utils. The problem is I work on windows so I cannot install and use bioconda-utils. Is there a manual way I can update my package?

Thank you in advance.

**Comment by druvus** [comment]
Bioconda only support Linux and MacOS. However you may use Bioconda on Windows using Lunux subsystem by following the following [guide](https://github.com/kapsakcj/win10-linux-conda-how-to).
