### ISSUE TITLE
autoconf

### ISSUE THREAD

**Issue by druvus** [bioconda/bioconda-recipes#2821]
I have now spent some time to understand why autoconf build is failing using bioconda's setup while it is built successfully at conda-forge. The difference semms to be the version of conda-build  used in the two projects (2.0.0 vs. 1.21.14). conda-forge includes the following in their setup script to force using a version v1 of conda-build. 

<pre>
# KLUDGE to work around changes in conda-build 2.0.0
conda install -n root --yes --quiet conda-build=1
</pre>

The autoconf tool only needs m4 and perl-threaded as requirements. 

I have used the condaforge/linux-anvil image to confirm that the package builds successfully if I downgrade the conda-build version to 1.21.14 while everything else is like the bioconda setup. It doesn't work with any 2.0.x version. 

It seems basically be some issues with newer conda-build version causing the problem. I don't really know how to proceed here  so any help or suggestion would be appreciated.

**Comment by bgruening** [comment]
I'm fine with including the hack from conda-forge here as well - in the build-sh script.
@druvus I probably ask this before, but why not getting this fix upstream? Unlikely?

**Comment by druvus** [comment]
I initially thought it would be faster to fix the bioconda version. It seems that the conda-forge version correctly adds the correct absolute path to the shebang. See the snippet below where I am using a environment called test on the docker image. It is not generic but it get correct for the environment it get installed to. The only drawback is the pinned perl version but it would probably not matter as it is only used during building.

<pre>
(test) [root@22581e410061 tmp]# conda install -c conda-forge autoconf
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment /anaconda/envs/test:

The following NEW packages will be INSTALLED:

    autoconf: 2.69-pl5.20.3.1_3 conda-forge

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#########################################################################################| 100%
(test) [root@22581e410061 tmp]# which autoreconf
/anaconda/envs/test/bin/autoreconf
(test) [root@22581e410061 tmp]# head /anaconda/envs/test/bin/autoreconf
#! /anaconda/envs/test/bin/perl -w
# -*- perl -*-
# Generated from autoreconf.in; do not edit by hand.

eval 'case $# in 0) exec /anaconda/envs/test/bin/perl -S "$0";; *) exec /anaconda/envs/test/bin/perl -S "$0" "$@";; esac'
    if 0;

# autoreconf - install the GNU Build System in a directory tree
# Copyright (C) 1994, 1999-2012 Free Software Foundation, Inc.
</pre>

The simplest solution would probably be to erase bioconda's autoconf both from github repo and anaconda even if it is not so good practise.

**Comment by bgruening** [comment]
@daler @johanneskoester what do you think? I'm ok with removing it, also it's not ideal but it is a build dependency and should only be relevant during rebuilds ... which we hardly can do at the moment.

**Comment by druvus** [comment]
Fixed in #2825. Thanks @dyusuf
