### ISSUE TITLE
Travis prefers defaults over conda-forge

### ISSUE THREAD

**Issue by glormph** [bioconda/bioconda-recipes#2853]
When building a recipe I needed boost from `conda-forge` (`defaults` doesn't include static libs). This worked fine in a local conda build run, but when pushing to travis the jobs failed because boost was installed from `defaults` anyway.

My guess is that my local conda has channels ordered with conda-forge before defaults (as specified in my `.condarc` file) and that it stops searching after it finds the first channel.

Should there be a standard order in bioconda, or a way to order or specify the channels before a build/run?

**Comment by daler** [comment]
The recent changes were inconsistent across docs and travis-ci, which is probably what was causing this. See #2862 for the PR that fixes it.

However, we need to choose a single consistent channel order, and we decided that defaults should have higher priority than conda-forge. See #2675 for details.

@johanneskoester maybe we should keep track of cases like this, where the conda-forge should have higher priority, as well as other cases where defaults should have higher priority, to see if we can empirically arrive at the best channel order given the kinds of dependencies used in bioconda recipes.

**Comment by glormph** [comment]
In my particular case I just specified a version not in defaults and that fixed it, but good to know. I assume the issue can be closed.

**Comment by johanneskoester** [comment]
@glormph, can you refer to the problematic PR please?

**Comment by glormph** [comment]
Sure, it was my [percolator again PR](https://github.com/bioconda/bioconda-recipes/pull/2854)

**Comment by johanneskoester** [comment]
The hardcoding of boost is a bit problematic though. It will cause incompatibilities with other packages in bioconda that depend on a different boost version. That's why we have the global variable for that.

So, in your case, what was the problem with the boost version from default?

**Comment by glormph** [comment]
The default boost did not install static libs. The conda-forge one does.

Another way around it would be installing boost from source. Since I only need filesystem and system libs it would maybe not take as much time as a full install (which would timeout Travis).

Not sure I understand the problem with the hardcoding. Do you mean the buildstring or the requirement?

**Comment by johanneskoester** [comment]
I mean the requirement. Say two packages depend on boost. One on the version we consistently define globally, the other on a differnt one. They cannot be installed into the same environment. This is fine if there is a technical reason for depending on a particular version. But it is not ok, if the only reason to use a different version is to work around a more fundamental problem. 

But wait, the tool links statically against boost? In that case, you don't even need the runtime dependency, don't you?

**Comment by glormph** [comment]
Good catch! I am really quite a noob at packaging (and compiling) but I think I understand that. Will give it a try immediately!

**Comment by johanneskoester** [comment]
When you create a new PR, please also refer this issue and the old PR and ping me.
Thanks!

**Comment by glormph** [comment]
Will do. One thing, the buildstring (which contains boost version), will I need to remove that? In other words, is that for showing what it runs with, or what it was built with?

**Comment by johanneskoester** [comment]
You can keep that. It is for the build dependency.
