### ISSUE TITLE
sra-tools 2.11.0 built invalid

### ISSUE THREAD

**Issue by janstrauss1** [bioconda/bioconda-recipes#28596]
Hi there,

I installed the most recent SRA toolkit using `conda install sra-tools`.
Yet, I keep getting the following error:
```
An error occured: std::exception
If this continues to happen, please contact the SRA Toolkit at https://trace.ncbi.nlm.nih.gov/Traces/sra/
```
Searching for similar issues at [sra](https://github.com/ncbi/sra-tools), I can read at [https://github.com/ncbi/sra-tools/issues/497#issuecomment-831906642](https://github.com/ncbi/sra-tools/issues/497#issuecomment-831906642) that the conda built may be invalid.

Many thanks in advance for any help!

**Comment by kfuku52** [comment]
I have confirmed that this problem is continuing. Downgrading sra-tools worked well for me: `conda install sra-tools=2.10`
