### ISSUE TITLE
default simulate-travis.py run requires mulled-build

### ISSUE THREAD

**Issue by dkoppstein** [bioconda/bioconda-recipes#2887]
I was trying to test out a few new packages, using the new command in the documentation: 

`./simulate-travis.py --packages bioconductor-ebarrays --loglevel=debug`

However, the build fails here:

```
DEBUG bioconda_utils.pkg_test:test_package(112): mulled-build commands: ['mulled-build', 'build-and-test', 'bioconductor-ebarrays=2.38.0=r3.3.1_0', '--name-override', 'tmp', '--test', 'Rscript -e "library(\'EBarrays\')"', '--extra-channel', 'conda-forge', '--extra-channel', 'defaults', '--extra-channel', 'r', '--extra-channel', 'bioconda', '--extra-channel', 'file://efs/home/dkoppstein/miniconda3-4.0.5/conda-bld']
```

presumably because I don't have mulled-build in my PATH. I'm not sure where to get this executable and it's not in the documentation, am I invoking simulate-travis incorrectly?

**Comment by bgruening** [comment]
Try to install galaxy-lib. This should give you the executable.

**Comment by dkoppstein** [comment]
Thanks @bgruening, that worked. My build is succeeding now; however, I'm still getting a warning from bioconda_utils that `involucro` can't be found. Perhaps we should update the README.md to direct users building their own packages to install galaxy-utils and whatever package has `involucro`? 

Here's the relevant part of the debug log: 

```
DEBUG bioconda_utils.pkg_test:test_package(101): Tests to run: Rscript -e "library('EBarrays')"
DEBUG bioconda_utils.pkg_test:test_package(112): mulled-build commands: ['mulled-build', 'build-and-test', 'bioconductor-ebarrays=2.38.0=r3.3.1_0', '--name-override', 'tmp', '--test', 'Rscript -e "library(\'EBarrays\')"', '--extra-channel', 'conda-forge', '--extra-channel', 'defaults', '--extra-channel', 'r', '--extra-channel', 'bioconda', '--extra-channel', 'file://efs/home/dkoppstein/miniconda3-4.0.5/conda-bld']
INFO bioconda_utils.build:build(128): BIOCONDA TEST SUCCESS recipes/bioconductor-ebarrays, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
DEBUG bioconda_utils.build:build(129): STDOUT:
/bin/sh: 1: involucro: not found
WARNING: Overriding mulled image name, auto-detection of 'mulled' package attributes will fail to detect result.
involucro -v=3 -f /efs/home/dkoppstein/miniconda3-4.0.5/lib/python3.5/site-packages/galaxy_lib-16.10.9-py3.5.egg/galaxy/tools/deps/mulled/invfile.lua -set CHANNELS='bioconda,file://efs/home/dkoppstein/miniconda3-4.0.5/conda-bld' -set TEST='Rscript -e "library('EBarrays')"' -set TARGETS='bioconductor-ebarrays=2.38.0=r3.3.1_0' -set REPO='quay.io/mulled/tmp' -set BINDS='build/dist:/usr/local/,/s/home/dkoppstein/miniconda3-4.0.5/conda-bld:/s/home/dkoppstein/miniconda3-4.0.5/conda-bld' build-and-test
```

**Comment by daler** [comment]
@dkoppstein there was a typo in the FAQ, should be fixed soon in master (see #2897, #2898 )

`involucro` should be downloaded by mulled-build and placed in the current directory. @bgruening would it be possible to have a

```
mulled-build get-involucro /path-to-put-involucro
````

command to make this step more explicit?

**Comment by bgruening** [comment]
If I remember correctly I have created an involcro conda package which galaxy-lib depends on ... and so on ... :)
Closing this, please reopen if I did all this just in my dreams.

**Comment by yesimon** [comment]
I've installed `bioconda-utils` as a pip egg and `mulled-build` was not found. Thus `galaxy-lib` was not automatically installed. Can we add `galaxy-lib` to the pip requirements as well?
