### ISSUE TITLE
bulding R pacakge on OSX - Library not loaded: @rpath/libreadline.6.2.dylib

### ISSUE THREAD

**Issue by dyusuf** [bioconda/bioconda-recipes#2904]
This is an unusual error starting to appear during last two days. 

please check the Travis output: 
https://travis-ci.org/bioconda/bioconda-recipes/jobs/174520712

The same recipe was successful two days ago.
https://travis-ci.org/bioconda/bioconda-recipes/jobs/174406798

From yesterday, all R packages in my doing list got the same error on OSX.

**Comment by dyusuf** [comment]
As commented in #2900, it is related to channel order.

**Comment by bgruening** [comment]
Fixed by @daler!

**Comment by dyusuf** [comment]
@daler thanks!
