### ISSUE TITLE
enable bioperl 1.7.* for osx : currently for linux only

### ISSUE THREAD

**Issue by martin-raden** [bioconda/bioconda-recipes#2910]
Due to the new bioperl 1.7 dependencies

```
 - perl-db-file
 - perl-dbd-mysql 
```

that are NOT available for osx, the new `perl-bioperl` 1.7.1 is only available for linux.

@bgruening started already to get the dependencies working on osx in the [perl-osx-nov](https://github.com/bioconda/bioconda-recipes/compare/perl-osx-nov?expand=1) branch, but failed so far. So please, everybody interested in osx builds contribute there!

an upgrade to bioperl >=1.7 is needed due to the current/coming transition of NCBI services to https (and the shutdown of the http-services used by bioperl <1.7).

hope this helps to get it enabled soon,

Martin

**Comment by martin-mann** [comment]
Maybe something I found concerning osx issues faced in the perl-osx-nov branch:

 [https://github.com/minrk/patch-conda-rpaths](https://github.com/minrk/patch-conda-rpaths)

plus discussion here:

 [https://github.com/ContinuumIO/anaconda-issues/issues/498](https://github.com/ContinuumIO/anaconda-issues/issues/498)

which might be also related to #2904

**Comment by epruesse** [comment]
bioperl is available for osx these days
