### ISSUE TITLE
Perl-bioperl-core-1.7.1 package broken.. please remove!!

### ISSUE THREAD

**Issue by martin-raden** [bioconda/bioconda-recipes#2917]
@bgruening I am crying... the bioperl 1.7 package (which kept me busy for more than a week) is not packed correctly.. even with successful travis build... (test was disabled due to cyclic deps...)

See file size: [perl-bioperl-core-1.7.1](https://anaconda.org/bioconda/perl-bioperl-core/files) = 14kb ...

Please remove the 1.7 package from the channel.

This causes no problems, since the `perl-bioperl` package is hard tagged with the old version (no 1.7 perl-bioperl package so far)

**Comment by martin-mann** [comment]
Grmpf.. guess its this [local::lib](https://github.com/bioperl/bioperl-live/blob/master/INSTALL.md) quirk that is needed to get it installed in the target directory... so another dependency..

**Comment by martin-mann** [comment]
Is there a way to incorporate this perl-local-lib package from a private channel?

[https://anaconda.org/dan_blanchard/perl-local-lib](https://anaconda.org/dan_blanchard/perl-local-lib)

Ahhh.. will pull conda `perl` as well... 😣

**Comment by epruesse** [comment]
assuming this was fixed somehow
