### ISSUE TITLE
Pinning the conda-forge way

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#2943]
@johanneskoester whould it be worth to sync our pinning with the one from conda-forge?

https://github.com/conda-forge/conda-forge.github.io/blob/af6e7b282efb2bf9b62fe10f8093d76b37c333e1/scripts/pin_the_slow_way.py#L29-L60

**Comment by johanneskoester** [comment]
Yes, sounds like a good idea. I think this should not happen automatically, because changing a version might trigger a lot of updates, but we should try to keep it in sync manually.

**Comment by bgruening** [comment]
related: https://github.com/bioconda/bioconda-recipes/compare/env_matrix_ext?expand=1

**Comment by epruesse** [comment]
outdated
