### ISSUE TITLE
Perl-osx-nov PR merge: linux package build failed

### ISSUE THREAD

**Issue by martin-raden** [bioconda/bioconda-recipes#2957]
@bgruening Somehow the `perl-osx-nov/xmlbuilder` merge builds failed even after it went through for the branch build

[https://travis-ci.org/bioconda/bioconda-recipes/builds/175984864](https://travis-ci.org/bioconda/bioconda-recipes/builds/175984864)

What to do?

**Comment by bgruening** [comment]
"fixed" it by put it on the blacklist: https://github.com/bioconda/bioconda-recipes/pull/2958

@daler any idea why all tests pass with "SUCCESSFUL" but the summary actually fails?
https://travis-ci.org/bioconda/bioconda-recipes/jobs/175984865#L495

**Comment by martin-mann** [comment]
As said, also happend for the following merge of `xmlbuilder`...

**Comment by daler** [comment]
@bgruening no idea -- I'll block out some time later today to look at this.

**Comment by daler** [comment]
Hopefully this will fix it: https://github.com/bioconda/bioconda-utils/pull/34

**Comment by martin-mann** [comment]
so after merging this, should I push a new build (number) of the failed package? (and remove it from the blacklist)

**Comment by epruesse** [comment]
outdated
