### ISSUE TITLE
jpeg 9 as gnuplot-py requirement 

### ISSUE THREAD

**Issue by dprada** [bioconda/bioconda-recipes#2964]
Hi!

I think gnuplot-py has to explicitly require jpeg 9 (with jpeg 8 doesn't work).

I was getting this:
`gnuplot: error while loading shared libraries: libjpeg.so.9: cannot open shared object file: No such file or directory`

Until I updated my jpeg to 9.

Thanks for keeping this conda repo updated!

**Comment by martin-mann** [comment]
I have pushed jpeg-9b recently. seems we have to rebuild the gnuplot-package to get that loaded appropriately. Best add "==9*" as version dependency for the jpeg in the meta.yaml file to ensure the dependency is met.

**Comment by bgruening** [comment]
I will try it here: https://github.com/bioconda/bioconda-recipes/pull/3007

**Comment by epruesse** [comment]
outdated
