### ISSUE TITLE
SortMeRNA OSX support

### ISSUE THREAD

**Issue by wasade** [bioconda/bioconda-recipes#2972]
I attempted to grab `SortMeRNA==2.0` on OSX and was surprised that the package didn't exist for the osx channel. Is there a quick fix here? I believe that `build.sh` is inline for an OSX build. If there is a quick fix, I'd be happy to issue a PR with a little guidance :)

**Comment by bgruening** [comment]
@wasade try to remove the `skip: True  # [osx]` in the recipe and build it on your box with `conda build path/to/recipe`. Hopefully this will pass and you can create a PR with this single-line change.

**Comment by wasade** [comment]
Thanks! Testing right now

**Comment by bgruening** [comment]
@wasade thanks a lot!

**Comment by wasade** [comment]
Thank you! :)
