### ISSUE TITLE
help with adding osx-64 recipe for r2r

### ISSUE THREAD

**Issue by janstrauss1** [bioconda/bioconda-recipes#29813]
Dear all,

for the [R2R package](https://sourceforge.net/projects/weinberg-r2r/) that allows to draw aesthetic RNA secondary structures there seems to be a [linux-64 bioconda recipe](https://anaconda.org/bioconda/r2r) available only.

I'd be very interested in a recipe for Mac OS but unfortunately not experienced enough to add a recipe myself, thus I'm asking the community for help.

Many thanks in advance!

**Comment by janstrauss1** [comment]
Tagging @epruesse, @dpryan79, @metageni and @phil-gusev for help as they seem to have been working with R2R before #10738, https://github.com/bioconda/bioconda-recipes/pull/15131#issue-276063763, #11065

**Comment by dpryan79** [comment]
Can you make a new PR removing the `skip` for OSX and incrementing the build number? That'd be a good place to start.

**Comment by janstrauss1** [comment]
@dpryan79, many thanks for your swift feedback!

As you suggested, I've now made a new PR, removing the `skip` for OSX and incrementing the build number.
Unfortunately, building and testing on OSX seems to be failing. Any suggestion on how to proceed?

Thanks in advance!

**Comment by janstrauss1** [comment]
R2R v1.0.6 is now available in bioconda for `linux-64` and `osx-64`.
