### ISSUE TITLE
hivtrace fails to install - conflict wit python

### ISSUE THREAD

**Issue by osallou** [bioconda/bioconda-recipes#3001]
root:/# conda config --add channels bioconda
root:/# conda config --add channels conda-forge
root:/# conda install hivtrace
Fetching package metadata: ........
Solving package specifications: ............................
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|#########################################################################################################| 100%

Hint: the following packages conflict with each other:
  - hivtrace
  - python 2.7*

Use 'conda info hivtrace' etc. to see the dependencies for each package.

**Comment by daler** [comment]
The [`hivtrace` recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/hivtrace/meta.yaml) skips the recipe for Python 2.7, which is usually an indicator that the package does not support Python 2.7.

In fact, the [hivtrace documentation](https://github.com/veg/hivtrace#system-dependencies) indicates that Python 3 is required.

**Comment by osallou** [comment]
Ok will try with python 3. But what if both python 2 and 3 are installed
but python2 is default, will conda detect/manage this?

**Comment by daler** [comment]
In this case you should create a new environment with the different python, e.g., 

```
conda create -n hivtrace-env python=3 hivtrace
```

**Comment by bgruening** [comment]
@osallou I will close this, please reopen when this does not solve it for you.
