### ISSUE TITLE
searchgui and peptide-shaker require code distribution to be copied 

### ISSUE THREAD

**Issue by jj-umn** [bioconda/bioconda-recipes#3023]
@bgruening 

    http://compomics.github.io/searchgui/wiki/searchcli.html

    Please note that search engines use indexes and temporary files stored locally in their folder. It is thus important to use a single instance of SearchCLI at a time. In distributed setups, we recommend keeping a clean copy of SearchGUI, and distribute it to the different workers prior to execution.

    https://github.com/compomics/peptide-shaker/wiki/PeptideShakerCLI

    Note that PeptideShaker back-end relies on a database allowing only a single open connection at a time. It is thus important to use a single instance of PeptideShakerCLI at a time. In distributed setups, we recommend keeping a clean copy of PeptideShaker, and distribute it to the different workers prior to execution.

Is it appropriate to copy the jar code in the python wrappers: searchgui and peptide-shaker:
diff --git a/recipes/searchgui/3.1.4/searchgui.py b/recipes/searchgui/3.1.4/searchgui.py
index e5dff1e..22d8c89 100755
--- a/recipes/searchgui/3.1.4/searchgui.py
+++ b/recipes/searchgui/3.1.4/searchgui.py
@@ -9,6 +9,7 @@
 import os
 import subprocess
 import sys
+import shutil
 from os import access
 from os import getenv
 from os import X_OK
@@ -70,7 +71,14 @@ def jvm_opts(argv):
 
 def main():
     java = java_executable()
-    jar_dir = real_dirname(sys.argv[0])
+    """
+    SearchGui updates files relative to the path of the jar file.
+    Thus we need to copy the jar file, lib, and resources to the working directory
+    when this script is first invoked in a job.
+    """
+    jar_dir = os.path.join(os.getcwd(),'bin')
+    if not os.path.exists(jar_dir):
+        shutil.copytree(real_dirname(sys.argv[0]), jar_dir, symlinks=False, ignore=None)
     (mem_opts, prop_opts, pass_args) = jvm_opts(sys.argv[1:])
 
     if pass_args != [] and pass_args[0].startswith('eu'):

**Comment by jj-umn** [comment]
Pull Request:  SearchGui copy the jar file, lib, and resources to cwd #3133

**Comment by bgruening** [comment]
Oh I missed this completely. I don't like this at all. But I think your PR is then a valid solution. Maybe you can set an ENV variable, which when it is set the stuff is copied?

I'm a little bit hesitant to do the copying by default as this is a complete different behavior from other conda packages.
