### ISSUE TITLE
Python version range in recipe not respected in package

### ISSUE THREAD

**Issue by jlumpe** [bioconda/bioconda-recipes#30370]
The [recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/hesslab-gambit/meta.yaml) for my package includes `python >=3.7` in both the `host` and `run` subsections of `requirements`, but the [built package](https://bioconda.github.io/recipes/hesslab-gambit/README.html#package-hesslab-gambit) says Python 3.9 is required. Is my recipe incorrect somehow?

**Comment by jlumpe** [comment]
Awesome, thanks @marcelm. `conda search` now shows me builds for 3.7-3.9. Should this maybe be added to the contributor documentation?

**Comment by marcelm** [comment]
Yes, absolutely. I’ll make a PR when I find some time for this (unless anyone else wants to have a go). Perhaps this should even be a lint check.
