### ISSUE TITLE
kat installation

### ISSUE THREAD

**Issue by KamilSJaron** [bioconda/bioconda-recipes#30672]
Hello, I am running in a trouble with conda installation of kat. When install it in a blank env

```
conda install kat -c bioconda
```

and then try to run it, I get

```
kat: error while loading shared libraries: libboost_filesystem.so.1.60.0: cannot open shared object file: No such file or directory
```

I was able to reproduce the error on two different clusters (but I am nearly sure I have installed kat via conda in past, not sure what changed).

**Comment by acaprez** [comment]
Hello,

I suspect you have something in your existing environment pinning boost to 1.60 and potentially limiting the version of kat.  Could you please try creating a fresh environment instead, i.e. `conda create -n mykatenv kat`?  Also double check that conda-forge is in your list of channels.

**Comment by KamilSJaron** [comment]
Hi, you are right - it actually worked on both clusters. I thought I tested it in a blank env, but I must have messed it up and installed there something before. Sorry about that.
