### ISSUE TITLE
Discrepancy between bioconda github and the bioconda channel

### ISSUE THREAD

**Issue by mworkentine** [bioconda/bioconda-recipes#3081]
The bioconda master branch lists bioconductor-shortread as version 1.30.0 (see [here](https://bioconda.github.io/recipes/bioconductor-shortread/README.html?highlight=shortread)), however, the bioconda channel on anaconda cloud lists version 1.28.0 (see [here](https://anaconda.org/bioconda/bioconductor-shortread)).

And from conda:
```
❯ conda search -c bioconda bioconductor-shortread
Fetching package metadata .............
bioconductor-shortread    .  1.28.0                 r3.2.2_0  bioconda
```

1.28.0 depends on R 3.2.2 and so 3.2.2 is the most recent version of R that can be installed in any environment where shortread is installed.

**Comment by bgruening** [comment]
This is now fixed and 1.32.0 is available.
