### ISSUE TITLE
Can't download STAR-Fusion

### ISSUE THREAD

**Issue by matq007** [bioconda/bioconda-recipes#30923]
Hi, for some reason I am not able to download the latest STAR-Fusion v1.10.0 when I make a clean conda environment. I've tried also using docker and even creating a [multi-package container](https://github.com/BioContainers/multi-package-containers/pull/1887).

Here is an output when I try do it on clean conda environment. Any suggestion what might went wrong?
Thank you.

```
conda install star-fusion=1.10.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**Comment by mfansler** [comment]
Sorry, I should have been more specific. We need to see the channel priorities. So, output:

```bash
conda config --show channels channel_priority
## should output
channels:
  - conda-forge
  - bioconda
  - defaults
channel_priority: strict  # I think 'flexible' would also work
```

This is [the expected channel configuration](https://bioconda.github.io/user/install.html#set-up-channels) for Bioconda.

**Comment by matq007** [comment]
I see, I have slightly different order

```bash
channels:
  - bioconda
  - conda-forge
  - defaults
channel_priority: flexible
```

I will try to reorder and see if that solves the issue. Thank you for the tip :)
