### ISSUE TITLE
Join Bioconda team

### ISSUE THREAD

**Issue by gbayarri** [bioconda/bioconda-recipes#31037]
Hi, following the [Join the team](https://bioconda.github.io/user/install.html#join-the-team) documentation we pinged @bioconda/core in order to add a new user @svletana to the Bioconda team:

https://github.com/bioconda/bioconda-recipes/pull/26943

I forgot the '@' before the name of the user, so probably this was the problem. What should we do now for adding her to the team? He's already able to make PR's, but she hasn't all the permissions (e.g. approve PRs).

Thanks.

**Comment by dpryan79** [comment]
@gbayarri I've sent her an invite now!
