### ISSUE TITLE
Use Jekyll for pages

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#311]
With Jekyll, we would be able to display summaries for each recipe on the github.io homepage (see [here](http://jekyllrb.com/docs/datafiles/). I tried to set it up, but didn't immediately manage to properly install all dependencies on my Fedora Linux. Is anybody of you familiar with Jekyll?

**Comment by kyleabeauchamp** [comment]
I've used pelican but not jekyll.

**Comment by ostrokach** [comment]
How about using Sphinx and readthedocs?

We could init Sphinx inside a *./docs* folder, and have an *index.rst* file with something like:

```
.. toctree::
   :maxdepth: 2
   :glob:

   ../recipes/*/*
```

I haven't tested this, but I think it should work.

Then each recipe could have a *README.rst* file, with the title being the repository name?

**Comment by ostrokach** [comment]
I created a simple script that goes through the recipes and generates README files.

Sphinx [can't read source files above the root folder](http://stackoverflow.com/questions/10199233/can-sphinx-link-to-documents-that-are-not-located-in-directories-below-the-root), so the READMEs are saved in the *./docs/recipes* folder.

Here is a demo readthedocs page: http://bioconda-recipes-demo.readthedocs.org/en/docs/

**Comment by johanneskoester** [comment]
I like this approach. We could switch to sphinx for the entire page and host it on github.io. This would create a nice integrated experience.

**Comment by johanneskoester** [comment]
Seems to be quite easy to do that. We need to disable jekyll as described [here](https://github.com/michaeljones/sphinx-to-github#attention). [Here](https://github.com/Syntaf/travis-sphinx) is a python package that handles automatic deployment via travis.

**Comment by ostrokach** [comment]
So I'll just merge the pull request? It won't overwrite anything without the GITHUB_TOKEN, and you have a better idea of what to do for the front page...

**Comment by johanneskoester** [comment]
ok

**Comment by johanneskoester** [comment]
@bioconda/all we finally have an integrated sphinx based homepage now, which also shows all the recipes. Thanks to @ostrokach for implementing this!

**Comment by daler** [comment]
Very nice, this looks great!

**Comment by strokach** [comment]
- I added a `.nojekyll` file because the static content was not being served.
- I created a new repository with the copy of the files and `--force` pushed it to bioconda.github.io, because the home page was not working.
