### ISSUE TITLE
No travis log output when build times out

### ISSUE THREAD

**Issue by marcelm** [bioconda/bioconda-recipes#3130]
I am not sure whether this is correct, but I believe that the Travis log output is incomplete when a build times out.

I am trying to find out why #3085 times out all the time. [The log output](https://travis-ci.org/bioconda/bioconda-recipes/jobs/181182806) of one of these attempts is not helpful because it stops right before the recipe build starts. It seems that the error log is only printed when the build script recognizes that something has failed. When the script itself gets stopped because of a timeout, it does not print anything.

If my assumption is correct, I suggest that the behavior be changed. The log should really be updated live if possible.

**Comment by gregvonkuster** [comment]
+1 I've been hitting this issue repeatedly with various recipes lately.

**Comment by bgruening** [comment]
My best bet is that you are missing some runtime dependency in your recipe. Can you try to add gcc as runtime dep?

**Comment by marcelm** [comment]
I’ve fixed the runtime deps already. This report is about the missing debug output, which made it very hard to find the problem.

**Comment by daler** [comment]
@marcelm @bgruening it would be great to get logs to show up in real time but I think the way travis is set up might require some large changes in our infrastructure.

**Comment by marcelm** [comment]
Hm, ok, wasn’t aware that this is a Travis thing. Too bad!

**Comment by marcelm** [comment]
The actual problem is in `travis_wait`, which does the stdout buffering: travis-ci/travis-ci#5716

**Comment by marcelm** [comment]
How much time do the jobs on Travis actually get? Is it two hours? Then giving `travis_wait` a timeout of 120 minutes is too much because the job has already been running for at least one or two minutes when it starts. So the entire job is killed "from the outside" and `travis_wait` never has a chance of reaching the timeout. As far as I can tell from its source code, it *would* print the output when a timeout is reached.

The obvious solution is to reduce the timeout by a few minutes. This won’t give us a 'live' update, but we would at least see the log output when a job that ran too long was killed.

**Comment by marcelm** [comment]
Note also [the last lines of the log output](https://travis-ci.org/bioconda/bioconda-recipes/jobs/181182806#L477). It prints "Still running (119 of 120): scripts/travis-run.sh". It never reaches 120 minutes. Also, the very last line (`The job exceeded the maximum time limit` ...) is not the message that `travis_wait` would print.

**Comment by daler** [comment]
@marcelm nice catch. travis-ci has kindly increased our build times to 2 hrs. Would you mind playing around with https://github.com/bioconda/bioconda-recipes/blob/master/.travis.yml#L9 to see if it helps?

**Comment by marcelm** [comment]
Here is the [log of a job run with `travis_timeout 115`](https://travis-ci.org/bioconda/bioconda-recipes/jobs/182306281).

How about removing `travis_wait` entirely? [It should be used](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) when a script does not produce any output for more than 10 minutes. Does that apply to any of the recipes? Most of the time a job runs for a long time, I would assume that it is because things are being compiled or tested - and in that case, there will always be output.

[Here is a log of a job run without `travis_wait`](https://travis-ci.org/bioconda/bioconda-recipes/jobs/182307088).

Actually, I would go so far as to say that if a recipe build does not produce any output for 10 minutes, then it really is an indication of a problem. In the case of the stalled `mulled-build` process that I ran into, this was definitely true and would have saved me over 1,5 hours of waiting.

**Comment by daler** [comment]
Thanks for figuring this out. I think we do still need `travis_wait`. With `loglevel=info`, output will only be created for built/test start/stop. Pretty sure we have some packages that take a long time to compile and therefore will have more than 10 mins between the build start and build end messages. Blast? sra-toolkit maybe?

Ideally we should set the timeout to some high percentile of build times, but I have no idea what that would be. I would bet though that >10 mins for a single job is rare. So maybe we use `travis_wait`, set the timeout to 10 mins, and if we have known cases where the build will likely take longer, we can temporarily set it higher for those particular PRs. In any case, we definitely need to have it <120 as you've shown.

@bgruening can you expose more granular control of involucro stdout/stderr? Also related to #3157.

**Comment by bgruening** [comment]
I fixed the stdout stuff upstream and waiting for a new release. 
@marcelm thanks for looking into the timeout issue. However, I think this removing the travis_wait does not work. I have tested it here with a really long running recipe: https://travis-ci.org/bioconda/bioconda-recipes/jobs/182767004#L474

It seems we need to have this travis_wait, it the time is over travis will kill the job. 
But 120m is certainly too long, we should decrease it to `110` maybe? Do you want to create a PR for this?

**Comment by marcelm** [comment]
@daler In my opinion this is a reason for using `loglevel=debug` by default. But I guess that is different discussion.

@bgruening I have tried to decrease the timeout, but I get this problem: https://travis-ci.org/bioconda/bioconda-recipes/jobs/183036684 I won’t have more time over the next days, so I’d be more than happy if you could take care of this.

**Comment by daler** [comment]
@marcelm @bgruening this last error was from my recent changes in bioconda-utils, should be fixed in #3168.

@marcelm I was using debug logs for being very verbose locally. Have to be careful with what gets printed though, otherwise we go over the 4MB log size limit. Moving forward I think we can just revisit what gets `lNFO` and what gets `DEBUG` logged based on the new mulled-build stdout.

**Comment by daler** [comment]
@marcelm seems to be fixed now: https://travis-ci.org/bioconda/bioconda-recipes/builds/183045484

**Comment by marcelm** [comment]
I’ve opened PR #3170.

**Comment by sebastian-luna-valero** [comment]
Hello All,

After having merged with master, I am having the same problem:
https://travis-ci.org/CGATOxford/bioconda-recipes/jobs/185484256
https://travis-ci.org/CGATOxford/bioconda-recipes/jobs/185484257

However, it works locally with:
```
./simulate-travis.py --docker --packages cgat-scripts-nosetests --loglevel=debug
```

Is there anything I can look at?

Best regards,
Sebastian

**Comment by bgruening** [comment]
@sebastian-luna-valero we have some extra build time in bioconda, so we are allowed to build for 2h not only for 45 min. You are encountering a build-timeout. How long does it build locally for you?

**Comment by bgruening** [comment]
@sebastian-luna-valero we have some extra build time in bioconda, so we are allowed to build for 2h not only for 45 min. You are encountering a build-timeout. How long does it build locally for you?

**Comment by sebastian-luna-valero** [comment]
thanks @bgruening 

locally it takes about 52 minutes.

should I then create a branch directly on the bioconda repo?

**Comment by bgruening** [comment]
@sebastian-luna-valero yes, please do this.
I will close this issue now. We enhanced this a little bit.
