### ISSUE TITLE
perl-bioperl 1.6.924-6 is broken

### ISSUE THREAD

**Issue by dakl** [bioconda/bioconda-recipes#3131]
Hi, 

I'm getting problems when installing perl-bioperl-1.6.924 (build number 6) using `conda install perl-bioperl`. Certain subpackages such as `Bio::PrimarySeqI` are missing. A quick look at anaconda could reveals that build 4 is 2.2 Mb but build 6 is only 5.7 kb. Manually downloading build 4 and installing is works fine. 

Is therefore seems to me that something is broken in the latest build of this version of bioperl. 

cheers

**Comment by bgruening** [comment]
Hi @dakl,

I guess this was due to some work regarding a new bioperl release: https://github.com/bioconda/bioconda-recipes/pull/2909 and many more PR.

Any help here is appreciated!
Thanks,
Bjoern

**Comment by matthdsm** [comment]
seconded, I'm having the same issue. Any news on a fix? Is it possible to revert (remove?) a build, so that version installed by default is at least functional?

Thanks
M

**Comment by epruesse** [comment]
outdated
