### ISSUE TITLE
test-macos jobs blocked by CircleCI

### ISSUE THREAD

**Issue by mcmero** [bioconda/bioconda-recipes#31320]
CircleCI seems to be blocking Mac OS testing jobs ([example](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/55140/workflows/fb69be06-9e0a-457a-a2ea-2bc4d730b50c/jobs/174017)):

`This job has been blocked because resource-class:medium is not available on your plan. Please upgrade to continue building.`

Test-linux appears to be working fine. This seems to be affecting several recent builds. Is there a fix for this, or is it perhaps an issue on CircleCI's end?

**Comment by johanneskoester** [comment]
Apparently there has been a sudden change in our free plan at CircleCI. We are currently investigating the issue and have contacted them. If we don't find a solution until tomorrow evening, we will move our CI jobs to Azure immediately.

**Comment by mbargull** [comment]
We do have macOS builds working again :tada:.
(We have to restart the failed macOS jobs manually, though.)
Let's monitor the situation over the next few days a bit and leave this issue open at least until tomorrow or so.

**Comment by mcmero** [comment]
Thanks. What is the best way to rebuild a PR affected by this? I've tried `@BiocondaBot rebuild` on [this PR](https://github.com/bioconda/bioconda-recipes/pull/31306) but that doesn't seem to work.
