### ISSUE TITLE
UnavailableInvalidChannel

### ISSUE THREAD

**Issue by ning-y** [bioconda/bioconda-recipes#31460]
I think the bioconda channel may be offline?

```
(base) ningyuan_sg@machine-image-model-2:~$ conda install -c conda-forge -c bioconda snakemake
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: bioconda
  channel url: https://conda.anaconda.org/bioconda
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

The above is from a Google Cloud Compute instance. I get the same error from my home PC (separate network), and laptop (with mobile hotspot so it's a separate network connection from the home PC). I've installed stuff from bioconda successfully on my home devices.

Using mamba also throws a 404 for bioconda.

I know this is more of a server/deployment issue, not directly related to this repository, but I am not sure where else to report this.

**Comment by bgruening** [comment]
Yes, we are in contact with anaconda to solve this problem. Thanks for reporting.

**Comment by Char-Al** [comment]
It seems to be fixed now.
