### ISSUE TITLE
writing a wrapper around a tool.

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#3147]
Hi,
I created a recipe for [PEP_Scaffolder](https://github.com/bioconda/bioconda-recipes/pull/3146), but I have a problem to write a [wrapper](https://github.com/bioconda/bioconda-recipes/pull/3146/commits/d13828e29338e6c67a25d25b8cc717887ac24c5b#diff-4de78094bbeaaa659c95a43f65f662fb) for it because the main script (`PEP_scaffolder.sh`) require knowing where its dependencies are stored.

How is it possible fix it?

Thank you in advance.

Mic

**Comment by epruesse** [comment]
outdated
