### ISSUE TITLE
Stale biocontainers requests is left on quay.io

### ISSUE THREAD

**Issue by pvanheus** [bioconda/bioconda-recipes#31535]
While the Python module requests no longer has a bioconda package, there is an older Docker container left on [quay.io](https://quay.io/repository/biocontainers/requests?tag=latest&tab=tags). This has the broken `/etc/resolv.conf` that causes problems with Singularity builds. In some circumstances, Galaxy can pick up this container with resulting problems.

Please remove this stale container. Thanks.

**Comment by bgruening** [comment]
Should we not generate a new container instead with a higher build number?

**Comment by pvanheus** [comment]
@bgruening - perhaps. I don't know enough about how the build system for Galaxy works - how does it handle packages that are in conda-forge but not in bioconda?

**Comment by bgruening** [comment]
Add it here https://github.com/BioContainers/multi-package-containers :-)

**Comment by bgruening** [comment]
@pvanheus can you try the new one: https://quay.io/repository/biocontainers/requests?tag=latest&tab=tags
