### ISSUE TITLE
Test env is broken if recipe dir name is > 9 characters and package depends on R

### ISSUE THREAD

**Issue by tetianakh** [bioconda/bioconda-recipes#3158]
For recipes which depend on R, if the name of recipe directory is longer than 9 characters,  test environment is not created correctly and build tests fail. 

For example, take a `jamm` recipe. Make sure it builds, and tests pass: `conda build recipes/jamm`. 
Then, rename the directory to anything 10 characters or longer, and build again:

```
$ cp -r recipes/jamm recipes/jammjammjamm
$ conda build recipes/jammjammjamm
....
/path/to/conda-bld/jammjammjamm_1481213464226/test_tmp/run_test.sh: line 3: JAMM.sh: command not found
TESTS FAILED: jamm-1.0.7.4-r3.3.1_0
```

The output is different depending on the package, but the general idea is the same -- it can't find the installed package files in the newly created test environment.

The problem dissappears if you pass the path to `meta.yaml` to `conda build` command:

```
$ conda build recipes/jammjammjamm/meta.yaml
....
+ /bin/bash -x -e /path/to/conda-bld/meta.yaml_1481214506720/test_tmp/run_test.sh
...
+ TEST END: jamm-1.0.7.4-r3.3.1_0
```

This behaviour is quite confusing. Is this a known "feature"? Is this a bug? Can anyone reproduce this? Should I create an issue for this in the `conda` repo instead?

Conda and OS versions:

```
conda-build 2.0.11
conda 4.2.13
Ubuntu 16.04.1 LTS
4.4.0-53-generic
```

**Comment by rvalieris** [comment]
seems like a known bug, I get these warnings trying to build jammjammjamm:
```
WARNING conda_build.build:create_env(687): Build prefix failed with prefix length 255
WARNING conda_build.build:create_env(688): Error was: 
WARNING conda_build.build:create_env(689): Placeholder of length '80' too short in package r::r-base-3.3.1-3.
The package must be rebuilt with conda-build > 2.0.
WARNING conda_build.build:create_env(690): One or more of your package dependencies needs to be rebuilt with a longer prefix length.
WARNING conda_build.build:create_env(692): Falling back to legacy prefix length of 80 characters.
WARNING conda_build.build:create_env(693): Your package will not install into prefixes > 80 characters.
```

This bug which seems to be describing the same problem: https://github.com/conda/conda-build/issues/1337

**Comment by rvalieris** [comment]
the solution for cases like this is to rebuild the packages described in the warning, in this case r-base (which was already rebuilt since).
