### ISSUE TITLE
Require license in meta.yaml

### ISSUE THREAD

**Issue by kyleabeauchamp** [bioconda/bioconda-recipes#316]
I propose that you explicitly require every recipe to have a license line in the about section of the yaml.  Only a few are missing right now:

```
****** NO LICENSE FOUND FOR ./recipes/grabix/meta.yaml
****** NO LICENSE FOUND FOR ./recipes/knot/meta.yaml
****** NO LICENSE FOUND FOR ./recipes/libgd/meta.yaml
****** NO LICENSE FOUND FOR ./recipes/metaseq-all/meta.yaml
****** NO LICENSE FOUND FOR ./recipes/pbgzip/meta.yaml
****** NO LICENSE FOUND FOR ./recipes/pythonpy/meta.yaml
```

I also propose:
1.  Explicitly check for the license in travis
2.  Before upload, decide whether the license is OSS or restrictive by a small whitelist
3.  Push the uploaded package to either the `bioconda` channel or the `bioconda-restricted` channel.

This would allow you to maintain one repository for both OSS and non-OSS recipes, but firewall downloads of binaries for academic only software.  @johanneskoester  let me know how that sounds as a solution.

**Comment by kyleabeauchamp** [comment]
Regarding (2, 3) there may be other ways to engineer this sort of thing, but that sounded like the simplest to me.

**Comment by kyleabeauchamp** [comment]
Metaseq is an interesting case for the license because it is a metapackage with potentially academic dependencies.  Presumably the dependencies will be able to handle their own licenses, but we'd still want to have some sort of license (presumably OSS) on the metapackage.

**Comment by kyleabeauchamp** [comment]
Grabix seems to have some ambiguity according to the debian packagers: https://github.com/arq5x/grabix/issues/5

@chapmanb has contributed to that repo previously, so perhaps he can help resolve the questions.

**Comment by kyleabeauchamp** [comment]
See #317 and #318 which fix most of the outstanding recipes, with the exception of grabix

**Comment by kyleabeauchamp** [comment]
Grabix is MIT, and I have adjusted my pull request #319  accordingly.

**Comment by johanneskoester** [comment]
Thanks Kyle! Having two channels is problematic though, because we now have funding for the bioconda channel from CA. Licenses seem to be controlled vocabulary in conda. Maybe we can provide a pull request that adds a configuration option to conda to only allow OSS licenses on request?

**Comment by kyleabeauchamp** [comment]
Ok.  My second idea is to add a dummy dependency to all academic licensed
packages and put that package in the alternate repository.

**Comment by kyleabeauchamp** [comment]
One other idea I had is to use something with the "features" flags to tag the academic licenses.  However, I still don't have an idea of how to implement a "firewall" with that method.  (http://conda.pydata.org/docs/building/meta-yaml.html#id1)

**Comment by johanneskoester** [comment]
That sounds promosing. Maybe the guys at CA have some thoughts. Do you want to file an issue, or should we contact the anaconda support about it?

**Comment by kyleabeauchamp** [comment]
I can open an issue this evening.

**Comment by bgruening** [comment]
@kyleabeauchamp do you think this can be closed?
