### ISSUE TITLE
Would it be possible to edit a published version number?

### ISSUE THREAD

**Issue by milkschen** [bioconda/bioconda-recipes#31638]
Hi folks,

I'm an author of the [leviosam](https://github.com//bioconda/bioconda-recipes/tree/master/recipes/leviosam) package. We accidentally published a package with a wrong version number (the latest version is 0.5.1, but in the bioconda page the top version is 3.1.1, which was erroneously labelled 7 months ago). We wonder if it'd be possible to change a published package. Thank you very much for the efforts to maintain bioconda!

**Comment by bgruening** [comment]
We could, but this would break reproducibility and would affect all your users. So we usually do not do that :(

**Comment by milkschen** [comment]
Thank you for the quick response. The v3.1.1 is a very old and erroneously-named version (we don't actually have that version released on github) and we've made major changes to our software since that. We're fine to change it if that's possible.

**Comment by bgruening** [comment]
Can you bump your github release just to be bigger as the release on conda?

**Comment by milkschen** [comment]
Ok. We'll opt for this path. Thank you for your help and suggestion :)
