### ISSUE TITLE
perl-threaded can be deprecated

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#3167]
@tomkinsc was able to get our custom perl modifications into conda-forge with https://github.com/conda-forge/perl-feedstock/pull/6

This means we can just use `perl` instead of `perl-threaded`. I see two possibilities from here on:

* bulk rebuild all perl-packages against `perl`
* change our `perl-threaded` package to depend on `perl`, some kind of meta-package and change our recommendation to use `perl` from now on.

The first one will take a while and a lot of effort, like the R migrations. The second is not tested, just a guess that this might work.

Any other ideas?

Thanks a lot to @tomkinsc who spend a lot of time in getting this package into conda-forge!

ping @bioconda/core

**Comment by johanneskoester** [comment]
Thanks @tomkinsc! I'd prefer the bulk rebuild. We can do this gradually, one connected component of our internal perl dep-graph at a time. Maybe we can even combine this with moving perl packages over to conda-forge if they are not bioinformatics specific.

**Comment by rvalieris** [comment]
there is also a perl packge, in addition to perl-threaded, on the bioconda channel, wouldn't that mean the bioconda version will have the highest priority and be installed instead of the conda-forge version ?

**Comment by bgruening** [comment]
@rvalieris yes this is correct.
@johanneskoester do you see any disadvantages in the second option? I spend so many hours already in perl land and this is a mess and rebuilding takes probably ages. Please note that we haven't even finished the R rebuild by now :(

**Comment by rvalieris** [comment]
so as I understand, for this to work without the need of rebuilding packages:
* conda-forge::perl needs to match the current bioconda::perl-threaded version (because perl modules are installed in versioned paths)
* prevent users from getting bioconda::perl by accident after the transition ( because bioconda::perl is not compiled with threads (and "thread-multi" is also included on the module path))

but wouldn't all modules need to be rebuild anyway when perl itself is updated ?

**Comment by bgruening** [comment]
Sounds correct to me. A rebuild is imho only necessary if you increase the perl version and make it ABI/API incompatible.

**Comment by johanneskoester** [comment]
I don't have a strong opinion on this. Feel free to choose option 2 if that is easier.

**Comment by jerowe** [comment]
So just to be clear, what perl from what channel should we be building with? I know the channels get pulled in automatically, but I still want to know. It looks like the perl in conda-forge is now the functional equivalent of the perl-threaded. Is this correct?

**Comment by bgruening** [comment]
@jerowe yes the conda-forge one should be a drop in replacement for perl-threaded.
@johanneskoester can we remove our old `perl` package from the channel? Otherwise, I'm not sure how we can say we want to have the `perl` one form conda-forge.

**Comment by bgruening** [comment]
@johanneskoester can we remove the `perl` packages from bioconda? They should not be much in use, but preventing the meta-package idea to work.

**Comment by johanneskoester** [comment]
If the same version exists on conda-forge, I have no objections. Versions that are not on conda-forge I'd like to keep, in order to not break environment definitions from users.

**Comment by bgruening** [comment]
@johanneskoester 
```
perl                         5.18.1                        0  bioconda        
                             5.18.2                        0  bioconda        
                             5.18.2                        1  bioconda        
                          .  5.18.2                        8  bioconda        
                             5.20.3.1                      1  conda-forge     
                             5.20.3.1                      2  conda-forge     
                             5.22.0                        8  bioconda        
                          .  5.22.0                        9  bioconda        
                             5.22.2.1                      0  conda-forge 
```
According to our guideline we should not use `perl`. How is the channel priority working in the latest conda versions, do we get always the latest version, no matter which channel it is, or do we get only one version from the top-priority channel?

**Comment by johanneskoester** [comment]
Priority beats version. That is, if there is something in a higher priority channel, it will be preferred, regardless of whether it has a higher or lower version. However, perl is pinned, right? Hence, if we remove the version we pin against from bioconda, it will take the version from conda-forge.

**Comment by bgruening** [comment]
We do not have the same exact version in conda-forge and bioconda as indicated above. But I had hoped that `perl` is not used much in bioconda these days, I can be wrong.
Just wanted to be sure, before I screw everything up and remove the `perl` packages and merge this metapackage PR :)

**Comment by jerowe** [comment]
@bgruening , long live perl!

**Comment by johanneskoester** [comment]
That's fine. What I mean is that 

1. We need to ensure that our CONDA_PERL variable points to the version that is in conda-forge. If we don't want to rebuild all our perl packages, we should probably ensure that 5.22.0 is in conda-forge.
2. We need to delete that specific version from bioconda.
3. The rest of the versions in bioconda can stay, in order to not break existing environments.

**Comment by bgruening** [comment]
Our channel order makes it really difficult to deprecate packages. So essentially I need to get an older version into conda-forge ... this will take some time or will not be possible at all.

**Comment by rvalieris** [comment]
I admit I didn't knew about this CONDA_PERL variable and I'm not sure how it affect the packages, but I want to point out that [perl guarantees minor version updates won't break ABI](http://modernperlbooks.com/mt/2010/02/perl-5-version-numbers-and-binary-compatibility.html), this means packages built with 5.22.0 should work with any perl >=5.22.0, <5.23.0.

There are a few packages still depending on bioconda::perl but none of then are specifies a ==[version], not current ones anyway, a few pinned recipes do. like viennarna and barrnap.
