### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#3175]
Hi,
Unfortunately, I am getting permission denied with this [PR](https://github.com/bioconda/bioconda-recipes/pull/3174):

```
+ DBG2OLC -h
/QRISdata/Q0231/apps/conda-bld/dbg2olc_1481502872617/test_tmp/run_test.sh: line 3: /QRISdata/Q0231/apps/conda-bld/dbg2olc_1481502872617/_t_env/bin/DBG2OLC: Permission denied
TESTS FAILED: dbg2olc-20160205-0
```

What did I miss?

Thank you in advance,

Mic

**Comment by yhoogstrate** [comment]
I ran into the same problem. If you have used `cp` in your build.sh, try to replace it with `mv`.

**Comment by bgruening** [comment]
@yhoogstrate and mv is working? This is wired! :)

**Comment by yhoogstrate** [comment]
Yep, I get the impression the `Fixing permissions` step is resetting chmods to readonly when files get a new/different inode? I ran into this in a package that did not do compilation,  just copies the compiled binary from an archive.

**Comment by bgruening** [comment]
@mictadlo let me know if you have problems.
