### ISSUE TITLE
Recipes failed on Travis CI

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#3176]
Hi,
I could build locally the following recipes, but on Travis CI they failing:

* [SparseAssember](https://github.com/bioconda/bioconda-recipes/pull/3171)
* [Sparc](https://github.com/bioconda/bioconda-recipes/pull/3172)

What did I miss?

Thank you in advance.

Mic

**Comment by tetianakh** [comment]
Can you please send a URL to the build logs? I'm also having issues with CI builds and I wonder if they're similar to yours.

**Comment by mictadlo** [comment]
Below the CI logs:
* [Sparc](https://travis-ci.org/bioconda/bioconda-recipes/jobs/183116159)
* [SparseAssembler](https://travis-ci.org/bioconda/bioconda-recipes/jobs/183103614)

**Comment by sebastian-luna-valero** [comment]
Not sure whether it will help but there seems to be a problem downloading a tarball in both cases:

https://travis-ci.org/bioconda/bioconda-recipes/jobs/183116159#L566

https://travis-ci.org/bioconda/bioconda-recipes/jobs/183103614#L616

**Comment by bgruening** [comment]
@mictadlo I will close this, let us know if you need more help. Please ping "@ bioconda/core" next time directly at the PR.
