### ISSUE TITLE
while the entire build failed, the following recipes were built successfully

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#3209]
Hi, I thought I used `git checkout -b package-name`, but something went wrong and multiple recipes end up in one PR. How is it possible to merge the successfully build recipes below to bioconda?

* [PR](https://github.com/bioconda/bioconda-recipes/pull/3171) and [Travis CI](https://travis-ci.org/bioconda/bioconda-recipes/jobs/184058608) output:
```
ERROR bioconda_utils.build:build_recipes(361): BIOCONDA BUILD SUMMARY: while the entire build failed, the following recipes were built successfully:
recipes/sparseassembler
```

* [PR](https://github.com/bioconda/bioconda-recipes/pull/3172) and [Travis CI](https://travis-ci.org/bioconda/bioconda-recipes/jobs/184058252) output:
```
ERROR bioconda_utils.build:build_recipes(361): BIOCONDA BUILD SUMMARY: while the entire build failed, the following recipes were built successfully:
recipes/sparc
recipes/cromwell
recipes/sparseassembler
```

Thank you in advance.

Mic

**Comment by bgruening** [comment]
@mictadlo can you just close both PRs and create new ones - one PR one recipe? This would be the easiest way.

**Comment by bgruening** [comment]
@mictadlo let us know if you need more help.
