### ISSUE TITLE
skip: True  # [osx] seems not work

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#3211]
Hi,
Travis CI is still waiting for Mac OSX despite I used in this [PR](https://github.com/bioconda/bioconda-recipes/pull/3210)

```
build:
  skip: True  # [osx]
```

What did I do wrong?

Thank you in advance.

Mic

**Comment by daler** [comment]
Every PR is run on Linux and OSX, if only just to check if there are recipes that need to be built. After this check, if recipes are skipped then they are not built. There is not a good way of turning off OSX completely on a PR-by-PR basis.

If, however, a recipe skips OSX but the build system tries to build it anyway (and then fails), please reopen.
