### ISSUE TITLE
Using more recent compilers

### ISSUE THREAD

**Issue by holtgrewe** [bioconda/bioconda-recipes#3224]
I have not found a solution to this but it might have occured earlier.

I want to compile Flexbar which needs seqan-library which needs a relatively recent compiler, e.g., GCC >= 4.9.1 or some Clang compiler.

How can I solve this issue?

**Comment by bgruening** [comment]
@holtgrewe sequan-library is already available so you could simply depend on this, no need to compile it on your own - or do you a newer GCC also for flexbar?

**Comment by holtgrewe** [comment]
@bgruening seqan-library 2.2 (which flexbar requires) is header-only and uses features only available in C++14. Thus, for compiling flexbar I need a modern compiler. Fun times!

I guess I would have to add a build requirement on GCC 4.9.1 then and this would have to go into the global anaconda channel or conda-forge?

**Comment by bgruening** [comment]
This is a huge can of works. But yes you would need to get a newer GCC version in, have a look at this: https://github.com/conda/conda-recipes/pull/502 and similar PRs

**Comment by holtgrewe** [comment]
@bgruening I think I don't need the bleeding edge version there but rather just copy one of the other recipes (and dependencies).

`anaconda search -t gcc-5` shows packages with name prefixes (e.g., `salford_systems/gcc-5`). Would I add gcc-5 and dependencies from this user's packages to bioconda-recipes then?

**Comment by bgruening** [comment]
I don't think that bioconda wants to maintain GCC. It should be added to conda-forge or actually to anaconda probably as the PR I linked above.

We are discussion the compiler situation since one year, not sure if anything happend on this front recently.

**Comment by holtgrewe** [comment]
OK, what I don't understand is why there is a gcc-5 in conda-recipes but I don't see it in conda install. Do you know?

**Comment by bgruening** [comment]
No. conda-recipes are not as transparent as they should be. This is one reason conda-forge will take the entire low-level stack and maintain this in a transparent, community driven way.

**Comment by holtgrewe** [comment]
OK, so you would welcome a PR with `gcc-5` with a copy from whatever is in conda-recipes into conda-forge? Or is there more stuff blocking this?

**Comment by bgruening** [comment]
Imho, but I can be totally wrong, think you have a higher chance to get this in in conda-forge.

**Comment by daler** [comment]
@holtgrewe just to clarify: step 1 is to get `gcc-5` into conda-forge. That channel is managed independently from bioconda so we don't really have a say in that. Not sure whether they would want it in conda-forge or in defaults.  But we do depend on both those channels' packages so either one is fine. Step 2 would be the Flexbar PR for bioconda, which would depend on the new `gcc-5` from conda-forge.

**Comment by bgruening** [comment]
Related: https://github.com/conda-forge/staged-recipes/issues/872

**Comment by jerowe** [comment]
Any word on this?

**Comment by bgruening** [comment]
Yes, new compiler should come soon from the conda-forge and continuum people!

**Comment by jerowe** [comment]
YAY!!!!!!!!!!!!!

**Comment by notestaff** [comment]
Any updates on the newer compiler?  I need a C++14 compiler to compile kmc_tools in the kmc package.  Thanks a lot!

**Comment by notestaff** [comment]
@bgruening any news on when it might be possible to use a C++11 compiler with bioconda?  E.g. the RECKONER read-correction tool needs C++11.

**Comment by bgruening** [comment]
@notestaff sorry no news other than soon :(

**Comment by dpryan79** [comment]
Closing, since we're using newer compilers now
