### ISSUE TITLE
AutoMerge workflow has always been failing for the last month spamming notifications

### ISSUE THREAD

**Issue by corneliusroemer** [bioconda/bioconda-recipes#32316]
I've noticed that the AutoMerge workflow has always been failing for a month now causing a large stream of failed CI run notifications that are clogging up my notifications.

Should we switch this workflow off until it's fixed @dpryan79 ?

Or is there another way that I can avoid getting loads of notifications for this single workflow?

https://github.com/bioconda/bioconda-recipes/actions/workflows/AutoMerge.yml

![image](https://user-images.githubusercontent.com/25161793/148557832-91f352e4-a2e2-4e60-9302-b36640ec59bb.png)

The last time it succeeded was more than a month ago:

![image](https://user-images.githubusercontent.com/25161793/148557875-1270d83d-ff6f-4063-a3c8-b1d2a3e05462.png)

**Comment by dpryan79** [comment]
@corneliusroemer Yeah, or I should read into it to figure out what the heck it's supposed to be doing. I've never actually seen it work...

**Comment by dpryan79** [comment]
This should now be disabled.
