### ISSUE TITLE
How to do PR properly?

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#3234]
Hi,
I submitted my second [PR](https://github.com/bioconda/bioconda-recipes/pull/3233). But for some reasons `Sparc` and `SparseAssembler`. I did the following steps:
1. git checkout -b sparc
2. writting recipe
3. git add recipes/sparc
4. git commit -m "Sparc a new recipe"
5. git push origin sparc

Did do anything wrong?

Thank you in advance.

Mic

**Comment by daler** [comment]
It's not clear what you're asking, that PR was created successfully. In general, assuming you're working on your own fork, as it looks like you are doing for that PR, `git push origin branchname` pushes to your fork. You then have to open a PR on bioconda through the github web interface.

**Comment by mictadlo** [comment]
Yes, I do want you said, but for example, my latest [PR](https://github.com/bioconda/bioconda-recipes/pull/3239) also includes all other PR histories. Is it correct?

**Comment by daler** [comment]
Ah, this is kind of a general git question. In general, between PRs, you'll want to go back to master branch, pull any upstream changes, and check out a new branch starting from that updated master branch.
 
Details here:

http://bioconda.github.io/contrib-setup.html (setting up "upstream")
http://bioconda.github.io/contribute-a-recipe.html#update-repo-and-requirements (workflow for a new recipe)

**Comment by bgruening** [comment]
@mictadlo I will close this, let us know if you need more help.

**Comment by mictadlo** [comment]
Thank you for your guys help. It works now.
