### ISSUE TITLE
OSError: More than one meta.yaml files found in /bioconda-recipes/recipes/augustus

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#3254]
I got the below error  for augustus:

``` 
OSError: More than one meta.yaml files found in /Users/lorencm/projects/bioconda-recipes/recipes/augustus
```

while using it in the following way:

```
requirements:
  run:
    - python
    - blast
    - hmmer
    - augustus 3.2.2
```

What did I do wrong?

Thank you in advance

mic

**Comment by druvus** [comment]
I think it is because you listed augustus as a dependency in the augustus.

Agustus was recently updated so I am closing.
