### ISSUE TITLE
cannot upgrade to python 3.8 because of t_coffee (in the dependency chain of bioperl)

### ISSUE THREAD

**Issue by 0xaf1f** [bioconda/bioconda-recipes#32576]
I'm not sure whether t_coffee can be rebuilt for python 3.8+, but my environment is stuck at python 3.7 and I need prokka (the thing needing bioperl) to co-exist with some python code I'm using.

```
Encountered problems while solving:
  - package t_coffee-11.0.8-py37hea885bf_8 requires python >=3.7,<3.8.0a0, but none of the providers can be installed

```

**Comment by 0xaf1f** [comment]
related to #29069 and #20459

**Comment by matthdsm** [comment]
same issue here

**Comment by svm-zhang** [comment]
I have the same t_coffee problem. The installation was successful using the command below. However, the python shipped along with it was 3.7.12. 

`mamba create -n test ensembl-vep=105.0`

If I tried to update the python to >= 3.9 to work with my other scripts, I saw the exact same error message.

It baffles me and is of course beyond my knowledge about why a perl package requires a very specific python version requirement. I tried to look for t_coffee installation documentation and was not able to find anything that relates to this requirement.

Could someone please help fix this problem or suggest some potential solution that I could try? Much appreciated.

**Comment by 0xaf1f** [comment]
I spent too much time trying to shave this yak at one point and I was at least able to get a good picture of the situation before I ran out of time to do something about it. So gather 'round for story time:

There is [t_coffee](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/t_coffee) (Underscore) and [t-coffee](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/t-coffee) (Hyphen).  Underscore came first, but both are currently on the build blacklist. When packaging Underscore, @ostrokach added a [fancy python wrapper to the program executable]((https://github.com/bioconda/bioconda-recipes/commit/d9afcdccb98a638afc5d2f2136b17b8fb8baad9d)) specifically for the conda package, which is where this python <3.7 dependency comes in. `perl-bio-tools-run-alignment-tcoffee` depends on Underscore, so this is how perl and python became intertwined and all these conflicts arose.

I think Hyphen was meant to replace Underscore based on the [post-link message in Hyphen](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/t-coffee/post-link.sh):

```
echo "** WARNING: This T-Coffee recipe is still under development **"
echo ""
echo "It does not contain all required packages to use all T-Coffee modes."
echo "We suggest to use the Bioconda 't_coffee' recipe instead or download it"
echo "from the web site http://www.tcoffee.org"
echo ""
```

So anyway, we're still stuck with Underscore and its unnecessary dependency on python.

The proper course of action to clean up the situation from what I can tell is to:

- remove Hyphen from [the blacklist](https://github.com/bioconda/bioconda-recipes/blame/master/build-fail-blacklist) so that its build doesn't get skipped when you go on to step 2.
- update and finalize the [packaging for Hyphen](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/t-coffee)
- change [perl-bio-tools-run-alignment-tcoffee](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/perl-bio-tools-run-alignment-tcoffee/meta.yaml) so that it depends on Hyphen rather than Underscore. This will break the connection between bioperl and python 3.7.
- celebrate the newfound ability to co-install bioperl and modern versions of python

And then at some point Underscore should be deleted or somehow marked obsolete.

**Comment by 0xaf1f** [comment]
Also related: https://github.com/bioconda/bioconda-recipes/issues/10614

**Comment by svm-zhang** [comment]
@0xaf1f thank you very much for the explanation. Now it all makes sense to me. I will follow the other ticket and hopefully this can get resolved and everybody celebrates!

**Comment by 0xaf1f** [comment]
This has now been fixed! 

>remove Hyphen from [the blacklist](https://github.com/bioconda/bioconda-recipes/blame/master/build-fail-blacklist) so that its build doesn't get skipped when you go on to step 2.

done in https://github.com/bioconda/bioconda-recipes/commit/a78d91b9f7fc47bd3f916be424d470ade80251ad

>    update and finalize the [packaging for Hyphen](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/t-coffee)

done in https://github.com/bioconda/bioconda-recipes/pull/38347

>    change [perl-bio-tools-run-alignment-tcoffee](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/perl-bio-tools-run-alignment-tcoffee/meta.yaml) so that it depends on Hyphen rather than Underscore. This will break the connection between bioperl and python 3.7.

done in [#38199](https://github.com/bioconda/bioconda-recipes/pull/38199)

>    celebrate the newfound ability to co-install bioperl and modern versions of python

:tada: 

There is still a lingering connection between bioperl and python in that `t-coffee` depends on `viennarna`, but at least the latter is a declared python package and gets rebuilt when new python packages are introduced. viennarna is only needed by r-coffee, so maybe that could be split out of the t-coffee package at some point.

**Comment by amizeranschi** [comment]
@0xaf1f many thanks for your help in solving this, once and for all!
