### ISSUE TITLE
start rebuilding R packages with R 3.3.2?

### ISSUE THREAD

**Issue by dyusuf** [bioconda/bioconda-recipes#3270]
ping @bgruening @daler 

Both r channel and conda-forge have released R 3.3.2.

Meanwhile, the bugs in conda R 3.3.1 will not be fixed by r channel -  https://github.com/ContinuumIO/anaconda-issues/issues/1239

wondering if it is the time to rebuild the packages with R 3.3.2?

**Comment by daler** [comment]
Yep, we should do this. It will take a lot of time, but hopefully not as long as before since 3.3.1 -> 3.3.2 is not as big of a jump, and many packages' URLs should still work.

**Comment by dyusuf** [comment]
let me know, when/how we should start. How I should contribute.

**Comment by daler** [comment]
First step is to edit `env_matrix.yml` to use R 3.3.2 (https://github.com/bioconda/bioconda-recipes/blob/master/scripts/env_matrix.yml). That will trigger a re-build of every single R package, so you have to blacklist everything except a handful to avoid overloading travis-ci. The blacklist should be topologically sorted such that the first packages allowed to build are the ones that don't depend on anything but R.

It's technically possible to re-build everything locally all in one shot without blacklisting anything; that would take a while but would be a good way to see what kinds of problems will need to be fixed for the upgrade.

**Comment by daler** [comment]
@dyusuf actually we need to finish the last R packages for 3.3.1. Ideally we're done when everything in `sorted-r-blacklist` is commented-out.

**Comment by bgruening** [comment]
@daler AFAIK the last missing R packages, diffbind for example where problematic because of xlibs. I have a open WIP PR somewhere. Not sure this should block us?

**Comment by daler** [comment]
@bgruening I haven't revisited in a while. If there were issues that will otherwise take a while to resolve then I agree they shouldn't block. But I do think the problems should be indicated somewhere. Comments in sorted-r-blacklist seem to be best (and I've found them to be useful in the past).

@bgruening could you add comments on currently-blacklisted packages that you know have issues (e.g. xlibs problems for diffbind), and @dyusuf could you identify the remaining problems and indicate that in the comments? Middle of next week I will have time to help out.

**Comment by bgruening** [comment]
sorry, it was minfi: https://github.com/bioconda/bioconda-recipes/pull/3010 I will try it once again and then comment it in this file.

**Comment by bgruening** [comment]
@daler what do you think about pinning against `3.3.*`?

**Comment by daler** [comment]
@bgruening how does the build string work with a `*` in `CONDA_R`?

**Comment by bgruening** [comment]
@daler it will not work currently, but quirks in the build-system should not stop us to do the correct thing.
I guess for `*` pinning we should provide a `CONDA_R_STRING` variable that defaults to `3.3.x`

**Comment by daler** [comment]
Ah, good idea. In that case I think it should work. @johanneskoester, thoughts?

**Comment by daler** [comment]
Give it a shot to see if it works! Add a `CONDA_R_STRING` as well, and add that to the build string of all R recipes. I think the only way to figure out if it will work is to try it.

**Comment by bgruening** [comment]
@daler do you think this should be part of every package, or part of bioconda-utils?

**Comment by dyusuf** [comment]
@daler @bgruening 

guys, our group has a deadline pressure to make a conda linux package (based on R 3.3.2) available for the submission of a MS. So for now, I would need to put it this as the priority.

regarding using `3.3.*` , I did a test run while by only setting `CONDA_R: "3.3.*"`, the result is ...r3.3._0.tar.bz2. I need to make a few more tests to see the feasibility. Well, I don't have the time at the moment. will revisit it once the MS is submitted. Now, I just use  `CONDA_R: "3.3.2"`.

After a few runs for compiling pkgs with R 3.3.2, it appears the travis testing for OSX is troublesome with `make: gfortran: No such file or directory` 

Is it because of gfortran not available for the travis OSX build?

**Comment by bgruening** [comment]
`gfortran` has it's own package afaik for OSX.

**Comment by daler** [comment]
@dyusuf many of us have our own deadlines on other things (not necessarily bioconda-related), so I suspect it will take some time to get this done on bioconda as quickly as you need. Perhaps a better approach for you in the meantime would be to have your own conda channel, or one for the group, with the same channel dependencies as bioconda.

For the `gfortran` issue, it may also be in the `gcc` package for OSX rather than `llvm`.

**Comment by dyusuf** [comment]
@daler thanks for the suggestion. well, one of the reasons to stick to bioconda is because it is one of the default channels of galaxytools. our conda pkgs nees to be in bioconda for publishing our galaxy tool in the repo of galaxytools.

@bgruening unless the restriction on the channel requirement is not strict...

**Comment by bgruening** [comment]
@daler @johanneskoester;

I tried to pin R to `CONDA_R: "3.3"` (3.3* also works, but produces 3.3** in between) and it seems to work - we get a package with this name `bioconductor-deseq2-1.12.4-r3.3_3.tar.bz2`

```
Filtering 1 of 1 (100.0%) recipes/bioconductor-deseq2
INFO bioconda_utils.build:build_recipes(265): Building and testing 1 recipes in total
INFO bioconda_utils.build:build_recipes(266): Recipes to build: 
bioconductor-deseq2
INFO bioconda_utils.build:build_recipes(303): Building and testing subdag 0 of 1 (1 recipes)
INFO bioconda_utils.build:build(58): BIOCONDA BUILD START recipes/bioconductor-deseq2, env: CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3*
INFO bioconda_utils.build:build(107): BIOCONDA BUILD SUCCESS /home/bag/miniconda3/conda-bld/linux-64/bioconductor-deseq2-1.12.4-r3.3_3.tar.bz2, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3*
INFO bioconda_utils.build:build_recipes(376): BIOCONDA BUILD SUMMARY: successfully built 1 of 1 recipes
+ set +x
```

The problem I see is that this package does probably not get any preference over the 3.3.1 version. On the other hand

**Comment by dyusuf** [comment]
@daler @bgruening 

I am curious how you guys test the recipes against osx? do you have a mac at hand or...?

**Comment by bgruening** [comment]
@dyusuf I have nothing at hand ... sorry. I completely rely on travis or skip it. Maybe  @bioconda/osx can help.

**Comment by dyusuf** [comment]
@bgruening I am relying on travis while it takes too long.

@bioconda/osx  The package such as bioconductor-impute was successfully built on osx during the last update with R 3.3.1 while now it produces error related to the compiler. 

Do you guys know if the building stability is ensured in the osx system employed by Travis.

**Comment by bgruening** [comment]
@dyusuf it might help to use the travis in your personal fork.
Currently, travis is using a OS-X VM and this has not changed much in the recent month afaik. But it will change on 20.01.2017 ... so no the OS-X image is not really stable. I think this has some licence issues.

**Comment by johanneskoester** [comment]
Sorry guys for answering so late. I am currently porting the R channel to conda-forge (r-base 3.3.2 was the first package). Our goal is to get rid of the R channel completely, because it causes various binary incompatibilities with conda-forge.
Please do not switch to R 3.3.2 until that is finished. We would only waste a lot of build time and probably need to do things again later.

**Comment by johanneskoester** [comment]
xref: conda-forge/staged-recipes#2009

**Comment by croth1** [comment]
@johanneskoester, thanks for doing the heavy lifting here! Do you have a todo-list for things that still have to be done until we can drop the r-channel? Is there anyway we can help you here?

**Comment by johanneskoester** [comment]
@croth1 the plan and progress is outlined in conda-forge/staged-recipes#2009.

**Comment by bgruening** [comment]
@dyusuf instead we have rebuild everything against R 3.4.1 and migrated a lot to conda-forge.
See here more more details: https://github.com/bioconda/bioconda-recipes/pull/6119
