### ISSUE TITLE
Travis CI environment variables

### ISSUE THREAD

**Issue by sebastian-luna-valero** [bioconda/bioconda-recipes#3271]
Hi All,

We use Travis CI environment variables to exclude some tests. Specifically, we use `TRAVIS`, as listed here:
https://docs.travis-ci.com/user/environment-variables/

This variable should also be available when running Travis CI for `bioconda-recipes`, am I right?

For some reason, it does not seem to be the case and it causing our error here:
https://travis-ci.org/bioconda/bioconda-recipes/jobs/185740645#L3762

Best regards,
Sebastian

**Comment by daler** [comment]
Thanks @sebastian-luna-valero, didn't realize others would be depending on those env vars but it makes sense. I'll add an issue to bioconda-utils.

That said, we generally don't run unit tests in recipes (see https://bioconda.github.io/guidelines.html#tests for more info) so in this particular case you might just keep the `cgat --help`.

**Comment by sebastian-luna-valero** [comment]
You're right @daler , many thanks!

I will update the recipe accordingly.

**Comment by bgruening** [comment]
Please feel free to reopen if this is still a problem after @daler has merged #45

**Comment by daler** [comment]
@sebastian-luna-valero can you please try out https://github.com/bioconda/bioconda-utils/pull/49 to see if this fixes the issue?
