### ISSUE TITLE
Struggling to rebump after a failed version release

### ISSUE THREAD

**Issue by nickhsmith** [bioconda/bioconda-recipes#32730]
Hi there. I am a developer of the tMAE package, and 13 days ago I released a new version that was picked up by the bioconda-recipe scraper/bot #32527 to push tMAE from 1.0.2 -> 1.0.3. Immediately after the release, I realized I had made a big mistake. I deleted the release 1.0.3 went back to the code and fixed it up. I have since fixed everything and have since rereleased a new version/tag 1.0.3, but it doesn't seem like this new version of 1.0.3 is being picked up since the previous PR was made.

Is there a way to retrigger this release so that bioconda-recipe is updated for users to install via conda? Do I need to bump the version again?

Thanks again. Sorry for the headache/confusion!

**Comment by c-mertes** [comment]
Yes, you need to bump the version again. Not sure if there is a way to flag the version as nonfunctional?
