### ISSUE TITLE
Can't use simulate-travis.py

### ISSUE THREAD

**Issue by abretaud** [bioconda/bioconda-recipes#3275]
I'm trying to use the `simulate-travis.py` script, but can't get it to work.
It complains about missing `ruamel_yaml` and `conda.fetch` python modules.
I thought running this would fix it:
`./simulate-travis.py --install-requirements`
but obviously it doesn't work since it itself requires these modules.

Am I missing something on this (some magic command to run before maybe?)?

**Comment by daler** [comment]
`conda.fetch` is from conda, and `ruamel_yaml` is a dependency of conda itself. Do you have conda installed in this environment?

**Comment by abretaud** [comment]
Oh... Maybe I messed up my conda:

```
[abretaud@lapinou bioconda-recipes]$ conda --version
conda 4.2.13
[abretaud@lapinou bioconda-recipes]$ conda list
# packages in environment at /home/abretaud/miniconda2:
#
conda                     4.2.13                   py27_0  
conda-build               2.0.12                   py27_0  
conda-env                 2.6.0                         0  
conda-verify              2.0.0                    py27_0  
contextlib2               0.5.4                    py27_0  
enum34                    1.1.6                    py27_0  
filelock                  2.0.7                    py27_0  
jinja2                    2.8                      py27_1  
markupsafe                0.23                     py27_2  
openssl                   1.0.2j                        0  
patchelf                  0.9                           0  
pip                       9.0.1                    py27_1  
pkginfo                   1.4.1                    py27_0  
pycosat                   0.6.1                    py27_1  
pycrypto                  2.6.1                    py27_4  
python                    2.7.13                        0  
pyyaml                    3.12                     py27_0  
readline                  6.2                           2  
requests                  2.12.4                   py27_0  
ruamel_yaml               0.11.14                  py27_0  
setuptools                27.2.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3  
[abretaud@lapinou bioconda-recipes]$ ./simulate-travis.py --install-requirements
Traceback (most recent call last):
  File "./simulate-travis.py", line 6, in <module>
    import ruamel_yaml as yaml
ImportError: No module named ruamel_yaml
```

**Comment by daler** [comment]
For contributing to bioconda, you need to have a py3 root environment (see https://bioconda.github.io/contrib-setup.html#install-conda-and-docker-one-time-setup for details). Looks like you have py27, that might be causing the issue.

**Comment by abretaud** [comment]
Oh. I used `planemo conda_init` to install it.
@bgruening should planemo/galaxy install miniconda3?

**Comment by JenCabral** [comment]
I had this issue when I had more than one conda installed on my machine. Once I removed the one that was not miniconda3, the issue disappeared. 
You can use conda info it should give you a bit more info about what's installed where

**Comment by bgruening** [comment]
@abretaud for planemo miniconda2 or miniconda3 can be used, we do not have any preference. However, bioconda-utils needs miniconda3 - which just means python3.

**Comment by abretaud** [comment]
Ok, it works with miniconda3, thanks!

@bgruening I'm thinking about our training in january, I thought the recommended workflow would look like this:

- pip install planemo
- planemo conda_init
- write your conda recipe
- test it with simulate-travis.py
- push the recipe to bioconda
- make your galaxy tool xml with functional tests
- planemo conda_install
- planemo test --conda_dependency_resolution
- ...

But conda_init will install a conda version that will not allow to run simulate-travis (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/deps/conda_util.py).
So should we recommend to install miniconda3 by hand instead of conda_init?

**Comment by bgruening** [comment]
We can try to get a patch into galaxy/planemo to install miniconda3, at least optionally.

**Comment by abretaud** [comment]
The install code is in galaxy/galaxy-lib :/

**Comment by abretaud** [comment]
I think this can be discussed in https://github.com/galaxyproject/planemo/issues/604 now
