### ISSUE TITLE
perl-rest-client no longer found in PERL5LIB

### ISSUE THREAD

**Issue by marchoeppner** [bioconda/bioconda-recipes#32787]
Hi,

I have previously used the perl-rest-client package without issues. Over the past month or so something must have changed since it can no longer be found when installed via bioconda. 

I tried "native" conda environments (v2 and v3) on my local  machine as well as conda-within-docker-container setups. The library does not end up in any of the paths included in PERL5LIB within the environment. I also cannot find it anywhere else. From the recipie, I cannot tell why that would be the case... Maybe someone can try and reproduce this?

Steps to reproduce:
conda install -c bioconda perl-rest-client

And then load the library in a perl script within the activated environment:

use REST::Client;

Throws an error that the library was not found.

Cheers,
Marc

**Comment by dpryan79** [comment]
Can you create a new environment with it? I just finished rebuilding everything for perl 5.32.1, so you may be getting a mixture of packages for different versions of perl (years ago this wasn't properly pinned, which is the most likely cause of this behavior).

**Comment by marchoeppner** [comment]
Sorry for the late reply. Yes, this seems fixed now. Thanks!
