### ISSUE TITLE
simulate_travis.py always uses docker, regardless of the --docker flag

### ISSUE THREAD

**Issue by lparsons** [bioconda/bioconda-recipes#3291]
Even without the `--docker` flag, I get `+ bioconda-utils build recipes config.yml --docker --loglevel=info --packages quast --force` which tries to run docker.

It looks like [`simulate_travis.py` sets `TRAVIS_OS_NAME` to `linux`](https://github.com/bioconda/bioconda-recipes/blob/master/simulate-travis.py#L138) and [`travis_run.sh` forces `--docker` if `TRAVIS_OS_NAME == “linux”`](https://github.com/bioconda/bioconda-recipes/blob/master/scripts/travis-run.sh#L14).

I'm not sure how to properly fix this without breaking something, so I'm just reporting it for now.

**Comment by tomkinsc** [comment]
@bioconda/core: commenting on this in case it was missed during the holidays.

**Comment by epruesse** [comment]
outdated
