### ISSUE TITLE
recipe outside bioconda channel

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#3302]
Hi,
it seems I need lpsolve for [augustus](https://github.com/bioconda/bioconda-recipes/pull/3283) and I found a recipe [here](https://anaconda.org/snorfalorpagus/lpsolve). 

Is there a way to tell inside Augustus recipe to use a foreign recipe?

Thank you in advance.

Michal

**Comment by bgruening** [comment]
No this is not possible, but you could include this recipe in bioconda, or in conda-forge which would be more appropriate I think.
