### ISSUE TITLE
reprof package needed

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#3335]
Anyone wants to create a package for https://github.com/Rostlab/reprof to learn packaging with bioconda?

https://github.com/Rostlab/reprof

**Comment by souravsingh** [comment]
I can help with this.

**Comment by bgruening** [comment]
@souravsingh that would be great, let me know if you need any help. I started with this package: https://github.com/bioconda/bioconda-recipes/pull/3336

**Comment by epruesse** [comment]
outdated
