### ISSUE TITLE
Prokka running error

### ISSUE THREAD

**Issue by sekhwal** [bioconda/bioconda-recipes#33356]
Hi, 
I am trying to install prokka using conda. However, it shows an error when I run it. I tried in different ways to install prokka but it still shows the error while running and does not produce output files.

I using the command for installation:

conda install -c conda-forge -c bioconda -c defaults prokka

error:::

------------- EXCEPTION ------------- MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /home/anaconda3/envs/genome-anno/lib/perl5/5.32/site_perl /home/anaconda3/envs/genome-anno/lib/perl5/site_perl /home/anaconda3/envs/genome-anno/lib/perl5/5.32/vendor_perl /home/anaconda3/envs/genome-anno/lib/perl5/vendor_perl /home/anaconda3/envs/genome-anno/lib/perl5/5.32/core_perl /home/anaconda3/envs/genome-anno/lib/perl5/core_perl .) at /home/anaconda3/envs/genome-anno/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

STACK Bio::Root::Root::_load_module /home/anaconda3/envs/genome-anno/lib/perl5/site_perl/Bio/Root/Root.pm:522 STACK (eval) /home/anaconda3/envs/genome-anno/lib/perl5/site_perl/Bio/SearchIO.pm:620 STACK Bio::SearchIO::_load_format_module /home/anaconda3/envs/genome-anno/lib/perl5/site_perl/Bio/SearchIO.pm:619 STACK Bio::SearchIO::new /home/anaconda3/envs/genome-anno/lib/perl5/site_perl/Bio/SearchIO.pm:217

STACK toplevel /home/anaconda3/envs/genome-anno/bin/prokka:1113
For more information about the SearchIO system please see the SearchIO docs. This includes ways of checking for formats at compile time, not run time Can't call method "next_result" on an undefined value at /home/anaconda3/envs/genome-anno/bin/prokka line 1114.

**Comment by rpetit3** [comment]
I've submitted a PR to address this issue: https://github.com/bioconda/bioconda-recipes/pull/33411

**Comment by rpetit3** [comment]
The `Bio::SearchIO::hmmer3` module was removed in  v1.7.3 of BioPerl, and likely the newer version v1.7.8 is being installed. My pull request pins the BioPerl version to v1.7.2 to resolve this issue

**Comment by sekhwal** [comment]
I think I have already installed Bioperl v1.7.8. Please see my command below:
sudo cpanm install Bio::Root::Version module
install is up to date. (0.01)
Bio::Root::Version is up to date. (1.7.8)

**Comment by rpetit3** [comment]
Yep, you need BioPerl 1.7.2

**Comment by sekhwal** [comment]
Could you please let me know how to install BioPerl 1.7.2. I was trying to follow the instruction using the [page](https://wiki.archlinux.org/title/Bioperl). However, it does not help me.

**Comment by sekhwal** [comment]
I could not find Bioperl 1.7.2 at [Metacpan](https://metacpan.org/release/CJFIELDS/BioPerl-1.7.0._2).

**Comment by rpetit3** [comment]
```
conda activate YOUR_PROKKA_ENVIRONMENT
conda install -c conda-forge -c bioconda 'perl-bioperl=1.7.2'
```

**Comment by sekhwal** [comment]
Thank you very much for your help. It works now.

In addition, I was wondering if you could help me to solve following message when I install a package using conda:

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

**Comment by rpetit3** [comment]
Awesome! And, those "solving envrionment" messages can be ignored. 

Going to close this for now, cheers!
