### ISSUE TITLE
samtools 1.15 exclude htslib 1.15  as dependency

### ISSUE THREAD

**Issue by maarten-k** [bioconda/bioconda-recipes#33361]
Samtools 1.15 excluded htslib 1.15 as a dependency.

`
htslib >=1.14,<1.15.0a0`

samtools 1.15 ends up now with an older version of htslib (1.14) as a dependency. 

Would a rebuild fix this problem or am I oversimplifying this issue?

**Comment by maarten-k** [comment]
Artifact of rebuild is still limited to 
   "htslib >=1.14,<1.15.0a0",

**Comment by maarten-k** [comment]
There is a separate file with htslib number in there. I updated it to 1.15

**Comment by maarten-k** [comment]
Looks this is fixed in #33362

**Comment by jmarshall** [comment]
This is now fixed for samtools by PR #33366. (Should also be fixed for bcftools as well, but that is still percolating through anaconda's server caches.)
