### ISSUE TITLE
Happy new year!

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#3337]
Dear @bioconda/all!

This is just small summary of 2016 from the BioConda perspective to say thanks to everyone involved in this great project.
BioConda has become a huge bioinformatic community with 175 contributors and more and more upstream developers, maintaining there own tools and packages. We could create nearly 2000 conda packages, many of them with multiple versions. 

A few highlights:
* complete [new documentation](https://bioconda.github.io) and Guidelines (thanks @daler)
* bioconda-utils was created as a home for all our tooling around bioconda (thanks to @daler and @johanneskoester)
* migration of all R packages to R-3.3
* we had our first Community Contribution Fest with more then 20 participants
* testing of packages was improved a lot
* we joined forces with conda-forge
* for every conda package a [BioDocker container](https://quay.io/organization/biocontainers) is created
* ~2000 packages and containers (thanks to @bioconda/all)

Not bad for one year of work! :)
Happy new year to all of you!
Bjoern

**Comment by hainm** [comment]
happy new year to all. ^^

**Comment by gregvonkuster** [comment]
Many, many thanks to you @bgruening - you enabled much of this!  ;)

**Comment by daler** [comment]
Because @bgruening is too modest, I'd like to point out that any item on his list that does not have a name is his own work :) And I think his tireless work in improving PRs, resolving issues, and community outreach has contributed more than anything else to this first year's success. Thanks Bjoern!

**Comment by jerowe** [comment]
Congratulations and happy new year!

**Comment by johanneskoester** [comment]
Indeed, thanks to all of you! I would never have imagined that Bioconda would grow that fast when we started it in 2015. I can also only agree on praising @bgruening for all his work!

**Comment by leobiscassi** [comment]
Happy new year to all!
I'd like especially thank you @bgruening for all support and encouragement to contribute in the past year, was really important to me. 2017 will be awesome!

**Comment by mictadlo** [comment]
Happy new year to all!
