### ISSUE TITLE
igblast - libncbi-vdb.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zktuong** [bioconda/bioconda-recipes#33479]
Hi,

I noticed that igblast (v1.17.1) stopped working yesterday.

I nailed it down to because of a new upload for ncbi-vdb to 3.0.0 yesterday:
https://anaconda.org/bioconda/ncbi-vdb

While installation with `conda install -c bioconda igblast` performs without issue, when trying to execute the program like `igblastn -h`, it returns an error:
`error while loading shared libraries: libncbi-vdb.so.2: cannot open shared object file: No such file or directory`

This was solved with:
`conda install -c bioconda igblast ncbi-vdb=2.11.0`

**Comment by marcelm** [comment]
* The PR updating ncbi-vdb is at #33449
* There is a Debian bug about an identical problem: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=953897
* It may be helpful to look at the patches that Debian applies: https://salsa.debian.org/med-team/ncbi-vdb/-/commits/master/

**Comment by marcelm** [comment]
Hi, a new Bioconda IgBLAST package has been uploaded. Can you try again? This new one works for me.

**Comment by zktuong** [comment]
Yes thanks for the prompt response. it's working now!
