### ISSUE TITLE
Kat recipe does not build

### ISSUE THREAD

**Issue by JenCabral** [bioconda/bioconda-recipes#3366]
While trying to update the Kat recipe to pull the latest version from the developers github repo, I've run into a problem where even the original recipe won't build. Using simulate-travis.py I receive the following error:
```
Package: kat-2.0.8-1
source tree in: /opt/conda/conda-bld/work
Command failed: /bin/bash -x -e /opt/conda/conda-bld/work/conda_build.sh

ERROR bioconda_utils.build:build_recipes(355): BIOCONDA BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
ERROR bioconda_utils.build:build_recipes(366): BIOCONDA BUILD SUMMARY: FAILED recipe kat-2.0.8-1.tar.bz2, environment CONDA_GSL=1.16;CONDA_GMP=5.1;CONDA_PY=27;CONDA_BOOST=1.60;CONDA_PERL=5.22.0;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_R=3.3.1
Traceback (most recent call last):
  File "./simulate-travis.py", line 150, in <module>
    sp.run(['scripts/travis-run.sh'], env=env, universal_newlines=True, check=True)
  File "/home/jcabral/miniconda3/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['scripts/travis-run.sh']' returned non-zero exit status 1
```
To build the original I modified the meta.yaml so the build number was 1.

Additionally, I noticed an error when conda installs kat, the most recent boost version is used. Kat requires boost 1.60 so I must then force install boost 1.60.

I am hoping to update version both because the current one has a bug with boost and because Kat has been changed quite a bit since 2.0.8.

**Comment by bgruening** [comment]
@JenCabral the error should be above this message, do you have more information?

**Comment by JenCabral** [comment]
I have a gist of the full output:
https://gist.github.com/JenCabral/f44d98bbf33f226493bff7d984418337

**Comment by bgruening** [comment]
Please try to add `perl` as build-dependency. If this is not enough, please add this to your build-dependencies: https://github.com/bioconda/bioconda-recipes/blob/a9982d89942003874f4b3887580d291de2d651bf/recipes/exparna/build.sh#L3-L13

**Comment by bgruening** [comment]
This should be fixed now.
