### ISSUE TITLE
This job ran on an OS X image that will be retired on January 20, 2017. After that, it will route to our Xcode 6.4 infrastructure.

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#3374]
@bioconda/core @bioconda/osx travis will change the OS-X image and XCode really soon.

Please read more about this here: https://blog.travis-ci.com/2016-12-13-xcode-82-ga-is-here

Should we use an older version, what is the impact on OS-X if we compile on newer versions ...
It's probably worth to look at conda-forge to make a decision, if we do not decide anything we will compile soon on a newer OS-X and XCode.

**Comment by daler** [comment]
I feel like we've been pretty good about depending on llvm (or gcc in some cases) in the osx packages that need them. Theoretically our packages should already be agnostic to what's on the system.

HPCs tend to not use OSX, so I don't think supporting older OSX is as important as supporting older CentOS.

But we should start spot-checking some known-to-be-problematic recipes on 8.2 to see what we're up against.

**Comment by johanneskoester** [comment]
I agree. Building on a newer OSX should be fine. Giving a minimum version guarantee is much more important for HPC and Linux.

**Comment by bgruening** [comment]
Than nothing is to be done here, great!
Last question, can a incompatibility with conda-forge have any implications here?

**Comment by johanneskoester** [comment]
What kind of incompatibility?

**Comment by bgruening** [comment]
That they compile on older OS-X versions.
