### ISSUE TITLE
bioconductor-curatedmetagenomicdata broken package download link

### ISSUE THREAD

**Issue by simone-pignotti** [bioconda/bioconda-recipes#33841]
Hi,

I am running into the following error when installing `bioconductor-curatedmetagenomicdata`:
```
ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 682d4fd17da55f29fcfa2196f7745746:
https://bioconductor.org/packages/3.14/data/experiment/src/contrib/curatedMetagenomicData_3.2.1.tar.gz
```

On the other hand, version 3.2.3 is available from the same location, so changing the package version here
https://github.com/bioconda/bioconda-recipes/blob/aad25a47d26c5401c50d2e3471c4e046d083de66/recipes/bioconductor-curatedmetagenomicdata/meta.yaml#L1
to 3.2.3 might simply fix this.

Tagging @dpryan79 based on previous contributions, sorry if it's not the right person!
Thanks

**Comment by dpryan79** [comment]
@simone-pignotti Can you make a PR to update this? Bioconductor is always removing these packages :(

**Comment by dpryan79** [comment]
@simone-pignotti The CI will test that.

**Comment by simone-pignotti** [comment]
Great, should be ready to merge!

**Comment by dpryan79** [comment]
@bioconda-bot please fetch artifacts

**Comment by simone-pignotti** [comment]
Thank you very much @dpryan79, I successfully installed and tested the new version locally.
