### ISSUE TITLE
help requested compiling dada2 on OSX 

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#3391]
Hi Team Bioconda,

I'm running into an Rcpp-related issue when compiling `bioconductor-dada2` on osx. I'm wondering/hoping  that someone may have pointers/suggestions on fixes (maybe the legendary  @bgruening ?).

I'm beginning to think the issue is that Rcpp was compiled with a different compiler  - could that account for this error? ([these](https://github.com/hadley/dplyr/issues/1770) [seem](https://github.com/hadley/dplyr/issues/213) to suggest yes). 

Branch: https://github.com/zachcp/bioconda-recipes/tree/newdada2
Failed Build: https://travis-ci.org/zachcp/bioconda-recipes/jobs/189599749

Here is a taste of the error log:
```
bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla
+ mv DESCRIPTION DESCRIPTION.old
+ grep -v '^Priority: ' DESCRIPTION.old
+ /anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/bin/R CMD INSTALL --build .
* installing to library ‘/anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library’
* installing *source* package ‘dada2’ ...
** libs
clang++ -std=c++11 -I/anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/lib/R/include -DNDEBUG  -I/anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/include -I"/anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library/Rcpp/include" -I"/anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library/RcppParallel/include"   -fPIC  -I/anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/include -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from ./../inst/include/dada2.h:7:
In file included from ./../inst/include/dada2_RcppExports.h:7:
In file included from /anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library/Rcpp/include/Rcpp.h:38:
In file included from /anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library/Rcpp/include/Rcpp/Vector.h:69:
/anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library/Rcpp/include/Rcpp/String.h:586:12: error: explicit specialization of non-template struct 'hash'
    struct hash<Rcpp::String>
           ^   ~~~~~~~~~~~~~~
/anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library/Rcpp/include/Rcpp/String.h:589:24: error: expected '(' for function-style cast or type construction
            return hash<string>()(s.get_cstring());
                   ~~~~^
/anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library/Rcpp/include/Rcpp/String.h:589:25: error: unexpected type name 'string': expected expression
            return hash<string>()(s.get_cstring());
                        ^
/anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library/Rcpp/include/Rcpp/String.h:589:33: error: expected expression
            return hash<string>()(s.get_cstring());
                                ^
In file included from RcppExports.cpp:4:
In file included from ./../inst/include/dada2.h:7:
In file included from ./../inst/include/dada2_RcppExports.h:7:
In file included from /anaconda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library/Rcpp/include/Rcpp.h:65:
```

**Comment by kyleabeauchamp** [comment]
Perhaps it's a C++11 versioning issue, where on OSX the default C++ version (e.g. C++11 versus older C++) is always a bit different.  Might try searching for c++11 in the previous issues?

**Comment by bgruening** [comment]
If this is really related to the compiler, I hope you can wait a little bit. @johanneskoester is porting currently the `r` channel, including `rcpp` to conda-forge, where we share some build infrastructure and the compiler.

My proposal would be to skip the OSX builds for now until @johanneskoester is finished and a new conda-forge based rcpp exists. If you have some time, I bet @johanneskoester needs some help in porting them over :)

**Comment by zachcp** [comment]
thanks @bgruening ; I'm going to wait on this until the conda-forge port is complete.  @johanneskoester how are you doing the ports of the r system?  I might be able to lend a hand.

**Comment by johanneskoester** [comment]
@zachcp thanks, I appreciate that!! Conda-forge is experiencing some issues in their build system which have to be fixed first. Unfortunately their progress is kind of slow at the moment. Once that is fixed, I will make a plan which package to port when. You can watch the issue conda-forge/staged-recipes#2009 for progress, and join whenever you want.

**Comment by martin-mann** [comment]
@zachcp 
Hi, I am running into OSX build problems myself and found [this](http://stackoverflow.com/questions/19912862/compiling-boostprogram-options-on-mac-os-x-with-g-4-8-mac-ports) (giving it a try right now), i.e. you might need to explicitely set the c++lib used via `CXXFLAGS=-stdlib=libc++ LDFLAGS=-stdlib=libc++`, but not sure about the outcome yet. :)

**Comment by zachcp** [comment]
thanks @martin-mann . I'd like to avoid the rabbit hole of recompiling things with different compilers if at all possible. If you have a workaround we can get it working, otherwise i'm inclined to wait until the port to conda-forge is complete.
