### ISSUE TITLE
modern Xorg stack

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#3394]
Hi all,

there is a interesting PR on conda-forge (https://github.com/conda-forge/staged-recipes/pull/2068) that was closed because of low priority and less time.

We also have a few packages here that require some Xorg libs which are currently relying on libs in the Docker containers, so are not completely relocatable.

If someone has time the PR above is nearly complete. The recipe needs to be split up into several packages and a metapackage needs to be created. It's hopefully easy to do, but time consuming. I think a good chance to look at conda-forge and contribute a important stack to the conda community.

Ciao,
Bjoern

**Comment by souravsingh** [comment]
I am interested in working on the issue. Which packages need to be pushed?

**Comment by bgruening** [comment]
@souravsingh please read the last comments on: https://github.com/conda-forge/staged-recipes/pull/2068
Maybe you can coordinate with them a little bit! Thanks!

**Comment by bgruening** [comment]
This stack is now more or less in conda-forge.
