### ISSUE TITLE
Binaries not being uploaded

### ISSUE THREAD

**Issue by armintoepfer** [bioconda/bioconda-recipes#33969]
I see that the nightly upload are failing and that I can't access the latest version via conda.

For example `primrose` is at v1.3
https://anaconda.org/bioconda/primrose/files

This upload is failing
https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/63382/workflows/73a97e1a-2c5d-49eb-81d3-5f2de6764d3b/jobs/180092

**Comment by armintoepfer** [comment]
Hey @bioconda/build-system, can you please have a look?

**Comment by dpryan79** [comment]
Anaconda's CDN sync is broken again. I've notified them.

**Comment by martin-raden** [comment]
it's back to normal it seems... at least the packages I uploaded on 28th are online now.

**Comment by martin-raden** [comment]
could be closed?
