### ISSUE TITLE
Rsem should have perl

### ISSUE THREAD

**Issue by jerowe** [bioconda/bioconda-recipes#3397]
rsem-expression command requires perl. I will rebuild the recipe to include this.

**Comment by bgruening** [comment]
Can you include a test that catches this error?
Thanks!

**Comment by jerowe** [comment]
Sure.

I remember seeing at some point a discussion on which R package should be required. Is it r or r-base?

**Comment by bgruening** [comment]
`r` for the moment!

**Comment by jerowe** [comment]
Closing.
