### ISSUE TITLE
CANU can't find JAVA and GNUplot

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#3409]
Hi @sh4wn and @bgruening,
With our current CANU recipe and even with CANU's binary build, I am running into this [problem](https://github.com/marbl/canu/issues/329).

Any idea what would be the path for java and  gnuplot in our recipe or can we modify the recipe to put the paths for them into ~/.canu?

Thank you in advance

Michal

**Comment by bgruening** [comment]
Me too!
@rvalieris can you contact me please via mail?

**Comment by sh4wn** [comment]
I also cannot reproduce this, installs and runs fine here.
