### ISSUE TITLE
No biocontainer for staden_io_lib

### ISSUE THREAD

**Issue by matthdsm** [bioconda/bioconda-recipes#34138]
There's no biocontainer to be found for staden_io_lib.

Can I trigger the build manually somewhere?

Thanks
M

**Comment by matthdsm** [comment]
@bioconda/build-system?

**Comment by bgruening** [comment]
https://quay.io/repository/biocontainers/staden_io_lib?tab=tags&tag=latest

**Comment by bgruening** [comment]
Is this what you are searching?

**Comment by matthdsm** [comment]
wow damn... my search didn't turn up anything.. 
Thanks for the help, feeling pretty stupid now
