### ISSUE TITLE
bioconda-legacy

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#3417]
Instead of deleting old repositories that are migrated to conda-forge, is it ok if I create a channel called `bioconda-legacy` and migrate packages into this channel for people that needs them for some reasons?

**Comment by daler** [comment]
Sounds good. I definitely don't think any should be deleted. Can you also add info on this to the guidelines? Maybe as another checklist item -- ensure the recipe is not in the legacy folder.

**Comment by bgruening** [comment]
@bioconda/all I created https://anaconda.org/bioconda-legacy and moved perl into it.

**Comment by bgruening** [comment]
I also moved autoconf into this new organisation: https://github.com/bioconda/bioconda-recipes/issues/3443

**Comment by croth1** [comment]
What is the plan for the recipes? Should they go in a separate legacy repository or do we just remove them?

**Comment by bgruening** [comment]
@croth1 the recipes are all migrated into conda-forge. So recipe will be there, if you need older versions or the exact same version it is in the git history and in the package tarball. Is this ok?

**Comment by mmiladi** [comment]
@bioconda/core I am facing this error while trying to install circos which depends on perl-gd (now in conda-forge), without having conda-forge in default channels the recipe fails. Is there a way to include conda-forge channel for bioconda-legacy dependencies by default?

```
$ conda install -c bioconda circos
Fetching package metadata .............
Solving package specifications: 

PackageNotFoundError: Package not found: '' Dependencies missing in current linux-64 channels: 
  - circos -> perl-gd -> libgd >=2.2.4
  - circos -> perl-gd -> perl 5.22.0*
  - circos -> perl-readonly

Close matches found; did you mean one of these?
    libgd: libgdal, libdb, libpng
    perl: perl-b, petl, pepr

You can search for packages on anaconda.org with
    anaconda search -t conda perl-readonly
(and similarly for the other packages)

```
