### ISSUE TITLE
Drop bioconda autoconf

### ISSUE THREAD

**Issue by nsoranzo** [bioconda/bioconda-recipes#3443]
autoconf in conda-forge has been updated to use `/usr/bin/env perl` in https://github.com/conda-forge/autoconf-feedstock/pull/12 which is a better solution than the one presently in the bioconda recipe.

Can we drop autoconf from the bioconda channel, so it does not take precedence over the conda-forge one?

Ping @druvus @dyusuf @bgruening

**Comment by bgruening** [comment]
@nsoranzo I created https://anaconda.org/bioconda-legacy/autoconf and moved this package into this new organisation.

**Comment by nsoranzo** [comment]
Thanks @bgruening!

**Comment by nsoranzo** [comment]
@bgruening https://anaconda.org/bioconda/autoconf/files seems to still contain a package ( linux-64/autoconf-2.69-pl5.22.0_3.tar.bz2 ).

**Comment by bgruening** [comment]
Some PR updated it `1 hour and 25 minutes ago`. Now I have a problem, since I can not move it to legacy, I will remove just this one.

**Comment by bgruening** [comment]
removed

**Comment by nsoranzo** [comment]
Was built again this night :sad:

**Comment by bgruening** [comment]
And removed again. I think this is due to all PR that where merged before I removed the recipes from the repo.

**Comment by nsoranzo** [comment]
Yep, I suspect that too.
