### ISSUE TITLE
Can not install libgd dependency in OSX build

### ISSUE THREAD

**Issue by bow** [bioconda/bioconda-recipes#3465]
Hi everyone,

During building of a package in Travis, I am getting this error message for the libgd package (a dependency of a dependency of a package I am trying to build):

    ...
    conda.exceptions.PaddingError: Placeholder of length '32' too short in package bioconda::libgd-2.2.3-3.
    The package must be rebuilt with conda-build > 2.0.

[Here](https://travis-ci.org/bow/bioconda-recipes/jobs/191520302#L623) is the complete log. This only occur in the OSX build; the exact same package [can be built](https://travis-ci.org/bow/bioconda-recipes/jobs/191520301) in Linux just fine.

Is this a known issue or is this expected? Is there anything I can help to fix this?

**Comment by croth1** [comment]
Recently the libgd was migrated to conda-forge. See https://github.com/conda-forge/libgd-feedstock.

I am not planning to maintain the bioconda version anymore. Do you have the same problem with libgd from conda-forge?

**Comment by bow** [comment]
I haven't (not sure how, actually) checked libgd from conda-forge. This may be a bit difficult for me since I do not have OSX myself, and I do not depend on libgd directly.

My package actually depends on circos, which depends on perl-gd, which then depends on libgd. Bioconda has recipes for all these three packages, which I assume is being used during the Travis build.

Does this mean circos and perl-gd both need to be rebuilt to depend on conda-forge's libgd?

**Comment by jrderuiter** [comment]
I have the same issue, but the libgd from conda-forge works fine for me. Can we just remove this bugged version from bioconda, if it is no longer going to be maintained?

**Comment by croth1** [comment]
ping @bioconda/core for that.

**Comment by bgruening** [comment]
In conda-forge is the version 2.2.1 and in bioconda 2.1.1post. Not sure how big the impact on reproducibility is.
@johanneskoester @daler are you ok if I move this package into bioconda-legacy and purge the recipe?

**Comment by daler** [comment]
@bgruening using the maintained conda-forge version sounds good to me. I think this kind of thing will be coming up a lot as we migrate packages over there, so we should probably decide how to handle these in general.

**Comment by bgruening** [comment]
My proposal is to move packages to bioconda-lagacy (a new repository on anaconda.org) and remove the recipe from git before.

**Comment by daler** [comment]
@bgruening sorry about that, for some reason I keep thinking of `bioconda-legacy` as a git repo of recipes or a subdirectory within the `bioconda` repo, rather than the anaconda channel of packages that it is. I'm just being dense. Yes, moving to `bioconda-legacy` anaconda channel sounds great!

**Comment by bgruening** [comment]
Removed the recipe and tranfered the package to `bioconda-legacy`

**Comment by bow** [comment]
Thank you @bgruening! I can confirm now that the exact same commit [works in both Linux and OSX](https://travis-ci.org/bow/bioconda-recipes/builds/191520300).
