### ISSUE TITLE
Reported slimfastq version does not match bioconda's version

### ISSUE THREAD

**Issue by Midnighter** [bioconda/bioconda-recipes#34673]
@maarten-k slimfastq's bioconda version is 2.04 but when I run `slimfastq -v` the output is:

```
Version 2.03
Internal format version=6
```

Is there an easy way to fix that?

**Comment by maarten-k** [comment]
Thanks for the report. I can confirm your finding. The release of slimfastq 2.04 downloaded from Github, has  2.03  as the version number(config.cpp:45) .  
a simple ` sed -i 's@user_version="2.03";@user_version="2.04";@g' config.cpp ` before compiling would sort this out.

However, I think bioconda is not the place to fix this issue  (correct me if I am wrong).

**Comment by Midnighter** [comment]
My bad, I realized later that the 2.04 version was not something you added but is an actual release of slimfastq itself. I'll report it there.
