### ISSUE TITLE
Jillian Rowe as BioConda Core member

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#3479]
I would like to propose @jerowe as a @bioconda/core member.

She already is one of our top contributors: https://github.com/bioconda/bioconda-recipes/graphs/contributors and has help a lot lately with reviewing and closing issues.

I think she will be a great addition to our small core team!
@bioconda/core please vote!

**Comment by jerowe** [comment]
Hi all, 

Thanks for the nomination. ;)  Bioconda is an awesome and incredibly useful project! I am very happy to be a part of it.

**Comment by aymanm** [comment]
I vote yes. Jillian lives and breathes bioconda

**Comment by tomkinsc** [comment]
👍

**Comment by daler** [comment]
Definitely!

**Comment by johanneskoester** [comment]
Yes, that's a great idea!

**Comment by bgruening** [comment]
@jerowe welcome to @bioconda/core! I think you the entire bioconda community can be glad to have you in the core team! Thanks!

**Comment by jerowe** [comment]
Thanks! I'm very excited to be a part of the bioconda core team!
