### ISSUE TITLE
bioconda-utils hangs on test section

### ISSUE THREAD

**Issue by sebastian-luna-valero** [bioconda/bioconda-recipes#3496]
Hello,

My recipes are hanging on the test part of the recipe:

https://github.com/bioconda/bioconda-recipes/pull/3491
https://travis-ci.org/bioconda/bioconda-recipes/builds/192344798

https://github.com/bioconda/bioconda-recipes/pull/3493
https://travis-ci.org/bioconda/bioconda-recipes/builds/192346796

Running `simulate-travis.py` locally I can see that the execution hangs on the test section:
```
INFO bioconda_utils.build:build(124): BIOCONDA TEST START via mulled-build recipes/cgat-pipelines-nosetests, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
updating index in: /sebastian/i35/conda-bld/linux-64

DEBUG bioconda_utils.pkg_test:test_package(97): Tests to run: python --version && R --version && python -c "import numpy" && python -c "import pandas" && python -c "import pysam" && python -c "import pybedtools" && python -c "import rpy2"

DEBUG bioconda_utils.pkg_test:test_package(121): No container push commands are generated

DEBUG bioconda_utils.pkg_test:test_package(122): mulled-build command: ['mulled-build', 'build-and-test', 'cgat-pipelines-nosetests=0.0.1--py27r3.3.1_0', '-n', 'biocontainers', '--test', 'python --version && R --version && python -c "import numpy" && python -c "import pandas" && python -c "import pysam" && python -c "import pybedtools" && python -c "import rpy2"', '--extra-channels', 'file://sebastian/i35/conda-bld,r,defaults,conda-forge']
```

Has something changed recently in that regard in the build system?

Many thanks,
Sebastian

**Comment by bgruening** [comment]
Not recently, but since a few month we are testing packages in a busybox Docker container. It seems you package is not running in this environment, which indicates that you are missing something ... or at least something is wrong.

**Comment by sebastian-luna-valero** [comment]
That's strange. Even when I remove the test section completely, the `simulate-travis.py` execution hangs on:
```
INFO bioconda_utils.build:build(124): BIOCONDA TEST START via mulled-build recipes/cgat-scripts-nosetests, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=35;CONDA_R=3.3.1
updating index in: /sebastian/i35/conda-bld/linux-64

DEBUG bioconda_utils.pkg_test:test_package(97): Tests to run: 

DEBUG bioconda_utils.pkg_test:test_package(121): No container push commands are generated

DEBUG bioconda_utils.pkg_test:test_package(122): mulled-build command: ['mulled-build', 'build-and-test', 'cgat-scripts-nosetests=0.0.2--py35r3.3.1_0', '-n', 'biocontainers', '--test', '', '--extra-channels', 'file://sebastian/i35/conda-bld,r,defaults,conda-forge']

```

@bgruening are you able to reproduce the problem on your end?

**Comment by bgruening** [comment]
Not yet sorry. Not sure if I will find time this week, giving a workshop at the moment.

**Comment by sebastian-luna-valero** [comment]
Thanks @bgruening 

@daler I have been able to reproduce the same problem with your metapackage:
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/hubward-all

If you try running `simulate-travis.py` on that (with an updated version number), it will also hang on the test section. Do you know why?

**Comment by daler** [comment]
I could see `hubward-all` failing now due to not having any tests (that package was added long before we had our current infrastructure). But for your PR you've included tests. Maybe there's something about having a build.sh, or maybe there's something about the structure of a metapackage that causes mulled-build to hang.

I just tested the hubward-all package locally. It did hang where you mention ("`mulled-build command: ...`") for a while, but watching CPU and resources it looked like it was doing a lot of disk i/o. After letting it sit for a couple minutes it passed. It took a total of about 6 mins to run.

I'm not sure what's going on with your PR though since it's taking 2 hrs with no output. Maybe try setting `--loglevel=debug` in `.travis.yml` to troubleshoot your PR?

**Comment by sebastian-luna-valero** [comment]
Thanks @daler. Trying that now:
https://travis-ci.org/bioconda/bioconda-recipes/builds/192735506

I have also found the following error locally:
```
[Jan 17 16:34:07] SOUT Extracting packages ...
[      COMPLETE      ]|##################################################| 100%                 |   0%
[Jan 17 16:35:23] SOUT Linking packages ...
[Jan 17 16:38:43] SERR /usr/local/bin/.gcc-post-link.sh: line 10: lsb_release: command not found
[Jan 17 16:38:43] SERR /usr/local/bin/.gcc-post-link.sh: line 49: ld: command not found
[wheel               ]|######################                     Couldn't locate crtXXX.o in default library search paths. You may not have it  at all. It is usually packaged in libc6-dev/glibc-devel packages. We will try  to locate crtXXX.o with system installed gcc...
[Jan 17 16:38:43] SOUT There is no /usr/bin/gcc
[Jan 17 16:38:43] SERR *** Can't install the gcc package unless your system has crtXXX.o. ***
[Jan 17 16:38:43] SERR Error: Error: post-link failed for: gcc-4.8.5-7
[gcc                 ]|#######################                           |  47%
[Jan 17 16:38:44] ERRO Task processing failed: Unexpected exit code [1] of container [5520cbd06317 step-5343e2eb09], container preserved
./involucro -v=3 -f /sebastian/i35/lib/python3.5/site-packages/galaxy_lib-16.10.9-py3.5.egg/galaxy/tools/deps/mulled/invfile.lua -set CHANNELS='bioconda,file://sebastian/i35/conda-bld,r,defaults,conda-forge' -set TEST='true' -set TARGETS='cgat-scripts-nosetests=0.0.2=py34r3.3.1_0' -set REPO='quay.io/biocontainers/cgat-scripts-nosetests:0.0.2--py34r3.3.1_0' -set BINDS='build/dist:/usr/local/,/sebastian/i35/conda-bld:/sebastian/i35/conda-bld' build-and-test

ERROR bioconda_utils.build:build(137): STDERR:
None
```
which has been reported before:
https://github.com/bioconda/bioconda-recipes/pull/2463
https://github.com/bioconda/bioconda-recipes/issues/3134

but it was not solved.

Not sure why is happening :(

**Comment by bgruening** [comment]
can you try to add libgcc or gcc as runtime dep?

**Comment by sebastian-luna-valero** [comment]
@bgruening thanks for merging:
https://github.com/bioconda/bioconda-recipes/pull/3491

So the solution was to replace `gcc` with `libgcc`. However, we do need `gcc` as a dependency for our metapackage.

Could we please discuss a bit more about the long-term solution to this problem? In order to use `gcc` as a dependency, we should either consider using the `conda metapackage` command as explained here:
http://conda.pydata.org/docs/commands/build/conda-metapackage.html

Although I am not sure how to incorporate that into the `bioconda` workflow, since no tests are allowed.

On the other hand, provided that `gcc` is a package in the `defaults` channel, we could also report this issue upstream to Continuum. Others have already done it before:
https://github.com/ContinuumIO/docker-images/issues/21
https://github.com/ContinuumIO/docker-images/issues/23

What do you think?

**Comment by sebastian-luna-valero** [comment]
Update:

Interestingly enough, when I remove both `gcc` and `libgcc` from the recipe, it does not work either:
https://travis-ci.org/bioconda/bioconda-recipes/builds/192755064

**Comment by bgruening** [comment]
Just to summarize, gcc as run-dep will crash, libgcc as run-dep works, no libgcc and no gcc will also crash, and what is with libgcc and gcc as run-deps?

**Comment by sebastian-luna-valero** [comment]
When you include both `gcc` and `libgcc`, the build is errored as well:
https://travis-ci.org/bioconda/bioconda-recipes/builds/193001033

**Comment by sebastian-luna-valero** [comment]
Hello both, 

Just to add further comments on this issue of `gcc` causing the build to hang if it is a requirement on the `run` section of the recipe, I recalled that in version 0.0.1 of the `cgat-scripts-nosetests` recipe this was not an problem. See PR here: 
https://github.com/bioconda/bioconda-recipes/pull/3278/files

and Travis output here:
https://travis-ci.org/bioconda/bioconda-recipes/jobs/185835542

I was wondering whether an update of the `gcc` package caused this problem.

I need to upload a couple of more meta-packages like this, and it would be nice to have `gcc` as a dependency in the `run` requirements, if possible.

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Also, for our reference, here is the error message:
```
pkgs/gcc-4.8.5-7/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.8.5/cc1: error while loading shared libraries: libcloog-isl.so.4: cannot open shared object file: No such file or directory
Installation failed: gcc is not able to compile a simple 'Hello, World' program.

LinkError: Link error: Error: post-link failed for: gcc-4.8.5-7 
```

**Comment by sebastian-luna-valero** [comment]
Sorry for the noise, I just wanted to add that you can get the error message above by just installing gcc on a conda environment as well:
```
$ conda install gcc
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment /sebastian/test-gcc:

The following NEW packages will be INSTALLED:

    cloog: 0.18.0-0             (soft-link)
    gcc:   4.8.5-7              (soft-link)
    gmp:   6.1.2-0  conda-forge (soft-link)
    isl:   0.12.2-0             (soft-link)
    mpc:   1.0.3-3  conda-forge (soft-link)
    mpfr:  3.1.5-0  conda-forge (soft-link)

Proceed ([y]/n)? 

Linking packages ...
/ifs/apps/conda-2017-01-27/pkgs/gcc-4.8.5-7/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.8.5/cc1: error while loading shared libraries: libcloog-isl.so.4: cannot open shared object file: No such file or directory                  |  83%
Installation failed: gcc is not able to compile a simple 'Hello, World' program.

LinkError: Link error: Error: post-link failed for: gcc-4.8.5-7 

$ conbda info
bash: conbda: command not found
(/sebastian/test-gcc) 
[Fri Jan 27 17:59:43] sebastian@cgat050:/sebastian
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.5.3.final.0
       requests version : 2.12.5
       root environment : /ifs/apps/conda-2017-01-27  (writable)
    default environment : /sebastian/test-gcc
       envs directories : /ifs/apps/conda-2017-01-27/envs
          package cache : /ifs/apps/conda-2017-01-27/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
            config file : /ifs/home/sebastian/.condarc
           offline mode : False

```

**Comment by sebastian-luna-valero** [comment]
Submitted new issue to Continuum:
https://github.com/ContinuumIO/anaconda-issues/issues/1392

**Comment by sebastian-luna-valero** [comment]
@bioconda/core this the response from Continuum:

> You need to remove `conda-forge` from your list of channels, `conda defaults` and `conda forge` are not Binary Compatible

I thought we all were on the same boat?

**Comment by johanneskoester** [comment]
Looks like this might be an issue of your channel priorities. Here, we have a higher priority for defaults than conda-forge. This way, you get gcc with all its deps from defaults and it should work. However, you should maybe bring that issue to the attention of the conda-forge guys, because such a binary incompatibility is certainly not intended.

**Comment by johanneskoester** [comment]
The cause might be the recent update to gcc 4.8.5 (4.8.2 before) in defaults. So I guess there is some missing pinning in the packages coming from conda forge.

**Comment by sebastian-luna-valero** [comment]
Thanks @johanneskoester 

You're right, I did not have the correct channel order locally but I got the same problem with Travis tests for bioconda packages and that should not be the case as the setup would have correctly configured the channel order, am I right?
https://github.com/bioconda/bioconda-recipes/blob/master/scripts/travis-setup.sh#L31

I will ping back to conda-forge guys about the issue.

**Comment by sebastian-luna-valero** [comment]
Indeed, after having the correct order I can still experience the same issue.
```
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /ifs/apps/conda-2017-01-30  (writable)
    default environment : /ifs/apps/conda-2017-01-30
       envs directories : /ifs/apps/conda-2017-01-30/envs
          package cache : /ifs/apps/conda-2017-01-30/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /ifs/home/sebastian/.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.5.2 Linux/2.6.32-642.11.1.el6.x86_64 Scientific Linux/6.8 glibc/2.12
                UID:GID : 1362:1000

$ conda create -p /sebastian/test-gcc gcc    
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /sebastian/test-gcc:

The following NEW packages will be INSTALLED:

    cloog: 0.18.0-0
    gcc:   4.8.5-7 
    gmp:   6.1.0-0 
    isl:   0.12.2-0
    mpc:   1.0.3-0 
    mpfr:  3.1.5-0 

Proceed ([y]/n)? 

gmp-6.1.0-0.ta 100% |#############################################################################################################################################################################################| Time: 0:00:00   7.12 MB/s
isl-0.12.2-0.t 100% |#############################################################################################################################################################################################| Time: 0:00:00   9.31 MB/s
mpfr-3.1.5-0.t 100% |#############################################################################################################################################################################################| Time: 0:00:00  16.58 MB/s
cloog-0.18.0-0 100% |#############################################################################################################################################################################################| Time: 0:00:00  13.09 MB/s
mpc-1.0.3-0.ta 100% |#############################################################################################################################################################################################| Time: 0:00:00  13.15 MB/s
gcc-4.8.5-7.ta 100% |#############################################################################################################################################################################################| Time: 0:00:02  31.04 MB/s
/ifs/apps/conda-2017-01-30/pkgs/gcc-4.8.5-7/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.8.5/cc1: error while loading shared libraries: libcloog-isl.so.4: cannot open shared object file: No such file or directory
Installation failed: gcc is not able to compile a simple 'Hello, World' program.
ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'defaults::gcc-4.8.5-7'.
LinkError: Link error: Error: post-link failed for: defaults::gcc-4.8.5-7 

Attempting to roll back.

LinkError: Link error: Error: post-link failed for: defaults::gcc-4.8.5-7 

```

The solution provided by Continuum is to remove `conda-forge` (?). See:
https://github.com/ContinuumIO/anaconda-issues/issues/1392

By the way, I don't seem to find a gcc feedstock on `conda-forge`, am I right @jakirkham? Only this thread:
https://github.com/conda-forge/staged-recipes/issues/436

Best regards,
Sebastian

**Comment by johanneskoester** [comment]
OK but that looks like the error occurs with the defaults packages as well. The are no conda-forge packages pulled any more. Removing conda-forge does not help, does it?

**Comment by sebastian-luna-valero** [comment]
Indeed, removing conda-forge does not help either and I have reported that already. Thanks!

On the other hand, do you mean that `bioconda` is now independent of `conda-forge`? I can see how the travis setup still uses it:
https://github.com/bioconda/bioconda-recipes/blob/master/scripts/travis-setup.sh#L31
https://github.com/bioconda/bioconda-recipes/blob/master/config.yml#L15

and is also reference on the documentation:
https://bioconda.github.io/contribute-a-recipe.html

**Comment by johanneskoester** [comment]
On the contrary. We heavily depend on conda forge and strive to move all general purpose packages there. We also lead the effort to port the R channel to conda-forge.

**Comment by sebastian-luna-valero** [comment]
Sorry, I was confused by your comment:

> The are no conda-forge packages pulled any more.

**Comment by sebastian-luna-valero** [comment]
Hello @bioconda/core 

The outcome of our discussion over:
https://github.com/ContinuumIO/anaconda-issues/issues/1392

to solve the problem when installing `gcc` from the `defaults` channel:
```
LinkError: Link error: Error: post-link failed for: defaults::gcc-4.8.5-7 
```

was to use the following configuration in the `.condarc` file:
```
allow_softlinks: False

channels:
  - bioconda
  - r
  - defaults
  - conda-forge
```

Is this something that should be reflected on bioconda's build system?

Please let me know your thoughts.

Best regards,
Sebastian

**Comment by epruesse** [comment]
outdated
