### ISSUE TITLE
@rvalieris as a Bioconda core member

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#3504]
I would like to propose @rvalieris as a @bioconda/core member.

He has provided several high quality PRs. Especially some that refactor or improve our package structure. Even more important, he helped a lot with reviewing the PRs of others.

@bioconda/core please vote!

**Comment by bgruening** [comment]
:tada:

**Comment by chapmanb** [comment]
I'm +1 for all these recommendations. It's so great to have more community members contributing.

**Comment by jerowe** [comment]
+1 !

**Comment by johanneskoester** [comment]
Well then, welcome in the core team @rvalieris!

**Comment by rvalieris** [comment]
thanks everyone, I really like the bioconda project, and I enjoy contributing to it.
