### ISSUE TITLE
MUSIC: samtools version and libcrypto

### ISSUE THREAD

**Issue by darked89** [bioconda/bioconda-recipes#35085]
Hello,

I did:

```
conda create --name music
conda activate music
conda install -c bioconda music 
```

and ended up with a broken samtools 1.7 install:
```
samtools --version 
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

I could not find any hard-wired samtools version in the recipe for MUSIC. 

Hope it helps,

Darek Kedra

**Comment by bgruening** [comment]
Can you please try -c conda-forge -c bioconda or https://bioconda.github.io/user/install.html#set-up-channels

**Comment by darked89** [comment]
Thanks a lot:

```
conda install -c conda-forge -c bioconda music
```

installed a working executable of samtools 1.15.1 and MUSIC

DK
