### ISSUE TITLE
Bioconductor Release 3.15

### ISSUE THREAD

**Issue by mfansler** [bioconda/bioconda-recipes#35116]
Are there any plans to bulk build the latest Bioconductor release?

**Comment by mjsteinbaugh** [comment]
Now that R 4.2 is up on conda-forge, we should be able to make this happen. @dpryan79 any way I can help update the recipes?

**Comment by dpryan79** [comment]
@mjsteinbaugh The next step is to convince conda-forge to run the CRAN migration, since we need that (more or less) finished as the last step before we can start. I just merged in R 4.2.1 on conda-forge, so I'll make a PR on conda-forge-pinning and request a migration.

**Comment by BEFH** [comment]
Is there any update on this? It would be helpful to know what the blockers are (presumably on the conda-forge side) so that we can help out if needed.

**Comment by dpryan79** [comment]
Yes! They started their migration last night (EU time).

**Comment by BEFH** [comment]
AMAZING! Thanks for letting me know. This will allow us to comment out so many docker containers in our workflows.

**Comment by mjsteinbaugh** [comment]
@dpryan79 Following up on this, should we wait and just build Bioconductor 3.16 instead? It is scheduled for release on November 2nd.

**Comment by mfansler** [comment]
I'd vote to build both. Bioconductor is too core to bioinformatics users to have a gap in versions. 

The Conda Forge R 4.2 migration is mostly done, BTW.

**Comment by dpryan79** [comment]
We'll skip over 3.15. It takes about 2 weeks to build all ~3000 Bioconductor packages and by then they will have been deprecated. At this point there's no real gain to burning many hundreds of hours of CI resources.

**Comment by kullrich** [comment]
One question, if there would be a stable bulk build on all bioconductor release packages.
All `bioconductor-XXX` bioconda packages would be redundant and one should think about to remove this kind of R-package branch from bioconda?

**Comment by kullrich** [comment]
I am just on the way to include my R-Bioconductor package to bioconda, mainly to make it accessible to Galaxy afterwards.
If there is a stable bulk bioconductor biconda release, at least this type of integration should be covered to deal with downstream pipeline integration.

**Comment by bgruening** [comment]
What is the name of your package?

**Comment by kullrich** [comment]
Hi, it is `MSA2dist` the problem for the Bioconductor `release-3.16` so far is that the most used package/dependency `Biostrings`, so far is failing for `OSX`. With this issue using an `OSX` as the working OS, it is not possible to use the common approach (https://bioconda.github.io/contributor/guidelines.html) to include any other Bioconductor package that depends on `Biostrings`.

**Comment by kullrich** [comment]
see e.g.
https://github.com/bioconda/bioconda-recipes/issues/37827
https://github.com/bioconda/bioconda-recipes/issues/37535
https://github.com/bioconda/bioconda-recipes/issues/37224

**Comment by bgruening** [comment]
OSX builds to take usually longer (we have simply more Linux capacity) than Linux builds. And the current 2.66 Linux build is just a day old, so I would be patient.
I assume that the current bulk build of all packages will still take a week until most packages are build, so if you can wait a week, we can look at those issues again.

**Comment by bgruening** [comment]
Also keep an eye on https://anaconda.org/bioconda where you see the latest packages arriving.

**Comment by amizeranschi** [comment]
@bgruening is the release of Bioconductor 3.16 expected to break packages for older releases (such as 3.14 and R 4.1)? Because I'm running into errors with packages that were installing fine a couple of days ago: https://github.com/bioconda/bioconda-recipes/issues/37906

The irony is that the package version that I'm referencing there, `bioconductor-org.hs.eg.db-3.14.0-r41hdfd78af_1`, was released a couple of months ago to fix these exact same errors with `post-link.sh`, which at that time were happening with the previous iteration of the package (`bioconductor-org.hs.eg.db-3.14.0-r41hdfd78af_0`), which was released one year ago.

https://anaconda.org/bioconda/bioconductor-org.hs.eg.db/files

**Comment by dpryan79** [comment]
@amizeranschi The new packages won't affect old ones. There's something very strange going on here.
