### ISSUE TITLE
Helping with maintenance

### ISSUE THREAD

**Issue by mfansler** [bioconda/bioconda-recipes#35123]
I would like to help with general upkeep on the repository. However, my review approvals don't seem to trigger PR progression (e.g., https://github.com/bioconda/bioconda-recipes/pull/35072). Is there a process to apply for upgraded permissions?

Previous discussions (e.g., #595 #2327) don't seem to arrive at definite guidelines and I was unable to find relevant sections in the documentation.

@cbrueffer @bgruening you appear to have such permissions, and we've crossed paths on Conda Forge recipes - could you advise?

**Comment by bgruening** [comment]
@mfansler thanks a lot for your offer I invited you to the organization.
