### ISSUE TITLE
@druvus as bioconda/core member

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#3520]
I'd like to nominate @druvus for the core team -- he's had a steady stream of high-quailty PRs (in fact, he is the 4th-highest contributor in terms of commits), contributes all sorts of helpful fixes, and is active in helping new contributors get up to speed.

@bioconda/core votes please?

**Comment by johanneskoester** [comment]
Great idea!

**Comment by bgruening** [comment]
Wonderful!

**Comment by jerowe** [comment]
Great! ;-)

**Comment by daler** [comment]
Great, glad to have you on the core team @druvus!

**Comment by druvus** [comment]
thanks! Happy to join and continue to contribute. Saved a lot of time and headaches since the bcbio people got me aware of this project.
