### ISSUE TITLE
BiocondaBot auto-updater not creating PRs

### ISSUE THREAD

**Issue by victorlin** [bioconda/bioconda-recipes#35414]
[Filtering for PRs from BiocondaBot](https://github.com/bioconda/bioconda-recipes/pulls?q=is%3Apr+author%3ABiocondaBot) shows that the last PR was created on 2022-06-15 (as of submitting this issue).

There has been at least one PyPI update since then: the `augur` recipe (`nextstrain-augur` on PyPI) had a [release of version 16.0.0](https://pypi.org/project/nextstrain-augur/16.0.0/) on 2022-06-16, yet there hasn't been an auto-bump PR.

**Comment by daler** [comment]
@victorlin thanks for reporting. This was my fault in removing the circle-ci tests last week when overhauling the docs. Clearly we need some better docs detailing where all the moving parts are running, to avoid such issues in the future! I'm working on that. And of course working on fixing the autobump which should be back up soon and working through the backlog.

**Comment by daler** [comment]
OK, see at least the detected [augur autobump PR](https://github.com/bioconda/bioconda-recipes/pull/35430).

I manually triggered a round of updates to start getting through the backlog, but FYI the autobump [*should* run every hour](https://github.com/bioconda/bioconda-utils/blob/master/.circleci/config.yml#L209). Though if there are a lot of updates to get through or it hits too many requests it may time out and then pick up on the next hour.

I'll keep this open until I confirm that circleci has run a few rounds of autobumps.

**Comment by telatin** [comment]
Looks fixed from the modules I updated on CPAN recently, thanks :)

**Comment by daler** [comment]
Confirmed autobump is regularly running hourly now; closing.

**Comment by victorlin** [comment]
@daler thank you for fixing this!
