### ISSUE TITLE
Built Package Cannot Be Found in Azure Pipeline

### ISSUE THREAD

**Issue by Colelyman** [bioconda/bioconda-recipes#35536]
Has anyone experienced when the CI fails with the following error: 
```
ERROR:bioconda_utils.build:BUILD FAILED: the built package /usr/share/miniconda/envs/bioconda/conda-bld/linux-64/crispresso2-2.2.9-py39h5094d80_0.tar.bz2 cannot be found
```

This is the second time that I have encountered this, both have been with the `crispresso2` recipe and both have been during autobumps. The most recent time that I encountered this is in #35491 (with accompanying log from Azure with the error, https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=17987&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572)

When I search for `h5094d80` the only occurrences are at the end of the log file when it says that it can't be found. But you can see that other packages are being built (but they obviously have a different hash). Anyone have any ideas on how to debug this? I don't think that this is recipe specific to `crispresso2`, but if it is I am happy to change whatever needs to.

When I previously encountered this (#34903) I "resolved" it by bumping up the build number, committing that, having the CI lint fail, decrementing the build number, committing that, and having the CI resolve.

**Comment by siebrenf** [comment]
I had the same error with an unstable recipe. In both cases the package installs and the test work (I can see the `--help` menu in the logs), but then the tarball cannot be found in the mulled_container. I fixed this for my package by tweaking the recipe. 

Your recipe is very different from mine, but here are some things you could try to tweak:
- your `host` section seems waaay to big. At most you'll need `python`, `setuptools`, `cython` and `numpy`. (Bioconda actually packages python, cython and numpy together [under the hood](https://github.com/bioconda/bioconda-utils/blob/e5e82b2c4ea39ce423d1effe1d84ca2477be3952/bioconda_utils/bioconda_utils-conda_build_config.yaml#L35), so you could even just use the first two)
- you could perhaps tweak your `build.sh`. 
  - For example: [snakemake](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/snakemake/meta.yaml) also uses setuptools, but actually uses pip for the `install` function. Not sure if this works for you though! To replicate it, add `pip` to the `host` sections, add `script: python -m pip install --no-deps --ignore-installed .` to the `build` section, and remove the `build.sh` file.
- not sure if this matters, but the `python` versions don't match between `host` and `run` sections.
- if neither of these worked, then your package might have an additional dependency that is only noticed when using the minimal container. 

good luck :)

**Comment by Colelyman** [comment]
Hartelijk bedankt voor jouw hulp @siebrenf, je hebt me uren bespaard!
