### ISSUE TITLE
Apple silicon arm support

### ISSUE THREAD

**Issue by shi-scala** [bioconda/bioconda-recipes#35579]
Hi,

Are there plans to support Apple's arm silicon processors?
I'm an avid bioconda user however a lot of osx-arm64 packages are missing.

Cheers

**Comment by liamjwang** [comment]
I have the same question.

I saw that the [bioconda docs](https://bioconda.github.io/) say:
`NOTE: Bioconda supports only 64-bit Linux and macOS`

If I want to add osx-arm64 support to a recipe, would it be okay to submit a duplicate recipe to conda-forge?

**Comment by OneCricketeer** [comment]
Duplicates #23454 + https://github.com/bioconda/bioconda-utils/issues/706

**Comment by corneliusroemer** [comment]
Closed as duplicates
