### ISSUE TITLE
matplotlib-venn duplicated package

### ISSUE THREAD

**Issue by mmiladi** [bioconda/bioconda-recipes#3583]
There is a matplotlib-venn conda package under conda-forge. Probably we can think of moving its bioconda recipe to bioconda-legacy?

https://github.com/bioconda/bioconda-recipes/tree/f5eb63e30a76fd13c28663786d219c9f7750267c/recipes/matplotlib-venn

**Comment by bgruening** [comment]
Can you check if it is the exact same version and create a PR to remove the recipe(s) from git?
I will move it over then.

**Comment by mmiladi** [comment]
Well no it is not exactly same version:
```
    bioconda/matplotlib-venn  |   0.11.1 | conda           | linux-64, osx-64
                                          : Functions for plotting area-proportional two- and three-way Venn diagrams in matplotlib.
     conda-forge/matplotlib-venn |   0.11.4 | conda           | linux-64, win-32, win-64, osx-64
                                          : Functions for plotting area-proportional two- and three-way Venn diagrams in matplotlib
```

**Comment by bgruening** [comment]
@bioconda/core what do you think?

**Comment by kyleabeauchamp** [comment]
SGTM, but you and @johanneskoester  are the authors so up to you.

**Comment by johanneskoester** [comment]
I'm fine with removing the recipe, as long as the packaged version stays available on bioconda, i.e. we don't delete the package from the channel.

**Comment by bgruening** [comment]
But this means this package will always be favoured instead of the conda-forge one, right? So if someone wants to have a newer version we need to specify >=.

**Comment by johanneskoester** [comment]
You are right, I forgot about that. In that case, let's rather break now than later and move the package to legacy.

**Comment by mmiladi** [comment]
Thanks for your feedbacks. This PR https://github.com/bioconda/bioconda-recipes/pull/3598 removes the recipe. However I don't know how/where the legacy channel is handled.

**Comment by bgruening** [comment]
Done.
