### ISSUE TITLE
Bioconda Package Version Information

### ISSUE THREAD

**Issue by MichWeb75** [bioconda/bioconda-recipes#36244]
Hi,
I am wondering why bioconda repository version and bioconda website announced version of a package is different. For example I just installed

  + snakemake                                   7.12.0  hdfd78af_0           bioconda/noarch          Cached

but https://bioconda.github.io/recipes/snakemake/README.html?highlight=snakemake#package-package%20&#x27;snakemake&#x27;
announces latest version 7.9.0-0

Best, Michael

**Comment by daler** [comment]
@MichWeb75 the automatic scheduled docs generation was not working, but this should now be fixed, and e.g. https://bioconda.github.io/recipes/snakemake/README.html now correctly shows 7.14 as the latest.
