### ISSUE TITLE
integrate cargo-port URLs in the bioconductor skeleton builder

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#3638]
We have currently 2000 tarballs backuped on cargo-port. So I think it is a reliable service. We do had a few downtimes but I think it is overall working.

What do you think about adding the cargo-port URL by default to the meta.yaml as second or third link?
A link typically looks like this: https://depot.galaxyproject.org/software/bioconductor-affyio/bioconductor-affyio_1.42.0_src_all.tar.gz

I hope that rebuilding r-packages will be much more easier with this change in place.
ping @bioconda/r

**Comment by johanneskoester** [comment]
Yes, let's do that!

**Comment by druvus** [comment]
Good idea!

**Comment by daler** [comment]
#3713 adds this. If I remember, bioaRchive tarball md5sums differed from bioconductor tarball md5sums. So if the url the recipe is built from one url and the package is built from another, it'll fail from md5 mismatch. But cargo-port mirrors the top url directly, right? So should we remove bioaRchive urls to avoid such md5 issues?
