### ISSUE TITLE
Bioconda website not showing recent recipe updates

### ISSUE THREAD

**Issue by jlumpe** [bioconda/bioconda-recipes#36527]
I've noticed that bioconda.github.io has not been rebuilt in 18 days: https://github.com/bioconda/bioconda.github.io/actions. Is there a reason for that?

**Comment by daler** [comment]
@jlumpe @telatin this is now fixed, migrated from circleci over to Actions, and you can see a successful scheduled build, https://github.com/bioconda/bioconda-utils/actions/runs/2988494722.

**Comment by jlumpe** [comment]
Thanks!
