### ISSUE TITLE
building conda packages against pysam 0.9.1 and conda-build > 2.0

### ISSUE THREAD

**Issue by adamlabadorf** [bioconda/bioconda-recipes#3671]
I am trying to build a package that has pysam as a dependency. conda build reports the following when attempting to use the latest bioconda pysam version (0.9.1-py35_1) :
```
ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'bioconda::pysam-0.9.1-py35_1'.
PaddingError: Placeholder of length '80' too short in package /projectnb/bubhub/conda_root/conda-bld/rseqc_1485401195820/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.5/site-packages/pysam/calignedsegment.cpython-35m-x86_64-linux-gnu.so.
The package must be rebuilt with conda-build > 2.0.


Attempting to roll back.
```
My package does use the package successfully after rolling back, but it might be helpful to rebuild the pysam packages using the most recent version of conda build to avoid these issues.  Here is my conda info:
```
Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.1.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
```

**Comment by acaprez** [comment]
Are you sure you're getting the newest version of `pysam`?  The latest version is 0.9.1.4-1 (https://anaconda.org/bioconda/pysam/files).  Looking at the package metadata, those were all built using `conda-build` 2.0.7.  Using `conda inspect prefix-lengths` on the tarballs confirms the prefix length is 255.

**Comment by adamlabadorf** [comment]
You're right, upon closer inspection of my meta.yaml file I was pinning the version to 0.9.1, not 0.9.1.4-1. When I build with 0.9.1.4 I don't get the message, consistent with what you see. When I force version 0.9.1 I still get the issue. Does bioconda rebuild older package versions to update the prefix length? Since I don't need 0.9.1 for anything this issue is technically resolved, but others might legitimately encounter this in the future.

**Comment by daler** [comment]
In general bioconda does not rebuild older packages using new infrastructure. The mechanism for this would be to add a new subdirectory for the old version number and bump the build number to trigger a rebuild. Looks like pysam already has a 0.9.1 subdir, so I bumped the build number. Let's see how #3710 goes.

**Comment by daler** [comment]
@adamlabadorf can you give 0.9.1 a try to see if it works now?

**Comment by sebastian-luna-valero** [comment]
Also, pysam 0.10.0 is coming:
https://github.com/bioconda/bioconda-recipes/pull/3724

**Comment by adamlabadorf** [comment]
@daler I no longer get the rollback warning when building against 0.9.1-py35_2.  Looks like it worked.
