### ISSUE TITLE
GTDBTK bad dependency version for fastani.

### ISSUE THREAD

**Issue by nlvw** [bioconda/bioconda-recipes#36934]
https://github.com/bioconda/bioconda-recipes/blob/c90d3092a0119a3cd39af0fe684eda2bd730376a/recipes/gtdbtk/meta.yaml#L24

The current setting of only version 1.3 conflicts with many other packages in bioconda and does not reflect the official documentation from GTDB-TK which states a version >=1.32 https://ecogenomics.github.io/GTDBTk/installing/index.html?highlight=fastani#third-party-software

**Comment by peterjc** [comment]
Fixed in #39388 although pinned to fastANI 1.32 specifically
