### ISSUE TITLE
Conda noarch packages

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#3701]
Just to track that we should at some point port a few our packages to noarch packages to save space:

https://www.continuum.io/blog/developer-blog/condas-new-noarch-packages

**Comment by hainm** [comment]
@bgruening When will "some point" happen? :D

**Comment by hainm** [comment]
Some users want to use `nglview` with python 3.6 but bioconda has not supported yet. `noarch` is pretty good option for nglview (just purely python and javascript).

**Comment by dpryan79** [comment]
Closing, since we do this now.
