### ISSUE TITLE
Tighter integration with HPC platforms

### ISSUE THREAD

**Issue by jerowe** [bioconda/bioconda-recipes#3708]
@bioconda/core

What do you all think of integrating with an HPC module build system? I was initially drawn to conda because it is perfect for HPC systems. I believe many of our users are also using  HPC systems.  I mostly build bioconda packages to stick into a module somewhere. ;-)

What would people think of, in the way that we have docker images per package, also having a module config per package? I like Easybuild, and at least 1 person (besides me) has contributed a bioconda package as a [module config](https://github.com/hpcugent/easybuild-easyconfigs/search?utf8=%E2%9C%93&q=bioconda).

If this gets a 'yay', what would be the best way to go about it? Have an additional repo of configs? I'm not sure what other options would be, but please chime in.

**Comment by daler** [comment]
Based on the examples you show, it looks like a local script could autogenerate an `.eb` file from a conda recipe since they share much of the same information. So on your HPC system you could run something like `bioconda-utils easybuild uri://to/recipe` to get a config. If there are additional bits of info that would be required to build a config (`toolchain`? `moduleclass`?), maybe they could be added as additional entries under the `extra` section of meta.yaml files. That way you could gain access to a large number of recipes with minimal maintenance overhead.

**Comment by bgruening** [comment]
@jerowe more or less the same question from me. Can we generate these files on the fly with some nice tools, or to we pre-generate them and store them somewhere?

**Comment by jerowe** [comment]
@bgruening , the files could definetely be generated on the fly. All the information we need is in the recipes meta.yaml.

Thanks for the comment, @daler. I think all the recipes would be have 'bio' as a module class. Toolchain is always dummy as we  aren't using any of EB compilers.

**Comment by bgruening** [comment]
@jerowe in this case I would +1 a PR against bioconda-utils to support this conversion.

**Comment by holtgrewe** [comment]
Dear all, our group has also looked into this and the main issue that we have seen so far is the relocation feature of conda (e.g., replacing the hashbang in scripts with placeholders). @jerowe do you see a solution to this?

**Comment by jerowe** [comment]
Hi Manual,

Depends on exactly what you mean. ;-)

I see perl/python scripts being a big culprit in this regard. There will be
many scripts with #!/usr/bin/env perl|python or even
#!/usr/bin/perl|python. If you are using proper distribution tools for
these (Module::Build for perl, setuptools for python) this is quite easy to
'fix'. I make an effort to check all the packages I contribute for
particular hashbang lines, but I'm sure I don't catch them all.

If you mean when conda build creates the long prefix, that has generally
been fine. We have been using conda and bioconda packages in production on
our HPC system for over a year now and have not had any difficulties with
this, with the small exception that sometimes if you create an conda
environment using the -p option earlier releases of conda do not like you
to install them to too long of a path name.

I got a bit sidetracked the last few weeks, but I was able to build
easybuild*, lmod, and environment modules as conda packages and deploy them
both on a docker sanbox and on our HPC. I am hoping to get back to this
issue in the upcoming weeks.

If you're interested in a sandbox we have built one here:
https://quay.io/repository/nyuad_cgsb/easybuild
Docker file for reference:
https://github.com/nyuad-cgsb/nyuad-docker/blob/master/easybuild/Dockerfile

**Comment by holtgrewe** [comment]
@jerowe OK, I think that also binaries contain long placeholders that are then patched. Correct me if I'm wrong, but how do you handle this?

**Comment by jerowe** [comment]
Conda build handles this. I've never gotten into the nitty gritty details
of it myself, but here is the document:

http://conda-test.pydata.org/docs/build.html#making-packages-relocatable

I know there are a few recipes that use the binary_prefix opt. Let me see
if I can look into them for you.

**Comment by holtgrewe** [comment]
OK, how is your approach overall? You create a conda environment and then load this through environment modules?

What we were trying to do is to convert "raw" conda packages to environment modules and this is where we failed.

**Comment by johanneskoester** [comment]
Maybe I missed that, but can somebody enlighten me on what would be the advantage of combining modules with conda? Isn't the modules system just another way of what conda environments do?
Don't get me wrong, I'm fine with any work on this, I just want to understand the motivation.

**Comment by jerowe** [comment]
@johanneskoester , you bring up an important point. 

Running `source activate my_software` is basically the same as `module load my_software`. But, I work on HPC, and they use modules. It is confusing to users to give them two methods to do the same thing, so all our modules are loaded transparently with modules.

Also, as far as I know it is not possible to source activate multiple environments. It is possible to layer modules using environment variables (appending/prepending PYTHONPATH/PERL5LIB/configs/whatever). So I would say environment modules gives you a bit more control over the environment, but not much.

What we do is `module load my_software`, but behind that is a conda environment.

**Comment by johanneskoester** [comment]
Just tell, them to use Snakemake and they don't need either of the two ;-). Just kidding. Ok, that makes sense somehow, but you can't load two modules with conflicting version of the same package either, right (e.g. Python 2 and 3)?
So, isn't `module load` rather equivalent to `conda install`, and conda environments would rather be equivalent to a set of module load commands?

**Comment by jerowe** [comment]
We actually use something very like Snakemake. ;-) But I really like snakemake. It has lots of cool features. I got into it a few years ago and it was the first workflow runner I ever saw that I considered sane. Some of the others made me sit around and bang my head against a wall. ;-)

I would say `module load` is nearly equivalent to `source activate`. 

You could two load modules, just the most recently loaded would override the previous. Python isn't such a big issue because they have the executables (sort of) named python2 and python3. I actually discourage loading multiple modules. We have spent a lot of time over the last year implementing 'analysis modules', where a single module usually has everything you need for a particular analysis (variant detection, rnaseq, etc).

**Comment by jerowe** [comment]
@holtgrewe , we use easybuild to deploy modules that are underlying conda environments. We are very open to collaborating and I can give you as much information as you like, but you should let me know the level you wish for so I don't overload you with stuff. ;-)

**Comment by holtgrewe** [comment]
@johanneskoester Yes, I'd also say that `module load` and `conda install` are equivalent. However, `conda install` performs patching of files whereas `module load` only updates environment variables.

Or at least so it appeared to us before we gave up marrying those two.

What @jerowe is proposing is to make `module load` equivalent to activating an environment.

@jerowe I think the original idea is to have atomic modules that you can then mix and match together. IMO the reason you have to discourage enabling multiple ones comes from the conflicts arising from large modules.

We will probably discontinuing the usage of environment modules (and the fugly easybuild process) in favour of bioconda. We might provide users with up-to-date GCC/etc. versions through environment modules but the user groups who do software compilation and Bioinformatics are almost completely separate in our environment.

**Comment by jerowe** [comment]
@holtgrewe , we have a similar setup. My users tend to be scientists, not software engineers. This drives quite a bit of our infrastructure design. We mostly go with larger analysis modules in order to 'help' our users and prevent errors in doing 20 separate module load commands in a single analysis. 

IMO, modules are a bit more flexible than conda envs, but there are a few talks going on in conda proper about catching up.

You can usually do up to date just about everything through bioconda and partnering channels, but if you are looking into module deployment systems I would strongly recommend checking out easybuild. Easybuild has functionality to deploy a module either from a single conda package or a conda env (remote of local). Additionally, it will take care of your file structure, directory permissions, caching information about your builds, etc etc. I find it very, very useful to have an additional software taking care of the deployment of software.

If you wanted to look at it from a layering perspective our setup looks like this:

1. Software is built in conda channels.
2. Software stacks (analysis modules - variant detection, rnaseq, etc) are configured using conda-env.
3. Software stacks are deployed on the HPC using easybuild.

Inbetween 2 and there is a bit of building things like documentation, man pages, making sure we don't have any conflicting versions, etc, but for the most part our functionality is taken care of by conda and easybuild. ;-)

**Comment by jerowe** [comment]
This has been a really interesting conversation. I'm always interested in the infrastructure setup of other bioinformatics institutes! Feel free to tell me more. ;-)

**Comment by 0xAF1F** [comment]
A similar ticket was filed on the conda repository in 2014: https://github.com/conda/conda/issues/1037

**Comment by jerowe** [comment]
Personally, I think the 'activate' script of conda should be replaced with modules, but I'm also perfectly happy to just create configuration files for bootstrapping modules from conda packages.

I know I've left this ticket open for awhile. I have a habit of taking on too many projects with not enough me, but as the academic year winds down I will be getting back into the conda space more. ;-)

**Comment by bgruening** [comment]
@jerowe what about adding this functionality as part of the mulled-builds tools. I added recently Singularity builds and generating a module file seems like a great next step to me. We can then push the files to a public  storage as much as I do with Singularity images.

**Comment by jerowe** [comment]
I was looking into the code for the mulled build tools. I am traveling atm,
but I do want to get back to this. I keep getting asked for it.

I saw the singularly issue! That's amazing! Many hpc platforms won't allow
docker, but many will allow singularity so yay!

**Comment by bgruening** [comment]
ping @chrisbarnettster

**Comment by bgruening** [comment]
@jerowe @holtgrewe are you still planning to work on this?

**Comment by holtgrewe** [comment]
@bgruening we've abandoned easybuild completely in favour of conda

**Comment by jerowe** [comment]
Nah let's close this out. It's still on the wishlist, but not necessarily on the actual attainable wishlist.

**Comment by audreystott** [comment]
Hi Jillian
I was referred to this conversation after speaking about a module-based tool that uses containers. Have you heard of Singularity-HPC? It has a registry that includes (and continues to include latest versions of) all of biocontainers, which are based of bioconda. With that, you can simply load the container as a module. The repo can be found here: https://github.com/singularityhub/singularity-hpc. Feel free to contact to chat more if you like!
Audrey
