### ISSUE TITLE
Program missing from RSEM package

### ISSUE THREAD

**Issue by rwanwork** [bioconda/bioconda-recipes#3709]
When looking for differentially expressed isoforms according to the instructions given [here](https://github.com/bli25ucb/RSEM_tutorial), the program rsem-generate-ngvector is called.  This in turn calls rsem-for-ebseq-calculate-clustering-info, which isn't installed by either versions 1.12.0, 1.14.0 of the bioconductor-ebseq package.  (As far as I can tell...)

A quick fix is to download the latest RSEM source and in the EBSeq/ directory, do a "make rsem-for-ebseq-calculate-clustering-info".  Unfortunately, I'm still new to conda and don't know how to turn this into a recipe...

**Comment by daler** [comment]
It may be that it just needs to be explicitly added to the list of executables to copy over (it's missing from [here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/rsem/build.sh#L9)). @jerowe, @percyfal looks like you had originally added this recipe, any insights?

**Comment by rvalieris** [comment]
yeah I think it was just an oversight, I opened a pull request to add rsem-for-ebseq-calculate-clustering-info

it there any other binary you noticed missing from the rsem package ?

**Comment by rwanwork** [comment]
Sorry, missed your message a day earlier due to several things happening at once today.  Though I can't say I've used all of the features of rsem yet, so far, no other binary was missing.  Thank you very much for the bug fix and for looking after the package -- it's been very useful!

**Comment by rvalieris** [comment]
no worries, I am glad I could help :)
