### ISSUE TITLE
StrainGE package only built for Python 3.7

### ISSUE THREAD

**Issue by lrvdijk** [bioconda/bioconda-recipes#37107]
Hi,

I noticed that my StrainGE package has very restrictive Python version requirements (python>=3.7, <3.8a0). Could anyone explain why that's the case? I haven't explicitly set those requirements.

Bioconda page: https://bioconda.github.io/recipes/strainge/README.html
Recipe: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/strainge/meta.yaml

Thanks!

**Comment by siebrenf** [comment]
It's on the blacklist so no new builds are being made. I've created PR #37237 to attempt a fix. Feel free to make changes if I was too rough with removing `host` requirements!
