### ISSUE TITLE
Help dealing with - Error: package or namespace load failed for ‘GenomeInfoDb’; there is no package called ‘GenomeInfoDbData

### ISSUE THREAD

**Issue by chancharikmitra** [bioconda/bioconda-recipes#37224]
I am having this issue of my jupyter notebook not being able to find the GenomeInfoDbData package even though it is already installed in my conda environment. Note: I am trying to use this package as part of the SpatialExperiment library. 
Anytime I try to install GenomeInfoDb or GenomeInfoDbData, conda tells me the package is already installed, and I have already tried `conda clean --all`. I would appreciate any help in fixing the issue.

I first posted this issue on the GenomeInfoDbData repo, where it was determined that this was most definitely a conda/bioconda issue. You can refer to it here (quite short): [https://github.com/Bioconductor/GenomeInfoDb/issues/42](url)

Conda Version: 4.14.0
.condarc file:

> channels:
>   - bioconda
>   - conda-forge
>   - defaults
> channel_priority: true

Running locally on macOS 11.6
Environment Dependencies **(you will find that GenomeInfoDb/Data are both there):**
[requirements.txt](https://github.com/Bioconductor/GenomeInfoDb/files/9668002/requirements.txt)

Error Readout when running library(SpatialExperiment) in a jupyter notebook (I included it all just in case):

`Loading required package: SingleCellExperiment

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats

Attaching package: ‘MatrixGenerics’

The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars

Loading required package: GenomicRanges

Loading required package: stats4

Loading required package: BiocGenerics

Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which.max, which.min

Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges

Loading required package: GenomeInfoDb

Error: package or namespace load failed for ‘GenomeInfoDb’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘GenomeInfoDbData’

Error: package ‘GenomeInfoDb’ could not be loaded
Traceback:

1. library(SpatialExperiment)
2. .getRequiredPackages2(pkgInfo, quietly = quietly)
3. library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc, 
 .     quietly = quietly)
4. .getRequiredPackages2(pkgInfo, quietly = quietly)
5. library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc, 
 .     quietly = quietly)
6. .getRequiredPackages2(pkgInfo, quietly = quietly)
7. library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc, 
 .     quietly = quietly)
8. .getRequiredPackages2(pkgInfo, quietly = quietly)
9. stop(gettextf("package %s could not be loaded", sQuote(pkg)), 
 .     call. = FALSE, domain = NA)`

**Comment by pinin4fjords** [comment]
I had a possibly unrelated issue caused by the Bioconda version of GenomeInfoDb not being the latest patch release, which led me to update GenomeInfoDb to the latest patch version see (see https://github.com/bioconda/bioconda-recipes/pull/37485). 

Might be entirely unrelated to your problem, but you could try again now with the new bioconductor-genomeinfodb to see.

**Comment by pinin4fjords** [comment]
or https://github.com/bioconda/bioconda-recipes/issues/35205 might help

**Comment by chancharikmitra** [comment]
Sorry for the delayed response...Oddly: a full re-setup of my Conda environment from scratch (installing all of my dependencies) did the trick.
