### ISSUE TITLE
update and pin to boost 1.61.*

### ISSUE THREAD

**Issue by martin-mann** [bioconda/bioconda-recipes#3725]
Hi,
it's a growing pain to compile a program using the boost-regex lib, since its dependency (icu-lib) comes in the wrong version (54 instead of 56).

It seems that these issues have been cured in the boost 1.61 version at [boost conda recipes](https://github.com/conda/conda-recipes/commits/master/boost) plus they added the static libraries (which would be neat to compile truely stable binaries for bioconda).

Any hope for such an update? :)

Thanks for consideration,
Martin

**Comment by bgruening** [comment]
There will be some conda updates that improve the pinning infrastructure. At that time I expect some updated to the pinned versions.

**Comment by johanneskoester** [comment]
We have boost 1.61 now. There is still a blacklist with problematic recipes though. Björn, should I simply go on on that list or did you already check all of them and they don't work?

**Comment by martin-mann** [comment]
@johanneskoester @bgruening 

just a note: upgrading the boost pinning will break the rebuild of all packages that use 

```
   - boost {{CONDA_BOOST}}*
   - icu 56.*
```

in their requirements to compensate the missing pinning of the icu boost-dependency for the previously pinned boost-1.60 recipe. 

just something to look for / be aware of ...

**Comment by martin-mann** [comment]
a question concerning boost-1.61: 

since this comes with static libs, should we build static binaries to get rid of the runtime-boost requirement?

**Comment by johanneskoester** [comment]
Thanks! I wasn't aware of that hack anymore.

**Comment by johanneskoester** [comment]
I don't think this would be beneficial. If you do so, multiple packages will contain the same boost, requiring more space.
