### ISSUE TITLE
docker and singularity images

### ISSUE THREAD

**Issue by ashotmarg** [bioconda/bioconda-recipes#37318]
Hi, the recipe for the "hap-ibd" package was approved few weeks ago and the conda version seems to be working for that package: https://bioconda.github.io/recipes/hap-ibd/README.html?highlight=hap+ibd#package-package%20&#x27;hap-ibd&#x27; .
However, the docker image in the "quay.io/biocontainers" is not there. Do I need to do something about this from my end, or does this happen automatically? Similarly, should the singularity image at https://depot.galaxyproject.org/singularity/  , be generated automatically?
Thanks,
Ashot

**Comment by pinin4fjords** [comment]
It may just be that the image has not yet been made public (this used to happen automatically with bot merges, but hasn't recently). 

If you ask at https://gitter.im/biocontainers/Lobby they can probably help.

**Comment by bgruening** [comment]
Please check in 48h again, then the bots should have catched up. Feel free to open if it. Thanks!
