### ISSUE TITLE
variant-effect-predictor doesn't recognize Perl CGI dependency

### ISSUE THREAD

**Issue by jaeddy** [bioconda/bioconda-recipes#3732]
Apologies if I'm missing something obvious or already documented here. I'm trying to build a Docker image with the `variant-effect-predictor` package and another tool, but I'm running into an issue with the installed script not detecting the required `CGI` Perl module. 

I'm using the base image from BioContainers to test the VEP install. The installation with `conda` seems to work fine, but I get an error when I try to run the tool. It seems to be looking in the default Perl path for the container but not the conda-specific path. I can't tell whether this is a problem with the BioContainers image or with the VEP recipe.

Dockerfile here: https://github.com/BioContainers/containers/blob/master/biocontainers/Dockerfile

```
docker run -it biocontainers/biocontainers:latest
```

```
biodocker@0d70df106dd3:/data$ conda install variant-effect-predictor=86
```

Here's the error message:

```
biodocker@0d70df106dd3:/data$ variant_effect_predictor.pl --help
Can't locate CGI.pm in @INC (you may need to install the CGI module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /opt/conda/bin/variant_effect_predictor.pl line 46.
BEGIN failed--compilation aborted at /opt/conda/bin/variant_effect_predictor.pl line 46.
```

Confirming that CGI was installed by the conda recipe under `/opt/conda/lib/`:

```
biodocker@0d70df106dd3:/data$ ls /opt/conda/lib/perl5/site_perl/5.22.0/
Algorithm  CGI.pod  Encode     HTML  LWP.pm      Sub     WWW       lwpcook.pod
Archive    Capture  Exception  HTTP  Mozilla     Test    YAML      lwptut.pod
Bio        Class    Exporter   IO    Net         Text    YAML.pm   x86_64-linux-thread-multi
CGI        Data     Fh.pm      IPC   SUPER.pm    URI     YAML.pod
CGI.pm     Devel    File       LWP   Statistics  URI.pm  auto
```

**Comment by bgruening** [comment]
@jaeddy if you build your container manually with a Dockerfile, you should post this issue on the biocontainers github issue. Alternatively, this image should work for you: https://quay.io/repository/biocontainers/variant-effect-predictor

**Comment by jaeddy** [comment]
@bgruening thanks - will do. I found the biocontainer image for VEP earlier, and it seems to have been built using the conda recipe - I'm guessing with the 'auto-mulled' Travis feature (?). Are Dockerfiles generated/stored anywhere for those images? Just curious.

**Comment by bgruening** [comment]
The mulled build images don't have any Dockerfiles, it is completely automatized build. You don't have conda in the containers as well. So the entire build system is not part of the container, that's the beauty of it - the containers becomes really small.
The the above linked container is not working can you give us an error image? We need than to fix the conda package, as it does not seem to be complete.

**Comment by jaeddy** [comment]
Got it. Good to know!

The VEP container seems to work as expected, but I need to include some additional plugins (including one that's installed by a different tool (http://pvac-seq.readthedocs.io/en/latest/prerequisites.html). I thought it might be easier to start with the conda install while building a new container, rather than trying to augment the existing container - but I'm open to other strategies.

(btw - also opened an issue on [biocontainers](https://github.com/BioContainers/containers/issues/84))

**Comment by bgruening** [comment]
You can also create a meta-package which references your deps and you will get a container for this.

**Comment by epruesse** [comment]
outdated
