### ISSUE TITLE
bismark biocontainer wrong linux sort

### ISSUE THREAD

**Issue by JudithR** [bioconda/bioconda-recipes#37865]
Hi, 

I'm not sure where to report this as the responsibilities are not clear to me. Technically this is not an issue with bioconda, but with the container, and more specifically the OS part of the container. I reported it here [https://github.com/BioContainers/containers/issues/483](url) , but was pointed towards here.

I downloaded the docker biocontainer for bismark from quay.io (bismark:0.24.0--hdfd78af_0, 0.23 has the same issue). bismark2bedGraph uses the build in sort command from the container with the following flags: `sort -S $sort_size -T $sort_dir -k3,3V -k4,4n`. The build in sort does not know about -S and -T, resulting in empty output files in bismark_methylation_extractor : 
```
singularity shell ~/software/singularity/bismark_0.24.0--hdfd78af_0.sif
Singularity> sort --help
BusyBox v1.32.1 (2021-04-13 11:15:36 UTC) multi-call binary.

Usage: sort [-nrugMcszbdfiokt] [-o FILE] [-k start[.offset][opts][,end[.offset][opts]] [-t CHAR] [FILE]...

Sort lines of text

        -o FILE Output to FILE
        -c      Check whether input is sorted
        -b      Ignore leading blanks
        -f      Ignore case
        -i      Ignore unprintable characters
        -d      Dictionary order (blank or alphanumeric only)
        -n      Sort numbers
        -g      General numerical sort
        -M      Sort month
        -V      Sort version
        -t CHAR Field separator
        -k N[,M] Sort by Nth field
        -r      Reverse sort order
        -s      Stable (don't sort ties alphabetically)
        -u      Suppress duplicate lines
        -z      Lines are terminated by NUL, not newline
```
The reported error messages are:

```
Sorting input file BK12171.trimmed_filt_merged.1_bismark_bt2_pe.bedGraph.gz.methylation_calls.merged by positions (using -S of 2G)
sort: unknown sort type
Died at /usr/local/bin/bismark2bedGraph line 487.
Finished BedGraph conversion ...
```
with finally
```
No last chromosome was defined, something must have gone wrong while reading the data in (e.g. specified wrong file path for a gzipped coverage file?). Please check your command!
```

Would it be possible to update the container to contain a more complete version of Linux sort?

Thank you
Judith

**Comment by truatpasteurdotfr** [comment]
imho, there is just a missing coreutils requirement for sort (if the container is providing busybox version for sort) and fixing it in bioconda would provide a definitive fix. Meanwhile, one could just add `conda install coreutils` to the container recipe.

**Comment by bgruening** [comment]
@truatpasteurdotfr yes, this sounds correct. 
@JudithR you can build a new container with `coreutils` utilizing this repo https://github.com/BioContainers/multi-package-containers/
