### ISSUE TITLE
【Loading channels: failedCondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/bioconda/linux-64/repodata.json>】

### ISSUE THREAD

**Issue by Datacond** [bioconda/bioconda-recipes#37936]
Hi everybody
I know that this error is typical.But I've tried a lot of methods, but there's still no solution.
```
$ conda search star
Loading channels: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/bioconda/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
u'https://conda.anaconda.org/bioconda/linux-64'

```
This error is very similar to the others, but the last sentence is different(u'https://conda.anaconda.org/bioconda/linux-64')

Any suggestions for this typical error would be greatly appreciated.
Thanks.

**Comment by rpetit3** [comment]
@Datacond try again, I'm wondering if its just an intermittent issue

**Comment by Datacond** [comment]
Ok, all right. I think it might be the internet.thanks very much, @rpetit3

**Comment by Dazhuangafei** [comment]
Hello, I have encountered the same problem and tried a lot of methods, but they haven't been solved. Have you finally solved this problem? @Datacond

**Comment by Datacond** [comment]
This error is caused by the network. You can try again after a while.

**Comment by Dazhuangafei** [comment]
Thank you very much. It is for this reason that I have solved it
