### ISSUE TITLE
miniconda now ships with python 3.6

### ISSUE THREAD

**Issue by rvalieris** [bioconda/bioconda-recipes#3808]
and it broke the builds apparently

https://travis-ci.org/bioconda/bioconda-recipes/jobs/201919469
```[...]
installing: python-3.6.0-0 ...
[...]
UnsatisfiableError: The following specifications were found to be in conflict:

  - conda 4.2.15* -> enum34 -> ordereddict -> python 2.6* -> openssl 1.0.1*

  - python 3.6*

Use "conda info <package>" to see the dependencies for each package.

[...]
```
I don't understand why the conda version needs to be fixed, I think using whatever ships with miniconda should work no ?
ping @bioconda/core

**Comment by tomkinsc** [comment]
Python 3.6 is less than two months old. We could pin 4.2.15 to `py35_0` for now; [this line](https://github.com/bioconda/bioconda-recipes/blob/master/scripts/travis-setup.sh#L29):
`conda install -y conda=4.2.15`
would become:
`conda install -y conda=4.2.15=py35_0`

**Comment by johanneskoester** [comment]
Pinning the conda version gives us some additional control. But we could as well pin to the latest version and allow the use of python 36.

**Comment by tomkinsc** [comment]
This is true. Python 3.6 is less than two months old though, so I wasn't sure if we wanted to pin to it just yet, but we certainly can if we update dependencies accordingly.

**Comment by johanneskoester** [comment]
I don't think this matters. Conda build will use whatever is defined in the env matrix. We should keep 3.5 there for now. We would use 3.6 only as environment for bioconda utils. I will have a look at this tomorrow.

**Comment by mictadlo** [comment]
Hi, I have got the same [problem](https://travis-ci.org/bioconda/bioconda-recipes/jobs/202016641#L305) with my [recipe](https://github.com/bioconda/bioconda-recipes/pull/3758).
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda 4.2.15* -> enum34 -> ordereddict -> python 2.6* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by tomkinsc** [comment]
@mictadlo: All pull requests will have the same problem for now, but I have a PR open to fix it: https://github.com/bioconda/bioconda-recipes/pull/3809

**Comment by rvalieris** [comment]
thanks for the quick fix @tomkinsc.

I see now that the version was pinned because of a bug on conda: https://github.com/bioconda/bioconda-recipes/pull/3478

It makes sense to pin a version, I just worry this might generate conflicts elsewhere later.

for now I will close this as the immediate problem has been solved.

**Comment by johanneskoester** [comment]
The idea would be to always pin to the latest version that works well for us. Unfortunately we don't have the time to evaluate that frequently. But we should find out if the latest stable release works for us soon.

**Comment by rvalieris** [comment]
I agree @johanneskoester, how can we test this ? is getting any package built on the newer version enough to say if the release works for us ?

**Comment by johanneskoester** [comment]
The optimal way would be to encode the conda version solely in the dependencies of bioconda utils. When updating it there, the test suite of bioconda-utils will ensure everything works.

**Comment by johanneskoester** [comment]
I've just checked it, we already install those dependencies in travis-setup. Hence, this additional pinning does not really affect the builds. I remove it in PR #3821.

**Comment by odoublewen** [comment]
Hi @johanneskoester -- I am still confused -- What are we doing about Python 3.6? 

A user with a fresh ana/mini-conda installation today will have python 3.6.  What is the recommended workaround when they try to install bioconda packages that haven't been built on 3.6?  Do they need to do a `conda install python=3.5`?  Should this be documented somewhere?

Thanks

```
$ conda --version
conda 4.3.16

$ conda install pyvcf
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - pyvcf -> python 2.7* -> openssl 1.0.1*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by johanneskoester** [comment]
Good point. We should document it, and build for 3.6 as soon as possible.

**Comment by johanneskoester** [comment]
Downgrading works, as well as creating environments.
