### ISSUE TITLE
Missing containers for recipes?

### ISSUE THREAD

**Issue by apeltzer** [bioconda/bioconda-recipes#38099]
Hi!

several recipes as outlined here https://github.com/nf-core/circrna/issues/62 are missing biocontainers - is there something that went wrong in the upload process? recipes were merged a while ago, so should already be present / existing ...

**Comment by bgruening** [comment]
They are just hidden. By default, quay.io repositories are hidden and we need to make them public. For a long time, our bot was doing this, but it seems to have lost this ability. I don't have time atm to look into this, but if you give me a list with quay.io links where the repo should be I can make them public.

Thanks for you help.

**Comment by apeltzer** [comment]
https://quay.io/repository/biocontainers/ciriquant
https://quay.io/repository/biocontainers/circtools
https://quay.io/repository/biocontainers/find_circ
https://quay.io/repository/biocontainers/circrna_finder
https://quay.io/repository/biocontainers/targetscan
https://quay.io/repository/biocontainers/mulled-v2-04b2ef814c9c6ab8c196c3e372521b88160dc260:e0cb4046baee3fd35fdbf883ba8af34e3e8af2e8-0

**Comment by apeltzer** [comment]
Likewise question: No singularity containers there for these -- does that get created once they are unhidden?

**Comment by dpryan79** [comment]
Those should now be public (Björn must have beat me to doing that). The singularity question will have to be answered by Björn.

**Comment by bgruening** [comment]
Lol, I made them public and then got sidetracked. Sorry. Singularity will be generated in 24h. There is another bot that generated for all Docker a Singularity.

**Comment by apeltzer** [comment]
Thank you both for being around and helping with these type of things 🙏🏻 
@BarryDigby we're good now :-)
