### ISSUE TITLE
Pangolin - Biocontainer "out of date" re: pangolin-data

### ISSUE THREAD

**Issue by marchoeppner** [bioconda/bioconda-recipes#38157]
Hi,

I noticed that the Pangolin Biocontainer was last built 2 months ago (v 4.1.3). 

Now, I am not sure if this belongs here, but since then the pango-data Database underpinning Pangolin has seen two updates (now: 1.16). 

The issue here is that the version of Pangolin is not at all linked to the pangolin-data version. Instead, the recipie will install the latest version of pango-data when installing Pangolin from Conda (or, in extension, the Biocontainer). 

Which means the current container 4.1.3 is "out of date" with respect to the official lineage definitions by, probably, two releases since it hasn't been re-built since late September/early October. We found several examples where this was infact a problem leading to outdated calls. 

A way to solve this would simply be to trigger a re-build, maybe as 4.1.3-2 ? And maybe this could somehow be set up to auto-trigger for the current release of Pangolin, i.e. whenever pango-data gets updated, also re-build the current Pangolin biocontainer (one can dream! ;))

Would be much appreciated!

/Marc

**Comment by bgruening** [comment]
Thanks Marc for bringing up this issue.
I think best practice is to not ship any data with containers, but I guess this ship is sailed. pangolin supports having pago-data specified externally from your installation. Can you use that instead of relying on the pre-build one?

**Comment by marchoeppner** [comment]
Thanks for pointing out the local db option (must have missed it) - I guess that will do as a work-around.
