### ISSUE TITLE
conda seems to assume prodigal 2.60 as the newest version while it's actually 2.6.3 (also available at bioconda) 

### ISSUE THREAD

**Issue by jvollme** [bioconda/bioconda-recipes#3831]
The versions of prodigal which are available from the bioconda channel are:

>         prodigal             2.6.2                         1  bioconda        
>                              2.6.2                         2  bioconda        
>                              2.6.2                         3  bioconda        
>                              2.6.3                         0  bioconda        
>                              2.60                          0  bioconda        
>                              2.60                          1  bioconda

however, when using `conda install prodigal`, version 2.60 is installed by default. Probably it is automatically assumed to be the newest version based on the fact that 2.60 > 2.6 ?

It seems that this is probably just a typo from the prodigal developers. From the release-info of the [prodigal github-page](https://github.com/hyattpd/prodigal/releases/) it is apparent that 2.6.3 is the newest version (released Feb. 2016) while 2.60 was probably meant as "2.6.0" (released Jul 2013).

I know it is possible to select the newest version via `conda install prodigal=2.6.3`, but in the current state conda will then always try to "update" any newer version of prodigal to 2.60, whenever you try to automatically update it anytime later. This will mean that the outdated version of prodigal will be prevalent within conda environments, as many people may just rely on the default versions being installed, assuming they are always the most recent?

maybe it is possible to adjust the prodigal version priority in bioconda? Or maybe it would be an idea to remove the 2.60 version from the channel altogether?

**Comment by rvalieris** [comment]
yes conda will prefer the higher number because it assumes its the latest version.

I don't think we can change the package version now though, what we could do is move the 2.60 packages to bioconda-legacy, and maybe rebuild 2.60 as 2.6.0 if there's people depending on the older package.

@bgruening, what do you think ?

**Comment by bgruening** [comment]
I can only move repositories, so this would mean moving all version at once :(

**Comment by rvalieris** [comment]
oh ok, is it possible to just remove the files then ? we could then rebuild 2.60 as 2.6.0

**Comment by bgruening** [comment]
This would be possible yes. @bioconda/core does this work for you?

**Comment by johanneskoester** [comment]
Yes, we should do that.

**Comment by bgruening** [comment]
@jvollme just to clearify there is actual a version called 2.60 on github: https://github.com/hyattpd/Prodigal/releases ... maybe you can ask the author what this is?

**Comment by rvalieris** [comment]
@bgruening, yes there is but see the release notes of the 2.6.1 version:
```
* Re-release of previous version as 2.6.1 (previously referred to this as "2.60bugfix1").
The source is identical to the last release on Github except for updated dates,
a more streamlined Makefile, and a new markdown README.md.
* Moved to semantic versioning (major.minor.patch) with the 8/2014
re-release. Committed to being more rigorous about this moving
forward.
```
the author switched the versioning format in this release, actually since he calls it a re-release it might not even be necessary to have a 2.6.0 on bioconda.

**Comment by bgruening** [comment]
@rvalieris can you remove the recipe then? I will remove the package as soon as the package is removed.

**Comment by rvalieris** [comment]
its gone !

**Comment by bgruening** [comment]
And also from the channel ...
