### ISSUE TITLE
Problem updating to the most recent version

### ISSUE THREAD

**Issue by nickhsmith** [bioconda/bioconda-recipes#38336]
My problem is that my group has recently pushed an update to our package DROP (v1.2.4), which triggered a bioconda recipe update which was accepted #38295 and this change is reflected on https://anaconda.org/bioconda/drop BUT, when I go to install it or update a environment it fails to recognize the update.

Both `conda install -c bioconda drop` and `conda update drop` (from a previous installation) try to install the outdated version v1.2.3

It's been more than 24 hours, and it doesn't seem the update as made it onto the list of packages available on https://conda.anaconda.org/bioconda/noarch/

Any advice or help is greatly appreciated. Thanks!

**Comment by nickhsmith** [comment]
@Redmar-van-den-Berg any thoughts?

**Comment by Redmar-van-den-Berg** [comment]
@nickhsmith I tried to reproduce this issue, but if I create a new Conda environment and try to install drop I get the latest version:

```
drop-1.2.4                 |     pyhdfd78af_0          79 KB  bioconda
````

Maybe you have some caching issue with your conda install, can you try it in a new environment, or on a different system?
