### ISSUE TITLE
Bioconda Training Channel

### ISSUE THREAD

**Issue by jmchilton** [bioconda/bioconda-recipes#3834]
Howdy y'all. We do a fair number of interactive training events for Galaxy and I was thinking about how to train on building Conda recipes. My desire is to have participants go through a complete recipe - fork, create, merge, and use. Doing this to bioconda-recipes directly is problematic - because finding enough real software for every event would be very difficult and then to get it all compiled and working during these events would be very problematic in most cases.

I was wondering if the community would be interested in hosting like a ``bioconda-training-recipes`` channel and repository? We could then have every participant just add a hello world recipe with a different name - we could setup a bot to merge recipes that matched a certain set of patterns - and I can configure our development tooling to target this channel as well.

I could setup something more Galaxy branded - but I'd prefer it if we built resources that could also help the broader bioconda community and documentation.

It could also serve as a testing ground for automatic tooling associated with the bioconda channel is that would be helpful.

**Comment by bgruening** [comment]
ping @bioconda/core 

One culprit I see is actually travis build times. If we host such a channel under the bioconda organisation it will share one travis queue and hence will make training much harder. I suppose you are aiming at the entire bioconda test suite.

**Comment by johanneskoester** [comment]
That is a great idea! Thanks for considering this! We could create a separate bioconda-training organization.

**Comment by jmchilton** [comment]
@bgruening Doesn't the test suite only test changes? If not or we think this would be a problem anyway - I think creating a bioconda-training organization is a fine workaround.

**Comment by bgruening** [comment]
@jmchilton are you planning to really upload this package to a anaconda channel? If so yes, only changes, but we can remove those packages via travis cron every week ...

**Comment by jmchilton** [comment]
@bgruening It'd be most complete and the best demo to upload it and see it working I think? Does that happen right when PRs are merged?

**Comment by johanneskoester** [comment]
Yes. Whatever comes into the master branch is built and uploaded to anaconda.

**Comment by daler** [comment]
I think a separate bioconda-training channel and organization would be the cleanest solution. The tooling can be shared between bioconda and bioconda-training; this would help generalize the infrastructure and identify sticking points that need more documentation so it would certainly help bioconda. Benefits of maintaining separation would be more travis-ci resources for both groups and reduced complexity of infrastructure (e.g., wouldn't need cron jobs mentioned by @bgruening).

**Comment by johanneskoester** [comment]
I agree

**Comment by bgruening** [comment]
I created https://anaconda.org/bioconda-training and will create the github repo next week, depending on @johanneskoester latest build work.

**Comment by jmchilton** [comment]
Really awesome @bgruening - thanks for this!

**Comment by bgruening** [comment]
`will create the github repo next week` Oo ... sorry. Dropped the ball here.
I created: https://github.com/bioconda-training/bioconda-recipes and maybe a few people from Australia will use it next week :)

**Comment by bgruening** [comment]
Just found this old issue. Seems that no one has requested it so far again and use it. Should we close this issue?

The trainings that we are giving are usually directly on bioconda-recipes or conda-forge and so far no complains.
