### ISSUE TITLE
OS X -headerpad_max_install_name

### ISSUE THREAD

**Issue by yesimon** [bioconda/bioconda-recipes#3838]
When compiling a C/C++ program, I recently ran into the issue where I needed to add the following linker option for the conda post-processing step to work (due to usage of `rpath` and `install_name_tool` usage).

`-Wl,-headerpad_max_install_names`

The problem is that it's not easy to inject this into the varying build processes that people are using. The only way would be to use a custom gcc specs file and wrap alias gcc to use that specs file, which adds yet another layer of indirection. Alternatively, we can just note in the docs that this might be a common occurrence that requires patching of project Makefiles/CMakeLists etc.

@bioconda/osx

**Comment by bgruening** [comment]
@yesimon thanks for looking at it. Can we add it to https://bioconda.github.io/guidelines.html#c-c ?

**Comment by epruesse** [comment]
outdated
