### ISSUE TITLE
R-matlab is not working

### ISSUE THREAD

**Issue by ekushele** [bioconda/bioconda-recipes#38699]
Hello,

I'm trying to use r-matlab package on conda.
I installed the package with `conda install -c conda-forge r-matlab=1.0.2` (also tried `conda install -c conda-forge r-matlab=1.0.4`)

Then, I started the R session and tried to load the r-matlab library, and got an error:
```
> library(R.matlab)
Error: package or namespace load failed for ‘R.matlab’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘R.methodsS3’
```

@cumbof ... do you know?

**Comment by daler** [comment]
`r-matlab` is on the conda-forge channel rather than bioconda; the repository for the package is https://github.com/conda-forge/r-matlab-feedstock. It looks to be missing the `R.methodsS3` package in the package dependencies, but that needs to be handled over in that repo.
