### ISSUE TITLE
duplicated packages between bioconda and conda-forge

### ISSUE THREAD

**Issue by cokelaer** [bioconda/bioconda-recipes#3872]
a while ago I naively put general Python packages (e.g. easydev / colormap) into bioconda so that biological-related packages could be added as well (e.g. bioservices). I realised afterwards that the general packages should have been put elsewhere. I've seen that bioconda is now linked to conda-forge so I created recipes on conda-forge for the general packages (easydev).

My question is: what shall we do with the now duplicated packages that are on bioconda and conda-forge ? Would you recommend to remove them completely from bioconda, or simply keep the current version(s) but without any future updates  ?

**Comment by cokelaer** [comment]
Once I'm happy to move the duplicated packages to the legacy channel, what are the steps to follow ? Is there any doc about that ? thanks

**Comment by bgruening** [comment]
No documentation, currently. Remove the recipes from the github repo and ping @bioconda/core to move the package.

**Comment by cokelaer** [comment]
okay great. thanks
