### ISSUE TITLE
Travis CI: Error: no such patch: /opt/recipe/

### ISSUE THREAD

**Issue by CicoZhang** [bioconda/bioconda-recipes#3889]
Hey, everyone. I am adding an old package to bioconda. I have applied a patch, but only for OSX. It's been twice already that I got this error from Travis for the linux build. What does this error mean? Conda build works swimmingly locally.  I am not sure whether this error concerns the patch.

![image](https://cloud.githubusercontent.com/assets/11710225/23215014/1f4a1156-f911-11e6-92e9-d7c9840e3f43.png)

https://travis-ci.org/CicoZhang/bioconda-recipes/jobs/204195323

Thank you in advance.

**Comment by CicoZhang** [comment]
Interestingly, OSX has passed the test already, though I am using Ubuntu.
![image](https://cloud.githubusercontent.com/assets/11710225/23217323/238299b6-f919-11e6-934f-b84df156eade.png)

**Comment by bgruening** [comment]
@CicoZhang this simply means that your Linux build is broken. I might not get the question, sorry :(

**Comment by CicoZhang** [comment]
Hi, @bgruening , conda build the package locally perfectly, but fail to pass on Travis (Linux fails, OSX passed).

I get the error like this:

```
Error: no such patch: /opt/recipe/
ERROR bioconda_utils.build:build_recipes(375): BIOCONDA BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
ERROR bioconda_utils.build:build_recipes(386): BIOCONDA BUILD SUMMARY: FAILED recipe ogdf-Sakura-0.tar.bz2, environment CONDA_R=3.3.1;CONDA_GSL=1.16;CONDA_PY=27;CONDA_HDF5=1.8.17;CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_NCURSES=5.9
/home/travis/build.sh: line 158:  3465 Terminated              travis_jigger $! $timeout $cmd 
```

The whole log can be found [here](https://travis-ci.org/CicoZhang/bioconda-recipes/jobs/204195323)

Are there any 'obvious' mistakes here :) ?
![image](https://cloud.githubusercontent.com/assets/11710225/23218229/03a9b978-f91c-11e6-851e-861062fa2889.png)

**Comment by daler** [comment]
@CicoZhang if you open a PR, we can take a look at the code and test it ourselves. Nothing obvious in the screenshot you have here, but I think the version would be better as "201207" rather than "Sakura" since the former more closely fits PEP386.

**Comment by CicoZhang** [comment]
This problem is also reproduced by @acaprez , and he provides a workaround solution. It really works now. Hopefully this bug will be solved soon.
