### ISSUE TITLE
miRDeep 2 needs file to signal installation successful and run

### ISSUE THREAD

**Issue by gonzalovera** [bioconda/bioconda-recipes#3893]
Hi guys, 

After installing mirdeep2 with conda, when trying to run, e.g. quantifier.pl, you get the message:

> Please run the install.pl script first before using the miRDeep2 package
> 		The install script is located in /home/mgodia/.conda/envs/mirdeep2/ so just do
> 
> 		cd /home/$user/.conda/envs/mirdeep2/
>
> 		perl install.pl
> 
> 		 at /home/$user/.conda/envs/mirdeep2/bin/quantifier.pl line 1412.
> 

To skip this, you need to create an empty file, e.g.:

>		touch ~/.conda/envs/mirdeep2/install_successful

Recipe used: bioconda-recipes/recipes/mirdeep2/2.0.0.8/

Hope it helps,
Gonzalo

**Comment by daler** [comment]
@gonzalovera thanks for reporting.
