### ISSUE TITLE
Packages require rebuilding with conda-build > 2.0

### ISSUE THREAD

**Issue by lparsons** [bioconda/bioconda-recipes#3904]
I've identified these packages as needing to be rebuilt with conda-build > 2.0. I've gotten the `PaddingError: Placeholder of length '80' too short in package` error for each of them recently:

- [ ] `bioconda::deeptools-2.3.5-py27_1`
- [ ] `bioconda::deeptools-2.3.6-py27_1`
- [ ] `bioconda::deeptools-2.4.1-py27_0`

**Comment by lparsons** [comment]
BTW, I identified two other packages, but they are in the `r` channel, which seems deprecated. They are `r::r-base-3.2.1-0` and `r::r-base-3.2.2-0`.

**Comment by lparsons** [comment]
Not sure if this is correct, but I sumitted https://github.com/conda-forge/r-base-feedstock/issues/12 for the `r` packages.

**Comment by tomkinsc** [comment]
See: https://github.com/bioconda/bioconda-recipes/pull/3956
