### ISSUE TITLE
Bioconductor release cycle and version dependencies

### ISSUE THREAD

**Issue by vodkatad** [bioconda/bioconda-recipes#3911]
Hi, I've looked around to answer to this doubt but I have not been able to solve it.
Basically what I am missing is how Bioconda deals with the not stable API of some Bioconductor packages. For example the GenomicRanges package sometimes changes some internal mechanisms and also the external API, therefore packages depending on it have to adapt to these changes when there is a Bioc release.
Right now the script that generates skeletons for bioc recipes (it has no way to reconstruct these deps, I think/fear, but I could try to reason about a semi-automated solution): should the recipes writer/mantainers be warned to try to keep traces of these facts limiting the versions of the deps?

**Comment by bgruening** [comment]
@vodkatad if this is the case we should pin the version of GenomicRanges. So bind it to a specific version.

**Comment by vodkatad** [comment]
I think that this is the case for all packages depending on GenomicRanges at certain version changes (but not only GenomicRanges, this is only an example) - I will think about a way to automagically manage these cases (maybe parsing the svn log of Bioconductor) and in the meanwhile fix the recipes that I know of.

**Comment by bgruening** [comment]
Wonderful! Thanks for working on this!!!

**Comment by bgruening** [comment]
@vodkatad if you are working on the skeleton, please also have a look at: https://github.com/bioconda/bioconda-recipes/pull/3713

**Comment by vodkatad** [comment]
Thanks, I think that I will address this next week, hoping in some bright ideas :)

**Comment by daler** [comment]
@vodkatad do you know how Bioconductor currently handles this? For example our current bioconda GenomicRanges package is v1.26.1 (created Oct 27 2016). But I see on http://www.bioconductor.org/packages/3.4/bioc/html/GenomicRanges.html it's at v1.26.2. So in the past couple of months there was a version increase in GenomicRanges but no new Bioc release. Does Bioc re-build all packages to ensure they work the GenomicRanges (or other unstable packages)?

Maybe one solution would be to add a Bioc version string to bioconda packages, and simultaneously pin all versions at the time of the Bioc release.

**Comment by vodkatad** [comment]
Only bugfixes that do not change APIs (I think) should be committed to the release version of bioc packages. Every 6 months the devel version (with active development on and sometimes API modifications) reaches a "stable" point where every package works with the other ones and then the new Bioc version is released as release (sorry for the words clash). Bioc packages are built and checked regularly both for release and devel version, yes.

**Comment by daler** [comment]
Thanks.  @vodkatad, @bgruening what about something like this for bioconda:

Immediately after Bioc release:
- update and rebuild all r-* and bioconductor-* packages. May possibly need to do this on a separate server to get it done in a timely manner. As we've seen, it's painfully slow on travis-ci.
- source packages get mirrored to cargo-port
- add Bioc version string to bioconductor-* package names, similar to boost or gsl. We'd need a dummy package for the bioconductor release version, and need to ensure all bioconductor packages depend on that package. This can be handled in the bioconductor skeleton.

In between Bioc releases:
- rolling updates for post-release bugfixes. Packages still include the current Bioc version string and depend on current Bioc release dummy package
- could set up a cron job on travis, if not to auto-build then at least to notify us when versions change

Once that's in place we could think about adding Bioc devel support.

**Comment by vodkatad** [comment]
The Bioc ml convenes that single developers do not always put these dependencies explicitly. The Bioc version string seems ok to them. I do not have a clear idea of what needs to be done to implement this proposal but I could start looking at what is happening for boost/gsl, I will be extremely slow though :)

**Comment by daler** [comment]
Thanks! (thread [here](https://stat.ethz.ch/pipermail/bioc-devel/2017-February/010503.html) for those curious). Unfortunately we don't have good developer docs yet, but generally speaking here's what we need to implement this:

First would be adding `CONDA_BIOCONDUCTOR` in [`env_matrix.yml`](https://github.com/bioconda/bioconda-recipes/blob/master/scripts/env_matrix.yml) to get that env var visible to all recipes. Then we'd have to modify the [bioconductor_skeleton](https://github.com/bioconda/bioconda-recipes/blob/master/scripts/bioconductor/bioconductor_skeleton.py) to build meta.yaml files that include the CONDA_BIOCONDUCTOR in the build string, like in [this example](https://github.com/bioconda/bioconda-recipes/blob/d1351a9cdf3163bcd7c8cc5a21185e7f92412a99/recipes/intarna/meta.yaml#L12). The bioconductor_skeleton script needs some work. For example, URLs should not use "release" but instead should use the value of `CONDA_BIOCONDUCTOR`. The script should also be moved to `bioconda-utils` where it can be better maintained and take advantage of the infrastructure code there.

The time-consuming part is rebuilding everything. @bgruening mentioned big changes are coming with conda-build 3, and that we might have to rebuild everything anyway for that. I'm not sure what the timeline for that is, but in the meantime we could get the infrastructure in place to get ready for it. In practice, that will mostly involve improving the bioconductor_skeleton script.

**Comment by bgruening** [comment]
I have started the R3.4 rebuilds independent of conda-build-3, which might take until the next year until conda-forge has shifted and tested it intensively.
I will close this one, please feel free to reopen.
