### ISSUE TITLE
hifiasm on conda is 3-5 time slower than locally built version

### ISSUE THREAD

**Issue by chhylp123** [bioconda/bioconda-recipes#39177]
Hello,

I found that running a version of hifiasm compiled locally on our cluster, is significantly faster than running the conda version. I checked the conda recipes here: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/hifiasm, but cannot find anything abnormal. Could you please let me know is there any other things may affect the compiling of conda? Related issue: https://github.com/chhylp123/hifiasm/issues/392.

**Comment by peterjc** [comment]
Did #39545 fix this by changing the CXXFLAGS which were previously loosing the -O3 setting?

There is a separate PR on the hifiasm side which may also solve this, see linked issue.

**Comment by peterjc** [comment]
The comment https://github.com/chhylp123/hifiasm/issues/392#issuecomment-1442149761 says yes, 0.18.8 from bioconda now performs as expected. Closing.

**Comment by chhylp123** [comment]
Thanks. It has been sovled.
