### ISSUE TITLE
Updated package missing from bioconda 

### ISSUE THREAD

**Issue by mrvollger** [bioconda/bioconda-recipes#39363]
Hello,

I recently updated my package (fibertools-rs) to v0.1.2 but the new version does not appear to be available on the command line even thought the [updated files have been available for ~1.5 days](https://anaconda.org/bioconda/fibertools-rs). And here are a few screen shots showing that it should be available:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/6935283/218865607-8efd33fb-3d72-4751-bd07-b421eb2f7d9b.png">
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/6935283/218865654-aeba389d-3464-482c-a09e-5e610e0f0cd5.png">

But if I go to the [bioconda website](https://bioconda.github.io/recipes/fibertools-rs/README.html#package-fibertools-rs) or try installing from the command line the latest available version appears to only be 0.1.1:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/6935283/218865759-5ffdfe9d-c348-4b33-a915-4396fb315b6e.png">
<img width="619" alt="image" src="https://user-images.githubusercontent.com/6935283/218865925-a82d68bc-a482-41a3-ae6b-1c23c48288e9.png">

Is there some bioconda package index that needs to be updated?

Thanks in advance!
Mitchell

**Comment by amizeranschi** [comment]
Perhaps unrelated, but I suspect the Bioconda servers have been experiencing some issues during the last few days. There are some server-side problems with Bioconductor packages that have been reoccurring during the past few months and the latest reports are from only a few days ago: https://github.com/bioconda/bioconda-recipes/issues/37906#issuecomment-1447921224
