### ISSUE TITLE
Clarification on closed PRs

### ISSUE THREAD

**Issue by mbhall88** [bioconda/bioconda-recipes#39368]
I'm wondering if I am doing something wrong with autobump PRs.

I release a new version of my package, and an autobump PR was created https://github.com/bioconda/bioconda-recipes/pull/39345

However, I added a new dependency. So I edited the `meta.yaml` file in that PR. When the tests all passed, I approved the PR and then asked biocondabot to merge it. But it responded "I received an error uploading the build artifacts or merging the PR!"

I then tried updating the PR with the tip of master. After the CI passed again, bicondabot closed the PR! 

I then had the same problem again https://github.com/bioconda/bioconda-recipes/pull/39348

I've closed the most recent one https://github.com/bioconda/bioconda-recipes/pull/39364 and added a manual update myself https://github.com/bioconda/bioconda-recipes/pull/39367

What is the correct process in this example? It's happened to me before with other packages. 

1. It would be helpful if the bot gave some details of the error when trying to merge
2. should I only update the PR with master using the bioconda bot command? (i.e. don't click "update branch" myself)

**Comment by daler** [comment]
@mbhall88 this is unfortunately a known issue with the autobump bot. It's frustrating, we hope to fix it soon! You're not doing anything wrong, we need to be better about the bot behavior and also document the process better. The manual update is currently the best workaround.

**Comment by daler** [comment]
@mbhall88 this problematic, inappropriate closing should now be fixed as of earlier today, but please reopen if you notice it happening again.

**Comment by marcelm** [comment]
@daler I just stumbled over this issue by accident. I’ve had this problem before and am happy to see that it should be solved. I’d just like to suggest that fixes like these deserve an announcement in some way, perhaps by posting to #33333.
