### ISSUE TITLE
bcftools link to libgsl 2.5 but install gsl 2.7

### ISSUE THREAD

**Issue by incardon** [bioconda/bioconda-recipes#39382]
Dear developer

I want to report that the actual bcftools binary link to gsl 2.5, but gsl 2.7 is installed. I the base system does not have libgsl 2.5 
link will fail and bcftools will not work on the machine with a "cannot open shared library libgsl.so.2.5"

conda list

_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bcftools                  1.15                 h0ea216a_2    bioconda
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2023.01.10           h06a4308_0  
gdbm                      1.18                 h0a1914f_2    conda-forge
gsl                       2.7.1                h6e86dc7_1  
htslib                    1.15.1               h6bc39ce_1    bioconda
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               hf9c8cef_0    conda-forge
libcurl                   7.87.0               h6312ad2_0    conda-forge
libdeflate                1.13                 h166bdaf_0    conda-forge
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h516909a_1    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libnghttp2                1.51.0               hdcd2b5c_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.4                  h6a678d5_0  
openssl                   1.1.1t               h0b41bf4_0    conda-forge
perl                      5.34.0               h5eee18b_2  
readline                  8.2                  h5eee18b_0  
xz                        5.2.10               h5eee18b_1  
zlib                      1.2.13               h166bdaf_4    conda-forge

ldd on the binary

ldd /ceph01/projects/Exomes/cpo_trios/gatk_parabricks/.snakemake/conda/ff5f078f8555ed800632574b3975cc7b/bin/bcftools
	linux-vdso.so.1 (0x00007ffcee8d8000)
	libhts.so.3 => /ceph01/projects/Exomes/cpo_trios/gatk_parabricks/.snakemake/conda/ff5f078f8555ed800632574b3975cc7b/bin/../lib/libhts.so.3 (0x00007ff76abfa000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff76a8af000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff76a6ab000)
	libgsl.so.25 => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff76a488000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff76a093000)
	libdeflate.so.0 => /ceph01/projects/Exomes/cpo_trios/gatk_parabricks/.snakemake/conda/ff5f078f8555ed800632574b3975cc7b/bin/../lib/./libdeflate.so.0 (0x00007ff76adde000)
	liblzma.so.5 => /ceph01/projects/Exomes/cpo_trios/gatk_parabricks/.snakemake/conda/ff5f078f8555ed800632574b3975cc7b/bin/../lib/./liblzma.so.5 (0x00007ff76adb5000)
	libbz2.so.1.0 => /ceph01/projects/Exomes/cpo_trios/gatk_parabricks/.snakemake/conda/ff5f078f8555ed800632574b3975cc7b/bin/../lib/./libbz2.so.1.0 (0x00007ff76ada1000)
	libz.so.1 => /ceph01/projects/Exomes/cpo_trios/gatk_parabricks/.snakemake/conda/ff5f078f8555ed800632574b3975cc7b/bin/../lib/./libz.so.1 (0x00007ff76ad85000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff76acf6000)

**Comment by pettyalex** [comment]
@incardon it looks like you're mixing channels in an incompatible way.

Your environment has gsl from the `defaults` conda channel, but you're installing bcftools from `bioconda` and its supporting libraries from `conda-forge`. These are incompatible, and if you install `bcftools` or any other tools in bioconda, you need to be using conda-forge because they're built and linked against conda forge.

https://conda-forge.org/docs/user/tipsandtricks.html#using-multiple-channels

I don't know why, but conda-forge has libgsl globally pinned to that older version: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml#L343

**Comment by incardon** [comment]
Thanks for the answer. 

The package has been installed with --set channel_priority strict and the following  (standard) priority -c bioconda -c conda-forge -c defaults. Now I am not anymore on the system where the problem was, but on the system for example where I actually running I see 

`
(bcftools) [i-bird@localhost openfpm_pdata]$ which bcftools 
/home/i-bird/miniconda3/envs/bcftools/bin/bcftools
(bcftools) [i-bird@localhost openfpm_pdata]$ 
(bcftools) [i-bird@localhost openfpm_pdata]$ 
(bcftools) [i-bird@localhost openfpm_pdata]$ 
(bcftools) [i-bird@localhost openfpm_pdata]$ ldd /home/i-bird/miniconda3/envs/bcftools/bin/bcftools
	linux-vdso.so.1 (0x00007ffcc6f73000)
	libhts.so.3 => /home/i-bird/miniconda3/envs/bcftools/bin/../lib/libhts.so.3 (0x00007f624d7d9000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f624d6d3000)
	libz.so.1 => /home/i-bird/miniconda3/envs/bcftools/bin/../lib/libz.so.1 (0x00007f624d6b9000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f624d6b4000)
	libgsl.so.25 => /home/i-bird/miniconda3/envs/bcftools/bin/../lib/libgsl.so.25 (0x00007f624d200000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f624d6ad000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f624d023000)
	libdeflate.so.0 => /home/i-bird/miniconda3/envs/bcftools/bin/../lib/./libdeflate.so.0 (0x00007f624d698000)
	liblzma.so.5 => /home/i-bird/miniconda3/envs/bcftools/bin/../lib/./liblzma.so.5 (0x00007f624d66f000)
	libbz2.so.1.0 => /home/i-bird/miniconda3/envs/bcftools/bin/../lib/./libbz2.so.1.0 (0x00007f624d659000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f624d9ec000)
	libcblas.so.3 => /home/i-bird/miniconda3/envs/bcftools/bin/../lib/./libcblas.so.3 (0x00007f624ac00000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f624d654000)
	libgfortran.so.5 => /home/i-bird/miniconda3/envs/bcftools/bin/../lib/././libgfortran.so.5 (0x00007f624aa55000)
	libquadmath.so.0 => /home/i-bird/miniconda3/envs/bcftools/bin/../lib/./././libquadmath.so.0 (0x00007f624d618000)
	libgcc_s.so.1 => /home/i-bird/miniconda3/envs/bcftools/bin/../lib/./././libgcc_s.so.1 (0x00007f624d5ff000)
(bcftools) [i-bird@localhost openfpm_pdata]$ 

`

This does not make sense to me, why bcftools is linking with gsl 2.5 ?

Also an objdump -p on the bcftools report

`
objdump -p /home/i-bird/miniconda3/envs/bcftools/bin/bcftools

/home/i-bird/miniconda3/envs/bcftools/bin/bcftools:     file format elf64-x86-64

Program Header:
    PHDR off    0x0000000000000040 vaddr 0x0000000000000040 paddr 0x0000000000000040 align 2**3
         filesz 0x0000000000000268 memsz 0x0000000000000268 flags r--
  INTERP off    0x00000000000002a8 vaddr 0x00000000000002a8 paddr 0x00000000000002a8 align 2**0
         filesz 0x000000000000001c memsz 0x000000000000001c flags r--
    LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**12
         filesz 0x0000000000010200 memsz 0x0000000000010200 flags r--
    LOAD off    0x0000000000011000 vaddr 0x0000000000011000 paddr 0x0000000000011000 align 2**12
         filesz 0x00000000000c1785 memsz 0x00000000000c1785 flags r-x
    LOAD off    0x00000000000d3000 vaddr 0x00000000000d3000 paddr 0x00000000000d3000 align 2**12
         filesz 0x0000000000039c18 memsz 0x0000000000039c18 flags r--
    LOAD off    0x000000000010d5b0 vaddr 0x000000000010e5b0 paddr 0x000000000010e5b0 align 2**12
         filesz 0x0000000000005b50 memsz 0x0000000000005c10 flags rw-
 DYNAMIC off    0x000000000010e378 vaddr 0x000000000010f378 paddr 0x000000000010f378 align 2**3
         filesz 0x0000000000000270 memsz 0x0000000000000270 flags rw-
    NOTE off    0x00000000000002c4 vaddr 0x00000000000002c4 paddr 0x00000000000002c4 align 2**2
         filesz 0x0000000000000020 memsz 0x0000000000000020 flags r--
EH_FRAME off    0x00000000000ff140 vaddr 0x00000000000ff140 paddr 0x00000000000ff140 align 2**2
         filesz 0x00000000000016ec memsz 0x00000000000016ec flags r--
   STACK off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**4
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rw-
   RELRO off    0x000000000010d5b0 vaddr 0x000000000010e5b0 paddr 0x000000000010e5b0 align 2**0
         filesz 0x0000000000001a50 memsz 0x0000000000001a50 flags r--

Dynamic Section:
  NEEDED               libhts.so.3
  NEEDED               libm.so.6
  NEEDED               libz.so.1
  NEEDED               libdl.so.2
  NEEDED               libgsl.so.25
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
  RPATH                $ORIGIN/../lib
  INIT                 0x0000000000011000
  FINI                 0x00000000000d277c
  INIT_ARRAY           0x000000000010e5b0
  INIT_ARRAYSZ         0x0000000000000008
  FINI_ARRAY           0x000000000010e5b8
  FINI_ARRAYSZ         0x0000000000000008
  HASH                 0x00000000000002e8
  GNU_HASH             0x0000000000001d38
  STRTAB               0x00000000000073c8
  SYMTAB               0x00000000000031b0
  STRSZ                0x0000000000002687
  SYMENT               0x0000000000000018
  DEBUG                0x0000000000000000
  PLTGOT               0x000000000010f5e8
  PLTRELSZ             0x0000000000000018
  PLTREL               0x0000000000000007
  JMPREL               0x00000000000101e8
  RELA                 0x000000000000a098
  RELASZ               0x0000000000006150
  RELAENT              0x0000000000000018
  BIND_NOW             0x0000000000000000
  FLAGS_1              0x0000000008000001
  VERNEED              0x0000000000009fd8
  VERNEEDNUM           0x0000000000000004
  VERSYM               0x0000000000009a50
  RELACOUNT            0x00000000000002dd

Version References:
  required from libdl.so.2:
    0x09691a75 0x00 08 GLIBC_2.2.5
  required from libpthread.so.0:
    0x09691a75 0x00 04 GLIBC_2.2.5
  required from libm.so.6:
    0x09691a75 0x00 03 GLIBC_2.2.5
  required from libc.so.6:
    0x0d696914 0x00 09 GLIBC_2.4
    0x0d696913 0x00 07 GLIBC_2.3
    0x0d696917 0x00 06 GLIBC_2.7
    0x09691974 0x00 05 GLIBC_2.3.4
    0x09691a75 0x00 02 GLIBC_2.2.5

`

That again report that bcftools want gsl-2.5 explicitly.

If I also download the 1.17

`
wget https://anaconda.org/bioconda/bcftools/1.17/download/linux-64/bcftools-1.17-haef29d1_0.tar.bz2
tar -xf bcftools-1.17-haef29d1_0.tar.bz2
objdump -p bin/bcftools 
`

I run objdump on that:


`
(bcftools) [i-bird@localhost test_bcftools]$ objdump -p bin/bcftools 

bin/bcftools:     file format elf64-x86-64

Program Header:
    PHDR off    0x0000000000000040 vaddr 0x0000000000000040 paddr 0x0000000000000040 align 2**3
         filesz 0x0000000000000268 memsz 0x0000000000000268 flags r--
  INTERP off    0x00000000000002a8 vaddr 0x00000000000002a8 paddr 0x00000000000002a8 align 2**0
         filesz 0x000000000000001c memsz 0x000000000000001c flags r--
    LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**12
         filesz 0x00000000000107c0 memsz 0x00000000000107c0 flags r--
    LOAD off    0x0000000000011000 vaddr 0x0000000000011000 paddr 0x0000000000011000 align 2**12
         filesz 0x00000000000c8845 memsz 0x00000000000c8845 flags r-x
    LOAD off    0x00000000000da000 vaddr 0x00000000000da000 paddr 0x00000000000da000 align 2**12
         filesz 0x000000000003b358 memsz 0x000000000003b358 flags r--
    LOAD off    0x0000000000115590 vaddr 0x0000000000116590 paddr 0x0000000000116590 align 2**12
         filesz 0x0000000000005bf0 memsz 0x0000000000005cc0 flags rw-
 DYNAMIC off    0x0000000000116358 vaddr 0x0000000000117358 paddr 0x0000000000117358 align 2**3
         filesz 0x0000000000000260 memsz 0x0000000000000260 flags rw-
    NOTE off    0x00000000000002c4 vaddr 0x00000000000002c4 paddr 0x00000000000002c4 align 2**2
         filesz 0x0000000000000020 memsz 0x0000000000000020 flags r--
EH_FRAME off    0x0000000000107280 vaddr 0x0000000000107280 paddr 0x0000000000107280 align 2**2
         filesz 0x00000000000017b4 memsz 0x00000000000017b4 flags r--
   STACK off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**4
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rw-
   RELRO off    0x0000000000115590 vaddr 0x0000000000116590 paddr 0x0000000000116590 align 2**0
         filesz 0x0000000000001a70 memsz 0x0000000000001a70 flags r--

Dynamic Section:
  NEEDED               libhts.so.3
  NEEDED               libm.so.6
  NEEDED               libdl.so.2
  NEEDED               libgsl.so.25
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
  RPATH                $ORIGIN/../lib
  INIT                 0x0000000000011000
  FINI                 0x00000000000d983c
  INIT_ARRAY           0x0000000000116590
  INIT_ARRAYSZ         0x0000000000000008
  FINI_ARRAY           0x0000000000116598
  FINI_ARRAYSZ         0x0000000000000008
  HASH                 0x00000000000002e8
  GNU_HASH             0x0000000000001d80
  STRTAB               0x0000000000007630
  SYMTAB               0x0000000000003280
  STRSZ                0x000000000000280f
  SYMENT               0x0000000000000018
  DEBUG                0x0000000000000000
  PLTGOT               0x00000000001175b8
  PLTRELSZ             0x0000000000000018
  PLTREL               0x0000000000000007
  JMPREL               0x00000000000107a8
  RELA                 0x000000000000a568
  RELASZ               0x0000000000006240
  RELAENT              0x0000000000000018
  BIND_NOW             0x0000000000000000
  FLAGS_1              0x0000000008000001
  VERNEED              0x000000000000a3e8
  VERNEEDNUM           0x0000000000000005
  VERSYM               0x0000000000009e40
  RELACOUNT            0x00000000000002e1

Version References:
  required from libdl.so.2:
    0x09691a75 0x00 15 GLIBC_2.2.5
  required from libpthread.so.0:
    0x09691a75 0x00 07 GLIBC_2.2.5
  required from libm.so.6:
    0x09691a75 0x00 04 GLIBC_2.2.5
  required from libc.so.6:
    0x0d696914 0x00 20 GLIBC_2.4
    0x0d696913 0x00 13 GLIBC_2.3
    0x0d696917 0x00 11 GLIBC_2.7
    0x09691974 0x00 09 GLIBC_2.3.4
    0x09691a75 0x00 03 GLIBC_2.2.5
  required from libhts.so.3:
    0x0d4fb946 0x00 19 HTSLIB_1.16
    0x0d4fb940 0x00 18 HTSLIB_1.10
    0x00d4fb97 0x00 17 HTSLIB_1.7
    0x00d4fb95 0x00 16 HTSLIB_1.5
    0x00d4fb91 0x00 14 HTSLIB_1.1
    0x0d4fb943 0x00 12 HTSLIB_1.13
    0x00d4fb93 0x00 10 HTSLIB_1.3
    0x00d4fb96 0x00 08 HTSLIB_1.6
    0x00d4fb94 0x00 06 HTSLIB_1.4
    0x00d4fb90 0x00 05 HTSLIB_1.0
    0x04fb95c1 0x00 02 HTSLIB_1.2.1

`

And I again obtain a needed dependency from libgsl 2.5

**Comment by dgaston-nsh** [comment]
This is a problem I am also currently having. Conda-forge has gsl=2.7 in the channel, so everytime I try and install bcftools, even if I have gsl=2.5 already installed, conda wants to upgrade the gsl version which then results in an unusable bcftools

**Comment by dpryan79** [comment]
I just noticed this myself, somehow during building and testing there are two GSLs getting installed and the wrong one is getting linked against. I'll fix this.

Xref: https://github.com/bioconda/bioconda-recipes/pull/43229

**Comment by dpryan79** [comment]
As mentioned above, this is indeed due to a channel priority strictness. The newest GSL in conda-forge is 2.7, against which this is built, since we use strict channel priorities. GSL 2.7 creates libgsl.so.25 and that's what's linked against. In the defaults channel from Ananconda, there's a GSL 2.7.1 build, which ships libgsl.so.27. If strict channel priorities aren't used then this will get pulled in as well. Note that apparently some versions of mamba don't do strict channel prioritization (at least if memory serves).
