### ISSUE TITLE
Replace openmpi by the one on conda-forge?

### ISSUE THREAD

**Issue by bebatut** [bioconda/bioconda-recipes#3947]
Hi,

I saw there is a recipe for `openmpi` here, and also one on conda-forge. And the one on conda-forge seems more up-to-date.
Do you think it makes sense to remove the one here and use only the one in conda-forge?
@jerowe What do you think?

Currently, only 2 recipes are using it here (`abyss`  and `oases`).

Bérénice

**Comment by keuv-grvl** [comment]
OpenMPI is a general purpose software, so it would fit better at conda-forge. Moreover, there are 7 contributors on https://github.com/conda-forge/openmpi-feedstock, so it's a big help for us.

**Comment by jerowe** [comment]
Lets get rid of it then. I probably stole the recipe from conda-forge anyways. ;-)

**Comment by bgruening** [comment]
Agree, please create a PR that removes the recipe, I will move it to the bioconda-legacy channel afterwards.

**Comment by bgruening** [comment]
The package is now migrated to bioconda-legacy.

**Comment by bebatut** [comment]
Thanks @bgruening

**Comment by epruesse** [comment]
This caused a regression for `conda install sina`, which requires `arb-bio`, which requires `phyml=3.2.0`, which requires `openmpi=2`, which is no longer available.

**Comment by epruesse** [comment]
@bioconda/core Anyone have an idea of how to fix this? The current versions of `sina`, `arb-bio`, and `phyml` are effectively no longer installable, breaking reproducibility.

**Comment by kyleabeauchamp** [comment]
Presumably we could have the conda-forge folks createa  openmpi=2 recipe?

**Comment by bgruening** [comment]
The openmpi story should be much better these days. Feel free to reopen if needed.
