### ISSUE TITLE
Support for numpy v1.12

### ISSUE THREAD

**Issue by chapmanb** [bioconda/bioconda-recipes#3961]
@bioconda/core I'm working on updating CNVkit, which uses a recent pandas (0.19.x series) that is only built with numpy 1.11 and 1.12. Since bioconda is using 1.10 in `env_matrix.yml` packages like bx-python that build against numpy are incompatible with the 0.19.x pandas version.

Would it be possible to add 1.12 to `env_matrix.yml`? I don't understand enough about the magic behind this to understand how best to do this and update numpy dependent packages. Thanks much.

**Comment by johanneskoester** [comment]
Yes, but so far our policy was to only support build against one version of everything (except Python). Hence I'd say we simply switch to 1.12 now. Can we wait until the boost update is completed?

**Comment by chapmanb** [comment]
That would be perfect, working on it after the boost change makes a lot of sense. Thanks so much for coordinating all this.

**Comment by rvalieris** [comment]
just FYI, env_matrix was since updated to use numpy 112, here: https://github.com/bioconda/bioconda-recipes/pull/4888

**Comment by bgruening** [comment]
We have switched to conda-forge pinning in the meantime and I think this is solved. Please feel free to reopen if this issue still exists.
