### ISSUE TITLE
Update fastqc version

### ISSUE THREAD

**Issue by ekushele** [bioconda/bioconda-recipes#39692]
Hello,

There is a new version of fastQC that fixes the "out of memory" issues" (https://github.com/s-andrews/FastQC/issues/86#issuecomment-1450370599).
I tried to update the fastQC recipe, but I could only do that from my master branch, where I had an open PR already for adding meth_atlas package (https://github.com/bioconda/bioconda-recipes/pull/39192#issue-1572462338)

Anyway, updating fastQC fails because of the patch file. 

How can I fix it? 
CC @dpryan79 because you made the last commit to this recipe...

Thank you!

**Comment by dpryan79** [comment]
Thanks for the heads up, I've made a new PR: https://github.com/bioconda/bioconda-recipes/pull/39731

I also changed the source of the package to github so PRs can be autogenerated for new releases.
