### ISSUE TITLE
Delly recipe not using parallel version

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#3988]
@tobiasrausch is it right that the delly recipe does not use the parallel version of the binary? If so, can we replace it by the parallel build? Your release notes don't mention against which linux distribution it has been built. Alternatively, we could build from source, but I guess you had your reasons to use the binary in PR #2686, right?

**Comment by tobiasrausch** [comment]
The delly recipe is the pre-compiled (CentOS 5.3), single CPU binary. It would be nice to have both the delly-parallel and the single CPU delly version but that was beyond my bioconda recipe building skills. Feel free to replace the recipe or rebuild from source, thanks in advance.

**Comment by johanneskoester** [comment]
Ok, done!

**Comment by johanneskoester** [comment]
I have decided to only have the parallel version for now. Would there be a particular advantage to also have the single core version?
