### ISSUE TITLE
Error in Lint for a number of PRs

### ISSUE THREAD

**Issue by kmnip** [bioconda/bioconda-recipes#39986]
Quite a few PRs are stuck in `bioconda.bioconda-recipes (lint lint)`:
https://github.com/bioconda/bioconda-recipes/pull/39980
https://github.com/bioconda/bioconda-recipes/pull/39978
https://github.com/bioconda/bioconda-recipes/pull/39972
https://github.com/bioconda/bioconda-recipes/pull/39971
https://github.com/bioconda/bioconda-recipes/pull/39969

They all have the same error:
> An error occurred while provisioning resources (Error Type: Disconnect).

I am wondering if there is something wrong with the Azure pipelines?

**Comment by fenderglass** [comment]
Can confirm about https://github.com/bioconda/bioconda-recipes/pull/39978. Looks like the some of the PRs are getting through, the latest merge was ~12 hours ago, and the earliest PR here is ~2 days ago.

**Comment by andrewprzh** [comment]
Same happens for https://github.com/bioconda/bioconda-recipes/pull/40115

**Comment by daler** [comment]
Should be fixed now in #40071
