### ISSUE TITLE
Build task for bioconda-recipes fails (installation of bioconda-utils times out?)

### ISSUE THREAD

**Issue by kostrykin** [bioconda/bioconda-recipes#39999]
For some reason, the build task for bioconda-recipes is failing:

- https://github.com/bioconda/bioconda-recipes/pull/39994 (automatically generated PR)
- https://github.com/bioconda/bioconda-recipes/pull/39996 (manually created PR)

As far as I can tell, this is caused by a timeout of the installation of bioconda-utils:
<img width="574" alt="Bildschirm­foto 2023-03-20 um 23 38 15" src="https://user-images.githubusercontent.com/6557139/226481407-c08c0b79-f4db-4588-b529-f213bfe53c3c.png">

But why does this happen, and how to fix it?

**Comment by kostrykin** [comment]
probably a duplicate of #39986

**Comment by daler** [comment]
Should be fixed now in #40071
