### ISSUE TITLE
Unable to get the latest GATK4 update via Bioconda

### ISSUE THREAD

**Issue by stefmldk** [bioconda/bioconda-recipes#39992]
According to the documentation for the GATK4 package under Bioconda, the latest version was updated three days ago (same time as it was updated on GitHub) to version 4.4.0.0 and this is also the version that is associated with the main label. However, when I try to install with conda/mamba without specifying a version number, I end up with version 4.3.0.0. If I specify the version number to be 4.4.0.0, I get an error:

conda install -c bioconda gatk4=4.4.0.0

PackagesNotFoundError: The following packages are not available from current channels:

  - gatk4=4.4.0.0

**Comment by marcelm** [comment]
This is essentially #39943. I suggest to discuss over there and close this issue.

**Comment by johanneskoester** [comment]
CDN seems to be in sync again!
A side note:
the recommended command for installations is mamba, which is much faster than conda. Also note that using bioconda requires you to also use the conda-forge channel:

```
mamba install -c conda-forge -c bioconda gatk4=4.4.0.0
```
