### ISSUE TITLE
Missing dependency for salmon 0.8.0 in the linux-64 channel?

### ISSUE THREAD

**Issue by tomsing1** [bioconda/bioconda-recipes#4014]
I am running into problems installing *salmon* version 0.8.0 via conda.
The following code was executed on a fresh AWS EC2 instance running the stock ubuntu 16.04 image:

```
wget -q https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
chmod +x miniconda.sh
./miniconda.sh   # manually accepted the licensing terms
export PATH=/home/ubuntu/miniconda2/bin:$PATH
conda install -c bioconda salmon=0.8.0
```

This produced the following output:

```
Fetching package metadata: ......
Solving package specifications: .
Error:  Dependency missing in current linux-64 channels:
  - salmon 0.8|0.8.0* -> icu 56.*

You can search for this package on anaconda.org with

    anaconda search -t conda icu 56.*

You may need to install the anaconda-client command line client with

    conda install anaconda-client
```

I saw that @acaprez added the salmon 0.8.0 recipe and also noticed that @bgruening just merged pull request  #3918  referencing salmon. Perhaps you can provide some input?

Thanks a lot!
Thomas

**Comment by bgruening** [comment]
Hi @tomsing1, can you please check if you have `-c conda-forge` actiavted as well?
The recent merge was just a rebuild against the latest boost version.

**Comment by tomsing1** [comment]
Thanks a lot @bgruening . Adding `conda-forge` fixed my problem. I should've followed the instructions on the [bioconda page](https://bioconda.github.io/index.html#set-up-channels)...

```
conda install -c bioconda -c conda-forge salmon=0.8.0
```
