### ISSUE TITLE
Homer: C programs have not been compiled

### ISSUE THREAD

**Issue by yhoogstrate** [bioconda/bioconda-recipes#4033]
The following binaries are missing in the Homer package:

 - findPeaks
 - genomeOntology
 - getDifferentialPeaks
 - getGenomeTilingPeaks
 - getMappableRegions
 - getPeakTags
 - homer
 - homer2
 - HomerConfig.pm
 - HomerSVGLogo.pm
 - homerTools
 - makeTagDirectory
 - makeUCSCfile
 - mergePeaks

@BioNinja, are you able to fix this?

**Comment by rioualen** [comment]
Hello, 
Any update about the issue?

**Comment by BioNinja** [comment]
since the bioconda  build system changes alot，I'm afraid that I have no idea what happened and could not fixed this now. Sorry for all. I need some time to check the source code
