### ISSUE TITLE
linting follow-up

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#4056]
So . . . rolling out the linting did not go smoothly. Sorry for the inconvenience, everyone. I think I've fixed everything, but it's been difficult trying to get anything to run -- all day https://www.traviscistatus.com has had a backlog of 700+ OSX jobs, so each change takes hours to test.

Anyway, now that #4055 and https://github.com/bioconda/bioconda-utils/pull/75 are merged hopefully things should be working better.

By my reckoning the build system problems affected PRs from the following people:

- @acaprez
- @johanneskoester
- @cokelaer
- @chapmanb
- @jerowe
- @marcelm
- @ccwang002
- @shawnzhangyx
- @mdehollander

For those of you that merged PRs into master, but your packages are not appearing in the conda channel, can you please bump the build numbers and submit another PR? For those of you with unmerged PRs can you please update it with the changes in master? Note that I had to add some recipes to the `build-fail-blacklist` to get other jobs to pass:

recipes/gdsctools
recipes/delly
recipes/perl-hpc-runner-command

Once things are running smoothly again we can try removing [this env var](https://github.com/bioconda/bioconda-recipes/pull/4055/files#diff-354f30a63fb0907d4ad57269548329e3R23) to go back to the faster filtering.

**Comment by johanneskoester** [comment]
Thanks @daler! A quick note: it should not be necessary to bump the build numbers. Together with the recent commit-based building of packages, I have introduced a cron job that will build all packages on master that are not yet in the channel once a day. Hence, we just have to wait a bit.

**Comment by johanneskoester** [comment]
@daler, there is still something going wrong: https://travis-ci.org/bioconda/bioconda-recipes/jobs/208894085#L465

1. I merged my recent delly PR, but it thinks that env_matrix changed or the build was triggered with a cron job, and therefore wants to consider all recipes.
2. It lints all recipes because of this (and fails of course). I think we should deactivate linting if all recipes are considered.

**Comment by johanneskoester** [comment]
I hope to have fixed 2. in #4062.

**Comment by daler** [comment]
Thanks @johanneskoester, didn't realize the cron was actually building. And you're right linting is unnecessary on master. The only thing I can think of it catching is another channel adding the same package in the time between submitting a PR and merging to master. That's unlikely to happen and not a big deal even if it does.

Am I reading the travis history correctly in that the same delly merge was tested in both builds 15191 and 15198? I can't figure out why the second one thought the env_matrix changed or cron was true. Are there any cron jobs that would merge to master?

**Comment by johanneskoester** [comment]
Yes, there is one every day. Maybe that was the problem. I just though that it would not contain the merge message, but apparently it does then.

**Comment by johanneskoester** [comment]
@daler, apparently the build system still tries to filter all recipes although I am in a pull request where I only have one recipe changed:
https://travis-ci.org/bioconda/bioconda-recipes/jobs/208983816#L479
Are you sure the git diff inside bioconda-utils does the right thing?

Pull request #4046.

**Comment by daler** [comment]
Yes, that was intentional as a temporary way of building all the recipes that were missed due to the build issues, which wouldn't otherwise show up as changed in the commit range. Now I know that the cron job would have done the same thing, I just had to wait ;)

Anyway we just need to remove this line:

https://github.com/bioconda/bioconda-recipes/pull/4055/files#diff-354f30a63fb0907d4ad57269548329e3R23

which is used here:

https://github.com/bioconda/bioconda-recipes/pull/4055/files#diff-a666270151818014dbda5ced5b3bc54eR76

I was planning on waiting for things to go smoothly with the linting before re-enabling that. It seems like things have stabilized so I'll go ahead and re-enable.

**Comment by johanneskoester** [comment]
I see, thanks!

**Comment by daler** [comment]
xref #4070

**Comment by bgruening** [comment]
Linting works fantastic now. Thanks a lot @daler for all your work here!
