### ISSUE TITLE
Sync Python support with Conda-forge

### ISSUE THREAD

**Issue by nsoranzo** [bioconda/bioconda-recipes#4063]
Our env matrix for building Python packages is:
```
CONDA_PY:
  - 27
  - 34
  - 35
```

New conda-forge packages are now built using the following env matrix:
```
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
```

That's been confirmed to me on conda-forge gitter channel.

**Comment by druvus** [comment]
The env matrix is now in sync with conda-forge.
