### ISSUE TITLE
issues compiling glimmerHMM

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#4073]
Hi Team Bioconda,

I've [stubbed out a recipe for glimmerHMM](https://github.com/zachcp/bioconda-recipes/commit/8a5c464005db829be2feac181e4b8dd3cf6c5f87) which is tricky for a few reasons:

  1. non-flat source code organization (multiple directories)
  2. a data-training step results in non-executable data files that need to be stored in a directory somewhere.
  3. the C code is not compiling.

Although I am not sure about 1 and 2, I am currently stuck on 3 with the a message about malloc.h:

```
cd sources
make

6 warnings generated.
g++ -g -c util.c
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
util.c:4:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
```

After a bit of googling that told me that I could replace the <malloc.h> with <stdlib.h> I changed the lines but end up with a new error:

```
# can use this to get stdlib. However he executables segfault.
sed -ibak "s/#include <malloc.h>/#include <stdlib.h>/g" sources/util.c
sed -ibak "s/#include <malloc.h>/#include <stdlib.h>/g" sources/oc1.h
sed -ibak "s/#include <malloc.h>/#include <stdlib.h>/g" train/utils.c


# new warnings when compiling
6 warnings generated.
g++  -Wall -g build2.c -o build2 -lm
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
build2.c:67:11: warning: unused variable 'P' [-Wunused-variable]
  char  * P;
          ^
build2.c:410:9: warning: unused variable 'i' [-Wunused-variable]
   int  i, j, A, Div_By, Mod_By;
        ^
build2.c:26:12: warning: unused variable 'DEBUG' [-Wunused-const-variable]
const int  DEBUG = 0;
           ^
build2.c:28:12: warning: unused variable 'FALSE' [-Wunused-const-variable]
const int  FALSE = 0;
           ^
build2.c:35:12: warning: unused variable 'DEFAULT_START_POSITION' [-Wunused-const-variable]
const int  DEFAULT_START_POSITION = 0;
           ^
build2.c:36:12: warning: unused variable 'DEFAULT_STOP_POSITION' [-Wunused-const-variable]
const int  DEFAULT_STOP_POSITION = 79;

...
...

any many more like this...
```

I'm hoping these messages and their fix will be obvious to someone with more C/C++ experience. If you have any pointers on 3) it will definitely be appreciated.  

Thanks,
zach cp

**Comment by bgruening** [comment]
@zachcp this malloc error, do you only see it at OSX? If so try using GCC on OSX as well.

**Comment by zachcp** [comment]
thanks @bgruening . While using GCC allows the Makefile to run and build an executable, the executable causes Seg faults.  I've tried changing the CFlags but I can't seem to get it to build. The frustrating thing is that I can build the packages locally with the native Make/clang although I can't build locally with conda.

**Comment by tseemann** [comment]
@zachcp isn't the problem that you are using `g++` rather than `gcc` to compile vanilla C code?

**Comment by zachcp** [comment]
@tseemann thanks for the pointer! I should be able to patch it from here.

**Comment by zachcp** [comment]
hmmm... looks like there are issues whether I use the gcc compiler or clang. Here is the output using gcc.

```
+ make
CC -g -c glimmerhmm.c
In file included from glimmerhmm.c:1:
./delcher.h:41:1: error: unknown type name 'template'
template <class DT>
^
./delcher.h:41:10: error: expected identifier or '('
template <class DT>
         ^
./delcher.h:43:1: error: unknown type name 'template'
template <class DT>
^
./delcher.h:43:10: error: expected identifier or '('
template <class DT>
         ^
...
...
...
```
(Looks like others have [run into this issue before](http://stackoverflow.com/questions/43136340/cannot-compile-c-code-on-mac))

**Comment by luke-c-sargent** [comment]
I found a workaround to this problem by replacing instances of
`#include <malloc.h>`
with
`#include <malloc/malloc.h>`

using your recipe's example,
```
sed -i.bak "s~#include <malloc.h>~#include <malloc/malloc.h>~g" sources/util.c
sed -i.bak "s~#include <malloc.h>~#include <malloc/malloc.h>~g" sources/oc1.h
sed -i.bak "s~#include <malloc.h>~#include <malloc/malloc.h>~g" train/utils.c
```

There's still the truckload of warnings, but running `make` in `sources/` and `train/` creates executables that print their Usage and Options information on execution.
```
/t/G/sources ❯❯❯ file glimmerhmm
glimmerhmm: Mach-O 64-bit executable x86_64
/t/G/sources ❯❯❯ glimmerhmm
USAGE:  glimmerhmm <genome1-file> <training-dir-for-genome1> [options] 
Options:
-p file_name     If protein domain searches are available, read them from file file_name
-d dir_name      Training directory is specified by dir_name (introduced for compatibility with earlier versions)
-o file_name     Print output in file_name; if n>1 for top best predictions, output is in file_name.1, file_name.2, ... , file_name.n f
-n n             Print top n best predictions
-g               Print output in gff format
-v               Don't use svm splice site predictions
-f               Don't make partial gene predictions
-h               Display the options of the program
```
I haven't tested it super thoroughly, so _caveat emptor_

**Comment by zachcp** [comment]
@luke-c-sargent awesome! I'll give this a whirl and see how it works. Thank you!

**Comment by zachcp** [comment]
Hi @luke-c-sargent ,

I'm finally looping back around to this issue but still get segfaults when building. Id you have a few minutes could you try building against my branch and seeing if it passes? Thanks.

zach cp

GlimmerHMM Branch
https://github.com/zachcp/bioconda-recipes/tree/glimmerHMM

**Comment by luke-c-sargent** [comment]
gave it a clone, it builds as expected but does indeed segfault for me when running `meta.yml`'s test:
`glimmerhmm -v` 
though it's worth noting that `-v` is a functional argument ('Don't use svm splice site predictions') and does not output the version -- `glimmerhmm -h` or the functionally equivalent `glimmerhmm` might be more appropriate for basic output.

testing on linux, `glimmerhmm -v` doesn't cause a segfault; it does nothing but output a newline. I suppose the real determination will be running test data and ensuring valid results, though it segfaulting on one platform and not another in the `-v` case does not fill me with confidence.

**Comment by zachcp** [comment]
Ah, I see  about `glimmerhmm -v`. The failure is not a build failure as `glimmerhmm -h` passes. This is excellent. I can build and test it out on some actual data. Maybe there is a super-simple data test that can be performed as well. 

Thank you!
zcp

**Comment by mdehollander** [comment]
Hi,

Today I started building a package for GlimmerHMM as well, because it is a dependency of another program. I did not find it in bioconda yet, therefore I started a fresh one, being unaware of this issue and the GlimmerHMM branch from @zachcp. My build for linux went fine, but the osx build gave a malloc.h error. Thats how I ended up here.

What is the current status of the package? Does it build on linux and osx? Is there already a pull request?

You can find the branch I made today here: https://github.com/mdehollander/bioconda-recipes/tree/glimmerhmm/recipes/glimmerhmm

Notice that `glimmerhmm -v` will not give you the version, like most programs do:
```
/glimmerhmm -h
USAGE:  ./glimmerhmm <genome1-file> <training-dir-for-genome1> [options] 
Options:
-p file_name     If protein domain searches are available, read them from file file_name
-d dir_name      Training directory is specified by dir_name (introduced for compatibility with earlier versions)
-o file_name     Print output in file_name; if n>1 for top best predictions, output is in file_name.1, file_name.2, ... , file_name.n f
-n n             Print top n best predictions
-g               Print output in gff format
-v               Don't use svm splice site predictions
-f               Don't make partial gene predictions
-h               Display the options of the program
```

On linux it builds also without the `malloc.h` trick, so the `sed` command can also be moved within the if statement I think.

**Comment by zachcp** [comment]
Hi @mdehollander,

I've built and pulled the modified glimmerHMM package. https://github.com/bioconda/bioconda-recipes/pull/4884 .  This builds fine (osx/linux) and works locally (osx).

zcp

**Comment by mdehollander** [comment]
Great! Thanks.
