### ISSUE TITLE
_static files for docs not being copied

### ISSUE THREAD

**Issue by tomkinsc** [bioconda/bioconda-recipes#4108]
It looks like the files in `docs/_static/` are not being copied to [bioconda.github.io/_static/](https://github.com/bioconda/bioconda.github.io/tree/master/_static). Any ideas what may have changed that? The `conf.py` file [appears](https://github.com/bioconda/bioconda-recipes/blob/master/docs/conf.py#L158) to still have the same path defined.

**Comment by bgruening** [comment]
@tomkinsc this looks like a regression from the new build system.
ping @bioconda/core 
I might have time to look into this tomorrow.

**Comment by johanneskoester** [comment]
@tomkinsc are you sure? To me it looks like the just did not change in the last weeks. Is anything missing?

**Comment by johanneskoester** [comment]
I guess what you might mean is what I try to fix in PR bioconda/bioconda-utils#83.

**Comment by johanneskoester** [comment]
Ok, the badge generator is back online.

**Comment by tomkinsc** [comment]
Thanks, Johannes!
