### ISSUE TITLE
OSX package not uploaded to Anaconda

### ISSUE THREAD

**Issue by joverlee521** [bioconda/bioconda-recipes#41103]
The Auspice 2.46.0 [passed CI](https://github.com/bioconda/bioconda-recipes/actions/runs/5049250974) and I see the Linux package is on Anaconda. However, the OSX package is still on v2.45.1 on Anaconda.  

I think this is due to the `OSX Upload` job missing the `--anaconda-upload` flag?
https://github.com/bioconda/bioconda-recipes/blob/c2aa3a4e6aa8cab177ea9d1eef64ebbfa15f0cf0/.github/workflows/master.yml#L132-L133

**Comment by corneliusroemer** [comment]
@joverlee521 do you think it's that line here that shows the problem?
https://github.com/bioconda/bioconda-recipes/actions/runs/5049250974/jobs/9058455974#step:8:1204

**Comment by dpryan79** [comment]
Shit, yes, that's the problem. The good news is that the nightly uploader should catch this. I'll push a fix real quick.

**Comment by corneliusroemer** [comment]
Thanks a lot for all your work!

**Comment by corneliusroemer** [comment]
Seems to be fixed now, I just got the `osx` package:
```
  - auspice              2.45.1  h7133b54_2    bioconda                     
  + auspice              2.46.0  hb19a6fa_0    bioconda/osx-64         100MB
```

**Comment by dpryan79** [comment]
Excellent :)

**Comment by joverlee521** [comment]
Thank you both! This update did get uploaded in the [nightly uploader](https://github.com/bioconda/bioconda-recipes/actions/runs/5052470555/jobs/9065345036#step:8:23123) before the job timed out.

**Comment by corneliusroemer** [comment]
Silly me, nextstrain-cli is noarch
