### ISSUE TITLE
Including mamba (and therefore conda) as a dependency causes problems in Snakemake

### ISSUE THREAD

**Issue by tdido** [bioconda/bioconda-recipes#41477]
The [inclusion of mamba in the Snakemake recipe](https://github.com/bioconda/bioconda-recipes/blob/102ff47f2dcb9a66fac5c665d07ac9d22a670027/recipes/snakemake/meta.yaml#L28) results in conda also being installed. If this happens in an environment other than base this breaks Snakemake's ability to activate conda envs by name. See [this issue](https://github.com/snakemake/snakemake/issues/2288) for more details.

Is it OK to have conda/mamba installed in an environment other than base?

**Comment by mfansler** [comment]
No, it is not okay to install Conda or Mamba in another environment. It can lead to unexpected behavior. As per [the Mamba documentation](https://mamba.readthedocs.io/en/latest/installation.html#installation):

> *"Installing `mamba` into any other environment than **base** is not supported."*
