### ISSUE TITLE
OSX builds fail with ``KeyError: 'https://conda.anaconda.org/conda-forge'``

### ISSUE THREAD

**Issue by f0t1h** [bioconda/bioconda-recipes#41526]
```
22:36:43 BIOCONDA ERROR COMMAND FAILED (exited with 1): /opt/mambaforge/envs/bioconda/bin/conda mambabuild --override-channels --no-anaconda-upload -c conda-forge -c bioconda -c defaults -e /opt/mambaforge/envs/bioconda/conda_build_config.yaml -e /opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml recipes/tksm/meta.yaml
22:36:43 BIOCONDA ERROR STDOUT+STDERR:

```
```
Traceback (most recent call last):
  File "/opt/mambaforge/envs/bioconda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/build.py", line 2038, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/render.py", line 787, in expand_outputs
    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/metadata.py", line 2524, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/metadata.py", line 884, in finalize_outputs_pass
    fm = finalize_metadata(
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/render.py", line 547, in finalize_metadata
    build_unsat, host_unsat = add_upstream_pins(m,
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/render.py", line 387, in add_upstream_pins
    build_deps, build_unsat, extra_run_specs_from_build = _read_upstream_pin_files(m, 'build',
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/render.py", line 374, in _read_upstream_pin_files
    deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/render.py", line 131, in get_env_dependencies
    actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 141, in mamba_get_install_actions
    solution = solver.solve_for_action(_specs, prefix)
    return to_action(
  File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/core/solver.py", line 79, in to_action
    entry = lookup_dict[get_url_from_channel(c)]
KeyError: 'https://conda.anaconda.org/conda-forge'
```

PR: https://github.com/bioconda/bioconda-recipes/pull/41444
Azure log: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=34916&view=logs&j=1b052f1d-4456-52f0-9d43-71c4c5bd734d&t=edc48dcd-1fc2-5e3b-7036-7be9cea00123&l=651

**Comment by bluenote-1577** [comment]
I appear to have the same issue as well. 

PR: https://github.com/bioconda/bioconda-recipes/pull/41525
Log: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=34918&view=logs&jobId=3e927886-88a5-5ae4-09f7-f53fa1a22322&j=3e927886-88a5-5ae4-09f7-f53fa1a22322&t=577c9198-bb4c-5a92-f06b-21e420caadce

**Comment by guilledufort** [comment]
Hi,

I'm having the same issue as well.
PR: [#41553](https://github.com/bioconda/bioconda-recipes/pull/41553/commits)
[Log](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=35062&view=logs&j=1b052f1d-4456-52f0-9d43-71c4c5bd734d&t=edc48dcd-1fc2-5e3b-7036-7be9cea00123)

**Comment by siebrenf** [comment]
This issue does not affect `noarch: python` builds as they don't run `mambabuild`.
This issue does not affect all OSX builds. PR #41511 ran `mambabuild` successfully.

One of my tests failed ([log](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=35075&view=logs&jobId=1b052f1d-4456-52f0-9d43-71c4c5bd734d&j=1b052f1d-4456-52f0-9d43-71c4c5bd734d&t=edc48dcd-1fc2-5e3b-7036-7be9cea00123)), but succeeded when limiting it to pyton 3.7 ([log](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=35082&view=logs&j=1b052f1d-4456-52f0-9d43-71c4c5bd734d&t=edc48dcd-1fc2-5e3b-7036-7be9cea00123)) (no idea why yet).

**Comment by mbhall88** [comment]
I'm also seeing this in a Rust recipe on #41579

**Comment by raufs** [comment]
I also am seeing this issue: https://github.com/bioconda/bioconda-recipes/pull/41548

**Comment by gongyh** [comment]
I also am seeing this issue: https://github.com/bioconda/bioconda-recipes/pull/41619

**Comment by melkebir** [comment]
We're seeing this same issue: #41585

**Comment by mrvollger** [comment]
I am also seeing this in: https://github.com/bioconda/bioconda-recipes/pull/41663

**Comment by sebschmi** [comment]
Also happening in #41600

**Comment by mboudet** [comment]
Same issue in #41659

**Comment by milot-mirdita** [comment]
I tried to understand a bit what's going on. I didn't get very far yet but maybe its a hint.

I installed bioconda-utils locally and ran it. I am running on an ARM mac with `CONDA_SUBDIR=osx-64` set.

The key that exist in the `lookup_dict` is `https://conda.anaconda.org/conda-forge/osx-64`. While the requested key is `https://conda.anaconda.org/conda-forge`.

After adding the debug statements I tried to update to boa 0.15.1, which first didn't work because it was trying to download the following file:
`https://conda.anaconda.org/conda-forge/mamba-1.4.2-py38h2cdcfb1_0.conda`
instead of:
`https://conda.anaconda.org/conda-forge/osx-64/mamba-1.4.2-py38h2cdcfb1_0.conda`

This seems a rather similar symptom.

I deleted the package cache and it could install boa 0.15.1 successfully. However, this version immediately segfaults.

These are my current findings, not sure what to make out of these. Somewhere/something seems to contain the wrong channel url without the OS subdir.

**Comment by milot-mirdita** [comment]
I was playing a bit more with this. Still don't understand where the wrong(?) channel name comes from. But if I add a hack to `boa` I can get the build to proceed:
```
def to_action(specs_to_add, specs_to_remove, prefix, to_link, to_unlink, index):
    to_link_records = []

    prefix_data = PrefixData(prefix)
    final_precs = IndexedSet(prefix_data.iter_records())

    lookup_dict = {}
    for _, entry in index:
        lookup_dict[
                entry["channel"].platform_url(entry["platform"], with_credentials=False)
        ] = entry
+        if entry["url"].replace("/osx-64", "") != entry["url"]:
+            lookup_dict[entry["url"].replace("/osx-64", "")] = entry
```

The name error is a separate and probably unrelated issue on my mac, not sure why that happens locally but the perl build dependency in the recipe I was testing was causing the issue (it has some weird dependency that includes `*_perl5` which dies somewhere deep in `conda-build`.

I tried to track down how `to_link` is built but ended up in the guts of the `libmamba` C++ code and didn't feel like spelunking further.

**Comment by skoren** [comment]
Also in #41724. Any updates or fixes? This has been an issue for weeks now. Between this and the fact that my previously working recipe was broken by maintenance changes and blacklisted last month, it seems bioconda has become a bit unreliable.

**Comment by mbhall88** [comment]
Any updates @bioconda/core?

**Comment by rplanel** [comment]
Same issue in: #41681

**Comment by bernt-matthias** [comment]
Seems that the `python >=3` workaround does not help (in general). In https://github.com/bioconda/bioconda-recipes/pull/41672 there is no python requirement.

**Comment by dpryan79** [comment]
I suspect the cases where adding >=3 prevents this are cases where the wrong packages are then getting built. I honestly haven't had a chance to track this down. I've been hoping that one of the other core members would pop into this thread with the solution to this issue, but I suspect we'll have to open an issue with boa/libmamba and get the author's help there.

**Comment by skoren** [comment]
Thanks for the info @dpryan79. Sounds like an updated mamba release should fix that when it is ready.

**Comment by johanneskoester** [comment]
This is now fixed with the update to bioconda-utils 2.3.2 which uses boa 0.15.

**Comment by johanneskoester** [comment]
For those of you who have circumvented the issue by deactivating the osx build, it would be great if you could enable them again in follow-up PRs! Thanks a lot! It is always great to see how active the bioconda community is!

**Comment by marcelm** [comment]
This seems to have re-appeared in the following PRs:
* #42912
* #42914
* #42918
* #42930
