### ISSUE TITLE
My very basic rule does not build on mac anymore

### ISSUE THREAD

**Issue by sebschmi** [bioconda/bioconda-recipes#41677]
Please see this pull request: https://github.com/bioconda/bioconda-recipes/pull/41600

It does a very basic build of a Rust tool, but gives no indication as to why it fails on Mac. Could someone provide some support?

**Comment by siebrenf** [comment]
It's not (just) you: #41526. No solution in sight yet :(

**Comment by sebschmi** [comment]
Thanks for the link! Will close this as duplicate.
