### ISSUE TITLE
PR passed, but merge failed

### ISSUE THREAD

**Issue by bkille** [bioconda/bioconda-recipes#41746]
Hi,

MashMap v3.0.5 was [recently merged](https://github.com/bioconda/bioconda-recipes/pull/41711), but it seems to have [failed the CI](https://github.com/bioconda/bioconda-recipes/runs/14620701261) after merging and is not available for download. Do we need to create a new PR, or is there another way to push it through?

Thanks!

**Comment by mjsteinbaugh** [comment]
Thanks @bkille , bioconda's dealing with some infrastructure issues at the moment -- let's table this for a couple of days a revisit
