### ISSUE TITLE
version update?

### ISSUE THREAD

**Issue by cristhomas** [bioconda/bioconda-recipes#4174]
I can't find info on this, apologies if it's obviously somewhere I missed. 
Do I have this right that the version of a package is controlled by the 'version' at the top of the meta.yaml? If so, how long does it take for a new version to show up in the bioconda channel? 
Thank you...!

**Comment by bgruening** [comment]
Your package is rebuild again on the master branch, if this succeeds again you package is pushed to the channel. This can take some time, depending on travis and how many other PR are scheduled at the moment - currently a lot. Sorry :(
