### ISSUE TITLE
Conda cannot install samtools 1.17

### ISSUE THREAD

**Issue by Ge0rges** [bioconda/bioconda-recipes#42007]
Hello, 

I am trying to install samtools 1.17 on a Linux-based server. I create and environment then run: `conda install -c bioconda samtools` based on [this website](https://anaconda.org/bioconda/samtools). When I try to run it I get the following dependency error: `samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`.

Any help is appreciated.

**Comment by mjsteinbaugh** [comment]
Hi @Ge0rges,

I think you're running into trouble by installing samtools into your base environment. Try this:

- Uninstall conda
- Reinstall conda
- Create a samtools environment
- Activate the samtools environment
- Then run the install command posted above

Does that help resolve the issue?

Best,
Mike

**Comment by Ge0rges** [comment]
Hi Mike,

I was attempting to install it in its own environment already, but tried again for sanity's sake and obtained the same result.

**Comment by mjsteinbaugh** [comment]
OK thanks that's helpful -- I'll see if I can reproduce as well

**Comment by mfansler** [comment]
The command `conda install -c bioconda samtools` is invalid.<sup>**1**</sup> Rather, one must always prioritize Conda Forge:

``` bash
conda install -c conda-forge -c bioconda samtools
```

---

<sub>**[1]:** Rather annoyingly, Anaconda Cloud does not permit customization of the install commands that are shown on the site. These are automatically displayed and rather misguided.</sub>

**Comment by Ge0rges** [comment]
I confirm that worked.
