### ISSUE TITLE
Question / debug: Autobump and automations

### ISSUE THREAD

**Issue by holtjma** [bioconda/bioconda-recipes#42176]
Hello,

I recently submitted a PR to bioconda-utils (https://github.com/bioconda/bioconda-utils/pull/896) with the intent of enabling autobump in for the "hiphase" recipe.  When I run it locally, I get what I expect in terms of updating to latest:
```
$ bioconda-utils autobump recipes/ config.yml --packages hiphase --loglevel debug
...
13:48:37 BIOCONDA WARNING Finished update
13:48:37 BIOCONDA INFO Unrecognized URL stats:
13:48:37 BIOCONDA INFO 
13:48:37 BIOCONDA INFO Recipe status statistics:
13:48:37 BIOCONDA INFO Updated: 1
13:48:37 BIOCONDA INFO SUM: 1
```

And changes work great:
```
$ git diff recipes/hiphase/meta.yaml
diff --git a/recipes/hiphase/meta.yaml b/recipes/hiphase/meta.yaml
index 1b3094ade2..b5d2503597 100644
--- a/recipes/hiphase/meta.yaml
+++ b/recipes/hiphase/meta.yaml
@@ -1,6 +1,6 @@
 {% set name = "hiphase" %}
-{% set version = "0.8.1" %}
-{% set hiphase_sha256 = "92d02cd089183d076563a48bb81665c9a33603bb99635578babe5c5f716edaeb" %}
+{% set version = "0.10.2" %}
+{% set hiphase_sha256 = "2a20fc437ab5c0f2437246e8a36e7590c68f5ae5caa0cecb8e85a371f5357c6c" %}
 
 package:
   name: {{ name }}
```

What I can't figure out is why this did not automatically create a PR here via autobump.  My understanding was that once the issue was fixed, a version cut, and then updated in [common.sh](https://github.com/bioconda/bioconda-common/blob/master/common.sh), it would "just work".  Am I missing a part of the process for autobump to function correctly, or is something still broken for this recipe that is non-obvious to me?

**Comment by holtjma** [comment]
A similar recipe, `pbfusion`, is also having the same issue where autobump is working locally, but the recent update was not automatically captured.

**Comment by zeeev** [comment]
Yup, 0.3.0 has not posted yet.
https://github.com/PacificBiosciences/pbfusion/releases

**Comment by holtjma** [comment]
I did a bit more digging and stumbled into an area I didn't realize existed:

1. CircleCI is what is controlling autobump: https://github.com/bioconda/bioconda-utils/blob/master/.circleci/config.yml
2. The run and logs can be found here: https://app.circleci.com/pipelines/github/bioconda/bioconda-utils?branch=master
3. For both hiphase and pbfusion, it looks like we're hitting a rate limit on requests from GitHub, here is one example snippet:
```
...
14:07:22 [32mBIOCONDA INFO[0m Recipe hiphase: updating from remote bump/hiphase[0m
14:07:22 [32mBIOCONDA INFO[0m dnp-mapping had no changes[0m
14:07:23 [32mBIOCONDA INFO[0m provean had no changes[0m
14:07:23 [31mBACKOFF ERROR[0m Giving up get_text_from_url(...) after 1 tries (aiohttp.client_exceptions.ClientResponseError: 403, message='rate limit exceeded', url=URL('https://api.github.com/repos/PacificBiosciences/HiPhase/releases'))[0m
...
```

I'm not sure what the solution to this problem is, but this seems to be the obvious cause of the issue.

**Comment by jmarshall** [comment]
Is this GitHub API use authenticated via e.g. a user access token? The rate limit is [much higher for authenticated requests](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting).

Presumably mostly there is not a new release when we check. If we record an ETag or similar (possibly we already have a suitable modification datestamp to send) we can make these [requests conditionally](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#conditional-requests) and most of them will not count against rate limiting.

**Comment by holtjma** [comment]
Caveat everything below with, I would want some input from bioconda dev group as I could be wrong:

In the original PR that modified autobump, I did not use the GitHub API authentication (I was unaware of the API rate limits).  To my knowledge, this token is not being used by autobump, even if the token exists and is being used elsewhere in the process.  I put up a PR that basically dodges the API for now and instead just expands the location where it was originally hidden in the webpage.  

However, it sounds like using the API is the long-term correct solution, mainly for stability purposes as the web interface is subject to change (which is what broke it the first time).  Assuming the token is not currently generated or being used in autobump, we would likely need some buy-in from a core dev to help build and test this functionality, especially in the CI.  Also, given the quantity of recipes in bioconda, it's possible that we still hit the rate limit when authenticated.

**Comment by holtjma** [comment]
As of this PR (https://github.com/bioconda/bioconda-utils/pull/920), the autobump issue this question was created for is resolved.
