### ISSUE TITLE
blasr misses sawriter

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#4224]
Hi @bebatut and @druvus,
Could you please add [`sawriter`](https://github.com/PacificBiosciences/blasr/blob/f8bfa9c5565ae01ea669af872edaae5e55471d98/utils/makefile) to `blasr` recipe becuse `wgs-assembler`(https://github.com/bioconda/bioconda-recipes/issues/4176) requires it?

Thank you in advance

Michal

**Comment by bgruening** [comment]
I guess we can close this now? @mictadlo please reopen if not.
