### ISSUE TITLE
listed versus installed versions of recipes

### ISSUE THREAD

**Issue by vmkalbskopf** [bioconda/bioconda-recipes#4227]
On the recipe page for bowtie2 [http://bioconda.github.io/recipes/bowtie2/README.html](url), multiple versions are listed, up to version 2.3.0, the last major release. However, when  install it using the instructions, I get ver 2.2.5

How does one specify the version during installation?

**Comment by daler** [comment]
This seems to work:

```
conda create -n tmp-bowtie bowtie2

Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/ryan/miniconda3/envs/tmp-bowtie:

The following NEW packages will be INSTALLED:

    bowtie2:       2.3.0-py35_1       bioconda
    libgcc:        5.2.0-0
    openssl:       1.0.2k-1
    perl:          5.22.0.1-0         conda-forge
    perl-threaded: 5.22.0-pl5.22.0_12 bioconda
    pip:           9.0.1-py35_1
    python:        3.5.3-1
    readline:      6.2-2
    setuptools:    27.2.0-py35_0
    sqlite:        3.13.0-0
    tbb:           4.4_20150728-0     bioconda
    tk:            8.5.18-0
    wheel:         0.29.0-py35_0
    xz:            5.2.2-1
    zlib:          1.2.8-3

```
Do you already have bowtie2 in the environment you're installing it into? You may want `conda update bowtie2` instead in that case.

**Comment by vmkalbskopf** [comment]
Thanks You!

I initially installed it by condo install bowtie2
And that only gave me 2,5,0
The update command didn't work either.
But your command did work, so this is perfect.

**Comment by daler** [comment]
Strange. You might have something else in the environment that was pinning bowtie2 to an older version. Glad the new environment works.
