### ISSUE TITLE
problem with pysam from bioconda

### ISSUE THREAD

**Issue by Niazevedo** [bioconda/bioconda-recipes#4232]
Hi. I'm using a software that requires Pysam and this error is appearing. I downloaded Pysam with bioconda and it is already updated.

File "/Users/niazevedo/anaconda/lib/python2.7/site-packages/pysam/init.py", line 5, in
from pysam.libchtslib import *
ImportError: dlopen(/Users/niazevedo/anaconda/lib/python2.7/site-packages/pysam/libchtslib.so, 2): Library not loaded: @rpath/libhts.1.dylib
Referenced from: /Users/niazevedo/anaconda/lib/python2.7/site-packages/pysam/libchtslib.so
Reason: image not found

**Comment by kyleabeauchamp** [comment]
Thanks, I have confirmed that this is due to having HTSLib 1.4 installed.  We need to fix HTSLib=1.3.1 in the pysam recipe.  

cc https://github.com/pysam-developers/pysam/issues/421#issuecomment-288234929

**Comment by chapmanb** [comment]
Thanks for reporting this and working on it. We got a fixed version in now and the build should be available in 10 minutes or so. This pins to htslib 1.3.x which is compatible with pysam right now, and we'll update to pysam with 1.4 support once that gets released. Thanks again.
