### ISSUE TITLE
Help with committing recipe for Bioconda

### ISSUE THREAD

**Issue by theAguy** [bioconda/bioconda-recipes#42523]
Hi, I am new to Bioconda and having some difficulties with uploading a recipe.
The review fails in:
"bioconda.bioconda-recipes (lint lint)"
"bioconda.bioconda-recipes"
And I have no idea how to interpret these fails.

I would much appreciate any help with these fails.

Thank you very much in advance

**Comment by pdimens** [comment]
Click on the CI run itself in the PR and follow the link to the Azure pipeline:
![image](https://github.com/bioconda/bioconda-recipes/assets/19176506/4e740987-0f6e-4f2a-bc4b-355a9b5d29c8)

You may then click on the step:
![image](https://github.com/bioconda/bioconda-recipes/assets/19176506/c60e52a4-5458-4f1d-bf2b-37a9ea7522f4)

Once there, you can navigate to the output of the step:
![image](https://github.com/bioconda/bioconda-recipes/assets/19176506/10d34d90-645f-4b48-9b56-3f8e93808987)

**Comment by rpetit3** [comment]
@theAguy was this related to https://github.com/bioconda/bioconda-recipes/pull/42515

if so, ok to close?

**Comment by theAguy** [comment]
Yes, it was related to that.

Thank you very much!


Guy

‫בתאריך יום ו׳, 22 בספט׳ 2023 ב-21:27 מאת ‪Robert A. Petit III‬‏ <‪
***@***.***‬‏>:‬

**Comment by rpetit3** [comment]
thank you!
