### ISSUE TITLE
Failed to install bioconductor-genomeinfodbdata

### ISSUE THREAD

**Issue by wangzhichao1990** [bioconda/bioconda-recipes#42855]
Hi, 
Due to network reasons, I have been unable to install bioconductor-geneinfodbdata.
As far as I know, users from China often encounter this issue.
Is it possible to add the following link to this package?
Thanks.
```
https://mirrors.tuna.tsinghua.edu.cn/bioconductor/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
```
![Snipaste_2023-09-06_14-48-57](https://github.com/bioconda/bioconda-recipes/assets/14901250/48261946-30be-40a9-838d-a6bd3136f2d6)

**Comment by BoTang1** [comment]
Hi! 
  Have you solved this issue yet?
  I met the same issue with you? But I tried to download "GenomeInfoDbData_1.2.11".
