### ISSUE TITLE
gnu-sed for mac

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#4306]
Hi,
Linux `sed` and Mac `sed` syntax seem to be very different. Would it be possible to get [gnu-sed](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnu-sed.rb) for Mac installed?

Thank you in advance.

Michal

**Comment by tseemann** [comment]
I am unsure if `sed` falls under `bioconda` ?

**Comment by kyleabeauchamp** [comment]
Maybe add in conda forge?

**Comment by bgruening** [comment]
@mictadlo I'm not sure I understand your question, we have this in bioconda https://github.com/bioconda/bioconda-recipes/blob/master/recipes/sed/meta.yaml for both Linux and OSX afaik.

It should probably be moved to conda-forge, I agree.
Please reopen if this is still an issue.
