### ISSUE TITLE
bcftools links to incorrect GSL library on Intel based MacOS, Monterey 12.7

### ISSUE THREAD

**Issue by ialbert** [bioconda/bioconda-recipes#43321]
I am using an Intel-based Mac, Monterey 12.7.

     micromamba create -yn test bcftools
     micromamba activate test
     bcftools
     
generates the error:

```
dyld[1772]: Library not loaded: '@rpath/libgsl.25.dylib'
  Referenced from: '/Users/ialbert/micromamba/envs/test/bin/bcftools'
```

It appears that GSL 2.7 is installed but the binary links to GSL 2.5. Symlinking GSL 2.7 as 2.5 allows the program to start:

    ln -s /Users/ialbert/micromamba/envs/test/lib/libgsl.27.dylib \
            /Users/ialbert/micromamba/envs/test/lib/libgsl.25.dylib

but I don't know if the code making use of GSL functionality does work as intended.

    micromamba list | grep bcftools

prints:

      bcftools         1.17          h3bbda8f_1  bioconda

**Comment by pettyalex** [comment]
What is your channel priority? This looks like a channel priority problem. 

Bioconda packages are linked against conda-forge, so unless you have strict channel priority and are configured to use conda-forge as the default channel, you'll get a failure as it tries to use the default channels libgsl, which isn't compatible with bioconda.

What if you install with specified channels, like `mamba install -c conda-forge -c bioconda bcftools`? That should find and install the correct GSL.

**Comment by ialbert** [comment]
@pettyalex indeed, that was correct assumption. I will say that the error is massively confusing as such and over the years I have been using conda never really understood that it could cause this type of error.

thanks for the solution!
