### ISSUE TITLE
Racon caused segmantation fault

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#4335]
Hi @druvus,
Did you encounter the same [problem](https://github.com/isovic/racon/issues/22#issuecomment-290929091) as me?

Thank you in advance.

Michal

**Comment by druvus** [comment]
Hi @mictadlo, 
I have been on the move a lot recently so I haven't been testing it so carefully. I will try to look into it during the week. The racon recipe also needs some work to include accessory scripts etc.

**Comment by bgruening** [comment]
This seems to be fixed meanwhile. Thanks for the report.
