### ISSUE TITLE
libintl (gettext) so name wrong (libintl.so.8 vs libintl.so.9)

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-recipes#4360]
The versions of gettext in bioconda and conda-forge contain incompatible so names (8 and 9) due to a bug in the version shipped with bioconda. This leads to failure if a bioconda package requires packages from conda-forge and bioconda which both require gettext, as those from bioconda require libintl.so.9 and packages from conda-forge require libintl.so.8.

The "bug" was caused by an accidental bump to the "current" field of the libintl version, rather than the "revision" field. This was corrected in 0.19.8.1 ([announcement](https://lists.gnu.org/archive/html/info-gnu/2016-06/msg00006.html), [commit](http://git.savannah.gnu.org/cgit/gettext.git/commit/?h=v0.19.8.1&id=c737bf843616ca984c9416048a2da845e9ad3f50)).

One solution would be bumping gettext to 0.19.8.1 (I can submit a PR if this is your choice). 

However, should gettext be in bioconda at all? It would seem that this is a not bio-specific background package that should be pulled from conda-forge.

Either fix would probably require rebuilds of dependent packages, though.

How would you prefer to handle this?

**Comment by bgruening** [comment]
@epruesse I think this should be removed from bioconda. Can you create a PR and remove the recipe from the repo and ping me if you merge it. I will migrate the package to bioconda-legacy then.

Thanks for fixing this!

**Comment by epruesse** [comment]
@bgruening PR #4363 deletes the gettext recipe.

**Comment by bgruening** [comment]
Thanks!
