### ISSUE TITLE
regenie v3.3 build failure on linux

### ISSUE THREAD

**Issue by joellembatchou** [bioconda/bioconda-recipes#43639]
The linux check in PR #43300 fails with a very vague error:
https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=43619&view=results

<img width="1385" alt="image" src="https://github.com/bioconda/bioconda-recipes/assets/65199080/2200888e-644a-4295-8a8f-26b91f2e62ca">

Looking into the [logs](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=43619&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=4dddc55b-10bc-50fc-ac68-7ff899b7a030), all I see is "running (XX)"
<img width="1082" alt="image" src="https://github.com/bioconda/bioconda-recipes/assets/65199080/239e1aa3-09f6-4cab-99f4-ce6aaf11f110">

I tried a local build using bioconda-utils which was successful so I am not sure what is causing this on Azure pipelines.  Any guidance would be appreciated. Thanks!

**Comment by lightning-auriga** [comment]
Hi. I'm not an admin, I was just passing through and curious. I tried building the branch locally and got the error:

`regenie: error while loading shared libraries: libboost_system.so.1.74.0: cannot open shared object file: No such file or directory`

followed by test failure. It looks like it resolves to boost-cpp 1.74 in build, and then 1.82 during run/testing, and thus fails. I don't know if this is the same error that was causing you trouble, but maybe it's something?

**Comment by joellembatchou** [comment]
Thank you for the suggestion, I checked the build log on Azure and the same boost version number is used for host & run. Regardless, I set the version to 1.74 in meta.yaml (c5df22784d76b91dc362f860951f278c94115585) but it still resulted in build failure.

I am still getting successful build on my local machine:
<img width="989" alt="image" src="https://github.com/bioconda/bioconda-recipes/assets/65199080/bb9888a6-ef75-4471-8e8c-4050b30c6564">

What command are you using to build locally?

**Comment by timosachsenberg** [comment]
just for reference - I think we might have a similar issue: https://github.com/bioconda/bioconda-recipes/pull/43774
![image](https://github.com/bioconda/bioconda-recipes/assets/5803621/ea8554cf-7816-42f4-b407-16284032b76e)

**Comment by timosachsenberg** [comment]
In our case, we ran out of memory and were able to fix the issue by restricting builds to a lower number of threads.

**Comment by joellembatchou** [comment]
@timosachsenberg Thank you so much, that addressed the issue!
