### ISSUE TITLE
No build output/log anymore?

### ISSUE THREAD

**Issue by jpfeuffer** [bioconda/bioconda-recipes#43790]
Since our last release something changed on the bioconda side such that we do not get any build output of our build.shs anymore.
This also makes builds fail if they take longer than a certain time since the limit for missing output is lower than the general build limit.

**Comment by timosachsenberg** [comment]
@bgruening likely reason for failing https://github.com/bioconda/bioconda-recipes/pull/43799

**Comment by aliciaaevans** [comment]
Logs should be reenabled for recipe builds now.

**Comment by jpfeuffer** [comment]
Thanks! 

BTW: The build failures were not directly related to missing output.

However we definitely felt a significant speed decrease/ram increase since our last release which was the main issue.
