### ISSUE TITLE
recipe not built

### ISSUE THREAD

**Issue by msantorsola** [bioconda/bioconda-recipes#43840]
Hello,

I would like to build the recipe for [hapnest](https://github.com/intervene-EU-H2020/synthetic_data/tree/main) tool. Anyway, while passing all PR checks [#42924](https://github.com/bioconda/bioconda-recipes/pull/42924) with 0 warnings/0 errors, I locally get:

```
10:30:47 BIOCONDA INFO Nothing to be done for recipe recipes/hapnest
10:30:47 BIOCONDA INFO BUILD SUMMARY: successfully built 0 of 1 recipes
```

How can I fix this?

Thank you,
Mariangela

**Comment by aliciaaevans** [comment]
Hi @msantorsola, I just commented on your PR. I think you may have accidentally left `skip: True` in the `build` section of meta.yaml.

**Comment by msantorsola** [comment]
Hi @aliciaaevans, thank you. I modified the code and pushed it.
