### ISSUE TITLE
Improve one-time setup installation instructions for conda

### ISSUE THREAD

**Issue by peterjc** [bioconda/bioconda-recipes#4408]
Reading https://bioconda.github.io/contrib-setup.html#git-and-github-one-time-setup it says:

> Install conda and Docker (one-time setup)
> Currently, you need to install the requirements (see below) into the root conda environment which must be a Python 3 environment.
>
> Install conda. The Python 3 version is required.
> Install Docker. (optional, but allows you to simulate most closely the Travis-CI tests).
> Please note that it is also required to build any recipe prior to using the simulate-travis.py > command as explained here.

While conda does link to https://conda.io/miniconda.html I tried what to me is the default way to install a Python package under Python 3, ``pip3``,

```
$ pip3 install conda
Collecting conda
  Downloading conda-4.3.13.tar.gz (370kB)
    100% |████████████████████████████████| 378kB 3.3MB/s 
Collecting pycosat>=0.6.1 (from conda)
  Downloading pycosat-0.6.1.tar.gz (59kB)
    100% |████████████████████████████████| 61kB 10.9MB/s 
Requirement already satisfied: requests>=2.12.4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from conda)
Collecting ruamel.yaml>=0.11.14 (from conda)
  Downloading ruamel.yaml-0.14.5.tar.gz (241kB)
    100% |████████████████████████████████| 245kB 6.9MB/s 
Installing collected packages: pycosat, ruamel.yaml, conda
  Running setup.py install for pycosat ... done
  Running setup.py install for ruamel.yaml ... done
  Running setup.py install for conda ... done
Successfully installed conda-4.3.13 pycosat-0.6.1 ruamel.yaml-0.14.5
```

I quickly fell over the following, where after some searching I found ``ruamel_yaml`` is assumed to be installed as part of ``conda``:

```
$ ./simulate-travis.py --set-channel-order
Traceback (most recent call last):
  File "./simulate-travis.py", line 6, in <module>
    import ruamel_yaml as yaml
ImportError: No module named ruamel_yaml
```

Then I tried:

```
$ conda --version
ERROR: The install method you used for conda--probably either `pip install conda`
or `easy_install conda`--is not compatible with using conda as an application.
If your intention is to install conda as a standalone application, currently
supported install methods include the Anaconda installer and the miniconda
installer.  You can download the miniconda installer from
https://conda.io/miniconda.html.
```

I suggest the ``contrib-setup.html`` be more explicit that ``pip`` is not going to work.

**Comment by jasper1918** [comment]
I recently faced this issue as well. I started adding recipes a few weeks back and getting the environment right was tricky.The deceiving part is that the documentation appears complete. It is either missing a critical step or rather the simluate-travis.py --install-requirements is missing a key package. But I added a few dependencies manually and got it working(wish I remembered what they were...)

**Comment by peterjc** [comment]
I think it would be sensible to add ``ruamel_yaml`` as an explicit dependency.

I don't recall having to install anything else, but I was not starting from a completely clean Python environment.

**Comment by Tarun3679** [comment]
> simluate-travis.py --install-requirements

how to add manually the above package?

**Comment by bgruening** [comment]
@peterjc if you like please check the latest documentation and the latest builds. I also hope that the new bot and our new infrastructure, in general, makes it easier to contribute. 

Feel free to reopen if this is still an issue.
