### ISSUE TITLE
Travis vs the "real world"?

### ISSUE THREAD

**Issue by molpopgen** [bioconda/bioconda-recipes#4413]
This is more of a general question for some of the @bioconda/core folks.

To make a long story short, I've come across differences in what it takes to build a package on a Travis bot in a miniconda environment vs. what it takes to build the same package in the same environment on my on OS X and Linux machines.

Recently, Travis builds for my project (http://github.com/molpopgen/pylibseq) started failing.   The builds on Travis are done in a miniconda environment, pulling dependencies in from bioconda. Diagnosing the failure took quite a long time, but it reduced to the following:

* bioconda's libsequence is a dependency
* libsequence in turn depends on htslib
* libsequence was compiled against htslib 1.3.something, and htslib is now at 1.4 in bioconda.

In order to build on travis, I must install htslib==1.3.2.  However, I am perfectly able to use htslib 1.4 on my personal machines.  I've confirmed this on OS X and Linux.

The implication seems to be that when I update the pylibseq recipe for bioconda, I either have to update the build recipe for libsequence  and compile against htslib 1.4 (no big deal), or pin the htslib dependency at 1.3.2, which is artificial because it is only a requirement for the Travis system whereas things would appear to "just work" for users with htslib 1.4 (and presumably future versions to the extent that ABI compatibility is maintained).

My questions are:

* Are there recommendations for what to do here?
* I'm assuming we want to avoid random pinning as much as possible?
* On Linux, I suppose that I could simply statically-link dependent libraries, but I've never figured out if OS X's ld can do that...?

**Comment by kyleabeauchamp** [comment]
So for pysam, we ended up pinning HTSLib to a range that includes any "minor version" increments but not major version increments: https://github.com/bioconda/bioconda-recipes/blob/e7953fbfe7a57f7851ba5e85353ef9948740ebf9/recipes/pysam/meta.yaml#L21

FWIW, dealing with HTSLib versioning between disparate packages has been a source of several issues...

**Comment by molpopgen** [comment]
@kyleabeauchamp That is a useful solution, but is it "really" necessary (e.g., on your personal machine), or is it just something to make the Travis systems happy? 

In my specific case, 1.3 vs 1.4 only matters on Travis, but not on my home systems.  And if we start pinning, then it seems like we run into long-term issues as packages don't update, etc., and certain upgrade paths become unavailable to users?

**Comment by kyleabeauchamp** [comment]
IIRC this was motivated by failures observed on user machines, not on the Travis CI side.

**Comment by molpopgen** [comment]
@kyleabeauchamp That's interesting, thanks.  Perhaps it depends which corners of htslib one is using?

**Comment by kyleabeauchamp** [comment]
Pysam is a particuar challenge because it bundles a local copy of HTSLib, but (AFAIK) uses the shared linker when accessing it.  Thus, I suspect there's a possibility of "precedence" issues where the bundled API is accessing a different shared SO.  Not 100% sure though, would be great to sort out the root cause.

**Comment by molpopgen** [comment]
I suppose I'll close this one, at least for now.  Looks like pinning is our best bet.

**Comment by johanneskoester** [comment]
To ensure consistent pinning, we use our env_matrix.yml. it pins htslib to 1.4 currently, and all packages depending on htslib should use it. All this will become much easier once conda build 3 is released.
