### ISSUE TITLE
one recipe not synced on anaconda.org but another was

### ISSUE THREAD

**Issue by shenwei356** [bioconda/bioconda-recipes#4415]
Hi dear all,

I updated two recipes (#4393 for seqkit and #4394 for csvtk) and they are all tested OK and then merged almost the same time. However, after more than one day, only the csvtk was synced on [anaconda](https://anaconda.org/bioconda/csvtk/files), the seqkit was [not](https://anaconda.org/bioconda/seqkit/files).

How did it happen? Should I resubmit?

**Comment by bgruening** [comment]
@shenwei356 this should not happen, can you try to find the travis log for this merge if you have time?

**Comment by shenwei356** [comment]
You canceled it: https://travis-ci.org/bioconda/bioconda-recipes/builds/221034664

**Comment by bgruening** [comment]
I didn't. But somehow it gets stopped. I just restarted it and this should explain this issue here.

**Comment by shenwei356** [comment]
Yes, it's updated. Thank you @bgruening
