### ISSUE TITLE
PackagesNotFound - RSEM

### ISSUE THREAD

**Issue by gamja917** [bioconda/bioconda-recipes#44394]
Hi,
I am trying to install rsem but I can't.
I've tried all below :
conda create -n counters-env -c bioconda rsem
conda create -n counters-env -c bioconda  -c conda-forge -c rpi rsem
But it always said : 
PackagesNotFoundError: The following packages are not available from current channels: - rsem

How do I solve this problem?

**Comment by dpryan79** [comment]
I'm guessing you're on a mac and installed the ARM version of miniconda. There aren't yet any ARM builds for OSX, you'll need to use the intel version of miniconda.
