### ISSUE TITLE
BLAST not downloading

### ISSUE THREAD

**Issue by lichenlady94** [bioconda/bioconda-recipes#44983]
Hi! 

I've tried to download BLAST a few times whether it's with antismash or BLAST itself and it's saying that BLAST is not available. I'm wondering if it's something on my end or BLAST is actually down

**Comment by boratyng** [comment]
Hi @lichenlady94, are you trying to install BLAST from bioconda? I do not know anything about antimash, but this is working for me:
```
mamba install -c bioconda -c conda-forge blast == 2.15.0
```

**Comment by lichenlady94** [comment]
May I ask what terminal and system (i.e. Windows, Mac) are you using? It might be where the issue is

**Comment by peterjc** [comment]
I would bet this is a problem with trying to install BLAST under macOS with an Apple ARM CPU, however without further information I'm just going to close this stale issue.
