### ISSUE TITLE
Guidelines for recipe creation

### ISSUE THREAD

**Issue by lpantano** [bioconda/bioconda-recipes#455]
Hi,

this is a general question, probably for people who aren't expert like me.

There are many type of tools, like the ones you compile and create binaries, or the ones that are perl scripts, or java ... etc...

I tried to follow recipes that already exists, but maybe it would be good to add to README.md general guidelines like: java tools go to `share/tools...` and then do `blablabla`. Maybe there are several solutions, but for instance `Fastqc` is directly in the the `PREFIX` folder, and others inside `lib` and others inside `libexec`.

I feel bad when I put things in the wrong directory, and I will be happy to take feedback from any pull-request I do. But I think maybe we can add some general guidelines... or not. Just an idea.

thanks for bioconda anyway, is great!

**Comment by johanneskoester** [comment]
Hi,
this is a very good suggestion. Do you think it would be sufficient to link the [FSH](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)?

**Comment by lpantano** [comment]
that is a good idea. I will add some links to recipes in the repo to have a quick start depending on the tool type.
For instance for java one can be https://github.com/bioconda/bioconda-recipes/tree/master/recipes/gatk-framework
For perl another that you think is a good example to follow ...
And the same for the C compilation code etc...

The question was related to best practices examples to avoid putting binary, perl, java code ... in places that maybe are not the best.

I think that with few links to good examples will do most of the job for people like me.

thanks!

**Comment by johanneskoester** [comment]
This seems to be fixed with PR #636.

**Comment by lpantano** [comment]
awesome!

sent not from my computer
