### ISSUE TITLE
Updating bioconductor packages to 3.4

### ISSUE THREAD

**Issue by lpantano** [bioconda/bioconda-recipes#4560]
Hi @bioconda/core,

We (@chapmanb, @roryk, @mjsteinbaugh ) wanted to normalize are all bioconductor package (from bioconda) we use in bcbio-nextgen to use R 3.4 because there is a bunch of fixes now, otherwise we are starting to see incompatibility issues between packages.

Is there any guides to do this? I guess the first thing would be able to install 3.4 from r channel or are we using other channel?

Maybe this is a good start point to try to figure out how to update all bioconductor packages after a release. Any guides on how to proceed with this will be highly appreciated.

Cheers

**Comment by bgruening** [comment]
@lpantano before we rebuild all packages we would like to port all package from the `r` channel to conda-forge: https://github.com/conda-forge/staged-recipes/issues/2009

If this is done we put all r and bioc package from bioconda on a blacklist, increase the R version to 3.4 and as a last step remove one package after the other from the blacklist to rebuild everything.

**Comment by johanneskoester** [comment]
If you like to speedup the process, any help with the migration is very welcome. A complete guide can be found in conda-forge/staged-recipes#2009.

**Comment by chapmanb** [comment]
Björn and Johannes;
Thanks for the details about the R plans. Wow, this is an incredible effort. Do we need to port all of the packages by hand, or is there any automation in place? We're happy to help contribute, but the task list is, well, daunting. I'm not sure how best to jump in and then what updating to 3.4 will entail. Thanks again for tackling this.

**Comment by johanneskoester** [comment]
Most of the time a `conda skeleton cran packagename` is sufficient. The issue also provides a cleanup script for the resulting recipe. Then, all one needs to do is to create a pr. We are almost done with level 2 of the list. Maybe this will take two more weeks. Did you see my recent gitter messages for bioconda/core?

**Comment by bgruening** [comment]
@chapmanb @johanneskoester also see my comment here: https://github.com/conda-forge/staged-recipes/issues/2009#issuecomment-298161781

**Comment by chambm** [comment]
Is this thread about upgrading to R 3.4 (just released), or BioConductor 3.4 (released last year)? BioConductor 3.5 is out now (depends on R 3.4).

**Comment by lpantano** [comment]
R 3.4

**Comment by chambm** [comment]
OK good. So it won't block #4583  :)

**Comment by bgruening** [comment]
We are migrating now to R 3.3.2 and remove the r-channel. If we can agree with conda-forge on a R version to track we will migrate to R 3.4.x later.

**Comment by bgruening** [comment]
Small update I have started the R 3.4 migration on conda-forge and packages are now rebuilding. At least for Linux it looks good so far and we can start to migrate our packages as well.
If I find time I will start this in next week, given conda-forge is done rebuilding.

**Comment by druvus** [comment]
Nice work @bgruening !

**Comment by chapmanb** [comment]
Awesome, thanks so much Björn

**Comment by bgruening** [comment]
Ok. Next update. I finished the conda-forge migration and started the R3.4 build in the bulk branch. So the first packages are arriving for R3.4.

**Comment by roryk** [comment]
Thank you!

**Comment by bgruening** [comment]
@lpantano and all other following this issue. I think we have archived our goals during the last weeks (or was it month?). With https://github.com/bioconda/bioconda-recipes/pull/6119 I will close this issue now.

**Comment by chapmanb** [comment]
Björn -- wow, thank you so much for all this incredible amount of work.
