### ISSUE TITLE
pysam 0.22 Python version requirement is too strict

### ISSUE THREAD

**Issue by cmeesters** [bioconda/bioconda-recipes#45616]
Hi,

the rel. new Python recipe for pysam 0.22 indicates a Python requirement >=3.8,<3.9.0a0 , the current snakemake requires python >=3.11,<3.13 . Hence, embedding pysam in a workflow is impossible. 

Would it be possible to relax the python requirements for pysam?

**Comment by pdimens** [comment]
see #37805

**Comment by cmeesters** [comment]
Ah, thank you. Understandable. Hm, at least this way my course can learn, that no packaging system provides always 100% coverage.
