### ISSUE TITLE
prokbert autointegration failed

### ISSUE THREAD

**Issue by obalasz** [bioconda/bioconda-recipes#45810]
Hi,

I've updated the prokbert pip package, but somehow the integration to bioconda failed and not finished: 
https://github.com/bioconda/bioconda-recipes/pull/45794

I'm newbie, how can I facilitate the integration process?  

Cheers, Balázs

**Comment by mencian** [comment]
@obalasz I apologize for just now getting to this. I re-triggered the CI and `prokbert` now builds successfully. Not sure what the initial error was about (the logs have been erased) but whatever it was, it was a transient error. I'll close this issue for now. Please let me know if anything else pops up!
