### ISSUE TITLE
Too strict ete3 dependencies

### ISSUE THREAD

**Issue by karel-brinda** [bioconda/bioconda-recipes#4582]
Hi, I think that *ete3* has too strict list of dependencies, see https://github.com/bioconda/bioconda-recipes/blob/26f472b252306b85607dbaf8f64d6fcbb3c09cfc/recipes/ete3/meta.yaml. Especially `pyqt 4.11.*` causes a lot of problems. For instance, Python 3.6 cannot be used with the current version of the package:
```
 - ete3 -> pyqt 4.11.* -> python 2.6* -> openssl 1.0.1*
 - python ==3.6
```
PyQT is needed only for plotting trees. However, in many programs one does not need this functionality (e.g., in ProPhyle).

Maybe we could create two recipes, e.g., `ete3` and `ete3-minimalistic` (or `ete3` and `ete3-full`)? A similar problem has already appeared with other recipes and there are, e.g., multiple packages for kraken (`kraken`, `kraken-all`, and `kraken-biom`).

**Comment by karel-brinda** [comment]
cc @simonvh @nsoranzo

**Comment by bgruening** [comment]
@karel-brinda can this be a general problem that this package is not available for python3.6?

**Comment by karel-brinda** [comment]
@bgruening I think that Python 3.6 is usually used with a newer PyQT (e.g., 5.6):
```
$ conda create -y -c bioconda --name test python=3.6 pyqt
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/karel/miniconda/envs/test:

The following NEW packages will be INSTALLED:

    icu:        54.1-0       
    openssl:    1.0.2k-1     
    pip:        9.0.1-py36_1 
    pyqt:       5.6.0-py36_2 
    python:     3.6.1-0      
    qt:         5.6.2-0      
    readline:   6.2-2        
    setuptools: 27.2.0-py36_0
    sip:        4.18-py36_0  
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py36_0
    xz:         5.2.2-1      
    zlib:       1.2.8-3 
```

**Comment by karel-brinda** [comment]
```
$ conda create -y -c bioconda --name test2 python=3.6 pyqt=4
Fetching package metadata .............
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - pyqt 4* -> python 2.6* -> openssl 1.0.1*
  - python 3.6*
```

**Comment by bgruening** [comment]
Can you try conda create -y -c bioconda --name test2 python=3.5 pyqt=4?
BioConda do not support Python3.6 yet :( Sorry.

**Comment by simonvh** [comment]
So, is it just Python 3.6 that is the problem? I'm not an expert on either ete3 or PyQT versions. I just updated the ete3 recipe, as I needed it and the previous one didn't work. These dependencies were the minimum that I settled on after a lot of trial and error. As for creating multiple recipes, I would suggest involving @jhcepas?

**Comment by karel-brinda** [comment]
@bgruening 
```
$ conda create -y -c bioconda --name test2 python=3.5 pyqt=4
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /Users/karel/miniconda/envs/test2:

The following NEW packages will be INSTALLED:

    freetype:   2.5.5-2      
    libpng:     1.6.27-0     
    openssl:    1.0.2k-1     
    pip:        9.0.1-py35_1 
    pyqt:       4.11.4-py35_4
    python:     3.5.3-1      
    qt:         4.8.7-4      
    readline:   6.2-2        
    setuptools: 27.2.0-py35_0
    sip:        4.18-py35_0  
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py35_0
    xz:         5.2.2-1      
    zlib:       1.2.8-3      

#
# To activate this environment, use:
# > source activate test2
#
# To deactivate this environment, use:
# > source deactivate test2
#
```

**Comment by karel-brinda** [comment]
I can create an environment with Python 3.6 and other conda packages. I don't know which version of packages is used (maybe for Python 3.5?), but it works.

**Comment by druvus** [comment]
Bioconda now supports Python 3.6 so I am closing this.
