### ISSUE TITLE
 update samtools

### ISSUE THREAD

**Issue by wcarre** [bioconda/bioconda-recipes#45883]

**Comment by jmarshall** [comment]
Bioconda provides samtools 1.19.2, which is the current version.

If you think there is a problem, you will need to provide more details. It may be that you need to [check your channel setup details as per bioconda's installation instructions](https://bioconda.github.io).

**Comment by wcarre** [comment]
Hello,Sorry I click by mistake, did not want to bother you. Solve the problem related to conda cache rather than Samtools.CheersSent from my iPhoneOn 19 Feb 2024, at 20:59, John Marshall ***@***.***> wrote:﻿
Bioconda provides samtools 1.19.2, which is the current version.
If you think there is a problem, you will need to provide more details. It may be that you need to check your channel setup details as per bioconda's installation instructions.
