### ISSUE TITLE
Update pinned versions

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#4592]
Please post here to propose an update of the pinned versions (e.g. Python, R, Perl, boost, ...) or add a new pinning.

[**Status**](https://github.com/bioconda/bioconda-recipes/commits/bulk)

### Todo
* [x] Python 3.6
* [x] R 3.3.2

**Comment by bgruening** [comment]
@bioconda/osx we are currently migration to Python 3.6. This is happening on the `bulk` branch.
Look at this beauty: https://anaconda.org/bioconda/repo/history

However, there are a few (;)) packages that are failing and it would be great to get your help here.
For example look here: https://travis-ci.org/bioconda/bioconda-recipes/jobs/229428332 grep some failure and submit the change to the bulk branch. 

Thanks!
Bjoern

**Comment by johanneskoester** [comment]
@bioconda/osx, I am currently trying to fix an issue with conda-build on osx. I hope this this will solve many of the failures we see on osx. I'll keep you posted.

**Comment by johanneskoester** [comment]
Ok, the issue was that travis sometimes mixes up the order of the log messages on osx. If that seems to happen in your case, reloading with F5 should be sufficient to get the right order.

**Comment by johanneskoester** [comment]
Mhm, actually it still does not make any sense... @daler, could you have a look, maybe on a local mac machine? What is wrong there???

**Comment by johanneskoester** [comment]
It looks like after htseq has been built for the first time, the build folder is always the htseq folder and it sometimes tries to rebuild htseq and sometimes tries to build the current recipe but cannot find the correct files... This is really a mystery to me.

**Comment by johanneskoester** [comment]
The build issues have been fixed.

**Comment by johanneskoester** [comment]
@bioconda/core osx migration to py36 is done! On linux some recipes remain but I hope to be done in the next few days.

**Comment by bgruening** [comment]
@bioconda/r @bioconda/core we have started the migration to R 3.3.2.
Please look at the bulk branch and help fixing recipes as much as you can, ever fixed package helps!

Just click here on bulk and look for a failing one:
https://travis-ci.org/bioconda/bioconda-recipes/branches

If you want to get familiar with conda-forge we would also like to move all r-* package from bioconda into conda-forge. I have script to assists you with this!

Help welcome!

**Comment by bgruening** [comment]
@daler I have remove the R blacklist in the bulk branch - so far 150 packages are rebuild. I changed all packages to r-base and fixed a lot of links, so far so good. A few bioC links were backuped in cargo-port but are empty, not sure why, the majority is working.

200 out of 500 are already rebuild.

**Comment by daler** [comment]
Wow, awesome!

I work on fixing failed recipes on the bulk branch. Is the workflow to test them in a separate WIP PR before adding to `bulk`, or push all fixes directly to `bulk`?

**Comment by bgruening** [comment]
I push directly to `bulk`, the problem with a different branch is that you will get tons of linting errors.
One think I found, many many recipes do not have a checksum, which yielded in cargo-port downloaded something but could not verify it - this happened for all old recipes as well with the consequence that many package in cargo-port are error-pages. So not helpful, all more recent recipes with checksum should work and should be available in cargo-port.

**Comment by daler** [comment]
Thanks for the warning! Are you updating packages at the same time, or keeping existing package where possible?

**Comment by bgruening** [comment]
I keep packages as much as I can.
One additional warning, it seems that conda-forge does not check the entire list of URLs, it only takes the first one. Simply remove the first URL of the r-* packages ...

**Comment by bgruening** [comment]
@daler can you do me a favor you rerun every 2 hours the travis job of the `bulk` branch. Every package counts :)

**Comment by daler** [comment]
Will do!

**Comment by bgruening** [comment]
@bioconda/osx we got some of these `error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.7" but "10.9" during configure` any idea what this?

**Comment by rvalieris** [comment]
@bgruening, no idea why but some recipes explicit set this variable in the `build.sh`, see: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/dsk/build.sh#L4

**Comment by bgruening** [comment]
@rvalieris if you have some time could you have a look at https://travis-ci.org/bioconda/bioconda-recipes/jobs/240012049 .. just search for `MACOSX_DEPLOYMENT_TARGET`. It seem one of them is MACS and it does not have this set, as far as I can see.
Thanks!

**Comment by rvalieris** [comment]
yes, I think people are setting the variable explicitly to avoid the problem. we could just add this to macs recipe but I have no idea of what side effects this will have, do we have a minimum supported osx version ?

**Comment by bgruening** [comment]
I don't think so. How is this dependent of the Travis OSX vesion?

**Comment by acaprez** [comment]
Usually the reason for setting the `MACOSX_DEPLOYMENT_TARGET` is to enable support of newer C++ features.  This seems to be a different issue.

**Comment by rvalieris** [comment]
I think its the python package: https://github.com/conda-forge/python-feedstock/issues/137

**Comment by bgruening** [comment]
@rvalieris @acaprez @bioconda/osx I have started to work again on the R migration. I'm done to 10 packages for OSX - any help welcome: https://travis-ci.org/bioconda/bioconda-recipes/jobs/242842061

**Comment by druvus** [comment]
@bgruening I have an updated version of nanoraw in #4620 that works in the bulk branch on my mac. 

I think also it could be worth getting rid of the old 0.3.1 recipe. I can build 0.4.* and 0.3.1 recipes individually but it fails when the 0.3.1 folder is present. with the same error as in travis

**Comment by bgruening** [comment]
@druvus great! I merged master into bulk and removed the older version. Thanks a lot!

**Comment by bgruening** [comment]
`r-multicool` is a big one, a few others depend on it and it crashes with a memory error for me. I tried already some things in the bulk branch.

**Comment by bgruening** [comment]
I will close this now! Thanks all!

**Comment by johanneskoester** [comment]
Let's keep this open for future bulk updates.

**Comment by bgruening** [comment]
We have a more robust pinning system in place now, so closing this off.
