### ISSUE TITLE
Bioconda packages not downloading on Mac M3 

### ISSUE THREAD

**Issue by faleevz** [bioconda/bioconda-recipes#45948]
Hello everyone! I'm sorry for the potentially stupid question- I am just starting out with coding in conda. 

I am trying to download samtools, but it just does not work. 

I have tried downloading it through mamba as well. 
I have run:

conda config --add channels conda-forge
conda config --add channels bioconda
conda install samtools==1.11

And various variations of it.

Every time it tells me: 
PackagesNotFoundError: The following packages are not available from current channels:
  - samtools

Current channels:

  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

This is also happening to several other packages that I need to download from bioconda, so if anyone would provide any advice it would be incredibly appreciated!
Many thannks

**Comment by milot-mirdita** [comment]
You can install the x86_64 packages and run them through rosetta:
https://github.com/bioconda/bioconda-recipes/issues/41702#issuecomment-1614173361

**Comment by jmarshall** [comment]
Bioconda now supports Apple silicon, and samtools 1.20 is now available via bioconda for this platform.
