### ISSUE TITLE
Squash merge pull requests

### ISSUE THREAD

**Issue by dhimmel** [bioconda/bioconda-recipes#4595]
Just a note to maintainers, I think the repository would benefit from primarily adopting [squash merges](https://github.com/blog/2141-squash-your-commits) rather than GitHub's default "Create a merge commit" option.

For example, most pull requests are cohesive units that make sense as a single commit. Most of the subsequent commits in pull requests are responses to review and bug fixes. There is no reason to preserve these in the `master` commit history. Without squash merging, it becomes unwieldy to browse the history on GitHub. You also no longer have a linear history, which is ideal for simplicity.

I'd recommend still using merge commits for certain circumstances, like when a pull request has multiple authors.

FYI, this issue caught my attention when I was looking into https://github.com/bioconda/bioconda-recipes/pull/4468 by @kurtwheeler. CC @bgruening and @johanneskoester .

**Comment by bgruening** [comment]
I think this is a good idea. Yet it is hard to enforce I think. But we can make it a best practice rule.

**Comment by johanneskoester** [comment]
We could disable everything but squash. I would be fine with that.

**Comment by dhimmel** [comment]
> We could disable everything but squash. I would be fine with that.

`python/cpython` only allows squash merge. If you have lot's of maintainers, this could be most efficient.

> But we can make it a best practice rule.

Agree. Related, when squash merging, I'll often rephrase the commit message. For example, I'll add whether it closes an issue and I'll clarify the title as appropriate.

**Comment by johanneskoester** [comment]
@bioconda/core, do you have any objections against only allowing squash merges?

**Comment by rvalieris** [comment]
I think its a great idea, I guess people don't use it because its not the default option so its easy to miss.

**Comment by bgruening** [comment]
:+1: from me!

**Comment by bgruening** [comment]
Ok, I enabled this now.
Thanks for the suggestion!
