### ISSUE TITLE
Stuck at "Solving package specifications"

### ISSUE THREAD

**Issue by simonvh** [bioconda/bioconda-recipes#4599]
@bioconda/core I have an issue that I hope one of you will be able to help me with. I recently updated the bioconda package for [gimmemotifs](https://bioconda.github.io/recipes/gimmemotifs/README.html). However, using a simple install command will now fail, with conda being stuck at the "Solving package specifications" stage. 

```
$ conda create -n gimmemotifs python=2 gimmemotifs
Fetching package metadata ...............
Solving package specifications: .
```
When I specify the exact version, the installation works flawlessly:

```
$ conda create -n gimmemotifs python=2 gimmemotifs=0.10.0=py27_0
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/simon/anaconda3/envs/gimmemotifs:

The following NEW packages will be INSTALLED:
[...]
```

Has anyone seen this before? Any clues on how to solve it?

**Comment by johanneskoester** [comment]
That looks like a bug in the conda package manager. Can you please report this here: https://github.com/conda/conda? If you do so, please also tell them the version you are using.
