### ISSUE TITLE
viral_consensus v0.0.5 autobump ran into compile error

### ISSUE THREAD

**Issue by niemasd** [bioconda/bioconda-recipes#46253]
I wasn't sure what the best way to seek help for this was, but I noticed that the bioconda autobump ran into a compile error when bumping from 0.0.4 to 0.0.5:

https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=52526&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=4dddc55b-10bc-50fc-ac68-7ff899b7a030&l=654

The compile error seems to be the following:

```
/opt/conda/conda-bld/viral_consensus_1709706436049/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lz: No such file or directory
```

It's strange that it's no longer able to find `-lz` when compiling, given that the update from 0.0.4 to 0.0.5 didn't make any changes to how `viral_consensus` is compiled:

https://github.com/niemasd/ViralConsensus/compare/0.0.4...0.0.5

Any assistance to get `viral_consensus` updated to 0.0.5 via autobump on bioconda would be greatly appreciated

**Comment by mencian** [comment]
Hello @niemasd, I tried adding `zlib` to the host section [here](https://github.com/bioconda/bioconda-recipes/pull/46203) and that seems to have done the trick!

**Comment by niemasd** [comment]
Ah, thank you for catching that! I (seemingly incorrectly) thought that the `htslib` host would automatically handle any hosts `hstlib` depends on. I appreciate the help!

**Comment by jmarshall** [comment]
This is because conda-forge's zlib package is divided into `libzlib` (the runtime) and `zlib` (headers and `.a`/`.so` needed for linking). Having htslib listed as host would pull in libzlib appropriately, but as your code also uses _zlib.h_ and/or `-lz` itself you also need to list the zlib build-time package yourself.

**Comment by niemasd** [comment]
I see; thanks for following up! So I would need to add `- zlib` as an item under `build:`?

https://github.com/bioconda/bioconda-recipes/blob/cab2797977940c95672090cc30e3212eb99f0885/recipes/viral_consensus/meta.yaml#L17-L20

Apologies for my lack of experience with bioconda!

**Comment by jmarshall** [comment]
No, the change that @mencian made to add `host: zlib` is correct and all that is needed.

I was explaining why this was necessary, though I left off the context that until recently htslib depended on zlib rather than just libzlib — which is why it worked previously when 0.0.4 was being built.

**Comment by niemasd** [comment]
Ahhh I see; thank you for the additional context! That makes a lot of sense. I appreciate it!
