### ISSUE TITLE
Add dependency `interproscan` to `sanntis` recipe

### ISSUE THREAD

**Issue by jasmezz** [bioconda/bioconda-recipes#46396]
This is a question for the recipe author and developer of the SanntiS tool @SantiagoSanchezF:
Since `interproscan` is a dependency of SanntiS, it would be convenient to have it bundled in one conda recipe (and thus also in docker/singularity containers). Currently, users have to follow a separate installation procedure (see SanntiS [README](https://github.com/Finn-Lab/SanntiS/blob/master/README.md)). This makes it more difficult than necessary to use the tool in automated bioinformatic pipelines. 

If the reason is that interproscan is available for Linux-only, I argue that the docker/singularity containers run on Linux and would greatly benefit from `interproscan` being included. Additionally, probably even the conda package is mostly used on Linux environments.

- Do you agree to my reasoning?
- And/or is there another reason why you excluded `interproscan`?
- Can you include it?

**Comment by SantiagoSanchezF** [comment]
Hello,

Thank you for your suggestion and the thoughtful reasoning behind integrating IPS into the SanntiS conda recipe. While we understand the appeal of simplifying the installation process, there are a few challenges that have influenced our decision to keep them separate for the time being:

Package size and complexity: IPS is a very large tool with its own set of dependencies. Including it directly within the sanntis package would significantly increase the overall size and complexity of the installation.
Cross-platform compatibility and users: We are aware that a considerable portion of users already have IPS installed and configured in their environments. Additionally, we want to maintain cross-platform compatibility for sanntis as much as possible. Direct integration could potentially limit the usability for those not on Linux platforms or introduce unnecessary redundancies for users who already have IPS.

It's also worth noting that there's an IPS available on bioconda (https://anaconda.org/bioconda/interproscan), which could be utilised for custom recipes/installations. However, we haven't fully tested this integration.

We genuinely appreciate your input and are considering the possibility of integration or providing a more streamlined approach for using sanntis and IPS together in the future.

Best
Santiago

**Comment by jasmezz** [comment]
Hi @SantiagoSanchezF, thank you very much for the detailed answer! That's alright then, we'll create a multi-package biocontainer for our purposes (to have sanntis and interproscan bundled). :+1:
