### ISSUE TITLE
Issue with versions - GMM-Demux

### ISSUE THREAD

**Issue by mari-ga** [bioconda/bioconda-recipes#46523]
Hi,
I've been trying to contribute with some packages to Bioconda. I'm having problems with GMM-Demux. The Python version needed for the package must be <=3.11, therefore I established this requirement in the yaml file. However, not matter whether I use a fixed version of Python (`python ==3.10.13`) or include something like (python `<=3.10`), I still get this error:
`(OUT) conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("_python_rc"), MatchSpec("argparse==1.4.0=py26_0"), MatchSpec("python==3.12.0rc3=rc3_hab00c5b_1_cpython")}`

You can see the multiple time that this error has jumped here: https://github.com/bioconda/bioconda-recipes/pull/46440

Anything you would recommend for this problem?

Thank you very much in advance!

**Comment by mencian** [comment]
Closing this issue as it is solved; please feel free to re-open if there is anything else I might have missed!
