### ISSUE TITLE
rgi v6.0.3 needs pyrodigal < 3

### ISSUE THREAD

**Issue by danpal96** [bioconda/bioconda-recipes#46581]
rgi v6.0.3 specifies:
```
pyrodigal >=2.0.0
```
But since pyrodigal [v3.0.0](https://github.com/althonos/pyrodigal/releases/tag/v3.0.0) `OrfFinder` was renamed to `GeneFinder`, breaking the use of pyrodigal in rgi.

**Comment by mencian** [comment]
Closing this issue as `pyrodigal` is now pinned to `<3` in #46669.
