### ISSUE TITLE
Command line NoD predictor (clinod)

### ISSUE THREAD

**Issue by peterjc** [bioconda/bioconda-recipes#4675]
Command line NoD predictor is a tool for predicting nucleolar localization sequences (NoLSs) in a FASTA file of proteins using a neural network. There is also a webtool version at http://www.compbio.dundee.ac.uk/www-nod/

Would a recipe based on https://github.com/peterjc/pico_galaxy/blob/master/tools/clinod/tool_dependencies.xml be welcomed? Note clinod requires the SNNS Batch Interpreter v1.0 executable, which I would propose to download precompiled.

**Comment by bgruening** [comment]
Sure! :)

**Comment by bgruening** [comment]
ping @peterjc

**Comment by peterjc** [comment]
Done, belatedly closing this issue - thanks for the reminder:

https://anaconda.org/bioconda/clinod
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/clinod
