### ISSUE TITLE
pairix requires Perl for utilities

### ISSUE THREAD

**Issue by adthrasher** [bioconda/bioconda-recipes#46957]
I am attempting to use the [pairix container](https://quay.io/repository/biocontainers/pairix?tab=info) which includes a number of Perl scripts from the [source repo](https://github.com/4dn-dcic/pairix), but there is no Perl interpreter installed in the container. After [discussion](https://github.com/BioContainers/containers/issues/567) with the biocontainers team, it looks like the bioconda recipe lacks the Perl dependency.

**Comment by adthrasher** [comment]
The recipe is also missing `samtools` which is required by some of the utility scripts in the package.

**Comment by mencian** [comment]
@adthrasher I've added `perl` and `samtools` to the list of run dependencies [here](https://github.com/bioconda/bioconda-recipes/pull/47083).

**Comment by mencian** [comment]
Closing this issue as it is solved - feel free to re-open this thread if I've missed anything!
