### ISSUE TITLE
Can't find most bioconda packages using conda or mamba/micromamba

### ISSUE THREAD

**Issue by pmomadeira** [bioconda/bioconda-recipes#47025]
Greetings everyone,

As of late I've started having a problem when trying to install packages using conda or micromamba, particularly bioconda packages. When I try to download and install a package with conda install or micromamba install I inevitably get an error related to "package cant be found"

When using micromamba:
```
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ blast does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs

```

When using conda:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - blast

Current channels:

  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/nodefaults
  - https://conda.anaconda.org/bioconda

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

This has been happening with a lot of bioconda packages like blast, pysam, samtools, vcfpy, pyvcf etc, and I can't seem to be able to solve this problem. This has been occuring in a M1 MacbookAir with both conda and micromamba up to date, but for some reason is working on a linux machine.

If anyone has an idea about how to solve this problem I would be greatly appreciated. If you feel like you need any more info I'll be glad to add it.

**Comment by aliciaaevans** [comment]
Biconda does not yet support the Arm architecture that M1 uses. You can subscribe to the Announcements issue (https://github.com/bioconda/bioconda-recipes/issues/33333) for an update when we start building recipes for osx-arm64.
