### ISSUE TITLE
lint the yaml files and do this in TravisCI

### ISSUE THREAD

**Issue by peterjc** [bioconda/bioconda-recipes#4723]
Working on #4722 I ran into a malformed YAML issue, TravisCI and ``simulate-travis.py`` were unhelpful:

```
$ ./simulate-travis.py --packages nlstradamus
+ bioconda-utils lint recipes config.yml --git-range master HEAD
16:12:24 BIOCONDA INFO Recipes newly unblacklisted:

16:12:24 BIOCONDA INFO Recipes with modified meta.yaml files according to git: recipes/nlstradamus
16:12:24 BIOCONDA ERROR 

The following recipes failed linting. See https://bioconda.github.io/linting.html for details:

                      failed_tests
recipe                            
recipes/nlstradamus  [parse_error]

```

Using an online YAML linter quickly solved my problem.

I propose that all the recipes YAML files be linted, and that this becomes an early check in the TravisCI setup.

**Comment by peterjc** [comment]
https://yamllint.readthedocs.io/en/latest/ looks intriguing but seems to be unaware of the ``# [linux]`` and ``# [osx]`` markers (e.g. reports duplicated keys for platform specific URLs).

**Comment by daler** [comment]
@peterjc https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/linting.py#L240 is where linting currently happens. Do you think reporting the text of the exception would be sufficient? I guess it could be reported in a supplemental section under the dataframe of failed lint results?

**Comment by peterjc** [comment]
Reporting the text of the exception would certainly be a step forward, and might be sufficient.

Personally there is value in having the repository compliant with a light weight linting check which could also be used in a git pre-commit hook (``yamllint`` which I refered to earlier has the concept of configuration files which would help here), or many editors.

**Comment by daler** [comment]
I agree it would be great to validate yamls. I guess I worry about conda's meta.yaml files with their preprocessing selectors (as you mentioned) creating more complexity than it's worth. But now that you point out the config file option to `yamllint`, I think the `key-duplicates: disable` config option should solve it. I can't think of any other lint failures that would be caused by preprocessing selectors.

**Comment by peterjc** [comment]
There is the percent sign thing:

```
$ yamllint --version
yamllint 1.7.0
$ yamllint -d relaxed recipes/ale/meta.yaml 
recipes/ale/meta.yaml
  1:2       error    syntax error: found character '%' that cannot start any token
```

**Comment by daler** [comment]
Ah right, the jinja2 templating will make this a pain to work on files directly, which will in turn limit options for git commit hooks. The recipe needs to be filled in with the env but we could run validation on the filled-in contents from https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/linting.py#L81.

**Comment by peterjc** [comment]
Ah - so the ``meta.yaml`` files go though ``#`` preprocessing and ``%`` jinja2 templating before they could be given to a naive YAML linter. That does complicate matters for standalone linting.

**Comment by peterjc** [comment]
Can we use ``bioconda-utils lint ...`` for a git pre-commit hook?

**Comment by daler** [comment]
My understanding is that pre-commit hooks are not copied when cloning a repo, and so would need to be set up client-side on an individual basis. I think the current system -- nothing gets into master without passing travis-ci -- avoids requiring users to set up anything locally, and still serves the same purpose since `bioconda-utils lint` is run there. A pre-commit hook would avoid commits like "fix typo" and "forgot to bump version", but we're doing squash merges those shouldn't be too much of an issue. I might be missing something though -- are there other advantages?

**Comment by peterjc** [comment]
Yes, any git hook would have to be deliberately installed by the contributor.

However, catching typos with a fast local lint will avoid long waits for the TravisCI system to build a pull request. That in itself is a big advantage to me as a contributor.

**Comment by daler** [comment]
True. Have you tried https://github.com/bioconda/bioconda-recipes/issues/5374 yet (new docs [here](https://github.com/bioconda/bioconda-recipes/issues/5374))? This does everything that travis does, and should save a ton of time when running locally.

**Comment by peterjc** [comment]
I had not tried that - it allowed me to reproduce the linting failure from #5455 (giving the same cryptic failure).

Something along those lines for linting as a git hook might work...

**Comment by bgruening** [comment]
@peterjc is this still a problem? The new bioconda-utils should do a much better job today.

**Comment by peterjc** [comment]
I've not run into this particular issue in a long time - partly I am more familiar with YAML syntax now, but the better tooling is likely also helping. Closing, thanks.
