### ISSUE TITLE
Removal of faulty builds

### ISSUE THREAD

**Issue by mbargull** [bioconda/bioconda-recipes#4731]
Do you have any policy on pulling faulty builds from the `bioconda` conda repository?
An example for such a build is `pysam-0.10.0-py35_2`.
See the discussion at https://github.com/conda/conda/issues/4955.

Here is a copy-pasta of the last comment over there:

----

It's working this time because `pysam` now has a higher version number and thus possibly gets more prioritized by the solver.
The issue still stands that older faulty build need to be ignored (the `conda` issue) or pulled from the repository (which makes it a `bioconda` issue).
Re: the `conda` issue: Currently there is no functionality on the repository side to mark builds as defunct or superseded which only leaves the resolution given by @mcg1969: those builds need to be removed from the repository. For more details on that, see #4956 and @mcg1969's Gist at https://gist.github.com/mcg1969/38589eeefb046c417720f1027f97085b.

To still reproduce the issue, see:
```bash
$ conda create -n env -c bioconda --dry-run htslib 'pysam<0.11'
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/maba/miniconda3/envs/env:

The following NEW packages will be INSTALLED:

    bcftools:   1.4.1-0       bioconda
    bzip2:      1.0.6-3               
    curl:       7.52.1-0              
    htslib:     1.4.1-0       bioconda
    libgcc:     5.2.0-0               
    openssl:    1.0.2k-2              
    pip:        9.0.1-py35_1          
    pysam:      0.10.0-py35_2 bioconda
    python:     3.5.3-1               
    readline:   6.2-2                 
    samtools:   1.4.1-0       bioconda
    setuptools: 27.2.0-py35_0         
    sqlite:     3.13.0-0              
    tk:         8.5.18-0              
    wheel:      0.29.0-py35_0         
    xz:         5.2.2-1               
    zlib:       1.2.8-3               
```
If `htslib` is one of the explicitly requested packages, `conda` tries to maximize its version and thus picks up `htslib-1.4.1-0` but also `pysam-0.10.0-py35_2`. This `pysam` build is faulty in that it should require `htslib >=1.3,<1.4` but only requires `htslib >=1.3`. Outcome: The above command will install a non-functional `pysam` package.
```bash
$ conda create -n env -c bioconda --dry-run 'pysam<0.11'
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/maba/miniconda3/envs/env:

The following NEW packages will be INSTALLED:

    bcftools:   1.3.1-1       bioconda
    curl:       7.52.1-0              
    htslib:     1.3.2-0       bioconda
    libgcc:     5.2.0-0               
    openssl:    1.0.2k-2              
    pip:        9.0.1-py36_1          
    pysam:      0.10.0-py36_3 bioconda
    python:     3.6.1-2               
    readline:   6.2-2                 
    samtools:   1.3.1-5       bioconda
    setuptools: 27.2.0-py36_0         
    sqlite:     3.13.0-0              
    tk:         8.5.18-0              
    wheel:      0.29.0-py36_0         
    xz:         5.2.2-1               
    zlib:       1.2.8-3               
```
If `htslib` is not explicitly requested, only `pysam`'s version (including its build number) gets maximized so that `pysam-0.10.0-py36_3` can be used.

I am going to file an accompanying issue @bioconda.

----

**Comment by kyleabeauchamp** [comment]
If you are sure that pysam-0.10.0-py35_3 is working correctly, I think it's reasonable to delete the older builds for that version of pysam.

**Comment by mbargull** [comment]
I suppose it's working -- though I myself am not actually an user of that package. Maybe @sebastian-luna-valero can confirm.
Nonetheless I can confirm that `pysam-0.10.0-py35_3` incorporates the fix from #4235 which `pysam-0.10.0-py35_2` has not.

**Comment by sebastian-luna-valero** [comment]
Thanks both.  `pysam-0.10.0-py35_3` is working correctly, so probably removing `pysam-0.10.0-py35_2` is a good idea.

**Comment by bgruening** [comment]
Removed, thanks.
