### ISSUE TITLE
MashTree recipe does not work

### ISSUE THREAD

**Issue by karel-brinda** [bioconda/bioconda-recipes#4742]
Linux:
```
$ sc mashtree mashtree
Fetching package metadata .............
Solving package specifications: 

PackageNotFoundError: Dependency missing in current linux-64 channels: 
  - mashtree -> perl 5.22.0*

Close matches found; did you mean one of these?

    perl: perl-b, petl, pepr
```

OS X:
```
$ sc mashtree mashtree
Fetching package metadata .............
Solving package specifications: 

PackageNotFoundError: Dependency missing in current osx-64 channels: 
  - mashtree -> perl 5.22.0*

Close matches found; did you mean one of these?

    perl: perl-b, petl, pepr
```

@druvus Do you have any idea where is the problem?

**Comment by druvus** [comment]
Looks like you didn't add the conda-forge channel.

**Comment by druvus** [comment]
@karel-brinda Please try to run the following first so you know all channels are added: 

```
conda config --add channels conda-forge
conda config --add channels defaults
conda config --add channels r
conda config --add channels bioconda
```

**Comment by karel-brinda** [comment]
Thank you, ` conda config --add channels conda-forge` solved the problem. Why is this channel needed?

**Comment by druvus** [comment]
Bioconda focus on bioinformatic software and depends on conda-forge, r and defaults for more general software/library dependencies. For further information please see the [Using Bioconda instructions.](https://bioconda.github.io/#using-bioconda)

**Comment by bgruening** [comment]
@druvus just woke up and saw a bunch of mails from you in bioconda ... thanks a lot!!!

**Comment by karel-brinda** [comment]
@druvus Ok, thank you. I completely overlooked `conda-forge` and `defaults` in the recommendations. I was not aware of them at all.

**Comment by karel-brinda** [comment]
@druvus Since multiple channels can be required to install a package, the package websites should be changed. See e.g. https://anaconda.org/bioconda/mashtree:
>To install this package with conda run:
>`conda install -c bioconda mashtree=0.12`

This is very misleading and makes the impression that `bioconda` is the only required channel for `mashtree` . I believe that it would be better to display either this command ("no channels in the command, use `conda config --add channels` before installing the packages")
```
conda install mashtree=0.12
```
or this command ("a complete command for installing the package"):
```
conda install -c bioconda -c conda-forge mashtree=0.12
```

**Comment by druvus** [comment]
@bioconda/core please see the comment by @karel-brinda regarding the information at anaconda.org. Does they allow to modify the automatic generated text to clarify bioconda's channel dependencies or add a link  https://bioconda.github.io/  ?

**Comment by johanneskoester** [comment]
Not as far as I know of. Would you volunteer to file a feature request?
