### ISSUE TITLE
Help with bioconductor-rhdf5 on OSX

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#476]
I can't figure out what conda is doing that prevents the build from working. Running `conda build` on on OSX:

``` bash
conda build -c r -c bioconda recipes/bioconductor-rhd5
# ...
# checking whether we are cross compiling... configure: error: in `/Users/temp/anaconda/conda-bld/work/rhdf5/src/hdf5':
# configure: error: cannot run C compiled programs.
# If you meant to cross compile, use `--host'.
# See `config.log' for more details
# make: *** [libhdf5ForBioC.a] Error 1
```

Relevant section from `config.log`:

```
configure:4487: ./conftest
dyld: Library not loaded: @rpath/./libgfortran.3.dylib
  Referenced from: /Users/temp/anaconda/conda-bld/work/rhdf5/src/hdf5/./conftest
  Reason: image not found
./configure: line 4489: 43875 Trace/BPT trap: 5       ./conftest$ac_cv_exeext
configure:4491: $? = 133
configure:4498: error: in `/Users/temp/anaconda/conda-bld/work/rhdf5/src/hdf5':
configure:4500: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

However, if I manually build -- the way I think conda is doing it -- it works:

``` bash
conda install -c r -c bioconda r bioconductor-zlibbioc
curl -O  https://bioarchive.galaxyproject.org/rhdf5_2.14.0.tar.gz
tar -xf rhdf5_2.14.0.tar.gz
cd rhdf5
R CMD INSTALL --build .
```

I don't follow most of the details, but my reading of [this issue](https://github.com/conda/conda-build/issues/279) suggests this was solved at some point in conda itself. 

Any ideas?

**Comment by daler** [comment]
More info implying we may have to wait for a conda-build update: https://github.com/ContinuumIO/anaconda-issues/issues/498

**Comment by dyusuf** [comment]
@daler  any verdict yet on the issue? I am experiencing the same with rhtslib #2844

**Comment by daler** [comment]
Haven't made progress on this in many months . . . however using gcc instead of llvm for OSX has fixed some other problems in the meantime, so maybe that would help here?

**Comment by dyusuf** [comment]
I added gcc as one build dependency, while it did not work.  I guess I need to override the environmental variables? 

could you point me to the related recipe? cheers.

**Comment by bgruening** [comment]
There is no environment variable from bioconda to change the compiler.

**Comment by daler** [comment]
Just leaving a note for when someone gets a chance to work on this: @mvdbeek had some OSX solutions in https://github.com/bioconda/bioconda-recipes/pull/3124 that might work here.

**Comment by dyusuf** [comment]
@daler thanks for the info!

**Comment by druvus** [comment]
It finally exist a bioconductor-rhdf5 osx packages in bioconda, thanks to @acaprez.

**Comment by daler** [comment]
@acaprez very nice, thank you!

(xref #3670)
