### ISSUE TITLE
glmmTMB Package version inconsistency detected while updating Maaslin2 version to 1.16.0 

### ISSUE THREAD

**Issue by renu-pal** [bioconda/bioconda-recipes#47668]
I am getting the following error while updating Maaslin2 version to 1.16.0 for Galaxy platform. 
#46915 

![Screenshot from 2024-05-03 02-06-50](https://github.com/bioconda/bioconda-recipes/assets/148717065/ab206d08-6bb3-489c-b2a6-067bef2744a0)

**Comment by bgruening** [comment]
Please try again. A new version of r-glmmtmb has been released.
