### ISSUE TITLE
Advice for recipe downloading multiple files?

### ISSUE THREAD

**Issue by peterjc** [bioconda/bioconda-recipes#4772]
I've skimmed https://bioconda.github.io/faqs.html and other pages, but have yet to see an example ``meta.yaml`` which defines multiple independent entries under ``source:``. Searching the git repository with grep I could finds lots of examples with multiple URLs, but they all seem to using conditionals like ``# [linux64]``, ``# [linux32]``, ``# [osx]`` etc.

I would like to create an ``effectiveT3`` BioConda recipe to replace the ``tool_dependencies.xml`` used on my Galaxy wrapper:

https://github.com/peterjc/pico_galaxy/blob/master/tools/effectiveT3/tool_dependencies.xml
http://toolshed.g2.bx.psu.edu/view/peterjc/effectivet3

In essence this downloads FIVE separate JAR files, and puts them into a folder structure:

* ``$EFFECTIVET3/TTSS_GUI-1.0.1.jar``
* ``$EFFECTIVET3/module/TTSS_ANIMAL-1.0.1.jar``
* ``$EFFECTIVET3/module/TTSS_PLANT-1.0.1.jar``
* ``$EFFECTIVET3/module/TTSS_STD-1.0.1.jar``
* ``$EFFECTIVET3/module/TTSS_STD-2.0.2.jar``

This is a JAVA package, so I have read https://bioconda.github.io/guidelines.html#java which explains where to put the JAR files, recommends adding a shell script, and suggests https://github.com/bioconda/bioconda-recipes/tree/master/recipes/peptide-shaker as a model.

I could put the primary file ``TTSS_GUI-1.0.1.jar`` into ``meta.yaml``, but can I put in multiple entries under ``source:`` each with their own checksum?

Or, should I could put the primary file ``TTSS_GUI-1.0.1.jar`` into ``meta.yaml``, and have the ``build.sh`` itself download the four child JAR files itself (and verify their checksums)?

**Comment by peterjc** [comment]
Is there any easy way to get ``shasum`` installed as a build dependency? e.g. https://travis-ci.org/bioconda/bioconda-recipes/jobs/234836961

```
/opt/conda/conda-bld/recipe_1495462269594/work/conda_build.sh: line 17: shasum: command not found
```

**Comment by daler** [comment]
@peterjc WRT your original question, I think your latter solution is the best (choose a single source; download the rest in `build.sh`). WRT to `shasum`, try `sha256sum` instead, should be installed in `condaforge/linux-anvil`.

**Comment by peterjc** [comment]
OK, so the primary file's URL goes in ``meta.yaml`` and any secondary files should be downloaded and verified using ``build.sh`` - thanks!

**Comment by peterjc** [comment]
@daler is there an easy way to get ``sha256sum`` on the Mac build platform?

RE: https://travis-ci.org/bioconda/bioconda-recipes/builds/237209331 from https://github.com/bioconda/bioconda-recipes/pull/4790

If I switched to MD5 checksums, there would likely be the annoyance of ``md5`` vs ``md5sum``

**Comment by peterjc** [comment]
I'm trying this approach in my ``build.sh`` file:

```
# Expect ``sha256sum $FILE`` on Linux, or ``shasum -a 256 $FILE`` on macOS
SHA256CMD="$(command -v sha256sum || echo shasum -a 256)"
```

The same idea should also work for ``md5`` vs ``md5sum``

**Comment by peterjc** [comment]
Aliases did not work, as per https://github.com/bioconda/bioconda-recipes/tree/master/recipes/effectivet3 added in #4790 I used ``curl`` and ``sha256sum`` in my ``build.sh`` for fetching and verifying the child files. These commands can be made available under both macOS and Linux by declaring build dependencies:

```
requirements:
  build:
    - curl
    - coreutils
```
