### ISSUE TITLE
Updating recipes via `autobump` failed.

### ISSUE THREAD

**Issue by akikuno** [bioconda/bioconda-recipes#47929]
The autobump recently failed. 

The error message might not be related to the recipe updates.

```
No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request
```
https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=58686&view=logs&j=eb1ca712-fec5-5d93-deb0-40983fe61f2f

I would appreciate your assistance with this matter.

**Comment by corneliusroemer** [comment]
See https://github.com/bioconda/bioconda-recipes/issues/41025
