### ISSUE TITLE
Azure test fails with memory error

### ISSUE THREAD

**Issue by npbhavya** [bioconda/bioconda-recipes#48226]
Hi there,

I've been attempting to update the sphae meta.yaml file from v1.3.4 to v1.4.1, but the conda build is failing with a MemoryError: std::bad_alloc. You can find the build output at [47721](https://github.com/bioconda/bioconda-recipes/pull/47721).

Could someone please help me determine if this is a bioconda issue or if it's something that needs to be addressed in the code?

Thank you, 
Bhavya

**Comment by mencian** [comment]
Re-triggering the CI seems to have done the trick @npbhavya! Fortunately, the issue seems to be temporary. I have merged the PR; please feel free to re-open this thread if I have missed anything!
