### ISSUE TITLE
A small suggestion on submission mechanism of recipes

### ISSUE THREAD

**Issue by ZhijianZhou01** [bioconda/bioconda-recipes#48237]
Whether Conda's submission mechanism can be optimized. After each recipes test is successful, it says that the branch is old, then the branch needs to be updated, then it goes into test and wait, and then the branch is old again. Then, enter the endless loop.

**Comment by martin-g** [comment]
The update to latest `master` is not mandatory.
One can use the update/rebase button to re-trigger the CI checks but the PR could be merged without being up to date.

**Comment by ZhijianZhou01** [comment]
Thanks!
