### ISSUE TITLE
Trevor

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#4834]
@notestaff I have seen your trevor request and might have denied it too fast because I thought it was spam (the homepage link did not work). Can you provide a bit more detail first? The [command line application](https://github.com/vadimdemedes/trevor) does not look like it would need additional permissions in order to be run (I think it would be perfect to replace our simulate-travis.py).

**Comment by johanneskoester** [comment]
@notestaff could you tell me what is going on? I have now received a request for coveralls access? Is this intentional?

**Comment by notestaff** [comment]
Not sure what Trevor is.  I was logging into coveralls with github to
work on viral-ngs, and may have clicked something related to bioconda
instead; please ignore.

**Comment by johanneskoester** [comment]
Ok! Thanks for clarification.
