### ISSUE TITLE
gnuplot 5.0.4 errors

### ISSUE THREAD

**Issue by jerowe** [bioconda/bioconda-recipes#4848]
```
(/scratch/gencore/software/gnuplot/5.0.4) [gencore@login-0-4 ~]$ :gnuplot
gnuplot: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
```

I'll be looking into this today.

**Comment by bgruening** [comment]
My guess is that is was not strictly pinned against this older libjpeg version and you get now the version 9 during install. Pinning it would solve it probably.

**Comment by rvalieris** [comment]
this is now fixed on https://github.com/bioconda/bioconda-recipes/issues/5065
