### ISSUE TITLE
Travis-run.sh failed in Linux

### ISSUE THREAD

**Issue by shenwei356** [bioconda/bioconda-recipes#4849]
Dear @johanneskoester , your last [commit](https://github.com/bioconda/bioconda-recipes/commit/96798e71b579dbcc13793de40d2b0b0fd8579aa6) seems not perfect.

[Travis log](https://travis-ci.org/bioconda/bioconda-recipes/jobs/236839643#L514):

```
scripts/travis-run.sh: line 96: GITHUB_TOKEN: unbound variable
```

[Corresponding code](https://github.com/bioconda/bioconda-recipes/blob/master/scripts/travis-run.sh#L96):

```
  if [[ $TRAVIS_OS_NAME == "linux" && $TRAVIS_PULL_REQUEST != "false" && -n $GITHUB_TOKEN ]]
```

**Comment by johanneskoester** [comment]
Thanks! It has been fixed. I apologize!
