### ISSUE TITLE
libtool / libtoolize

### ISSUE THREAD

**Issue by cristhomas** [bioconda/bioconda-recipes#4864]
One of the packages I'm trying to build a recipe for requires libtool and libtoolize. libtool is a conda package, I have it in the requirements. Still, it is not picked up when I run conda build. 
below is the output I get.

Ideas?

~/git/conda_recipe$ conda build recipes/bioconductor-flowworkspace/
BUILD START: bioconductor-flowworkspace-3.22.0-r3.3.2_0

The following NEW packages will be INSTALLED:

    bioconductor-biobase:      2.32.0-0             bioconda   
    bioconductor-biocgenerics: 0.22.0-r3.3.2_0      local      
    bioconductor-flowcore:     1.42.0-r3.3.2_0      local      
    bioconductor-flowviz:      1.40.0-r3.3.2_0      local      
    bioconductor-graph:        1.48.0-1             bioconda   
    bioconductor-ncdfflow:     2.22.0-r3.3.2_0      local      
    bioconductor-rbgl:         1.52.0-r3.3.2_0      local      
    bioconductor-rgraphviz:    2.14.0-0             bioconda   
    bioconductor-zlibbioc:     1.22.0-r3.3.2_0      local      
    bzip2:                     1.0.6-3                         
    cairo:                     1.14.8-0                        
    cloog:                     0.18.0-0                        
    curl:                      7.52.1-0                        
    fontconfig:                2.12.1-3                        
    freetype:                  2.5.5-2                         
    gcc:                       4.8.5-7                         
    glib:                      2.50.2-1                        
    gmp:                       6.1.0-0                         
    gsl:                       2.2.1-0                         
    harfbuzz:                  0.9.39-2                        
    icu:                       54.1-0                          
    isl:                       0.12.2-0                        
    jbig:                      2.1-0                           
    jpeg:                      9b-0                            
    libffi:                    3.2.1-1                         
    libgcc:                    5.2.0-0                         
    libiconv:                  1.14-0                          
    libpng:                    1.6.27-0                        
    libtiff:                   4.0.6-3                         
    libtool:                   2.4.2-0                         
    libxml2:                   2.9.4-0                         
    mpc:                       1.0.3-0                         
    mpfr:                      3.1.5-0                         
    ncurses:                   5.9-10                          
    openssl:                   1.0.2l-0                        
    pango:                     1.40.3-1                        
    pcre:                      8.39-1                          
    pixman:                    0.34.0-0                        
    r:                         3.3.2-r3.3.2_0       r          
    r-assertthat:              0.1-r3.3.2_4         r          
    r-base:                    3.3.2-1              r          
    r-bh:                      1.62.0_1-r3.3.2_0    local      
    r-boot:                    1.3_18-r3.3.2_0      r          
    r-class:                   7.3_14-r3.3.2_0      r          
    r-cluster:                 2.0.5-r3.3.2_0       r          
    r-codetools:               0.2_15-r3.3.2_0      r          
    r-colorspace:              1.3_1-r3.3.2_0       r          
    r-corpcor:                 1.6.9-r3.3.2_0       local      
    r-data.table:              1.10.0-r3.3.2_0      r          
    r-dbi:                     0.5_1-r3.3.2_0       r          
    r-deoptimr:                1.0_8-r3.3.2_0       r          
    r-dichromat:               2.0_0-r3.3.2_2       r          
    r-dplyr:                   0.5.0-r3.3.2_0       r          
    r-foreign:                 0.8_67-r3.3.2_0      r          
    r-gridextra:               2.2.1-r3.3.2_0       r          
    r-gtable:                  0.2.0-r3.3.2_0       r          
    r-hexbin:                  1.27.1-r3.3.2_0      r          
    r-idpmisc:                 1.1.17-r3.3.2_0      local      
    r-kernsmooth:              2.23_15-r3.3.2_0     r          
    r-labeling:                0.3-r3.3.2_2         r          
    r-lattice:                 0.20_34-r3.3.2_0     r          
    r-latticeextra:            0.6_28-r3.3.2_0      r          
    r-lazyeval:                0.2.0-r3.3.2_0       r          
    r-magrittr:                1.5-r3.3.2_2         r          
    r-mass:                    7.3_45-r3.3.2_0      r          
    r-matrix:                  1.2_7.1-r3.3.2_0     r          
    r-matrixstats:             0.52.2-r3.3.2_0      conda-forge
    r-mgcv:                    1.8_16-r3.3.2_0      r          
    r-munsell:                 0.4.3-r3.3.2_0       r          
    r-mvtnorm:                 1.0_5-r3.3.2_0       r          
    r-nlme:                    3.1_128-r3.3.2_0     r          
    r-nnet:                    7.3_12-r3.3.2_0      r          
    r-pcapp:                   1.9_61-r3.3.2_0      r          
    r-plyr:                    1.8.4-r3.3.2_0       r          
    r-r6:                      2.2.0-r3.3.2_0       r          
    r-rcolorbrewer:            1.1_2-r3.3.2_3       r          
    r-rcpp:                    0.12.8-r3.3.2_0      r          
    r-rcpparmadillo:           0.7.500.0.0-r3.3.2_0 r          
    r-recommended:             3.3.2-r3.3.2_0       r          
    r-robustbase:              0.92_7-r3.3.2_0      r          
    r-rpart:                   4.1_10-r3.3.2_0      r          
    r-rrcov:                   1.4_3-r3.3.2_0       local      
    r-scales:                  0.4.1-r3.3.2_0       r          
    r-spatial:                 7.3_11-r3.3.2_0      r          
    r-stringi:                 1.1.2-r3.3.2_0       r          
    r-stringr:                 1.1.0-r3.3.2_0       r          
    r-survival:                2.40_1-r3.3.2_0      r          
    r-tibble:                  1.2-r3.3.2_0         r          
    r-xml:                     3.98_1.5-r3.3.2_0    r          
    readline:                  6.2-2                           
    tk:                        8.5.18-0                        
    xz:                        5.2.2-1                         
    zlib:                      1.2.8-3                         

Source cache directory is: /home/cris/miniconda3/conda-bld/src_cache
Found source in cache: flowWorkspace_3.22.0.tar.gz
Extracting download
Package: bioconductor-flowworkspace-3.22.0-r3.3.2_0
source tree in: /home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/work/flowWorkspace
+ source /home/cris/miniconda3/bin/activate /home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+ mv DESCRIPTION DESCRIPTION.old
+ grep -v '^Priority: ' DESCRIPTION.old
+ /home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/R CMD INSTALL --build .
* installing to library ‘/home/cris/R/x86_64-pc-linux-gnu-library/3.3’
* installing *source* package ‘flowWorkspace’ ...
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=c++11 accepts -g... yes
checking for gcc... gcc -std=gnu99
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
configure: setting xml2 flags...
configure: No directory was specified for --with-xml2. Trying to find xml2 using other methods.
checking for xml2-config... /home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/xml2-config
configure: setting protobuf flags...
configure: No directory was specified for --with-protobuf. Using bundled protocol buffer.
found  protobuf-2.6.0  header sources and tar archive;using what is there.
libtoolize: putting auxiliary files in `.'.
libtoolize: can not copy `/home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/share/libtool/config/ltmain.sh' to `./'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: can not copy `/home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/share/aclocal/libtool.m4' to `m4/'
libtoolize: can not copy `/home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/share/aclocal/ltoptions.m4' to `m4/'
libtoolize: can not copy `/home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/share/aclocal/ltsugar.m4' to `m4/'
libtoolize: can not copy `/home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/share/aclocal/ltversion.m4' to `m4/'
libtoolize: can not copy `/home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/share/aclocal/lt~obsolete.m4' to `m4/'
autoreconf: libtoolize failed with exit status: 1
/usr/bin/m4:aclocal.m4:1192: cannot open `m4/libtool.m4': No such file or directory
/usr/bin/m4:aclocal.m4:1194: cannot open `m4/ltoptions.m4': No such file or directory
/usr/bin/m4:aclocal.m4:1195: cannot open `m4/ltsugar.m4': No such file or directory
/usr/bin/m4:aclocal.m4:1196: cannot open `m4/ltversion.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
automake: error: autoconf failed with exit status: 1
mv: cannot stat 'm4/lt~obsolete.m4': No such file or directory
building protobuf...
found  pb_build  ;using what is there.
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking whether gcc -std=gnu99 understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc -std=gnu99... gcc3
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=c++11 accepts -g... yes
checking dependency style of g++ -std=c++11... gcc3
checking how to run the C++ preprocessor... g++ -std=c++11 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking C++ compiler flags...... use user-supplied: -I/home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include
checking whether __SUNPRO_CC is declared... no
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc -std=gnu99... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc -std=gnu99 object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if gcc -std=gnu99 static flag -static works... yes
checking if gcc -std=gnu99 supports -c -o file.o... yes
checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the gcc -std=gnu99 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -std=c++11 -E
checking for ld used by g++ -std=c++11... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ -std=c++11 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ -std=c++11 option to produce PIC... -fPIC -DPIC
checking if g++ -std=c++11 PIC flag -fPIC -DPIC works... yes
checking if g++ -std=c++11 static flag -static works... yes
checking if g++ -std=c++11 supports -c -o file.o... yes
checking if g++ -std=c++11 supports -c -o file.o... (cached) yes
checking whether the g++ -std=c++11 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for ANSI C header files... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for working memcmp... yes
checking for working strtod... yes
checking for ftruncate... yes
checking for memset... yes
checking for mkdir... yes
checking for strchr... yes
checking for strerror... yes
checking for strtol... yes
checking zlib version... ok (1.2.0.4 or later)
checking for library containing zlibVersion... -lz
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether to check for GCC pthread/shared inconsistencies... yes
checking whether -pthread is sufficient with -shared... yes
checking whether what we have so far is sufficient with -nostdlib... no
checking whether -lpthread saves the day... yes
checking the location of hash_map... <unordered_map>
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating protobuf.pc
config.status: creating protobuf-lite.pc
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
sed: can't read ../protobuf-2.6.0/ltmain.sh: No such file or directory
mv: cannot stat 'libtoolT': No such file or directory
cp: cannot stat 'libtoolT': No such file or directory
chmod: cannot access 'libtool': No such file or directory
CDPATH="${ZSH_VERSION+.}:" && cd ../protobuf-2.6.0 && /bin/bash /home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/work/flowWorkspace/src/protobuf-2.6.0/missing aclocal-1.15 -I m4
 cd ../protobuf-2.6.0 && /bin/bash /home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/work/flowWorkspace/src/protobuf-2.6.0/missing automake-1.15 --foreign
configure.ac:75: error: required file './ltmain.sh' not found
Makefile:390: recipe for target '../protobuf-2.6.0/Makefile.in' failed
make: *** [../protobuf-2.6.0/Makefile.in] Error 1
configure: Using the following compilation and linking flags for flowWorkspace
...
...
...
...
installing to /home/cris/R/x86_64-pc-linux-gnu-library/3.3/flowWorkspace/libs
** R
** inst
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/cris/R/x86_64-pc-linux-gnu-library/3.3/ncdfFlow/libs/ncdfFlow.so':
  /home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/bin/exec/../../lib/../.././libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/cris/R/x86_64-pc-linux-gnu-library/3.3/ncdfFlow/libs/ncdfFlow.so)
Error : package ‘ncdfFlow’ could not be loaded
ERROR: lazy loading failed for package ‘flowWorkspace’
* removing ‘/home/cris/R/x86_64-pc-linux-gnu-library/3.3/flowWorkspace’
Traceback (most recent call last):
  File "/home/cris/miniconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/cris/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "/home/cris/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "/home/cris/miniconda3/lib/python3.5/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/home/cris/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 1518, in build_tree
    config=config)
  File "/home/cris/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 1143, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/home/cris/miniconda3/lib/python3.5/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/home/cris/miniconda3/lib/python3.5/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/home/cris/miniconda3/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/home/cris/miniconda3/conda-bld/bioconductor-flowworkspace_1496172010500/work/flowWorkspace/conda_build.sh']' returned non-zero exit status 1

**Comment by acaprez** [comment]
It looks like it is getting pulled in:  `libtool:                   2.4.2-0`.  I suspect it's a more complex issue then.  Do you have a branch somewhere with your recipe(s)?   I can try building it and see if I can reproduce the problem.

**Comment by cristhomas** [comment]
There's a flowWorkspace branch now I just added, I tagged you in the PR.

**Comment by cristhomas** [comment]
thanks for looking into it

**Comment by bgruening** [comment]
@cristhomas @acaprez is this still a problem?

**Comment by immport-devteam** [comment]
might be, but the recipe build this was for works now.

**Comment by cristhomas** [comment]
it might be but flowworkspace now works
