### ISSUE TITLE
How to handle OpenGL requirement on Linux

### ISSUE THREAD

**Issue by chapmanb** [bioconda/bioconda-recipes#489]
Hi all;
I'm working on porting over R/bioconductor libraries to bioconda, and ran into an issue with those that require `r-rgl`. It links against libGLU, and gives errors:
```
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rgl', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/anaconda/envs/_build/lib/R/library/rgl/libs/rgl.so':
  libGLU.so.1: cannot open shared object file: No such file or directory
```
I could fix by installing an OpenGL implementation like Mesa: `yum install mesa-libGLU-devel` on the build box. Does everyone think this is the best plan to handle this, or know of a better/cleaner way to provide the dependency in conda without bringing in a huge X porting effort? Thanks for any help or ideas.

**Comment by johanneskoester** [comment]
To me, it sounds reasonable to assume a working X installation for such packages.

**Comment by chapmanb** [comment]
Johannes -- thanks much. Any objections from anyone if I add `mesa-libGLU-devel` to the CentOS build-bot Dockerfile?

**Comment by chapmanb** [comment]
Thanks again for the feedback. I added mesa in and updated the `bioconda/bioconda-builder` image on Docker Hub so it's now available for recipes. Thanks again.
