### ISSUE TITLE
Monocle conda recipe failed to install on Galaxy 16.10

### ISSUE THREAD

**Issue by apark229** [bioconda/bioconda-recipes#4893]
Hello!
I tried installing a monocle wrapper that I wrote for Galaxy, but the conda recipes for monocle failed to install on Galaxy 16.10.  It seems like the conda recipe for monocle is for linux only (https://anaconda.org/bioconda/bioconductor-monocle) - Could that affect the ability to install on Galaxy?  Also, here is a link to the monocle wrapper just incase: https://testtoolshed.g2.bx.psu.edu/view/apark22/monocle/efa041760b63

Thank you!

**Comment by bgruening** [comment]
@apark229 we need a error what exactly failed to help you. Also can you please try to install this in Galaxy 17.01 or 17.05? 16.10 has not conda enabled by default.

**Comment by bgruening** [comment]
ping @apark229 do you have an error report for us?
Please feel free to contact me or reopen this issue.
