### ISSUE TITLE
Recipe still showing up as build failure on wiki after being fixed and new release

### ISSUE THREAD

**Issue by raufs** [bioconda/bioconda-recipes#48984]
Hi,

Our software zol was one of the recipes broken in the recent update to bioutils. After tinkering the recipe, I was able to adjust the meta.yaml file to pass checks and update zol to the next version release; however, zol is still being listed in https://github.com/bioconda/bioconda-recipes/wiki/build-failures 

Can you please advise on how I can resolve why it is still showing up as a build failure? Do I need to delete the files: build_failure.osx-64.yaml and build_failure.linux-64.yaml in the recipe folder?

Apologies if this is explained somewhere and I missed it.

Thank you,
Rauf

**Comment by martin-g** [comment]
> Do I need to delete the files: build_failure.osx-64.yaml and build_failure.linux-64.yaml in the recipe folder?

Yes, I think this is the way !

**Comment by raufs** [comment]
Awesome, thank you! Will give that a try with the next version bumb.

**Comment by raufs** [comment]
It worked! Thank you @martin-g!
