### ISSUE TITLE
grequests package disappeared from anaconda repo ?

### ISSUE THREAD

**Issue by cokelaer** [bioconda/bioconda-recipes#4926]
To anybody who can help: I had created the grequests recipes a year or so ago with success but it looks like something changed a few days ago. If I type  
```
conda search grequests 
```
only a version py27 is shown (from conda-forge) and the previous versions I had made available on bioconda (27 and 3.5) are not there anymore. I checked on anaconda/bioconda channel interface and indeed it is not there. Yet, it used to work; for instance in my conda env I have the bioconda version appears (py35_1). 

I and others use this version py3.5 that is only available via bioconda so  I was wondering it this package had been changed or removed somehow ? thank you for any help

**Comment by bgruening** [comment]
@cokelaer yesterday we nearly hit our anaconda quota and removed repositories that were also in conda-forge. We tried to only remove exact version, but maybe we did a mistake here. conda-forge includes a bunch of packages not only for py27: https://anaconda.org/conda-forge/grequests/files

Are you missing build-numbers or real version of your recipe? If so we can get them back from git and rebuild them.

Sorry for the inconvenience, this should not happen :(

**Comment by cokelaer** [comment]
Indeed, conda-forge has many versions but for linux only py27 is available (not py35) whereas in packages such as bioservices or sequana (that are  in bioconda) we need the version 3.5 so indeed, it would be great to get them back. I understand that grequests and gevents could/should be in conda-forge but meanwhile we probably should get back those versions in bioconda if possible. thank you

**Comment by cokelaer** [comment]
Not sure what you meant by missing build-numbers or real version ? Right now I cannot see any files at all. Locally I was using the py35_1 of version 0.3.0

**Comment by rvalieris** [comment]
py35 and py36 builds are available on conda-forge now.

**Comment by cokelaer** [comment]
okay seems to work again indeed. Thanks. So no need for grequests on bioconda anymore.

**Comment by bgruening** [comment]
@cokelaer sorry for the inconvenience, for the reference: https://github.com/conda-forge/grequests-feedstock/pull/6
