### ISSUE TITLE
Unable to Build `bowtie` on osx-arm64

### ISSUE THREAD

**Issue by akikuno** [bioconda/bioconda-recipes#49284]
I submitted a Pull Request to make `bowtie` installable on `osx-arm64`, but it failed.

https://github.com/bioconda/bioconda-recipes/pull/49281

I couldn't determine the exact cause, but it seems that the issue might be due to `cpuid` only supporting x86.

```bash
05:41:46 BIOCONDA INFO (ERR) /opt/mambaforge/envs/bioconda/conda-bld/bowtie_1721108465169/_build_env/lib/clang/16/include/cpuid.h:14:2: error: this header is for x86 only
```
[👆 Link of the Error](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/122660/workflows/0ef248bd-d1c4-4e1e-8485-0a89893af1fc/jobs/197192?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary&invite=true#step-107-42657_144)

```bash
05:41:46 BIOCONDA INFO (ERR) /opt/mambaforge/envs/bioconda/conda-bld/bowtie_1721108465169/_build_env/lib/clang/16/include/cpuid.h:298:5: error: invalid output constraint '=a' in asm
```
[👆 Link of the Error](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/122660/workflows/0ef248bd-d1c4-4e1e-8485-0a89893af1fc/jobs/197192?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary&invite=true#step-107-42921_144)

The `cpuid` is found in `processor_support.h` of bowtie ([link](https://github.com/BenLangmead/bowtie/blob/master/processor_support.h)), but despite having the exact same code in bowtie2 ([link](https://github.com/BenLangmead/bowtie2/blob/master/processor_support.h)), bowtie2 builds without issues on `osx-arm64`([link](https://github.com/bioconda/bioconda-recipes/pull/49150)). Therefore, the cause might be something else. I couldn't determine the exact reason.

I apologize for the inconvenience, but I would appreciate any advice you could provide.

**Comment by martin-g** [comment]
Hi,

You will need to make some changes to the Makefile.
For example at https://github.com/BenLangmead/bowtie/blob/master/Makefile#L74 there is a comparison of `uname -m` against `aarch64` that is for Linux ARM64. To make it work for OSX you will need to add `or arm64`

**Comment by akikuno** [comment]
@martin-g

Thank you so much for your instruction!

There was a Pull Request in the bowtie repository regarding exactly this matter.

https://github.com/BenLangmead/bowtie/pull/131

I hope this one will be merged 🙏

**Comment by martin-g** [comment]
You can also do `make POPCNT_CAPABILITY=0` for ARM64 in build.sh

**Comment by akikuno** [comment]
@martin-g 

I've added `make POPCNT_CAPABILITY=0` in build.sh and All checks have passed. 

https://github.com/bioconda/bioconda-recipes/pull/49321

Thank you so much!
