### ISSUE TITLE
Is Azure CI down? It's queuing for all jobs, already >1hr

### ISSUE THREAD

**Issue by corneliusroemer** [bioconda/bioconda-recipes#49400]
<img width="2263" alt="Brave Browser 2024-07-19 02 01 00" src="https://github.com/user-attachments/assets/f668d0a4-dd29-4d0e-8901-499845708c66">

<img width="2218" alt="Brave Browser 2024-07-19 02 00 55" src="https://github.com/user-attachments/assets/0fe6d42c-fcdf-47a4-8671-17818b8aa024">

**Comment by corneliusroemer** [comment]
Things are running again - strange

**Comment by aliciaaevans** [comment]
https://status.dev.azure.com/_event/524064579 

Everything seems to be building now.  I'm guessing this was somehow connected to the CrowdStrike issue even though we aren't using Windows runners.

**Comment by corneliusroemer** [comment]
Did Crowd strike already start 18 hours ago? And on Azure? That'd surprise
me but it's good things are healthy again 😀
