### ISSUE TITLE
"ngs-disambiguate" PackagesNotFoundError

### ISSUE THREAD

**Issue by z1-Hong** [bioconda/bioconda-recipes#49488]
Hi. I've been trying to install "ngs-disambiguate" which is included in bioconda channel.
I've checked that bioconda channel includes this package at anaconda website: https://anaconda.org/bioconda/ngs-disambiguate

I tried the codes below:

conda install -c bioconda ngs-disambiguate
conda install ngs-disambiguate
conda install bioconda::ngs-disambiguate
conda install bioconda/label/cf201901::ngs-disambiguate

However, nothing works. Each try gives me the error of PackagesNotFoundError.

Please let me know how to solve the problem.

**Comment by aliciaaevans** [comment]
Are you trying to install this on Linux or something else? ngs-disambiguate has only been built for linux. The [Files page](https://anaconda.org/bioconda/ngs-disambiguate/files) for a package has the list of versions and platforms available.

**Comment by z1-Hong** [comment]
Thank you for your comment. I tried it on Mac. I will try it on Linux!
