### ISSUE TITLE
Abyss container broken

### ISSUE THREAD

**Issue by ruyjau** [bioconda/bioconda-recipes#4958]
The abyss container is broken. abyss-pe is a make script (starts #!/usr/bin/make), but /usr/bin/make is not included in the container.

**Comment by bgruening** [comment]
@ruyjau can you include make as a run-time dependency? This would hopefully fix it.

**Comment by daler** [comment]
@ruyjau closing for now as the issue should be resolved in fc44914, but please re-open if anything is not working.

**Comment by ruyjau** [comment]
please bump the build number, so we can use the new version
