### ISSUE TITLE
canu container broken

### ISSUE THREAD

**Issue by ruy-jauregui** [bioconda/bioconda-recipes#4963]
The canu container is missing a gnuplot shared library, and returns an error. When a command is given to skip gnuplot, it still won't run.

> rkt-run -e canu quay.io/biocontainers/canu:1.5--pl5.22.0_0 -d canu -p
> pun4 genomeSize=5.2m -pacbio-raw m*.*.subreads.fastq
> -- Canu release v1.5
> -- Detected Java(TM) Runtime Environment '1.8.0_102' (from 'java').
> gnuplot: error while loading shared libraries: libz.so.1: cannot open 
> shared object file: No such file or directory
> 
> ##run with the gnuplot tested option true:
> 
> rkt-run -e canu quay.io/biocontainers/canu:1.5--pl5.22.0_0 -d canu -p
> pun4 genomeSize=5.2m -pacbio-raw m*0.*.subreads.fastq 
> gnuplotTested=true
> 
> -- Canu release v1.5
> 
> -- Detected Java(TM) Runtime Environment '1.8.0_102' (from 'java').
> 
> -- Detected 0 CPUs and 378 gigabytes of memory.
> 
> -- No grid engine detected, grid disabled.
> -- DEBUG
> -- DEBUG
> -- DEBUG Have 1 configurations; largest memory size 378 GB; most cores 0:
> -- DEBUG class0 - 1 machines with 0 cores with 378GB memory each.
> -- DEBUG
> -- Task meryl can't run on any available machines.
> 
> -- It is requesting 4-8 GB memory and 1-4 threads.
> 
> -- See above for hardware limits.
> ===================================================================
> 
> Don't panic, but a mostly harmless error occurred and Canu stopped.
> Canu release v1.5 failed with:
> task meryl failed to find a configuration to run on
> 
>

**Comment by rvalieris** [comment]
just a update on this.

@bgruening triggered a rebuild on the canu recipe (https://github.com/bioconda/bioconda-recipes/pull/4962) and it solved the zlib error, however there is more:

```
# ldd /usr/local/bin/gnuplot
	/lib64/ld-linux-x86-64.so.2 (0x56487abcd000)
	libz.so.1 => /usr/local/bin/../lib/libz.so.1 (0x7f211b3df000)
	libgd.so.3 => /usr/local/bin/../lib/libgd.so.3 (0x7f211b17a000)
Error loading shared library libjpeg.so.8: No such file or directory (needed by /usr/local/bin/gnuplot)
	libpng16.so.16 => /usr/local/bin/../lib/libpng16.so.16 (0x7f211af3a000)
	libfreetype.so.6 => /usr/local/bin/../lib/libfreetype.so.6 (0x7f211aca2000)
	libtiff.so.5 => /usr/local/bin/../lib/libtiff.so.5 (0x7f211aa13000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x56487abcd000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x56487abcd000)
	libstdc++.so.6 => /usr/local/bin/../lib/libstdc++.so.6 (0x7f211a657000)
	libgcc_s.so.1 => /usr/local/bin/../lib/libgcc_s.so.1 (0x7f211a440000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x56487abcd000)
	libfontconfig.so.1 => /usr/local/bin/../lib/./libfontconfig.so.1 (0x7f211a1fe000)
	libjpeg.so.9 => /usr/local/bin/../lib/./libjpeg.so.9 (0x7f2119fc2000)
	libwebp.so.6 => /usr/local/bin/../lib/./libwebp.so.6 (0x7f2119d24000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x56487abcd000)
	liblzma.so.5 => /usr/local/bin/../lib/./liblzma.so.5 (0x7f2119aff000)
	librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x56487abcd000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f21198dd000)
	libxml2.so.2 => /usr/local/bin/../lib/././libxml2.so.2 (0x7f2119575000)
	libicui18n.so.58 => /usr/local/bin/../lib/././libicui18n.so.58 (0x7f2119075000)
	libicuuc.so.58 => /usr/local/bin/../lib/././libicuuc.so.58 (0x7f2118c76000)
	libicudata.so.58 => /usr/local/bin/../lib/././libicudata.so.58 (0x7f2117176000)
	libiconv.so.2 => /usr/local/bin/../lib/././libiconv.so.2 (0x7f2116e88000)
Error relocating /usr/local/bin/../lib/./libfontconfig.so.1: initstate_r: symbol not found
Error relocating /usr/local/bin/../lib/./libfontconfig.so.1: random_r: symbol not found
Error relocating /usr/local/bin/../lib/././libxml2.so.2: __isinf: symbol not found
Error relocating /usr/local/bin/gnuplot: __rawmemchr: symbol not found
Error relocating /usr/local/bin/gnuplot: __isnan: symbol not found
Error relocating /usr/local/bin/gnuplot: __strtod_internal: symbol not found
```

I think we could pin the `jpeg` version on gnuplot but I have no idea how to solve these "symbol not found" errors.

**Comment by bgruening** [comment]
I think this is solved. We tightened our pinning a lot during the last years.
