### ISSUE TITLE
Potential misdirected bin path for latest resfinder build

### ISSUE THREAD

**Issue by KasperThystrup** [bioconda/bioconda-recipes#49732]
Since commit 46a8fda, resfinder can no longer be envoked with its binary path in its envionrmet build. 

I suspect that the following changes in `recipes/resfinder/python_path.patch` may relate to the issue:

from

> --- run_resfinder.py.old	2022-03-24 02:00:31.990686268 -0500
> +++ run_resfinder.py	2022-03-24 02:01:00.924797159 -0500

to

> --- a/src/resfinder/run_resfinder.py
> +++ b/src/resfinder/run_resfinder.py

Since the latest commit seems to change build method to PIP, I'm uncertain how and where to point to the new binary path.

**Comment by KasperThystrup** [comment]
Mentioning @mencian since this was the latest contributor to resfinder on bioconda.

**Comment by mencian** [comment]
Hi @KasperThystrup, testing `resfinder` locally via `python -m resfinder --help` runs as expected:
```console
(resfinder) mzhuang1:Downloads/ $ python -m resfinder --help                                                 [13:08:13]
usage: __main__.py [-h] [-ifa INPUTFASTA] [-ifq INPUTFASTQ [INPUTFASTQ ...]] [--nanopore] -o OUTPUTPATH [-j OUT_JSON]
                   [-b BLASTPATH] [-k KMAPATH] [-s SPECIES] [--ignore_missing_species] [--output_aln]
                   [-db_res DB_PATH_RES] [-db_res_kma DB_PATH_RES_KMA] [-acq] [-ao ACQ_OVERLAP] [-l MIN_COV]
                   [-t THRESHOLD] [-d] [-db_disinf DB_PATH_DISINF] [-db_disinf_kma DB_PATH_DISINF_KMA] [-c]
                   [-db_point DB_PATH_POINT] [-db_point_kma DB_PATH_POINT_KMA] [-g SPECIFIC_GENE [SPECIFIC_GENE ...]]
                   [-u] [-l_p MIN_COV_POINT] [-t_p THRESHOLD_POINT] [--ignore_indels] [--ignore_stop_codons] [-v]
                   [--pickle]

options:
  -h, --help            show this help message and exit
  -ifa INPUTFASTA, --inputfasta INPUTFASTA
                        Input fasta file.
  -ifq INPUTFASTQ [INPUTFASTQ ...], --inputfastq INPUTFASTQ [INPUTFASTQ ...]
                        Input fastq file(s). Assumed to be single-end fastq if only one file is provided, and assumed
                        to be paired-end data if two files are provided.
  --nanopore            If nanopore data is used
  -o OUTPUTPATH, --outputPath OUTPUTPATH
                        Output directory. If it doesn't exist, it will be created.
```
Can you post the command you are using to invoke `resfinder`?

**Comment by KasperThystrup** [comment]
Yes certainly, In the version prior to this, resfindet could be envoled by
a simple 'run_resfinder.py' without running 'python -m'

*Replyed by email

**Comment by mencian** [comment]
@KasperThystrup Please test the newest `resfinder` release as the package should now be able to run with `run_resfinder.py`: see #49903

**Comment by KasperThystrup** [comment]
@mencian Well worked magic on your part. Works like a charm!

**Comment by mencian** [comment]
Closing this issue; please feel free to re-open if I've missed anything!
