### ISSUE TITLE
Please help remove package "mCross" from Bioconda

### ISSUE THREAD

**Issue by huijfeng** [bioconda/bioconda-recipes#49831]
Hi Bioconda team,

Could you kindly remove the package mCross from the bioconda channel please? This package is out of date and we are now run the package under personal Chanel.  It is misleading for users to download this version. Thanks!

Regards,
Huijuan

**Comment by martin-g** [comment]
Removing the package may break the build of any recipes that use it as a dependency.
IMO you need to promote your personal channel and make it clear that it provides a newer version. Or update the Bioconda recipe to build the newer version.
