### ISSUE TITLE
Missing UCSC package(s)

### ISSUE THREAD

**Issue by lparsons** [bioconda/bioconda-recipes#4988]
It seems that `scripts/ucsc/create-ucsc-packages.py` is missing some (at least one) UCSC tool: [`ldHgGene`](https://github.com/ENCODE-DCC/kentUtils/blob/master/src/hg/makeDb/ldHgGene/ldHgGene.c).

**Comment by bgruening** [comment]
Fixed with: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/ucsc-ldhggene
