### ISSUE TITLE
Build failure due to insufficient memory

### ISSUE THREAD

**Issue by eunos-1128** [bioconda/bioconda-recipes#50781]
When building a package called Maxit, the build fails on Linux due to insufficient memory (the build succeeds on Mac OS).

https://github.com/bioconda/bioconda-recipes/pull/50687

It's a C++ program, so I've tried various compilation optimizations and linker options, but to no avail.

The part that converts large CIF files to ODB files requires a lot of memory, and it seems that the process stops halfway through due to insufficient memory.

I tried creating a swap file, but I couldn't do it because I needed administrator privileges.

If anyone knows of a good solution, I'd be grateful for any advice.

Is it possible to increase the memory of the instance used in CI?

**Comment by eunos-1128** [comment]
I think building this package on linux needs 16GB RAM instance.

**Comment by aliciaaevans** [comment]
This PR was merged a while back. Also, we've switched over to GitHub Actions today, which should avoid this issue for other PRs.
