### ISSUE TITLE
update the boost pinning?

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#5109]
@johanneskoester @bgruening do you think we could bump our pinned boost version?

My reasoning is as follows . . . .

The test in #5108 is failing because `r-curl` is expecting `icu=58`. The specific failure is here: https://travis-ci.org/bioconda/bioconda-recipes/jobs/250111061#L1108

I tracked it down to the fundamental issue that `r=3.3.2` switched `icu` versions between build numbers, but neither we nor conda-forge pin `r-base` build numbers or `icu` version`cs. I figured out that:

- `r-base=3.3.2_2` uses `icu=56`
- `r-base=3.3.2_5` uses `icu=58`
- `boost=1.61` (our current pinned version) uses `boost-cpp=1.61` which in turn pins `icu=56`

I suspect that the conda-forge `r-curl` was built against an `r-base` that used `icu=58`. Since icu is not explicitly specifed in `r-curl`, the conda environment for #5108 forces `r=3.3.2_2, icu=56` because of `boost=1.61`, but happily includes `r-curl` despite the fact that it is incompatible.

The problem is solved when I bump the boost version, as in 728dfb38a4.

So @bioconda/core, is it OK to bump boost? The `bulk` branch should hopefully make it straightforward to do this.

**Comment by chapmanb** [comment]
Ryan;
+1 from me. icu 56 versus 58 has been driving me crazy with incompatibilities. Stabilizing on 58 would help a lot. Thanks for looking at this.

**Comment by bgruening** [comment]
We should align our pinning more to conda-forge. So +1.

**Comment by johanneskoester** [comment]
Yes, I totally agree. Feel free to trigger the update in the bulk branch.

**Comment by daler** [comment]
OK, I'll work on that. Looks like a fair amount of conflicts to work on between master and bulk, so I'll fix that first and then bump boost.

Just want to add a cross-reference here to what @epruesse brought up: https://github.com/bioconda/bioconda-utils/issues/142, which points out [`pin_the_slow_way.py`](https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py#L39)

**Comment by johanneskoester** [comment]
Conflicts? How come? Has anybody worked on bulk since the last merge (after R migration)?

**Comment by johanneskoester** [comment]
I think it should be fine to simply take everything from master. When a new bulk update is done, bulk should be a copy of master.

**Comment by daler** [comment]
Not sure why, but there were conflicts between master and bulk in a fresh clone. I went through them manually just to see what changed, and kept the master version.

**Comment by bgruening** [comment]
We are now pinning boost globally in sync with conda-forge, so I think we can close this one.
