### ISSUE TITLE
Boston / New England Bioconda meetup?

### ISSUE THREAD

**Issue by jerowe** [bioconda/bioconda-recipes#5118]
Are there any bioconda members in the New England area that would like to have a very informal meetup?

**Comment by bgruening** [comment]
@jerowe I'm too far away unfortunately :(
But maybe this is interesting for you. We developed some training slides here https://galaxyproject.github.io/training-material//topics/dev/tutorials/conda/slides.html#1
If you skip the first once this might be useful for such an event.

**Comment by jerowe** [comment]
I was thinking more along the lines of sticking some unsuspecting relative
with my kids and going for coffee. ;)

But I've been asked a few times about having a training for building
bioconda packages. I will be stealing these.
