### ISSUE TITLE
New package fails with mulled-build error on Travis (works fine with simulate-travis.py)

### ISSUE THREAD

**Issue by tdido** [bioconda/bioconda-recipes#5122]
Not sure how to debug Travis since I can't replicate the error locally. Any guidance appreciated.

https://travis-ci.org/tdido/bioconda-recipes

**Comment by rvalieris** [comment]
the error is:
```SERR ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory```

try adding libgcc dependency.

**Comment by HenningTimm** [comment]
I encounter the same error: [Travis log](https://travis-ci.org/HenningTimm/bioconda-recipes/jobs/252428277)

Everything runs fine with `simulate_travis.py`, but fails on Travis when I push to my forked repo. 
Adding libgcc as both a build and run dependency fixed it.

**Comment by tdido** [comment]
Yep, that solved it. Thanks1
