### ISSUE TITLE
MaxBin2 installation issue

### ISSUE THREAD

**Issue by UniAlberta** [bioconda/bioconda-recipes#51292]
Hi there, I`m using conda install bioconda::maxbin2 or conda install bioconda/label/cf201901::maxbin2 on linux. But I get the error of RuntimeError: Unable to read repodata JSON file 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64', error was: parse error line 1.
Could you please help me to solve this?
Thanks

**Comment by martin-g** [comment]
Please paste the exact commands you run!
Runtime error means the installation went well but issuing some other command fails.

**Comment by UniAlberta** [comment]
I try 
1) conda install bioconda::maxbin2 or 
2) conda install bioconda/label/cf201901::maxbin2
and neither of them works and gives me the error I sent above

**Comment by UniAlberta** [comment]
Never mind! I finally installed that.

**Comment by mencian** [comment]
Closing this issue as it seems you have it figured out; feel free to re-open if something else arises.
