### ISSUE TITLE
`simulate_travis.py --install-requirements` downgrades miniconda root environment

### ISSUE THREAD

**Issue by HenningTimm** [bioconda/bioconda-recipes#5134]
As mentioned here https://github.com/bioconda/bioconda-recipes/issues/3808, miniconda now ships with Python 3.6. This creates some issues when using the `simulate_travis.py` script.

I installed a brand new version of miniconda, and installed conda-build and anaconda.
When following the [tutorial on how to contribute a recipe](https://bioconda.github.io/contribute-a-recipe.html), running

    ./simulate-travis.py --set-channel-order
    ./simulate-travis.py --install-requirements

downgrades the root environment of miniconda from 3.6 to 3.5 using packages from conda-forge without any questions asked. 

    timm@neuromancer:~/repos/bioconda-recipes$ ./simulate-travis.py --install-requirements
    Fetching package metadata .............
    Solving package specifications: .
    
    Package plan for installation in environment /home/timm/miniconda3:
    
    The following NEW packages will be INSTALLED:
    
        argh:               0.26.2-py35_1      conda-forge
        bkcharts:           0.2-py35_0         conda-forge
        bzip2:              1.0.6-1            conda-forge
        certifi:            2017.4.17-py35_0   conda-forge
        colorlog:           2.10.0-py35_0      conda-forge
        galaxy-lib:         17.5.9-py35_1      bioconda   
        gmp:                6.1.2-0            conda-forge
        imageio:            2.2.0-py35_0       conda-forge
        involucro:          1.1.2-0            bioconda   
        lzo:                2.06-0                        
        mccabe:             0.6.1-py35_0       conda-forge
        ncurses:            5.9-10             conda-forge
        pandoc:             1.19.2-0           conda-forge
        pyaml:              15.8.2-py35_0      conda-forge
        pydotplus:          2.0.2-py35_0       conda-forge
        pygithub:           1.29-py35_0        conda-forge
        sphinx_rtd_theme:   0.1.9-py35_0       conda-forge
        webencodings:       0.5-py35_0         conda-forge
        whoosh:             2.7.4-py35_0       conda-forge
    
    The following packages will be UPDATED:
    
        _license:           1.1-py36_1                     --> 1.1-py35_1                    
        anaconda:           4.4.0-np112py36_0              --> custom-py35_0                 
        anaconda-navigator: 1.6.2-py36_0                   --> 1.6.3-py35_0                  
        anaconda-project:   0.6.0-py36_0                   --> 0.6.0-py35_0                  
        astroid:            1.4.9-py36_0                   --> 1.5.3-py35_0       conda-forge
        astropy:            1.3.2-np112py36_0              --> 1.3.3-np112py35_0  conda-forge
        backports:          1.0-py36_0                     --> 1.0-py35_0                    
        bitarray:           0.8.1-py36_0                   --> 0.8.1-py35_0                  
        blaze:              0.10.1-py36_0                  --> 0.10.1-py35_0                 
        bokeh:              0.12.5-py36_1                  --> 0.12.6-py35_0      conda-forge
        boto:               2.46.1-py36_0                  --> 2.47.0-py35_0                 
        cloudpickle:        0.2.2-py36_0                   --> 0.3.1-py35_0       conda-forge
        cryptography:       1.8.1-py36_0                   --> 1.9-py35_0         conda-forge
        cython:             0.25.2-py36_0                  --> 0.25.2-py35_1      conda-forge
        [...]

    The following packages will be SUPERSEDED by a higher-priority channel:
    
        alabaster:          0.7.10-py36_0                  --> 0.7.10-py35_0      conda-forge
        anaconda-client:    1.6.3-py36_0                   --> 1.6.3-py35_0       conda-forge
        asn1crypto:         0.22.0-py36_0                  --> 0.22.0-py35_0      conda-forge
        babel:              2.4.0-py36_0                   --> 2.3.4-py35_0       conda-forge
        bleach:             1.5.0-py36_0                   --> 1.4.2-py35_0       bioconda   
        bottleneck:         1.2.1-np112py36_0              --> 1.2.0-np112py35_0  conda-forge
        cffi:               1.10.0-py36_0                  --> 1.10.0-py35_0      conda-forge
        chardet:            3.0.3-py36_0                   --> 3.0.2-py35_1       conda-forge
        click:              6.7-py36_0                     --> 6.7-py35_0         conda-forge
        clyent:             1.2.2-py36_0                   --> 1.2.1-py35_0       conda-forge
        [...]

This seems terribly invasive to me. Is this intended behaviour?

**Comment by daler** [comment]
I agree this is pretty invasive. The core problem is that conda-build needs to be in the root environment, so if bioconda-utils needs a particular version of something (due to various bugs we find in conda and conda-build upstream) then the root env needs to reflect that. 

That said, I'd like to convert bioconda-utils to use its own isolated root env using ideas from https://github.com/bioconda/bioconda-utils/pull/145#issuecomment-312008659, which should fix this issue.

**Comment by HenningTimm** [comment]
Ah, I see the problem now. Thanks for the reply. 
Installing a separate miniconda for this sounds like a good Idea. This might also eliminate problems/ errors due to modified root environments, even though I am not sure if this actually happens.

However, for now I just use the Python3.5 environment. So (for me) there is no need to rush this.

**Comment by HenningTimm** [comment]
Solved by #5374
