### ISSUE TITLE
Unit tests not completing, disconnect error 

### ISSUE THREAD

**Issue by joshuailevy** [bioconda/bioconda-recipes#51569]
Hi, 

In PR #51511 (the update of our Freyja tool to v1.5.2), the tests seem to be hanging following a disconnect error that shows up after about 30 minutes - any idea what might be going on here? I don't see any specific test that have failed, and it's unclear with me how to proceed. Is this an issue with the Azure servers? We did see some memory warnings like those mention in Issue #51276. 

Any help would be greatly appreciated! We've been getting a bunch of questions on this since Freyja is used in a lot of public health bioinformatic pipelines.  

Thanks!

**Comment by robomics** [comment]
I think I've been hit by the same bug in PR https://github.com/bioconda/bioconda-recipes/pull/51561.

In my case, builds and tests complete successfully on the ARM runners, but the Linux x86 job fails like described in this issue.
Yesterday I tried to investigate the problem a bit further and came to the conclusion that the runner stops responding before the first line in the test script is executed.

Here is the code in the test script:

```bash
#!/usr/bin/env bash

1>&2 echo "Launching tests..."

sleep 30  # Give the runner a chance to pickup echo's output

"$PYTHON" -c 'import hictkpy; print(hictkpy.__version__)'
"$PYTHON" -m pytest test
```

I tried to run variations of this test multiple times, but I never saw "Launching tests..." being printed before the runner stopped responding.

**Comment by laura-bankers** [comment]
Hi Bioconda team! Are there any updates in resolving this issue?

**Comment by SwiftSeal** [comment]
I'm experiencing similar issues here https://github.com/bioconda/bioconda-recipes/pull/51675, linking for visibility

**Comment by robomics** [comment]
Thanks! things seems to be running smoothly now :)

**Comment by aliciaaevans** [comment]
All the PRs linked in this issue seem to have completing jobs now, so I'll close.
