### ISSUE TITLE
DESeq2 install error: apple-darwin version

### ISSUE THREAD

**Issue by mcornwell1957** [bioconda/bioconda-recipes#5180]
Hi All,

This is probably a user error, so I hate submitting it, but I do not know what the issue is. I am currently installing new software on a couple new computers and am trying to get all of my conda set ups working. On two separate machines (one macOS 10.10 and the other macOS10.12) I am installing the DESeq2 package. It installs "correctly" but if I try and load the library I get this error:

`> library(DESeq2)
Error: package ‘DESeq2’ was built for x86_64-apple-darwin14.5.0
`
Any thoughts? As I said, this is happening on two separate machines, so I am unsure what the issue is.

All I have done is install miniconda, configure channels (conda-forge, defaults, r, bioconda), download r-essentials, and then install bioconductor-deseq2 and dependencies)

Thank you very much for your help,

Tosh

**Comment by mcornwell1957** [comment]
Also may be helpful - This is the top of my R when I start it in my terminal

carelb01:~ Tosh$ R

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin11.4.2 (64-bit)

So is the error because the platforms aren't matching? why would that be?

Thanks again

**Comment by bgruening** [comment]
My assumption is that you OSX version is too old. But I have no clue about OSX. ping @bioconda/osx for help.

**Comment by mcornwell1957** [comment]
Further info:

I am looking at the info pages for DEseq2 for the last two versions (R3.3.1 and R3.3.2) I see that in the 3.3.1 version, in the DESCRIPTION file, this is the Build line: 
Built: R 3.3.1; x86_64-apple-darwin11.0.0; 2017-03-29 16:36:30 UTC; unix
But in the 3.3.2 version in the DESCRIPTION file, this is the build line:
Built: R 3.3.2; x86_64-apple-darwin14.5.0; 2017-06-06 22:43:11 UTC; unix

This looks like the issue, but why is the default R version I am getting when I download the conda R packages an old kernel, where is the disconnect and is it fixable?

Thank you

**Comment by mcornwell1957** [comment]
One more update: Temp fix is to just download everything for R3.3.1 still. Any input or if I can help with this would be great, for now, I'll just stick with R3.3.1 releases for everything

Thanks in advance @bioconda/osx

**Comment by druvus** [comment]
I have just looked into this using MacOS 10.12 by creating a new conda environment: 

`conda create --name r-test bioconductor-deseq2`

Everythin then works while starting R (3.3.2) and loading DESeq2 so I can't reproduce your problem. 

Could you please confirm that you set up the channels in the correct order? See info [here](https://bioconda.github.io/#set-up-channels)

**Comment by mcornwell1957** [comment]
Thanks for the channels tip! I was not aware that we had changed our preferred order and pushed the R channel so far down. I was still downloading all of my stuff from R.

I will close this issue, thank you for all of your help - just for my own knowledge, are bioconda and conda-forge essentially going to start supporting all R packages? has the R channel become defunct? Thanks again!

**Comment by johanneskoester** [comment]
Yes, you can also remove the r channel entirely from your channel list.

**Comment by daler** [comment]
Even when it's completely removed from `.condarc`, the r channel is still part of defaults, at least in recent versions of conda. The solution is to add the following to your `.condarc` to override:

```yaml
default_channels:
  - https://repo.continuum.io/pkgs/free
```
