### ISSUE TITLE
listed sina version number is incorrect

### ISSUE THREAD

**Issue by jvollme** [bioconda/bioconda-recipes#5194]
The version number of SINA in the bioconda repository is given as 1.3.0.
(recipe: [https://github.com/bioconda/bioconda-recipes/tree/master/recipes/sina](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/sina))
 However according to the [developers page](https://www.arb-silva.de/no_cache/download/archive/SINA/), that version does not exist yet.
The current stable version is 1.2.11
The most recent (unstable) beta version is 1.2.13

After installing the conda-repository version and checking it's version number (`sina --version`), I get:
`SINA v1.2.11 (revision 21227) `

So the version number should be corrected to 1.2.11, (otherwise this version may be incorrectly selected over later versions because v1.3 > e.g. 1.2.13)

**Comment by bgruening** [comment]
ping @mdehollander

@jvollme looking at the recipe it downloads a 1.3 version from the silva server: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/sina/meta.yaml#L16

I will ask my friends from de.NBI to get further help.

**Comment by epruesse** [comment]
I've moved SINA to [epruesse/SINA](https://github.com/epruesse/SINA). Now that I've got ARB in bioconda I'm working on getting SINA to build smoothly with conda. Once I've got 1.3.1 finished I'll update the recipe here. Shouldn't be long.

**Comment by bgruening** [comment]
@epruesse thanks a lot!
