### ISSUE TITLE
linting fails due to unrelated recipes

### ISSUE THREAD

**Issue by dlaehnemann** [bioconda/bioconda-recipes#5197]
In my fork, linting of a new recipe I added (monovar) fails, but only cites unrelated recipes:

```
                                     failed_tests
recipe                                           
recipes/anvio             [setup_py_install_args]
recipes/bcbio-nextgen-vm  [setup_py_install_args]
recipes/minvar            [setup_py_install_args]
recipes/multiqc-bcbio     [setup_py_install_args]
```

https://travis-ci.org/dlaehnemann/bioconda-recipes/jobs/252850581

It does pass the `./simulate-travis.py` linting on my machine, presumably because it only lints my local changes it finds through `git`? What should I do about the failure? Create a fixing pull request from a new branch?

**Comment by dlaehnemann** [comment]
Never mind. Did a second round of merging master into the recipe branch and pushed it into my fork and now it runs. No clue why, though...

**Comment by bgruening** [comment]
@dlaehnemann glad you figured it out! :)
