### ISSUE TITLE
What is the maximum package size for a data-heavy application?

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#5206]
Hi Team Bioconda,

I've been playing around with packaging [Antismash](https://bitbucket.org/antismash/antismash)for bioconda (see issue [here](https://bitbucket.org/antismash/antismash/issues/16/suggestion-port-antismash-to-bioconda)). All the deps are on conda and Antismash can be installed using conda (minimal install scripts [here](https://bitbucket.org/zachcp/antismashconda/overview)) but for Antismash to work effectively there are 2 large reference set data downloads (~4GB and ~1GB, compressed) that are required. 

Within the conda/bioconda ecosystem is there a way to distribute files of this size?  Is there a convention for how to use/distribute/require datasets? If not, suggestions would be very welcome.

cc: @bioconda/core 

Thanks,
zach cp

**Comment by johanneskoester** [comment]
Unfortunately not. We are currently at the limit of our storage. While I hope to improve the situation by negotiating with continuum, I cannot yet estimate when this will be possible. In my opinion, a software should provide such datasets on their homepage. Apart from that, there is the go-get-data project, which intends to distribute data via conda packages, see [here](https://github.com/gogetdata/ggd-recipes).

**Comment by daler** [comment]
@zachcp alternatively you can provide a data-download script, as done in https://github.com/bioconda/bioconda-recipes/tree/master/recipes/spectacle.  Actually it looks like from the antiSMASH docs that they already have a python script to download. As long as that gets into `$PREFIX/bin`, users can run that right after they  `conda install antismash`.

**Comment by johanneskoester** [comment]
Good point!

**Comment by zachcp** [comment]
Thanks guys.  These are great suggestions. Not sure of the best way to do this; a good solution shouldn't add too much complexity on top of what currently exists.

**Comment by johanneskoester** [comment]
Well, if the tool already provides a script, it seems reasonable to include that into $PREFIX/bin, and mention it in `extra::notes`.

**Comment by zachcp** [comment]
true. the only thing I'm thinking is that it would balloon the conda directory, but that is a different problem.
