### ISSUE TITLE
Continuum just doubled our storage

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#5208]
@bioconda/all I am glad to announce that continuum was so kind to double our storage in order to support our continued growth! I want to use this opportunity to thank all of you for your work on this amazing project! I would never have dreamed how big and popular bioconda would become!

If you are on Twitter, please retweet this to thank continuum: 
https://mobile.twitter.com/johanneskoester/status/885620657890971648

**Comment by kyleabeauchamp** [comment]
Nice work!

**Comment by inodb** [comment]
Congrats to the community! This is an awesome resource. Really one of those huge leaps forward in bioinformatics not easily reflected in citation count.

**Comment by hainm** [comment]
![beer-icon](https://user-images.githubusercontent.com/4451957/28190210-cfddb6c6-67f7-11e7-8d88-f1deb3952e92.png)

**Comment by khourhin** [comment]
Great news ! Thanks to you all !

**Comment by bgruening** [comment]
And now we have unlimited storage as it seems. Anaconda rocks!
