### ISSUE TITLE
Julia for macOS

### ISSUE THREAD

**Issue by abhi18av** [bioconda/bioconda-recipes#5211]
Hi bioconda team :)

This is a feature request regarding `julia` language. I'd love to have the julia installation managed (mostly) via `conda` channel. Presently, the `julia recipe` is

- Lagging behind the latest releases
- Doesn't have a version for `macOS`.

Could you help me out?

**Comment by bgruening** [comment]
@abhi18av you can update the julia release and try to remove the skip for OSX. If you have a PR open we can help you further. Does this work?
In general we should also consider to move julia into conda-forge.

**Comment by abhi18av** [comment]
Ah, that's a great idea!

Could you guide me to the necessary resources I'd need to learn more about
this? This might be my first contact package.

**Comment by bgruening** [comment]
Sure, this side contains a lot of information: https://bioconda.github.io/

**Comment by cbrueffer** [comment]
The bioconda julia recipe has been removed in favor of the one in the conda-forge channel.
