### ISSUE TITLE
Gnuplot is not compiled in QUAST recipe and can cause errors in downstream usage

### ISSUE THREAD

**Issue by michaelbarton** [bioconda/bioconda-recipes#5213]
## Description of error

When running the [QUAST biocontainer][quast], based on the QUAST bioconda
recipe, I get the following warning:

[quast]: https://quay.io/repository/biocontainers/quast

```
NOTICE: Failed to compile gnuplot (/usr/local/lib/python2.7/site-packages/quast_libs/gnuplot)! Try to compile it manually. You can restart Quast with the --debug flag to see the compilation command
```

This appears to be because gnuplot is not compiled by `python "setup.py"
install_full` during the bioconda build. Furthermore this is a warning and not
an error so `quast.py --test` does not return an exit code which would cause
the bioconda test to tail.

This warning does however become an error when trying to use the biocontainer
as part of common workflow language because the `--read-only=true` flag is used
when running Docker images. This error is:

```
[Errno 30] Read-only file system: '/usr/local/lib/python2.7/site-packages/quast_libs/gnuplot/make.log'
```

A work-around for this is to use the `--no-plots` flag, where QUAST does not
then use gnuplot.

## Fix for problem

I believe a fix for this would be something like adding the following to the
build.sh script:

```
make CFLAGS="-Wall -Wextra -Wunused -mpopcnt -std=gnu++0x -fopenmp -I${PREFIX}/include" -C ${QUAST_HOME}/quast_libs/gnuplot
```

I've tried to test this fix but I have been unable to so far. These are the
steps I took:

I installed miniconda, and then subsequently conda-build and bioconda-utils. I
however got an error where github could not be imported, `pip install PyGitHub`
appeared to fix this. I then ran the specified instructions outlined on the
contributions guidelines:

```
./simulate-travis.py --set-channel-order
./simulate-travis.py --install-requirements
```

This returned the error:

```
WARNING: conda-build appears to be out of date. You have version 2.1.16 but the latest version is 3.0.5.
```

I followed the supplied instructions by conda and ran this command:

```
conda update -n root conda-build
```

After doing this, I still get the conda-build out of date message. I am
therefore unable to test the changes to the conda recipe on my local machine.
Alternatively I tried using the `--docker` flag specified on the contributing a
recipe page:

```
./simulate-travis.py --docker --package quast
```

This generated the following output:

```
+ bioconda-utils lint recipes config.yml --git-range master HEAD
14:01:22 BIOCONDA INFO Recipes newly unblacklisted:

14:01:22 BIOCONDA INFO Recipes to consider according to git:
recipes/quast
14:01:22 BIOCONDA INFO Recipes to lint:
recipes/quast
+ set +x
+ bioconda-utils build recipes config.yml --loglevel=info --docker --package quast --git-range master HEAD
14:01:32 BIOCONDA INFO DOCKER: Pulling docker image condaforge/linux-anvil
14:01:34 BIOCONDA INFO DOCKER: Done pulling image
14:01:34 BIOCONDA INFO DOCKER: Building image "tmp-bioconda-builder" from /var/folders/pq/tqplnxrx1h1gl3c7fsk4mnjm0000gp/T/tmprrx5jxe3
...
14:04:34 BIOCONDA INFO DOCKER: Built docker image tag=tmp-bioconda-builder
14:04:34 BIOCONDA INFO Recipes newly unblacklisted:

14:04:34 BIOCONDA INFO Recipes modified according to git: quast
14:04:34 BIOCONDA INFO blacklist: blast/2.2.21, cap-mirseq, denovogear, detonate, mgkit, mothur/1.36.1, perl-font-afm, r-histonehmm
14:04:34 BIOCONDA INFO Filtering recipes

Filtering 1 of 1 (100.0%) recipes/quast
14:04:36 BIOCONDA INFO Nothing to be done.
+ set +x
```

The last line here indicates that there is nothing to be done by the
`simulate-travis.py` script. This indicates to me that the changes to QUAST
were not test.

I would like to contribute to bioconda and fix this bug myself. However I am
currently unable to test a fix for QUAST. What can I change in what I have done
so far to test this fix before submitting a pull request?

**Comment by daler** [comment]
Thanks @michaelbarton! I think the missing piece is that the [build number](https://conda.io/docs/building/meta-yaml.html#build-number-and-string) needs to be bumped in the QUAST meta.yaml file. 

Some background here is that bioconda-utils will lint recipes based on files that changed according to git, but the building is skipped if a package already exists in a channel for that version and build number -- even if that recipe changed according to git.

Something else I want to point out since you mentioned it is the conda upgrade warning and command. Periodically conda versions have bugs or are otherwise incompatible with bioconda-utils infrastructure. The new conda v3 is such a case. The `./simulate-travis.py --install-requirements` ensures you have the same conda version that will run on travis, and it's OK to have a "conda version out of date" message.

**Comment by bgruening** [comment]
@michaelbarton do you have any PR we can look at. I second what Ryan said, you probably just need to bump the version number.
