### ISSUE TITLE
Bot-generated package version was accidental release tag

### ISSUE THREAD

**Issue by jbelyeu** [bioconda/bioconda-recipes#52252]
I just released a new version of a package [svtopovz](https://github.com/PacificBiosciences/HiFi-SVTopo), but accidentally tagged the release as v0.2.1 instead of 0.1.2 as I intended. Unfortunately, the bot automatically drafted a new release for the v0.2.1 tag before I fixed my release version tag, and that nonexistent 0.2.1 version in bioconda is now superseding the most recent real version. Can you suggest a solution? 

Thanks!

**Comment by martin-g** [comment]
@bgruening ^^

**Comment by bgruening** [comment]
We could remove packages if you like, but we try to avoid this. Do the versions matter so much? Could you not just stick with the 0.2 or continue with 0.3? If not I can remove the containers and packages and hope no one has used them already.

**Comment by bgruening** [comment]
Thanks for the ping @martin-g

**Comment by jbelyeu** [comment]
Pretty strong preference for avoiding the version jump. If removal is a problem, is there a way to flag the version as broken or otherwise change installation priority?

**Comment by bgruening** [comment]
We can flag the packages, not the containers.

**Comment by bgruening** [comment]
Ok, I removed the containers and labelled the package as broken.
I hope its working now for you.
