### ISSUE TITLE
Recent versions of STAR do nothing on plain processors

### ISSUE THREAD

**Issue by Saluev** [bioconda/bioconda-recipes#52336]
Applies to `star-2.7.11b-h43eeafb_2` and `star-2.7.10b-h6b7c446_1`, i. e. probably to all STAR builds after [this change](https://github.com/bioconda/bioconda-recipes/commit/fcd38ab8b4b9c541bd0de33a8d8dde2a725a517c). 

I am running `conda` in a Docker environment on a M4-based MacOS system, and the processor apparently lacks all the features listed in [simd-dispatch.sh](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/star/patches/0003-create-simd-dispatch.patch) (avx2, avx, sse4.1, ssse3, sse3). The **expected behavior** would be to invoke `STAR-plain`, which is implemented in the end of `simd-dispatch.sh` (`$BASE-plain "$@"`). But in the actual bioconda package downloaded by `conda install`, this last line is absent:

```
(base) root@3b0922a4d64a:~# tail $(which STAR)
                shift
                # echo "${cmd}" "$@"
                "${cmd}" "$@"
                exit
        fi
}

for SIMD in avx2 avx sse4.1 ssse3 sse3 sse2 sse ; do test_and_run ${SIMD} "$@" ; done

# fallback to plain option
(base) root@3b0922a4d64a:~# 
```
So the **actual behavior** is no behavior at all, no STAR binary is being executed.

I checked the file in `pkgs/` folder for two aforementioned versions of the package, and the line is missing there as well. I cannot fathom why, but maybe rebuilding and reuploading the package could be a solution.

**Comment by martin-g** [comment]
Please send a Pull Request that just bumps the build number of the recipe. 
Then ask the bot to fetch the built artifacts to verify the fix.
