### ISSUE TITLE
k-8, python >=3.8 and osx x86_64

### ISSUE THREAD

**Issue by lynnjo** [bioconda/bioconda-recipes#52529]
This is a follow up to the closed issue 50888 (https://github.com/bioconda/bioconda-recipes/issues/50888)

Has any progress been made to make k8 to build on python >=3.8 for osx x86_64?  We are still in need of this for our pipeline.  Thanks - Lynn

**Comment by martin-g** [comment]
> Has any progress been made to make k8 to build on python >=3.8 for osx x86_64?

No!
Help is welcome!

**Comment by lynnjo** [comment]
@martin-g What sort of issues were you seeing with the osx x86_64 build?  Lookin at notes from the previous issue I see k8 needed a different version of v8/Node.js for Linux and OSX.  If I read the comments correctly, this was fixed for  Linux, Linux ARM, and OSX ARM.  Just not for OSX _x86_64.  Is that correct?

I honestly don't know what to setup to run your tests that have k8 with minimap2 and python, and probably don't have permissions to retest your CI tests that fail.

**Comment by martin-g** [comment]
You could open a PR for k8 and/or minimap2 and experiment. The CI checks will give you the feedback.

**Comment by lynnjo** [comment]
Oh - just saw @mencian note above, so perhaps he is looking at this - thanks!

**Comment by mencian** [comment]
@lynnjo Please give the new macOS build a try!

**Comment by lynnjo** [comment]
Has this been delivered ?  I am still getting an error message.

My environment.yml file looks like:

name: phgv2-updatedTiledb
channels:
  - conda-forge
  - bioconda
  - tiledb
dependencies:
  - python=3.10
  - tiledb-py=0.32.0
  - tiledbvcf-py=0.35.0
  - anchorwave=1.2.5
  - bcftools
  - samtools
  - agc=3.1
  - minimap2=2.28
  
  My command is:
  conda env create --solver libmamba -f upgraded_environment.yml
  
  The error is:
  
  conda env create --solver libmamba -f upgraded_environment.yml
Retrieving notices: ...working... done
Channels:
 - conda-forge
 - bioconda
 - tiledb
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed
Channels:
 - conda-forge
 - bioconda
 - tiledb
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package libtiledbvcf-0.35.0-hfffce77_0 requires tiledb >=2.26.0,<2.27.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ minimap2 2.28**  is installable with the potential options
│  ├─ minimap2 2.28 would require
│  │  └─ libzlib >=1.2.13,<1.3.0a0 , which can be installed;
│  └─ minimap2 2.28 would require
│     └─ k8   with the potential options
│        ├─ k8 0.2.5 would require
│        │  └─ zlib >=1.2.11,<1.3.0a0 , which can be installed;
│        ├─ k8 0.2.5 would require
│        │  └─ zlib >=1.2.13,<1.3.0a0 , which can be installed;
│        ├─ k8 0.2.5 would require
│        │  └─ libzlib >=1.2.13,<1.3.0a0 , which can be installed;
│        ├─ k8 [1.0|1.1|1.2] would require
│        │  └─ python_abi 3.8.* *_cp38 with the potential options
│        │     ├─ python_abi 3.8 would require
│        │     │  └─ python 3.8.* , which can be installed;
│        │     └─ python_abi 3.8, which can be installed;
│        └─ k8 1.2 would require
│           └─ python_abi 3.13.* *_cp313, which can be installed;
├─ python 3.10**  is uninstallable because there are no viable options
│  ├─ python [3.10.0|3.10.10|...|3.10.9] conflicts with any installable versions previously reported;
│  ├─ python [3.10.0|3.10.1|...|3.10.9] would require
│  │  └─ python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;
│  └─ python [3.10.15|3.10.16] would require
│     ├─ libzlib >=1.3.1,<2.0a0  but there are no viable options
│     │  ├─ libzlib 1.3.1 would require
│     │  │  └─ zlib 1.3.1 *_1, which conflicts with any installable versions previously reported;
│     │  ├─ libzlib 1.3.1 would require
│     │  │  └─ zlib 1.3.1 *_2, which conflicts with any installable versions previously reported;
│     │  └─ libzlib 1.3.1 would require
│     │     └─ zlib 1.3.1 *_0, which conflicts with any installable versions previously reported;
│     └─ python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;
├─ tiledb-py 0.32.0**  is installable with the potential options
│  ├─ tiledb-py 0.32.0 would require
│  │  └─ tiledb >=2.26.0,<2.27.0a0 , which requires
│  │     └─ libzlib >=1.3.1,<2.0a0 , which cannot be installed (as previously explained);
│  ├─ tiledb-py 0.32.0 would require
│  │  ├─ python >=3.11,<3.12.0a0 , which can be installed;
│  │  └─ python_abi 3.11.* *_cp311, which can be installed;
│  ├─ tiledb-py 0.32.0 would require
│  │  └─ python_abi 3.12.* *_cp312, which can be installed;
│  └─ tiledb-py 0.32.0 would require
│     ├─ python >=3.9,<3.10.0a0 , which can be installed;
│     └─ python_abi 3.9.* *_cp39, which can be installed;
└─ tiledbvcf-py 0.35.0**  is uninstallable because it requires
   └─ libtiledbvcf 0.35.0 hfffce77_0, which requires
      └─ tiledb >=2.26.0,<2.27.0a0 , which cannot be installed (as previously explained).
      
      
If I remove the version specification for python and minimap2 I end up with python 3.12.8 but minimap2, instead of the 2.28 version I'd like, shows up as minimap2.1.1 with 0 as the build.  This is the same error I was seeing before.
