### ISSUE TITLE
Pixelator singularity builds missing in galaxyproject

### ISSUE THREAD

**Issue by ambarrio** [bioconda/bioconda-recipes#52861]
The Pixelator v0.19.0 recipe was [approved and merged last week](https://github.com/bioconda/bioconda-recipes/pull/52721), and while its Docker image is [available on quay](https://quay.io/repository/biocontainers/pixelator?tab=tags&tag=latest), its Singularity image is [missing on galaxyproject](https://depot.galaxyproject.org/singularity/). I wonder if no upload happened automatically after merging that PR? Weren't these updates supposed to happen daily?

Tagging @bgruening @mencian 

Thanks a lot!

**Comment by bgruening** [comment]
The CI jobs was on hold. Its now working again, thanks for reporting.
