### ISSUE TITLE
Adding Biopython to conda-forge

### ISSUE THREAD

**Issue by souravsingh** [bioconda/bioconda-recipes#5292]
We are looking to add an option for users who like to try biopython to install it using ``conda``. While the binaries for Linux and Mac are updated through the excellent BioConda, the windows binaries for biopython aren't updated to the latest version.

For this reason, I am thinking of adding the biopython recipe to ``conda-forge`` so that we can maintain parity over the various systems. I would like to know if the folks at bioconda are alright with idea of having the biopython recipe at ``conda-forge``.

xref https://github.com/biopython/biopython.github.io/issues/118

cc @bioconda/core

**Comment by tomkinsc** [comment]
If it makes it easier for people to find/use biopython, I'm all for it. We'll be depending on conda-forge for the foreseeable future, so it will remain available to bioconda users.

With the channel precedence [suggested](https://bioconda.github.io/#set-up-channels)  in the bioconda docs, bioconda will be checked first before conda-forge, so it sounds like Windows users will get the package from conda-forge, and Mac/Linux users will source from bioconda, unless it is removed from bioconda and available only on conda-forge.

**Comment by bgruening** [comment]
What ever is the easiest for the package maintainer :)

ping @peterjc

**Comment by peterjc** [comment]
I'm familiar with how BioConda updates work (and how to update them, e.g. #5175), and conda-forge looks somewhat similar (although one repository per package), but I don't now how the default channel is updated.

I take it there are currently no plans for bioconda to expand to cover Windows (using AppVeyor)? I assume not, but that would be great.

Biopython is already on the default channel (Mac, Linux, Windows) but is already two releases out of date https://anaconda.org/anaconda/biopython - if there's an easy way to update that it might be the best option?

Otherwise, given we'd like to have Windows conda packages, @souravsingh seems right - conda-forge looks like a good idea. So +1 on trying this.

**Comment by souravsingh** [comment]
To update the binaries for biopython in the default channel, we would have to ask the uploader of the recipe to do so, which can get quite slow.

If there is no issue, I can quickly create a patch for the biopython recipe.

**Comment by peterjc** [comment]
Biopython is now in conda-forge, which has the advantage of providing Windows binaries:

https://github.com/conda-forge/biopython-feedstock
https://anaconda.org/conda-forge/biopython

Should we now deprecate the BioConda Biopython recipe, or continues to update both?

**Comment by johanneskoester** [comment]
It can be deprecated. But we can do that in an orchestrated effort in the next months. We still need to figure out a good sustainable strategy for this.

**Comment by peterjc** [comment]
@johanneskoester "this" being Biopython, or a more general issue for deprecating BioConda packages?

Speaking from a Biopython perspective, I don't mind having Biopython under both conda-forge and bioconda, and am willing to help keep both/either recipe up to date.

**Comment by bgruening** [comment]
A general strategy for deprecating recipes, I guess. I'm also fine with removing it from bioconda and go for conda-forge only.

**Comment by johanneskoester** [comment]
Yes. If possible, I want to avoid duplicate packages.

**Comment by peterjc** [comment]
So is this as simple are a pull request removing the entire BioConda ``recipes/biopython`` directory? If so I can do that, no problem.

**Comment by peterjc** [comment]
Pull request #5580 removes the Biopython recipe from the bioconda github repository.

**Comment by peterjc** [comment]
The Biopython recipe has now been removed from bioconda, and in future we will only update the conda-forge recipe.

Thanks everyone.
