### ISSUE TITLE
GCC 4.9

### ISSUE THREAD

**Issue by karel-brinda** [bioconda/bioconda-recipes#5297]
Is it possible to use GCC 4.9 in a Bioconda recipe? New versions of Unicycler require GCC 4.9.1+, see https://travis-ci.org/bioconda/bioconda-recipes/jobs/255613237#L764.

cc @bioconda/core

**Comment by johanneskoester** [comment]
Not at the moment. But Continuum IO is working on that. There will hopefully a GCC 5 package in the defaults channel soon. @msarahan: sorry if you are asked this all the time, but is there a place where we can check the progress of the new gcc package?

**Comment by chapmanb** [comment]
Johannes;
To add a +1 to this, I've ran into packages over the last few days I need and can't build without gcc 4.9+ support: the latest hap.py, vg, and hhga. Do you think it's worth trying to come up with workarounds in our Docker container until the more recent versions are available in conda-forge or the default channel?

**Comment by jerowe** [comment]
@chapmanb @karel-brinda - there is already a gcc 4.9 in the conda-forge docker image. Don't include gcc in your build dependencies and you should be using it. Its obviously not ideal, but it has worked for me.

**Comment by msarahan** [comment]
There are preview packages on Ray's channel and my channel, rdonnelly and
msarahan.  Current version is gcc 7.1. note that these are pseudo-cross
compilers, so that package names reflect the compilers name and the target
platform, e.g. gcc_linux-64. There will be a beta program soon for the
ecosystem built with these compilers, and we'll probably have the compilers
be part of that program.

Cc @mingwandroid @csoja

**Comment by msarahan** [comment]
PS: also note that the new compilers are much more separated than before.
The gcc 4.8 package was gcc, g++ and gfortran all in one.  The new
compilers have separate packages for gcc, gxx, and gfortran.

**Comment by chapmanb** [comment]
Mike -- this is great progress, thank you for working on this. I'm looking forward to testing this out in bioconda once we can pull from conda-forge.

Jillian -- thanks for the tip. I'm happy to temporarily use the container gcc but I could only find 4.8.2 in the container as well. Am I using the wrong container/doing something else wrong?
```
$ docker pull condaforge/linux-anvil
Using default tag: latest
latest: Pulling from condaforge/linux-anvil
Digest: sha256:dd53ef1792f777fa8b2abf30221bf9beb6cb6a81d158d498f0219c4d475696cd
Status: Image is up to date for condaforge/linux-anvil:latest
$ docker run -it condaforge/linux-anvil /bin/bash
(root) [root@2b4f7d5a4ddf /]# which gcc
/opt/rh/devtoolset-2/root/usr/bin/gcc
(root) [root@2b4f7d5a4ddf /]# gcc --version
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jerowe** [comment]
You're right. It is 4.8,but it's a special 4.8 with some ports from 4.9 to
support additional features.

**Comment by chapmanb** [comment]
Jillian -- ah, thanks much. Unfortunately the failing tools require gcc 4.9 regex support and it looks like that is not included in the special 4.8.

So it looks like our options right now are to move to the beta program when that's available or to get an updated gcc in the conda-forge container so we can use that in the interim. Does anyone have thoughts about what the best approach is? Thanks much for all the help with this.

**Comment by chapmanb** [comment]
Mike, Ray and all;
Thanks again for all the work on updating gcc versions. I wanted to check if there was a plan we could follow for making use of these versions. This in the context of bioconda builds so ideally we'd have them available via conda-forge so we could use them in recipes that require more recent gcc. If this is still in progress, is there is a good issue or mailing list to follow this work? Then I could lurk and keep up to date without bothering y'all. Thanks again.

**Comment by mingwandroid** [comment]
These new compilers lean heavily on conda-build 3, both for their construction and to make them simple to use.

For conda-forge to have access to them conda-forge needs to move to conda-build 3. It would also be ideal if they could adopt these toolchains globally otherwise you risk missing symbols when an incorrect libstdc++ and libgfortran gets loaded. Unfortunately conda-forge are doing something different for toolchains at present (toolchain3).

We have very recent llvm+clang (4.0.1) for macOS too now and again, it'd be nice to see those adopted.

**Comment by croth1** [comment]
I think we should discuss this also with conda-forge. ping @jakirkham.

**Comment by chapmanb** [comment]
Thanks for all the details on what needs to happen to switch over. I don't have a ton of background on the conda-forge internals but this seems like a lot of work. As a bridge to this it would be great to update the devtoolset in the conda-forge docker container so we could use 4.9 for those tools that need it now, and then swap over after all of the conda-build hurdles are cleared. What do folks think about taking this approach?

**Comment by kyleabeauchamp** [comment]
Is there any news on compiler toolchain updates now that Anaconda has more recent compilers (https://www.anaconda.com/blog/developer-blog/utilizing-the-new-compilers-in-anaconda-distribution-5/)?

**Comment by bgruening** [comment]
Everything looks, good we just waiting for conda-forge to use cb3 and we are all good! :)

**Comment by kyleabeauchamp** [comment]
Cool, I'm curious to see if modern compilers lead to performance improvements for various slow tasks.

**Comment by mingwandroid** [comment]
@kyleabeauchamp, I wouldn't expect more than 10-20% speedup, but for the top end of that, you may need to look into enabling things like LTO and PGO.

Which tasks in particular are you referring to? The two other big benefits of the new compilers are:

1. Support for the latest language features (C++11/14 and 17).
2. *Many* new security settings (PIC throughout, ASLR, read-only relocations, bind-now, SSP).
3. Much better diagnostics and error messages.
4. Santizers that can be used to track down tricky bugs.

To get the full benefit you need to set your compilation flags carefully. Hopefully you will be able to use our compiler activation packages for this though. The recipe is at https://github.com/AnacondaRecipes/aggregate/tree/master/ctng-compilers-activation-feedstock/recipe

**Comment by kyleabeauchamp** [comment]
In particular, I would rebuild BWA, HTSLib, samtools, and pysam.  Even a 10% speedup on those could be valuable to many people in the field.

**Comment by msarahan** [comment]
If you are able to be less conservative about CPU optimization level, you
may also get faster. For compatibility, we keep to optimizing only for
nocona, which corresponds to sse3. Utilizing avx and such might get you
some wins.

**Comment by kyleabeauchamp** [comment]
Yeah, eventually we'll probably need to have some Bioconda discussions about balancing conservative instruction sets versus improved performance.

**Comment by mingwandroid** [comment]
The only thing I think you may wish to change is to change the x86_64 -mcpu from nocona to k8 which will avoid SSE3.

Having said that, SSE3 gives good speedups and we only had 1 complaint about dropping SSE3 (which we didn't actually do deliberately!)

**Comment by mingwandroid** [comment]
Also, the -mcpu prescott precludes the first batch of Pentium 4-m (i.e. the predecessor to the core family), for that we also had 1 complaint.

**Comment by kyleabeauchamp** [comment]
One last question: the new cb3 doesn't make it trivial to have (and select at install-time) multiple builds with different instruction sets, does it?

**Comment by msarahan** [comment]
You have to encode it somehow.  Right now, it seems like adding a metapackage that represents that instruction set capability might be the way to go.  However, that doesn't allow fall-back to lesser optimization when the desired optimization isn't found.

I think the answer it "it should, but it's not proven in practice yet."

**Comment by kyleabeauchamp** [comment]
OK, I have a new question.  I'd like to use GCC 7.3 and target the `march` and optimization flags to rebuild `bwa` (multiple versions) to run faster.  Apparently dockerhub has an image for this version of GCC.  I'm curious if there's a way I can make these builds plug-and-play compatible with bioconda and conda-forge.  Any new thoughts?  Obviously I could compile things locally, but I think the real benefit here would be doing this in a way that benefits everyone.

**Comment by mingwandroid** [comment]
The conda solver has no ability to figure out the end-users CPU, so how do you propose it selects a `bwa` package that is compatible?

We have GCC 7.2 on defaults, building 7.3 should be very easy.

**Comment by kyleabeauchamp** [comment]
I'm thinking we could have the optimized package opt-in, perhaps with meta-packages or something?  I suspect 7.2 might serve my purpose as well, I can test it at some point.

**Comment by kyleabeauchamp** [comment]
Could you share the link to GCC 7.2?  I can't seem to install it via conda.

Meanwhile, I made a manual package build with my optimized compiler settings (https://github.com/kyleabeauchamp/bioconda_fast), but I'm still very interested in brainstorming ways we can make such things reproducible and sharable.

**Comment by msarahan** [comment]
It's in the blog post you linked above: https://www.anaconda.com/blog/developer-blog/utilizing-the-new-compilers-in-anaconda-distribution-5/

The main thing to keep in mind is the glibc lower bound.  Our compilers ship with a sysroot that has an old glibc.  This is what helps us keep our backwards compatibility.  Docker images serve the same purpose, but it's often as much or more work to create a docker image with an old glibc and a new compiler.  Most docker images with new compilers have new glibc, too.

**Comment by jgarc111** [comment]
Hello, @johanneskoester. Going back to one the first comments,

> There will hopefully a GCC 5 package in the defaults channel soon.

How is that coming along? Recently, trying to upgrade a recipe some PR checks failed (#8309) because some libstdc++ functions (`std::move`) are not implemented until GCC 5 and it was compiled using GCC 4.8.5

**Comment by msarahan** [comment]
Please read the rest of this thread.  There is a lot of information that you seem to be missing.

**Comment by s22chan** [comment]
@mingwandroid  fyi, I'm seeing `3x` (3mins to 1min) speedups for RNAcofold in the ViennaRNA package going from GCC `4.8.2` to `7.2.0`

**Comment by mingwandroid** [comment]
Wow, that's great, thanks for the feedback.

**Comment by bgruening** [comment]
We rebuild the entire conda universe against the new compiler stack. It was a huge effort! Thanks a lot to everyone that was involved and to all people waiting patiently until this was done.
