### ISSUE TITLE
remove mmtf package from bioconda

### ISSUE THREAD

**Issue by kain88-de** [bioconda/bioconda-recipes#5306]
I'm maintaining a mmtf package on [conda-forge ](https://github.com/conda-forge/mmtf-python-feedstock). I'm keeping it up to date there. (You are 5 patch releases behind).  It would be nice if you remove the mmtf-package so that people who use bioconda as well can use the current mmtf-package.

**Comment by cbrueffer** [comment]
mmtf-python was removed in 3d3f308879f2bc3355a6a74c11305dc48f2903c0

**Comment by kain88-de** [comment]
Thanks
