### ISSUE TITLE
conda on rhel 5.5   glibc 2.7 are not avaible

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [bioconda/bioconda-recipes#5308]
I install bwa using bioconda but when I try I have this error:
 ```
bwa
bwa: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by bwa)
```

It was able to install python 3.5 and other software. why not glibc?

**Comment by yesimon** [comment]
As in the other issue, your RHEL version and GLIBC versions are too old. You might have better luck compiling from source or trying bwa from the `homebrew-science` keg of `linuxbrew` https://github.com/Linuxbrew/brew
