### ISSUE TITLE
Integration of Bioconda with IPFS

### ISSUE THREAD

**Issue by alphaCTzo7G** [bioconda/bioconda-recipes#5309]
Hi all,

I am thinking of a opensource middlelayer/platform which will be built on top of IPFS (https://medium.com/@ConsenSys/an-introduction-to-ipfs-9bba4860abd0)
 
I recently found out that NCBI/NIH is struggling with the large amounts of data that is being generated from non-human genomes and is now sending the data off to Europe (https://ncbiinsights.ncbi.nlm.nih.gov/2017/05/09/phasing-out-support-for-non-human-genome-organism-data-in-dbsnp-and-dbvar/). I am guessing soon even EVA might start suffering from the data overload, as the volume of genomic data grows 4-5 fold over the next decade (Plos). GB/$ or bandwidth/$ is unlikely to grow at this pace and this problem is likely to get worse. As I see it, the prohibitive cost will drive these agencies to go for some kind of cost sharing using distributed storage and networking.
 
In short IPFS is a p2p distributed file system with built-in incentivizing systems to encourage users to locally cache and distribute data by combining pre-existing and new systems (git, dht, kademlia) that came out of ARPA/DARPA/IETF/Bell labs (https://github.com/ipfs/ipfs#more-about-ipfs).
 
I am thinking of this more as a middle-layer between the platform (Bioconda) and IPFS. Potentially all the datasets will be assigned a IPFS hash and the hash will be maintained on a website along with any metadata regarding the information contained in the dataset.
 
So instead of users having to query specific servers with the server specific API, they will query the dataset and IPFS through a uniform API (ipfs get /ipfs/<hash>).
 
Potential advantages:
1. Simple data access/pipelines across multiple organizations instead of having to use multiple Server specific API’s to get data ( using a simple interface: ipfs get <hash>)

2. Reduces cost of data storage/distribution by distributing data storage/access cost over the entire network
 
3. Proven to work with large datasets
 
4. Backward compatible with existing data transport networks
 
5. Inbuilt incentivization of users to store and distribute data with bitswap, Filecoin and Ethereum 
 
IPFS is developed as a networked file system, so it should be integrated similar to how other software platforms are integrated with files systems. So I was thinking that its best to have it as a default package within the platform, perhaps as a middlelayer. There are already amazing platforms, so I am not thinking of building an entire platform, but integrating IPFS with a great platform so that it benefits potential suppliers and consumers of data.

Based on this, and because the problem is faced acutely in the genomics community and BioConda is one of the most widely used softwares, I was thinking its best to integrate with Bioconda/Anaconda/spyder. 

Do you think its better to integrate with Anaconda/Spyder as that is the platform on which Bioconda is developed?

Are there any existing projects that do this already? Or similar projects that I could look into to, to get ideas from?
 
Do you see any holes in my logic?

I can go into more details on the use case scenario, that I am currently thinking of. 

Thanks

Paul

**Comment by daler** [comment]
@alphaCTzo7G, bioconda is focused on the software installation side of bioinformatics and is largely independent of the data. While it's true that users of bioconda are also typically users of these large datasets, the only integration with bioconda/conda I can think of would simply be to create a package that installs whatever is necessary to run `ipfs get`. I think that's what you are proposing here? That is, the tool would be built elsewhere like any other tool, and simply installed via conda.

In general I think this an interesting idea. You might want to check out https://github.com/gogetdata/ggd-recipes, which uses ideas from conda to get datasets, for some ideas. However something at the scale you're talking would likely require close communication with various data providers (NCBI, Ensembl, etc) and, depending on your use-cases, a ton of metadata headaches.

**Comment by bgruening** [comment]
Another possibility is to mount in the community curated reference datasets that are distributed via CMFS: https://github.com/usegalaxy-eu/cvmfs-example

Let me know if this is helpful or if you want to catch up here. In the meantime, I will close the issue.
