### ISSUE TITLE
noarch for packages which support only one major Python version

### ISSUE THREAD

**Issue by csachs** [bioconda/bioconda-recipes#5335]
I was about to prepare some packages for bioconda which would benefit from being defined as `noarch`, as they are pure Python packages and could be used that way by Windows users as well.

However I just stumbled upon a linting problem (as they are developed for Python 3) and the accompanying documentation, stating:

> This also holds for skipping Python versions, because noarch: python also implies that the resulting package will work with all Python versions. This is typically not the case if you skip a Python version.

I do think that this is a sub-optimal state, given it is for new projects only natural to not artificially add Python 2 backwards compatibility, and it otherwise makes (hosting space and compatibility-wise) very much sense to package these as  `noarch`  packages.

What do you think?

**Comment by daler** [comment]
@csachs agreed, but I'm pretty sure this is a conda upstream constraint rather than bioconda specific, see e.g. https://github.com/conda/conda-build/issues/542#issuecomment-130870047.

**Comment by csachs** [comment]
Ah, while I googled around a bit I did not spot there to be conda upstream discussion about this.
Feel free to close this issue …

**Comment by daler** [comment]
OK. Closing for now, but if you notice any updates upstream please reopen.
