### ISSUE TITLE
how do I package an R package in condas r-channel?

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#534]
Hi Team Bioconda,

I'm packaging up bioconductor-phyloseq and running into some `R` dependencies that aren't in anaconda's R channel. Anyone know how/where to get recipes included there?

thanks,
zach cp

**Comment by johanneskoester** [comment]
You can make a pull-request to [conda/conda-recipes](https://github.com/conda/conda-recipes). Faster would be to include it into bioconda itself (we already have some). At some point, we could think about merging them back into conda/conda-recipes.

**Comment by zachcp** [comment]
thanks @johanneskoester, I will add the deps to this repo although its definitely a good idea to think about moving these 'upstream' at some point
