### ISSUE TITLE
Single installation script

### ISSUE THREAD

**Issue by karel-brinda** [bioconda/bioconda-recipes#5355]
**Suggestion:** I suggest that Bioconda have a single installation script that sets up everything. Such a script should install Bioconda (including Miniconda), set up all the channels, make all necessary configuration (e.g., modifying `$PATH` in `.bashrc`) and install all commands such as `conda skeleton`. If an old installation of Bioconda exists, it should be able to fix it (e.g., add missing channels) or at least provide the user with a list of problems. The script should be also runnable in a non-interactive mode.

**Reasoning:** In the [answer to one of my tickets](https://github.com/bioconda/bioconda-recipes/issues/4742#issuecomment-302864843), @druvus pointed out that I was doing a systematic error when installing Bioconda (I didn't add the other channels). Yesterday, @bgruening told me about another installation step that I wasn't aware of (`./simulate-travis.py`). Bioconda is evolving quickly and it's hard to keep track of all changes. I believe that the majority of Bioconda users would really appreciate such a script. For instance, [Brew](https://brew.sh/) would be a good example to follow. In my projects, I currently use [this script](https://github.com/karel-brinda/bin/blob/master/_install_miniconda).

@bioconda/core

**Comment by daler** [comment]
@karel-brinda  good timing ;) -- see https://github.com/bioconda/bioconda-recipes/pull/5227

**Comment by bgruening** [comment]
Done :)
