### ISSUE TITLE
Missing busco config file

### ISSUE THREAD

**Issue by mschatz** [bioconda/bioconda-recipes#5429]
The current busco recipe correctly installs the dependencies, but leaves out the required config.ini file. It is not terribly difficult to make, but would totally streamline the process to have one included. The default config file is available here:
https://gitlab.com/ezlab/busco/blob/master/config/config.ini.default

All of the required paths can be set to the miniconda bin directory:

```
# BUSCO specific configuration
# It overrides default values in code and dataset cfg, and is overridden by arguments in command line
# Uncomment lines when appropriate
[busco]
# Input file
;in = ./sample_data/target.fa
;# Run name, used in output files and folder
;;out = SAMPLE
;# Where to store the output directory
;;out_path = ./sample_data
;# Path to the BUSCO dataset
;;lineage_path = ./sample_data/example
;# Which mode to run (genome / protein / transcriptome)
;;mode = genome
;# How many threads to use for multithreaded steps
;;cpu = 1
;# Domain for augustus retraining, eukaryota or prokaryota
;# Do not change this unless you know exactly why !!!
;;domain = eukaryota
;# Force rewrite if files already exist (True/False)
;;force = False
;# Restart mode (True/False)
;;restart = False
;# Blast e-value
;;evalue = 1e-3
;# Species to use with augustus, for old datasets only
;;species = fly
;# Augustus extra parameters
;# Use single quotes, like this: '--param1=1 --param2=2'
;;augustus_parameters = ''
;# Tmp folder
;;tmp_path = ./tmp/
;# How many candidate regions (contigs, scaffolds) to consider for each BUSCO
;;limit = 3
;# Augustus long mode for retraining (True/False)
;;long = False
;# Quiet mode (True/False)
;;quiet = False
;# Debug logs (True/False), it needs Quiet to be False
;;debug = True
;# tar gzip output files (True/False)
;;gzip = False
;# Force single core for the tblastn step
;;blast_single_core = True

[tblastn]
# path to tblastn
path = /work-zfs/mschatz1/mschatz/build/miniconda/bin/

[makeblastdb]
# path to makeblastdb
path = /work-zfs/mschatz1/mschatz/build/miniconda/bin/

[augustus]
# path to augustus
path = /work-zfs/mschatz1/mschatz/build/miniconda/bin/

[etraining]
# path to augustus etraining
path = /work-zfs/mschatz1/mschatz/build/miniconda/bin/
;
;# path to augustus perl scripts, redeclare it for each new script
[gff2gbSmallDNA.pl]
path = /work-zfs/mschatz1/mschatz/build/miniconda/bin/
[new_species.pl]
path = /work-zfs/mschatz1/mschatz/build/miniconda/bin/
[optimize_augustus.pl]
path = /work-zfs/mschatz1/mschatz/build/miniconda/bin/

[hmmsearch]
# path to HMMsearch executable
path = /work-zfs/mschatz1/mschatz/build/miniconda/bin/

[Rscript]
# path to Rscript, if you wish to use the plot tool
path = /work-zfs/mschatz1/mschatz/build/miniconda/bin/
```

Thanks for your help!

Mike

**Comment by daler** [comment]
@mschatz since the bin dir will change depending on the environment, a single config file won't work.

For example `conda install busco` will put executables in the root env `/path/to/miniconda/bin` but another environment created with `conda create -n env2 busco` will put them in `/path/to/miniconda/envs/env2/bin`. The paths would need to be filled in at install-time, and I'm not sure there's a hook for that.

Do the paths have to be specified? If unspecified will they default to `$PATH`? If not maybe a config-generator script could be written and included in the busco recipe, and it could fill out the required paths with the results of its own directory (e.g. from `( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )`).

**Comment by mschatz** [comment]
@daler Unfortunately the full paths do have to be specified in the config file. I think the config-generator script is the best option if possible, otherwise it will require some surgery to the busco source. 

Thank you!

Mike

**Comment by daler** [comment]
@mschatz, I added a config-gen script in #5476 as well as updated BUSCO to 3.0.2. This is now merged into master, can you give this a try?

**Comment by mschatz** [comment]
I tried this in a separate environment, but the config.ini file is missing:

```
$ conda create -n env2 busco
$ source activate env2
(env2) $ run_busco
ERROR   No section [busco] found in
/work-zfs/mschatz1/mschatz/build/miniconda/envs/env2/bin/../config/config.ini.
Please make sure both the file and this section exist, see userguide.
```

There is a config directory there, just not the config.ini. Any ideas? Im a
total novice when it comes to debugging conda install issues, but if you
point me in the right direction can poke around

Thanks!

Mike

**Comment by daler** [comment]
@mschatz it's actually not being automatically run, since it's a bit more complicated than a simple `mv` or `cp` as recommended for a post-link script (https://conda.io/docs/building/build-scripts.html).

So for now, this is the way to do it, using the env var suggested by the busco docs:

```
$ conda create -n env2 busco
$ source activate env2
(env2) $ generate_busco_config.py > config.ini
(env2) $ BUSCO_CONFIG_FILE=config.ini run_busco
```

**Comment by mschatz** [comment]
Sorry for missing that. Since the build script creates and populates the
config directory, I dont see why we cant also add in the config file. Would
it be allowed if generate-busco-config.py was replaced by sed?

Mike

**Comment by daler** [comment]
No worries, there's not a good place to document it; it's easy to miss.

The build script currently does not populate the config dir; it doesn't really fit the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) we try to follow. Instead the build script puts the default config in a share directory and mucks around with symlinks to allow the config-gen script find the default config file.

I don't use busco, but it looks like the config file is really just used for configuring paths since most of the stuff near the top is commented out. So it shouldn't need to be touched during normal usage, is that correct? Let me play around with more symlinking stuff in bash, plus sed, to see if I can get it to work well as a post-link script.

**Comment by mschatz** [comment]
Thanks Ryan. Yes, the config file just sets a few paths and otherwise
shouldnt need to be touched, especially since most (or all) of the other
settings can be set on the command line. Unfortunately, the paths do need
to be set in this file. Thanks for checking on it

Mike

**Comment by daler** [comment]
@mschatz I think I got it working; the post-link approach ended up being simpler. Can you try:

```
$ conda create -n env3 busco
$ source activate env3
(env3) $ run_busco
```

I get the following indicating there's no input. But there's no error about the missing config file, so I'm assuming it's found:

```
ERROR   The parameter '--in' was not provided. Please add it in the config file or provide it through the command line
```

**Comment by mschatz** [comment]
Thanks Ryan! We are making progress, but when I go to run it, it throws an
error:

```
$ run_busco -i genome.fasta -l
~/build/miniconda/config/busco/eukaryota_odb9 -o busco -m geno
INFO ****************** Start a BUSCO 3.0.2 analysis, current time:
08/14/2017 17:10:50 ******************
INFO Configuration loaded from
/work-zfs/mschatz1/mschatz/build/miniconda/envs/busco/bin/../config/config.ini
INFO Init tools...
INFO Check dependencies...
ERROR Impossible to locate the required script gff2gbSmallDNA.pl. Check
that you properly declared the path to augustus scripts folder in your
config.ini file (do not include the script name in the path !)
ERROR BUSCO analysis failed !
ERROR Check the logs, read the user guide, if you still need technical
support, then please contact mailto:support@orthodb.org
```

The gff2gbSmallDNA.pl script comes with augustus, so I had to edit the
config.ini to point to the `.../miniconda/envs/busco/scripts` directory
instead of the `.../miniconda/envs/busco/bin` directory. This needed to be
changed for all 3 scripts in the augustus section of the config.ini file
(gff2gbSmallDNA.pl, new_species.pl, and optimize_augustus.pl)

I also had to add an environment variable:
```
export
AUGUSTUS_CONFIG_PATH=/work-zfs/mschatz1/mschatz/build/miniconda/env/busco/config
```

Sorry for missing these dependencies before - can you update them?

Thanks!

Mike

**Comment by daler** [comment]
Hmm, for AUGUSTUS_CONFIG_PATH we'll probably need something using https://conda.io/docs/using/envs.html#saved-environment-variables. I haven't used this before, will have to play around with it. In the meantime, I'll open another PR for the changes to the augustus scripts which is an easy fix, but figuring out a good way to test could be tricky.

**Comment by mschatz** [comment]
Thanks!

**Comment by cbrueffer** [comment]
This PR looks resolved, any reason to keep it open?

**Comment by bgruening** [comment]
No reason! Thanks for cleaning up @cbrueffer!

**Comment by pjm43** [comment]
I've install bioconda busco, but get this error from augustus:  error while loading shared libraries: libboost_iostreams.so.1.60.0: cannot open shared object file: No such file or directory.  It looks like libboost_iostreams.so.1.63.0 is in envs/busco/lib but for some reason augustus is not finding it.  Any help would be appreciated.

**Comment by bgruening** [comment]
@pjm43 which version of augustus do you get?

**Comment by pjm43** [comment]
According to the bioconda install it was 3.2.2-0:

Package plan for installation in environment /fslhome/pjm43/miniconda3/envs/busco:

The following NEW packages will be INSTALLED:

    augustus:           3.2.2-0            bioconda   
    bamtools:           2.4.0-3            bioconda   
    blast:              2.2.31-1           bioconda   
    boost:              1.63.0-py36_5      conda-forge
    boost-cpp:          1.63.0-2           conda-forge
    busco:              3.0.2-py36_2       bioconda   
    bzip2:              1.0.6-1            conda-forge
    ca-certificates:    2017.7.27.1-0      conda-forge
    cairo:              1.14.6-4           conda-forge
    certifi:            2017.7.27.1-py36_0 conda-forge
    fontconfig:         2.12.1-4           conda-forge
    freetype:           2.7-1              conda-forge
    gettext:            0.19.7-1           conda-forge
    glib:               2.51.4-0           conda-forge
    graphite2:          1.3.9-0            conda-forge
    harfbuzz:           1.4.3-0            conda-forge
    hmmer:              3.1b2-3            bioconda   
    icu:                58.1-1             conda-forge
    jpeg:               9b-0               conda-forge
    libffi:             3.2.1-3            conda-forge
    libgcc:             5.2.0-0                       
    libiconv:           1.14-4             conda-forge
    libpng:             1.6.28-0           conda-forge
    libtiff:            4.0.6-7            conda-forge
    libxml2:            2.9.5-0            conda-forge
    ncurses:            5.9-10             conda-forge
    openssl:            1.0.2l-0           conda-forge
    pango:              1.40.4-0           conda-forge
    pcre:               8.39-0             conda-forge
    perl-app-cpanminus: 1.7039-2           bioconda   
    perl-dbi:           1.636-0            bioconda   
    perl-threaded:      5.22.0-10          bioconda   
    perl-yaml:          1.18-0             bioconda   
    pip:                9.0.1-py36_0       conda-forge
    pixman:             0.34.0-0           conda-forge
    python:             3.6.2-0            conda-forge
    r:                  3.2.2-0                       
    r-base:             3.2.2-0                       
    r-boot:             1.3_17-r3.2.2_0a              
    r-class:            7.3_14-r3.2.2_0a              
    r-cluster:          2.0.3-r3.2.2_0a               
    r-codetools:        0.2_14-r3.2.2_0a              
    r-colorspace:       1.2_6-r3.2.2_0a               
    r-dichromat:        2.0_0-r3.2.2_2a               
    r-digest:           0.6.9-r3.2.2_0     bioconda   
    r-foreign:          0.8_66-r3.2.2_0a              
    r-ggplot2:          2.1.0-r3.2.2_0     bioconda   
    r-gtable:           0.1.2-r3.2.2_2a               
    r-kernsmooth:       2.23_15-r3.2.2_0a             
    r-labeling:         0.3-r3.2.2_1a                 
    r-lattice:          0.20_33-r3.2.2_0a             
    r-magrittr:         1.5-r3.2.2_0       bioconda   
    r-mass:             7.3_45-r3.2.2_0a              
    r-matrix:           1.2_2-r3.2.2_0a               
    r-mgcv:             1.8_9-r3.2.2_0a               
    r-munsell:          0.4.2-r3.2.2_1a               
    r-nlme:             3.1_122-r3.2.2_0a             
    r-nnet:             7.3_11-r3.2.2_0a              
    r-plyr:             1.8.3-r3.2.2_0a               
    r-rcolorbrewer:     1.1_2-r3.2.2_2a               
    r-rcpp:             0.12.2-r3.2.2_0a              
    r-recommended:      3.2.2-r3.2.2_0                
    r-reshape2:         1.4.1-r3.2.2_1a               
    r-rpart:            4.1_10-r3.2.2_0a              
    r-scales:           0.3.0-r3.2.2_0a               
    r-spatial:          7.3_11-r3.2.2_0a              
    r-stringi:          1.0_1-r3.2.2_0a               
    r-stringr:          1.0.0-r3.2.2_0a               
    r-survival:         2.38_3-r3.2.2_0a              
    readline:           6.2-0              conda-forge
    setuptools:         36.3.0-py36_0      conda-forge
    sqlite:             3.13.0-1           conda-forge
    tk:                 8.5.19-2           conda-forge
    wget:               1.18-0                        
    wheel:              0.30.0-py36_0      conda-forge
    xz:                 5.2.3-0            conda-forge
    zlib:               1.2.11-0           conda-forge

**Comment by pjm43** [comment]
I fixed the problem by installing bioconda augustus the same envirnoment.   Is there test data to check the install?

**Comment by PinocchioK** [comment]
Hello everybody,
Im trying to start Busco but im always not able to succes it because im receiving an error message
INFO	****************** Start a BUSCO 3.0.2 analysis, current time: 03/12/2018 14:30:57 ******************
INFO	Configuration loaded from /gpfs/scratch/cb/khaoula/Tools/busco/scripts/../config/config.ini
INFO	Init tools...
INFO	Check dependencies...
ERROR	"tblastn" is not accessible, please add or modify its path in the config file. Do not include the commmand in the path !
ERROR	BUSCO analysis failed !
ERROR	Check the logs, read the user guide, if you still need technical support, then please contact mailto:support@orthodb.org
ive tried with Nano to reconfigure the path but it still not working
Thank you
