### ISSUE TITLE
Remove mysql dependency from UCSC tools

### ISSUE THREAD

**Issue by chapmanb** [bioconda/bioconda-recipes#5430]
@daler @nsoranzo and @bioconda/core 
I've been looking at trying to reduce the size of the big containers I generate with bioconda installs and noticed that the large ~300Mb mysql dependency gets pulled in as part of ucsc tool installs. Would anyone object to removing this dependency from some tools? I don't need to tackle the whole ucsc tree unless y'all think it is worth it, but could remove it from the ucsc tools I use as a first pass:

https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L127

Thanks much for any thoughts and suggestions.

**Comment by jerowe** [comment]
I'm not really familiar with this one, but is mysql necessary for core functionality?

If its not I'm not opposed to getting rid of it, but maybe for cases like this we should have a package-extras package that contains nice to haves for a software. I think gatk is one I wanted to create an extras package for. Some of the steps need additional R packages I don't want to just throw in there.

**Comment by chapmanb** [comment]
Jillian -- you can use it in conjunction with some tools to query the UCSC mysql servers but I don't believe it's a core dependency of any tool. I agree this is a good case for an extras or bundle type packages where folks who might want all batteries included could use that. As a first pass, if no one objects I'll start removing it from the tools I mentioned and we can decide on a policy and extras type packages later.

**Comment by nsoranzo** [comment]
Would removing the `mysql` requirements work? It seems the mysqlclient library is compiled in the binaries, e.g.:
```
$ ldd ~/miniconda3/pkgs/ucsc-bedtobigbed-332-0/bin/bedToBigBed
```
contains `libmysqlclient.so.18` .

**Comment by chapmanb** [comment]
Nicola -- good catch, thank you. Apologies, I thought I'd removed all my mysql shared libraries when testing this. It looks like we'll need the mysql client library, but what do folks think about switching over to mysql-connector-c (https://github.com/conda-forge/mysql-connector-c-feedstock) which has `libmysqlclient.so.18` and is 37M instead of 300M?

**Comment by nsoranzo** [comment]
If that works, sure!

**Comment by daler** [comment]
When I first built all the ucsc tools, I was focused on just getting them built rather than slimming them down. I'm all for keeping them small where possible. I'm not sure the mysql is needed for many of the tools, I think the makefiles are just trying to be a one-size-fits all for everything in the source tree. It's possible the makefiles could be tweaked to let them compile without mysql.

**Comment by micknudsen** [comment]
The UCSC BigWigToWig does not work for me:

```
[michaelk@MOMA1 ~]$ conda create -n test ucsc-bigwigtowig --y
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/michaelk/anaconda3/envs/test:

The following NEW packages will be INSTALLED:

    ca-certificates:  2017.7.27.1-0    conda-forge
    libedit:          3.1.20170329-0   conda-forge
    libgcc:           7.2.0-h69d50b8_2
    libgcc-ng:        7.2.0-h7cc24e2_2
    libpng:           1.6.28-2         conda-forge
    libstdcxx-ng:     7.2.0-h7a57d05_2
    mysql:            5.7.20-0         conda-forge
    ncurses:          5.9-10           conda-forge
    openssl:          1.0.2l-0         conda-forge
    ucsc-bigwigtowig: 332-0            bioconda
    zlib:             1.2.11-0         conda-forge

#
# To activate this environment, use:
# > source activate test
#
# To deactivate an active environment, use:
# > source deactivate
#

[michaelk@MOMA1 ~]$ source activate test
(test) [michaelk@MOMA1 ~]$ bigWigToWig
bigWigToWig: error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory
```

**Comment by micknudsen** [comment]
Addendum: It works fine on Mac, but is fails on Linux.

**Comment by nsoranzo** [comment]
It looks like mysql-5.7.20 was added to conda-forge yesterday (previously there was only mysql-5.5.24 in `defaults`). The new version ships with `libmysqlclient.so.20` instead of `.18`, so we either need to rebuild all packages depending on mysql or pin it (or both).

**Comment by daler** [comment]
I'm currently using `bulk` to build all of the Bioconductor 3.6 packages. I can hold off on this for the moment to get this in. The code to do this across all tools is at https://github.com/bioconda/bioconda-recipes/tree/master/scripts/ucsc, but this will need updating and testing to use `mysql-connector-c`.

**Comment by nh13** [comment]
@chapmanb I ran into this today. I tested adding `mysql-connector-c` to a custom recipe for `ucsc-gtftogenepred` (gtfToGenePred) and it worked fine.  Without it, I get the "`libmysqlclient.so.18` not loaded error".

**Comment by lparsons** [comment]
Any updates on this? Fresh installs of various ucsc tools are failing with the `libmyslclient.so.18` error.

**Comment by daler** [comment]
Sorry, have been busy with the BioC 3.6 upgrades. I'm starting testing now and will update shortly.

**Comment by chapmanb** [comment]
Ryan -- wow, thanks for working on this. I'd been punting waiting for you to finish using the bullk queue for the Bioconductor improvements. I appreciate you tackling it.

**Comment by daler** [comment]
@chapmanb I think our limiting factor at the moment is OSX VMs on travis. I have local tests passing for most tools, and it's just a matter of how best to use the travis-ci resources.

I think for now I'll start with your list from https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L127 as a single PR to get them in sooner rather than later.:

```yaml
  - ucsc-bedtobigbed
  - ucsc-bigbedinfo
  - ucsc-bigbedsummary
  - ucsc-bigbedtobed
  - ucsc-bedgraphtobigwig
  - ucsc-bigwiginfo
  - ucsc-bigwigsummary
  - ucsc-bigwigtobedgraph
  - ucsc-bigwigtowig
  - ucsc-fatotwobit
  - ucsc-gtftogenepred
  - ucsc-liftover
  - ucsc-wigtobigwig
```

@lparsons, @nh13, @micknudsen, @nsoranzo any others you want to add to this short-list?

**Comment by lparsons** [comment]
Don't want to slow things up, but I'm also using:

```
    - ucsc-axtchain=332
    - ucsc-chainmergesort=332
    - ucsc-chainnet=332
    - ucsc-chainsort=332
    - ucsc-chainsplit=332
    - ucsc-fasplit=332
    - ucsc-liftup=324
    - ucsc-netchainsubset=324
    - ucsc-twobitinfo=332
    - blat=35
```

If it's going to take a lot longer though, I guess these could go in a second round.

**Comment by daler** [comment]
@lparsons I was going to update to latest (`==357`) first since they haven't been updated in a while. Looks like archives are available http://hgdownload.soe.ucsc.edu/admin/exe/userApps.archive/, so I'll add subdirs for each of these earlier versions and bump the build numbers for them.

**Comment by lparsons** [comment]
I'm find with bumping, but it would be nice the older versions were fixed, as they are broken now.

**Comment by bgruening** [comment]
This was done. Thanks a lot @daler!
