### ISSUE TITLE
Issue with Nanopolish

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#5474]
On linux (hdf 1.8.17). I tried using hdf5 from conda-forge (1.8.19) and i get the same.

```
nanopolish: error while loading shared libraries: libhdf5.so.101: cannot open shared object file: No such file or directory
```

Edit:
Looks like this is a problem on macOS as well:

```
dyld: Library not loaded: @rpath/libhdf5.101.dylib
  Referenced from: /Users/zach/anaconda3/envs/py2/bin/nanopolish
  Reason: image not found
Abort trap: 6
```

Any ideas for fixes?

**Comment by zachcp** [comment]
adding system hdf5 on macOS (`brew install hdf5`) fixes it. During builds it looks like `nanopolish` links libraries but those may be different from what supplied via conda.

looks like hdf5-1.10 is available but the default install is 1.8.18 why is that?

so it seems there are some conflicts with Anaconda base packages that are pinned to lower versions of hd5: pytables, blaze, bottleneck, h5py. Once those are removed 1.10.1 installs just fine.

**Comment by bgruening** [comment]
At the moment we recomment to pin hdf5 like this `- hdf5 1.8.18|1.8.18.*` Hope this helps!
https://github.com/conda-forge/conda-forge.github.io/blob/0661e2ecf4b213ddf36350ca100a5a820eb17eb7/scripts/pin_the_slow_way.py#L52

**Comment by zachcp** [comment]
@bgruening thanks. I just submitted a PR specifying the hdf5 dep. Can you use the same pin trick within `meta.yaml`?

**Comment by bgruening** [comment]
@zachcp I don't understand, sorry. You should use the above pinning in your meta.yml :)
