### ISSUE TITLE
data-heavy bioconductor packages

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#5483]
Now that we have more space provided by continuum, I was wondering if it would be appropriate to add bioconductor data packages. For example I'd like to add `bioconductor-chipqc` but it depends on these data packages:

  - `bioconductor-txdb.celegans.ucsc.ce6.ensgene`
  - `bioconductor-txdb.hsapiens.ucsc.hg18.knowngene`
  - `bioconductor-txdb.hsapiens.ucsc.hg38.knowngene`
  - `bioconductor-txdb.mmusculus.ucsc.mm10.knowngene`
  - `bioconductor-txdb.mmusculus.ucsc.mm9.knowngene`
  - `bioconductor-txdb.rnorvegicus.ucsc.rn4.ensgene`

As an example, [`TxDb.Hsapiens.UCSC.hg38.knownGene`](https://bioconductor.org/packages/release/data/annotation/html/TxDb.Hsapiens.UCSC.hg38.knownGene.html) is 31MB, so these would be roughly 200MB of space on the anaconda servers.

If it doesn't make sense to store those packages there, is there an alternative solution (other than just not having a package for `bioconductor-chipqc`)?

**Comment by bgruening** [comment]
We could create a dummy package that runs a normal R install in the post-install hook maybe?

**Comment by daler** [comment]
Hmm, that's a good idea. I'll see if I can get that to work.

**Comment by daler** [comment]
@bgruening @johanneskoester I have something working in #5485, but it's not optimal.

Quoting from https://conda.io/docs/building/build-scripts.html:

> We strongly recommend that post-link (and pre-unlink) scripts should:
> 
>    - be avoided whenever possible,
>    - not touch anything other than the files being installed,
>    - not write anything to stdout (or stderr), unless an error occurs,
>    - not depend on any installed (or to be installed) conda packages, and
>    - only depend on simple system tools such as rm, cp, mv, ln, and so on.
> 

Installing a bioconductor data package via a post-link script would require `wget` and `R`, so we wouldn't be following the last two recommendations.

Other issues I've discovered with this approach:

- The moment the URL changes, the package is broken. Maybe if we could pre-cache on Cargo Port we could use that URL in the post-link. A possible way to catch this kind of issue would be to set up a cron job to install these packages every night.
- Errors in post-link.sh are hard to debug, so that might open up some support headaches if folks can't figure out why the install is mysteriously failing.
- Since it's a post-link process, any env installing the package will be creating a copy of the data rather than simply linking it. Probably not a big deal if there's sufficient local storage.

Thoughts?

**Comment by bgruening** [comment]
@daler thanks for investigating!
I don't have a good answer/solution I'm afraid. I think its a terrible idea to ship data with a software package manager and I don't think it scales at all with BioConda as long as we have restricted storage capacity. In Galaxy we have, and I think for good reasons, separated data from software and this serves us well.

Maybe the solution is good communication and stating clearly in all these recipes that we know this is a hack but do to practical limitations this is the only way we can support this?

**Comment by daler** [comment]
@bgruening I agree about the separation of code and data, but we're stuck with Bioconductor who disagree ;).

How about this for a way forward:

- get the post-link working better to support multiple URLs (e.g., cargo-port URLs)
- finally move bioconductor-skeleton over to bioconda-utils
- in the new bioconductor-skeleton, enable it to create a data package with post-link rather than a standard recipe. This decision would initially be based on tarball file size, but if there is other metadata we could use from a package that indicates it's a data package, then that would be better
- lots of documentation -- I think it would be important to describe how the post-link.sh works, since implications affect users and not just devs

**Comment by Tomnl** [comment]
The post-link sounds like a good idea. For me the data packages in bioconductor are very useful both for unit-testing and for using in actual analysis.

So if we can get them in bioconda in any form it would be great!

**Comment by bgruening** [comment]
@daler if we agree to go with post-link scripts I think your outline makes a lot of sense.

**Comment by daler** [comment]
@bgruening I updated #5485 with an improved `post-link.sh` that handles multiple URLs and md5sum checks. I kept the urls and md5sum in the meta.yaml so that they are checked at build time, even though nothing happens with the downloaded tarballs at build time.

I figured it would be useful to work out the best we can do on the post-link side so we can make a good decision on whether or not we want to go that route. Please let me know if you see anything else that would be useful in that script. 

@bioconda/core and @bioconda/r -- any other opinions on how to handle data packages, specifically this post-link strategy vs a quota increase on the anaconda channel?

**Comment by johanneskoester** [comment]
@daler, thanks for spearheading this! I think it should be obligatory for a data package to use `noarch: generic`.

**Comment by bgruening** [comment]
@daler thanks for implementing my small idea! I will close this for now. Thanks!
