### ISSUE TITLE
Julia installs packages into ~/.julia

### ISSUE THREAD

**Issue by dfornika** [bioconda/bioconda-recipes#5488]
The julia package is configured to install julia packages into the user's `~/.julia` directory, outside the conda environment.

Another developer has solved this by creating a wrapper that sets `JULIA_PKGDIR` to `$JULIA_HOME/share/julia/site`:

https://github.com/tkf/conda-julia
https://anaconda.org/tkf/julia

**Comment by bgruening** [comment]
@dfornika please feel free to create a PR. This would be really great.

**Comment by dfornika** [comment]
Ok, thanks. I think it's ready to merge.

**Comment by cbrueffer** [comment]
This looks resolved, first with the addition of the wrapper, then with the removal of julia from bioconda.
