### ISSUE TITLE
Bioconductor ExperimentalData package

### ISSUE THREAD

**Issue by Tomnl** [bioconda/bioconda-recipes#5497]
Hi all, 

Not sure if this is the correct place to ask this but...

Just wondering if there was a procedure for building recipes for  [ExperimentalData packages from Bioconductor ](https://www.bioconductor.org/packages/3.3/data/experiment/)?

Nothing is mentioned in the [docs](https://bioconda.github.io/guidelines.html#r-bioconductor) and I am not sure the ['no-arch'](https://bioconda.github.io/guidelines.html#noarch-packages) is appropriate as the data will not be loaded in as an R package

**Note:**
I created a yaml of the biconductor ExperimentalData package [msPurityData](https://github.com/Tomnl/bioconda-recipes/blob/msPurity-recipe/recipes/bioconductor-mspuritydata/meta.yaml) locally and it seems to work OK. 

The msPurityData _tar.gz_ package is 193.2 MB

**Comment by daler** [comment]
@Tomnl we're actually trying to work out these details in #5483 if you want to join us over there.

**Comment by Tomnl** [comment]
Thanks @daler. OK glad that people are discussing this. 

I will close this issue as it is a duplicate
