### ISSUE TITLE
retiring outdated version of cobrapy

### ISSUE THREAD

**Issue by hredestig** [bioconda/bioconda-recipes#5509]
Hi, 
I'm the current maintainer of the [cobrapy package](github.com/opencobra/cobrapy). Since last year we build python wheels for mac/win/linux to support easy installation via pypi. Since this works well, there seems to be little added advantage of also having cobrapy on bioconda and I therefore would like to remove https://bioconda.github.io/recipes/cobra to avoid confusion about what latest version is. I read you [don't like to remove old packages](https://bioconda.github.io/faqs.html#what-s-the-lifecycle-of-a-bioconda-package), does that policy apply also in this scenario?

cheers, Henning

**Comment by bgruening** [comment]
Hi @hredestig!
Thanks for getting in contact! For reproducibility reasons we try hard to keep also old versions.
ping @raivivek and @cdiener which contributed to this recipe.

My personnel opinion is that conda is it's own package manager and if people prefer conda over wheels that is totally fine and they are in charge to update the packages, not you. It's like with Debian packages, no-one assumes they offer the latest versions but for convenience many people are using these packages.
That said we would love to have you on board and help us maintaining this package.

**Comment by hredestig** [comment]
Thanks for the feedback, that's understandable, let's keep the old version in bioconda then.

**Comment by druvus** [comment]
Hi @hredestig!
Nice to see you around here. I checked the latest version of cobrapy and it seems we could bump the package as soon `swiglpk` and `optlang` been added to conda-forge. I am happy to assist you to get the latest version into bioconda.

**Comment by hredestig** [comment]
Hi @druvus! 
Same to you. optlang is pure python and swiglpk also has wheels for all major platforms so quite pip installable; what is the advantage of also having it here?

**Comment by druvus** [comment]
@hredestig it took some time but cobrapy is now bumped to the latest version at bioconda. 

The advantage to have it here is that users doesn't need to care about installing swig and glpk manually. Not a major in this case when it just a couple of non-python dependencies but for larger pipelines it is very helpful.
