### ISSUE TITLE
blast remote fails because GNUTLS is missing

### ISSUE THREAD

**Issue by Cashalow** [bioconda/bioconda-recipes#5539]
Hello,

Using blast 2.6 I am trying to send a remote request for blasting. However to do so blast need the libgnutls that are not available on conda-forge. Thus blastn -remote -db nr fails with the current version in bioconda.

I have tried adding the dependencies tlslite and openssl to see if they could provide the missing libraries but the blast remote failed each time. 

Does someone have an idea on which depencies to add for fixing this problem ?

Thank you very much,

**Comment by Cashalow** [comment]
(for the record, working on it https://github.com/conda-forge/staged-recipes/pull/3762)

**Comment by epruesse** [comment]
@Cashalow successfully added gnutls to conda-forge. So this is now only pending #6073

**Comment by Cashalow** [comment]
Done ! Closing :)
