### ISSUE TITLE
Automating updates of bioconda recipes

### ISSUE THREAD

**Issue by jdidion** [bioconda/bioconda-recipes#5554]
@daler and I discussed this at the NCBI hackathon this week. The goal is to create a general framework for automatically updating bioconda recipes for each new release of a project. Below I describe a python package that implements this functionality.

# Autoupdate python package

This requires the user to have a GitHub account and generate an API key. The package runs the following four operations:

1. The first time a user runs the package is run on a new machine, it forks bioconda/bioconda-recipes.
2. Although usually not necessary, it's probably a good idea to bring the fork up to HEAD. This and all other GitHub operations are done with the API via pygithub:
    * Create PR on fork, base: <user>/bioconda-recipes, head: bioconda/bioconda-recipes
    * merge PR
3. Within a user-configurable directory that defaults to ~/.bioconda:
    * Clone recipe locally with -n:
        ```
        git clone -n https://github.com/<user>/bioconda-recipes.git --depth 1
        cd bioconda-recipes
        git checkout HEAD recipes/<tool name>/meta.yaml
        ```
    * Edit the file (using regexps or by parsing, editing, and rewriting yaml) to (at a minimum) update the version and the source URL and MD5
    * Commit and Push
4. Create PR on bioconda, base: bioconda/bioconda-recipes, head: <user>/bioconda-recipes

The main benefit of this approach is flexibility - a user can run it locally, set it up for Travis to run it automatically following successful build of a release, or it could be run on a server triggered by an API call.

This package could be further extended such that when run by a user that has write access to the bioconda-recipes repo, it just checks out the whole repo rather than operating selectively on individual recipes, and modifications are automatically committed, which frees admins from having to manually approve lots of PR merges.

With that extension in place, this package could be run nightly as a cron job rather than requiring every package maintainer to run the package manually, or to call an API on a public-facing server that would have to be hosted somewhere. The challenge with this model is that packages are hosted different places that make it more or less easy to discover whether a new version has been released. With GitHub or PyPI it's easy, as they provide APIs. On the other hand, if someone is hosting releases on their own website, there's no general method for querying whether there's a release more recent than the one currently in the recipe.

The implementation of this package is pretty straight-forward. To me, the best strategy is starting out requiring package devs to manually execute the package or set up Travis to do it. We could provide examples of both. Long-term, it needs to be decided whether a push (API-based) or pull (cron-based) approach is best for making automated recipe updates more widely accessible.

**Comment by bgruening** [comment]
@jdidion can it be that something is missing from the text?
If you want to work on this please have a look at: https://github.com/ContinuumIO/pypi-conda-builds

**Comment by daler** [comment]
@bgruening the orig post has been updated from what was sent in the notification email from github, hopefully that addresses the missing text issue. And thanks for the repo link, looks very useful.

**Comment by bgruening** [comment]
Thanks to @epruesse we now have a bot that is doing exactly that :)

Thanks Elmar!
