### ISSUE TITLE
The Antismash Build is Maxing out the Build Machine's Available Space

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#5630]
Hi Team Bioconda,

My build of the [antismash](https://github.com/bioconda/bioconda-recipes/pull/5629) recipe is passing on [osx](https://travis-ci.org/bioconda/bioconda-recipes/jobs/266398943) but failing on [linux](https://travis-ci.org/bioconda/bioconda-recipes/jobs/266398944).  This recipe has a LOT of dependencies and is a rather big download which causes the build machine to fail (see error below or in travis log.)

Can I request an increase of the size of the build machine for this package. It would be VERY useful to have this on Bioconda and would be updated rather infrequently.

Thanks,
zach cp

cc:  @bioconda/core 

```
[Aug 20 00:24:05] WARN Local execution errorred with error [API error (500): {"message":"Error processing tar file(exit status 1): write /usr/local/lib/python2.7/site-packages/PyQt5/QtGui.so: no space left on device"}

], retrying with remote execution

[Aug 20 00:24:05] DEBU Creating container [step-d01f63c216]
```

```
Done. Your build exited with 1.

grep: write error: No space left on device
```

**Comment by zachcp** [comment]
Thanks @daler,

what would you recommend as the best way forward? Is there a way to make an appeal to Travis? I just double checked the dependencies and they are indeed required. Do we need to download all of the runtime dependencies if they are not needed at buildtime? 

Thanks, 
zach cp

**Comment by bgruening** [comment]
@zachcp AntiSmash is downloading a huge chunk of reference data. This should not end up in the package I guess. Instead you could use the actiavte script to download the reference data during installation time. Would this work for you?

**Comment by zachcp** [comment]
@bgruening  thanks for looking at this.

The bulk of the antismash data is already downloaded by a post-install script which downloads a  ~4Gb and  an ~1GB file.  This should not be happening in the install (I don't think it is.)   However, the package is still big install at ~100MB much of which is domain-specific data like HMM models for particular protein domains. Although it may be on the docket to separate these out, it is not currently feasible to do so. 

Can you tell if Travis is failing before even beginning the download? I think the large number of dependencies kills the process before the download of the package downloads, in which case reducing the package size will still result in a killed build.

zach cp

**Comment by bgruening** [comment]
I can not see the activate.sh script in your PR. However, the antismash installation is already 450MB without the dependencies ...

Can I misuse your PR and try to reduce the image size on travis?

**Comment by zachcp** [comment]
the post install script is actually just a python script "antismash/download_databases.py". It would need to be initiated by the user. 

>However, the antismash installation is already 450MB without the dependencies ...
Whoa. That seems a bit high, even after unzip - but I haven't properly looked.

>Can I misuse your PR and try to reduce the image size on travis?
by all means :)

**Comment by zachcp** [comment]
fixed.
