### ISSUE TITLE
/etc/machine-id not found

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#5839]
Hi,
I used `conda install dammit` and got the following output:

```
dbus post-link :: /etc/machine-id not found ..
dbus post-link :: .. using /proc/sys/kernel/random/boot_id
```
Is it a problem?

Thank you in advance

Michal

**Comment by daler** [comment]
This is from the `dbus` package's post-link script; it can be ignored. https://github.com/conda/conda-recipes/blob/master/dbus/post-link.sh.Linux
