### ISSUE TITLE
Jaffa recipes not work with the test data

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [bioconda/bioconda-recipes#5874]
I use jaffa version 1.8 and the last version. However I have problems when I try to complete the demo using demo data.
On stage filter_transcritps I have the fail message

`error in evaluetinf the argument 'args'  in selecting  method for  function do.call`

**Comment by bgruening** [comment]
@bioinfo-dirty-jobs not sure if this is a bioconda issue. Do you have reported this upstream?

**Comment by bgruening** [comment]
@bioinfo-dirty-jobs let us know if we can help here in any way.
