### ISSUE TITLE
kraken name clash

### ISSUE THREAD

**Issue by jenzopr** [bioconda/bioconda-recipes#5921]
Dear all,

I was about to contribute a recipe for the kraken tool set from the Enright group at EBI (http://www.ebi.ac.uk/research/enright/software/kraken). 
Since there is already a recipe called `kraken` in bioconda, I'll need to find a new name for the EBI kraken. Would `kraken-ebi` or any derivatives like `ebi-kraken` be fine? 

Thanks a lot for a short note!
Jens

**Comment by jenzopr** [comment]
I just saw that the tools reaper + tally + minion come with a different version number than seqimp. I will create two recipes, one for reaper + tally + minion and one for seqimp. The name clash shouldn't be an issue then.

**Comment by joey0214** [comment]
Hi, Jens, are you finished on this? I'm looking for the possibility to contribute to this. Looking forward to your comment. :D

**Comment by jenzopr** [comment]
Hi! No, I didn't finish this, but in the meantime there has been a PR (#7021) that just called it `reaper`. I guess its too late to have a better name ;)
