### ISSUE TITLE
gnuplot fails to start due to missing or wrong libraries

### ISSUE THREAD

**Issue by nlosacco** [bioconda/bioconda-recipes#5922]
If I try and run gnu plot on my OSX 10.12 I get this:

```
dyld: Library not loaded: @rpath/libgd.3.dylib
  Referenced from: /anaconda/bin/gnuplot
  Reason: image not found
Abort trap: 6
```
 I could not find any package with libgd version 3 on anaconda cloud.
If I pick the library from another application (say, Inkscape), then I get:

```

dyld: Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /anaconda/bin/gnuplot
  Reason: Incompatible library version: gnuplot requires version 45.0.0 or later, but libpng16.16.dylib provides version 44.0.0
Abort trap: 6
```

**Comment by Cashalow** [comment]
Gnuplot has recently been removed from bioconda so that the reference can be in conda-forge (https://github.com/bioconda/bioconda-recipes/pull/5106). Maybe something to look into ? Does it work when using conda-forge version ?

**Comment by nlosacco** [comment]
Hi,

the condo-forge version has the same problem, I file an issue to them as
well.

Thank you,

N


2017-09-01 13:51 GMT+02:00 Sacha Laurent <notifications@github.com>:

**Comment by croth1** [comment]
Since I will not maintain bioconda's gnuplot anymore - let's discuss this issue here: https://github.com/conda-forge/gnuplot-feedstock/issues/6.
