### ISSUE TITLE
Recipe reviews

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#595]
We are now already a quite huge team, and recipes sometimes appear faster than our current reviewing approach is able to handle. Packaging is not always straightforward, and sometimes there are different (more of less Bioconda-like) approaches to package a software.

This is why I want to propose a new algorithm for merging into master:
- Anybody is allowed to update an existing recipe to a new version and merge this into master (after tests have passed).
- For new recipes, a member of a yet to define core team needs to approve.

This way, we avoid recipes that do not follow e.g. the [FSH](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard), lack certain sections like tests or a description and any other issues.

Technically, we can put this guidelines into the CONTRIBUTING.md, such that they will show up when a pull request is created.

What do you think?

**Comment by bgruening** [comment]
+1 for `CONTRIBUTING.md` and defined guidelines - this will help a lot.

Also related to this what was the original idea behind the branch-protection? This seems to be a huge resource hog. You are more or less battling with other PR to get yours in, which ends up with several merges if you have a big PR or a program with large compile/test times. I can imagine this get's more annoying with more and more contributors.

I would propose that no one is allowed to directly push to this repository. We deactivate force pushes to master and only PR from remotes are allowed + your two proposed rules:

  * PR for an existing recipe to a new version can be merged into master (after tests have passed) without a second +1
  *  For new recipes, a member of a yet to define core team needs to approve it with a +1

**Comment by johanneskoester** [comment]
Force pushes are not causing the issue you see with merging. It is just another pull request being regularly merged that causes your PR to become outdated (see [here](https://github.com/blog/2051-protected-branches-and-required-status-checks), the branch must be up-to-date before merging). I don't think there is a technical solution that avoids this. Best way would be to make our tests much faster (and there is potential, because strangely several recipes are built over and over again).

**Comment by bgruening** [comment]
I haven't said that force-pushes resulting in this behaviour. It's just good to have to not loose commits accidentally :)

**Comment by johanneskoester** [comment]
You are right, sorry :-). Any further comments on this? I would propose to take the top 4 contributors as the core team: @daler @chapmanb, @tomkinsc and @johanneskoester. We were there from the start, and have relatively constant pull requests. That suggests that we should be responsive and experienced enough to handle the additional duties. Do you agree?

**Comment by chapmanb** [comment]
What do you think about having an honor system where contributors flag recipes they'd like review on? I worry about bottlenecking recipe updates. I found this to be a problem with homebrew-science where the hard working core team would get overwhelmed and end up missing simple merges for multiple days. If we had a process suggesting asking for feedback on first recipes or anything potentially different, I think most folks would follow this without needing to enforce anything. Then anyone could also feel empowered to review recipes, making it more community based.

**Comment by kyleabeauchamp** [comment]
I do have some doubts about a completely honor based system.  IMHO, it makes more sense to involve a slightly larger team (~8?) with `merge` access but still require review of all recipes.  

I'm less worried about turnaround time than I am about subtle bugs that break peoples results.

**Comment by johanneskoester** [comment]
So, I thought about only requiring reviews for new recipes. Simple updates won't need any review in my opinion. However, even this certainly slows down the process...

**Comment by kyleabeauchamp** [comment]
I also realize that the people with merge access don't necessarily need to be the people who are "trusted reviewers".  For example, you could keep the 4 people listed above as having the abillity to merge, but I imagine there are 10 or so people who might be competent to sign off on the +1 to merge.

**Comment by daler** [comment]
I like Kyle's reviewers-at-large idea where any one of 10-ish experienced folks can +1 a new recipe. "Core contributors" with merge access can then trust that +1 and/or review independently before merging. Hopefully spreading the review work around would reduce the burden Brad warns about.

For recipe updates, I think I'd prefer a review if the contents of the test have changed.

I think clear documentation and examples (#455), especially on what constitutes an acceptable test, would go a long way in making the review process easier for everyone -- contributors and reviewers.

As a side note, there are webhooks https://developer.github.com/webhooks that might be able to check and perhaps flag new contributor PRs. I haven't played around with them yet though.

**Comment by tomkinsc** [comment]
Happy to help any way I can. +1 to Kyle's plan, though perhaps we should also grant merge rights once contributors have successfully added a certain number of recipes. Recipe templates in the docs would be great ("Example recipe for a {python module, R package, java tool, ...}"), along with explicit suggestions of where to place things to comply with the filesystem hierarchy.

**Comment by bgruening** [comment]
This is related: https://github.com/bioconda/bioconda-recipes/issues/2327
Can we agree on a strategy before the hackathon?

**Comment by bgruening** [comment]
We have some Guidelines and we have coregroups that are supposed to help reviewing for special areas, like R, Perl ... should we close this issue now? I feel like we need to make these Guidelines more clear and get more people into the core team, but this is probably a different issue.

**Comment by daler** [comment]
Things seem to have been fine over the year since this was opened, except for @bgruening handling the bulk of the review work. We could definitely use some more folks on the core team.

**Comment by johanneskoester** [comment]
Also, a good linting should be top priority, since it can take away a lot of work from the people who have to review.

**Comment by bgruening** [comment]
True! xref for a few ideas: https://github.com/bioconda/bioconda-recipes/issues/1860

**Comment by epruesse** [comment]
outdated - may have to revisit at later time though
