### ISSUE TITLE
update bowtie version from 1.2 to 1.2.1.1

### ISSUE THREAD

**Issue by alexbaras** [bioconda/bioconda-recipes#5950]
This needs to be updated to match github version 1.2.1.1

https://github.com/BenLangmead/bowtie/releases

There is a major bug that was fixed regarding multithreading for fasta (not fastq) input

Thanks

**Comment by bgruening** [comment]
A start: https://github.com/bioconda/bioconda-recipes/pull/5951

**Comment by bgruening** [comment]
Fixed! Thanks for reporting!
