### ISSUE TITLE
Migrate and update tesseract to conda-forge and 3.05.1

### ISSUE THREAD

**Issue by cailiang9** [bioconda/bioconda-recipes#5971]

**Comment by bgruening** [comment]
@cailiang9 which software are you referring to :)
Also you can update the software on you own if you like, we will help you and review your update pull request.

**Comment by druvus** [comment]
@cailiang9 I guess you are referring to tesseract. It is an OCR software so it should as a non-bioinformatics software be migrated to conda-forge.

**Comment by bgruening** [comment]
renamed the issue and added hackathon label

**Comment by bgruening** [comment]
It is now in conda-forge!
