### ISSUE TITLE
Missing biocontainer for UROPA

### ISSUE THREAD

**Issue by jenzopr** [bioconda/bioconda-recipes#5986]
Dear all,

after the PR #5958 was merged I could not use the `docker pull quay.io/biocontainers/uropa` command because no repository exists. I tried to understand how bioconda and biocontainers relate, and as I understand from #2297 every bioconda recipe should result in a container on quay.io. The biocontainer registry UI shows an entry for uropa, pulling is, however, not possible.
I thought to investigate a bit and noticed that the travis-ci build for bioconda failed upon the merge (Build #22074). Could this have caused the missing container?

Best,
Jens

**Comment by bgruening** [comment]
@jenzopr can you check again the repository should exist.

**Comment by jenzopr** [comment]
Now it does! Thanks a lot. May I ask what the issue was?

**Comment by bgruening** [comment]
Slow and lazy @bgruening :)
There is a slight delay, due to the quay.io API and I need to trigger a "make public"...

**Comment by jenzopr** [comment]
Oh I see! Thanks a lot for your help 👍
