### ISSUE TITLE
Question regarding use of git_url

### ISSUE THREAD

**Issue by ernfrid** [bioconda/bioconda-recipes#5990]
I recently noticed that a recipe exists for extract-sv-reads (thanks @chapmanb!) and works well, but the binary that is created during the building of the recipe contains an incorrect version.

The reason for this is that the existing build system for extract-sv-reads derives and embeds version information based on the state of git at compile time. I understand that the bioconda guidelines indicate that a tarball is preferred, but I thought I'd ask if an exception might be made in this case and the git_url and git_rev mechanism utilized instead?

If built with git (and some jiggering to move build.sh out of the source directory) the version will report as so:
```
$ extract-sv-reads -v
version: 1.1.2 (commit 9bb74fc)
```

The current recipe produces a binary that reports its version as so
```
$ extract-sv-reads -v
version: unstable (commit nogit)
```

Thank you for your consideration.

**Comment by chapmanb** [comment]
Dave -- thanks for the heads up on the version issue. No problem, I'll swap over to use git urls for this and bump to the 1.1.2 release. Thanks for the great tool.

**Comment by ernfrid** [comment]
Wow. Thanks Brad and thank you for packaging it up.

In addition to switching to using git_rev and git_url, the other thing I found I had to do was to move the conda-build.sh file that gets dropped into the source. If this isn't moved then the build system detects that the repo isn't clean and flags it as such.

I've been unable to find a less dumb way of doing this, but this is what I had currently
```
diff --git a/recipes/extract-sv-reads/build.sh b/recipes/extract-sv-reads/build.sh
index c79a8be..fd62d06 100644
--- a/recipes/extract-sv-reads/build.sh
+++ b/recipes/extract-sv-reads/build.sh
@@ -1,6 +1,7 @@
 #!/bin/bash
 mkdir -p build
 cd build
+mv ../conda_build.sh .
 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX ..
 make
 make install```

**Comment by ernfrid** [comment]
Thanks again Brad!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chapmanb** [comment]
Thanks much for the heads up and all the tips on building with a clean version. The new package should be available now -- let us know if you spot any problems.
