### ISSUE TITLE
Error with Samtools recipe

### ISSUE THREAD

**Issue by jpuritz** [bioconda/bioconda-recipes#6028]
`conda create -n new_samtools samtools`
```
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/j.puritz/miniconda3/envs/new_samtools:

The following NEW packages will be INSTALLED:

    bzip2:    1.0.6-3          
    curl:     7.54.1-0         
    krb5:     1.13.2-0         
    libgcc:   5.2.0-0          
    libssh2:  1.8.0-0          
    openssl:  1.0.2l-0         
    samtools: 1.5-2    bioconda
    xz:       5.2.3-0          
    zlib:     1.2.8-3          

Proceed ([y]/n)? y

#
# To activate this environment, use:
# > source activate new_samtools
#
# To deactivate an active environment, use:
# > source deactivate
#
```
`source activate new_samtools`
`samtools`
```
samtools: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by daler** [comment]
@jpuritz this can happen if your channels are not in the correct order. Does using the order from https://bioconda.github.io/#set-up-channels solve the problem?

**Comment by jpuritz** [comment]
I actually just figured that out as well.  I’ll close the issue.

-- 
Jon Puritz, PhD

Assistant Professor
Department of Biological Sciences
University of Rhode Island
120 Flagg Road, Kingston, RI 02881

Webpage: MarineEvoEco.com

Cell: 401-338-8739

"The most valuable of all talents is that of never using two words when one
will do.” -Thomas Jefferson


On September 14, 2017 at 10:13:38 AM, Ryan Dale (notifications@github.com)
wrote:

@jpuritz <https://github.com/jpuritz> this can happen if your channels are
not in the correct order. Does using the order from
https://bioconda.github.io/#set-up-channels solve the problem?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bioconda/bioconda-recipes/issues/6028#issuecomment-329495192>,
or mute the thread

**Comment by jpuritz** [comment]
That is the solution

**Comment by crashfrog** [comment]
Hi, re-open this please, libbz2.so.1.0 isn't distributed by system packages of bzip2 (you should be linking libbz2.so.1.0.6 or libbz2.so.1 instead.)

**Comment by crashfrog** [comment]
We've already reconfigured our channel order, but it's still pulling a bzip2 package that doesn't include libbz2so.1.0.

**Comment by mbargull** [comment]
Can you show the outputs of
- `conda info`
- `conda config --show-sources`
- `conda create -n new_samtools samtools --dry-run`

**Comment by crashfrog** [comment]
`
     active environment : None
       user config file : /home/galaxy/.condarc
 populated config files : /home/galaxy/.condarc
          conda version : 4.4.7
    conda-build version : not installed
         python version : 3.5.2.final.0
       base environment : /home/galaxy/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/iuc/linux-64
                          https://conda.anaconda.org/iuc/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/galaxy/miniconda3/pkgs
                          /home/galaxy/.conda/pkgs
       envs directories : /home/galaxy/miniconda3/envs
                          /home/galaxy/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.5.2 Linux/3.10.0-327.36.1.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 33264:33264
             netrc file : None
           offline mode : False`

`==> /home/galaxy/.condarc <==
channels:
  - iuc
  - conda-forge
  - bioconda
  - defaults`

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.4.7
  latest version: 4.4.8

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/galaxy/miniconda3/envs/new_bcftools

  added / updated specs: 
    - bcftools


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    krb5-1.14.2                |                0         4.0 MB  conda-forge
    bcftools-1.6               |                0         2.6 MB  bioconda
    zlib-1.2.11                |                0          93 KB  conda-forge
    libssh2-1.8.0              |                2         243 KB  conda-forge
    curl-7.55.1                |                0         772 KB  conda-forge
    xz-5.2.3                   |                0         854 KB  conda-forge
    openssl-1.0.2n             |                0         3.5 MB  conda-forge
    ca-certificates-2017.11.5  |                0         145 KB  conda-forge
    bzip2-1.0.6                |                1         310 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        12.5 MB

The following NEW packages will be INSTALLED:

    bcftools:        1.6-0            bioconda   
    bzip2:           1.0.6-1          conda-forge
    ca-certificates: 2017.11.5-0      conda-forge
    curl:            7.55.1-0         conda-forge
    krb5:            1.14.2-0         conda-forge
    libgcc:          7.2.0-h69d50b8_2            
    libgcc-ng:       7.2.0-h7cc24e2_2            
    libssh2:         1.8.0-2          conda-forge
    libstdcxx-ng:    7.2.0-h7a57d05_2            
    openssl:         1.0.2n-0         conda-forge
    xz:              5.2.3-0          conda-forge
    zlib:            1.2.11-0         conda-forge

We're seeing the error now in bcftools execution, so I've run ```conda create``` on that package, instead. But ```bcftools``` jobs continue to come back with

`Fatal error: Exit code 100 ()
bcftools: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
Error occured while running:
    bcftools merge -o snpma.vcf --merge all --info-rules NS:sum tmp.vcf.5rv2_x2o/*.gz`

**Comment by crashfrog** [comment]
I've found this environment and activated it, and I can see there's still no libbz2.so.1.0, by running ```ldconfig -p | grep libbz2.so```:

	libbz2.so.1 (libc6,x86-64) => /lib64/libbz2.so.1
	libbz2.so (libc6,x86-64) => /lib64/libbz2.so

**Comment by crashfrog** [comment]
I think ```conda-forge``` might be the culprit, here; as I read this build script:

https://github.com/conda-forge/bzip2-feedstock/blob/master/recipe/build.sh

it doesn't create the correct shared object reference.

Thanks for your attention @mbargull ! You set me on the right path, I think.

**Comment by mbargull** [comment]
I can't reproduce your error, sorry. The `bzip2` recipe for Linux on `conda-forge` is fine, though. What you see there is just that an additional link is created. The `libbz2.so.1` link is already created by `make ...`.
Running
```
conda create -nnew_bcftools bcftools -c iuc -c conda-forge -c bioconda -c defaults
```
I get
```
 ls -la new_bcftools/lib/libbz2.*
-rw-rw-r-- 2 maba maba 332538 Mar 31  2017 new_bcftools/lib/libbz2.a
lrwxrwxrwx 1 maba maba     15 Jan 30 22:52 new_bcftools/lib/libbz2.so -> libbz2.so.1.0.6
lrwxrwxrwx 1 maba maba     15 Jan 30 22:52 new_bcftools/lib/libbz2.so.1.0 -> libbz2.so.1.0.6
-rwxrwxr-x 2 maba maba 213080 Mar 31  2017 new_bcftools/lib/libbz2.so.1.0.6
```
