### ISSUE TITLE
pinning to CONDA_ZLIB

### ISSUE THREAD

**Issue by notestaff** [bioconda/bioconda-recipes#6034]
@bgruening zlib in most recipes is not pinned to CONDA_ZLIB.  Should it be?   Should there also be CONDA_BZIP2?

**Comment by bgruening** [comment]
Yes, it should be as well as all others from here: https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py#L39

I'm hesitated to rebuild all packages now, because all this will be solved with conda-build3 which we will use hopfeully by the end of this year.

**Comment by notestaff** [comment]
Makes sense.
The page https://bioconda.github.io/guidelines.html points to salmon recipe as example of using CONDA_BOOST.  But that recipe actually pins to Boost 1.63 while CONDA_BOOST is now 1.64 .

**Comment by bgruening** [comment]
:( pretty bad. The was all changed in the recent updates. We should link to an other example, I assume there were good reasons to pin against an old build.

**Comment by bgruening** [comment]
@notestaff can you update the docs?

**Comment by notestaff** [comment]
@bgruening in https://github.com/bioconda/bioconda.github.io do I edit _sources and then use sphinx to generate the html?  sphinx complains about missing conf.py .

**Comment by daler** [comment]
@notestaff docs are actually edited in https://github.com/bioconda/bioconda-utils/tree/master/docs/source, and they are built and deployed when bioconda-utils passes on the master branch. So a PR on bioconda-utils with any updates should do the trick.

**Comment by bgruening** [comment]
I think this is fixed now. We need to bump the CONDA_ZLIB dependency at some point as we diverge currently from conda-forge, but this is an other issue.

Thanks @notestaff for reporting!
