### ISSUE TITLE
gatk-register: error with gatk version check due to path change

### ISSUE THREAD

**Issue by khourhin** [bioconda/bioconda-recipes#6038]
Hi,

I just tried to install GATK 3.8 using this method:

`conda install gatk`

Downloaded GATK from https://software.broadinstitute.org/gatk/download/

`gatk-register ~/Downloads/GenomeAnalysisTK-3.8-0.tar.bz2`

Returns:

> ENV_PREFIX /home/ekornobis/programs/anaconda3
> Processing GenomeAnalysisTK-3.8-0.tar.bz2 as *.tar.bz2
> Extracting GenomeAnalysisTK-3.8-0.tar.bz2
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
> tar: Ignoring unknown extended header keyword 'SCHILY.dev'
> tar: Ignoring unknown extended header keyword 'SCHILY.ino'
> tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
> GenomeAnalysisTK-3.8-0-ge9d806836/
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
> tar: Ignoring unknown extended header keyword 'SCHILY.dev'
> tar: Ignoring unknown extended header keyword 'SCHILY.ino'
> tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
> GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar
> Error: Unable to access jarfile ./GenomeAnalysisTK.jar
> The version of the jar specified, , does not match the version expected by conda: 3.8

After checking `gatk-register`, the problem seems to lie in the path of the extracted tar. After execution of `gatk-register ~/Downloads/GenomeAnalysisTK-3.8-0.tar.bz2`, the jar file is in:

/tmp/gatk/GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar

But apparently `gatk-register` looks for it in /tmp/gatk/GenomeAnalysisTK.jar i.e

`gatk-register` L89-97

```
cd /tmp/gatk
tar -vxjf $abspath_tarball   
if [[ "$2" != "--noversioncheck" ]]; then
check_version ./GenomeAnalysisTK.jar
fi
echo "Moving $(basename $abspath_tarball) to $ENV_PREFIX/opt/$PKG_NAME-$PKG_VERSION"
mv ./GenomeAnalysisTK.jar $ENV_PREFIX/opt/$PKG_NAME-$PKG_VERSION/
```
I don't know how to properly solve this, so I just mention it for now.

Cheers

@chapmanb @tomkinsc

**Comment by chapmanb** [comment]
Thanks much for letting us know about the problem and sorry for not catching the directory structure change. I checked in a fix to the registration script that should handle either this case or the previous tarballs. If reinstall and re-run gatk-register:
```
conda install -c conda-forge -c bioconda gatk
gatk-register /path/to/your/tarball
```
all should hopefully work cleanly. Thanks again.

**Comment by khourhin** [comment]
Happy to contribute how I can ! Thanks for the fix, everything's running fine now for me:
`conda install gatk`

`gatk-register ~/Downloads/GenomeAnalysisTK-3.8-0.tar.bz2`

> ENV_PREFIX /home/ekornobis/programs/anaconda3
> Processing GenomeAnalysisTK-3.8-0.tar.bz2 as *.tar.bz2
> Extracting GenomeAnalysisTK-3.8-0.tar.bz2
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
> tar: Ignoring unknown extended header keyword 'SCHILY.dev'
> tar: Ignoring unknown extended header keyword 'SCHILY.ino'
> tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
> GenomeAnalysisTK-3.8-0-ge9d806836/
> tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
> tar: Ignoring unknown extended header keyword 'SCHILY.dev'
> tar: Ignoring unknown extended header keyword 'SCHILY.ino'
> tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
> GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar
> GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar
> jar file specified matches expected version
> Moving GenomeAnalysisTK-3.8-0.tar.bz2 to /home/ekornobis/programs/anaconda3/opt/gatk-3.8

Thanks !

**Comment by ksw9** [comment]
Hi,
I'm having some trouble with this and any help would be greatly appreciated!
I tried to install gatk with
conda install -c conda-forge -c bioconda gatk
gatk-register <path>/gatk-3.8-py36_2.tar.bz2 

And I get the following errors:
Error: Unable to access jarfile ./GenomeAnalysisTK.jar
The version of the jar specified, , does not match the version expected by conda: 3.8

Thanks for your help!

**Comment by khourhin** [comment]
Are you sure about your path " /gatk-3.8-py36_2.tar.bz2 " ?
Sounds strange to me that the tar file in directly under the root.

**Comment by ksw9** [comment]
I didn't put in my full path for privacy, but yes, I confirmed the path is
to the .bz2 file. Thanks!

**Comment by khourhin** [comment]
OK, 
Indeed when I'm trying with the gatk tarball from https://anaconda.org/bioconda/gatk/files?type=conda (which looks like the one you used):

`gatk-register gatk-3.8-py36_2.tar.bz2`

Returns the error:

> Error: Unable to access jarfile ./GenomeAnalysisTK.jar
> The version of the jar specified, , does not match the version expected by conda: 3.8

But with the one downloaded from https://software.broadinstitute.org/gatk/download/, apparently no problems. It's only a workaround but might help.

**Comment by tomkinsc** [comment]
To clarify, Bioconda cannot distribution (pre-v4) versions of GATK directly, so the register script is intended to copy in a licensed copy of GATK downloaded from the Broad Institute’s website. The tarball from anaconda.org will *not* work as it only contains the registration script, and not GATK itself which must be sourced by the user. This may change under the new licensing scheme but for now this is the way it works.

**Comment by ksw9** [comment]
Got it, thanks!

**Comment by peflanag** [comment]
Hey, I'm confused! I'm not tech savvy with command line so my terminology might be wrong. I have installed gatk with "conda install -c conda-forge -c bioconda gatk" 
but the "gatk-register path-to-downloaded-gatk3.8" command wont work

Any ideas?
