### ISSUE TITLE
Building using git repository for newick_utils

### ISSUE THREAD

**Issue by Cashalow** [bioconda/bioconda-recipes#6039]
Hello,

I am trying to update (again) newick_utils. Indeed the stable release is very old (2011), but the github repo has further commits that add new functionalities that I would like to use. According to the repo, the author has more or less stopped the development of newick_utils. Can you confirm to me that there is no way to add a package built based on a git repo and the only way would be to ask the mantainer to release a new stable release on its github package ? 

Thank you for your help,

**Comment by bgruening** [comment]
@Cashalow you can alsoways skip some linting if you need to.
But in this case you could simply use: https://github.com/tjunier/newick_utils/archive/da121155a977197cab9fbb15953ca1b40b11eb87.tar.gz to get the latest commit, right?

**Comment by Cashalow** [comment]
Ok thanks a lot I did not know you could do that ! (I had tried to have some of the linting skipped but somehow failed, anyway I will carry on with building on the archive).

**Comment by bgruening** [comment]
Cool, thanks!
