### ISSUE TITLE
recompile blast with --with-dll

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-recipes#6057]
The blast 2.6.0 package unpacks to 786MB. In constrained (docker) environments, that's huge. The cause seems to be the large number of statically linked executables.

 - Recompiling with `--with-dll` should fix this.
 - The OSX binaries could also be compiled, rather than copied from the release.
 - Using `--without-debug` and/or `strip` from `binutils` to clean out debug symbols should further reduce size. I'm getting 81MB total on naive OSX build.
 - Using `--with-check` seems prudent (apparently enables unit tests)

Does anyone understand all the flags that can be enabled/disabled on the blast compile? Or have a link to some docs that are more informative than `./configure --help`?

**Comment by bgruening** [comment]
@epruesse is this still valid? Can we close the issue?

**Comment by epruesse** [comment]
Closing it. The new BLAST package is only 31M unpacked. :-)
