### ISSUE TITLE
name collision: jellyfish -> conda-forge/jellyfish-feedstock

### ISSUE THREAD

**Issue by croth1** [bioconda/bioconda-recipes#6107]
bioconda's jellyfish recipe has a name collision with conda-forge/jellyfish-feedstock.

**Comment by bgruening** [comment]
:( but expectable ... can we rename the bioconda one and update all dependent packages?

**Comment by bgruening** [comment]
ping @croth1

**Comment by croth1** [comment]
Hmh, back then it was just a random observation - I'd need help to solve this:
- a suggestion of a new name
- help on how renaming works - is it just submitting a new recipe + one of the admins moving the old to the deprecated channel?

**Comment by epruesse** [comment]
I had to rename `arb` to `arb-bio` so that it would not conflict with `libarb`. Annoying because `arb` does get called `arb` name in Debian/Ubuntu...

**Comment by bgruening** [comment]
Ok, I put up a rename PR. Please comment on this.
