### ISSUE TITLE
tag "latest" missing on quay.io

### ISSUE THREAD

**Issue by notestaff** [bioconda/bioconda-recipes#6113]
@bioconda/core   The page for bioconda docker containers e.g.
https://quay.io/repository/biocontainers/spades
says 
Pull this container with the following docker command:
docker pull quay.io/biocontainers/spades

running this command says that tag "latest" is missing.

**Comment by bgruening** [comment]
@notestaff I can not change the sentence. What I could do, but not sure how is to figure out what the latest version is and create a latest tag. Maybe by looking up what Conda identifies as latest version. Either way, this is somewhere on my todo list. Let me know if you would like to help.
