### ISSUE TITLE
RepeatMasker: how to install full repeat database

### ISSUE THREAD

**Issue by michaelbroe** [bioconda/bioconda-recipes#6161]
Running RepeatMasker gives the following message:

> RepeatMasker version open-4.0.6
Search Engine: NCBI/RMBLAST [ 2.2.27+ ]
Missing full RepeatMasker repeat library!
This installation of RepeatMasker is using the minimal repeat
database ( RepeatMaskerLib.embl ) which is distributed with the
program. This minimal database can only be used along with a
custom repeat library ( specified with the -lib option ). To
obtain the full repeat database please visit:
     http://www.girinst.org.

After obtaining the database from giri (`RepBaseRepeatMaskerEdition-20170127.tar.gz`) how can I configure RepeatMasker to read it?

Cheers!

**Comment by colindaven** [comment]
Perhaps this will help:

Comment from build.sh in the recipe:

# users will have to provide their own library and point to it using the REPEATMASKER_LIB_DIR environment variable

**Comment by michaelbroe** [comment]
Thank you for taking the trouble to reply.

bioconda is so plug-and-play it hadn't occurred to me to look for special comments in the build.sh script (as opposed to a readme or something like that). This is very useful information.

Cheers
