### ISSUE TITLE
QuasiRecomb package request

### ISSUE THREAD

**Issue by dridk** [bioconda/bioconda-recipes#6172]
https://github.com/cbg-ethz/QuasiRecomb

**Comment by bgruening** [comment]
@dridk do you want to work on this? It seems to be a Java application, so this documentation should get you started: https://bioconda.github.io/guidelines.html#java

**Comment by bgruening** [comment]
This package is now available from https://github.com/bioconda/bioconda-recipes/pull/17751

Thanks to @foellmelanie for working in this during the hackathon.
