### ISSUE TITLE
Remove dependencies from Docker build box

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#624]
I encountered a problem where samtools is requiring libncurses, yet it was merged and build for conda.
I think this is because the build box has too many libraries preinstalled, like in this line: https://github.com/bioconda/bioconda-recipes/blob/master/scripts/Dockerfile#L5

Can we remove the -devel packages and fix all packages that have these dependencies? I'm volunteering to do this.

**Comment by johanneskoester** [comment]
That sounds reasonable, thanks! @daler @chapmanb, I think you helped designing the image, do you agree?

**Comment by chapmanb** [comment]
Björn -- thank you for this. Apologies, I didn't realize these were getting dynamically linked against the CentOS 5 packages. Some of the libraries (like X11 mesa) are known external dependencies if you want to run those packages since they would be a beast to make as conda dependencies. Thanks again.

**Comment by bgruening** [comment]
Brad; yeah removing X11 would be crazy, I was more talking about bzip2-devel, zlib-devel and ncurses-devel.

I will work on this during the next week.
Thanks @chapmanb and  @johanneskoester!

**Comment by daler** [comment]
Thanks Björn, this would be great.

Is there a way to determine which existing packages would need rebuilding? I guess a brute force approach would be to try building all recipes in a container lacking those libs to see what fails, but maybe there's a more elegant solution.

**Comment by bgruening** [comment]
Ok, I have something to work, on but it really needs time here. I end up rebuilding the entire repository and many tools seems to need some ugly hacks to recognise the *.h files and I need some more time for this.

**Comment by johanneskoester** [comment]
Shouldn't it suffice to define the include path like [here](https://github.com/bioconda/bioconda-recipes/blob/c10e2fad3c441b55910fda4a6d1d2e0b4bfe2fa4/recipes/pybigwig/build.sh#L3)? Also, we should use the opportunity to switch to gcc and libgcc from anaconda.org for all recipes (I would also think that this might solve the include issues as well).

**Comment by johanneskoester** [comment]
Any updates?

**Comment by bgruening** [comment]
@johanneskoester no good ones. 100 out of 600 packages fail. Not only due to zlib but also because of unavailable URL's etc. This will take more time as I had hoped.

**Comment by johanneskoester** [comment]
Which branch is it? We can fix the recipes together.

**Comment by bgruening** [comment]
Need to push it, give me a few more days. Help is really appreciated. Any idea how to solve the broken URLs? https://github.com/galaxyproject/cargo-port or more https://bioarchive.galaxyproject.org/ usage would be possible.

**Comment by johanneskoester** [comment]
I think we encountered that issue before. If I am not mistaken @daler indeed used one of the resources you mention for newer bioconductor recipes.

**Comment by bgruening** [comment]
Maybe I can hack up a script and replace the URLs automatically ...

**Comment by chapmanb** [comment]
Björn and Johannes;
I'm working on moving perl recipes to use conda gcc for builds to help with this. Do we need gcc to be a `run` requirement, or is listing it as a `build` requirement sufficient to give the portability we need?

**Comment by johanneskoester** [comment]
gcc itself does not need to be a run requirement. But some (not every) code requires libgcc, the corresponding runtime. So far, we always added libgcc as a runtime dependency, just in case. I think it won't hurt.

**Comment by bgruening** [comment]
Time flys and we have a much nicer build system by now.
