### ISSUE TITLE
Possible issue due to conda-build path.

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#6245]
Hi Team Bioconda,

I'm running into errors building the [Indigo chemical toolkit](https://github.com/zachcp/bioconda-recipes/tree/indigo) and am running into some errors that are related to the conda build process.  Basically I am trying to run the build scripts but am getting an error message that the directory is not there.  I have tried specifying the build folder to no effect and am hoping that some extra eyeballs can help me diagnose the issue.

Thanks,
zach cp

Travis Build Logs:
https://travis-ci.org/zachcp/bioconda-recipes/builds/283877857
https://travis-ci.org/zachcp/bioconda-recipes/jobs/283877858
https://travis-ci.org/zachcp/bioconda-recipes/jobs/283877859

```
# relevant bits
...
+ '[' Darwin == Darwin ']'
+ export MACOSX_DEPLOYMENT_TARGET=10.9
+ MACOSX_DEPLOYMENT_TARGET=10.9
+ python build_scripts/indigo-release-libs.py --preset=mac10.9
python: can't open file 'build_scripts/indigo-release-libs.py': [Errno 2] No such file or directory
...
```

Build.sh:
```
mkdir -p $PREFIX/bin

if [ "$(uname)" == "Darwin" ]; then
  export MACOSX_DEPLOYMENT_TARGET=10.9
  python build_scripts/indigo-release-libs.py --preset=mac10.9
  python build_scripts/indigo-release-libs.py --preset=mac10.9
else
  python build_scripts/indigo-release-libs.py --preset=linux64
  python build_scripts/indigo-release-utils.py --preset=linux64
fi
```

Indigo Repo:
https://github.com/epam/Indigo

**Comment by etal** [comment]
This issue might be the same one I'm seeing in the cnvkit package: etal/cnvkit#254

Here's an example [failed build log](https://travis-ci.org/etal/cnvkit/jobs/283887161) on TravisCI -- `conda-build` fails, logs are unclear as to the root cause, lots of "prefix" stuff in the paths. Some suspicion of R package/dependency versions; I see similar errors with and without the "R" conda channel included in the cnvkit installation command.

**Comment by zachcp** [comment]
Thanks @etal.

Yours looks like a linking error of some sort but at least is building  :)

```
ERROR:conda.core.link:An error occurred while installing package 'defaults::r-base-3.2.2-0'.

PaddingError: Placeholder of length '80' too short in package /home/travis/miniconda3/conda-bld/cnvkit_1507236061611/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/Rscript.

The package must be rebuilt with conda-build > 2.0.

Attempting to roll back.

Build prefix failed with prefix length 255

WARNING:conda_build.environ:Build prefix failed with prefix length 255

Error was: 
```


After a weekend of sleeping on it I think i have made mistake in my recipe that  I noticed when going though yours.  

```
# previous
fn: indigo-1.3beta

# current: I believe this explains why the directory was not found - it wasn't being unpacked.
fn: indigo-1.3beta.tar.gz
```

**Comment by zachcp** [comment]
My issue was indeed the incorrect `fn` value. I am now building. There may be other issues, of course but these can be addressed separately.

Thank you @etal for indirectly solving my problem!
