### ISSUE TITLE
List of Python packages mapped from bio.tools to PyPI

### ISSUE THREAD

**Issue by dansondergaard** [bioconda/bioconda-recipes#6254]
Here's the (short) list of packages that we we're able to map to PyPI:

(bio.tools identifier, bio.tools entry name, PyPI package name, PyPI package url)

- SciLuigi SciLuigi sciluigi https://github.com/pharmbio/sciluigi
- seqcluster seqcluster seqcluster http://github.com/lpantano/seqcluster
- Mikado Mikado mikado https://github.com/lucventurini/mikado
- macs MACS macs http://liulab.dfci.harvard.edu/MACS/
- intermine InterMine intermine http://www.intermine.org
- gemtools GEMtools gemtools https://github.com/gemtools/gemtools
- gat GAT gat https://github.com/AndreasHeger/gat
- besst BESST besst https://github.com/ksahlin/BESST
- structure_threader Structure_threader structure_threader https://github.com/StuntsPT/Structure_threader
- Scoary Scoary scoary https://github.com/AdmiralenOla/Scoary

No idea if it's useful.

**Comment by bgruening** [comment]
Thanks for this. I will follow up on this and the new bio.tools strategy ...
