### ISSUE TITLE
Channel Priorty

### ISSUE THREAD

**Issue by rfarouni** [bioconda/bioconda-recipes#6271]
The current channel priorty order 

```
(conda config --add channels r)
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
```

is giving me a headache. With such a priorty setting, R 3.2.1 gets installed instead of the latest 3.4.1. Also the numpy installation gets linked with Openblas instead of MKL. MKL on my system is much faster and the latest R is essential when working with the latest Bioconductor packages

**Comment by bgruening** [comment]
@rfarouni if you want to current channel priority order please refer to https://bioconda.github.io/index.html#set-up-channels

**Comment by rfarouni** [comment]
@bgruening Sorry I submitted the comment before I finished writing it.

**Comment by johanneskoester** [comment]
I cannot reproduce what you report. The order means that bioconda has highest priority, then conda-forge and then defaults. conda-forge provides R 3.4.1. And I always get MKL installed when I try to install numpy. Do you see these problems as well when trying to create a new environment?

**Comment by rfarouni** [comment]
@johanneskoester Yes, but maybe because I am running Linux

**Comment by bgruening** [comment]
@rfarouni feel free to reopen, if you still have problems.
