### ISSUE TITLE
In recipe guidelines, suggest that people add "keywords" in the "about" section

### ISSUE THREAD

**Issue by notestaff** [bioconda/bioconda-recipes#6302]
It would be good if recipes were tagged with standardized keywords, e.g. assembler, mapper etc.
Could then auto-generate lists of related tools, see which bioinformatics topics are under-represented, etc.

**Comment by johanneskoester** [comment]
Good point. To some extent, this would be accomplished by the upcoming integration of Bioconda with the bio.tools database. Basically, people could search bio.tools for the software they need, and use Bioconda to install it. However, it might be still good to have keywords in the recipe. @bioconda/core, what do you think?

**Comment by daler** [comment]
I'd say it's a good idea, but only if 1) there's an existing controlled vocabulary of tags, and 2) we add a linter that requires all added keywords to come from the controlled vocabulary. Otherwise it has the potential to get messy, add noise, and be difficult to parse.

**Comment by notestaff** [comment]
There's also https://omictools.com/ .  At the moment it seems more complete than bio.tools , i.e. a few random tools I've tried were listed there but not in bio.tools .

**Comment by notestaff** [comment]
There's also this database that assigns Research Resource Identifiers (RRIDs) to tools:
https://scicrunch.org/resources
e.g.
 https://scicrunch.org/resources/Tools/record/nlx_144509-1/ca1ef5c9-66ac-5889-a77b-a8fc43349c6e/search?q=bowtie&l=bowtie
Can help disambiguate similarly-named tools.

**Comment by bgruening** [comment]
ping @joachimwolff ... related to the small bot.

@notestaff we will try to keep https://github.com/bio-tools/content/ in sync with bioconda. This will get us a nice ontology instead of tags that everyone can make up.

Let me know if you want to contribute to this.
I will close the issue, please feel free to reopen if we are too slow.
