### ISSUE TITLE
Pyparsing package not needed

### ISSUE THREAD

**Issue by jeromekelleher** [bioconda/bioconda-recipes#631]
The pyparsing package was added unnecessarily as part of the dependencies for msprime in #607. This should be removed.

What is the procedure for removing packages from the upstream repository? Does this happen automatically when the corresponding recipes are removed or does something else need to happen?

Thanks to @kyleabeauchamp for pointing this out in #629.

**Comment by kyleabeauchamp** [comment]
It does not happen automatically.  I suppose the only way to do it is for @johanneskoester  to manually delete the files from the cloud using either the web or cmdline interfaces to conda.

**Comment by jeromekelleher** [comment]
Thanks @kyleabeauchamp, I've opened PR #633 to remove the pyparsing recipe.

@johanneskoester, sorry to bother you with this, but could you delete the built pyparsing package from the repo please?

**Comment by johanneskoester** [comment]
Sure, no problem. I have deleted it for you.

**Comment by jeromekelleher** [comment]
Thanks @johanneskoester!
