### ISSUE TITLE
Workflow management section in Bioconda paper?

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#6326]
@bgruening @chapmanb do we want a paragraph per WMS that describes (with examples) in what way Bioconda/Conda is integrated into the workflow engine or definition? I could write something like that for Snakemake, but only if you want to do the same for Galaxy and BCBio-nextgen. If not, I would rather leave this out. I don't want to bias the reader towards one of the solutions.

**Comment by bgruening** [comment]
I can add a section, but my gut feeling says we should try to make this independent and maybe just mention that they are a few larger systems that rely on this project heavily.

**Comment by johanneskoester** [comment]
Ok, that sounds reasonable as well. We already have a sentence in the main text about the tight integration into the three WMS. We can leave it like that.

**Comment by chapmanb** [comment]
Johannes and Björn -- I'm fine with either approach. I could write a sentence about bcbio usage building all-in-one Docker containers (https://github.com/bcbio/bcbio_docker) with CloudBioLinux or just leave it as a mention. Thanks for including this.

**Comment by johanneskoester** [comment]
Ok, let's leave it as it is now, and see if the reviewers want more details.
