### ISSUE TITLE
samtools error with ncurses

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#637]
In the `bioconda/bioconda-builder` container, `samtools` works fine and therefore the build passes. But on Ubuntu 14.04, I get a libncurses error:

```bash
$ conda create -n samtools-test -c bioconda samtools
$ source activate samtools-test
$ samtools
samtools: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar
```

Looking at the other available versions, I see that in v1.1 [the `build.sh`](https://github.com/bioconda/bioconda-recipes/blob/d7dcc5d86f9b2cc1fe65a86ab8e62c14a5e83a5f/recipes/samtools/1.1/build.sh) fixes some stuff with ncurses. But I get the same problem with v1.1:

```bash
$ conda create -n samtools-test-1.1 -c bioconda "samtools==1.1"
$ source activate samtools-test-1.1
$ samtools
samtools: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar
```
I'm not sure how to fix this, mostly because I'm unfamiliar with C and how libs are handled. Any ideas?

**Comment by daler** [comment]
Never mind, found #246. Using 
```
conda install -n samtools-test -c r ncurses
```
fixed this. Definitely not obvious, but I don't see an obvious fix either.

**Comment by johanneskoester** [comment]
The correct fix would be [my PR](https://github.com/conda/conda-build/pull/728). In the meantime, we can assume that people have the R channel active as well (it is mentioned on the Bioconda homepage that this is a requirement).

**Comment by daler** [comment]
Ah, didn't see that PR. And I missed that addition to the docs -- I will re-read them now!
