### ISSUE TITLE
Unicycler update to 0.4.2 requires an offline build

### ISSUE THREAD

**Issue by ar0ch** [bioconda/bioconda-recipes#6455]
Hi all,

I'd like to submit a new Unicycler recipe ( [patch here](https://gist.github.com/ar0ch/0cddd9ac807349d48a3a407ec86133aa) ) that updates Unicycler to 0.4.2 and adds racon and miniasm as run time dependencies.  It looks like conda-forge hasn't moved to the new devtoolset yet (https://github.com/conda-forge/docker-images/pull/23) which would include a newer gcc/gxx in the build container and GCC 4.9+ is not available via Continuum / Anaconda yet.  Unfortunately, these builds will fail CI because of the gcc version issue, see [travis-ci logs](https://travis-ci.org/ar0ch/bioconda-recipes/builds/292090164) from my fork:

```
BUILD START: unicycler-0.4.2-py36_0
    (actual version deferred until further download or env creation)
updating index in: /opt/conda/conda-bld/linux-64
updating index in: /opt/conda/conda-bld/noarch
Can't build /opt/recipe due to unsatisfiable dependencies:
Package missing in current linux-64 channels: 
  - gcc >=4.9.4
```

The last Unicycler update required an offline build: https://github.com/bioconda/bioconda-recipes/pull/5923, which I guess we'll need for this one as well.

This update would also require that https://github.com/bioconda/bioconda-recipes/pull/6433 be merged so that Racon is installable in py3 environments

Thanks and let me know if any other info is needed
Aroon

**Comment by bgruening** [comment]
@ar0ch I'm happy to do the offline build again and push this. Hopefully we will get a new GCC soon!

**Comment by ar0ch** [comment]
Awesome, thanks @bgruening!  PR here: https://github.com/bioconda/bioconda-recipes/pull/6515

It looks like Anaconda 5 was released a few days ago and that brings the new GCC, so hopefulyl conda-forge will update the devtoolset soon :)

**Comment by bgruening** [comment]
Unfortunately, this will take some time. The update to conda-build-3 is a lot of work.

**Comment by ar0ch** [comment]
@bgruening Have you had a chance to do this offline build?  No rush/pressure!

**Comment by bgruening** [comment]
Urgs ... I forget to ping back here. A new version should be online.
