### ISSUE TITLE
Pear downloads now problematic

### ISSUE THREAD

**Issue by peterjc** [bioconda/bioconda-recipes#6456]
RE: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pear/meta.yaml

The old homepage https://sco.h-its.org/exelixis/web/software/pear/ still has lots of broken ULRs to download the current and past releases. The old URLs like http://sco.h-its.org/exelixis/web/software/pear/files/pear-0.9.6-src.tar.gz now give an Error 404.

The page has a link to https://www.h-its.org/en/research/sco/software/#NextGenerationSequencingSequenceAnalysis which offers a commercial or *"PEAR Academic, If you are a member of an academic institution and you use this software solely for research purposes, you can download this."* which is via https://www.h-its.org/downloads/pear-academic/

The license is probably the same (*Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported*), but this is not clear to me (missing title).

The problem is there is no clean download URL, rather a "checkout" zero price button with a click-through form to be filled in.

**Comment by peterjc** [comment]
Note the download checkout form has this additional term:

> #3b Sharing the product
> It is prohibited to share the download links or the digital product with any other person, unless it is specified in one of the individual software licenses. Each copy needs to be acquired through a separate digital product checkout process.

It looks like the package maintainer would have to manually go though the form, download the package, cache it somewhere (should be allowed under the terms of the CC-BY-NC-SA 3.0), and point BioConda at the cache.

**Comment by nsoranzo** [comment]
@peterjc You should be able to use the source package saved in depot: https://depot.galaxyproject.org/software/pear/pear_0.9.6_src_all.tar.gz

**Comment by mbargull** [comment]
@nsoranzo just beat me to it and his solution is superior ;)

**Comment by peterjc** [comment]
The cached source at https://depot.galaxyproject.org/software/pear/pear_0.9.6_src_all.tar.gz is perfect if we need to update the v0.9.6 package.

But what happens next time Pear is updated? Does the person doing the update have to click though the form and then cache the source package somewhere?

**Comment by bgruening** [comment]
@peterjc the author contacted me a few weeks ago and complained that I have written the Galaxy integration and I should remove the tool from the TS. This was all unjustified and the current license does not restrict re-distributing, but he made very clear that this is not intended and he probably changes the license. Let worry about this iff the next release is available.

**Comment by peterjc** [comment]
I suspect the author is under pressure from their employer trying to commercialise the tool. As you suggest, let's wait and see what happens with the next release of Pear.

**Comment by peterjc** [comment]
Currently the BioConda recipe is for Pear 0.9.6

According to https://sco.h-its.org/exelixis/web/software/pear/ (old home page) there was a 0.9.8 release:

> PEAR 0.9.8 released 2015-04-09
> An updated version of PEAR is released.
> * Added --version options
> * Fixed minor error when loading bzip files
> * Lowered autotools version

According to https://www.h-its.org/downloads/pear-academic/ (on the new home page) there is an even newer 0.9.11 release:

> **Release**
>
> Current Tag: 0.9.11
> Description:
> > Notes
> > 1. The pre-compiled linux binary pear-0.9.11-linux-x86_64.tar.gz is compiled statically with [zlib](http://www.zlib.net) and [bzip2](http://bzip.org) support.
> > 2. The file pear-src-0.9.11.tar.gz contains the pear source code and does not require autotools installed.
> > 3. The file LICENSE.txt contains the license agreement, that you accept by downloading, installing and using this software.
>
> **Important notice**
>
> The PEAR creative commons license prohibits commercial use of the code. For testing and using PEAR on a commercial basis you need to purchase a commercial software license.
>
> **License**
>
>THE WORK (AS DEFINED BELOW) IS PROVIDED UNDER THE TERMS OF THIS CREATIVE COMMONS PUBLIC LICENSE (“CCPL” OR “LICENSE”). THE WORK IS PROTECTED BY COPYRIGHT AND/OR OTHER APPLICABLE LAW. ANY USE OF THE WORK OTHER THAN AS AUTHORIZED UNDER THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
>
> BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED HERE, YOU ACCEPT AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. TO THE EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE LICENSOR GRANTS YOU THE RIGHTS CONTAINED HERE IN CONSIDERATION OF YOUR ACCEPTANCE OF SUCH TERMS AND CONDITIONS.
>
> ...
>
> “License Elements” means the following high-level license attributes as selected by Licensor and indicated in the title of this License: Attribution, Noncommercial, ShareAlike.
>
> ...

They fail to say clearly the license title, thus which of the “License Elements” are being used. I infer they are still imposing at least the Non-commercial license element.

**Comment by bgruening** [comment]
@peterjc any news here. After they have contacted me personally I have dropped the ball here and I'm not gonna spend time on pear anymore.

**Comment by peterjc** [comment]
We need someone familiar with the CREATIVE COMMONS PUBLIC LICENSE  (CCPL) and how and if restrictions can be applied to it to comment. See also this note on the old home page https://sco.h-its.org/exelixis/web/software/pear/

> Important notice
The PEAR creative commons license prohibits commercial use of the code. For testing and using PEAR on a commercial basis you need to purchase a commercial software license. If you wish to purchase such a license please contact:
Prof. Alexandros Stamatakis

Their intent is clearly to prevent commercial use, which sadly appears to prevent distribution, and thus BioConda packaging of the newer releases.

**Comment by winni2k** [comment]
I am a researcher who was hoping to build a conda packaged tool that relies on pear 0.9.10. If I can't get pear 0.9.10 through conda then I will be looking for an alternative to pear. 🤷‍♂️

**Comment by winni2k** [comment]
For anyone else reading this issue, FLASH appears to be a GPL3 licensed alternative: https://bioconda.github.io/recipes/flash/README.html

**Comment by bgruening** [comment]
@winni2k exactly. Galaxy also switched from PEAR to FLASH.
