### ISSUE TITLE
pysam seems to have missing dependency or file

### ISSUE THREAD

**Issue by gioelelm** [bioconda/bioconda-recipes#6525]
When I try to build a package including with ``pysam`` as a run dependency I get this problem during testing:

```
  File "/home/gioele/anaconda3/conda-bld/velocyto_1509204700142/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/site-packages/velocyto/counter.py", line 8, in <module>
    import pysam
  File "/home/gioele/anaconda3/conda-bld/velocyto_1509204700142/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory
Tests failed for velocyto-0.9.8-py36hc6d07c3_0.tar.bz2 - moving package to /home/gioele/anaconda3/conda-bld/broken
```

This is probably related to the fact that my all environment is based on anaconda  and bzip2-1.0.6 might have a missing file in the anaconda build as explained in this issue:
https://github.com/ContinuumIO/anaconda-issues/issues/2441

Installing using Pypi ``pysam 0.11.2.2`` and my package on pip everything is working out.
I think this should be solved at the level of bioconda somehow to allow the build process to work .
Any suggestions?

Fing below the requirements and thest from my ``meta.yaml``:

```
requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
  run:
    - python
    - h5py
    - numpy
    - scipy
    - cython
    - pysam
    - matplotlib
    - scikit-learn
    - click
    - loompy
    - numba
    - typing

test:
  imports:
    - velocyto

  commands:
    - velocyto --help
```

**Comment by bgruening** [comment]
@gioelelm please make sure your channel order is correct. `conda-forge` should be before `defaults`.

**Comment by gioelelm** [comment]
It feels like a strong constraint isn't it? I would have also to specify this in my package documentation and basically require the users of the package to accept this priority change, right? 

For a long time me my colleagues have preferred to use ``defaults`` and keep other channels ``bioconda`` and ``conda-forge`` as backups where a package is not available. I found that even when I leave ``conda-forge`` as my lowest priority channel it tends to mess up my all installation. Is the conda community moving to ``conda-forge`` centered environemt? I read [this](https://www.anaconda.com/blog/developer-blog/announcing-the-release-of-anaconda-distribution-5-0/) but  I am not very update on the topic.

**Comment by bgruening** [comment]
We depend on conda-forge and we build against conda-forge. Please see https://bioconda.github.io/index.html#set-up-channels for how you need to set the channel order. Everything else can break. This is because channel orders matter, during build and run-time and we need to have the same.

**Comment by gioelelm** [comment]
Ok it makes a lot of sense. But then I imagine it would be quite difficult to transition an existing environment to use the different channel order without breaking the environment at some point, right? Shouldn't the docs specify that it is recommended to make a clean `conda` environment?

**Comment by bgruening** [comment]
Existing environments should not be effected, afaik, and it will not break these environments. However, new environments should follow the correct channel priority. This is true for all conda channels.

Hope this helps. Feel free to reopen if you still have problems.
