### ISSUE TITLE
Haskell (stack build) recipes do not build on MacOS

### ISSUE THREAD

**Issue by luispedro** [bioconda/bioconda-recipes#6607]
There are a few Haskell packages on bioconda (`grep`ing just now, I find my own ngless, as well as cmv, rnalien, and selectsequences).

None of them build on macOS.

They all have the relevant `skip` flag, so there is no failure, but this is not the optimal situation.

/cc @eggzilla (who I believe is maintaining the other Haskell packages)

**Comment by bgruening** [comment]
@luispedro @eggzilla tried hard to get stack running on OSX, but this seems to be non-trivial. Any help welcome!

**Comment by eggzilla** [comment]
Hi, @luispedro , nice to see more Haskell developers joining bioconda :-)
I am also not statisfied with the current situation. Stack 1.6.1 is currently in pre-release, I will start
a new effort on resolving the situation on release of the production version in the next days. If its ok for you I will ping you as soon as I update the recipe on conda-forge.

**Comment by eggzilla** [comment]
I forgot to mention that using biocontainers is a possible workaround for MacOs.

**Comment by luispedro** [comment]
Yes, ping me. My biggest limitation is that I don't have easy access to an OSX system for testing.

**Comment by luispedro** [comment]
I posted on reddit asking for help from the Haskell community:

https://www.reddit.com/r/haskell/comments/8hdzrv/call_for_help_we_cannot_get_haskellbased_anaconda/

**Comment by bgruening** [comment]
@luispedro @eggzilla can we close this issue or should we keep it open?

**Comment by eggzilla** [comment]
Hi, I think that we discussed on an other thread to solve the problem with static compilation. From my side the issue can be closed.
