### ISSUE TITLE
r-phangorn package has conflicting dependencies

### ISSUE THREAD

**Issue by ilevantis** [bioconda/bioconda-recipes#6651]
After doing `conda create -n r r` to create a fresh environment I tried to install the r-phangorn recipe.

I got the following dependency error:

```
(r) $ conda install -c bioconda r-phangorn
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - r-phangorn
Use "conda info <package>" to see the dependencies for each package.

(r) $ conda info r-phangorn
Fetching package metadata .............

r-phangorn 2.2.0 r3.4.1_0
-------------------------
file name   : r-phangorn-2.2.0-r3.4.1_0.tar.bz2
name        : r-phangorn
version     : 2.2.0
build string: r3.4.1_0
build number: 0
channel     : bioconda
size        : 2.5 MB
arch        : x86_64
has_prefix  : True
license     : GPL (>= 2)
license_family: GPL3
md5         : cb8871ae7744b6c681150ecb923296ed
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/bioconda/linux-64/r-phangorn-2.2.0-r3.4.1_0.tar.bz2
dependencies:
    libgcc
    r-ape >=4.1
    r-base 3.4.1*
    r-fastmatch
    r-igraph >=1.0
    r-magrittr
    r-matrix
    r-quadprog
    r-rcpp
```

**Comment by bgruening** [comment]
Which R version was installed in your initial `r` environment?
Please do the following `conda create -n r r r-phangorn`. This should work and get you the correct R versions. Also strictly this is also works `conda create -n r r-phangorn` and is probably even better, because you don't need `r`, but just `r-base`.

**Comment by ilevantis** [comment]
```
$ conda create -n phangorn r-phangorn
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - r-phangorn
Use "conda info <package>" to see the dependencies for each package.
```

It still seems to give the same error.

I tried to follow the dependencies and it seems like it might be to do with `r-fastmatch` and `r-phangorn` requiring different versions of `r-base`.

```
$ conda info r-fastmatch
Fetching package metadata .............

r-fastmatch 1.1_0 r3.3.1_0
--------------------------
file name   : r-fastmatch-1.1_0-r3.3.1_0.tar.bz2
name        : r-fastmatch
version     : 1.1_0
build string: r3.3.1_0
build number: 0
channel     : bioconda
size        : 34 KB
arch        : x86_64
has_prefix  : True
license     : GPL-2
license_family: GPL2
md5         : fb0ff115ff08b443ee6170efda199846
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/bioconda/linux-64/r-fastmatch-1.1_0-r3.3.1_0.tar.bz2
dependencies:
    libgcc
    r-base 3.3.1*

r-fastmatch 1.1_0 r3.3.2_0
--------------------------
file name   : r-fastmatch-1.1_0-r3.3.2_0.tar.bz2
name        : r-fastmatch
version     : 1.1_0
build string: r3.3.2_0
build number: 0
channel     : bioconda
size        : 35 KB
arch        : x86_64
has_prefix  : True
license     : GPL-2
license_family: GPL2
md5         : 64a94430991e61faaa1ce3b12578fc59
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/bioconda/linux-64/r-fastmatch-1.1_0-r3.3.2_0.tar.bz2
dependencies:
    libgcc
    r-base 3.3.2*
$ conda info r-phangorn
Fetching package metadata .............

r-phangorn 2.2.0 r3.4.1_0
-------------------------
file name   : r-phangorn-2.2.0-r3.4.1_0.tar.bz2
name        : r-phangorn
version     : 2.2.0
build string: r3.4.1_0
build number: 0
channel     : bioconda
size        : 2.5 MB
arch        : x86_64
has_prefix  : True
license     : GPL (>= 2)
license_family: GPL3
md5         : cb8871ae7744b6c681150ecb923296ed
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/bioconda/linux-64/r-phangorn-2.2.0-r3.4.1_0.tar.bz2
dependencies:
    libgcc
    r-ape >=4.1
    r-base 3.4.1*
    r-fastmatch
    r-igraph >=1.0
    r-magrittr
    r-matrix
    r-quadprog
    r-rcpp
```

**Comment by mbargull** [comment]
`r-fastmatch` built with `r-base 3.4.1.*` is available at conda-forge. I'd guess you miss conda-forge in your channel list.

**Comment by ilevantis** [comment]
Adding conda-forge to the channel list does indeed fix the problem.

There should probably be some mention on the [readme page](http://bioconda.github.io/recipes/r-phangorn/README.html) that the package currently requires the conda-forge channel to satisfy dependencies.

**Comment by daler** [comment]
@ilevantis on the [readme page](http://bioconda.github.io/recipes/r-phangorn/README.html#installation) it says

> "With an activated Bioconda channel (see [2. Set up channels](http://bioconda.github.io/index.html#set-up-channels)), install with:...".

That link [Set up channels](http://bioconda.github.io/index.html#set-up-channels) shows how to set up the channels (including conda-forge).

Previously we were worried about the information getting out-of-sync, and each README links to the most recent documentation. But I think the channel requirements have stabilized such that this should no longer be a problem. I think it might help new users if this information was directly in the README of each package, rather than requiring linking to the docs.

**Comment by ilevantis** [comment]
Ah I see now that the "Set up channels" link is specifically about setting up channels to make bioconda work rather than just general documentation about how to add a channel in conda. For the past year I've been using conda I never knew that conda-forge packages were requirements for bioconda packages!

Perhaps rewording the sentence to:

"With an activated Bioconda channel (see 2. Set up channels for how to ensure all Bioconda dependencies can be met), install with...

**Comment by bgruening** [comment]
Hope it is more clear today. You are correct that conda-forge was not always a dependency, we changed this at some point.
