### ISSUE TITLE
Travis-CI complains "Build config did not create any jobs" since commit 5a76a5

### ISSUE THREAD

**Issue by fgp** [bioconda/bioconda-recipes#6809]
Since I pushed commit 5a76a5 to my fork's master branch, pushing to my recipe branch no longer triggers a travis-ci build. Travis-CI lists the commit under "Requests", but reports that ""Build config did not create any jobs". I suspect the problem is the "fork = true" condition -- could it be that Travis-CI somehow doesn't know that my repository is a fork of the main bioconda-recipe repo? Do I have to tell Travis-CI that somehow? The "Contributing" section of the manual does not seem to specify any special steps one must take to configure that, and the Travis-CI documentation (https://docs.travis-ci.com/user/conditional-builds-stages-jobs/) seems to indicate that "fork" is a built-in variable (I guess Travis-CI queries it from github somehow).

**Comment by daler** [comment]
@fgp we've been making some improvements to the build system in the past day or so. Things are still settling down, and it may be that we're missing something here. The latest fix we're working on is https://github.com/bioconda/bioconda-recipes/pull/6811. Once that's merged into master and you pull those changes to your fork, would you mind trying again? If it still doesn't work then we'll work on a fix.

In the meantime, can you post a link to the travis-ci build you're referring to? I don't see any bioconda-recipes forks under your account.

**Comment by fgp** [comment]
I just pulled the latest master and pushed that master plus my branch rebased on top of it (named r-akima) to https://github.com/Cibiv/bioconda-recipes. It seems that the problem persists - still nothing scheduled on Travis-CS (well, the master push trigger a build, but I cancelled that. The build I want is the one of my r-akima branch)

**Comment by daler** [comment]
I tested it on my fork as well and I'm also not seeing the branch tests. I'll play around with it some more. The logic looks correct in the job selection. 

You're right, travis-ci has the existing fork variable. We're testing out these beta features: 

- https://docs.travis-ci.com/user/build-stages/
- https://docs.travis-ci.com/user/conditional-builds-stages-jobs/

Also, if this is in preparation for an `r-akima` PR (as implied by your branch name) would you please submit it to conda-forge instead since it's not a bio-specific package?

**Comment by fgp** [comment]
This is indeed in preparation of a `r-akima`PR, but only because the next step after that is a PR for my own R package (called `gwpcR`) which happens to depend on `r-akima`, and which definitely is a bio-specific package (It's a model of PCR amplifcation and NGS sequencing that we describe in a paper recently uploaded to bioArxiv). Since `r-akima` just a necessary dependency from CRAN, I wasn't quite sure where to submit it -- I'll gladly submit to conda-forga if that's more appropriate. I'd still like to get the CI process going for `r-akima` though, since that's what I already started with, and I guess duplicating this for my package will then simply be a matter of copy and paste.

**Comment by DrYak** [comment]
Hello, I'm seeing the exact same problem in my local fork too :

 - pushes to the forked master do trigger Travis
 - pushes to my recipes-branch do not trigger Travis, only the pull-request to your parent repository does trigger on your Travis account.

**Comment by johanneskoester** [comment]
@DrYak, could you show me your `.travis.yml` on the branch that has the problem?

**Comment by johanneskoester** [comment]
@DrYak Wait, I think I have seen it. So, it looks like the `fork` variable in the `.travis.yml` is false, when not doing a pull request... 
What happens if you replace `fork = true` with `repo != bioconda/bioconda-recipes`?

**Comment by johanneskoester** [comment]
A fix will hopefully be PR #6986.

**Comment by johanneskoester** [comment]
This should be fixed now.

**Comment by johanneskoester** [comment]
Should be fixed via #6986. Feel free to reopen if the problem persists.

**Comment by fgp** [comment]
Seems to work now, just pushed and travis-ci started building. Thanks a bunch to everyone for helping to fix this!
