### ISSUE TITLE
Delete unnecessary branches

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-recipes#6812]
There are a bunch of (probably dead) branches on bioconda-recipes. Should they be cleaned out?

(As an aside: is the mechanism behind the `bulk` branch documented anywhere?)

**Comment by daler** [comment]
Probably a good idea to clean them out. What should the criteria be though?

I don't think `bulk` is documented anywhere, but I'll write it up.

**Comment by bgruening** [comment]
I clean at least the merged branches every month or so. We should organise a new hackathon when cb3 comes around and close also old open PRs.

Closing this for now.

**Comment by epruesse** [comment]
IIRC we had the discussion about prefix directories elsewhere before. Mostly, the number is so high because of the `bioconda-xyz` and the `r-xyz` packages, so it may suffice to split those out.

The number of branches may now be higher because of the autobump tool keeping ~100 of them around for recipes with active updates (i.e. recipes that won't build with the newest version for some reason and need manual intervention).

Did you experience performance issues with the number of `ref`s? A few thousand should be ok (outside of the github interface that is).
