### ISSUE TITLE
rpy2 still at v2.7.8

### ISSUE THREAD

**Issue by nick-youngblut** [bioconda/bioconda-recipes#6841]
I'm running conda on Ubuntu 16.04.3, and the most up-to-date version of rpy2 available from bioconda is v2.7.8. On my system, this rpy2 version generates the following error when I try to load it in a python kernel in Jupyter:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-fb23c6edefe4> in <module>()
----> 1 get_ipython().run_line_magic('load_ext', 'rpy2.ipython')

/ebio/abt3_projects/software/miniconda3/envs/py3/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2093                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2094             with self.builtin_trap:
-> 2095                 result = fn(*args,**kwargs)
   2096             return result
   2097 

<decorator-gen-65> in load_ext(self, module_str)

/ebio/abt3_projects/software/miniconda3/envs/py3/lib/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/ebio/abt3_projects/software/miniconda3/envs/py3/lib/python3.6/site-packages/IPython/core/magics/extension.py in load_ext(self, module_str)
     31         if not module_str:
     32             raise UsageError('Missing module name.')
---> 33         res = self.shell.extension_manager.load_extension(module_str)
     34 
     35         if res == 'already loaded':

/ebio/abt3_projects/software/miniconda3/envs/py3/lib/python3.6/site-packages/IPython/core/extensions.py in load_extension(self, module_str)
     90                               dir=compress_user(self.ipython_extension_dir)))
     91             mod = sys.modules[module_str]
---> 92             if self._call_load_ipython_extension(mod):
     93                 self.loaded.add(module_str)
     94             else:

/ebio/abt3_projects/software/miniconda3/envs/py3/lib/python3.6/site-packages/IPython/core/extensions.py in _call_load_ipython_extension(self, mod)
    137     def _call_load_ipython_extension(self, mod):
    138         if hasattr(mod, 'load_ipython_extension'):
--> 139             mod.load_ipython_extension(self.shell)
    140             return True
    141 

/ebio/abt3_projects/software/miniconda3/envs/py3/lib/python3.6/site-packages/rpy2/ipython/rmagic.py in load_ipython_extension(ip)
    786     # Initialising rpy2 interferes with readline. Since, at this point, we've
    787     # probably just loaded rpy2, we reset the delimiters. See issue gh-2759.
--> 788     if ip.has_readline:
    789         ip.readline.set_completer_delims(ip.readline_delims)

AttributeError: 'ZMQInteractiveShell' object has no attribute 'has_readline'
```

According to [this rpy2 issue](https://bitbucket.org/rpy2/rpy2/issues/359/rmagic-failing-to-load-with-ipython-500), believe this error was fixed in v2.8.2. 

I'm wondering why bioconda hasn't updated rpy2 to >= v2.8.2. As far as I can tell, rpy2 v2.7.8 doesn't really work, at least on Ubuntu 16.04.3. 

If I install a more up-to-date version of rpy2 from the "r" channel, this violates the [bionconda install docs](https://bioconda.github.io/) in terms of which channels to use, particularly:

> The r channel is only included due to backward compatibility

**Comment by bgruening** [comment]
rpy2 is moved to conda-forge where we have a 2.8.5 version. Please use this version.
https://github.com/conda-forge/rpy2-feedstock/

**Comment by nick-youngblut** [comment]
When setting the bioconda channel as higher priority than conda-forge, won't rpy2 from bioconda be installed instead of rpy2 from conda-forge, or does channel priority not apply in this situation?

**Comment by bgruening** [comment]
Yes, in this case you would get the bioconda one, but you can request a higher version of the package with `rpy2=2.8.5`

**Comment by nick-youngblut** [comment]
Ok. Thanks for the clarification. This does seem like an issue that many could face (at least on Ubuntu 16.04.3): they set channel priority as stated in the bioconda docs, then install jupyter & rpy2, then rpy2 doesn't work in Jupyter. So in this situation the user will have to search on why rpy2 isn't working, and then figure out that the conda-forge version should be used instead of the default-installed bioconda version. 

I'm guessing there's probably not a lot that can be done about this (the old bioconda version probably needs to still exist for backwards compatibility), but it does set up the user for some frustration.

**Comment by nick-youngblut** [comment]
I can create a new issue for this, but installing rpy2 v2.8.5 from conda-forge causes the issue that rpy2 uses the root conda environment for the R library path:

```
# Jupyter cell #1; kernel is "Python [conda env:py3]", and "py3" is a simple conda environment with rpy2 v2.8.5 installed
%load_ext rpy2.ipython
```

``` 
# Jupyter cell #2
.libPaths() 
[1] "/ebio/abt3_projects/software/miniconda3/lib/R/library"
```

With the library path set for the root environment, R packages installed in the current conda environment can't be used, and the point of installing R packages in a particular conda environment is to create isolated environments. 

Maybe this is a known issue, but I haven't been able to find it in the long list of conda-forge issues.

**Comment by daler** [comment]
@nick-youngblut I just tested it using a fresh envrionment I'm unable to reproduce. `.libPaths()` is pointing correctly to the environment's R lib for me. Can you double check that, e.g., `import rpy2; print(rpy2.__file__)` is pointing the environment's copy?

**Comment by nick-youngblut** [comment]
Yeah,  I tried creating a fresh environment too and wasn't able to recreate the `.libPaths()` issue. I'm not sure what went wrong, but it seems to be resolved.

**Comment by odedro** [comment]
How do you fixed this problem, in case you do not have conda ??
