### ISSUE TITLE
new project: bioconda-data

### ISSUE THREAD

**Issue by matthdsm** [bioconda/bioconda-recipes#6909]
Hi All,

I was wondering if anyone has thought about leveraging the conda system for for reference data.
There's already been some work towards this in the [gogetdata project](https://github.com/gogetdata/ggd-recipes) by @arq5x and it has been adapted by @chapmanb to be used in [cloudbiolinux](https://github.com/chapmanb/cloudbiolinux/tree/master/ggd-recipes). I think this endeavour would be a great fit for bioconda, and it would be a TREMENDOUS help to the community to have a go to version control system for reference data.

I'd love to hear some thoughts and comments towards this. I'm aware that costs for storage and network traffic may be limiting factors, but it'd be wonderful to have something like this.
Perhaps (wild speculation, bear with me here) a collaboration with the [Elixir project](https://www.elixir-europe.org) could be organized to offset some costs. An initiative like this looks like something along the lines of their bio.tools repo.

Let me know what you think!
Cheers
M

**Comment by kyleabeauchamp** [comment]
I think doing dataset storage well would be valuable but challenging.  For example, storage costs are high,  some sort of caching and data checking would be necessary, and many modern workflows require working with AWS or other object storage platforms.

**Comment by arq5x** [comment]
cc @brentp

**Comment by kyleabeauchamp** [comment]
Also: many datasets are currently distributed under "strange" licenses, meaning you may encounter legal roadblocks when trying to bring them into a unified API.

**Comment by bgruening** [comment]
The Galaxy project is maintaining a 4TB reference storage that is distributed via a CVMFS, this is also mirrored in Europe (also with ELIXIR support) and a mirror is planned in Australia as well. We are currently investigating how we can make the process of adding new data more transparent, but the infrastructure for this is already there.

If you want to play with it you can try the Galaxy Docker image: https://github.com/bgruening/docker-galaxy-stable#on-demand-reference-data-with-cvmfs--toc

The CVMFS setup is really easy to setup and the system is independent of Galaxy and can be used by everyone. @kyleabeauchamp the nice thing is caching etc is already build into the CVMFS abstraction.

Let me know if anyone wants to play with this and I can provide more information.

**Comment by matthdsm** [comment]
Hi Björn,

The galaxy CVMFS looks very interesting to me. Could you point me to some resources where I can read up on this?

Thanks a lot!
Cheers
M

**Comment by johanneskoester** [comment]
@bgruening, the CVMFS based solution is indeed interesting. A current problem is that it is not usable in a zero-setup/no-admin way without docker. To have that, we would need a CVMFS client that is available as a conda package. Do you you think that would be feasible?

Regarding conda for data (which would still make sense I think), @brentp what is the status of gogetdata?

**Comment by unode** [comment]
@johanneskoester Would something like [IPFS](https://ipfs.io/) + IPNS address the issues you mentioned?

**Comment by bgruening** [comment]
@matthdsm can you drop me a mail I will try to forward everything what I currently have.

@johanneskoester I dumped my trial of getting cvmfs-conda into staged-recipes. Its not easy and probably not possible currently as you need libfuse and a fuse enabled kernel. Not sure if its worth the effort. I will try to work on this over Xmas. But I guess fuse etc. is easy enough to install with system packages.
