### ISSUE TITLE
Guidelines for updating recipes

### ISSUE THREAD

**Issue by rfarouni** [bioconda/bioconda-recipes#6932]
@rvalieris @bgruening @druvus @daler 

A month ago, in the meta.yaml build requirement section of the recipe for [haystack_bio](https://github.com/bioconda/bioconda-recipes/blob/b91f47ed508daa529321f6aee23f14bd962082dd/recipes/haystack_bio/meta.yaml#L36), I set the version of meme to 4.11.2. A while ago the[ recipe](https://github.com/bioconda/bioconda-recipes/commit/b5664c17ce2bb231073f8696f4fe510e92c65ace#diff-096226c40490eaea0fd2bc4551b7a6f8L9) for 4.11.2 meme was replaced and updated to 4.12.0. Oddly the recipe for meme 4.11.1 was kept, but not that for 4.11.2. Was there a reason for skipping 4.11.1 but not 4.11.2? 

When now I  try to install *haystack_bio*, I get this error

```conda install haystack_bio
Fetching package metadata .............
Solving package specifications: 

PackageNotFoundError: Packages missing in current channels:
            
  - haystack_bio -> meme -> perl 5.22.0*
```

Is there a way to setup notifications if an installation fails due to a recipe update?  

Thanks.

**Comment by johanneskoester** [comment]
Thanks for reporting. Actually, the policy is to keep all old versions. However, we usually don't keep them as recipes (unless we need to rebuild them), but just the packages on the anaconda channel. As you can see [here](https://anaconda.org/bioconda/meme/files), 4.11.2 and 4.11.1 are both still there. It rather looks like somehow perl 5.22.0 is missing in your setup. Could you show us your channel setup?

**Comment by rfarouni** [comment]
I see. So the actually recipe doesn't have to exist in the Github repo! The perl error was caused by me removing the conda-forge channel ( it created some problems with my other installations). I added it again and the package installed.

**Comment by rfarouni** [comment]
But now although meme installs it doesn't run. The installed version is 
`meme                      4.11.2           py27pl5.22.0_0    bioconda`

but when I run meme --help  or fimo --help, I get an error 
```

meme: error while loading shared libraries: libicui18n.so.58: cannot open shared object file: No such file or directory
```

**Comment by johanneskoester** [comment]
Ok, glad it works now. The channel priority is crucial for packages to work. Only if it is exactly like we say in the docs, we can be sure that everything works as expected.
