### ISSUE TITLE
busco failed to install

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#6960]
Hi @simonvh, @daler, @abretaud,
I failed to install busco:

```
$ conda create -n busco python=3.6
$ source activate busco
$ conda install busco
....
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'bioconda::busco-3.0.2-py36_2'.
LinkError: post-link script failed for package bioconda::busco-3.0.2-py36_2
running your command again with `-v` will provide additional information
location of failed script: /work/waterhouse_team/miniconda2/envs/busco/bin/.busco-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

LinkError: post-link script failed for package bioconda::busco-3.0.2-py36_2
running your command again with `-v` will provide additional information
location of failed script: /work/waterhouse_team/miniconda2/envs/busco/bin/.busco-post-link.sh
==> script messages <==
<None>
```

Thank you in advance.

Michal

**Comment by mbargull** [comment]
Hi Michal,
you got an outdated and broken build of `busco 3.0.2` due to a [bug in Conda which is currently being worked on](https://github.com/conda/conda/pull/6296).
You'll get the newest build if you install `gsl` along with `busco`:
```bash
conda install busco gsl
```

**Comment by mcg1969** [comment]
@mbargull I came over here from PR 6296... I see that the outdated build of busco 3.0.2 is still being made available. Given our discussions, should that perhaps be archived?

**Comment by abretaud** [comment]
+1 to remove the broken build, I suspect it is breaking the tests of one of my PRs on another project

**Comment by mbargull** [comment]
@johanneskoester: That'd mean we have to label builds 0, 1, 2, and 3 of ` busco 3.0.2` as `broken`.

**Comment by johanneskoester** [comment]
Done!
