### ISSUE TITLE
sambamba optional runtime dependency on samtools/bcftools and package-split samtools

### ISSUE THREAD

**Issue by vinjana** [bioconda/bioconda-recipes#6974]
I need to install sambamba 0.5.9 with samtools/bcftools 0.1.19. Unfortunately, sambamba has a runtime dependency declared on bcftools that was split out of the samtools package some time after 0.1.19. Therefore, if I want to install sambamba 0.5.9 it will pull in the newer bcftools (which will BTW **silently** override the original 0.1.19 version). I would like to note that samtools/bcftools is an **optional** runtime dependency of sambamba, i.e. most of sambamba subtools work without it.

What should I do here? I think the correct solution would be to completely remove bcftools as dependency from sambamba. Any objections? Also, bcftools should get a dependency `samtools >=1.2` (or so, need to figure out the exact version) to avoid the overwriting of bcftools (which will result in a mix of samtools 0.1.19 and a newer bcftools). 

Another solution that would keep the runtime dependency would be to add a complex dependency of the sort "samtools <1.2 | samtools >=1.2, bcftools >=1.2" -- unfortunately this is the wrong syntax and I am not yet even sure whether conda[-build] can deal with such complex dependencies.

It would be nice to get some feedback on this before all the fuzz with a PR. So, comments are appreciated!

**Comment by bgruening** [comment]
@chapmanb @tomkinsc do you have any input here? Thanks!

**Comment by chapmanb** [comment]
+1 on removing the samtools and bcftools requirements from the recipe. I think it's fine to mention these as optional functionality but they're not required for most things you'd do with sambamba.

**Comment by vinjana** [comment]
Sorry for asking again, but parts of my question remain unanswered. What about older package versions? I need the sambamba 0.4.6 and 0.5.9 package versions w/o the samtools dependency. I guess, there are people who do not include the build version in their environment dependency explicitly. Would backporting then still be o.k.?

**Comment by johanneskoester** [comment]
Yes, backporting would be ok. You can add those versions as subfolders (if not already there), and increase the build number.

**Comment by bgruening** [comment]
I think this is resolved - feel free to reopen if there is still something unclear.
Thanks @vinjana!

**Comment by tomkinsc** [comment]
Removing the build dependenciew seems like the right call; thanks for handling this. We can always a `sambamba-full` package if it becomes an issue for users.
