### ISSUE TITLE
binsanity recipe is lacking dependencies

### ISSUE THREAD

**Issue by nick-youngblut** [bioconda/bioconda-recipes#7031]
The `binsanity` recipe (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/binsanity/meta.yaml) is currently lacking at least one dependency: `featureCounts`. The test for the recipe is `Binsanity -h`, which really doesn't check that all dependencies have been installed.

**Comment by bgruening** [comment]
@nick-youngblut do you know a better test?
Please see here for a fix: https://github.com/bioconda/bioconda-recipes/pull/7032

**Comment by nick-youngblut** [comment]
In regards to dependencies, `subread` just needs to be added to the requirements in the yaml file. `binsanity` seems to fully work after that (at least for `binsanity-wf`). 

In regards to a better test, `binsanity` does include a [test script](https://github.com/edgraham/BinSanity/blob/master/test-scripts/Binsanity-lc) for running one of the binsanity pipelines. Maybe @edgraham could also create a test script for the `binsanity-wf` pipeline.

**Comment by bgruening** [comment]
Ok, this should be fixed now.
Regarding the test, we can not afford to run functional tests in bioconda but a way to check if all dependencies are included would be nice.

Thanks for the report!
