### ISSUE TITLE
Best practices for bioconda / miniconda package compilation options

### ISSUE THREAD

**Issue by nickloman** [bioconda/bioconda-recipes#7082]
Hi

I'm attempting to update the recipe for nanopolish in Conda.

Currently the Bioconda recipe reuses the hdf5 recipe provided by Miniconda.

However nanopolish requires that HDF5 library is built with threadsafe mode. Modifying the HDF5 recipe would presumably have a large knock-on effect on other packages.

Nanopolish itself deals with this by downloading & configuring a custom hdf5 during make, but at the moment this is disabled.

I wonder what is the community's preferred way of dealing with an issue like this? I need to change the build.sh command to HDF5 to fix this.

Sorry if this is a dumb question - it is my first go at bioconda recipes.

Best
Nick

**Comment by druvus** [comment]
Hi @nickloman 
I did some of the initial work on the nanopolish recipe so it nice original authors here. The current version of the recipe uses the hdf5 from conda-forge, which is a a channel bioconda depends on. 

The conda-forge version of hdf5 should been built with threadsafe mode plus some additional stuff enabled:
https://github.com/conda-forge/hdf5-feedstock/blob/master/recipe/build.sh#L18

Did you have some issues indicating that threadsafe mode is not working using nanopolish from bioconda?

**Comment by kyleabeauchamp** [comment]
To follow up on what @druvus said, if you have issues with the HDF5 package version, a likely culprit is the channel ordering, which is a perennial source of confusion.

**Comment by bgruening** [comment]
@nickloman if you get hdf5 from `defaults` (miniconda) you probably have not set the channels correctly. Please follow: https://bioconda.github.io/index.html#set-up-channels

**Comment by nickloman** [comment]
Thanks @druvus @kyleabeauchamp @bgruening for your quick responses. I hadn't appreciated the details of the channel ordering, or that the conda-forge hdf5 recipe was different from the miniconda version. I've reviewed the conda-forge recipe and that's fine!

I've learnt a lot over the last day or two and hope to contribute back an updated nanopolish recipe shortly to bring it up to date.

Thanks for your help!
