### ISSUE TITLE
Version mismatch for bioconductor-org.ce.eg.db

### ISSUE THREAD

**Issue by jdblischak** [bioconda/bioconda-recipes#7117]
The [meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/df888a84679216aa7809f926ac75a2504467d5d4/recipes/bioconductor-org.ce.eg.db/meta.yaml) for [bioconductor-org.ce.eg.db](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/bioconductor-org.ce.eg.db) points to [version 3.2.3 from the 3.2 release](https://www.bioconductor.org/packages/3.2/data/annotation/html/org.Ce.eg.db.html).

The [post-link.sh](https://github.com/bioconda/bioconda-recipes/blob/df888a84679216aa7809f926ac75a2504467d5d4/recipes/bioconductor-org.ce.eg.db/post-link.sh) file points to [version 3.4.1 from the 3.5 release](https://www.bioconductor.org/packages/3.5/data/annotation/html/org.Ce.eg.db.html).

I was going to update this as part of https://github.com/bioconda/bioconda-utils/issues/235, but I wasn't sure what to do with it.

**Comment by daler** [comment]
@jdblischak this sounds like something I messed up when transitioning pre-existing data packages from the "normal" kind to the post-link kind.

This looks like it will install 3.4.1 even when asking for 3.2.3. I think the best fix would be to move 3.2.3 to a new directory, like in [bioconductor-org.dm.eg.db](https://github.com/bioconda/bioconda-recipes/tree/df888a84679216aa7809f926ac75a2504467d5d4/recipes/bioconductor-org.dm.eg.db), and make it a proper 3.2.3 recipe.
