### ISSUE TITLE
ensembl-vep: reasons to selectively install only some vep_plugins modules?

### ISSUE THREAD

**Issue by biocyberman** [bioconda/bioconda-recipes#7186]
vep-plugins has quite a few more Perl modules, could you @matthdsm tell the rationale of installing only some of them? The relevant code section is from line 39 to 44 of this file:
https://github.com/bioconda/bioconda-recipes/blob/bb40e7976c0e93897961d651699b1936e8d783db/recipes/ensembl-vep/build.sh#L39

**Comment by matthdsm** [comment]
Hi, 

There's not really a reasoning behind it. Those are just the plugins that are used within the bcbio framework. If you have an easy and efficiënt fix to install all of them, you're welcome to submit a PR.

Cheers
M

**Comment by biocyberman** [comment]
This is a simple way to let vep install its plugins by itself:
```diff
diff --git a/recipes/ensembl-vep/build.sh b/recipes/ensembl-vep/build.sh
index 2b2a4b1cb..2703e2d56 100644
--- a/recipes/ensembl-vep/build.sh
+++ b/recipes/ensembl-vep/build.sh
@@ -31,18 +31,18 @@ ln -s $target/* $PREFIX/bin
 cd $target
 # Use external Bio::DB::HTS::Faidx instead of compiling interally
 # Compile in VEP causes issues linking to /lib64 outside of rpath
-vep_install -a a --NO_HTSLIB --NO_TEST --NO_BIOPERL --NO_UPDATE
+vep_install -a a --NO_HTSLIB --NO_TEST --NO_BIOPERL --NO_UPDATE --PLUGINS
 # Remove test data
 rm -rf t/
 
 # Install plugins
-curl -ks -o CADD.pm https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/$version/CADD.pm
-curl -ks -o dbNSFP.pm https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/$version/dbNSFP.pm
-curl -ks -o MaxEntScan.pm https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/$version/MaxEntScan.pm
-curl -ks -o SpliceRegion.pm https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/$version/SpliceRegion.pm
-curl -ks -o GeneSplicer.pm https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/$version/GeneSplicer.pm
-curl -ks -o dbscSNV.pm https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/$version/dbscSNV.pm
-curl -L -ks -o loftee.tar.gz https://github.com/konradjk/loftee/archive/8de80a4.tar.gz
+# curl -ks -o CADD.pm https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/$version/CADD.pm
+# curl -ks -o dbNSFP.pm https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/$version/dbNSFP.pm
+# curl -ks -o MaxEntScan.pm https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/$version/MaxEntScan.pm
+# curl -ks -o SpliceRegion.pm https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/$version/SpliceRegion.pm
+# curl -ks -o GeneSplicer.pm https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/$version/GeneSplicer.pm
+# curl -ks -o dbscSNV.pm https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/$version/dbscSNV.pm
+# curl -L -ks -o loftee.tar.gz https://github.com/konradjk/loftee/archive/8de80a4.tar.gz
 tar -xzvpf loftee.tar.gz
 mv loftee-*/*.pl .
 mv loftee-*/*.pm .

```
conda-build command fails:

```bash
conda-build .
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Undefined Jinja2 variables remain (['CONDA_HTSLIB', 'CONDA_HTSLIB']).  Please enable source downloading and try again.

```

I did not know where to initialize `CONDA_HTSLIB` so I did not fill safe to make a PR.

**Comment by matthdsm** [comment]
Hi, 

Adding the `--plugins` flag does indeed install all plugins, but due to some quirks in the way conda uses perl and all of vep's dependencies, these plugins do not work. Hence the manual installation.

Cheers
M

**Comment by biocyberman** [comment]
Hi Mathias
I would like to try building the package, and see what quirks are there. Could you show me how to build this package? 
This line in `meta.yaml`, in which `CONDA_HTSLIB` is undefined, is causing the build to fail:
`string: "htslib{{CONDA_HTSLIB}}_{{PKG_BUILDNUM}}"`

**Comment by matthdsm** [comment]
You can find more info on build variants [here](https://conda.io/docs/user-guide/tasks/build-packages/variants.html). I also don't have that much experience with those. Perhaps @bioconda/core could help you along.

Cheers
M

**Comment by daler** [comment]
@matthdsm @biocyberman please see https://github.com/bioconda/bioconda-recipes/issues/7233#issuecomment-356300214. Bioconda needs some additional infrastructure to coordinate dependencies across thousands of packages, so there's some additional setup required.

**Comment by biocyberman** [comment]
@daler That explains a lot. Thanks
