### ISSUE TITLE
humann2 should be come with new version of metaphlan2

### ISSUE THREAD

**Issue by SilasK** [bioconda/bioconda-recipes#7257]
Can somebody update the requeirement in humann2 to request metaphlan2 >= 2.6

there were bugs in metaphlan2 2.5 mainly how to download the database.

Kind regards

**Comment by bgruening** [comment]
See here: https://github.com/bioconda/bioconda-recipes/pull/7268

Thanks for reporting! Please feel free to update those recipes on your own - everyone is welcome :)
