### ISSUE TITLE
MultiQC: wrong networkx dependency?

### ISSUE THREAD

**Issue by andreas-wilm** [bioconda/bioconda-recipes#7290]
Hi all,

I've create a new environment for multiqc 1.3 with `conda create -n multiqc-1.3 multiqc=1.3`.
After activating the env `multiqc --help` works fine, but running it on any folder produces the following error message:

    File "/apps/miniconda3/envs/multiqc-1.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.ContextualVersionConflict: (networkx 1.11 (/apps/miniconda3/envs/multiqc-1.3/lib/python3.6/site-packages), Requirement.parse('networkx>=2.0'), {'colormath'})

`conda list -n multiqc-1.3 -e` (see [cl.txt](https://github.com/bioconda/bioconda-recipes/files/1638099/cl.txt) for full list) shows that networkx=1.11 is installed!?

Thanks,
Andreas

**Comment by mbargull** [comment]
There is an error in the `colormath 3.0.0` package on `conda-forge`, see https://github.com/conda-forge/colormath-feedstock/pull/3.
You can `conda install -n multiqc-1.3 colormath<3` to get a compatible `colormath` version.

**Comment by mbargull** [comment]
`conda install -n multiqc-1.3 'colormath<3'` in a shell.

**Comment by andreas-wilm** [comment]
That fixes the issue for me. Closing because it's an upstream problem

**Comment by ewels** [comment]
Sorry all - this was my fault, merging a bad release for the colormath installation because I was in a rush and I don't really know what I'm doing. Thanks for helping out @mbargull!

**Comment by khourhin** [comment]
I just had a similar problem with multiqc 1.5:

>pkg_resources.ContextualVersionConflict: (decorator 4.0.11 (/pasteur/homes/ekornobi/anaconda3/lib/python3.6/site-packages), Requirement.parse('decorator>=4.1.0'), {'networkx'})`

Updating 'decorator' fixed the issue:

`conda update decorator`

**Comment by cokelaer** [comment]
I had similar issues. 

>ContextualVersionConflict: (networkx 1.11 (/home/cokelaer/miniconda3/envs/py3/lib/python3.5/site-
  packages), Requirement.parse('networkx>=2.0'), {'colormath'})

Updating *networkx* partially fixed the problem. 

```   
conda update networkx
Fetching package metadata .................
Solving package specifications: .
The following packages will be UPDATED:

networkx: 2.0-py35_1         conda-forge --> 2.1-py_1     conda-forge

The following packages will be DOWNGRADED:

multiqc:  1.6-py35h24bf2e0_0 bioconda    --> 1.0-py35_4   bioconda   
spectra:  0.0.11-py_0        conda-forge --> 0.0.7-py35_0 conda-forge
```
Note that here multiqc was downgraded to 1.0 (I realised afterwards). Then I still got a similar error:

>VersionConflict: (spectra 0.0.7 (/home/cokelaer/miniconda3/envs/py3/lib/python3.5/site-packages), 
    Requirement.parse('spectra>=0.0.10'))

So, I install *spectra* again:
```
conda install spectra

The following packages will be UPDATED:

spectra:  0.0.7-py35_0 conda-forge --> 0.0.11-py_0 conda-forge

The following packages will be DOWNGRADED:

networkx: 2.1-py_1     conda-forge --> 2.0-py35_1  conda-forge
```
Then, I updated multiqc to the latest version (1.6). 

    conda install multiqc

And, then everything seems to work fine
