### ISSUE TITLE
Nominating @mbargull to become a core team member

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#7293]
Hi all and especially @bioconda/core!

I would like to nominate @mbargull to become a Bioconda core team member. He has contributed TO more then 40 PRs, but more importantly he has contributed to the build-infrastructure, to upstream conda, is helping in conda-forge and Bioconda to a tremendous degree! I can not remember any recent PR where @mbargull was not involved.

This would mean @mbargull as a core member can add new people to the organisation, can migrate/remove packages from the channel and hot-fix things if needed with admin privileges. I honestly think he deserves this level of trust! He has my :+1: :)

We do not have an official procedure for this but I would like to think that this proposal gets accepted if we do not get a :-1:  with a good explanation and if all @bioconda/core members votes with :+1: 

So please vote! :)

**Comment by bgruening** [comment]
:+1:

**Comment by chapmanb** [comment]
+1 -- Marcel, thank you for all the contributions.

**Comment by jerowe** [comment]
+1 !

**Comment by druvus** [comment]
+1

**Comment by rvalieris** [comment]
:+1:

**Comment by johanneskoester** [comment]
Absolutely, this is a very good idea.

**Comment by tomkinsc** [comment]
👍

**Comment by daler** [comment]
Yes! @mbargull has been doing amazing things.

**Comment by mbargull** [comment]
Thanks to everyone for being so kind, much appreciated. And I will gladly return the compliments: It has already been really pleasant working/interacting with you guys!

**Comment by bgruening** [comment]
This is a clear vote! Welcome @mbargull to @bioconda/core!
