### ISSUE TITLE
kobas run-kobas is missing in recipe

### ISSUE THREAD

**Issue by afust** [bioconda/bioconda-recipes#7297]
in kobas there is a "run-kobas" script/entry point but this is missing in the recipe. 
The problem seems to be in the package.patch file [package.patch file](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/kobas/package.patchl). There is an entry point but the function is missing compared to `annotate `and `identify `in the top. 
Thus, there is no functionality for this. Can anyone help me with this?

We tried to solve this in #7123 but some checks are still failing.

Thanks, Annika

**Comment by bgruening** [comment]
@afust can you check the the newest version. I just merged your PR. Sorry for the delay.
