### ISSUE TITLE
Time for Circle-CI?

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#7312]
Hi all!

Travis is still not recovering and I'm wondering if we really need to build Linux builds on travis. Maybe it is time to move on and build Linux builds on Circle-CI. From my experience Circle-CI is super fast on conda-forge.

What do you think @bioconda/build-system @bioconda/core?

**Comment by johanneskoester** [comment]
We still would have to wait on the osx builds on travis though. Hence, I would think there is too little benefit to justify the additional work of maintaining two CIs. Maybe we should give travis a last chance? Maybe they will make some changes that improve the situation in the future after this disaster.

**Comment by johanneskoester** [comment]
Thinking about it: if we manage to get osx builds on Circle CI, a move would of course be a good idea. What about the following: once the bioconda paper is published, we approach them whether they want to sponsor us or at least give us a discount? Until then, we try to be happy with Travis?

**Comment by johanneskoester** [comment]
Nah, I can't wait. I am asking them now.

**Comment by jerowe** [comment]
I'm not sure how much of an concern this is, but the bioconda-utils would have to be updated to reflect the environmental variables changing from Travis to Circle.

**Comment by johanneskoester** [comment]
I am now working on the migration. Watch out for a PR.

**Comment by bgruening** [comment]
Lol, this was just meant as a discussion :)
In principle I'm also happy with Travis, but it might be time to try other things. Thanks for taking the lead here Johannes!

**Comment by daler** [comment]
@johanneskoester thank you for your impatience ;) Supporting multiple CI services should make bioconda-utils more general, too. I'm curious to see how CircleCI works out, thanks for working on this.

**Comment by johanneskoester** [comment]
You're welcome! You can see the progress [here](https://github.com/bioconda/bioconda-recipes/commits/circleci). It has definitely some nice advantages in terms of flexibility. The speed is just awesome. This seems to be really promising.

**Comment by bgruening** [comment]
Jupp, the speed is just impressive!

**Comment by mbargull** [comment]
Nice work! Glad you didn't ponder over it and just asked them so fast 😄

There were to things I wanted to check
1. Does their (container-based) systems support `sudo` uses? AFAIC, for Travis CI you can't use `sudo` in containers.
   =>  Turns out, no problem with `sudo` for CircleCI, so the `sudo` in our startup scripts should be fine.
2. Speed for Linux builds is great on CircleCI, but what can we expect for OSX builds? http://traviscistatus.com/ shows absolute numbers on concurrent jobs and backlog size. https://status.circleci.com/ doesn't give that detailed information.
   => Didn't find any concrete numbers on that by a quick search, but at least found measurements from another user that recently switched from Travis to CircleCI: https://hackernoon.com/why-xod-switched-from-travis-to-circle-ci-98b6832f2d96#1b7e.

Looks very promising thus far!

**Comment by johanneskoester** [comment]
@mbargull seems that macos and linux have almost similar speed in circleci, see #7329. For now, I use VMs for both linux and macos, so there is no docker issue. However, I am indeed checking whether we will be able to run within docker containers. mulled might be a problem there, but I have found evidence that circleci allows "docker in docker". I will see if that works.

**Comment by mbargull** [comment]
> macos and linux have almost similar speed in circleci

Nice!

> However, I am indeed checking whether we will be able to run within docker containers. mulled might be a problem there, but I have found evidence that circleci allows "docker in docker". I will see if that works.

Ah, right, we also want to run Docker/`mulled` ourself; forgot about that again. If CircleCI already has support for that in place, that'd be nice. Otherwise, one has to make sure they actually want to [run Docker-in-Docker or not](http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/#the-solution).

**Comment by epruesse** [comment]
CirlceCI has three "executor" types `docker`, `machine` and `macos`, where `machine` runs as root on a full VM. At least with the 2.0 API they do have support to `[...] build Docker images for deploying elsewhere or for further testing [...]` via [RemoteDocker]( https://circleci.com/docs/2.0/building-docker-images/).

@johanneskoester Do you think you can maintain compatibility for both CI systems?

I realize that it's probably extra work (both CI providers have unique features not offered by the other, the caching works differently, etc) but I can see a few reasons for having that option. One is of course the classic heuristic for options (hardcode as long as there are no choices, expect many choices once there are two options). The flexibility of going back, or to a third provider, in the event of congestion, downtime, policy changes etc, or if we just run out of minutes on CircleCI, would be great. The "backup CI provider" could also potentially serve as an independent pipeline for batch PRs. And then there might be people using the bioconda toolchain for other (say beta testing) channels, and CircleCI normally charges for minutes on the MacOS executor.

**Comment by johanneskoester** [comment]
Yes, we can keep the old travis config around. @bgruening wanted to take care of that.

**Comment by johanneskoester** [comment]
In fact, as I understood from my personal conversation, the MacOS builds are free for all open source projects on circleci. They just have to ask and it is not officially announced.

**Comment by johanneskoester** [comment]
Quick update:
CircleCI has told me today, that we should not worry about the build times. They are flexible in this regard for OSS projects, and they will approach us if problems arise. So, no sudden shutdown because we reach a limit or so.

**Comment by peterjc** [comment]
We could probably close this issue since the switch from TravisCI to CircleCI is live.

However, I wanted to note that the macOS builds currently do not run the tool's tests.

Specifically they omit the ``--docker --mulled-test`` arguments, cross reference #5891 which may be relevant?

**Comment by epruesse** [comment]
@peterc Docker on macOS just runs a VirtualBox with Linux in it, so there is no point in running them from the macOS build. (Running them from macOS developer systems is useful to do a complete test, including Linux).

**Comment by peterjc** [comment]
Thanks @epruesse.

If you have any input for doing BioConda packaging on macOS and running the tests, please do comment over on https://github.com/bioconda/bioconda-recipes/issues/5891 

But from a CircleCI point of view, this is working as intended on macOS then. Can we close this issue?

**Comment by bgruening** [comment]
Thanks @johanneskoester :)
