### ISSUE TITLE
Metapackage versions

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#733]
I noticed that we already have a couple of metapackages in Bioconda. My question is, what is their purpose, and how should we version them?

**Comment by daler** [comment]
Some packages like hubward and metaseq rely on non-Python tools like UCSC utils and bedtools that users may already have installed. If they don't already have them installed, the respective metapackage will set everything up. It's much more convenient to say "install the metapackage" than to describe how to download and install each individual moving part.

Another possible reason is for aggregating tools of a specific type. One example we had talked about before was a metapackage for all bigBed-related tools from UCSC.

In the end, they are more about convenience. As for versioning, I'm not sure. A UCSC bigBed-related metapackage should have the same version as all the UCSC utils included in the package, but it's not clear what to use for a metapackage tying together disparate tools.

**Comment by johanneskoester** [comment]
Ok, that makes a lot of sense. Exactly, metapackages that just represent a collection of arbitrary tools should maybe have their own versioning. We could recommend semantic versioning, starting from 1.0.0.

**Comment by daler** [comment]
Sounds good. I'll do a round of docs updates, including metapackage versioning and notes about building with perl-threading.

**Comment by johanneskoester** [comment]
Great, thanks!

**Comment by johanneskoester** [comment]
Maybe the guidelines should be GUIDELINES.md instead? Similar to README.md and so on...

**Comment by daler** [comment]
Yep, good point
