### ISSUE TITLE
Issue with .so on htslib

### ISSUE THREAD

**Issue by tiagoantao** [bioconda/bioconda-recipes#7330]
There is something fishy with the symbolic links for shared libraries with htslib, check this:

```bash
$ ls -l libhts.*
-rw-rw-r-- 2 root root 1113820 Oct 24 23:49 libhts.a
lrwxrwxrwx 1 root root      13 Jan 21 17:19 libhts.so -> libhts.so.1.6
-rw-rw-r-- 2 root root  857726 Oct 24 23:49 libhts.so.1.6
lrwxrwxrwx 1 root root      13 Jan 21 17:19 libhts.so.2 -> libhts.so.1.6
```

Note that we have `libhts.so.2 -> libhts.so.1.6`  Notice the so.**2** instead of so.1

I noticed this because if you install angsd (which depends on htslib) it raises the error with regards to library version.

**Comment by mbargull** [comment]
Looks like this works as intended: https://github.com/samtools/htslib/commit/f10f9b2748bdf5828c6025360237d89ced643f6c.
Likely, the recipe for `angsd` just needs to have `htslib` pinned. That could be done while also updating it to a newer release (https://github.com/ANGSD/angsd/releases).

**Comment by bgruening** [comment]
I pinned htslib in bulk for angsd.

**Comment by bgruening** [comment]
@tiagoantao is this solved for you?

**Comment by tiagoantao** [comment]
I solved this with a hack. I will assume this is solved...
