### ISSUE TITLE
Adding sierrapy, a program that would be easily installed with pip

### ISSUE THREAD

**Issue by ozagordi** [bioconda/bioconda-recipes#7332]
Hi.
I would like to contribute the package [SierraPy](https://github.com/hivdb/sierra-client/tree/master/python), mainly because I would like to use it in my own tool (MinVar). SierraPy is installed with pip, so I tried `conda skeleton pypi sierrapy` and the following `conda build` or `./simulate-travis.py`. They both fail as one requirement is another pypi package, gql. If I try to install gql it fails because it needs graphql-core, also on pipy, which needs rx (again, on pypi). I guess that these would all go into conda-forge and not bioconda. But am I really supposed to contribute these into conda-forge before being able to install SierraPy?

Thanks.

**Comment by daler** [comment]
@ozagordi it looks like `graphql-core` v1.1 is [available on conda-forge](https://anaconda.org/conda-forge/graphql-core), but `gql` is not. So yes, you would need to add `gql` to conda-forge.

Back in the early days, we often had to add multiple layers of dependencies just to get one package in the channel! Luckily, these days many packages are available on bioconda or conda-forge. Unfortunately here it looks like gql is an exception.

Also I see that `sierra-client` [needs click](https://github.com/hivdb/sierra-client/blob/master/python/requirements.txt), so you will want to use the extended image as documented [here](https://bioconda.github.io/troubleshooting.html#using-the-extended-image) when making the recipe for bioconda.

**Comment by ozagordi** [comment]
Ok, thanks for the explanation! I hadn't noticed that click required a special treatment. I'm now trying to add `gql` to conda-forge, but I'm still failing.

Thanks again!
