### ISSUE TITLE
R can't find certain bioconductor packages installed through bioconda

### ISSUE THREAD

**Issue by jma1991** [bioconda/bioconda-recipes#7337]
I have a fresh install of miniconda / bioconda and have tried installing "bioconductor-txdb.mmusculus.ucsc.mm10.knowngene". The install completes but when I run R and try to load the relevant package I get the following error:

```
> library("TxDb.Mmusculus.UCSC.mm10.knownGene")
Error in library("TxDb.Mmusculus.UCSC.mm10.knownGene") :
  there is no package called ‘TxDb.Mmusculus.UCSC.mm10.knownGene’
```

The same happens for a few other packages, such as "bioconductor-bsgenome.mmusculus.ucsc.mm10". Other packages such as "bioconductor-deseq2" install and will load, but produce another error:

```
Error: package or namespace load failed for ‘GenomeInfoDb’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘GenomeInfoDbData’
Error: package ‘GenomeInfoDb’ could not be loaded
```
The GenomeInfoDb package is listed as installed by conda. I tried re-installing the dependency and I still get the error.

My current conda install is:
```
Current conda install:

               platform : linux-64
          conda version : 4.3.32
       conda is private : False
      conda-env version : 4.3.32
    conda-build version : not installed
         python version : 3.6.4.final.0
       requests version : 2.18.4
       root environment : /home/s1437643/conda  (writable)
    default environment : /home/s1437643/conda
       envs directories : /home/s1437643/conda/envs
                          /home/s1437643/.conda/envs
          package cache : /home/s1437643/conda/pkgs
                          /home/s1437643/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/s1437643/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.32 requests/2.18.4 CPython/3.6.4 Linux/2.6.32-642.6.2.el6.x86_64 CentOS/6.9 glibc/2.12
                UID:GID : 1427536:1612586
```

**Comment by daler** [comment]
@jma1991 I just tested it with the following and it worked for me:

```bash
conda create -n bioc -y bioconductor-txdb.mmusculus.ucsc.mm10.knowngene
source activate bioc
Rscript -e "library(TxDb.Mmusculus.UCSC.mm10.knownGene)"
```

Do you have `$R_HOME` or `$R_LIBS` set? Over in https://github.com/bioconda/bioconda-utils/pull/231 we came to the conclusion that specifying the library location (as done [here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-txdb.mmusculus.ucsc.mm10.knowngene/post-link.sh#L43)) would let us ignore `$R_HOME` or `$R_LIBS`, but maybe that doesn't hold true.

To help troubleshoot, what's the output of the following?

```bash
Rscript -e ".libPaths()"
```

**Comment by jma1991** [comment]
Neither $R_HOME or $_LIBS are set and the output from the command is: "/home/s1437643/conda/lib/R/library"

I seemed to have fixed the issue by specifying the R channel in my .condarc file. Originally I had removed it because conda was not able to resolve package specifications (I think because of the overlap between the conda-forge and r channels). With the r channel available and a fresh environment I no longer get any problems.

**Comment by daler** [comment]
The test I did was actually with the default R channel removed (which I had done for the reason you state). Specifically,

```
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
``` 

Maybe some sort of local caching issue? I guess we can close for now, but please re-open if it happens again.

**Comment by adomingues** [comment]
Hi @daler ,

I am seeing a very similar issue to the originally described. Basically, installation of packages ` bioconductor-ensdb.*` works fine, but when loading in R:

```R
> [1] "/lustre/projects/conda/users/domingue/envs/test_ens/lib/R/library"
> Error in library("EnsDb.Mmusculus.v79") : 
>   there is no package called ‘EnsDb.Mmusculus.v79’
> Execution halted
```
The package is installed by conda, in $CONDA_PKGS_DIRS, but not linked/copied to the R library (`/lustre/projects/conda/users/domingue/envs/test_ens/lib/R/library`). I managed to narrow it down the issue to a few key things:

- it happens only in the lustre filesystem
- it happens only with `EnsDb` packages (test with GViz and GeneOverlap were successful)
- is conda specific since installing those packages with cluster wide R installation was successful. 

I hope this helps to debug and let me know if you need a reproducible example.

Cheers.

**Comment by adomingues** [comment]
Just add some more information, this in our slurm system we get a warning which does not happen when installing elsewhere:

```
conda install -c bioconda bioconductor-ensdb.hsapiens.v86
(..)
Executing transaction: | WARNING conda.core.link:run_script(1165): pre-unlink script failed for package bioconda::bioconductor-ensdb.hsapiens.v86-2.99.0-r36_3
consider notifying the package maintainer
```

I don't know if this is related but it could be useful information anyway.
