### ISSUE TITLE
Deprecating the tabulate package

### ISSUE THREAD

**Issue by cbrueffer** [bioconda/bioconda-recipes#7339]
```conda install tabulate``` results in an old bioconda tabulate package (```tabulate-0.7.5-py36_0.tar.bz2```) to be installed, instead of the current conda-forge one. The 0.7.5 version we ship in bioconda is also available on conda-forge, so I think ours can safely be marked broken.

Edit: the bioconda tabulate recipe was removed in favour of the conda-forge one a while ago.

**Comment by cbrueffer** [comment]
Ping @daler

**Comment by daler** [comment]
Done, thanks!
