### ISSUE TITLE
Question about the conflict of current zlib pinning with newer Python  

### ISSUE THREAD

**Issue by ccwang002** [bioconda/bioconda-recipes#7350]
Currently zlib is pinned to version 1.2.8 while Python 3.6.3+ on conda-forge has been using zlib 1.2.11, so whenever a package pinning zlib is installed (say, cyvcf2), user will experience a downgrade of Python as well as a bunch of Python's dependencies. 

Is this downgrade intentional? If so, when will the zlib be updated and what's the plan to support newer Python release?

Thanks!

**Comment by daler** [comment]
@bgruening @johanneskoester should we bump zlib? I can babysit the travis-ci builds on the bulk branch for this.

**Comment by bgruening** [comment]
We should, I have started to work on this, but its slightly more work as we also need to increase all build-numbers of affected packages.

**Comment by daler** [comment]
Thanks. Do you have a PR going that I could help out on?

**Comment by daler** [comment]
```
$ find recipes -name "meta.yaml" | xargs grep -i -l zlib | wc -l
608
```
Phew, you're not kidding, it's a big job!

**Comment by ccwang002** [comment]
That's super fast. Thanks for your great work!

**Comment by daler** [comment]
Yikes, didn't mean to close that! This is an ongoing project and many of those 608 recipes will require hand-editing. It will take a while, unfortunately.

**Comment by bgruening** [comment]
@daler here you go: https://github.com/bioconda/bioconda-recipes/pull/7385

**Comment by rvalieris** [comment]
most of the recipes have been rebuilt with a newer zlib now (https://github.com/bioconda/bioconda-recipes/issues/7712), and python can be updated, so I will go ahead and close this.
