### ISSUE TITLE
maker and perl-moosex-app builds fail in nightly

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#7396]
@mbargull, could you please have a look at the two failures in our nightly build (see [here](https://circleci.com/gh/bioconda/bioconda-recipes/615)) and fix them? Seems to be (a) a problem with the tests that are executed and (b) a dependency issue. Thanks!

**Comment by mbargull** [comment]
Fixes (read: workarounds) are in #7408 and #7410.

**Comment by johanneskoester** [comment]
Thanks, closing as we can track the rest in those PRs.
