### ISSUE TITLE
simulate-travis.py

### ISSUE THREAD

**Issue by roryk** [bioconda/bioconda-recipes#7419]
Where did it go?

**Comment by roryk** [comment]
Oh I see, swapped over to a new CI system.

**Comment by philres** [comment]
Sorry for hijacking your thread, but I'm having the same problem. How did you solve it?

I cloned the repo but it does not have the `simulate-travis.py`

Thanks,
Philipp

**Comment by roryk** [comment]
Heya, I just ignored the local testing for now since the documentation isn't updated for the new CI. So I pushed to a forked repository, opened a pull request and let the CI handle the testing rather than doing it locally.

**Comment by mbargull** [comment]
duplicate of https://github.com/bioconda/bioconda-recipes/issues/7375.
