### ISSUE TITLE
Circle-CI hangs at ListTaskSignals

### ISSUE THREAD

**Issue by vinjana** [bioconda/bioconda-recipes#7478]
I'd like to check a build with circle CI and run
```bash
bioconda-recipes/ $ circleci build
```

After the curl download of .circleci/common.sh the procedure hangs:

```bash
...
====>> Download common definitions
  #!/bin/bash -eo pipefail
curl -s https://raw.githubusercontent.com/bioconda/bioconda-utils/master/.circleci/common.sh > .circleci/common.sh
DEBU[2018-01-31T14:08:05Z] Restarting ListTaskSignals stream            
INFO[2018-01-31T14:08:05Z] checking task signals                        
DEBU[2018-01-31T14:08:05Z] EOF in ListTaskSignals stream                
... <repeated>
```

Full output at [gist](https://gist.github.com/vinjana/6d7429fbfd4e0217d60d41f14e44222d).

Circle-CI is run on a cloud VM that has direct access to the outside without a proxy (at least no proxy needs to be specified explicitly.

Has anybody an idea, what may be wrong here?

**Comment by vinjana** [comment]
Hm. The default configs for docker + iptables were apparently to restrictive. Got it to run by dropping the firewall.

**Comment by kurko** [comment]
I have this problem. No firewall config restricting anything here.

**Comment by maysam** [comment]
> Hm. The default configs for docker + iptables were apparently to restrictive. Got it to run by dropping the firewall.

how?
