### ISSUE TITLE
I don't find the  simulate_travis.py

### ISSUE THREAD

**Issue by SilasK** [bioconda/bioconda-recipes#7550]
shouldn't it be at the top repo of the bioconda-recipes?

**Comment by daler** [comment]
Hi @SilasK, after moving to CircleCI, the local testing is now done with the CircleCI client. The new docs have more info on this: https://bioconda.github.io/contribute-a-recipe.html#test-locally

**Comment by SilasK** [comment]
OK, I just followed the documentation. and the CircleCI client was optional. 
So may be the doc need a slight update..

**Comment by khoegenauer** [comment]
Contributing docs still contain a reference to simulate-travis.py:

https://bioconda.github.io/contribute-a-recipe.html#build-an-isolated-conda-installation-with-dependencies

If needed, I can open a new issue in the bioconda-utils repo.

**Comment by mbargull** [comment]
@khoegenauer: https://github.com/bioconda/bioconda-utils/issues/269
