### ISSUE TITLE
name conflics between conda-forge and bioconda

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#7574]
Hi @bioconda/core,

any idea what we should do in a general way with these things?

https://github.com/conda-forge/staged-recipes/pull/5116

**Comment by jwkvam** [comment]
Sorry about that :( when I picked bowtie it was available on pypi ~2 years ago

**Comment by dougalsutherland** [comment]
Sorry, I didn't even think to check here before merging.

Should we maybe unpublish the bowtie conda-forge package and give it a different name? (And if so, have the linter check if a bioconda package already exists?)

cc @conda-forge/core

**Comment by bgruening** [comment]
@dougalsutherland @jwkvam thanks for dropping by here! Its not your fault and sooner or later such things will happen. We decided as a conda community to not prefix python packages, so this is unavoidable. A linter would be nice on both sides, we do have actually one in bioconda. But then we still need to solve the naming issue. Should we name it python-bowtie in this case?

Thanks again for be so supportive!

**Comment by jwkvam** [comment]
Yea, I would prefer "bowtie-py" since I also use that name with readthedocs. I'm not sure if I have the power to do this.

**Comment by dougalsutherland** [comment]
For renames you should send a PR with the new name to staged-recipes and someone from conda-forge/core needs to delete the old one.

**Comment by jwkvam** [comment]
Sounds good, I'll do that in a moment.

**Comment by bgruening** [comment]
New occurrence: https://github.com/conda-forge/staged-recipes/pull/5084
