### ISSUE TITLE
PackageNotFoundError when installing stacks

### ISSUE THREAD

**Issue by sven1990** [bioconda/bioconda-recipes#7609]
Hi, 
I'm trying to install stacks with "conda install -c bioconda stacks" but it does not find stacks.
I can install other packages so it is really just stacks that cannot be found and I have also tried to install it with the Anaconda Navigator but stacks does not show up in the list of available software within bioconda. 

Can anybody help?

Thanks

Sven

**Comment by bgruening** [comment]
Hi Sven,

please not that you will get the new stacks 2.0 if you install it like this. This version of stacks will have a ton of tools, like `cstacks`, `gstacks` and so on. Please read the manual about stacks 2.0 or install a 1.x version.

**Comment by sven1990** [comment]
Hi Björn (or anybody else who can help), 
thank you very much, but I already know that I should get stacks 2.0 when I install it like that. 
The problem is that neither stacks 2.0 nor any other version could be found.

This is what I get:

PackageNotFoundError: Packages missing in current channels:
            
  - stacks

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://conda.anaconda.org/r/osx-64
  - https://conda.anaconda.org/r/noarch

I hope somebody can help
