### ISSUE TITLE
Unresolvavle dependency error for libclang

### ISSUE THREAD

**Issue by rob-p** [bioconda/bioconda-recipes#7659]
Hi,

  A user of one of my packages (salmon) is having trouble installing the latest version, despite the fact that it built successfully and is up on the package repos (i am able to install the latest version).  The issue is described here (https://github.com/COMBINE-lab/salmon/issues/194#issuecomment-364941997).  The issue seems to be a dependency conflict.

**Comment by mbargull** [comment]
Looks like they have some other package installed that uses `libboost` from `defaults` which in turn demands `libcxx >=4.0.1`. But we have `libcxx` pinned to `4.0.0`. That situation might get better with `conda-build 3` and if we then use `{{ compiler("cxx") }}`, which should give us a compatible compiler/runtime deps. For now, can you create a pull request replacing the OSX-only build requirements at
https://github.com/bioconda/bioconda-recipes/blob/26c3e93d0d6171e4ee69791b73aef88567680882/recipes/salmon/meta.yaml#L28-L29
with `- clangxx_osx-64 4.0.1  # [osx]` and the run requirement at
https://github.com/bioconda/bioconda-recipes/blob/26c3e93d0d6171e4ee69791b73aef88567680882/recipes/salmon/meta.yaml#L42
with `- libcxx >=4.0.1  # [osx]`? This would emulate what `conda-build 3` with `compiler("cxx")` would give us. We should change that again once we completely switch to the new compilers.

**Comment by mbargull** [comment]
You could, of course, reuse the `llvm_version` variable and set that one to `4.0.1` and use
```yaml
- clangxx_osx-64 =={{ llvm_version }}  # [osx]
```
```yaml
- libcxx >={{ llvm_version }}  # [osx]
```

**Comment by TBradley27** [comment]
Hello,

I am not sure how helpful this additional information is, but I am seeing a similar problem on a linux machine:

`conda install -c bioconda salmon=0.9.1`

output:

```
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - salmon=0.9.1
  - boost=1.64
```

The highest version of salmon I can install is `0.8.1.`  Conda version is `4.5.3`

**Comment by bgruening** [comment]
Please use as much as you can `conda create -n salmon salmon=0.9.1`. This will give you a clean environment and not clash with other deps installed in another environment.
