### ISSUE TITLE
UnsatisfiableError: uropa is in conflict with itself (py36)

### ISSUE THREAD

**Issue by jenzopr** [bioconda/bioconda-recipes#7678]
Hi all,

I tried to install [uropa](https://bioconda.github.io/recipes/uropa/README.html) using a freshly installed miniconda3 with python3.6.

A call of `conda install -c bioconda uropa=2.0.2a0` resolves to
```
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - uropa 2.0.2a0*
Use "conda info <package>" to see the dependencies for each package.
```

However, uropa was build fine (it comes from [pypi](https://pypi.python.org/pypi/uropa/2.0.2a0)) in bioconda. Since we have a running py35 installation with uropa, I assume that some upstream dependencies fail. How can I check in detail the dependency chain that is resolved during the `conda install` call?

I can also provide the output of `conda install --debug -v -c bioconda uropa=2.0.2a0`.
Any help is welcome!

Best,
Jens

**Comment by mbargull** [comment]
Hi @jenzopr,

that's a bad and misleading error message from `conda`. For some reason it didn't put out an appropriate `PackageNotFoundError`. Please note that `bioconda` depends on packages from the `conda-forge` channel; see http://bioconda.github.io/#set-up-channels.
```bash
conda install -c bioconda -c conda-forge uropa=2.0.2a0
```
should work.

Cheers,
Marcel
