### ISSUE TITLE
Package Edlib: missing dependencies

### ISSUE THREAD

**Issue by Martinsos** [bioconda/bioconda-recipes#7694]
Hi,
first of all thank you for creating bioconda and including Edlib in it :)!
I am creator of [Edlib](https://github.com/Martinsos/edlib) and there is a recipe for it on bioconda (which I am not creator of).

Some of Edlib users reported that they are having problems installing Edlib on OSX, since gcc is required to build it and they don't have it, so it seems there is a problem of missing dependency: https://github.com/Martinsos/edlib/issues/102.

How can we fix this? Unfortunately I don't know much about conda or conda recipes, but I am happy to help anyway I can if you could provide some guidance.

Thanks!

**Comment by colinbrislawn** [comment]
Hello Martin,

I didn't write that recipe, but hopefully I get you started. The conda recipe for Edlib is over here:
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/edlib 

`build.sh` is the build process and [`meta.yaml`](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/edlib/meta.yaml) lists the requirements. 

Do you think this could be as simple as adding `gcc` back for OSX?

As @vmikk and @karel-brinda made this recipe, let's see what they suggest!

**Comment by Martinsos** [comment]
Hi @colinbrislawn, thank you for quick response!
Yes it seems like it, but I am guessing there might be a reason why it was excluded from OSX? Yes, let's hear what they have to say!

**Comment by mbargull** [comment]
xref https://github.com/Martinsos/edlib/issues/102#issuecomment-365854838.
I believe the original issue is not Conda/Bioconda related (was a `pip install`), so going to close this one. Please let me know if that's not the case.
Cheers

**Comment by Martinsos** [comment]
Thanks!
