### ISSUE TITLE
checkm_genome not working for py3

### ISSUE THREAD

**Issue by nick-youngblut** [bioconda/bioconda-recipes#7703]
`checkm-genome             1.0.7                    py35_0    bioconda` generates the following error when trying to run `checkm` or any of the `checkm` subcommands (eg., `checkm lineage_wf`):

```
$ checkm
  File "/ebio/abt3_projects/software/miniconda3/envs/genome_quality/bin/checkm", line 58
    print ''
           ^
SyntaxError: Missing parentheses in call to 'print'
```

`checkm` installs from bioconda by default with py3 but is not (fully) converted to py3.

**Comment by alienzj** [comment]
@nick-youngblut Hi, CheckM now working for py3.

**Comment by nick-youngblut** [comment]
Thanks @alienzj!
