### ISSUE TITLE
Help needed for some blacklisted packages

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#7712]
Hi 

we have rebuild more then 700 packages during the last week. Many of them to get build against a newer zlib version, but also for the new htslib.

It took me too long to fix all the old recipes and master was diverging to much, so I ended up to put the last packages on the [blacklist](https://github.com/bioconda/bioconda-recipes/blob/master/build-fail-blacklist). A few recipes do not detect the new zlib version, a few just failed to download source (rust-packages?) and so on.

There is something for every team I guess :)
@bioconda/core @bioconda/haskell @bioconda/perl @bioconda/lib @bioconda/rust 

Help welcome!
Thanks Bjoern

**Comment by dpryan79** [comment]
That was quite the herculean effort, well done! Should these be updated in a similar bulk branch or would more standard individual PRs suffice?

**Comment by bgruening** [comment]
Standard PRs would be nice, taking a few per PR out of the blacklist. Thanks @dpryan79!

**Comment by dlaehnemann** [comment]
For the rust recipes blacklisted, it seems like the following networking bug in `conda build` caused the error:
https://github.com/conda/conda-build/issues/2255

This might be relevant for other failures, e.g. the certificate validation errors -- but as I am not familiar with those recipse, so maybe someone else wants to chime in? I would take care of the rust recipes.

The suggested workaround (found [here](https://github.com/conda-forge/mosfit-feedstock/issues/23#issuecomment-349112622)) is to unset to bash variables, that seem to be set to empty values by conda build and cause the bug. So depending on whether the networking issue appears during building or during testing, the respective bash script needs to have the following two lines added before any networking might take place:
```
unset REQUESTS_CA_BUNDLE
unset SSL_CERT_FILE
```

**Comment by mbargull** [comment]
Yeah, we had this with a recipe for a Julia package recently,
https://github.com/conda-forge/julia-feedstock/issues/45#issuecomment-366396484:
> For posterity, this is the change I [added to `build.sh`](https://github.com/bioconda/bioconda-recipes/blob/68e8b620728059ebb75bf1366e225dd41df3902d/recipes/mentalist/0.1.3/build.sh#L3-L6):
>
```bash
# circumvent a bug in conda-build >=2.1.18,<3.0.10
# https://github.com/conda/conda-build/issues/2255
[[ -z $REQUESTS_CA_BUNDLE && ${REQUESTS_CA_BUNDLE+x} ]] && unset REQUESTS_CA_BUNDLE
[[ -z $SSL_CERT_FILE && ${SSL_CERT_FILE+x} ]] && unset SSL_CERT_FILE
```
When we update to `conda-build >=3.0.10`, we can remove those workarounds again.

**Comment by dlaehnemann** [comment]
OK, this looks safer -- if I read this correctly, you check whether the string is NULL with `-z` and whether it is set with `${VARIABLE+x}` (which returns non-NULL `x`, if the variable is set) and only then unset the variable. I guess I should use that and the version-specifics in the comments.

**Comment by bgruening** [comment]
We always need help to remove packages from the blacklist, but I will close this issue for now.
