### ISSUE TITLE
stacks dependency needs updating

### ISSUE THREAD

**Issue by tiagoantao** [bioconda/bioconda-recipes#7814]
Our stacks installation was failing:

```
process_shortreads: /vcore/software/conda/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by process_shortreads)
process_shortreads: /vcore/software/conda/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by process_shortreads)
process_shortreads: /vcore/software/conda/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by process_shortreads)
```

This was simple to solve  with a `conda install libgcc`:

`libgcc:       5.2.0-0          --> 7.2.0-h69d50b8_2`

Thus, it would be probably good to update the dependency on libgcc version?

**Comment by tiagoantao** [comment]
ping @bgruening @abretaud

**Comment by mbargull** [comment]
That would answer the question in https://github.com/bioconda/bioconda-recipes/pull/7531#issuecomment-363425282! I'll submit the fix for that, thanks for letting us now.
