### ISSUE TITLE
vcftools does not set PERL5LIB causing perl scripts to fail

### ISSUE THREAD

**Issue by lparsons** [bioconda/bioconda-recipes#7819]
The [vcftool documentation](https://vcftools.github.io/examples.html) states that `PERL5LIB` must be set so that the Perl scripts can find the Perl modules:
```
export PERL5LIB=/path/to/your/vcftools-directory/src/perl/
```

**Comment by bgruening** [comment]
@lparsons is this still an issue? If so please reopen.

**Comment by lparsons** [comment]
This does appear to remain an issue. In addition, I believe `make install` only makes the binary available in the path, while the other exectuables are in `vcftools/bin/` according to the docs: https://vcftools.github.io/examples.html.

**Comment by lparsons** [comment]
However, appears this is already "fixed" in an entirely different recipe: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/perl-vcftools-vcf
