### ISSUE TITLE
Perl6 in bioconda

### ISSUE THREAD

**Issue by mtw** [bioconda/bioconda-recipes#7869]
Hi
I was wondering whether anybody has looked into Rakudo (aka Perl6) support in bioconda. 

Given that the Perl6 specification is essentially a different language than Perl5, I guess a separate `perl6` package would make sense. If I understood it correctly this is in contrast to bioconda best practices, given that `python` and `R` only have one package (thanks @bgruening for pointing me there).

This needs a broader discussion in the perl community here. 

Looking forward to your thoughts.
Cheers,
Michael

**Comment by bgruening** [comment]
ping @bioconda/perl

**Comment by rvalieris** [comment]
Is there a perl6 bioinformatics related tool you are interested in using ? if so we could look into adding that tool to bioconda. but perl6 itself should go into conda-forge.

Yes I agree perl6 should go into a separated package, perl6 is completely different from perl, the name resemblance is just part of its history.

**Comment by bgruening** [comment]
ping @jakirkham, @msarahan, @tomkinsc

**Comment by bgruening** [comment]
I would frame this question a little bit more generic. How do we envision support for perl6 in conda.

* separate package, different name
* same package, with enhances build matrix similar to python, R ...

**Comment by msarahan** [comment]
It's much less about how do we envision support, and more about what features are required.

* Do packages support both?
* Are there compiled blobs specific to one or the other?  Python has .pyc files that are incompatible across versions, but there's also the C-level ABI.  I have no idea what perl has.
* For pure-perl, is there the notion of "noarch" - packages that will work with any perl version?

If perl6 is really a totally different language from 5, and there is no compatibility, it's easy.  You don't need a matrix.  You need to specify which perl version each perl package is written for.

Anaconda is happy to support this by answering questions you all might have, but we just simply don't use perl enough to take any sort of action on this ourselves.  We don't understand the system, and would not make the correct choices.

**Comment by rvalieris** [comment]
to to add a little more, perl x perl6 differs from python it the sense that perl6 is not backwards compatible in anyway to perl 5, and there is no expectation that perl 6 will replace perl on the future.

python 3 is the continuation of python 2, while perl 6 is new everything but the "spirit" of the language, and perl 5 continues to be developed independently.

it really is just a similar name, and multiple people have complained about it in the past, e.g. http://blogs.perl.org/users/vstemen/2017/10/perl6-should-be-renamed-perlplusplus.html

**Comment by mtw** [comment]
@rvalieris Not a specific tool. I've been playing with perl6 for some time now and currently porting some of my perl5 modules to perl6. Apart that there is [bioperl6](https://github.com/cjfields/bioperl6), which has some BioPerl functionality ported to Perl6.

**Comment by rvalieris** [comment]
@mtw thats alright, honestly I haven't been following perl6 at all lately, but if people find it useful to have these packages conda I don't see why not add them.

**Comment by jakirkham** [comment]
Normally when we have come to a tricky situation like this one in the past, we have looked at what other packagers do. So it would be good to take a look at at Homebrew, MacPorts, apt-get, yum, etc. to get some idea as to how they deal with Perl 5 and Perl 6.

**Comment by rvalieris** [comment]
everyone seems to ship it by the name of "rakudo" not perl6, thats the name of the implementation (http://rakudo.org). just like we have a "openjdk" package, but not a "java" package. 
we could say that rakudo "provides" perl6.

**Comment by mtw** [comment]
_Perl6_ is the **language specification**. _Rakudo_ is a compiler for Perl6. Hence fully agree with @rvalieris regradring naming conventions, i.e.`rakudo` [resp `rakudo-star` (see e.g [Homebrew](http://formulae.brew.sh/formula/rakudo-star)]

**Comment by rvalieris** [comment]
I made a conda recipe to show what it would look like but I got an error: https://gist.github.com/rvalieris/1146cfbd87e7af1f4c5622fb4f76e01e

probably something with how conda patches binary paths. I don't really understand the interaction between rakudo, moarvm and nqp to tell whats wrong.

**Comment by mtw** [comment]
I have added a PR with a recipe for [rakudo-star](https://github.com/conda-forge/staged-recipes/pull/5246) 2018.01 to conda-forge. It seems the same error reported by @rvalieris is triggered here after local installation via ``conda install --use-local rakudo-star``. Got suck here ...
```perl6 -V
Unhandled exception: Could not map file '/Users/mtw/miniconda3/share' into memory: FIXME
   at gen/moar/ModuleLoader.nqp:92  (/Users/mtw/miniconda3/share/nqp/lib/Perl6/ModuleLoader.moarvm:)
 from gen/moar/ModuleLoader.nqp:79  (/Users/mtw/miniconda3/share/nqp/lib/Perl6/ModuleLoader.moarvm:load_module)
 from <unknown>:1  (/Users/mtw/miniconda3/share/perl6/runtime/CORE.setting.moarvm:<dependencies+deserialize>)
 from gen/moar/ModuleLoader.nqp:257  (/Users/mtw/miniconda3/share/nqp/lib/Perl6/ModuleLoader.moarvm:)
 from gen/moar/ModuleLoader.nqp:247  (/Users/mtw/miniconda3/share/nqp/lib/Perl6/ModuleLoader.moarvm:load_setting)
 from src/Perl6/World.nqp:741  (/Users/mtw/miniconda3/share/nqp/lib/Perl6/World.moarvm:load_setting)
 from src/Perl6/World.nqp:518  (/Users/mtw/miniconda3/share/nqp/lib/Perl6/World.moarvm:loading_and_symbol_setup)
 from src/Perl6/Grammar.nqp:1231  (/Users/mtw/miniconda3/share/nqp/lib/Perl6/Grammar.moarvm:comp_unit)
 from src/Perl6/Grammar.nqp:532  (/Users/mtw/miniconda3/share/nqp/lib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2330  (/Users/mtw/miniconda3/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1881  (/Users/mtw/miniconda3/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1797  (/Users/mtw/miniconda3/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:1830  (/Users/mtw/miniconda3/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:1833  (/Users/mtw/miniconda3/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1819  (/Users/mtw/miniconda3/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1519  (/Users/mtw/miniconda3/share/nqp/lib/NQPHLL.moarvm:eval)
 from src/Perl6/Compiler.nqp:67  (/Users/mtw/miniconda3/share/nqp/lib/Perl6/Compiler.moarvm:verbose-config)
 from gen/moar/stage2/NQPHLL.nqp:1631  (/Users/mtw/miniconda3/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:42  (/Users/mtw/miniconda3/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1625  (/Users/mtw/miniconda3/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/Users/mtw/miniconda3/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/Users/mtw/miniconda3/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/Users/mtw/miniconda3/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/Users/mtw/miniconda3/share/perl6/runtime/perl6.moarvm:<entry>)

**Comment by rvalieris** [comment]
yeah, I opened a issue on rakudo about this https://github.com/rakudo/rakudo/issues/1549, but nothing so far. better hold off the recipe for now.

**Comment by mtw** [comment]
Thanks @rvalieris. I've closed the PR on conda-forge for now.

**Comment by hermidalc** [comment]
I'm sure I'm not the first person to ask this, but why is everything Perl in bioconda?  Should everything except bio-related CPAN libs be in conda-forge and defaults channels?

**Comment by bgruening** [comment]
@hermidalc historical reasons. Bioconda is older than conda-forge and we initially hosted even the original perl package. That said we are planning since years to move the majority of your packages to conda-forge, but no one wants to do it. Any help appreciated. I somewhere have even a plan how to start, e.g. making sure we can create `noarch: generic` perl packages for a minor perl version.

**Comment by hermidalc** [comment]
> @hermidalc historical reasons. Bioconda is older than conda-forge and we initially hosted even the original perl package. That said we are planning since years to move the majority of your packages to conda-forge, but no one wants to do it. Any help appreciated. I somewhere have even a plan how to start, e.g. making sure we can create `noarch: generic` perl packages for a minor perl version.

My vote for Perl6 since it’s new would be to do everything in conda-forge and defaults.

**Comment by bgruening** [comment]
I will close this issue. Whatever we do with perl it should be in conda-forge. It would be amazing if a perl hero can commit to this work and push it forward.

Thanks all,
Bjoern
