### ISSUE TITLE
Package rnaQUAST

### ISSUE THREAD

**Issue by peterjc** [bioconda/bioconda-recipes#7965]
http://cab.spbu.ru/software/rnaquast/

As per http://cab.spbu.ru/files/rnaquast/release1.5.0/manual.html#sec2 to run rnaQUAST you need:

*    Python 2 (2.5 or higher)
*    matplotlib python package
*    joblib python package
*    gffutils python package (needs biopython)
*    NCBI BLAST+ (blastn)
*    GMAP (or BLAT) aligner

These are all available as conda packages, so this ought not to be too hard.

**Comment by colinbrislawn** [comment]
This now exists!
https://anaconda.org/bioconda/rnaquast
