### ISSUE TITLE
Problems installing Gubbins using conda

### ISSUE THREAD

**Issue by DolapoA** [bioconda/bioconda-recipes#7987]
**I am having problems installing a program called Gubbins (https://github.com/sanger-pathogens/gubbins/blob/master/INSTALL.md).**

I have executed the following commands:**
conda config --add channels r
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
conda install gubbins

**...to which I'm met with the error:**
conda install gubbins
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - asn1crypto
  - gubbins
Use "conda info <package>" to see the dependencies for each package.

**And then when I inquire I get:**

gubbins 2.3.1 py36_0

file name   : gubbins-2.3.1-py36_0.tar.bz2
name        : gubbins
version     : 2.3.1
build string: py36_0
build number: 0
channel     : https://conda.anaconda.org/bioconda/linux-64
size        : 88 KB
arch        : x86_64
constrains  : ()
license     : GPL-2.0
md5         : 9f41f0cab793b13abceb7fcd86f918cb
platform    : linux
subdir      : linux-64
url         : https://conda.anaconda.org/bioconda/linux-64/gubbins-2.3.1-py36_0.tar.bz2
dependencies:
    biopython >=1.59
    dendropy >=4.0.2
    fasttree
    libgcc
    nose >=1.3
    python 3.6*
    raxml
    reportlab >=3.0
    zlib 1.2.8*

**So I figured I need to download and install _zlib_ and _python 3.6_ as per asterix , but I've done that it still doesn't work. So I'm wondering if anyone has a solution?**

**Comment by andrewjpage** [comment]
I have tested this just now in a container with a blank install of miniconda 2/3. Gubbins is a python3 application and if you try to install it using python 2 (miniconda 2) it will give the above error.  More info here: https://conda.io/docs/user-guide/tasks/manage-python.html

**Comment by rvalieris** [comment]
you should be able to install gubbins 2.3.1-py36_1, the py36_0 package was built with zlib 1.2.8 and it conflicts with other packages that have zlib pinned on 1.2.11. the py36_1 package was built with 1.2.11.

**Comment by DolapoA** [comment]
@andrewjpage Thanks.
