### ISSUE TITLE
`circleci build` fails on `/tmp/repo/docker-entrypoint-source` when run locally

### ISSUE THREAD

**Issue by dlaehnemann** [bioconda/bioconda-recipes#8006]
After setting up circleci on my system as described in the Contribution guidelines, I could not get `circleci build` to run -- it errors with:
```
/tmp/.bash_env-localbuild-1519670009: line 4: /tmp/repo/docker-entrypoint-source: No such file or directory
```
I've tried removing all old Docker images and have reinstalled docker, to eliminate that as an error source, but am still not sure that this might not just be some odd local configuration of mine. However, if I revert the path change of [this commit](https://github.com/bioconda/bioconda-recipes/commit/7899e3b3c64b3918ee221c175ee3be1c3776f761) in the now two occurrences of the path in the following context, `circleci build` runs normally: 

https://github.com/bioconda/bioconda-recipes/blob/125077444ac6065c86edf598ab4b360a7ccd18ca/.circleci/config.yml#L63-L67

@mbargull (as the above mentioned commit is yours) and maybe others: Am I missing some obvious solution? Or is this indeed a bug?

For reference, the full log of `circleci build` up to the failure:

```
====>> Spin up Environment
Build-agent version 0.0.4704-deba4df (2018-02-21T21:01:29+0000)
Starting container bioconda/bioconda-utils-build-env
  using image bioconda/bioconda-utils-build-env@sha256:b9939c34493fdbf329bf9632059d39d914978ecb532d94a90d5f6426ddc94798

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1519670009
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=unblacklist_rust_recipes
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=https://github.com/bioconda/bioconda-recipes.git
  CIRCLE_SHA1=731acbf007dd134d2b5d5e0525db8ad393e53f7f
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1519670009
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/sh
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
====>> Setup ssh
  #!/bin/bash -eo pipefail
mkdir -p ~/.ssh
ssh-keyscan -H github.com >> ~/.ssh/known_hosts

# github.com SSH-2.0-libssh_0.7.0
====>> Setup base system
  #!/bin/bash -eo pipefail
cat >> $BASH_ENV <<EOF
if [[ \$- == *u* ]] ; then
    set +u ; . /tmp/repo/docker-entrypoint-source ; set -u
else
    . /tmp/repo/docker-entrypoint-source
fi
EOF

====>> Download common definitions
  #!/bin/bash -eo pipefail
curl -s https://raw.githubusercontent.com/bioconda/bioconda-common/master/common.sh > .circleci/common.sh
/tmp/.bash_env-localbuild-1519670009: line 4: /tmp/repo/docker-entrypoint-source: No such file or directory
====>> Setup bioconda-utils
  #!/bin/bash -eo pipefail
.circleci/setup.sh
/tmp/.bash_env-localbuild-1519670009: line 4: /tmp/repo/docker-entrypoint-source: No such file or directory
/tmp/.bash_env-localbuild-1519670009: line 4: /tmp/repo/docker-entrypoint-source: No such file or directory
/tmp/.bash_env-localbuild-1519670009: line 2: /tmp/repo/docker-entrypoint-source: No such file or directory
Error: Exited with code 1
Step failed
Task failed
```

**Comment by mbargull** [comment]
Can you try
```bash
docker pull bioconda/bioconda-utils-build-env
```
? The docs at http://bioconda.github.io/contribute-a-recipe.html#test-locally where just [recently updated](https://github.com/bioconda/bioconda-utils/pull/276) to mention this important step (thanks @daler!).

**Comment by dlaehnemann** [comment]
Ah, yes, now it works -- and I figured it had to be something simple like that, but had no clue and missed the docs update, as I had been working around the issue since last week...

Thanks @mbargull!

And back to other problems...

**Comment by mbargull** [comment]
> missed the docs update, as I had been working around the issue since last week...

Sorry for the troubles; I made the changes more than a week *before* the docs had been updated, my bad.

> And back to other problems...

Good luck! :wink:
