### ISSUE TITLE
svgwrite and msprime packages migrated to conda-forge

### ISSUE THREAD

**Issue by jeromekelleher** [bioconda/bioconda-recipes#8015]
I've migrated the svgwrite and msprime packages that I was maintaining here up to conda-forge, [here](https://github.com/conda-forge/svgwrite-feedstock) and [here](https://github.com/conda-forge/msprime-feedstock).

Would it be possible to archive the bioconda versions of these packages please? (I think this is the strategy for such packages?) Thanks.

In case anyone is wondering, the only reason I migrated msprime to conda-forge was for Windows support. Svgwrite is a more general dependency, and probably is more suitable for conda-forge anyway.

**Comment by bgruening** [comment]
@jeromekelleher in bioconda and conda-forge are not the same versions. So can we leave the packages in this channel and remove just the recipe? You could pin your packages then for some higher version than what is in bioconda to get the conda-forge version.

**Comment by jeromekelleher** [comment]
That sounds perfect, thanks @bgruening. Shall I go ahead and remove the recipes in a PR?

**Comment by bgruening** [comment]
Yes, please :)
Thanks!

**Comment by jeromekelleher** [comment]
Done; thanks @bgruening, keep up the great work!
