### ISSUE TITLE
Error installing BUSCO

### ISSUE THREAD

**Issue by fernandomoramarquez** [bioconda/bioconda-recipes#8135]
Hi Bioconda Team:

I installed the BUSCO package several times without any problem. But today I have tried to install BUSCO on my UBUNTU 16.04LTS computer again and the installation has printed the following message:

An error occurred while installing package 'defaults::gcc-4.8.5-7'.
LinkError: post-link script failed for package defaults::gcc-4.8.5-7

I attach a complete log file with the verbose option.

Any idea on how to solve it?

Thanks in advace.
[busco_error.txt](https://github.com/bioconda/bioconda-recipes/files/1775525/busco_error.txt)

**Comment by daler** [comment]
@fernandomoramarquez based on the log it doesn't look like you have `conda-forge` as a channel. Can you please follow the setup from https://bioconda.github.io/index.html#set-up-channels and then provide the output of `conda info`?
