### ISSUE TITLE
Environment modules

### ISSUE THREAD

**Issue by holtgrewe** [bioconda/bioconda-recipes#816]
Hi,

what is your opinion about [environment modules](https://github.com/hpcugent/easybuild)?

Environment modules are common in cluster environment for allowing concurrent installation of multiple version and activating and deactivating programs by modifying `$PATH` etc. Also, they allow to specify dependencies.

We are currently using [EasyBuild](https://github.com/hpcugent/easybuild) for automatizing our software installs (but jumping on the bioconda train would be nice as I guess the Bioinformatics community is larger here). One nice feature of EasyBuild is that it automatically generates environment module files. I think that bioconda would benefit greatly from this as well.

However, I do not know bioconda (or conda) well enough for estimating how easy/hard it would be to implement automatic generation of environment files.

For us, this is probably the largest road block towards adopting bioconda over EasyBuild.

Thanks,
Manuel

**Comment by johanneskoester** [comment]
If we are talking about the same thing, my impression was always that conda makes [environment modules](https://en.wikipedia.org/wiki/Environment_Modules_(software)) obsolete. It allows you to install any available software version, without admin rights into your home directory on your cluster. If you need multiple versions of the same software, you can use separate conda environments and activate them before execution (in fact, Snakemake will automate this approach in the future, by allowing to define requirements per rule, which are instantiated into separate environments and activated before rule execution).

**Comment by holtgrewe** [comment]
I have had a closer look at conda/bioconda now and there is a small, but relevant difference: environment modules allows you load modules in an ad hoc fashion. You can load and unload modules in trial-and-error fashion which makes it easy to use interactively. On the other hand, conda appears to force you to create an environment with a specific version of a program. Is this correct?

Anyway, it appears that environment module generation would be something to solve at the conda and not at the bioconda leve, I guess.

**Comment by johanneskoester** [comment]
Yes, that's true. They are less interactive in the sense of somehow being persistent instead of transient and interactive (which can be advantageous though). I think the behaviour you think about could maybe generated with some simple wrappers and aliases. But you are right, this is more a conda-level discussion.

**Comment by holtgrewe** [comment]
Closing in favour of #3708
