### ISSUE TITLE
can't install ceas in bioconda

### ISSUE THREAD

**Issue by sengoku93** [bioconda/bioconda-recipes#8160]
Hi,

I am unable to install ceas via conda/ bioconda. I have tried both: (conda install ceas) and (conda install -c bioconda ceas). Both result in failure to locate the package. Any advice would be appreciated. Thank you!

**Comment by rvalieris** [comment]
currently, the ceas package is only available on linux with python2.

if you are using linux, you can create a separated env for ceas like this:

`conda create -n ceas ceas`

**Comment by sengoku93** [comment]
Ah, makes sense. Thank you!
