### ISSUE TITLE
Clarifying contribution policies and patches

### ISSUE THREAD

**Issue by charlesreid1** [bioconda/bioconda-recipes#8183]
Hello,

I'm opening an issue to address a question that ultimately we did not have to answer, but that has come up since.

When bumping kaiju to the latest version #7213 we were fortunate enough to have a very responsive package maintainer who jumped into the conversation and worked with us to fix compilation errors in the upstream. Had we been less lucky, our PR might have ended up languishing and we would have opted to patch.

The patch policy does not seem consistent. Some patches are [standard changes](https://bioconda.github.io/troubleshooting.html#usr-bin-perl-or-usr-bin-python-not-found) for recipes (e.g., changing `#!/usr/bin/perl` to `#!/usr/bin/env perl`), while others are user-specific (e.g., patching a JSON file to add a database that a user is interested in adding). There isn't much guidance in place around when to patch and how in the [contributing](https://bioconda.github.io/contributing.html) doc, and some users may write a patch, fix an issue, but never notify the package maintainer.

I believe this can be addressed by imposing a requirement for contributors around patching and etiquette: if a PR adding or modifying a recipe contains a patch, there should also be a requirement that the person submitting the PR demonstrate they've made some attempt to fix the problem upstream, perhaps by linking to an upstream PR they submitted or mentioning they attempted to contact the developer or opened an issue.

(This could also help in letting package maintainers know their package is in bioconda, instead of the less pleasant experience of them discovering their package along with a stash of patches in a bioconda recipe...)

Thoughts?

**Comment by daler** [comment]
@charlesreid1 good points.

I don't think it would be useful to block a PR until upstream changes are fixed, but I do think it's reasonable to ask that upstream has been notified. @bioconda/core any opinions?

https://github.com/bioconda/bioconda-utils/pull/283 is an update of the contributing policy that reflects these suggestions.

**Comment by charlesreid1** [comment]
Excellent, thank you for making this into a PR.

> I don't think it would be useful to block a PR until upstream changes are fixed

Agreed - patches are necessary and it's unreasonable to expect every upstream maintainer to be responsive. I was thinking of a webhook mechanism - something looking for .patch files in a commit and posting a comment that perhaps tags the owner of the package repo, or asks "Are there any major changes that should be pushed to upstream?" etc. 

In any case, simply mentioning patches in the contributing document is a great improvement!

**Comment by bgruening** [comment]
Great discussion! Thanks for starting this @charlesreid1! Our docs have improved since then and conda-forge added also a lot to this ecosystem so we should be better here in 2019. Closing this out.
