### ISSUE TITLE
Requesting reviews as a new user is impossible

### ISSUE THREAD

**Issue by apeltzer** [bioconda/bioconda-recipes#8267]
Dear team, 

according to your documentation/contribution guidelines, users should be able to contribute by uploading a recipe and then requesting a review from @bioconda/core. unfortunately, as also listed here in GitHubs documentation, this is impossible without repository access:

https://help.github.com/articles/requesting-a-pull-request-review/

(see also the attached screenshot).

As I don't want to link one specific person of the core team all the time - is there a better way of letting people know that there is something new contributed without annoying people?

Also, this should probably be mentioned in the documentation - happy to do a pull request for that (with or without review ;-)). 

Cheers and thanks for your work,
Alex

![screenshot from 2018-03-15 21-12-06](https://user-images.githubusercontent.com/2359510/37488615-8c73b246-2895-11e8-8a84-23c32885f10d.png)

**Comment by apeltzer** [comment]
I'm talking about this section here specifically: https://bioconda.github.io/contrib-setup.html#request-to-be-added-to-the-bioconda-team-optional

@bgruening @johanneskoester @jerowe @chapmanb  (I think thats enough to get your attention on this thing)

**Comment by daler** [comment]
@apeltzer thanks for pointing this out. A PR on the docs to describe this would be great. They are built from the bioconda-utils repo, in the [`docs/source`](https://github.com/bioconda/bioconda-utils/tree/master/docs/source) directory.

**Comment by apeltzer** [comment]
I'll update this and send a PR for that soon - and will cc in here, too.

**Comment by johanneskoester** [comment]
@apeltzer you might not be able to request a review via the github buttons, but you can always put a mention to `@bioconda/core` into your PR message.

**Comment by apeltzer** [comment]
Really? (see screenshot) above, as long as I'm not part of the bioconda organization, I wasn't able to do that unfortunately... :-/

**Comment by johanneskoester** [comment]
Good to know. But does that also mean that you cannot mention them by just writing this out? Maybe just the completion does not work?

**Comment by apeltzer** [comment]
Exactly - neither typing it directly not copying this from a readme did work...

**Comment by johanneskoester** [comment]
Ok, I see. That is sad. PR for the docs is very welcome, thanks for pointing this out!

**Comment by apeltzer** [comment]
PR is out ;-)
