### ISSUE TITLE
bioconductor R package dependencies in Docker containers

### ISSUE THREAD

**Issue by ewels** [bioconda/bioconda-recipes#8341]
Question ported from [gitter](https://gitter.im/bioconda/Lobby?at=5ab296cebb1018b37a0dce63):

I'm trying to build a Docker container using bioconda, but I think I must be missing something with the bioconductor R packages... See my [`Dockerfile`](https://github.com/ewels/NGI-RNAseq/blob/35225f4703577a694f3db7a8ac7ce16c26d11c75/Dockerfile) and [`
environment.yml`](https://github.com/ewels/NGI-RNAseq/blob/a015a08c71e0927fe8995ecf8f74948f7979bc36/environment.yml).

It builds fine, but then when I try to run using the dupRadar bioconductor package I get this:

```
Loading required package: dupRadar
Loading required package: parallel
Error in loadNamespace(name) : there is no package called ‘KernSmooth’
Calls: duprateExpDensPlot ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

I get similar errors for edgeR - basically none of the R dependencies seem to be present in the container.

Can anyone spot what I'm missing? When I install the conda environment locally on my Mac it seems to work fine..

**Comment by apeltzer** [comment]
I'll link @bioconda/core to this. Checked whether KernSmooth is a different package, but that should be  in base-R actually.

**Comment by apeltzer** [comment]
I'm not sure if this is a lead on whats going on, but e.g. the dupRadar script sets some paths in the `meta.yaml`, [check this out](https://github.com/bioconda/bioconda-recipes/blob/f42598f031654703eb56562ab6e304c5c39b482f/recipes/bioconductor-dupradar/meta.yaml#L16).

I'm running a local testcase whether e.g. including these paths in the PATH variable fixes these issues, as it looks like it just can't find the required R libraries `KernSmooth` at that point.

**Comment by apeltzer** [comment]
Okay, seems like that could be an issue here, yes:

```
Singularity testpath:~/testSingularity> which R
/opt/conda/envs/ngi-rnaseq/bin/R
Singularity testpath:~/testSingularity> R

R version 3.4.1 (2017-06-30) -- "Single Candle"
(skipped some unrequired parts) 

> library("KernSmooth")
Error in library("KernSmooth") : there is no package called ‘KernSmooth’

> print(.libPaths())
[1] "/home/alex/R/x86_64-pc-linux-gnu-library/3.4"
[2] "/opt/conda/envs/ngi-rnaseq/lib/R/library"    
> library('KernSmooth')
Error in library("KernSmooth") : there is no package called ‘KernSmooth’
```
What first jumps in my face is, that the `libPaths()` are loaded in the order host first, then conda environment. That could also explain why you Phil didn't have the issue, maybe because you were able to load the locally installed edgeR/dupRadar package.

**Comment by daler** [comment]
@ewels it looks like kernsmooth is a hidden dependency of dupRadar, only loaded in `duprateExpDensPlot`.  KernSmooth is in the `recommended` package, not the `base`, https://stackoverflow.com/a/9705725. At some point (not sure if this is on conda's end or on CRAN's end) recommended are no longer included. 

One option would be to add `r-kernsmooth` to the `bioconductor-dupradar` (I'll take care of this);  temporarily you could add it to your env yaml. Alternatively you could try adding `r-recommended` to your env.yaml though that seems a bit heavier.

Here's how I reproduced (locally, no need for docker):

```bash
conda create -n dupradar bioconductor-dupradar
source activate dupradar
Rscript -e 'library(dupRadar); attach(dupRadar_examples); duprateExpDensPlot(dm)'
```

installing `r-kernsmooth` fixed it:

```bash
conda install r-kernsmooth
Rscript -e 'library(dupRadar); attach(dupRadar_examples); duprateExpDensPlot(dm)'
```

Adding `r-kernsmooth` to the env yaml and building the Docker container seems to make it work.

In both cases however `Rscript -e 'library(limma)'` worked. Do you have a example of how limma fails trying to import something?

**Comment by ewels** [comment]
Brilliant - thanks both! @daler - after adding `r-kernsmooth` to the list of requirements, dupRadar now seems to be working 👍 

For the second error, it turns out that it wasn't the `edgeR` package that was causing problems but rather two other dependencies that I had in the same script (`data.table` and `gplots`). I tried adding these to the conda env file and I _think_ it's working now!

Super cool, thanks for your investigations! I was worried that there was something bigger going on, but the dream of the conda env file + minimal Dockerfile lives on! ✨ 

Phil

**Comment by ssayols** [comment]
Hi all,
dupRadar maintainer here. Thank you for reporting the issue.

I added `KernSmooth` as an `IMPORT` in `DESCRIPTION` for Bioconductor release (3.15). Should be available sometime tomorrow. For the next Bioconductor release, proper `roxygen` `@import` tags have been added.

Please reopen the issue if the problem persists.

cheers,
Sergi
