### ISSUE TITLE
notice about recipes built by conda skeleton (especially Python packages)

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#8366]
Hi @bioconda/all - 

While we are moving toward using conda-build 3, our infrastructure is still using the older conda-build 2. This has been causing some issues recently, as the `meta.yaml` files created by conda-build-3's `conda skeleton` are incompatible with conda-build 2.

This seems to primarily be an issue with Python packages. For details and the (easy) fix, please see the updated docs at https://bioconda.github.io/guidelines.html#python.

**Comment by lparsons** [comment]
Slight typo in the docs:

> We are moving towards supporting conda-build-3 which has many nice features we can take advantage of. In the meantime, however, we need to use *conda-build 3*.

Should be "... we need to use *conda-build-2*".

**Comment by bgruening** [comment]
I think this can be closed.
