### ISSUE TITLE
mothur depends on readline v7

### ISSUE THREAD

**Issue by tiagoantao** [bioconda/bioconda-recipes#8375]
Mothur depends on readline 7, If one has readline 6 on the conda environment, a link problem will occur.

The workaround is simply a `conda install readline` to update readline, but I suspect the best thing is to update the mothur package to reflect the dependency

**Comment by apeltzer** [comment]
Most likely not a problem anymore - cb3 has readline == 7.0

**Comment by colinbrislawn** [comment]
Is this still an issue or can we safely close it?
