### ISSUE TITLE
Suggestions for how to troubleshoot failed OSX travis builds w/o local OSX?

### ISSUE THREAD

**Issue by xguse** [bioconda/bioconda-recipes#838]
Hello y'all

I run Linux. But some of the packages I build are for coworkers who need OSX versions.  In the past I have pushed a few PRs that included additions to the OSX white-list and luckily they built beautifully.

However a couple of my colleagues will need an r package that has a pretty large number of deps.  I wrote and tested all the recipes using the docker build container and they work great.  But they keep failing the OSX portion of the build checks.

The travis system is of course not really set up to be used for troubleshooting and the checks are long.  Does anyone have any hints as to how I might speed up the process?  Am I just going to have to find some OSX box someone might lend me time on to run the checks every time one of them needs something thats not in the built channels already?

Thanks!

**Comment by zachcp** [comment]
The only thing I can think of is if theres a way to generate the DAG of dependencies and cross reference that against the OSX whitelist. That should be doable without OSX and can let you know what other packages you will need to add to the whitelist in order for your package to build.

**Comment by lomereiter** [comment]
I tried this kind of remote debugging once—it's downright unproductive; I ended up using https://github.com/AndrewDryga/vagrant-box-osx for testing purposes.

**Comment by daler** [comment]
If it helps -- if only to narrow down which dependencies need to be added to `osx-whitelist` -- `scripts/toposort_recipes.py` does what @zachcp mentioned.

**Comment by xguse** [comment]
@daler: very good to know.  Thanks. I will probably focus on that approach from now on.

**Comment by epruesse** [comment]
outdated
