### ISSUE TITLE
anvio recipe doesn't specify diamond version

### ISSUE THREAD

**Issue by nick-youngblut** [bioconda/bioconda-recipes#8380]
The [anvio recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/anvio/meta.yaml) currently doesn't specify a version for diamond. This can lead to two different 'anvio' conda environments:

1. `conda update anvio` will still use old `diamond` version
1. `conda create -n anvio_env -c bioconda anvio` will use newest version of `diamond` 

Since different versions of `diamond` require different database formats, this can lead to errors like the following:

```
Config Error: Pfft. Something probably went wrong with Diamond's 'blastp' since one of the
              expected output files are missing. Please check the log file here:
              '/tmp/global2/nyoungblut/LLMGA_33004609329/log.txt.
```

... when running `anvi-run-ncbi-cogs`

**Comment by bgruening** [comment]
To some degree, this is how conda should work. If anvio is not restricted to a particular version the recipe should not pin an arbitrary version. Instead, you can create an environment and pin your dependencies down. An other idea would be to have these diamond databases in a versioned directory ... all of that is nothing we can solve in conda I'm afraid.
