### ISSUE TITLE
ggplot 2.0

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#839]
I want to add ggplot2 to bio-conda. The ggplot package is in the conda official repo and I have updated the recipe but its taking a bit of time to make its way to the Anaconda website. On the assumption that forgiveness is better than permission I am going to package ggplot2  here and we can remove it when it lands in the conda repo.

Thanks,
 zach cp

**Comment by druvus** [comment]
ggplot2 is now included in bioconda so I am closing.
