### ISSUE TITLE
r-rcppgsl does not specify an R version

### ISSUE THREAD

**Issue by jdblischak** [bioconda/bioconda-recipes#8423]
I was surprised that r-rcppgsl 0.3.1 from the bioconda channel was installed preferentially instead of r-rcppgsl 0.3.3 from the conda-forge channel. I suspect this is because the bioconda package does not specify the version of R. Could the package linux-64/r-rcppgsl-0.3.1-0.tar.bz2 be marked as broken so that it does not get installed over newer versions of r-rcppgsl?

https://anaconda.org/bioconda/r-rcppgsl/files

**Comment by bgruening** [comment]
Done. We do build against specific R version in the same way that conda-forge is doing it. So hopefully this will not happen again.
