### ISSUE TITLE
I received ~20 notifications emails in the last two days, how to stop them?

### ISSUE THREAD

**Issue by davidechicco** [bioconda/bioconda-recipes#8454]
Hi

Sorry to disturb anyone, but I've been receiving around 20 emails yesterday and today about any update on any recipe of bioconda. I would like to not receive these emails anymore; what should I do?

My settings are already set to "Not watching", but I still receive all these emails nonetheless.
I would like to receive emails only about my BEHST recipe and anytime someone mentions me.

Thanks

-- Davide

**Comment by peterjc** [comment]
My guess is something was changed on the team/group setting?I recently got an unexpected email from GitHub titled:

"Subscribed to bioconda/bioconda-recipes notifications"

I went to https://github.com/bioconda/bioconda-recipes/subscription to change it back to "Not watching" which is probably what you want to do too.
