### ISSUE TITLE
Shovill needs ncurses installed for samtools

### ISSUE THREAD

**Issue by peterk87** [bioconda/bioconda-recipes#8482]
I get the following error when trying to run shovill installed into its own conda env:

```
Checking for assembly errors in contigs.fasta
Running: bwa index contigs.fasta >> 70-bwa.log 2>&1
Running: (bwa mem -v 3 -x intractg -t 1 contigs.fasta R1.fq.gz R2.fq.gz | samtools sort --threads 1 -m 2G --reference contigs.fasta -T /tmp/samtools.10616 -o shovill.bam) >> 70-bwa.log 2>&1
Error 32512 running command
```

Running [samtools](https://github.com/bioconda/bioconda-recipes/blob/9af68bd9e7b5cf311eb2804134d74386f91b305f/recipes/shovill/meta.yaml#L33) installed into the shovill conda env, I get:

```
samtools: error while loading shared libraries: libtinfow.so.5: cannot open shared object file: No such file or directory
```

Workaround is to install ncurses from conda-forge:
```
$ source activate /path/to/shovill-conda-env
$ conda install -c conda-forge ncurses
```

**Comment by tseemann** [comment]
This is not a `shovill` problem - it's a `samtools` issue.
In your env can you run `ldd $(which samtools)` ?

`libtinfo` is part of `ncurses`. Does the conda recipe deploy all the libs?
On dists you need the `ncurses-dev[el]` packages.

**Comment by bgruening** [comment]
You probably have a wrong channel order. Make sure conda-forge has a higher priority than defaults.

**Comment by peterk87** [comment]
Thanks @tseemann and @bgruening! The issue occurred in a Galaxy Docker container and on a Galaxy VM. No such issues were encountered when installing and running `shovill` locally on Ubuntu 16.04.4 LTS through Conda. I'll ensure the proper order of Conda channels in my VMs and Docker containers. Thanks!

**Comment by tseemann** [comment]
@bgruening danke for the simple solution :)

**Comment by bede** [comment]
Relieved to find this after being bitten by the same issue!
