### ISSUE TITLE
ssh publickey error when trying to run local circleci build

### ISSUE THREAD

**Issue by tesujimath** [bioconda/bioconda-recipes#8524]
I'm trying to test a new recipe, running circleci build locally.  The setup bioconda-utils step fails with this:
```
$ circleci build
<snip>
====>> Setup bioconda-utils
  #!/bin/bash -eo pipefail
.circleci/setup.sh
remote: Counting objects: 34, done.        
remote: Compressing objects: 100% (12/12), done.        
remote: Total 34 (delta 19), reused 33 (delta 19), pack-reused 0        
Unpacking objects: 100% (34/34), done.
From https://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__arcftucilt/master
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
<snip>
```

There are some other errors, but this is the first.  Any hints on what's wrong?  I have my own tesujimath ssh private key for my GitHub account loaded up in ssh-agent.  Does my public key need to be installed somewhere?  Where?

**Comment by bgruening** [comment]
@tesujimath are you on your own master branch? If so try to avoid this :)

**Comment by tesujimath** [comment]
@bgruening I'm on a feature branch which only exists locally in my clone of my fork of bioconda-recipes. What repo is circleci trying to access? The upstream bioconda-recipes? Why is it using ssh rather than https?

Sorry, I'm a bit new at circleci.

**Comment by tesujimath** [comment]
Well, I'm concluding this ssh permission problem is a red herring, since the circleci build continues past it.  My adventure continues in #8530.
