### ISSUE TITLE
Contributing a Bioconductor package - currently on the devel branch only

### ISSUE THREAD

**Issue by federicomarini** [bioconda/bioconda-recipes#8527]
Hi,

I am trying to wrap up a bioconda recipe for our newest Bioconductor package, `iSEE` (http://bioconductor.org/packages/devel/bioc/html/iSEE.html), but I am facing the issue with the skeleton builder that the package is not found on the release branch - which, matter of facts, is correct, as it is not yet been released.

What is the procedure in such cases? Should I just wait and sit tight for the couple of weeks that will be required? 

To plan ahead, I checked that most of the dependencies are already there, and if I found some to be unsatisfied yet, I'd probably put all of them in the same PR. Is this recommended?

Cheers,
Federico

**Comment by federicomarini** [comment]
Hi Ryan - thanks for the reply.
As of now we are still adding a couple of fixes, and more importantly, we do rely on package versions that are on the devel branch, i.e. some functions are not there yet on the release branch, and I guess neither are there in the bioconda packages. So probably the best solution would be to keep everything ready when the release itself takes place.

For the dependencies, I checked and it seems only one is missing, and it is another Bioc pkg, so they will probably go hand in hand with the main submitted package.

I'll keep up to date with the current/future practices so that the recipe-release runs as smooth as possible.
Federico

**Comment by federicomarini** [comment]
Hi @daler , picking up on the open issue now that R and bio got the newest release.

I did prepare the recipes for `scRNAseq` and `iSEE`, and was testing them with circleCI locally. I am getting errors since it is trying to build on the version 3.4.1 of R, while `iSEE` requires >=3.5.0.

Is it possible to pass this to the circleCI client somehow?

**Comment by federicomarini** [comment]
(I was also trying to setup the bootstrap too, but it takes quite a long time and nothing happens (~40 min) after `./bootstrap.py /tmp/miniconda`) -> there I can ideally < use `--R 3.5.0`

**Comment by daler** [comment]
@federicomarini while R 3.5.0 itself is released, getting a conda-forge R 3.5.0 package will take some time and then updating the thousands of packages in conda-forge and bioconda R 3.5.0 is quite a large job that we will be tackling in the near future.

We are also in the middle of migrating to conda-build-3, which changes how things are pinned (which includes the pinned R version).

Best I can say now is to please wait a bit more, sorry!

As for the bootstrap script taking a long time, I just tested it locally and it finished in under 2 minutes. Sometimes conda has connectivity issues, might just need to try again.

**Comment by federicomarini** [comment]
No problem Ryan, time is on our side ;)

... and about bootstrap, I kept trying (work, home) and still stays pretty stuck (`top` says a `tr` process sucks 100% of a core, but does not proceed further). I made sure I got the latest updates, but maybe something else is conflicting?
F

**Comment by federicomarini** [comment]
Following up on that...
It might be a problem with the macOS system-wide version of python.

```
$ which python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python
$ ./bootstrap.py /tmp/miniconda
```
-> that does not work

```
$ ~/miniconda3/bin/python bootstrap.py /tmp/miniconda
```
-> this one does. 

Not strictly related to the recipe, but "should I remove the system-wide python"? I ask because the python ecosystem is for me not as familiar as R.
(Funny enough, xkcd seems to peek in my issues recently - https://xkcd.com/1987/)

**Comment by daler** [comment]
@federicomarini the bootstrap script is designed to work with whatever version of python you have kicking around, so the macOS py27 should (theoretically!) be fine. Most of the work is being done when it calls out to the [`.circleci/setup.sh` script](https://github.com/bioconda/bioconda-recipes/blob/master/.circleci/setup.sh). You mention a stuck `tr` process, maybe it's [this line](https://github.com/bioconda/bioconda-recipes/blob/master/.circleci/setup.sh#L20) that's causing the hangup? That's unrelated to Python version though, so I don't yet understand why the hangup would be Python-version-dependent.

No reason to remove your system-wide Python. Though to make things easier you may want to consider adding `~/miniconda3/bin` to the beginning of your PATH variable so you're always using the conda version (that's what I typically do on both mac and linux).

**Comment by bgruening** [comment]
This is now to a large part automatised. So with every new BioC release we will get the packages as well, and containers.
