### ISSUE TITLE
Why does pysam have samtools and bcftools as dependencies?

### ISSUE THREAD

**Issue by garrettjstevens** [bioconda/bioconda-recipes#8528]
Hi all,

I'm wondering why `pysam` has `samtools` and `bcftools` as build and run dependencies? https://github.com/bioconda/bioconda-recipes/blob/c8734a4c9697f8ab6d5a06aff54f901bd3ce1945/recipes/pysam/meta.yaml#L21-L41

I know that `pysam` is built against `htslib`, so that requirement makes sense, but the `samtools` and `bcftools` functionality that `pysam` has is contained in the `pysam` code itself, completely separate from any installation on the system (see https://github.com/pysam-developers/pysam/issues/653).

Is there a reason I'm not understanding why they are required?

**Comment by kyleabeauchamp** [comment]
If we're positive that there are no edge cases that will occur by de-coupling them, then we can de-couple them.  cc @AndreasHeger

**Comment by garrett-stevens** [comment]
I can see what you mean about avoiding confusion. I'd argue, though, that perhaps it sometimes creates confusion as well. By installing samtools and bcftools along with pysam, it's almost implies that it's using those. If folks had to explicitly install samtools and bcftools, though, that would imply that they were separate and shouldn't be expected to be the same.

It's good to know, though, that I can force pull in a new version of e.g. bcftools into a testing environment to try out new features and it won't mess up pysam. Maybe a comment in the `meta.yaml` or something explaining this would be appropriate?

**Comment by kyleabeauchamp** [comment]
I'll add some notes in the meta.yaml when I upgrade pysam.

**Comment by marcelm** [comment]
The current pysam recipe no longer has samtools or bcftools as dependency.
