### ISSUE TITLE
CircleCI does not detect any modified recipe

### ISSUE THREAD

**Issue by ntraut** [bioconda/bioconda-recipes#8549]
Hello,
I am having trouble with docker circle. I am trying to modify a recipe to add osx support. I have followed all the step in https://bioconda.github.io/contribute-a-recipe.html and above. I tested my modifications with `conda-build recipes/my-recipe` and it worked. But before making a pull request I wanted to be sure that my modifications did not damage the build for linux.

So I tried to test with Docker. I ran:
```
# Ensure the build container is up-to-date
docker pull bioconda/bioconda-utils-build-env

# Run the build locally
circleci build
```

It said me that no recipe was modified:
```
====>> Spin up Environment
Build-agent version 0.0.4812-e4f6fcc (2018-04-03T01:38:26+0000)
Starting container bioconda/bioconda-utils-build-env
  using image bioconda/bioconda-utils-build-env@sha256:dcc5d4f999f83679363885dba64e716d6c036866a48d7fb05a7676308bbbae3f

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1523020099
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=master
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=https://github.com/ntraut/bioconda-recipes
  CIRCLE_SHA1=edf379c6dc938cdcbf5de1c057f0e091af506e58
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1523020099
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/sh
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
====>> Setup ssh
  #!/bin/bash -eo pipefail
mkdir -p ~/.ssh
ssh-keyscan -H github.com >> ~/.ssh/known_hosts

# github.com SSH-2.0-libssh_0.7.0
====>> Setup base system
  #!/bin/bash -eo pipefail
cat >> $BASH_ENV <<EOF
if [[ \$- == *u* ]] ; then
    set +u ; . /tmp/repo/docker-entrypoint-source ; set -u
else
    . /tmp/repo/docker-entrypoint-source
fi
EOF

====>> Download common definitions
  #!/bin/bash -eo pipefail
curl -s https://raw.githubusercontent.com/bioconda/bioconda-common/master/common.sh > .circleci/common.sh
====>> Setup bioconda-utils
  #!/bin/bash -eo pipefail
.circleci/setup.sh
From https://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__qespousrxx/master
fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository
====>> Linting
  #!/bin/bash -eo pipefail
bioconda-utils lint recipes config.yml --git-range master HEAD
13:08:57 BIOCONDA INFO Recipes newly unblacklisted:

13:08:57 BIOCONDA INFO No recipe modified according to git, exiting.
====>> Testing
  #!/bin/bash -eo pipefail
bioconda-utils build recipes config.yml --git-range master HEAD
13:08:58 BIOCONDA INFO Recipes newly unblacklisted:

13:08:58 BIOCONDA INFO No recipe modified according to git, exiting.
Success!
```

I tried to commit my changes and push them to my fork which is not written as necessary in the guidelines, but I ran into the same issue.

I am sure I have missed something but I don't see what, can you help to find it out?

**Comment by daler** [comment]
@ntraut couple of things. You may have to bump the build number to get the recipe to build. But more importantly, the Circle CI client builds within a docker container, so it's actually testing just the linux side of things and ignoring anything with MacOS.

I've just added some new functionality to test this (xref https://github.com/bioconda/bioconda-utils/pull/291 and #8537). Can you grab the latest from master branch, and try:

```bash
$ ./bootstrap.py /tmp/miniconda
$ source activate ~/.config/bioconda/activate
(BIOCONDA-UTILS) $ bioconda-utils build recipes config.yml --git-range master
(BIOCONDA-UTILS) $ source deactivate
```

**Comment by ntraut** [comment]
> You may have to bump the build number to get the recipe to build

I incremented the build number by 1.
> $ ./bootstrap.py /tmp/miniconda

I had to replace `tempfile` by `mktemp` in `.circleci/setup.sh: line 6` to make the command working.
> (BIOCONDA-UTILS) $ bioconda-utils build recipes config.yml --git-range master

I got `BIOCONDA INFO BUILD SUMMARY: successfully built 1 of 1 recipes` so it worked :)
> source deactivate

`circleci build` still did not detect anything new.

Thanks for your help!

**Comment by daler** [comment]
Ah, thanks, that change is relatively new and I didn't know about `mktemp` for MacOS. I'll change that. Glad it worked with that change.

I suspect the reason `circleci build` didn't pick it up is because it's configured by default to use `--git-range master HEAD` (see [this line](https://github.com/bioconda/bioconda-recipes/blob/master/.circleci/config.yml#L79)), which needs a file to be either staged or committed to be detected as changed. I suspect if you were to edit `.circleci/config.yml` to just use `--git-range master` (to mimic the bioconda-utils command that worked, and which also detects unstaged edits) it would pick up the change.

**Comment by ntraut** [comment]
It worked when just using `--git-range master`. But what I don't understand is even after adding the modified recipe into the index, it didn't detect it using `--git-range master HEAD`.

**Comment by daler** [comment]
@ntraut actually not sure either. I may be misremembering  . . . it may have to be committed, not just staged.

**Comment by nathanweeks** [comment]
`./bootstrap.py /tmp/miniconda` is also failing for me on CentOS 7.4 due to the `tempfile` command missing.

`mktemp` is part of GNU coreutils, and is available on stock RHEL/CentOS 7.x and Ubuntu 16.04 LTS---perhaps that should be preferred over `tempfile`?

**Comment by daler** [comment]
Thanks @nathanweeks, added in #8625
