### ISSUE TITLE
The GSL version?

### ISSUE THREAD

**Issue by molpopgen** [bioconda/bioconda-recipes#8613]
The build environment defines CONDA_GSL, which I believe is still 1.16.  Upstream (conda-forge) is at the current GSL version,  2.4.  The 2.x series has quite a bit to offer in terms of new features.  In fact, the reason I'm posting this question is because a feature I'd really like to use is in 2.2.1.

The question is: can we change CONDA_GSL to a more recent version?

The hiccup is that 2.0 is ABI incompatible with 1.16, due to a bugfix.  I acknowledge that problem.  But it seems worth it to have the default version of such a high-quality library be from the current decade :).

@bioconda/core

**Comment by bgruening** [comment]
Yes, worth to update I think especially to stay in sync with conda-forge.
Could you bump the version number in our config to the version conda-forge is using. Ideally test it locally and create a PR targeting the bulk branch. We can then merge it into bulk and try to fix errors.

**Comment by molpopgen** [comment]
Happy to do this, or at least make an attempt--where do I look to do this?  I'm only familiar with the recipes repo, and not at all with the core utils.

**Comment by bgruening** [comment]
https://github.com/bioconda/bioconda-recipes/blob/master/scripts/env_matrix.yml#L11
Bump it and lets hope not so many recipes break :)

Thanks!

**Comment by daler** [comment]
Closing, as #8622 is merged.
