### ISSUE TITLE
RSeQC exit codes

### ISSUE THREAD

**Issue by rasmusagren** [bioconda/bioconda-recipes#8620]
RSeQC contains a bunch of Python scripts that always exit with 0, regardless of whether there has been an error. This causes problems in my workflow with partially written files that aren't detected as faulty. Would it be ok to patch that in the recipe? It's not exactly a bug or related to installing, but it's annoying. I've also written the developers and asked for a fix.

**Comment by bgruening** [comment]
If you have created a PR upstream and contacted the author, I don't think we mind a patch. But please let people review it before merging.

**Comment by rasmusagren** [comment]
It's on Sourceforge so I can't make a PR. I'll be sure to ask for reviews.

**Comment by daler** [comment]
@rasmusagren if you have contacted the authors and have a patch for the bioconda recipe, a PR here is more than welcome. Closing this issue for now.
