### ISSUE TITLE
How to bump Perl Set::IntervalTree version?

### ISSUE THREAD

**Issue by micknudsen** [bioconda/bioconda-recipes#8656]
Hi,

I would like to update the recipe for `Perl Set::IntervalTree` to the newest version (0.11), because the most recent version in bioconda is causing troubles for me in `star-fusion` (see https://github.com/STAR-Fusion/STAR-Fusion/issues/58).

However, I have not been able to locate a `tar.gz` archive in the same location as the currect bioconda version:

https://github.com/bioconda/bioconda-recipes/blob/2b11025dbae7011edf19a807ba5d86589dce9172/recipes/perl-set-intervaltree/meta.yaml#L5-L7

I know very little about Perl (nothing, actually), so I may simply be looking in the wrong place. Any ideas how to update?

Thanks!

**Comment by rvalieris** [comment]
closing this, since the issue was resolved.
