### ISSUE TITLE
OpenMS missing dependencies

### ISSUE THREAD

**Issue by bernt-matthias** [bioconda/bioconda-recipes#8697]
In order to plot with MetaProSIP some additional dependencies seem to be necessary: 

- libxrender
- cairo
- libsm
- libice

In addition fonts should be installed (but I don't know which) -- but currently I only get a box drawn for each character in the generated plots.

**Comment by bgruening** [comment]
@bernt-matthias do you have a test which we can use?

**Comment by bernt-matthias** [comment]
You could use the call generated by the Galaxy tools test: 

`MetaProSIP  -in_mzML MetaProSIP_1_input.mzML -in_fasta MetaProSIP_1_input.fasta -out_csv out.csv -out_peptide_centric_csv out-pep.csv -in_featureXML MetaProSIP_1_input.featureXML -mz_tolerance_ppm 10.0 -rt_tolerance_s 30.0 -intensity_threshold 10.0 -correlation_threshold 0.7 -xic_threshold 0.7 -decomposition_threshold 0.7 -weight_merge_window 5.0 -plot_extension png -qc_output_directory plots/ -labeling_element C`

the input files are here: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/openms/test-data

Maybe also 
- xorg-libxext
- xorg-libxt

are necessary.

**Comment by bernt-matthias** [comment]
fonts problem was solved locally after our admins installed: 

dejavu-sans-fonts-2.33-1.el6.noarch
ghostscript-fonts-5.50-23.2.el6.noarch
liberation-fonts-common-1.05.1.20090721-5.el6.noarch
liberation-sans-fonts-1.05.1.20090721-5.el6.noarch
urw-fonts-2.4-11.el6.noarch

(CentOS 6)

**Comment by bernt-matthias** [comment]
seems solved in https://github.com/bioconda/bioconda-recipes/pull/19989
