### ISSUE TITLE
circlator caused UnsatisfiableError

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#8709]
Hi @druvus, @peterjc, @mbargull, @bgruening and @asntech, 
I got the following error:
```
conda create --name circlator circlator
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - circlator -> bio_assembly_refinement >=0.4.0 -> pyfastaq >=3.10.0 -> python 3.6*
  - python 2.7*
Use "conda info <package>" to see the dependencies for each package.
```
What did I miss?

Thank you in advance.

Michal

**Comment by druvus** [comment]
Circlator is only compatible with Python 3 so it should pick up Python 2.7. Do you have Python 2.7 in your Rooth environment?

**Comment by mictadlo** [comment]
Yes, my miniconda installation is based on python2. In order to prevent it tried to install circlator in a separated conda environment but then I got the above error.

**Comment by mictadlo** [comment]
I fixed the problem with `conda create --name circlator python==3.6 circlator`
