### ISSUE TITLE
restart failed nightly builds?

### ISSUE THREAD

**Issue by dlaehnemann** [bioconda/bioconda-recipes#8728]
@bioconda/build-system 

I have just seen that [a recipe I have merged in last night](https://github.com/bioconda/bioconda-recipes/pull/8725) signals a circleci failure of the nightly build. I am not sure what exactly that means, as the regular package upload did work and the package is available. Also, I think the only reason it fails was some kind of networking issue (`HTTP 404 NOT FOUND` on some bioconductor url: https://circleci.com/gh/bioconda/bioconda-recipes/8560). So I guess there are two questions:

1) Does it matter that this nightly build failed?
2) If so, is there a way to rerun the nightly build (e.g. just restarting the circleci jobs?)?

**Comment by daler** [comment]
@dlaehnemann it's OK that they fail; packages are primarily built right upon being merged so the nightly builds are more of a routine linting process. And don't worry, this had nothing to do with your PR!
