### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [bioconda/bioconda-recipes#8743]
Hello Sir. I'm a UI/UX and Graphics Designer. I want provide a logo for you. Would you mind if I propose a new logo design for your application as my Open Source Contribution?

Thanks before.

**Comment by daler** [comment]
@anharismail thanks, our logo is at https://github.com/bioconda/bioconda-recipes/tree/master/logo; if you'd like to propose changes you're more than welcome. Best way to do that would be to open a PR with the proposed changes.
