### ISSUE TITLE
Time for recipe to be available in repository

### ISSUE THREAD

**Issue by frubino** [bioconda/bioconda-recipes#8744]
Hi,

I updated the `mgkit` package a few days ago and the pull request was successful. However, I still can't see the package updated in the bioconda repository. In general, how long does it for the package to be available?

I have my own enviroment, the issue is mostly for users that are required to work under conda.

Thanks

**Comment by jenzopr** [comment]
Hi @frubino 
the package / your changes will be available in the bioconda repository after a member of bioconda organization has merged your PR into the master branch. Since no member is a *fulltime* bioconda'er, this might take a while. Once it has been merged, the new version should be available within hours.

Best,
Jens

**Comment by daler** [comment]
@frubino it looks like mgkit is on the blacklist: https://github.com/bioconda/bioconda-recipes/blob/master/sorted-r-blacklist#L5.

This means that the build system will ignore it, which you can see in the tests, e.g., https://circleci.com/gh/bioconda/bioconda-recipes/8424 says "nothing to be done".

The solution is to open a new PR where `mgkit` is removed from the blacklist. You may also need to make a minor change to the recipe (a small whitespace edit, for example) for the build system to pick it up.

I will have bioconda-utils emit a big warning when it encounters a changed recipe that is also on the blacklist to avoid this kind of thing in the future.

**Comment by frubino** [comment]
Thanks, I made a pull request #8745 to incorporate changes.

**Comment by daler** [comment]
Closing as #8745 is merged.
