### ISSUE TITLE
Gviz rtracklayer ideogramtrack

### ISSUE THREAD

**Issue by mrlmachado** [bioconda/bioconda-recipes#8766]
I found myself now without any ideas for solving what I faced in my local galaxy server. I'm runing version 18.01 of galaxy with nginx and interactive environment enabled and I build a tool with Gviz package dependency resolving by conda. Galaxy resolve all dependencies correctly but when I call IdeogramTrack function from R it throws a Bad Request 400 Error only within galaxy environment. If I execute from the server with Rscript, my code runs perfectly. I tried disable GIE and enable debug level of logs from nginx and wsgi but no success to find what is causing this error. I know this function call ucsc uri to download hg tables, but it works from the very server where galaxy is running and within galaxy it does not work. I really need help here to understand what is happening and how can I solve this out.

**Comment by bgruening** [comment]
We are tracking this elsewhere.
