### ISSUE TITLE
Package update request: IQ-TREE 1.5.5 to 1.6.3

### ISSUE THREAD

**Issue by xvazquezc** [bioconda/bioconda-recipes#8770]
Hi there,

I've been trying to update the recipe for IQ-TREE, but I had no luck (barely starting with this...). Either I'm not doing something right or it could be that it requires `gcc >= 5.0` as suggested in [this issue at the IQ-TREE repo](https://github.com/Cibiv/IQ-TREE/issues/60), in which case I'm completely lost

Any help would be appreciated.

Cheers,
Xabi

**Comment by johanneskoester** [comment]
We will move to conda build 3 very soon, which will give us newer compilers. Hopefully this will fix your issue. Let's keep this open until bioconda/bioconda-utils#293 is merged.
