### ISSUE TITLE
wigEncode comes from which recipes?

### ISSUE THREAD

**Issue by alienzj** [bioconda/bioconda-recipes#8836]
Hello,
when I use archlinux, I can search which package a command comes from, for example:
`pacman -Qo gcc`
it will tell me:
`/usr/bin/gcc belong to  gcc 7.3.1+20180406-1`
so, how can I quickly know which recipes **ucsc-*** **wigEncode** comes from?

[wigEncode code](https://github.com/ENCODE-DCC/kentUtils/blob/master/src/hg/makeDb/hgLoadWiggle/wigEncode.c)

Please help me!
Thanks very much!

**Comment by daler** [comment]
@alienzj I don't believe there is such a tool for finding particular executable names across all conda packages. As you found, bioconda maintains (most) UCSC tools with a `ucsc-` prefix followed by an all-lowercase name.

However, it appears that `wigEncode` has not been built on bioconda (`conda info ucsc-wigencode` does not return any results). I suspect there's something different about that particular program that causes it to be missed by our [ucsc-tool-packaging code](https://github.com/bioconda/bioconda-recipes/tree/master/scripts/ucsc).

We will be rebuilding all of these tools in the near future as we move to conda-build 3, but I will see if there's something obvious that can be done to get v357 of wigEncode built.

**Comment by alienzj** [comment]
Thanks very much!
