### ISSUE TITLE
bootstrap.py fails due to no Docker access

### ISSUE THREAD

**Issue by nick-youngblut** [bioconda/bioconda-recipes#8863]
I'm following the instructions for contributing as described at https://bioconda.github.io/contribute-a-recipe.html. The documentation states:

> **If you do not have access to Docker**, you can still run the basic test by excluding the --docker and --mulled-test arguments in the last command:

I do not have access to Docker on my machine (no admin rights for installing it; the admin won't install it). I tried running `./bootstrap.py /tmp/miniconda` with my miniconda install, and I got the following error:

```
$ ./bootstrap.py  /tmp/miniconda
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/bioconda/bioconda-recipes
 * [new branch]      master     -> __upstream__gfkqtcuvwh/master
.circleci/setup.sh: line 33: docker: command not found
Traceback (most recent call last):
  File "./bootstrap.py", line 96, in <module>
    sp.check_call(['.circleci/setup.sh'], env=env)
  File "/tmp/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.circleci/setup.sh']' returned non-zero exit status 127. 
```

So, it appears that I actually must have Docker installed, correct? Maybe I'm just confused by the error.

**Comment by daler** [comment]
@nick-youngblut you're right, there's a line in the setup that does use docker. I'll add a fix so that you can set it up without needing docker. It'll probably be additional arg, like `bootstrap.py --no-docker /tmp/miniconda`.

**Comment by daler** [comment]
Closing; please reopen if this is still an issue!
