### ISSUE TITLE
Marking r-purrr packages broken

### ISSUE THREAD

**Issue by cbrueffer** [bioconda/bioconda-recipes#8895]
The bioconda ```r-purrr``` recipe was removed a while ago, but the old packages are still in the bioconda channel and the conda solver prefers them to the up to date conda-forge packages. All versions covered in bioconda are also available from conda-forge.

Please mark the packages listed in [https://anaconda.org/bioconda/r-purrr/files](https://anaconda.org/bioconda/r-purrr/files) as broken.

Pinging @daler

**Comment by daler** [comment]
@cbrueffer done. I marked them with the label `in-conda-forge`. I also marked the latest version of `r-psych`, which is now in conda-forge, with the `in-conda-forge` label.

**Comment by cbrueffer** [comment]
Thanks @daler !
