### ISSUE TITLE
Multiple compilations in a single recipe?

### ISSUE THREAD

**Issue by CicoZhang** [bioconda/bioconda-recipes#8901]
I want to make this package into Bioconda. https://github.com/ls-cwi/heinz. It requires the installation of two dependencies by compiling separately and then a final compilation to get the executable bin file. How can I make all the three compilations happen in one recipe?

Alternatively, can I directly distribute the BIN file directly without compilation?

Thanks in advance.

**Comment by daler** [comment]
@CicoZhang OGDF and LEMON are in conda-forge so you can use them as build dependencies. Not sure about CPLEX though, but the way to do it would be to have it in conda-forge as well. The heinz recipe would use them all as build-time dependencies.

**Comment by CicoZhang** [comment]
@daler Tjx. BTW, can I follow conda-build 3.0 style now?

**Comment by daler** [comment]
closing; `heinz` recipe is in https://github.com/bioconda/bioconda-recipes/pull/8926
