### ISSUE TITLE
CircleCI error: No module named Cython

### ISSUE THREAD

**Issue by endrebak** [bioconda/bioconda-recipes#8913]
Build log:

https://circleci.com/gh/bioconda/bioconda-recipes/9904?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The meta.yaml used in the commit: https://github.com/bioconda/bioconda-recipes/pull/8911/commits/51a41c21ea8928abf486ba1e20b0636d9667bbf3

Any help appreciated :)

Ps. am I doing things completely wrong? Is the proper way to include cython packages something else, like distributing binaries or what?

**Comment by lucventurini** [comment]
Hi @endrebak ,
                     I would try the following:

- in the "script" section, change from "python setup.py [..]" to "$PYTHON setup.py [..]"
- Try specifying a version of Cython, e.g. for my Mikado putting:
```  - cython >=0.28.2 ```

seemed to function.

Best

**Comment by daler** [comment]
@endrebak sorry for the late reply. This meta.yaml uses the new conda-build 3 version (with `host:` section rather than `build:`). What's happening is that there are no build dependencies detected. 

Changing `host:` to `build:` should do the trick.

**Comment by endrebak** [comment]
No need to apologize. Will fix this later, thanks :)
