### ISSUE TITLE
Package update request: Flexbar 2.5 to  3.1

### ISSUE THREAD

**Issue by mlbendall** [bioconda/bioconda-recipes#8928]
Hello @ArneKr,
We are interested in using Flexbar version 3.1 but see you have already created a recipe for 2.5. I'd be happy to create a recipe for the new version but just wanted to check with you first, in case you preferred to do it yourself.

Thanks!

**Comment by colinbrislawn** [comment]
Flexbar has been updated!
https://anaconda.org/bioconda/flexbar
