### ISSUE TITLE
pyteomics conda package is incompatible with modules available through pip

### ISSUE THREAD

**Issue by mglubber** [bioconda/bioconda-recipes#8971]
Installing pyteomics with conda from the bioconda channel appears to be incompatible with the pyteomics modules [pyteomics.pepxmltk](https://pypi.org/project/pyteomics.pepxml/) and [pyteomics.cythonize](https://pypi.org/project/pyteomics.cythonize/) available through pip. 

To test:
```
conda create --name some_env python=2.7 -c bioconda pyteomics 
conda activate some_env 
pip install pyteomics.pepxmltk
```

Will give an ImportError if you try to use pyteomics, e.g.:
```
>>> from pyteomics import mass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name mass
```

The same error occurs if pyteomics.cythonize is installed instead of pepxmltk.

However, if I install both pyteomics and the additional modules through pip, everything works correctly.

```
conda create --name some_env python=2.7
conda activate some_env
pip install pyteomics pyteomics.pepxmltk
>>> from pyteomics import mass
>>> mass.calculate_mass(formula="H2O")
18.0105646837
```
Installing just pyteomics through conda without any additional modules also works correctly. 

According to the pyteomics maintainer, this is [due to conda installing the package as an egg](https://bitbucket.org/levitsky/pyteomics/issues/25/pyteomics-34-incompatible-with-current) (`pyteomics-3.4-py2.7.egg` )in site-packages, while the cythonize and pepxmltk modules use the folder `pyteomics` (i.e. `some_env/lib/python2.7/site-packages/` is different when pyteomics is installed via conda vs pip), and `import` can't handle both the egg and the `pyteomics` folder in `site-packages`. Since everything works correctly when pip is used, I'm assuming the issues lies with the conda recipe?

**Comment by rvalieris** [comment]
ignoring the egg sounds weird to me but this is not up to conda to decide, the same would happen with whatever method used to install the egg. I guess the best in this case is to not build the package as an egg.

**Comment by levitsky** [comment]
Thank you! I think the recipe can also be updated to the latest pyteomics version, which is 3.5.1.

**Comment by rvalieris** [comment]
yes, I will update it soon ! I just wanted to get the fix in first.

**Comment by mglubber** [comment]
I just tested in a fresh environment, and everything work correctly after updating the package via `conda update pyteomics`. Thanks for your help, @rvalieris
