### ISSUE TITLE
Bioconductor UnsatisfiableError

### ISSUE THREAD

**Issue by MichWeb75** [bioconda/bioconda-recipes#9026]
Hi all,
I would like to install Bioconductor packages with conda  / bioconda

`conda install -c bioconda bioconductor-iranges`

Produces error :

UnsatisfiableError: The following specifications were found to be in conflict:
  - bioconductor-iranges

**Comment by bgruening** [comment]
Can you please try `conda create -n iranges -c bioconda bioconductor-iranges`

**Comment by MichWeb75** [comment]
This worked! Thanks, maybe you can forward this to 
https://anaconda.org/biobuilds/r-iranges
