### ISSUE TITLE
gawk fails on macos (see also #8904)

### ISSUE THREAD

**Issue by brantfaircloth** [bioconda/bioconda-recipes#9046]
bioconda gawk fails to run on osx (10.13.4, conda 4.5.4).  This is likely related to test failure noted in #8904 (mac os tests failed) for commit 55bfcd4.  The specific issue is:
```
dyld: Library not loaded: @rpath/libmpfr.4.dylib
  Referenced from: /Users/bcf/Anaconda/envs/phyluce-test/bin/gawk
  Reason: image not found
```
This subsequently causes problems in the bioconda version of `mafft`, which is where I first noticed the issue (the `mafft` wrapper calls `awk` and that was dying).

Versions of `gawk` from conda-forge and pkgs/main work as expected (and, as a result, mafft works as expected).

**Comment by bgruening** [comment]
gawk is now maintained in conda-forge and has seen a few major new releases.
