### ISSUE TITLE
SAMtools - can't access remote sequence when reading CRAM

### ISSUE THREAD

**Issue by garrett-stevens** [bioconda/bioconda-recipes#9056]
Hello all,

When decoding CRAM files, if there are `@SQ` headers with MD5 values (`M5` tags) but the specified FASTA file can't be found/opened, SAMtools will by default try to use the MD5 to download the sequence from the EBI server (`http://www.ebi.ac.uk/ena/cram/md5/<md5>`) and save it to the REF_CACHE location.

Using SAMtools from bioconda, I am not able to get this to work:
```
$ conda create -y -p /opt/anaconda3/envs/test1 samtools
$ source activate test1
$ samtools --version
samtools 1.8
Using htslib 1.8
Copyright (C) 2018 Genome Research Ltd.
$ samtools view test.cram > /dev/null
[E::cram_get_ref] Failed to populate reference for id 0
[E::cram_decode_slice] Unable to fetch reference #0 11109669..16279328
[E::cram_next_slice] Failure to decode slice
[main_samview] truncated file.
```
However, using SAMtools I compile on my own, this works just fine (some output omitted for brevity):
```
$ wget https://github.com/samtools/samtools/releases/download/1.8/samtools-1.8.tar.bz2
$ tar xjf samtools-1.8.tar.bz2
$ cd samtools-1.8/
$ ./configure
$ make
$ cd ..
$ ./samtools-1.8/samtools --version
samtools 1.8
Using htslib 1.8
Copyright (C) 2018 Genome Research Ltd.
$ # This works fine
$ ./samtools-1.8/samtools view test.cram > /dev/null
$ # Also, you can see in my cache where the downloaded reference now is:
$ ls -R .cache/
.cache/:
hts-ref

.cache/hts-ref:
a7

.cache/hts-ref/a7:
18

.cache/hts-ref/a7/18:
acaa6135fdca8357d5bfe94211dd
```

I've tried manually setting `REF_PATH='http://www.ebi.ac.uk/ena/cram/md5/%s'` (also tried HTTPS) and `REF_CACHE='$HOME/.cache'` when using the bioconda version, but that doesn't help. I can see from the `build.sh` that libcurl is explicitly enabled, so I'm not sure what's preventing it from downloading those references via HTTP: https://github.com/bioconda/bioconda-recipes/blob/fa495c10ee8e421f12afe7ceb373eeb8e6487652/recipes/samtools/build.sh#L21

Also, after the reference is downloaded to REF_CACHE via the working version of SAMtools, the bioconda SAMtools is able to find it and display the file just fine.

The following zip has a CRAM that should work for reproducing this:
[test.zip](https://github.com/bioconda/bioconda-recipes/files/2045832/test.zip)

**Comment by rvalieris** [comment]
I can reproduce the issue by adding `--enable-plugins` on the local build configure.

I am not sure where the problem is exactly. but with strace I can see that samtools tries to open the URL as if it was a local file:
```
open("https://www.ebi.ac.uk/ena/cram/md5/a718acaa6135fdca8357d5bfe94211dd", O_RDONLY) = -1 ENOENT (No such file or directory)
```

**Comment by garrett-stevens** [comment]
@rvalieris, thanks for the response! I've filed an issue in SAMtools since this might be an issue there (although it might also be the expected behavior, I can't find much information on what `--enable-plugins` is actually supposed to do): https://github.com/samtools/samtools/issues/857

It looks like `--enable-plugins` got added to the `build.sh` in this commit, although I can't tell exactly what it's doing: https://github.com/bioconda/bioconda-recipes/commit/afd726a3667aa3394b69bfd21d9249e9e3fb36c8

**Comment by rvalieris** [comment]
ping @bioconda/core 

thanks for the clarifications @jmarshall, I agree the recipe needs cleaning, the recipe is as it is currently because it has a long history of different issues resolved over the years, made by different people.
I will try to make PR later today with a cleaner build.sh

**Comment by garrett-stevens** [comment]
Thanks to both of you for helping out. I'm wondering, should the new samtools recipe (and bcftools as well) depend on the htslib recipe/package like @jmarshall implied? It seems like that's the more conda-esque way of doing things, rather than building htslib separately for all three, although I could definitely be wrong.

That's probably outside the scope of this issue, though. Maybe it's better to just clean up the current recipe and try and handle adding in that dependency another time.

**Comment by kyleabeauchamp** [comment]
Yes, if possible I think we should have the samtools recipe depend on the HTSLib package, rather then vendoring the build internally.

**Comment by kyleabeauchamp** [comment]
PS: I might work on this samtools recipe rewrite after the conda-build3 changes go live.

**Comment by rvalieris** [comment]
i made an initial PR here: https://github.com/bioconda/bioconda-recipes/pull/9072,
comments and reviews are welcome.

**Comment by rvalieris** [comment]
the PR was merged, and https support should be working now.

the only thing left is to link samtools with the htslib package, which we will do after conda-build 3 stuff gets merged.

**Comment by garrett-stevens** [comment]
Thanks everyone! I just tested this out with the latest build and it worked great. I'll close the issue and keep my eye out for when samtools gets linked to the htslib package.
