### ISSUE TITLE
MOODS/GCC - OS dependent Illegal instruction during runtime

### ISSUE THREAD

**Issue by jenzopr** [bioconda/bioconda-recipes#9079]
Hi @bioconda/python @bioconda/lib,

We're facing a strange issue with `MOODS` failing with a `Illegal instruction` error dependent on the host OS (Debian 8 vs. Debian 9).

The following steps have been carried out on both systems (at the same time):
```
conda create -c bioconda -c conda-forge -n moods_test moods
```
and in `python`:
```
import MOODS.tools
MOODS.tools.flat_bg(4)
```

The call is successful on Debian 8, but fails with the `Illegal instruction` error on Debian 9.
We could so far track the issue down to be related to `gcc / libgcc` (see [here](https://github.com/jhkorhonen/MOODS/issues/19)). Since `libgcc` comes in the same version on both systems (its in the runtime dependency), we suspect `MOODS` to use some things from the host's `gcc` during runtime. On Debian 8, `gcc` comes in version 4.9.2, but on Debian 9 in version 6.3.0.

Next, we tried to require `gcc` during runtime as well (version 4.8.5), but this did not solve the problem.
How could we continue investigation? 

Thanks a lot,
Jens

**Comment by jenzopr** [comment]
The problem is solved now. Our setup is based on KVM and the processor type was not communicated correctly from the hypervisor to the virtual machine. This lead `configure` to configure for the communicated processor, but the execution was actually on a different processor.

Best,
Jens

**Comment by mbargull** [comment]
Thanks for the update @jenzopr! I was very curious what happened there :wink:

**Comment by jenzopr** [comment]
The processor(s) were exposed as something that Debian identified as `CPU family 15` in `/proc/cpuinfo`, which boils down to an Intel Pentium 4. That would be a bit too old for new hypervisors from last year, but luckily I could set the processor type to the correct microarchitecture on the hypervisor 😃

**Comment by adam-azarchs** [comment]
I am also experiencing this problem when running on AWS `r3` instance types, which are Sandy Bridge family which does not support AVX2.  The problem is at https://github.com/jhkorhonen/MOODS/blob/master/python/setup.py#L10 which sets `-march=native` so it'll build for whatever CPU build system has, which in this case appears to be at least Haswell.

In our case we need to be able to run on CPUs going all the way back to at least Westmere (no SSE4 support).
