### ISSUE TITLE
Remove log4cpp from Bioconda recipes

### ISSUE THREAD

**Issue by marcelotrevisani** [bioconda/bioconda-recipes#9097]
Hi guys, I just let you know that I created a recipe for the package ``log4cpp`` in ``conda-forge``. Because of that it is not necessary to maintain this recipe in Bioconda anymore.

https://github.com/conda-forge/log4cpp-feedstock

**Comment by marcelotrevisani** [comment]
cc: @bebatut

**Comment by mbargull** [comment]
Thanks @marcelotrevisani! Tracking this in gh-9111
