### ISSUE TITLE
Nanopolish 0.9.2 and Porechop in conflict?

### ISSUE THREAD

**Issue by nickloman** [bioconda/bioconda-recipes#9148]
Hi 

I've recently built a new nanopolish 0.9.2 package.

I can't seem to make a Conda environment with both nanopolish and porechop installed athough I am sure I have done this previously.

During installation, Conda complains that porechop and nanopolish are in conflict.

From what I can gather, it is the Python version that causes the conflict judging by the output of conda info.

`conda info nanopolish==0.9.2

nanopolish 0.9.2 ncurses5.9_0
-----------------------------
file name   : nanopolish-0.9.2-ncurses5.9_0.tar.bz2
name        : nanopolish
version     : 0.9.2
build string: ncurses5.9_0
build number: 0
channel     : https://conda.anaconda.org/bioconda/osx-64
size        : 1.7 MB
arch        : x86_64
constrains  : ()
license     : MIT
md5         : 3585b5b0535bddf11eca39957ec8e53d
platform    : darwin
subdir      : osx-64
url         : https://conda.anaconda.org/bioconda/osx-64/nanopolish-0.9.2-ncurses5.9_0.tar.bz2
dependencies:
    biopython
    bwa
    eigen
    hdf5 1.8.17*
    libdeflate
    libgcc
    ncurses 5.9*
    python 2.7*`

`conda info porechop==0.2.3_seqan2.1.1=py36_2

porechop 0.2.3_seqan2.1.1 py36_2
--------------------------------
file name   : porechop-0.2.3_seqan2.1.1-py36_2.tar.bz2
name        : porechop
version     : 0.2.3_seqan2.1.1
build string: py36_2
build number: 2
channel     : https://conda.anaconda.org/bioconda/osx-64
size        : 77 KB
arch        : x86_64
constrains  : ()
license     : GPL-3.0-only AND BSD-3-Clause
md5         : 87055c6655fdd80cbec165201425642b
platform    : darwin
subdir      : osx-64
url         : https://conda.anaconda.org/bioconda/osx-64/porechop-0.2.3_seqan2.1.1-py36_2.tar.bz2
dependencies:
    python 3.6*`

I can't see that in the nanopolish recipe we specify any particular version of Python though, so I am confused where the 2.7* pinning comes from . Any suggestions here @druvus  ?

It looks like the bundled scripts are probably mainly compatible with Python 3 but some of the lesser used ones are not (could be fixed though).

**Comment by nickloman** [comment]
I think the problem is that there are only builds for nanopolish 0.9.2 for python 2.7, whereas 0.9.0 had builds for python 3.5 and 3.6 as well, but I didn't change the recipe to skip the builds, so I'm a little bit stumped. Can I force a rebuild of a recipe?

**Comment by druvus** [comment]
@nickloman I sak you modified the build string (removed the python part). I think It might be the reason you only build for one python version. Currently only a cellphone so I can’t do any checking at the moment.

**Comment by nickloman** [comment]
Yeah I'm not sure how/why I did that but I think that was the problem! Thanks, I just restored it!

**Comment by nickloman** [comment]
Hmm, although my builds are passing fine and according to CircleCi the upload has worked, I can't seem to see the expected latest files on Anaconda still ... 

https://anaconda.org/bioconda/nanopolish/files

https://circleci.com/gh/bioconda/bioconda-recipes/11771

**Comment by nickloman** [comment]
I got there in the end .. somehow!
