### ISSUE TITLE
Removing broken BLASR binary artifacts

### ISSUE THREAD

**Issue by pb-dseifert** [bioconda/bioconda-recipes#9176]
Hi @bgruening 
The previous versioning scheme used by BLASR in bioconda was broken, and now causes conda to choose an old, broken release (`5.3.9c6f0a5`) over the new point release (`5.3.1`), probably due to some string to int coercion or something. Could you please delete

`linux-64/blasr-5.3.f8bfa9c-0.tar.bz2`
`linux-64/blasr-5.3.9c6f0a5-0.tar.bz2`
`linux-64/blasr-5.2p1-0.tar.bz2`

and

`linux-64/blasr_libcpp-1.1-boost1.64_1.tar.bz2`
`linux-64/blasr_libcpp-1.1-boost1.61_0.tar.bz2`
`linux-64/blasr_libcpp-1.1-boost1.60_0.tar.bz2`

from the Anaconda cloud, so that users will not get it, which happened to us today (https://github.com/PacificBiosciences/blasr/issues/396#event-1667137994).

**Comment by bgruening** [comment]
@pb-dseifert can you bump release a new version of blasr, e.g. 5.4? The only other way would be to mark the other versions as broken, which I would like to avoid.

**Comment by bgruening** [comment]
Oo, this sounds advantageous. Hope you can influence them in a good direction :)
I marked the packages as broken.

**Comment by pb-dseifert** [comment]
Thanks a lot, 5.3.2 is now showing up as the most recent version!
