### ISSUE TITLE
Trinity 2.1.1 fails because of name collision with conda-forge jellyfish

### ISSUE THREAD

**Issue by brantfaircloth** [bioconda/bioconda-recipes#9235]
This is somewhat redundant with #6107, but might be viewed as a separate issue.  The v2.1.1 install of Trinity (which I got by default after dependency checks) fails in my hands when `.condarc` contains:
```
channels:
  - defaults
  - conda-forge
  - bioconda
```
This is because of the name collision of `conda-forge jellyfish` and `bioconda jellyfish-2.2.6`.

**Comment by bgruening** [comment]
see here for a jellyfish rename: https://github.com/bioconda/bioconda-recipes/pull/17748
