### ISSUE TITLE
picard shell-wrapper default heap size

### ISSUE THREAD

**Issue by walterdevalk** [bioconda/bioconda-recipes#9325]
I was using Picard to mark duplicates this week. An out of memory error raised after processing several samples. The default heap size in the shell-wrapper is 1Gb. After adding the argument -Xmx2g everything went fine.

In the picard tool documentation  (https://broadinstitute.github.io/picard/command-line-overview.html) a heap size of 2Gb is advised:

> jvm-args are arguments that are specific to Java, not Picard. We do not provide guidance for specifying JVM (Java Virtual Machine) arguments except for specifying memory: most of the commands are designed to run in 2GB of JVM, so we recommend using the JVM argument -Xmx2g.

Is there a reason the default is set to 1Gb?

**Comment by maarten-k** [comment]
I think it is a good idea to use there "defaults". What is the reason why to set Xmx in a script to start with? (default would be 1/4 of the total memory). Also, this script disables memory setting which is set via the command line.
For example:
```
export JAVA_TOOL_OPTIONS="-Xmx2G"
```
