### ISSUE TITLE
assemblerflow has been renamed flowcraft

### ISSUE THREAD

**Issue by corburn** [bioconda/bioconda-recipes#9368]
Similar to the abruijn discussion #9174, the author of assemblerflow has renamed the project flowcraft. Should the existing recipe be renamed or should a new recipe be added?

https://pypi.org/project/assemblerflow/#history
https://pypi.org/project/flowcraft/#history

https://github.com/assemblerflow/flowcraft

**Comment by ODiogoSilva** [comment]
Hi, I'm one of the developers of assemblerflow/flowcraft. The name was changed after version 1.20 and a recipe for the the new package was already created (https://anaconda.org/bioconda/flowcraft). We maintain the assemblerflow recipe for use cases that require version <1.20.

**Comment by corburn** [comment]
Thanks @ODiogoSilva
