### ISSUE TITLE
My recipe is in bioconda but not built

### ISSUE THREAD

**Issue by jupollet** [bioconda/bioconda-recipes#9447]
All checks have passed for perl-string-random recipe. 
My recipe was merged in bioconda but not built (PR #9388).

**Comment by daler** [comment]
@jupollet, please see https://github.com/bioconda/bioconda-recipes/issues/9404 -- it will take substantially longer than usual for packages to be built due to the major changes currently underway.

**Comment by jupollet** [comment]
is it the cause of this error when i try to make a new PR  : 

error ci/circleci: lint : 

From ssh://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__khwnguykby/master
The CI configuration is out of date.
Please merge in bioconda:master.
Exited with code 1

**Comment by dpryan79** [comment]
This is now available, so can this issue be closed?
