### ISSUE TITLE
Fix matplotlib version in qiime 1.9.1

### ISSUE THREAD

**Issue by cdiener** [bioconda/bioconda-recipes#945]
QIIME 1.9.1 does not work with matplotlib 1.5 (see https://github.com/biocore/qiime/issues/2117), and probably never will until QIIME 2.x. So the matplotlib version should reflect that in the recipe.

Cheers

**Comment by bgruening** [comment]
@cdiener this should be reflected here: https://github.com/biocore/qiime/blob/master/setup.py#L437
I will fix it in the recipe to be greater than 1.5

**Comment by cdiener** [comment]
Unfortunately, the qiime setup.py is not up to date. The version string allows installation of 1.5 (larger than 1.1 and not 1.4.2). It should be *smaller* than 1.5 in the recipe since qiime 1.x does not support matplotlib 1.5+.

**Comment by bgruening** [comment]
Ok, will patch Qiime if I find time and update the recipe. Thanks!

**Comment by cdiener** [comment]
Awesome. Thanks to you!

**Comment by bgruening** [comment]
Ok done. I will work further on an OS-X version.
