### ISSUE TITLE
Question: how are managed/handled maven based packages

### ISSUE THREAD

**Issue by osallou** [bioconda/bioconda-recipes#9468]
To build a (bio)conda package, how is managed maven based package which downloads its dependencies from a remote repo ?
I could not find a documentation/example to handle this.

**Comment by rvalieris** [comment]
I am not familiar with maven but you should be able to add maven as a build-time dependency and call `mvn` on the build.sh to do everything you need.

see this recipe that uses maven: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/mobster/meta.yaml, https://github.com/jyhehir/mobster/blob/master/install.sh

**Comment by osallou** [comment]
The pb is maven downloads all its dependencies from a remote repo, nit a
good pratice from a packaging poibt of view..
While it supports offline mode, dependencies must be available in a
spexific way, getting jar files in classpath is not enough

Le ven. 22 juin 2018 à 19:04, Renan Valieris <notifications@github.com> a
écrit :

**Comment by bgruening** [comment]
@osallou I guess we do ship precompiled jar files very often. As you said "nit a
good pratice from a packaging poibt of view..". And we don't have a strong Java community that cares about fixing this properly.
