### ISSUE TITLE
Issue with build/upload system?

### ISSUE THREAD

**Issue by necrolyte2** [bioconda/bioconda-recipes#947]
I think there may be a bug with the recipe building
See related #937 PR

If you look at the travis build it says it skipped [samtools 0.1.19](https://travis-ci.org/bioconda/bioconda-recipes/jobs/113688653#L888) but it ran [quast](https://travis-ci.org/bioconda/bioconda-recipes/jobs/113688653#L950), even though that build should have been for samtools not quast.

Also, if you look at the anaconda.org [bioconda](https://conda.anaconda.org/bioconda) page samtools is not listed as being recently updated and when I do `conda install samtools==0.1.19` it is not installing the updated dependencies like it should(aka, ncurses does not get installed)

**Comment by johanneskoester** [comment]
Looks like PR #937 does not increase the build number. Without that, conda cannot know that the recipe has changed.

**Comment by johanneskoester** [comment]
I think this is solved, right?
