### ISSUE TITLE
Octopus: missing '-DCMAKE_BUILD_TYPE=Release' flag in build.sh

### ISSUE THREAD

**Issue by dorjee** [bioconda/bioconda-recipes#9476]
The current version of octopus package in bioconda is missing `-DCMAKE_BUILD_TYPE=Release` flag in its build script. Please refer to the exchange on octopus issue tracker: https://github.com/luntergroup/octopus/issues/28#issuecomment-398206273

This issue has been resolved by the developer on other versions of the same software [#25](https://github.com/luntergroup/octopus/issues/25) However, the same hasn't been done for Conda version for some reason. Would it be possible add this flag and tag a new version, please?
```
-cmake  -DINSTALL_PREFIX=ON -DCMAKE_INSTALL_PREFIX=$PREFIX -DINSTALL_ROOT=ON ..  
+cmake  -DINSTALL_PREFIX=ON -DCMAKE_INSTALL_PREFIX=$PREFIX -DINSTALL_ROOT=ON -DCMAKE_BUILD_TYPE=Release ..  
```
Thanks,

**Comment by corburn** [comment]
Looks like the build number needed to be bumped in #7992

**Comment by bgruening** [comment]
I will take care of this in the bulk branch.
