### ISSUE TITLE
Properly specifying version constraints for dependencies

### ISSUE THREAD

**Issue by luizirber** [bioconda/bioconda-recipes#9547]
Hello,

while updating the sourmash recipe (in #9546) I change the `khmer` version constraints to
[` - khmer >=2.1,<3`](https://github.com/bioconda/bioconda-recipes/blob/b34eb5e39a287ef8aa50def07605b8f86fa41502/recipes/sourmash/meta.yaml#L36)
but, when I tried to install it conda still pulls `khmer 3.0.0a1-py36hfc679d8_0`:

<details>
 <summary>Details</summary>

    $ conda install -c bioconda sourmash==2.0.0a8 
    Solving environment: done

    ## Package Plan ##

      environment location: /home/chick/miniconda3

      added / updated specs: 
        - sourmash==2.0.0a8

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        glib-2.43.0                |                1         5.4 MB
        matplotlib-2.0.2           |      np113py36_0        10.9 MB
        libpng-1.6.30              |                1         220 KB
        libgcc-7.2.0               |       h69d50b8_2         304 KB
        numpy-1.13.3               |   py36hdbf6ddf_4         3.9 MB
        qt-5.6.2                   |                5        43.5 MB
        dbus-1.10.20               |                0         1.4 MB
        ------------------------------------------------------------
                                               Total:        65.6 MB

    The following NEW packages will be INSTALLED:

        bz2file:          0.98-py36_0                       
        cycler:           0.10.0-py36h93f1223_0             
        dbus:             1.10.20-0                         
        expat:            2.2.5-he0dffb1_0                  
        fontconfig:       2.12.1-3                          
        freetype:         2.5.5-2                           
        glib:             2.43.0-1                          
        gst-plugins-base: 1.8.0-0                           
        gstreamer:        1.8.0-0                           
        icu:              54.1-0                            
        ijson:            2.3-py36_0             conda-forge
        intel-openmp:     2018.0.3-0                        
        jpeg:             9b-h024ee3a_2                     
        khmer:            3.0.0a1-py36hfc679d8_0 bioconda   
        libgcc:           7.2.0-h69d50b8_2                  
        libgfortran-ng:   7.2.0-hdf63c60_3                  
        libiconv:         1.14-0                            
        libpng:           1.6.30-1                          
        libstdcxx-ng:     7.2.0-hdf63c60_3                  
        libxcb:           1.13-h1bed415_1                   
        libxml2:          2.9.4-0                           
        matplotlib:       2.0.2-np113py36_0                 
        mkl:              2018.0.3-1                        
        mkl_fft:          1.0.1-py36h3010b51_0              
        mkl_random:       1.0.1-py36h629b387_0              
        numpy:            1.13.3-py36hdbf6ddf_4             
        pyparsing:        2.2.0-py36hee85983_1              
        pyqt:             5.6.0-py36_2                      
        python-dateutil:  2.7.3-py36_0                      
        pytz:             2018.4-py36_0                     
        qt:               5.6.2-5                           
        scipy:            1.1.0-py36hfc37229_0              
        screed:           1.0-py36_0             bioconda   
        sip:              4.19.8-py36hf484d3e_0             
        sourmash:         2.0.0a8-py36hfc679d8_1 bioconda 

    Proceed ([y]/n)? 
</details>

What would be the right syntax, or is this a bug?

**Comment by rvalieris** [comment]
hello, this is one of those cases were conda is technically right but its confusing.

the problem is that the version string "3.0.0a1" is considered by conda as a "pre-release" version and thus its less than "3.0.0".

you could change the selector to "khmer >=2.1,<2.9" to work around this.

**Comment by luizirber** [comment]
Thanks! I updated the recipe and set up a new PR #9574

**Comment by mbargull** [comment]
xref: https://github.com/bioconda/bioconda-recipes/pull/9574#discussion_r197960577
