### ISSUE TITLE
GATK jar file location

### ISSUE THREAD

**Issue by micknudsen** [bioconda/bioconda-recipes#9567]
Some GATK3 tools (e.g. [CatVariants](https://software.broadinstitute.org/gatk/documentation/tooldocs/3.8-0/org_broadinstitute_gatk_tools_CatVariants.php)) cannot be run using the `gatk3` wrapper script but require direct access to the `GenomeAnalysisTK.jar` file. Is there a way to get the jar file location?

Would it make sense to add an extra option to `gatk3-register` such as:

`gatk3-register --jar-file-location`

or maybe just have `gatk3-register` return the path to `GenomeAnalysisTK.jar` if it has been registered?

**Comment by rvalieris** [comment]
>Some GATK3 tools (e.g. CatVariants) cannot be run using the gatk3 wrapper script

you can call CatVariants, try this:
`gatk3 org.broadinstitute.gatk.tools.CatVariants --help`

the wrapper checks the argument, see the source: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gatk/gatk.py#L79

**Comment by micknudsen** [comment]
Sorry, I missed that part. Thanks for pointing that out.
