### ISSUE TITLE
circleci test-macos fails

### ISSUE THREAD

**Issue by asmariyaz23** [bioconda/bioconda-recipes#9580]
I was able to circleci build the recipe locally but the test-macos [PR #9576](https://github.com/bioconda/bioconda-recipes/pull/9576). Could someone help me understand this error?

Thank you!

**Comment by dpryan79** [comment]
You'll want to merge in the master branch or just rebase your edits off of the most recent commit in the master branch.

**Comment by asmariyaz23** [comment]
@dpryan79 I built this recipe off the latest commit at the time. Forked the repo just yesterday afternoon.

**Comment by dpryan79** [comment]
At the moment a lot changes in a day.

**Comment by asmariyaz23** [comment]
merging with master did the trick! thank you :)
