### ISSUE TITLE
CircleCI : Auto Cancelling a Redundant Build

### ISSUE THREAD

**Issue by martin-mann** [bioconda/bioconda-recipes#9583]
Hi @bioconda/build-system 

it might be worst checking whether you want to enable **"Auto Cancelling a Redundant Build"** within the CircleCI test system:

https://circleci.com/docs/2.0/skip-build/#auto-cancelling-a-redundant-build

this will skip all obsolete builds when new commits are pushed to a  branch, which I find quite usefull. Even more, since I "forgot" to tag my commits with `[ci skip]`

https://circleci.com/docs/2.0/skip-build/#skipping-a-build

since I wasnt aware of that possibility...

thanks for looking into this,
Martin

**Comment by mbargull** [comment]
We already have that setting activated, but its description is
> **Auto-cancel redundant builds (Does not apply to workflows)**
>
> With the exception of your default branch, we will automatically cancel any queued or running builds on a branch when a newer build is triggered on that same branch. This feature will only apply to builds triggered by pushes to GitHub.

and I guess due to that `(Does not apply to workflows)` addition it's not really used :confused:

**Comment by martin-mann** [comment]
hrmpf...  I see.. what a pitty.. maybe it is worth to ping the circleci people that this would be a great feature!?!

thanks for feedback, I will close the issue.
Martin
