### ISSUE TITLE
circleci test worked localy, pushed changes then linting failed

### ISSUE THREAD

**Issue by SchwarzMarek** [bioconda/bioconda-recipes#9717]
Hello,
I'm trying to write my first recipe and I'm feeling like banging my head against the wall.

I've wrote the recipe and was able to run test build and install using conda-build localy (worked), then tried to push changes -> linting failed - my mistake. 

So I installed the circleci localy fixed linting problem, pushed changes - > linting OK, linux OK, macos (fail on testing).
Then, I've tried to wrote the test different way (having no access to macos) and run circleci localy -> OK. Then pushed changes and linting failed [(circleci report)](https://circleci.com/gh/bioconda/bioconda-recipes/16066?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) ??? And it appears to me that that is not even my code. 

At this point I don't know what I should do to fix it.

Do someone has some advice on how run tests for macos? 

Link for the [PR](https://github.com/bioconda/bioconda-recipes/pull/9647).

Any help is appreciated.
Best regards

Marek Schwarz

**Comment by dpryan79** [comment]
Your master branch is presumably rather old. Pull that from bioconda and then merge it into your branch.

**Comment by SchwarzMarek** [comment]
Oh, thank you.
