### ISSUE TITLE
Extending existing HMMER3 package to include Easel mini applications

### ISSUE THREAD

**Issue by mscheremetjew** [bioconda/bioconda-recipes#9746]
Hello,
I came across the Bioconda hmmer package (https://bioconda.github.io/recipes/hmmer/README.html). It contains all the hmmer binaries and works nicely. But unfortunately it does not contain the extra mini applications (Easel tools), like esl-reformat etc. Those tools are not installed by default, but it is an optional compilation step at install time (page 13 of http://eddylab.org/software/hmmer3/3.1b2/Userguide.pdf). The mini apps are included in all the various HMMER 3 version.

"Optionally, you can install the Easel library package as well, including its various “miniapplications”, in
addition to its library and header files. We don’t do this by default, in case you already have a copy of Easel
separately installed:
> cd easel; make install"

I was wondering if you could add those to the hmmer package as well?
Kind Regards,
Maxim

**Comment by bgruening** [comment]
@mscheremetjew pleaes create a PR and include this into the recipe. I think this is a good addition.

**Comment by mscheremetjew** [comment]
@bgruening Many Thanks for your reply. We will have a look into this. In theory this should be a relatively easy and straight forward extension.
I have one more question. This Bioconda hmmer package is used to build the following Docker image:
https://quay.io/repository/biocontainers/hmmer
How do we trigger the re-built of the Docker image for Hmmer 3.2. Would that happen automatically?

**Comment by colinbrislawn** [comment]
I just checked and all the esl miniapps appear to be included right now!

I'll close this issue, but feel free to reopen if you find any issues.
