### ISSUE TITLE
weblogo - naming convention for python packages

### ISSUE THREAD

**Issue by sebastian-luna-valero** [bioconda/bioconda-recipes#976]
Hi all,

One of my packages depends on a python module called `weblogo`:
https://pypi.python.org/pypi/weblogo

However, there is a recipe in bioconda called `weblogo` that contains a completely different program:
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/weblogo
http://weblogo.berkeley.edu/

I am about to add the `weblogo` package hosted in `PyPI` to bioconda but what would be a proper name for it? I guess we should define a common policy for this kind of problems.

Many thanks,
Sebastian.

**Comment by johanneskoester** [comment]
Maybe the policy could be to prefix with "python-" in case of ambiguities, i.e. python-weblogo? @bioconda/all, any opinions?

**Comment by daler** [comment]
`python-` prefix sounds reasonable. There's precedence at least: I did this with `python-wget` for the PyPI package `wget`.

**Comment by acaprez** [comment]
Sounds fine to me as well.

**Comment by brentp** [comment]
Sounds good

**Comment by sebastian-luna-valero** [comment]
Many thanks all, I will use `python-weblogo`

Best regards,
Sebastian.

**Comment by vivekiitkgp** [comment]
Probably it'll be a good idea to mention this somewhere on README or
CONTRIBUTING guidelines.

--
https://vivekiitkgp.github.io
