### ISSUE TITLE
Any interest in a Bioconda Hackathon this month?

### ISSUE THREAD

**Issue by cgconf** [bioconda/bioconda-recipes#9779]
Hi folks,

I'm looking for anyone who might be going to PEARC18 (https://www.pearc18.pearc.org/) who would like to be involved in a hackathon. We're organizing a general hackathon for HPC, and would like to see if someone can lead a group working with bioconda and biocontainers. The general theme of the hackathon is not necessarily software development, but rather, deployment on HPC systems. Getting bioconda working smoothly on as many systems as possible, and possibly packaging up bioinformatics software that is not yet in bioconda, is the gold star goal. Let me know asap if you will be there or are willing to participate in any capacity.

**Comment by bgruening** [comment]
ping @bioconda/all 
Thanks Carrie!

**Comment by acaprez** [comment]
I'll be at PEARC and am up for some type of hackathon.

**Comment by bgruening** [comment]
Wonderful! Thanks a lot @acaprez!

**Comment by npavlovikj** [comment]
This sounds like a great idea, but Is it possible to make the hackathon online, so people that are not attending PEARC can still remotely participate?

**Comment by bgruening** [comment]
@cgconf I know this will happen, do you mind updating this issue with more details for interested participants? Thanks!

**Comment by druvus** [comment]
PEARC18 was taking place last summer so I am closing.
