### ISSUE TITLE
Doubt about how to refresh README.html file

### ISSUE THREAD

**Issue by CarlosHorro** [bioconda/bioconda-recipes#9782]
Hi,

I would like to ask you about how I can update the content of the README.html file, ie:
http://bioconda.github.io/recipes/pathwaymatcher/README.html

as after updating the package for some versions, that file is still making reference to the first version and with some broken links (ie: Docker). In the near future I will also need to update the "home" info...

Greetings,
Carlos

**Comment by bgruening** [comment]
This is updated automatically, but we are currently keeping the build-infrastructure busy, so this can take some time ... as soon as we are done with the major rebuild this will go faster again.
