### ISSUE TITLE
blacklist gimmemotifs

### ISSUE THREAD

**Issue by simonvh** [bioconda/bioconda-recipes#9819]
@bgruening I see that the gimmemotifs has been blacklisted with the message that the upload takes more than 10 minutes. Can I help solve this? What exactly is the problem, which upload is this? It seems to build fine when I test it locally.

**Comment by bgruening** [comment]
@simonvh please try, I'm not sure what happened and postponed it until I rebuild most of the other pkgs.

**Comment by bgruening** [comment]
I think it was about uploading the container. Is this pkg especially big?
