### ISSUE TITLE
NanoPlot: libbz2.so.1 No such file or directory

### ISSUE THREAD

**Issue by dfornika** [bioconda/bioconda-recipes#9833]
When attempting to run `NanoPlot` on my system I get the following error message:

```
(nanoplot) [dfornika@sabin ~]$ NanoPlot -h
Traceback (most recent call last):
  File "/opt/miniconda2/envs/nanoplot/bin/NanoPlot", line 4, in <module>
    import nanoplot.NanoPlot
  File "/opt/miniconda2/envs/nanoplot-1.13.0/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 18, in <module>
    from nanoget import get_input
  File "/opt/miniconda2/envs/nanoplot-1.13.0/lib/python3.5/site-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/opt/miniconda2/envs/nanoplot-1.13.0/lib/python3.5/site-packages/nanoget/nanoget.py", line 29, in <module>
    import pysam
  File "/opt/miniconda2/envs/nanoplot-1.13.0/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory
```

This is a shared compute cluster system, so I'd prefer not to mess with the system packages. Should `bzip2` be added as a run-time dependency on the `NanoPlot` recipe? (and/or maybe the `NanoGet` or `pysam` recipes?)

@wdecoster @bioinformed

**Comment by wdecoster** [comment]
NanoPlot seems to gets this issue from nanoget, which gets it from pysam. So I think the dependency should be solved there? Tagging @AndreasHeger

**Comment by dpryan79** [comment]
This is actually coming from htslib. It's very likely that you have the wrong channel order. Please ensure that the order is:

 1. bioconda
 2. conda-forge
 3. default

The default channel has a broken bzip2 package for "reasons" but that will typically get over-ridden by the conda-forge package which is correctly made.

BTW, you can likely fix this with a simple `conda install -c conda-forge bzip2`.

**Comment by dfornika** [comment]
Thanks @dpryan79. You're right about my channel priority, I have conda-forge at the bottom of my priority list so I'll change that right now.

Your suggestion to do `conda install -c conda-forge bzip2` seems to have worked. I don't get the error message, I get the expected help output when I run `NanoPlot -h` now.

**Comment by wdecoster** [comment]
Thanks @dpryan79 and thanks for confirming @dfornika!
