### ISSUE TITLE
Building with SELinux

### ISSUE THREAD

**Issue by duboism** [bioconda/bioconda-recipes#9862]
Hi,

I'm new to conda/bioconda so please pardon my ignorance.

I tried to [test locally](https://bioconda.github.io/contribute-a-recipe.html#test-locally) my recipe on a Fedora 27 machine with SELinux enforcing but I didn't work:
     19:30:47 BIOCONDA INFO Recipes newly unblacklisted:
     
     19:30:47 BIOCONDA INFO Recipes modified according to git: plascope
     19:30:59 BIOCONDA INFO DOCKER: Building image "tmp-bioconda-builder" from /tmp/tmp_0iu_18o
     .19:32:23 BIOCONDA INFO DOCKER: Built docker image tag=tmp-bioconda-builder
     19:32:23 BIOCONDA INFO blacklist:
     ...
     19:32:23 BIOCONDA INFO Generating DAG
     19:32:23 BIOCONDA INFO Inspected 0 of 1 recipes
     19:32:23 BIOCONDA INFO Building and testing 1 recipes in total
     19:32:23 BIOCONDA INFO Recipes to build: 
     plascope
     19:32:23 BIOCONDA INFO Building and testing subdag 1 of 1 (1 recipes)
     19:32:25 BIOCONDA INFO Determining expected packages
     Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
     
     Adding in variants from internal_defaults
     Adding in variants from /tmp/miniconda/miniconda/conda_build_config.yaml
     Adding in variants from /tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
     Attempting to finalize metadata for plascope
     19:32:29 BIOCONDA INFO BUILD START recipes/plascope
     19:32:33 BIOCONDA ERROR COMMAND FAILED: docker run --net host --rm -v /tmp/tmpvki419pk/build_script.bash:/opt/build_script.bash -v /tmp/miniconda/miniconda/conda-bld:/opt/host-conda-bld -v /home/mdubois/Code/bioconda-recipes/recipes/plascope:/opt/recipe -e CONDA_SHLVL=1 -e CONDA_EXE=/tmp/miniconda/miniconda/bin/conda -e LANG=fr_FR.UTF-8 -e CONDA_PYTHON_EXE=/tmp/miniconda/miniconda/bin/python -e CONDA_PROMPT_MODIFIER=(base)  -e CONDA_DEFAULT_ENV=base -e CONDA_ROOT=/tmp/miniconda/miniconda -e CONDA_ALLOW_SOFTLINKS=false -e HOST_USER_ID=20000 tmp-bioconda-builder /bin/bash /opt/build_script.bash
     19:32:33 BIOCONDA ERROR STDOUT+STDERR:
     bash: cannot set terminal process group (-1): Inappropriate ioctl for device
     bash: no job control in this shell
     Glob /opt/recipe/meta.yaml did not match in root_dir /
     ERROR:conda_build.utils:Glob /opt/recipe/meta.yaml did not match in root_dir /
     Traceback (most recent call last):
       File "/opt/conda/bin/conda-build", line 11, in <module>
         sys.exit(main())
       File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
         execute(sys.argv[1:])
       File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
         verify=args.verify)
       File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 198, in build
         raise ValueError('No valid recipes found for input: {}'.format(recipe_paths_or_metadata))
     ValueError: No valid recipes found for input: ['/opt/recipe/meta.yaml']
     
     19:32:33 BIOCONDA ERROR BUILD FAILED recipes/plascope
     19:32:33 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
     19:32:33 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/plascope

I kept the image with `--keep-image` and was able to run `bash` in it with the same volumes mounted (copy pasting the command used by bioconda):

    $ docker run -i --net host --rm -v /tmp/tmpem2auuuy/build_script.bash:/opt/build_script.bash -v /tmp/miniconda/miniconda/conda-bld:/opt/host-conda-bld -v /home/mdubois/Code/bioconda-recipes/recipes/plascope:/opt/recipe -e CONDA_SHLVL=1 -e CONDA_EXE=/tmp/miniconda/miniconda/bin/conda -e LANG=fr_FR.UTF-8 -e CONDA_PYTHON_EXE=/tmp/miniconda/miniconda/bin/python -e CONDA_PROMPT_MODIFIER='(base)'  -e CONDA_DEFAULT_ENV=base -e CONDA_ROOT=/tmp/miniconda/miniconda -e CONDA_ALLOW_SOFTLINKS=false -e HOST_USER_ID=20000 tmp-bioconda-builder /bin/bash
    ### Inside the container:
    $ cd /opt
    $ ls
    build_script.bash
    conda
    docker
    host-conda-bld
    recipe
    rh
    $ ls recipe
    ls: cannot open directory recipe: Permission denied

I think it is linked to [this issue in conda](https://github.com/conda-forge/conda-smithy/issues/637). Using the `Z` option for mounting volumes works:

    $ docker run --net host --rm -v /tmp/tmp06myaxy2/build_script.bash:/opt/build_script.bash:Z -v /tmp/miniconda/miniconda/conda-bld:/opt/host-conda-bld:Z -v /home/mdubois/Code/bioconda-recipes/recipes/plascope:/opt/recipe:Z -e CONDA_SHLVL=1 -e CONDA_EXE=/tmp/miniconda/miniconda/bin/conda -e LANG=fr_FR.UTF-8 -e CONDA_PYTHON_EXE=/tmp/miniconda/miniconda/bin/python -e CONDA_PROMPT_MODIFIER='(base)'  -e CONDA_DEFAULT_ENV=base -e CONDA_ROOT=/tmp/miniconda/miniconda -e CONDA_ALLOW_SOFTLINKS=false -e HOST_USER_ID=20000 tmp-bioconda-builder /bin/bash /opt/build_script.bash

Setting SELinux to `Permissive` allowed me to build the package so it's not blocking and the solution probably lies in conda but, as mentioned in the bug, SELinux is a useful feature so we might pay attention to that. Also the doc should mention to set SELinux to `Permissive` for now.

**Comment by eslerm** [comment]
Have you tired running docker with `--selinux-enabled`?

`semanage` can be used to create new policies.

**Comment by duboism** [comment]
Docker was started as a service by my distribution (Fedora 27 at the time of this message but I have since upgrade to Fedora 28). As far as I can tell (tested on a fresh VM), `docker` runs with `--selinux-enabled`. I was not able to build on the VM.

On Fedora 28 and it works (`docker` is run with `--selinux-enabled` too).

**Comment by eslerm** [comment]
Are you running into problems when relabelling files with `:Z` (or `:z`)?

**Comment by bgruening** [comment]
Closing as there are no updates. Hope it works now for you all.
