### ISSUE TITLE
circleci build failed when PR, but successed locally

### ISSUE THREAD

**Issue by Nanguage** [bioconda/bioconda-recipes#9874]
Hello,
I am a bioconda novice. When I try to PR my recipe, I got some checking error.

#9873 

Because I have passed the local `circleci build` command. So, I checked the difference between locally and online build log. I found that, online circleci is try to build many other recipes which are not belong to my project. 

The head of online circleci build log:
```
02:10:11 BIOCONDA INFO Recipes newly unblacklisted:
frogs
perl-list-someutils/0.53
perl-term-app-roles
...
02:10:11 BIOCONDA INFO Recipes modified according to git: frogs perl-list-someutils/0.53 perl-term-app-roles perl-array-compare perl-module-extract-use/1.043 mirdeep2/2.0.0.8 perl-statistics-ttest perl-convert-binhex perl-b-hooks-endofscope/0.21 perl-html-element-extended perl-border-style perl-xml-twig perl-go-perl footprint perl-mime-tools perl-module-fromperlver/0.008002 perl-color-theme perl-class-load perl-git-wrapper-plus erds ngseqbasic perl-params-validate perl-extutils-cbuilder/0.280230 perl-xml-dom-xpath dlo-hic-tools dimspy/1.1.0 dimspy/1.0.0 perl-extutils-helpers perl-namespace-clean/0.27 perl-xml-dom perl-html-formatter perl-package-stash perl-params-validate/1.26 dimspy perl-file-path perl-ppi/1.236 perl-html-tree perl-bio-gff3 detonate perl-html-treebuilder-xpath perl-sql-statement
```

And the head of local circleci build log look like this:

```
06:50:59 BIOCONDA INFO Recipes newly unblacklisted:

06:50:59 BIOCONDA INFO Recipes modified according to git: dlo-hic-tools
```

**Comment by jpuritz** [comment]
You need to modify (removing `duo-hic-tools`), add, and commit the `build-fail-blacklist` file locally.

**Comment by Nanguage** [comment]
@jpuritz You mean I should remove this branch, then create a new and add other recipes to the `build-fail-blacklist` on my branch?

**Comment by jpuritz** [comment]
I'm sorry, I misread this.  I would try merging this branch with the master branch and trying the local tests again.

**Comment by mbargull** [comment]
@Nanguage, feel free to ping an appropriate team from https://github.com/orgs/bioconda/teams/ directly in a comment on a PR that's causing troubles. No need to open a separate issue -- that way we can directly see the relevant context and discuss right a the source of the problem :wink:.

**Comment by mbargull** [comment]
Hence, I'm going to close this issue in favor of the PR. And I, just like @jpuritz, also assume that updating the branch with `master` likely resolves that issue.
