### ISSUE TITLE
gcc 7.2 with conda-build 3; fix octopus recipe

### ISSUE THREAD

**Issue by chapmanb** [bioconda/bioconda-recipes#9904]
@bioconda/core 

I'm working on fixing the currently blacklisted octopus recipe and am not sure how to, or if we can, specify gcc 7.2 with the switch over to conda-build 3. There are some other discussion threads on recent gccs (#5297) but I'm not sure what the current status is with the switch over and what we currently recommend to do this for forward compatibility with conda-forge. octopus requires gcc 6.3 or greater and I previously had this working with the `gcc_linux-64` packages (https://github.com/bioconda/bioconda-recipes/pull/7502/files). Does anyone have any pointers or docs on the current approach to do this? Thanks much.

**Comment by druvus** [comment]
@mbargull and @johanneskoester gave the following advice in the gitter channel and it has been used successfully for the stacks 2.0 recipe. 

you can add a recipe/conda_build_config.yaml file with contents like:

```
c_compiler:
  - gcc      # [linux]
  - clang    # [osx]
cxx_compiler:
  - gxx      # [linux]
  - clangxx  # [osx]
```
which should give you the newer Anaconda compiler packages.

**Comment by bgruening** [comment]
Also have a look at the stacks recipe.

**Comment by chapmanb** [comment]
Andreas and Björn;
Thanks so much for the tips and pointer to the stacks recipe. This was exactly what I needed and I was able to get octopus built with this additional file. For anyone who comes across this thread, the octopus recipe is another example of how to use the latest compilers:

https://github.com/bioconda/bioconda-recipes/tree/master/recipes/octopus

Thank you again for all the help.
