### ISSUE TITLE
phyml not building

### ISSUE THREAD

**Issue by nickloman** [bioconda/bioconda-recipes#9926]
I can't install phyml any more, either previous known builds or just a fresh one.

Weirdly the recipe branch shows:
"Cannot retrieve the latest commit at this time."

https://github.com/bioconda/bioconda-recipes/tree/master/recipes/phyml

Any idea @johanneskoester  ?

**Comment by nickloman** [comment]
I bumped the build number but it didn't seem to help

**Comment by zachcp** [comment]
looks like its on the blacklist. https://github.com/bioconda/bioconda-recipes/blob/master/build-fail-blacklist#L1531-L1532

maybe toggle that in your PR/build

**Comment by colinbrislawn** [comment]
This appears to be working!
https://anaconda.org/bioconda/phyml/files 

I'll close this issue for now but feel free to reopen if you discover any issues.
