### ISSUE TITLE
Install DAS tool

### ISSUE THREAD

**Issue by SilasK** [bioconda/bioconda-recipes#9968]
Has anybody already started to make a recipie for DAS tool? 

https://github.com/cmks/DAS_Tool

**Comment by bgruening** [comment]
Not that I'm aware of, but this does not mean anything :)

**Comment by alienzj** [comment]
@SilasK Hello, thanks very much for the das_tool recipe.
Could you update numpy version in the das_tool's meta.yaml?

**Comment by SilasK** [comment]
Because the version in DASTool recipe is too old. Which version do you suggest?

**Comment by alienzj** [comment]
numpy >= 1.16.1

**Comment by PertuyF** [comment]
Saw this and just started a PR. Feel free to participate if required @SilasK.

**Comment by alienzj** [comment]
@PertuyF Thanks very much!
