### ISSUE TITLE
Package incomplete?

### ISSUE THREAD

**Issue by marchoeppner** [bioconda/bioconda-recipes#9980]
Hi,
just installed vcftools 0.1.15 and it seems to be missing all of the companion scripts, like vcf-concat, vcf-sort etc:

https://vcftools.github.io/perl_module.html

Is this known/intended?

Cheers,
Marc

**Comment by apeltzer** [comment]
Hm, the recipe just does what is mentioned in the installation section of the method:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/vcftools/build.sh

`make install` which should make the scripts available actually.

**Comment by marchoeppner** [comment]
Hi,

just installed 0.1.16 and the scripts are definitely not there, just "vcftools" under bin/

When building vcftools from scratch (https://github.com/vcftools/vcftools/releases/download/v0.1.15/vcftools-0.1.15.tar.gz):

./configure --prefix=/path/to/install
make
make install

ls /path/to/install/

```
ill-aa     fill-ref-md5  vcf-concat     vcf-convert       vcf-indel-stats  vcf-phased-join   vcf-sort    vcftools    vcf-validator
fill-an-ac  vcf-annotate  vcf-consensus  vcf-fix-newlines  vcf-isec         vcf-query         vcf-stats   vcf-to-tab
fill-fs     vcf-compare   vcf-contrast   vcf-fix-ploidy    vcf-merge        vcf-shuffle-cols  vcf-subset  vcf-tstv
```

**Comment by theandyb** [comment]
Based on the package descriptions, I think those scripts should be provided by the perl-vcftools-vcf package. That being said, even after having installed that package I am still not seeing the companion scripts (fill-aa, etc)

**Comment by apeltzer** [comment]
So if that's the case, I suppose its a bug?

**Comment by dpryan79** [comment]
@bioconda/core Should the old perl-vcftools-vcf packages should be removed. The version numbering system seems to have changed between the original @chapmanb repository to the more current vcftools/vcftools repository. This also caused some recipes (at least rad_haplotyper) to get added to the blacklist during the CB3 migration. As is, it's likely that one will always need to specify a version to get the most recent version of that package, since I don't foresee vcftools to hit a version higher than 0.953.

**Comment by deeptimittal12** [comment]
running conda install -c bioconda perl-vcftools-vcf=0.1.16 does not install all the vcftools perl scripts. vcf-convert is still missing. Does anyone have any updates about it? Thanks a lot.

**Comment by ekanun1995** [comment]
Yes

**Comment by deeptimittal12** [comment]
@ekanun1995 can you elaborate? thank you.

**Comment by deeptimittal12** [comment]
@dpryan79 Thanks for your reply. If I use conda install perl-vcftools-vcf command, it installs the latest version 0.953 but all the perl scripts are missing. 

As per the suggestions here, I tried to specify the version conda install -c bioconda perl-vcftools-vcf=0.1.16 but vcf-convert and some other perl scripts are still missing. 

I am not sure how to request this addition but as far as I know, adding vcf-convert in build.pl and meta.yaml should make this work.

**Comment by MikeWLloyd** [comment]
Just to update this. I think this issue can be closed. I ran `conda install -c bioconda perl-vcftools-vcf=0.1.16` and got `0.1.16-pl526_2` and that version includes vcf-convert. 

```
$ which vcf-convert
~/miniconda2/bin/vcf-convert
```

**Comment by dpryan79** [comment]
OK, if someone else runs into this please reopen.
