### ISSUE TITLE
Delly and htslib version

### ISSUE THREAD

**Issue by micknudsen** [bioconda/bioconda-recipes#9981]
I have noticed that `delly` cannot be installed alongside the newest version of `htslib`:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - delly=0.7.8 -> htslib=1.6
  - htslib=1.9
```

At first, I supposed that this meant that the exact version `htslib=1.6` was required, but `delly` installs without problems alongside `htslib=1.7`, too. I think it has to do with this piece of _magic_ in the `meta.yaml` file:

https://github.com/bioconda/bioconda-recipes/blob/aa1283bb1dbc9bc4c1fbb398ae1d96ce64816a8d/recipes/delly/meta.yaml#L30

Is the any reason why the requirement wouldn't just be e.g. `htslib>=1.6`?

**Comment by kyleabeauchamp** [comment]
CONDA_HTSLIB is deprecated and should be replaced as you mentioned.

**Comment by kyleabeauchamp** [comment]
I think?  Is that correct @bgruening ?  I noticed we still have the env matrix, but I think it's deprecated and could be deleted?  https://github.com/bioconda/bioconda-recipes/blob/master/scripts/env_matrix.yml#L5

**Comment by bgruening** [comment]
Yes, this file can be removed. We are using now global pinning from conda-forge and overwrite them here: https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/bioconda_utils-conda_build_config.yaml or if you include a similar file in your folder you can overwrite the settings locally.

**Comment by johanneskoester** [comment]
But don't do that unless there is a good reason ;-).

**Comment by bgruening** [comment]
Anything we can help? Can we close this issue?

**Comment by micknudsen** [comment]
I am just wondering why one still gets the version conflicts when trying to install delly alongside htslib. There are no limits on the htslib version in the delly meta.yaml file.

**Comment by bgruening** [comment]
The missing `{{CONDA_HTSLIB}}` does not mean we are not pinning against a specific htlib version. All bioconda packages are compiled against at least one very specific htslib version. Its just that this detail is not hidden and not visible in the recipe, but it still holds true.

**Comment by micknudsen** [comment]
@bgruening Thanks for clarifying. I am closing this issue, since it turned out not to be an issue at all 😃
